post_install() {
  for u in `users`; do
    yadcfg=/home/$u/.config/yad.conf
    [[ -f $yadcfg ]] || su -c "yad --timeout 1 --no-buttons --skip-taskbar --undecorated" $u
    sed -i "s/show_remain=false/show_remain=true/" $yadcfg
  done
  echo
  echo "To execute exiting command without entering password, run 'visudo' as root and add the following:"
  echo "%user ALL=(ALL) ALL, NOPASSWD: /sbin/shutdown, /usr/sbin/pm-suspend, /usr/sbin/pm-hibernate"
  echo
}
