--- Makefile	2012-05-09 01:04:23.676471560 +0200
+++ Makefile.patch	2012-05-09 01:04:00.383147046 +0200
@@ -33,7 +33,7 @@
 fragiso: fragiso.o util.o md5.o rpmhead.o cfile.o $(zlibbundled)
 
 _deltarpmmodule.so: readdeltarpm.o rpmhead.o util.o md5.o cfile.o $(zlibbundled)
-	for PY in python python3 ; do \
+	for PY in python2 python3 ; do \
 		if [ -x /usr/bin/$$PY-config ] && [ -x /usr/bin/$$PY ]; then \
 			PYVER=`$$PY -c 'from distutils import sysconfig ; print(sysconfig.get_python_version())'`; \
 			PYCFLAGS=`$$PY-config --cflags`; \
@@ -71,7 +71,7 @@
 	install -m 644 makedeltaiso.8 $(DESTDIR)$(mandir)/man8
 	install -m 644 applydeltaiso.8 $(DESTDIR)$(mandir)/man8
 	install -m 644 drpmsync.8 $(DESTDIR)$(mandir)/man8
-	for PY in python python3 ; do \
+	for PY in python2 python3 ; do \
 		if [ -x /usr/bin/$$PY ]; then \
                         PYLIB=`$$PY -c 'from distutils import sysconfig ; print(sysconfig.get_python_lib(1))'` ; \
 			PYVER=`$$PY -c 'from distutils import sysconfig ; print(sysconfig.get_python_version())'` ; \
