post_install() {
  ln -s /opt/firefox/firefox /usr/bin/firefox-non-australis-interface
  chmod +x /usr/bin/firefox-non-australis-interface  
  echo -e "To start Mozilla Firefox Non Australis - \e[31m/usr/bin/firefox-non-australis-interface \e[39m"
  echo -e "Creating a shortcut as the default in Firefox - \e[32mln -s /opt/firefox/firefox /usr/bin/firefox \e[39m"
}
post_remove() {
  rm -R /usr/bin/firefox-non-australis-interface
}