post_install()
{
if [ -L /usr/bin/myagent-im ] ; then rm /usr/bin/myagent-im ; fi
if [ -x /usr/local/bin/myagent-im ] ; then ln -s /usr/local/bin/myagent-im /usr/bin ; fi
}

post_upgrade()
{
if [ -L /usr/bin/myagent-im ] ; then rm /usr/bin/myagent-im ; fi
if [ -x /usr/local/bin/myagent-im ] ; then ln -s /usr/local/bin/myagent-im /usr/bin ; fi
}

pre_remove()
{
if [ -L /usr/bin/myagent-im ] ; then rm /usr/bin/myagent-im ; fi
}
