5c5
< BINDIR  = /usr/local/bin
---
> BINDIR  = /usr/local/bin/
7a8
> DESTDIR =
17,18c18,19
< 	install -m 755 --strip $(PROJECT) $(BINDIR)
< 	install -m 644 doc/$(PROJECT).html $(DOCDIR)
---
> 	install -D -m 755 --strip $(PROJECT) $(DESTDIR)$(BINDIR)$(PROJECT)
> 	install -D -m 644 doc/$(PROJECT).html $(DESTDIR)$(DOCDIR)$(PROJECT).html
