post_install() {
  fc-cache -fs
  mkfontscale usr/share/fonts/TTF
  mkfontdir usr/share/fonts/TTF
  echo "After install read example on http://gnome-look.org/content/show.php/CONKY-colors?content=92328"
  echo "conky-colors <options> will create conkyrc file in current directory"
}

post_upgrade() {
  fc-cache -fs
  mkfontscale usr/share/fonts/TTF
  mkfontdir usr/share/fonts/TTF
}

post_remove() {
  fc-cache -fs
  mkfontscale usr/share/fonts/TTF
  mkfontdir usr/share/fonts/TTF
}
