post_install() {
  if [ "$CARCH" = 'x86_64' ]; then
    nspluginwrapper -i /usr/lib32/mozilla/plugins/libflashplayer.so
  fi
}

post_remove() {
  if [ "$CARCH" = 'x86_64' ]; then
    nspluginwrapper -r /usr/lib32/mozilla/plugins/libflashplayer.so
  fi
}

post_update() {
  if [ "$CARCH" = 'x86_64' ]; then
    nspluginwrapper -u /usr/lib32/mozilla/plugins/libflashplayer.so
  fi
}

# vim:set ts=2 sw=2 et:
