post_install() {
  if [ -z "`getent group gearman`" ]; then
    groupadd -g 112 gearman
  fi
  if  [ -z "`getent passwd gearman`" ]; then
    useradd -u 112 -g gearman -c "Gearman" -d /dev/null -s /bin/false gearman
  fi
  touch /var/log/gearmand.log
  chown gearman:gearman /var/log/gearmand.log
  echo "Examples conf: http://gearman.org/index.php?id=manual:job_server"
}

post_upgrade() {
  post_install $1
}

post_remove() {
  userdel gearman
}
