post_install() {
  if [ -z "`getent group gearman`" ]; then
    groupadd -g 112 gearman &>/dev/null
  fi
  if  [ -z "`getent passwd gearman`" ]; then
    useradd -u 112 -g gearman -c "Gearman" -d /dev/null -s /bin/false gearman &> /dev/null
  fi
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  getent passwd gearman &>/dev/null && userdel gearman &> /dev/null
  getent group gearman &>/dev/null && groupdel gearman &> /dev/null
}

