#! /bin/bash

case "$1" in
	logout|quit|exit)
		#"systemctl exit" is no good because:
		#1. It still requires a (root) password
		#2. exit.target does not actually exist
		#So this uses the dbus method, which also requires a password
		MESSAGE="Enter password to logout:"
		METHOD="KillUser"
		ARGS="$UID 15"
		gksu -m "$MESSAGE" "gdbus call -y -d org.freedesktop.login1 -o /org/freedesktop/login1 -m org.freedesktop.login1.Manager.$METHOD $ARGS"
		exit
		#MESSAGE="Loging Out..."
		#METHOD="exit"
		#ICON="logout"
		#OK="Logout"
	;;
	suspend|standby|sleep)
		MESSAGE="Suspending..."
		METHOD="suspend"
		ICON="shutdown"
		OK="Suspend"
	;;
	hibernate)
		MESSAGE="Hibernating..."
		METHOD="hibernate"
		ICON="shutdown"
		OK="Hibernate"
	;;
	reboot|reset)
		MESSAGE="Rebooting..."
		METHOD="reboot"
		ICON="shutdown"
		OK="Reboot"
	;;
	shutdown|poweroff)
		MESSAGE="Powering Off..."
		METHOD="poweroff"
		ICON="shutdown"
		OK="Poweroff"
	;;
	*)
		exit
	;;
esac

# Zenity's OK and Cancel buttons are backward unless you read left to right...
[[ $(zenity --question --title=indicator-session-systemd --window-icon="/usr/share/icons/gnome/16x16/actions/gnome-$ICON.png" --text="$MESSAGE?\n(5 sec)" --ok-label Cancel --icon-name="gnome-$ICON" --cancel-label $OK --timeout=5; echo $?) -gt 0 ]] && systemctl $METHOD
