post_install()
{
	if ! grep -qs ^minbif: /etc/group
	then
		groupadd -r -g 67 minbif
	fi

	if ! grep -qs ^minbif: /etc/passwd
	then
		useradd -r -u 67 -g minbif \
		        -d /var/lib/minbif \
		        -s /bin/false -c minbif minbif
	fi

	systemd-tmpfiles --create minbif.conf
}

post_upgrade()
{
	post_install $1
}

post_remove()
{
	if grep -qs ^minbif: /etc/passwd
	then
		userdel minbif
	fi

	if grep -qs ^minbif: /etc/group
	then
		groupdel minbif
	fi
}
