#!/bin/bash
if [ "$(gconftool-2 -g /apps/metacity/general/theme 2>&1 | grep 'No value set for')" != "" ] && [ -d /usr/share/themes/Adwaita-Manjaro-dark/metacity-1/ ]; then
	gconftool-2 -s /apps/metacity/general/theme -t string Adwaita-Manjaro-dark
elif [ "$(gconftool-2 -g /apps/metacity/general/theme 2>&1 | grep 'No value set for')" != "" ]; then
	gconftool-2 -s /apps/metacity/general/theme -t string Adwaita
fi
if [ "$(gconftool-2 -g /apps/metacity/general/titlebar_uses_system_font 2>&1 | grep 'No value set for')" != "" ]; then
	gconftool-2 -s /apps/metacity/general/titlebar_uses_system_font -t bool true
fi
if [ "$(gconftool-2 -g /apps/metacity/general/button_layout 2>&1 | grep 'No value set for')" != "" ]; then
	gconftool-2 -s /apps/metacity/general/button_layout -t string ":minimize,maximize,close"
fi
