KERNEL_NAME=-ac100
KERNEL_VERSION=3.0.27-1-ac100

post_install () {
  depmod ${KERNEL_VERSION}
  mkinitcpio -p linux-ac100 -k ${KERNEL_VERSION}
  abootimg --create /boot/ac100.img -f /boot/ac100/bootimg.cfg -k /boot/ac100/zImage -r /boot/ac100/initrd.img
  #dd if=/boot/ac100.img of=/dev/mmcblk0p2
  echo "bootimage placed in /boot/ac100.img, use 'dd' for write it to boot partition (be careful!)"
}

post_upgrade(){
  post_install
}
