post_install() {
    echo ""
    echo "-------------------------------------------------------------"
    echo " The top level package name was changed from 'pagination' to"
    echo " 'linaro-django-pagination'."
    echo ""
    echo " more info at project's page and here:"
    echo " http://packages.python.org/linaro-django-pagination/"
    echo "-------------------------------------------------------------"
    echo ""
}

post_upgrade() {
    post_install
}
