.TH "kardsgt" "6" "18 Jul 2008" "John Schneiderman" "KardsGT: You are now Free to play"

.SH NAME
KardsGT \- A card game suite.

.SH SYNOPSIS
.B kardsgt
[
.I options
] ...

.SH DESCRIPTION
.B kardsgt
is a card game programme that has many of your favourite card games. Each game
comes with an exhaustive manual on how to play. In addition to the many
wonderful games, we also have amazing characters to play against. Each character
has their own history and sense of play, giving you a fun challenge as you spend
your time.
.PP
KardsGT has a ranking system for both the human players and the computer
players. The human players rank is based on how many games they win over time.
Computer players have their ranks based on the skill level approximation of
their game play strategies.
.PP
KardsGT uses a simple interface for playing the games. To play a card, simply
drag the card you want to play to the place you need to play your card, or
double-click on the card you want to play. Additionally you can right click and
sort your cards in a predefined mannor. You can sort by rank, by suit, or by
random. If this doesn't fit with your needs you can click and drag your cards
into the position you want them to be in your hand.
.PP
The image of the players indicate not just their mood but also facilitates
communication with you. For example, if it is a player's turn the letter "T"
appears in the upper-left of the players picture. If it is not the player's turn
and the player is the dealer then the letter "D" is displayed, else the player's
skill ranking number is displayed instead.
.PP
Some games have buttons in them, clicking on them will activate the action they
describe. For example, spades has a contract button, this button will tell you
how many tricks the team have contracted. In the centre of the interface you'll
see the playing area. This playing area is where you'll drag the card you wish
to play. The play area also allows you to see the last cards played until the
next card is played. KardsGT comes with a few standard images, the image for you
and the images for each of the cards. If you would like to change any of the
images you can by selecting the configure option under the settings menu. From
there you can point to a directory that has card images (currently only in an
xpm file format), the image used for the back of the card, or even use the
default image for a female player or select an image of your choosing.

.SH "EXIT STATUS"
The game returns 0 on a success. All other values are indicate failure.

.SH OPTIONS
.B h
\- gives a limited overview of the available options.
.PP
.B v
\- gives the version information about KardsGT.
.PP
.B l
.I filename
\- loads the previously saved game as specified by filename.

.SH GAMES AVAILABLE
Crazy Eights, Cribbage, Euchre, Hearts, Old Maid, Spades, War

.SH FILES
/usr/bin/kardsgt
.PP
/usr/share/doc/kardsgt

.SH VERSION
0.7.0.

.SH BUGS
Please use the bug form at our website at
.B http://kardsgt.nongnu.org
.PP
Follow the link to the development site, and you'll be able to submit a bug
report from there.

.SH COPYRIGHT

Copyright (C) 2006 - 2008  John Schneiderman
.PP
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
