--- Makefile.orig	2013-07-08 02:04:00.273298343 +0000
+++ Makefile	2013-07-08 02:04:39.146629710 +0000
@@ -1,8 +1,8 @@
-PREFIX?=/opt/circonus
+PREFIX?=/usr
-MAN=$(PREFIX)/man/man8
+MAN=$(PREFIX)/share/man/man8
 SBIN=$(PREFIX)/sbin
-CONF=$(PREFIX)/etc/node-agent.d
-MODULES=$(PREFIX)/etc/node_modules
+CONF=/etc/node-agent.d
+MODULES=$(PREFIX)/share/nad/node_modules
 MAKE?=make
 
 all:
