# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Babken Vardanyan <483ken@gmail.com>

_gemname=rkelly-remix
pkgname=ruby1.9-$_gemname
pkgver=0.0.6
pkgrel=1
pkgdesc='RKelly Remix is a fork of the RKelly[https://github.com/tenderlove/rkelly] JavaScript parser.'
arch=(any)
url='https://github.com/nene/rkelly-remix'
license=(MIT)
depends=(ruby1.9)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('fba132c8e8c20b63b1d68f39ae10aa676dd5db1d')

package() {
  local _gemdir="$(ruby-1.9 -e'puts Gem.default_dir')"
  gem-1.9 install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
