# Contributor: jdj <djin.joo@gmail.com>

post_install() {
  echo Executing mktexlsr
  mktexlsr
  echo Executing updmap-sys, map=kotex-base
  updmap-sys --enable Map=kotex-base.map
  echo Executing updmap-sys, map=kotex-extra
  updmap-sys --enable Map=kotex-extra.map
  echo Executing updmap-sys, map=kotex-mkdkor
  updmap-sys --enable Map=kotex-midkor.map
}

post_upgrade() {
	post_install
}

post_remove() {
	mktexlsr
	updmap-sys
}

op=$1
shift

$op $*
