post_upgrade() {
	echo "The files .livestreamer-cursesrc and .livestreamer-curses.db"
	echo "must be moved to the following directories:"
	echo ".livestreamer-cursesrc must be moved to"
	echo '$XDG_CONFIG_HOME/livestreamer-curses/livestreamer-cursesrc'
	echo "and .livestreamer-curses.db must be moved to"
	echo '$XDG_DATA_HOME/livestreamer-curses/livestreamer-curses.db'
	echo "More information under:"
	echo "https://github.com/gapato/livestreamer-curses/issues/8"
}
