#pkgname=gnome-chemistry-utils

post_install() {
  gconfpkg --install gnome-chemistry-utils
  update-desktop-database -q
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  /usr/bin/update-mime-database /usr/share/mime > /dev/null 2>&1

  echo " "
  echo "Note : When you upgrade your goffice package by one major"
  echo "version number (i.e. from 0.6.x to 0.8.x), you will have"
  echo "to recompile gcu if you want some programs such as"
  echo "gchempaint to remain functional."
  echo " "
}

post_upgrade() {
  gconfpkg --install gnome-chemistry-utils
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  /usr/bin/update-mime-database /usr/share/mime > /dev/null 2>&1

  echo " "
  echo "Note : When you upgrade your goffice package by one major"
  echo "version number (i.e. from 0.6.x to 0.8.x), you will have"
  echo "to recompile gcu if you want some programs such as"
  echo "gchempaint to remain functional."
  echo " "

}

pre_remove() {
  gconfpkg --uninstall gnome-chemistry-utils
}

post_remove() {
  update-desktop-database -q
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  /usr/bin/update-mime-database /usr/share/mime > /dev/null 2>&1

}
