pre_install() {
  cp /usr/share/unity-2d/launcher/Launcher.qml /usr/share/unity-2d/launcher/Launcher_backup.qml
}

post_install() {
  cp $srcdir/Unity\ Gnome\ Installer/unity-2d-launcher.desktop ~/.config/autostart/unity-2d-launcher.desktop
  killall unity-2d-launcher
}

post_upgrade() {
  post_install
}

post_remove() {
  mv /usr/share/unity-2d/launcher/Launcher_backup.qml /usr/share/unity-2d/launcher/Launcher.qml
  rm ~/.config/autostart/unity-2d-launcher.desktop
  killall unity-2d-launcher
}
