--- makefile	2005-10-03 00:46:56.000000000 +0200
+++ makefile.new	2007-09-05 15:41:24.000000000 +0200
@@ -1,8 +1,8 @@
 CC = gcc
 
 ####### choose the line that makes the binary faster on your machine
-# CFLAGS = -O3 -Wall -fomit-frame-pointer -funroll-loops
-CFLAGS = -O0 -Wall -Werror  -fomit-frame-pointer -march=k8 -std=c99 -D_GNU_SOURCE
+CFLAGS = -O3 -Wall -fomit-frame-pointer -funroll-loops
+# CFLAGS = -O0 -Wall -Werror  -fomit-frame-pointer -march=k8 -std=c99 -D_GNU_SOURCE
 
 ####### debug/tuning options for developers
 # CFLAGS = -O -Wall -g3 -static
