post_install() {

cat << EOF

To enable the privoxy service at boot, run the following command as root:
systemctl enable privoxy.service

To manually start the service (without having to reboot), run the following command as root:
systemctl start privoxy.service

EOF
post_upgrade

}

post_upgrade() {

cat << EOF

Before removing the privoxy service, run the following commands as root:

systemctl stop privoxy.service
systemctl disable privoxy.service

EOF

}
