    
    post_install(){
    
    echo ":::::::::::::::::::::::::::::::::::::"
    
    echo "Se necesitan algunos permisos."
    
    sudo chown -R $USER /opt/radit
    sudo groupadd radit
    sudo gpasswd -a $USER  radit
    sudo chgrp -R radit /opt/radit
    sudo chmod -R g+w /opt/radit 
    
    echo ":::::::::::::::::::::::::::::::::::::"
   
    echo "Gracias por instalar Radit!"

    }
    
    
    post_remove() {
    rm -Rf /opt/radit/
    }