.T PXE 8 "2006-06-30" "1.4.2" "PXE daemon"

.SH NAME
pxe \- a free PXE daemon

.SH SYNOPSIS
.B pxe

.SH DESCRIPTION
.B PXE
is a specification to boot PCs from the net. Apart from BOOTP or DHCP for
acquiring an IP address and TFTP for transferring files, it requires a PXE
daemon on the server which implements the boot loader selection.

.SH OPTIONS
.B PXE
has no options, but a configuration file in /etc/pxe.conf.

.SH AUTHOR
PXE was written by Tim Hurman <kano@kano.org.uk>.
.PP
This manual page was written by Jens Schmalzing <jensen@debian.org>, for the
Debian project (but may be used by others).
