post_install() {
    echo
    echo -n ">>> Creating i2p system user and group... "
    /usr/sbin/useradd --system --user-group --home /opt/i2p i2p 2>/dev/null || true
    chown -R i2p:i2p /opt/i2p
    chmod -R 750 /opt/i2p
    echo "done"
}

post_upgrade() {
    chown -R i2p:i2p /opt/i2p
    chmod -R 750 /opt/i2p
}

pre_remove() {
    echo
    echo -n ">>> Removing i2p system user... "
    /usr/sbin/userdel i2p
    echo "done"
}
