post_install() {
    getent passwd i2p &>/dev/null || {
        echo -n ">>> Creating i2p system user... "
        /usr/sbin/useradd --system --user-group --home /opt/i2p i2p
        echo "done"
    }
    chown i2p:i2p /run/i2p
    chown -R i2p:i2p /opt/i2p
}

post_upgrade() {
    #if [[ "$2" = old_version && "$1" = new_version ]]; then; fi
    chown i2p:i2p /run/i2p
    chown -R i2p:i2p /opt/i2p
}

pre_remove() {
    getent passwd i2p &>/dev/null && {
        echo -n ">>> Removing i2p system user... "
        /usr/sbin/userdel i2p
        echo "done"
    }
}
