post_install() {
    echo
    echo -n ">>> Creating i2p system user... "
    getent passwd i2p &>/dev/null ||
        /usr/sbin/useradd --system --user-group --home /opt/i2p i2p
    chown -R i2p:i2p /opt/i2p
    echo "done"
    echo
}

post_upgrade() {
    chown -R i2p:i2p /opt/i2p
    systemctl --system daemon-reload
}

pre_remove() {
    echo
    echo -n ">>> Removing i2p system user... "
    getent passwd i2p &>/dev/null &&
        /usr/sbin/userdel i2p
    echo "done"
    echo
}
