post_install() {
  echo
  echo Unfortunately, the GeoExpress command line utilities are unable to find their
  echo libraries and data files in the PATH. You will need to set two variables,
  echo GDAL_DATA and PROJSO, for GeoExpress to work. Execute the following commands
  echo and maybe add them to a startup script:
  echo
  echo export GDAL_DATA=/usr/share/geoexpress
  echo export PROJSO=/usr/lib
  echo
}

post_upgrade() {
  post_install $1
}

post_remove() {
  post_install $1
}

