post_install()
{
	/opt/brother/Printers/hl3170cdw/inf/setupPrintcapij hl3170cdw -i  
	if [ -e /etc/rc.d/lprng ]; then
	/etc/rc.d/lprng restart
	elif [ -e /etc/rc.d/lpd ]; then
	/etc/rc.d/lpd restart
	fi
	chmod 755 /opt/brother/Printers/hl3170cdw/lpd
	chmod 755 /opt/brother/Printers/hl3170cdw/inf
	chmod 755 /opt/brother/Printers/hl3170cdw/
	chmod 755 /opt/brother/Printers/hl3170cdw/
	chmod 755 /opt/brother/Printers
	chmod 755 /opt/brother/Printers
	chmod 755 /opt/brother
	chmod 755 /opt/brother
}

post_remove()
{
	if [ -e /etc/rc.d/lprng ]; then
		/etc/rc.d/lprng restart
	elif [ -e /etc/rc.d/lpd ]; then
		/etc/rc.d/lpd restart
	fi
	mkdir -p /opt/
}

pre_remove()
{
	/opt/brother/Printers/hl3170cdw/inf/setupPrintcapij hl3170cdw -e
}
