# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Babken Vardanyan <483ken@gmail.com>

_gemname=pg
pkgname=ruby1.9-$_gemname
pkgver=0.17.1
pkgrel=1
pkgdesc='Pg is the Ruby interface to the {PostgreSQL RDBMS}[http://www.postgresql.org/]'
arch=(i686 x86_64)
url='https://bitbucket.org/ged/ruby-pg'
license=(BSD Ruby GPL)
depends=(ruby1.9)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('2f3c2625f2bb07157647870af97007014e2191fb')

package() {
  local _gemdir="$(ruby-1.9 -e'puts Gem.default_dir')"
  gem-1.9 install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
