#!/bin/sh

CP="/usr/share/java/neo4j/*:/usr/share/java/neo4j/system/*:/usr/share/java/neo4j/plugins/*"
CP="$CP:/usr/share/java/commons-io/commons-io.jar:/usr/share/java/commons-logging/commons-logging.jar"
CP="$CP:/usr/share/java/commons-collections/commons-collections.jar"
CP="$CP:/usr/share/java/antlr2.jar"
. /usr/share/java/slf4j/setClasspath.sh
CP="$CP:$SLF4J_API:$SLF4J_JDK14:$JCL_OVER_SLF4J:$LOG4J_OVER_SLF4J"

exec "$JAVA_HOME/bin/java" -cp "$CP" -Dapp.name="neo4j-shell" org.neo4j.shell.StartClient "$@"
