post_install() {
    echo "Install Hints:"
    echo "---------------------"
    echo "==> Ensure that fuse module is loaded"
    echo "==> Any user with x2gopgwrapper root access can use the system:"
    echo "    %users ALL=(ALL) NOPASSWD: /usr/bin/x2gopgwrapper"
    echo "More documentation can be found on the wiki"
	mkdir -p /var/db/x2go
	/usr/lib/x2go/x2gosqlite.sh
    /bin/true
}

post_upgrade() {
    /bin/true
}
