post_install() {
	post_upgrade
	print_info
}

post_upgrade() {
	clean_plugins
	ajenti-pkg upgrade
}

pre_remove() {
	rc.d stop ajenti || return 1
}

post_remove() {
	clean_ajenti
}

clean_plugins() {
	rm -rf /var/lib/ajenti/plugins/*
}

clean_ajenti() {
	rm -rf /var/lib/ajenti
}

print_info() {
	/bin/cat << EOF
==> Run "rc.d start ajenti" to start Ajenti daemon
==> Open http://127.0.0.1:8000/ to setup and use Ajenti
EOF
}
