# Generated by gem2arch
# Maintainer: LeeF

_gemname=i18n
pkgname=ruby-enterprise-i18n-040
pkgver=0.4.2
pkgrel=0
pkgdesc="New wave Internationalization support for Ruby"
arch=('i686' 'x86_64')
url="http://github.com/svenfuchs/i18n"
license=('MIT')
depends=('ruby-enterprise')
makedepends=('ruby-enterprise')
provides=('ruby-enterprise-i18n')
source=(http://gems.rubyforge.org/gems/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
md5sums=('be9b3a47b16d0bf29256ff55d6babe09')

build() {
  cd $srcdir
  local _gemdir=`ruby -rubygems -e'puts Gem.default_dir'`
  gem install --ignore-dependencies --no-rdoc --no-ri -i "$pkgdir$_gemdir" $_gemname-$pkgver.gem
}
