post_install() {
    name='teamcity-agent'
    
    echo "Creating user and group $name..."    
    getent group "$name" &>/dev/null || groupadd -r "$name" >/dev/null
    getent passwd "$name" &>/dev/null || useradd -r -g "$name" -d "/var/lib/$name" -s /bin/bash -G "$name" "$name" >/dev/null
    chown -R "$name:$name" "/opt/$name"
    chown -R "$name:$name" "/var/lib/$name"

    echo 
    echo "Make sure /usr/lib/jvm/default-java symlinks to your prefered Java environment."
    echo "If you want to use a different Java, set it in /etc/conf.d/$name"
    echo 
    echo "You have to tune your agent config before you can run it. Check /opt/$name/conf."
    echo "Check docs: http://confluence.jetbrains.com/display/TCD7/Setting+up+and+Running+Additional+Build+Agents#SettingupandRunningAdditionalBuildAgents-InstallingviaZIPFile"
    echo
    echo "To start your agent:"
    echo "  systemctl start $name"
}

post_upgrade() {
    echo "Make sure /usr/lib/jvm/default-java symlinks to your prefered Java environment."
    echo "If you want to use a different Java, set it in /etc/conf.d/teamcity"
}

post_remove() {
    name='teamcity-agent'
    echo "Removing user and group $name..."

    getent passwd "$name" &>/dev/null && userdel "$name" >/dev/null
    getent group "$name" &>/dev/null && groupdel "$name" >/dev/null
}
