post_install() {
  /usr/bin/printf '----------------------------------------------------\n'
  /usr/bin/printf '     Comodo has been installed to /opt/COMODO.\n'
  /usr/bin/printf ' This directory will be added to your path when you\n'
  /usr/bin/printf ' next log in (assuming you source /etc/profile.d/*)\n'
  /usr/bin/printf ' Run /opt/COMODO/post_setup.sh as root to configure\n'
  /usr/bin/printf '                 this application\n'
  /usr/bin/printf '----------------------------------------------------\n'
}
