post_install() {
    echo "==> "
    echo "==> You need to extract the mouse.lab file from the Windows binary zip"
	echo "==> and place it with your Grim Fandango datafiles:"
	echo "==> http://graphics.berkeley.edu/~tpfaff/data/grim_mouse_0_1.zip"
	echo "==> Source: http://forums.residualvm.org/viewtopic.php?p=3040#3040"
	echo "==> "
	echo "==> Remember that this build of ResidualVM is not supported by the ResidualVM developers."
	echo "==> "
}


op=$1
shift

$op $*
