--- a/Makefile
+++ b/Makefile
@@ -120,8 +120,9 @@ MAKE_DPARSER = ./make_dparser
 
 EXECUTABLES = make_dparser
 LIBRARIES = $(LIBMKDPARSE) $(LIBDPARSE)
-INSTALL_LIBRARIES = $(LIBDPARSE)
+INSTALL_LIBRARIES = $(LIBDPARSE) $(LIBMKDPARSE)
 INCLUDES = dparse.h dparse_tables.h dsymtab.h dparse_tree.h
+MANPAGE_PREFIX = $(PREFIX)/share/man
 MANPAGES = make_dparser.1
 
 EXECS = $(EXECUTABLES) sample_parser test_parser
@@ -150,14 +151,14 @@ install:
 	cp -f $(INCLUDES) $(PREFIX)/include
 	mkdir -p $(PREFIX)/lib
 	cp -f $(INSTALL_LIBRARIES) $(PREFIX)/lib
-	mkdir -p $(PREFIX)/man/man1
-	cp -f $(MANPAGES) $(PREFIX)/man/man1
+	mkdir -p $(MANPAGE_PREFIX)/man1
+	cp -f $(MANPAGES) $(MANPAGE_PREFIX)/man1
 
 deinstall:
 	rm $(EXECUTABLES:%=$(PREFIX)/bin/%)
 	rm $(INCLUDES:%=$(PREFIX)/include/%)
 	rm $(INSTALL_LIBRARIES:%=$(PREFIX)/lib/%)
-	rm $(MANPAGES:%=$(PREFIX)/man/man1/%)
+	rm $(MANPAGES:%=$(MANPAGE_PREFIX)/man1/%)
 
 make_dparser: $(MAKE_PARSER_OBJS) $(LIBRARIES)
 	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^ version.c $(LIBS) 
