post_install() {
	echo "You have to change some configuration to use Google Authenticator."
	echo "You can find more information on how to install and use it on"
	echo "http://julianbrost.bitbucket.org/archlinux/google-authenticator-libpam/"
}

post_remove() {
	echo "Remember to undo the configuration changes. For more information, see"
	echo "http://julianbrost.bitbucket.org/archlinux/google-authenticator-libpam/"
}
