diff -r a680ec2a1fc9 libpam/Makefile
--- a/libpam/Makefile	Mon Mar 14 16:35:10 2011 -0700
+++ b/libpam/Makefile	Thu Mar 17 22:47:05 2011 +0100
@@ -46,14 +46,13 @@
 	$(RM) *.o *.so google-authenticator pam_google_authenticator_unittest
 
 google-authenticator: google-authenticator.o base32.o hmac.o sha1.o
-	$(CC) -g $(LDFLAGS) $(shell [ -f /usr/lib/libdl.so ] && echo " -ldl") \
-	      -o $@ $+
+	$(CC) -g $(LDFLAGS)                                                   \
+	      -o $@ $+ $(shell [ -f /usr/lib/libdl.so ] && echo " -ldl")
 
-pam_google_authenticator_unittest: pam_google_authenticator_unittest.o        \
+pam_google_authenticator_unittest: pam_google_authenticator_unittest.o    \
                                    base32.o hmac.o sha1.o
 	$(CC) -g $(LDFLAGS) -rdynamic -lc                                     \
-              $(shell [ -f /usr/lib/libdl.so ] && echo " -ldl")               \
-              -o $@ $+
+              -o $@ $+ $(shell [ -f /usr/lib/libdl.so ] && echo " -ldl")
 
 pam_google_authenticator.so: base32.o hmac.o sha1.o
 pam_google_authenticator_testing.so: base32.o hmac.o sha1.o
