diff -r 870f9c0eed8f libpam/Makefile
--- a/libpam/Makefile	Sun Jul 24 14:05:20 2011 -0700
+++ b/libpam/Makefile	Mon Jul 25 20:24:12 2011 +0200
@@ -56,18 +56,18 @@
 	               pam_google_authenticator_unittest
 
 google-authenticator: google-authenticator.o base32.o hmac.o sha1.o
-	$(CC) -g $(DEF_LDFLAGS) $(shell [ -f /usr/lib/libdl.so ] &&           \
-	      echo " -ldl") -o $@ $+
+	$(CC) -g $(DEF_LDFLAGS) -o $@ $+                                      \
+		$(shell [ -f /usr/lib/libdl.so ] && echo " -ldl")
 
 demo: demo.o pam_google_authenticator_demo.o base32.o hmac.o sha1.o
-	$(CC) -g $(DEF_LDFLAGS) -rdynamic                                     \
-	      $(shell [ -f /usr/lib/libdl.so ] && echo " -ldl") -o $@ $+
+	$(CC) -g $(DEF_LDFLAGS) -rdynamic -o $@ $+                            \
+	      $(shell [ -f /usr/lib/libdl.so ] && echo " -ldl")
 
-pam_google_authenticator_unittest: pam_google_authenticator_unittest.o        \
+pam_google_authenticator_unittest: pam_google_authenticator_unittest.o    \
                                    base32.o hmac.o sha1.o
-	$(CC) -g $(DEF_LDFLAGS) -rdynamic -lc                                 \
-              $(shell [ -f /usr/lib/libdl.so ] && echo " -ldl")               \
-              -o $@ $+
+	$(CC) -g $(DEF_LDFLAGS) -rdynamic -lc -o $@ $+                        \
+		$(shell [ -f /usr/lib/libdl.so ] && echo " -ldl")
+              
 
 pam_google_authenticator.so: base32.o hmac.o sha1.o
 pam_google_authenticator_testing.so: base32.o hmac.o sha1.o
