diff -r 7223591fd2dd libpam/Makefile
--- a/libpam/Makefile	Mon Apr 18 16:50:52 2011 +0100
+++ b/libpam/Makefile	Thu Apr 21 17:13:23 2011 +0200
@@ -47,18 +47,17 @@
 	               pam_google_authenticator_unittest
 
 google-authenticator: google-authenticator.o base32.o hmac.o sha1.o
-	$(CC) -g $(LDFLAGS) $(shell [ -f /usr/lib/libdl.so ] && echo " -ldl") \
-	      -o $@ $+
+	$(CC) -g $(LDFLAGS) -o $@ $+                                          \
+	$(shell [ -f /usr/lib/libdl.so ] && echo " -ldl")
 
 demo: demo.o pam_google_authenticator_demo.o base32.o hmac.o sha1.o
 	$(CC) -g $(LDFLAGS) -rdynamic                                         \
-	      $(shell [ -f /usr/lib/libdl.so ] && echo " -ldl") -o $@ $+
+	      -o $@ $+ $(shell [ -f /usr/lib/libdl.so ] && echo " -ldl")
 
-pam_google_authenticator_unittest: pam_google_authenticator_unittest.o        \
+pam_google_authenticator_unittest: pam_google_authenticator_unittest.o    \
                                    base32.o hmac.o sha1.o
-	$(CC) -g $(LDFLAGS) -rdynamic -lc                                     \
-              $(shell [ -f /usr/lib/libdl.so ] && echo " -ldl")               \
-              -o $@ $+
+	$(CC) -g $(LDFLAGS) -rdynamic -lc -o $@ $+                            \
+              $(shell [ -f /usr/lib/libdl.so ] && echo " -ldl")
 
 pam_google_authenticator.so: base32.o hmac.o sha1.o
 pam_google_authenticator_testing.so: base32.o hmac.o sha1.o
