post_install() {
	cat <<-'EOF'

		In order to use this theme you need to edit ~/.gtkrc-2.0 file:
		  gtk-theme-name="kde44-oxygen-molecule"
		  gtk-icon-theme-name="oxygen"
		  gtk-font-name="DejaVu Sans 9"

		In KDE you can specify Oxygen-Molecule theme by going to 'System Settings
		-> Appearance -> Colors' and selecting the Oxygen-Molecule.
		
		Also, to make sure your GTK apps use only the Oxygen Molecule color scheme,
		go to 'System Settings -> Appearance -> Colors -> Options' and uncheck the
		'Apply colors to non-KDE4 applications' option.

	EOF
}

post_upgrade() {
	post_install
}
