--- ./Makefile.orig	2010-06-24 14:38:40.000000000 +0200
+++ ./Makefile	2010-06-24 15:27:54.861691866 +0200
@@ -4,9 +4,9 @@
 		-shared                \
                 -fPIC
 
-DEPENDENCY_CFLAGS = `pkg-config --cflags libxul libxul-unstable gnome-keyring-1`
+DEPENDENCY_CFLAGS = `pkg-config --cflags libxul gnome-keyring-1`
 GNOME_LDFLAGS = `pkg-config --libs gnome-keyring-1`
-XUL_LDFLAGS = `pkg-config --libs libxul libxul-unstable`
+XUL_LDFLAGS = `pkg-config --libs libxul `
 VERSION = 0.3
 FILES = GnomeKeyring.cpp 
 
