3c3
< CFLAGS = -Wall -DIN_BUILDING_LIBIRC @CFLAGS@
---
> CFLAGS = -fPIC -Wall -DIN_BUILDING_LIBIRC @CFLAGS@
7c7
< 
---
> DESTDIR+=
13c13
< lib:	libircclient.a
---
> lib:	libircclient.a libircclient.so
16,21c16,22
< 	-mkdir @prefix@/include
< 	-mkdir @prefix@/lib
< 	cp ../include/libircclient.h @prefix@/include/libircclient.h
< 	cp ../include/libirc_errors.h @prefix@/include/libirc_errors.h
< 	cp ../include/libirc_events.h  @prefix@/include/libirc_events.h 
< 	cp libirc.a @prefix@/include/lib/libirc.a
---
> 	mkdir -p $(DESTDIR)/usr/{lib,include/libircclient}
> 	mkdir -p $(DESTDIR)/usr/share/{man,{doc,}/libircclient}
> 	cp libircclient.a libircclient.so  $(DESTDIR)/usr/lib
> 	cp ../include/libirc*.h  $(DESTDIR)/usr/include/libircclient
> 	cp -a ../doc/{html,rfc1459.txt} $(DESTDIR)/usr/share/doc/libircclient
> 	cp -a ../examples $(DESTDIR)/usr/share/libircclient
> 	cp -a ../doc/man/man3 $(DESTDIR)/usr/share/man
27a29,31
> 
> libircclient.so: $(OBJS)
> 	$(CC) -shared -Wl $(OBJS) -o libircclient.so
