post_install() {
     echo " "
     echo "When activtools is installed, activinspire needs to be killed before it can restart."
     echo "Therefore, a second launcher to restart activinspire is created (inspire-restart)."
     echo " "
     echo "If you want to toggle calibration via hovering the activboard hotspot, run activmgr."
     echo "If you just want to calibrate, run activcalibrate."
     echo "In both cases, activcalibrate has to be closed by Alt+F4 or get killed after the last calibration-point."
}
