## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
    # warn 2.4.x users  about conf file change
    if [[ $(vercmp $2 2.5.0) -lt 0 ]]; then
    echo "
    Please note that pacaur $1 now support XDG standard properly
    and that the main configuration file has been moved to
    /etc/xdg/pacaur/pacaur.conf

    Please move your /etc/pacaur.conf.pacsave to this new location.
    "
    fi
}
