post_install() {
  /bin/ln -sf /usr/lib/acml/gfortran/libacml{,_mp}{.a,.so} /usr/lib
  /bin/ln -sf /usr/lib/acml/libcblas.a /usr/lib
}

post_upgrade() {
  /bin/ln -sf /usr/lib/acml/gfortran/libacml{,_mp}{.a,.so} /usr/lib
  /bin/ln -sf /usr/lib/acml/libcblas.a /usr/lib
}

pre_remove() {
  rm /usr/lib/libacml.a  
  rm /usr/lib/libacml.so  
  rm /usr/lib/libacml_mp.a  
  rm /usr/lib/libacml_mp.so  
  rm /usr/lib/libcblas.a
}