# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Babken Vardanyan <483ken@gmail.com>

_gemname=rdoc
pkgname=ruby1.9-$_gemname
pkgver=3.12.2
pkgrel=1
pkgdesc='RDoc produces HTML and command-line documentation for Ruby projects'
arch=(any)
url='http://docs.seattlerb.org/rdoc'
license=()
depends=(ruby1.9 ruby1.9-json)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('687cd1bc56c2ad79fd9e2e3854d0a6db575e2aa2')

package() {
  local _gemdir="$(ruby-1.9 -e'puts Gem.default_dir')"
  gem-1.9 install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE.rdoc" "$pkgdir/usr/share/licenses/$pkgname/LICENSE.rdoc"
}
