# Maintainer: Moritz Fischer <moritz.fischer@student.kit.edu>
pkgname=gnuradio-uhd-git
pkgver=20110322
pkgrel=1
pkgdesc="free software development toolkit that provides the signal processing runtime and processing blocks to implement software radios using readily-available, low-cost external RF hardware and commodity processors"
arch=('i686' 'x86_64')
license=('GPL')
depends=('fftw' 'python-numpy' 'boost' 'cppunit' 'swig' 'gsl' 'blas' 'guile' 'uhd')
makedepends=('git')
optdepends=('wxpython: gr-wxgui' 'python-cheetah' 'python-lxml' 'qwtplot3d: gr-qtgui' 'sdcc: firmware and all the parts needing USRP' 'doxygen: docs autogenerated documentation' 'pxml: grc', 'pygtk: grc' 'python-lxml: grc')
provides=('gnuradio')
url="http://gnuradio.org"
source=()
md5sums=()
conflicts=(gnuradio-git)

_gitroot=http://gnuradio.org/git/gnuradio.git
_gitname=gnuradio

build() {
  cd ${srcdir}

  if [ -d $_gitname ]; then
    (cd $_gitname && git clean -x -d -f && git pull origin)
    msg "Updated the local files."
  else
    git clone $_gitroot
		msg "GIT checkout done or server timeout"
  fi

  cd $_gitname
  msg "Replacing filenames to use python2."
  sed -i -e "s|#![ ]*/usr/bin/env python$|#!/usr/bin/env python2|" $(find $srcdir -name '*.py')
	export PYTHON=python2
  msg "Starting build."
	git clean -x -f -d
  ./bootstrap
	export PKG_CONFIG_PATH=/usr/lib64/pkgconfig
  ./configure --prefix=/usr --with-boost-libdir=/usr/lib --disable-gr-uhd \
							--with-lv_arch="generic mmx sse sse2 sse3 sse3 sse4_1 sse4_2"
						  # if on AMD sse_4_a might be desireable
  make || return 1
  make check || return 1
  make DESTDIR=${pkgdir} install || return 1
}
