ETCD_DATA_DIR="/var/lib/etcd/"

post_install() {
    mkdir -p "${ETCD_DATA_DIR}"

    # create an etcd user
    id -u etcd &>/dev/null || useradd -r -M -U -d /dev/null -s /bin/nologin etcd

    chown -R etcd:etcd "${ETCD_DATA_DIR}"
}

post_upgrade() {
    post_install

cat << EOF
	In case of upgrade from v0.4 or earlier
	you should, probably, read following:

	/usr/share/doc/etcd/0_4_migration_tool.md

EOF
}
