post_install() {
  echo ">>> Add 'vaiopower' to DAEMONS=() in /etc/rc.conf if you want vaiopower"
  echo ">>> to be run at boot and to automatically disable the devices set in"
  echo ">>> /etc/vaiopower.conf."
}

post_remove() {
  # System is unable to resume if it has been suspended with DVD off.
  # So make sure DVD is on when we remove the package.
  DEVICE="/sys/devices/platform/sony-laptop"
  [ -w $DEVICE/cdpower ] && [ "$(cat $DEVICE/cdpower)" = 0 ] && echo 1 > $DEVICE/cdpower
}
