post_install() {
	echo "Creating menu's and file associations, please wait..."
	/opt/cxoffice/bin/cxmenu --crossover --install
	/opt/cxoffice/bin/cxassoc --crossover --install
	echo "Done!"
	echo
	echo "This is the demo version, to fully activate it you must have a valid serial and registrate it"
	echo "More information about this process here: http://www.codeweavers.com/products/cxlinux/"
}

post_upgrade() {
	post_install
}