# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: tuftedocelot <tuftedocelot@fastmail.fm>

_gemname=optiflag
pkgname=ruby-$_gemname
pkgver=0.7
pkgrel=1
pkgdesc='OptiFlag is an embeddable DSL library for declaring and using command-line options/flags in any Ruby program.'
arch=(any)
url='http://rubyforge.org/projects/optiflag/'
license=()
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('20d0b9c73ce34c216f36addccf25d5c7f990789e')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
