post_install() {
  echo ""
  echo "You can find Pixitracker and sample packs here: /usr/lib/pixitracker"
  echo " and example songs in /usr/lib/pixitracker/songs"
  echo "More information about pixitrracker available on this websites:"
  echo "http://www.warmplace.ru/soft/pixitracker/"
  echo "http://www.warmplace.ru/forum/"
  echo "http://code.google.com/p/pixilang"
  echo ""
  echo "Pixilang official manual: http://code.google.com/p/pixilang/w/list"
  echo ""
}
