#Automatically generated by pip2arch on 2012-06-20

pkgname=motmot.wxvalidatedtext
pkgver=0.5.3
pkgrel=1
pkgdesc="validated integer/float text entry field for wxPython"
url="http://code.astraw.com/projects/motmot"
depends=('python2' )
makedepends=('python2-distribute' )
license=('BSD')
arch=('any')
source=('http://pypi.python.org/packages/source/m/motmot.wxvalidatedtext/motmot.wxvalidatedtext-0.5.3.zip')
md5sums=('5abc3c3562bdda17e941f4c5c03f767c')

build() {
    cd $srcdir/motmot.wxvalidatedtext-0.5.3
    python2 setup.py build
}

package() {
    cd $srcdir/motmot.wxvalidatedtext-0.5.3
    python2 setup.py install --root="$pkgdir" --optimize=1 
}
