#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    sleep 10
    ;;
  stop)
    ;;
  restart)
  $0 stop
  $0 start
  ;;  
*)
    echo "usage: $0 {start|stop|restart}" 
esac
exit 0
