--- Makefile.in.in	2013-02-13 20:15:20.488659175 -0200
+++ Makefile.in.in	2013-02-13 20:08:54.412006584 -0200
@@ -37,9 +37,9 @@ DATADIRNAME = @DATADIRNAME@
 itlocaledir = $(prefix)/$(DATADIRNAME)/locale
 subdir = po
 install_sh = @install_sh@
-# Automake >= 1.8 provides @mkdir_p@.
+# Automake >= 1.8 provides @MKDIR_P@.
 # Until it can be supposed, use the safe fallback:
-mkdir_p = $(install_sh) -d
+MKDIR_P = $(install_sh) -d
 
 INSTALL = @INSTALL@
 INSTALL_DATA = @INSTALL_DATA@
@@ -110,7 +110,7 @@ install-data-yes: all
 	linguas="$(USE_LINGUAS)"; \
 	for lang in $$linguas; do \
 	  dir=$(DESTDIR)$(itlocaledir)/$$lang/LC_MESSAGES; \
-	  $(mkdir_p) $$dir; \
+	  $(MKDIR_P) $$dir; \
 	  if test -r $$lang.gmo; then \
 	    $(INSTALL_DATA) $$lang.gmo $$dir/$(GETTEXT_PACKAGE).mo; \
 	    echo "installing $$lang.gmo as $$dir/$(GETTEXT_PACKAGE).mo"; \
