_pkgname=ca-certificates
pkgname=ca-certificates-git
pkgver=20130119.21.gea93bfa
pkgrel=2
pkgdesc='Common CA certificates'
arch=('any')
url='http://packages.qa.debian.org/c/ca-certificates.html'
license=('MPL' 'GPL')
depends=('bash' 'run-parts' 'openssl' 'findutils' 'coreutils' 'sed')
makedepends=('python2' 'git')
provides=('ca-certificates')
conflicts=('ca-certificates')
install='ca-certificates.install'
backup=('etc/ca-certificates.conf')

source=('git://git.debian.org/git/collab-maint/ca-certificates.git')
md5sums=('SKIP')

pkgver() {
    cd "${srcdir}/${_pkgname}"
    git describe --always | sed 's|debian/||g; s|-|.|g'
}

build() {
    cd "${srcdir}/${_pkgname}"
    sed 's|/usr/bin/python|/usr/bin/python2|g' -i mozilla/certdata2pem.py
    sed 's|python|python2|g' -i mozilla/Makefile
    make
}

package() {
    cd "${srcdir}/${_pkgname}"
    install -d -m755 "${pkgdir}"/{etc/ca-certificates/update.d,usr/{sbin,share/ca-certificates},etc/ssl/certs}
    make install DESTDIR="${pkgdir}"
    mv "${pkgdir}/usr/sbin" "${pkgdir}/usr/bin"
    install -D -m644 sbin/update-ca-certificates.8 "${pkgdir}/usr/share/man/man8/update-ca-certificates.8"

    (
    echo "# Automatically generated by ${_pkgname}-${pkgver}-${pkgrel}"
    echo "# see update-ca-certificates man page"
    echo "# "
    cd "${pkgdir}/usr/share/ca-certificates"
    find . -name '*.crt' | sort | cut -b3-
    ) > "${pkgdir}/etc/ca-certificates.conf"
}
