post_install() {
  echo "update mime database..."
  update-mime-database usr/share/mime > /dev/null
  echo "update desktop mime database..."
  update-desktop-database -q
  echo "update gconf schemas..."
  GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source` gconftool-2 --makefile-install-rule /etc/gconf/schemas/gnome-raw-thumbnailer.schemas
}

post_upgrade() {
  post_install $1
}

post_remove() {
  post_install $1
}
