post_upgrade()
{
    usr/bin/update-desktop-database -q
    usr/bin/gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_install()
{
    post_upgrade
    echo "Depends and optdepends are modified according to installed packages."
    echo "Detected optional dependencies are moved into depends array."
    echo "Adding new optional dependency needs re-compiling the package."
    echo "All the above process are done automatically."
}

post_remove()
{
    post_upgrade
}
