post_upgrade()
{
    xdg-icon-resource forceupdate --theme hicolor &>/dev/null
    update-desktop-database -q
}

post_install()
{
    post_upgrade
    echo "Depends and optdepends are modified according to installed packages."
    echo "Detected optional dependencies are moved into depends array."
    echo "Adding new optional dependency needs re-compiling the package."
    echo "All the above process are done automatically."
}

post_remove()
{
    post_upgrade
}
