.
.TH SALSAMSG 1 \*(Dt "SalsaMsg v0.01" "User Commands"
.hy 0
.
.SH "NAME"
\fBsalsamsg\fR
.
.SH "OVERVIEW"
Exchanges Salsa20 keys encrypted with GPG between two peers connected through a socket\. It then uses the exchanged Salsa20 keys to exchange encrypted messages, read in and out through supplied file descriptors\. Once the \'nonce\' had gone though it\'s permutations, a new session key will be generated and transmitted, no nonce/key re\-use!
.
.SH "USAGE"
\fBsalsamsg \-m <Mode> \-i <IP> \-p <Port> \-l <Local PGP ID> \-r <Remote PGP ID>\fR
.
.SS "Mode"
If Mode is \fBc\fR for Connect (Client)
.
.P
If Mode is \fBl\fR for Listen (Server)
.
.SS "IP"
If Mode is \fBc\fR then the remote IP to connect to
.
.P
If Mode is \fBl\fR then the local IP to bind to
.
.SS "Port"
If Mode is \fBc\fR then the remote Port to connect to
.
.P
If Mode is \fBl\fR then the local Port to bind to
.
.SS "Local PGP ID"
The PGP ID for the Private Key to decrypt incoming Salsa keys (Your PGP ID)
.
.SS "Remote PGP ID"
The PGP ID for the Public Key to encrypt outing Salsa keys (Their PGP ID)
