#!/bin/bash

# Version 1.6 by graysky
#
# See this wiki article for more details:
# https://wiki.archlinux.org/index.php/Modprobed_db
#
# The purpose of this little script is to keep track of EVERY single module
# that your system has probed over a time period for the purpose of having the
# perfect amount of modules compiled into your kernel via the make localmodconfig
# option.
#
# The script keeps two files:
# 1) A human readable file: /var/log/modprobe.db
# 2) A very convenient space separated file you can simple cat into a modprobe line
# prior to a kernel build: /var/log/modprobe.long
#
# Simply run reload_database prior to building your kernel

. /etc/modprobed_db.conf

db=${dbpath}/modprobed.db
dblong=${dbpath}/modprobed.long

if [ ! -f ${db} ]; then
 echo "No db present so making" ${db}
 cat /proc/modules  | awk '{print $1}' | sort -k 1,1 | grep -Ev "`echo ${ignore[*]} | sed -e 's/^/^(/' -e 's/ /|/g' -e 's/$/)$/'`" > ${db}
 sed ':a;N;$!ba;s/\n/ /g' ${db} > ${dblong}
fi

dbsize=$(wc -l <${db})
echo "The db currently contains this many records: "${dbsize}
dbcheck=$(md5sum ${db} | cut -c1-32)

cat /proc/modules  | awk '{print $1}' | sort -k 1,1 | grep -Ev "`echo ${ignore[*]} | sed -e 's/^/^(/' -e 's/ /|/g' -e 's/$/)$/'`" > /tmp/.test
sort -k 1,1 ${db} /tmp/.test | uniq > /tmp/.new
newcheck=$(md5sum /tmp/.new | cut -c1-32)

if [ "$dbcheck" != "$newcheck" ]; then
 echo "New modules detected.  Updating db..."
 cp /tmp/.new ${db}
 newdbsize=$(wc -l <${db})
 echo "The db now contains this many records: "${newdbsize}
 sed ':a;N;$!ba;s/\n/ /g' ${db} > ${dblong}
fi
