#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/profile
. /etc/conf.d/apollo

PIDFILE="/run/apollo.pid"
umask=077

check_pid() {
	[ ! -f "$PIDFILE" ] && return 1
	local PID=$(cat "$PIDFILE" 2> /dev/null)
	if [ -z "$PID" -o ! -d "/proc/$PID" ]; then
		rm -f "$PIDFILE" 2> /dev/null
		return 1
	fi
	return 0
}

kill_pid() {
	if check_pid; then
		local PID=$(cat "$PIDFILE" 2> /dev/null)
		kill $PID &> /dev/null
		local RET=$?
		check_pid
		return $RET
	fi
	return 1
}

wait_pid() {
	while check_pid; do sleep 1; done
}

case "$1" in
	start)
		stat_busy "Starting Apollo"
		if [ -z "$BROKER" ]; then
			stat_fail
			echo "Specify the broker to run in /etc/conf.d/apollo"
		else
			if check_pid; then
				stat_fail
				exit 0
			fi

			nohup apollo-broker "$BROKER" run >/dev/null 2>&1 &

			if [ $? -gt 0 ]; then
				stat_fail
			else
				echo $! > /run/apollo.pid
				add_daemon apollo
				stat_done
			fi
		fi
		;;
	stop)
		stat_busy "Stopping Apollo"
		if ! kill_pid; then
			stat_fail
		else
			rm_daemon apollo
			stat_done
		fi
		;;
	restart)
		$0 stop
		wait_pid
		$0 start
		;;
	*)
		echo "usage: $0 {start|stop|restart}"
esac
exit 0
