post_install() {
    cat <<'MSG'
==> WARNING: 	Ardour3 is in a very early stage of rapid development. The upstream
		developer requests that you only use this package if you are
		familiar with debugging tools and intend to contribute useful
		information upstream.

		Please read the following:
   		  http://ardour.org/debugging_ardour
		  http://ardour.org/how_to_report_a_bug
MSG
}

post_upgrade() {
    if [ "$1" == "x" ]; then
        post_install $1
    fi
}

