post_install() {
  post_upgrade "$1"
  cat <<MSG
==> WARNING: Ardour3 is in a very early stage of rapid development. The upstream
developer requests that you only use this package if you are familiar with
debugging tools and intend to contribute useful information upstream.

Please read the following:
  http://ardour.org/debugging_ardour
  http://ardour.org/how_to_report_a_bug
MSG
}

post_upgrade() {
  update-desktop-database -q
}

post_remove() {
  post_upgrade "$1"
}

# vim:set ts=2 sw=2 et: