#!/bin/bash

daemon_name=accel-pppd

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/$daemon_name

PIDFILE=/var/log/$daemon_name.pid
get_pid() {
	pidof -o %PPID $daemon_name
}

if [ ! -d "/run/accel-ppp" ] ; then
        mkdir /run/accel-ppp
fi

case "$1" in
	start)
		stat_busy "Starting PPTP/PPPoE/L2TP $daemon_name daemon"

		PID=$(get_pid)
		if [[ -z $PID ]]; then
			[[ -f /var/run/$daemon_name.pid ]] &&
				rm -f /var/run/$daemon_name.pid
		# RUN
		$daemon_name -d -p $PIDFILE $ACCEL_PPPD_OPTS
		#
		if [[ $? -gt 0 ]]; then
			stat_fail
			exit 1
		else
			echo $(get_pid) > /var/run/$daemon_name.pid
			add_daemon $daemon_name
			stat_done
		fi
		else
			stat_fail
			exit 1
		fi
		;;

	stop)
		stat_busy "Stopping PPTP/PPPoE/L2TP $daemon_name daemon"
		PID=$(get_pid)
		# KILL
		[[ -n $PID ]] && kill $PID &> /dev/null
		#
		if [[ $? -gt 0 ]]; then
			stat_fail
			exit 1
		else
			rm -f /var/run/$daemon_name.pid &> /dev/null
			rm_daemon $daemon_name
			stat_done
		fi
		;;

	restart)
		$0 stop
		sleep 4
		$0 start
		;;

	status)
		stat_busy "Checking $daemon_name status";
		ck_status $daemon_name
		;;

	*)
		echo "usage: $0 {start|stop|restart|status}"
esac

exit 0

# vim:set ts=2 sw=2 et:
