# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=mogli
pkgname=ruby-$_gemname
pkgver=0.0.46
pkgrel=1
pkgdesc='Open Graph Library for Ruby'
arch=(any)
url='http://developers.facebook.com/docs/api'
license=(MIT)
depends=(ruby ruby-hashie ruby-httmultiparty ruby-httparty ruby-multi_json-1.7)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('5de056a32bff7a0207820aa3e88d51032d4a3d84')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
