diff --git a/fcoe-utils/Makefile.am b/fcoe-utils/Makefile.am
index 5cbc15f..3baff95 100644
--- a/fcoe-utils/Makefile.am
+++ b/fcoe-utils/Makefile.am
@@ -10,20 +10,20 @@ AM_CFLAGS = -Wall -Wformat=2 -Werror -Wmissing-prototypes -Wstrict-prototypes
 ## rules for building fcoeadm
 fcoeadm_SOURCES = fcoeadm.c fcoeadm_display.c
 fcoeadm_LDADD = lib/libutil.a libopenfcoe.a
-fcoeadm_CFLAGS = $(AM_CFLAGS) $(HBAAPI_CFLAGS)
-fcoeadm_LDFLAGS = $(AM_LDFLAGS) $(HBAAPI_LIBS)
+fcoeadm_CFLAGS = $(AM_CFLAGS) $(HBAAPI_CFLAGS) $(LIBHBALINUX_CFLAGS)
+fcoeadm_LDFLAGS = $(AM_LDFLAGS) $(HBAAPI_LIBS) $(LIBHBALINUX_LIBS)
 
 ## rules for building fcoemon
 fcoemon_SOURCES = fcoemon.c
 fcoemon_LDADD = lib/libutil.a
-fcoemon_CFLAGS = $(AM_CFLAGS) $(DCBD_CFLAGS)
-fcoemon_LDFLAGS = $(AM_LDFLAGS) -lrt
+fcoemon_CFLAGS = $(AM_CFLAGS) $(DCBD_CFLAGS) $(HBAAPI_CFLAGS)
+fcoemon_LDFLAGS = $(AM_LDFLAGS) $(HBAAPI_LIBS) -lrt
 
 ## rules for building fcping
 fcping_SOURCES = fcping.c
 fcping_LDADD = lib/libutil.a
-fcping_CFLAGS = $(AM_CFLAGS) $(HBAAPI_CFLAGS)
-fcping_LDFLAGS = $(AM_LDFLAGS) $(HBAAPI_LIBS) -lrt
+fcping_CFLAGS = $(AM_CFLAGS) $(HBAAPI_CFLAGS) $(LIBHBALINUX_CFLAGS)
+fcping_LDFLAGS = $(AM_LDFLAGS) $(HBAAPI_LIBS) $(LIBHBALINUX_LIBS) -lrt
 
 ## rules for building fipvlan
 fipvlan_SOURCES = fipvlan.c
@@ -67,7 +67,7 @@ init_d_SCRIPTS = etc/initd/fcoe
 
 dist_noinst_DATA = README COPYING INSTALL fcoe-utils.spec etc/config
 
-BASH_COMPLETION_DIR=/etc/bash_completion.d/
+BASH_COMPLETION_DIR=/usr/share/bash-completion/completions/
 
 install-data-hook:
 	if [ ! -f ${DESTDIR}${fcoe_configdir}/config ] ; then \
@@ -73,7 +73,7 @@ install-data-hook:
 	if [ ! -f ${DESTDIR}${fcoe_configdir}/config ] ; then \
 		cp ${srcdir}/etc/config ${DESTDIR}${fcoe_configdir}/config; \
 	fi; \
-	if [ ! -d "${BASH_COMPLETION_DIR}" ] ; then \
-		mkdir ${BASH_COMPLETION_DIR}; \
+	if [ ! -d "${DESTDIR}${BASH_COMPLETION_DIR}" ] ; then \
+		mkdir -p ${DESTDIR}${BASH_COMPLETION_DIR}; \
 	fi; \
-	cp -f ${srcdir}/contrib/bash_completion/* ${BASH_COMPLETION_DIR}
+	cp -f ${srcdir}/contrib/bash_completion/* ${DESTDIR}${BASH_COMPLETION_DIR}
