post_install() {
  echo -----------------------------------------------------------------
  echo Don\'t forget to edit /etc/systemd/system/twitchnotifier.service
  echo to tailor it to your needs if you are going to use it
  echo -----------------------------------------------------------------
}

post_upgrade() {
  echo -----------------------------------------------------------------
  echo TwitchNotifier now provides a systemd unit to make sure it runs
  echo on graphical login. Enable twitchnotifier.service and edit it in
  echo /etc/systemd/system to tailor it to your needs!
  echo -----------------------------------------------------------------
}