#!/bin/sh

# Kills all your processes when you log out.
ps --user $USER | egrep -v "ssh|screen" | cut -b11-15 | xargs -t kill

# Sets the desktop background to solid black. Useful if you have multiple monitors.
xsetroot -solid black