# This PKGBUILD was generated by cpan4pacman via CPANPLUS::Dist::Pacman
# Maintainer: Kristaps Esterlins <kristaps dot esterlins at gmail dot com> 
# Contributor: Kristaps Esterlins <kristaps dot esterlins at gmail dot com> 

pkgname=perl-audio-flac-decoder
_pkgname=Audio-FLAC-Decoder
pkgver=0.3
pkgrel=1
pkgdesc="An object-oriented FLAC decoder"
url="http://search.cpan.org/~daniel/Audio-FLAC-Decoder"
depends=('perl>=5.005' 'perl-audio-flac-header' 'flac')
license=('GPL')
options=('!emptydirs')
arch=('i686' 'x86_64')
source=(http://www.cpan.org/authors/id/D/DA/DANIEL/${_pkgname}-$pkgver.tar.gz)
md5sums=('765a3281f71766e8264028227d2c8a9e')

build() {
  cd  $srcdir/${_pkgname}-$pkgver
  eval `perl -V:archname`
  /usr/bin/perl Makefile.PL \
      INSTALLARCHLIB=/usr/lib/perl5/current/$archname \
      INSTALLSITELIB=/usr/lib/perl5/site_perl/current \
      INSTALLSITEARCH=/usr/lib/perl5/site_perl/current/$archname
  make || return 1
  make DESTDIR=$pkgdir install || return 1
  find $pkgdir -name '.packlist' -exec rm  '{}' \;
  find $pkgdir -name '*.pod' -exec rm  '{}' \;
}
