pkgname=xscrabble

# arg 1:  the new package version
post_install() {
  echo ""
  echo "NOTE:"
  echo "To play xscrabble you need to install language files"
  echo "For English language files, please install xscrabble-en."
  echo "Also French language files are available on the internet,"
  echo "but no Arch package currently exists."
  echo ""
}

post_upgrade() {
  post_install $1
}

op=$1
shift
$op $*
