--- src/cinux-loader-i686-pc-linux-gnu-2.02/makefile	2010-04-05 13:32:47.000000000 +0200
+++ makefile	2011-09-07 11:10:38.458932923 +0200
@@ -3,10 +3,9 @@
 
 # # # # # # # Changeable directions variables # # # # # # # #
 #															#
-BIN_DIR = /usr/bin
-LIB_DIR = /usr/lib
-MAN_DIR = /usr/share/man/man1
-DOC_DIR = /usr/share/doc
+BIN_DIR = $(DESTDIR)/usr/bin
+MAN_DIR = $(DESTDIR)/usr/share/man/man1
+DOC_DIR = $(DESTDIR)/usr/share/doc
 #
 #
 # If you change the SYSCONF_DIR value,
@@ -18,7 +17,7 @@
 # For more infomation about the conf file look into
 # the manual (man cinux-loader)
 #
-SYSCONF_DIR = /etc
+SYSCONF_DIR = $(DESTDIR)/etc
 #															#
 # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
 
@@ -44,10 +43,3 @@
 	install -d -m 755 $(MAN_DIR)
 	install -m 755 $(NAME).1 $(MAN_DIR)
 
-	if [ ! -f $(LIB_DIR)/libpcre.so.0 ]; then \
-		if [ -f $(LIB_DIR)/libpcre.so ]; then \
-			ln -sv $(LIB_DIR)/libpcre.so $(LIB_DIR)/libpcre.so.0; \
-		else \
-			ln -sv `ls $(LIB_DIR)/libpcre.so.* | head -n1` $(LIB_DIR)/libpcre.so.0; \
-		fi \
-	fi
