# arg 1:  the new package version
# arg 2:  the old package version
post_install() {

tar -xf /opt/lib32/usr/bin/flashplayer.tar.gz
mv flashplayer /opt/lib32/usr/bin/flashplayer
rm /opt/lib32/usr/bin/flashplayer.tar.gz

}

post_upgrade() {

tar -xf /opt/lib32/usr/bin/flashplayer.tar.gz
mv flashplayer /opt/lib32/usr/bin/flashplayer
rm /opt/lib32/usr/bin/flashplayer.tar.gz

}

pre_remove() {

rm /opt/lib32/usr/bin/flashplayer

}

op=$1
shift
$op $*
