post_install() {
_alert
}

_alert() {
cat << EOF
If you were running the version of espeakup from community, Do the following to clear out the old service file:
# systemctl disable espeakup
To start the new service:
# systemctl daemon-reload
# systemctl enable espeakup@voice-file.service
E.g. systemctl enable espeakup@en-us.service
# systemctl stop espeakup;systemctl start espeakup@en-us.service
EOF
}

