--- Makefile.orig	2011-02-07 19:59:17.491702619 +0100
+++ Makefile	2011-02-07 20:00:31.668369286 +0100
@@ -1,5 +1,6 @@
-
-export prefix=/usr/local
+DESTDIR ?= 
+prefix ?= $(DESTDIR)/usr
+export prefix
 export milena_dir=$(prefix)/share/milena
 export doc_dir=$(prefix)/share/doc/milena
 export speechd_dir=$(shell ./find_speechd)
@@ -11,7 +12,6 @@
 
 all: config.dat
 	make -C src all
-	make -C data all
 	make -C utils all
 	make -C speechd all
 	make -C milena_ws all
@@ -24,7 +24,6 @@
 clean:
 	rm -f config.dat
 	make -C src clean
-	make -C data clean
 	make -C utils clean
 	make -C speechd clean
 	make -C milena_ws clean
@@ -32,10 +31,8 @@
 		
 install:
 	make -C src install
-	ldconfig
 	mkdir -p $(doc_dir)
 	install -m 644 README* $(doc_dir)
-	make -C data install
 	make -C utils install
 	make -C milena_ws install
 	make -C subplayer install
@@ -44,8 +41,6 @@
 	for i in README*;do rm -f $(doc_dir)/"$$i";done
 	if [ -d $(doc_dir) ] ; then rmdir --ignore-fail-on-non-empty $(doc_dir);fi
 	make -C src uninstall
-	ldconfig
-	make -C data uninstall
 	make -C utils uninstall
 	make -C milena_ws uninstall
 	make -C subplayer uninstall
--- src/Makefile.orig	2011-02-07 20:00:42.588369284 +0100
+++ src/Makefile	2011-02-07 20:01:50.615035952 +0100
@@ -57,6 +57,9 @@
 	rm -f *~ *.o *.so milena milena.h milena.pc milena_cyrillic.h
 	
 install:	milena
+	install -dm 0755 $(prefix)/bin
+	install -dm 0755 $(LIBDIR)
+	install -dm 0755 $(prefix)/include/
 	install -m 0755 milena $(prefix)/bin
 	install -m 0755 libmilena.so libmilena_mbrola.so $(LIBDIR)
 	install -m 0644 milena.h milena_mbrola.h $(prefix)/include/
