--- Makefile.orig	2010-10-23 18:08:58.872564868 +0200
+++ Makefile	2010-10-23 18:11:49.312564867 +0200
@@ -1,5 +1,6 @@
-
-export prefix=/usr/local
+DESTDIR ?= 
+prefix ?= $(DESTDIR)/usr
+export prefix
 export milena_dir=$(prefix)/share/milena
 export speechd_dir=$(shell ./find_speechd)
 export distro=$(shell uname -o)
@@ -10,7 +11,6 @@
 
 all: config.dat
 	make -C src all
-	make -C data all
 	make -C utils all
 	make -C speechd all
 	make -C milena_ws all
@@ -23,7 +23,6 @@
 clean:
 	rm -f config.dat
 	make -C src clean
-	make -C data clean
 	make -C utils clean
 	make -C speechd clean
 	make -C milena_ws clean
@@ -31,8 +30,6 @@
 		
 install:
 	make -C src install
-	ldconfig
-	make -C data install
 	make -C utils install
 	make -C speechd install
 	make -C milena_ws install
@@ -40,8 +37,6 @@
 
 uninstall:
 	make -C src uninstall
-	ldconfig
-	make -C data uninstall
 	make -C utils uninstall
 	make -C speechd uninstall
 	make -C milena_ws uninstall
--- src/Makefile.orig	2010-10-23 18:12:17.619231534 +0200
+++ src/Makefile	2010-10-23 18:13:13.662564868 +0200
@@ -57,6 +57,9 @@
 	rm -f *~ *.o *.so milena milena.h milena.pc milena_cyrillic.h
 	
 install:	milena
+	install -dm 0755 $(prefix)/bin
+	install -dm 0755 $(LIBDIR)
+	install -dm 0755 $(prefix)/include/
 	install -m 0755 milena $(prefix)/bin
 	install -m 0755 libmilena.so libmilena_mbrola.so $(LIBDIR)
 	install -m 0644 milena.h milena_mbrola.h $(prefix)/include/
