#!/usr/bin/bash

if [ "$#" != "1" ]; then
    echo "usage: git publish <rsync_dest>"
    exit 1
fi

RSYNC_DEST=$1

function verify_not_dirty {
    [[ $(git status 2> /dev/null | tail -n1) == "nothing to commit, working directory clean" ]]
    if [ $? != 0 ]; then
        echo "Git repo is dirty. Clean it up and then try again."
        exit 1
    fi
}

verify_not_dirty

set -e

REPO_BASE=$(git rev-parse --show-toplevel)
COMMIT=$(git rev-parse HEAD|cut -c-8)
TIME=$(date "+%Y%m%d-%H%M%S")
FILENAME=$(basename $REPO_BASE)-$COMMIT-$TIME.tgz
TMPFILE=/tmp/$FILENAME

[ -e "$TMPFILE" ] && rm "$TMPFILE"

if [ -e "$TMPFILE" ]; then
    echo "$TMPFILE already exists, which means you may have already published this version."
    exit 1
fi

echo "Creating tarball at $TMPFILE"
tar -C "$(dirname $REPO_BASE)" -c -z -v --exclude-vcs --exclude-vcs-ignores -f "$TMPFILE" "$(basename $REPO_BASE)"

echo "Rsyncing tarball to $RSYNC_DEST"
rsync -v "$TMPFILE" "$RSYNC_DEST"

echo OK

