post_install(){
/usr/bin/egrep -i "^svxlink" /etc/group >> /dev/zero
if [ ! $? -eq 0 ]
then
	groupadd svxlink
fi

/usr/bin/egrep -i "^svxlink" /etc/passwd >> /dev/zero
if [ ! $? -eq 0 ]
then
	useradd svxlink -d /var/lib/svxlink -g svxlink
fi
}


pre_remove(){
/usr/bin/egrep -i "^svxlink" /etc/passwd >> /dev/zero
if [ $? -eq 0 ]
then
        userdel svxlink
fi

/usr/bin/egrep -i "^svxlink" /etc/group >> /dev/zero
if [ $? -eq 0 ]
then
        groupdel svxlink
fi
}
