post_install() {
  groupadd mach
  for folder in lib cache tmp; do
    [ -d /var/$folder/mach ] || mkdir -m u+rwx,g+rws,o+rx-w /var/$folder/mach; chown root.mach /var/$folder/mach
  done
  chmod u+s /usr/sbin/mach-helper
  echo "Please add your user to the mach group"
}

post_upgrade() {
  chmod u+s /usr/sbin/mach-helper
}

post_remove() {
  groupdel mach
  for folder in lib cache tmp; do
    [ -d /var/$folder/mach ] && rm -rf /var/$folder/mach
  done
}
