# Maintainer: kfgz <kfgz at interia pl>
# Contributor: hauzer <alokinpwn at gmail dot com>

pkgname=pburn
pkgver=4.3.12
pkgrel=1
pkgdesc="CD/DVD recording program used in Puppy Linux."
arch=('any')
url="http://murga-linux.com/puppy/viewtopic.php?t=23881"
license=('GPL')
depends=('cddetect' 'dvd+rw-tools' 'gtkdialog-svn' 'hotplug2stdout')
makedepends=('pet2tgz')
optdepends=('dvdauthor: for burning Video-DVD'
            'ffmpeg: for converting audio/video'
            'normalize: for volume settings on Audio-CD'
            'pfilesearch: for file search'
            'vamps: for shrinking Video-DVD'
            'vcdimager: for burning Video-CD'
            'vobcopy: for copying Video-DVD'
            'nrg2iso: for converting CD or DVD image generated by Nero Burning Rom to ISO format')

source=(http://www.meownplanet.net/zigbert/${pkgname}-${pkgver}.pet
        ${pkgname}.desktop
        ${pkgname})
md5sums=('7b4a3ec7198bd956ba09f6b8f159ed8c'
         'e9e5c23dfec6f0bacdc9ed0df19dca2e'
         'd3441385bc1a0d3678c4aa28811b37bc')

build() {
  cd "${srcdir}"
  pet2tgz -i "${srcdir}"/${pkgname}-${pkgver}.pet -o "${srcdir}"/${pkgname}-${pkgver}.tar.gz
  tar -xzf "${srcdir}"/${pkgname}-${pkgver}.tar.gz
}

#_md5sum=dd9d73d7364f5cee1bb757d740f38fd7

#build() {
#  cd "${srcdir}"
#  if [ -e ${pkgname}-${pkgver}.pet ]; then
#    if [ ${_md5sum} != `md5sum ${pkgname}-${pkgver}.pet | awk '{print $1}'` ]; then error "Md5sum is incorrect!" && exit; fi
#    pet2tgz -i "${srcdir}"/${pkgname}-${pkgver}.pet -o "${srcdir}"/${pkgname}-${pkgver}.tar.gz
#    tar -xzf "${srcdir}"/${pkgname}-${pkgver}.tar.gz
#  else
#    #wget --user=puppy --password=linux http://www.meownplanet.net/zigbert/${pkgname}-${pkgver}.pet
#    wget http://www.meownplanet.net/zigbert/${pkgname}-${pkgver}.pet
#    #wget http://kfgz.mydevil.net/${pkgname}-${pkgver}.pet
#    if [ ${_md5sum} != `md5sum ${pkgname}-${pkgver}.pet | awk '{print $1}'` ]; then error "Md5sum is incorrect!" && exit; fi
#    pet2tgz -i "${srcdir}"/${pkgname}-${pkgver}.pet -o "${srcdir}"/${pkgname}-${pkgver}.tar.gz
#    tar -xzf "${srcdir}"/${pkgname}-${pkgver}.tar.gz
#  fi
#}


package() {
  install -D -m755 ${pkgname} "${pkgdir}"/usr/bin/${pkgname}
  install -D -m644 ${pkgname}.desktop "${pkgdir}"/usr/share/applications/${pkgname}.desktop
  install -D -m644 "${srcdir}"/${pkgname}-${pkgver}/usr/share/icons/hicolor/scalable/apps/${pkgname}.svg \
				   "${pkgdir}"/usr/share/icons/hicolor/scalable/apps/${pkgname}.svg

  mkdir -p "${pkgdir}"/usr/share
  mkdir -p "${pkgdir}"/usr/share/locale/en/LC_MESSAGES
  cp -r "${srcdir}"/${pkgname}-${pkgver}/usr/local/${pkgname} "${pkgdir}"/usr/share/
  cp -r "${srcdir}"/${pkgname}-${pkgver}/usr/share/doc "${pkgdir}"/usr/share/
}
