post_install() {
  cat << _EOF
 
==> In order to play your music with gmusicbrowser, you need to install 
	gstreamer and its perl bindings  OR  mpg321/vorbis-tools/flac123/alsa-utils  OR  mplayer
	(look at optdepends for details)
     
_EOF
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_upgrade() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_remove() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}
