post_install() {
	echo -n "Updating bitmap fonts... "
	mkfontscale /usr/share/fonts/misc
	mkfontdir /usr/share/fonts/misc
	fc-cache /usr/share/fonts/misc
	echo "done"

	echo -n "Updating TrueType fonts... "
	mkfontscale /usr/share/fonts/TTF
	mkfontdir /usr/share/fonts/TTF
	fc-cache /usr/share/fonts/TTF
	echo "done"

	echo -n "Reloading font database... "
	xset fp rehash
	echo "done."
}

post_upgrade() {
	post_install
}

post_remove() {
	post_install
}
