diff -ru drc-3.2.1.orig/source/makefile drc-3.2.1/source/makefile
--- drc-3.2.1.orig/source/makefile	2012-05-07 15:15:49.000000000 +0200
+++ drc-3.2.1/source/makefile	2012-11-15 19:12:38.187503476 +0100
@@ -4,7 +4,7 @@
 VERSION=3.2.1
 
 # Where to install
-INSTALL_PREFIX=$(DESTDIR)/usr/local
+INSTALL_PREFIX=$(DESTDIR)/usr
 
 # Compiler
 CC=g++
@@ -21,7 +21,7 @@
 
 # Pentium 3 or greater optimizaztions settings with SSE support
 # Be careful: -mfpmath=sse sometimes causes accuracy problems
-CFLAGS=-march=pentium3 -O -s -mfancy-math-387 -msse -mfpmath=sse -mtune=pentium3 -I. 
+CFLAGS=-march=native -Os -pipe -I. -DUseDouble
 
 # Same as above, but tested on recent Mac OS X
 # Be careful: -mfpmath=sse sometimes causes accuracy problems
@@ -61,11 +61,11 @@
 OBJS=drc lsconv glsweep
 
 # Installation definitions
-CONFIG_TARGETS=config/*
-TARGET_TARGETS=target/*
+CONFIG_TARGETS=config/**/*
+TARGET_TARGETS=target/**/*
 MIC_TARGETS=mic/*
 IMPULSE_TARGETS=../sample/rs.pcm
-DOC_TARGETS=readme.txt ../doc/text/drc.txt
+DOC_TARGETS=readme.txt
 BIN_TARGETS=drc lsconv glsweep
 
 # Targets
@@ -85,6 +85,7 @@
 	rm -f $(OBJS)
 
 install: $(CONFIG_TARGETS) $(TARGET_TARGETS) $(MIC_TARGETS) $(IMPULSE_TARGETS) $(DOC_TARGETS) $(BIN_TARGETS)
+	install -d $(INSTALL_PREFIX)/bin
 	install $(BIN_TARGETS) $(INSTALL_PREFIX)/bin
 	install -d $(INSTALL_PREFIX)/share/drc/config/
 	install $(CONFIG_TARGETS) $(INSTALL_PREFIX)/share/drc/config/
