--- Makefile	2011-05-10 16:30:47.776412693 +0200
+++ Makefile.mod	2011-05-10 16:32:38.624081448 +0200
@@ -29,6 +29,9 @@
 
 CAMLP4LIB:=$(shell $(CAMLP4BIN)$(CAMLP4) -where)
 
+DESTDIR:=$(DESTDIR)
+FINALDEST:=$(DESTDIR)$(COQLIB)
+
 ##########################
 #                        #
 # Libraries definitions. #
@@ -202,22 +205,22 @@
 	$(MAKE) all "OPT:=-opt"
 
 install:
-	mkdir -p $(COQLIB)/user-contrib
+	mkdir -p $(FINALDEST)/user-contrib
 	(cd tactics; for i in $(VOFILES1); do \
-	 install -d `dirname $(COQLIB)/user-contrib/ProgramCalculation/$$i`; \
-	 install $$i $(COQLIB)/user-contrib/ProgramCalculation/$$i; \
+	 install -d `dirname $(FINALDEST)/user-contrib/ProgramCalculation/$$i`; \
+	 install $$i $(FINALDEST)/user-contrib/ProgramCalculation/$$i; \
 	 done)
 	(cd theories/theory_of_lists; for i in $(VOFILES2); do \
-	 install -d `dirname $(COQLIB)/user-contrib/ProgramCalculation/Theories/$$i`; \
-	 install $$i $(COQLIB)/user-contrib/ProgramCalculation/Theories/$$i; \
+	 install -d `dirname $(FINALDEST)/user-contrib/ProgramCalculation/Theories/$$i`; \
+	 install $$i $(FINALDEST)/user-contrib/ProgramCalculation/Theories/$$i; \
 	 done)
 	(cd equivalences; for i in $(VOFILES3); do \
-	 install -d `dirname $(COQLIB)/user-contrib/ProgramCalculation/Equivalences/$$i`; \
-	 install $$i $(COQLIB)/user-contrib/ProgramCalculation/Equivalences/$$i; \
+	 install -d `dirname $(FINALDEST)/user-contrib/ProgramCalculation/Equivalences/$$i`; \
+	 install $$i $(FINALDEST)/user-contrib/ProgramCalculation/Equivalences/$$i; \
 	 done)
 	(for i in $(VOFILES0); do \
-	 install -d `dirname $(COQLIB)/user-contrib/$(INSTALLDEFAULTROOT)/$$i`; \
-	 install $$i $(COQLIB)/user-contrib/$(INSTALLDEFAULTROOT)/$$i; \
+	 install -d `dirname $(FINALDEST)/user-contrib/$(INSTALLDEFAULTROOT)/$$i`; \
+	 install $$i $(FINALDEST)/user-contrib/$(INSTALLDEFAULTROOT)/$$i; \
 	 done)
 
 clean:
