--- makefile.old	2006-09-09 02:12:10.000000000 +0200
+++ makefile	2006-09-09 02:15:46.000000000 +0200
@@ -5,15 +5,15 @@
 #CC=gcc
 
 # Compiler options
-OPTS=-g
-OPTS=-O0
+#OPTS=-g
+#OPTS=-O0
 #OPTS=-O2
 
 UNAME = $(shell uname)
 
 ifeq ($(UNAME), Linux)
 CXX       = g++
-CPPFLAGS += $(OPTS) -Wall -pedantic
+CPPFLAGS += $(OPTS) -Wall -pedantic $(CFLAGS)
 endif
 
 #######################################
