post_install() {
    echo ">>>>"
    echo ">>>> WARNING! The first time you launch Trine use trine-launcher"
    echo ">>>> or the trine.desktop file, not the trine command"
    echo ">>>> otherwise you will not be able to save your progress"
    echo ">>>>"
    echo ">>>> You also need to install proprietary drivers for your video"
    echo ">>>> card (nvidia-utils or catalyst-utils)."
}

post_upgrade() {
    post_install $1
}

pre_remove() {
    /bin/true
}

op=$1
shift

$op $*

