diff -u flactag-1.1/Makefile flactag-1.1.new/Makefile
--- flactag-1.1/Makefile	2008-12-16 06:20:56.000000000 -0500
+++ flactag-1.1.new/Makefile	2011-05-01 13:43:09.617640889 -0400
@@ -53,7 +53,7 @@
 	chmod 755 ${INSTALLPATH}/usr/bin/ripflac
 	
 flactag.1: flactag.1.xml Makefile
-	docbook2x-man flactag.1.xml
+	docbook2man flactag.1.xml
 	
 flactag.1.xml: flactag.1.txt Makefile
 	asciidoc -d manpage -b docbook flactag.1.txt
@@ -85,7 +85,7 @@
         sed 's,\($*\)\.o[ :]*,\1.o $@ : ,g' > $@
 
 flactag: $(FLACTAGOBJS)
-	g++ `neon-config --libs` -o $@ -lslang -lmusicbrainz3 -ldiscid -lFLAC++ -lunac -ljpeg $^ 
+	g++ `neon-config --libs|sed 's/ -Wl,--as-needed//'` -o $@ -lslang -lmusicbrainz3 -ldiscid -lFLAC++ -lunac -ljpeg $^ 
 	
 discid: $(DISCIDOBJS)
 	g++ -o $@ -ldiscid $^
