post_install() {
	echo "
	To use shenv, source the appropriate shell's shenvrc 
	from /usr/share/shenv/ in your shell's rc file
	
	Eg: (for bash) Add this to your ~/.bashrc file
	. /usr/share/shenv/bash/shenvrc

	Raise issues at https://github.com/sathyamvellal/shenv/issues
	"
}

post_remove() {
	echo "
	Your shenv scripts are kept intact in \$HOME/.shenv directory.
	You have to remove them manually, if you do not need them
	"
}
