#!/bin/bash

PATH=/sbin:/bin:/usr/sbin:/usr/bin
export PATH

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/sbin/upsd`

# POWERDOWNFLAG *must* match that in upsmon.conf
# Loading POWERDOWNFLAG from /etc/sysconfig/ups
DRIVERPATH=/usr/lib/nut
if [ -f /etc/nut/ups ]; then
  . /etc/sysconfig/ups
else
  POWERDOWNFLAG=/etc/killpower
  NUTUSER=nut
fi
UPSDCONF=/etc/nut/upsd.conf
UPSCONF=/etc/nut/ups.conf

# if there are no config file, bail out
[ -f $UPSDCONF ] && [ -f $UPSCONF ] || exit 0

runcmd() {
   echo -n "$1 "
   shift
   if [ "$BOOTUP" = "color" ]; then
      $* && echo_success || echo_failure
   else
      $*
   fi
   echo
}

# See how we are called.
case "$1" in
  start)
	# new style drivers uses 'upsdrvctl'
	echo -n "NUT Starting UPS model drivers: "
	# starting ase nut user
	daemon --user $NUTUSER `which upsdrvctl` start
	echo
	if [ $? -eq 0 ]; then
		echo -n "NUT Starting UPS daemon: "
		# starting ase nut user
		daemon upsd -u $NUTUSER
		echo
		touch /var/lock/subsys/upsd
	fi
	;;

  stop)
	# new style upsd stop
	action "NUT Stopping UPS daemon" \
	upsd -c stop
	# new style drivers uses 'upsdrvctl'
	action "NUT Stopping UPS model drivers" \
	upsdrvctl stop

	rm -f /var/lock/subsys/upsd
	;;

  powerdown)
	# new style drivers
	runcmd "NUT powerdown of attached UPS(es)" upsdrvctl shutdown
	;;

  restart)
	$0 stop
	$0 start
	;;

  reload)
	# reloading upsd config files
	action "NUT Reloading config files" \
	upsd -c reload
	;;

  status)
	# new style drivers
	action "NUT: checking UPS model drivers" upsdrvctl status

	status upsd
	;;
  *)
	echo "Usage: upsd {start|stop|powerdown|restart|reload|status}"
	exit 1
esac
exit 0
