post_install() {
  cat << EOF

>>> Add 
>>>	+/usr/share/scgraph/sclang
>>>     +/usr/lib/scgraph/plugins
>>> to your sclang.cfg, so the classes get loaded in your SuperCollider installation.
>>>
>>> create the directories
>>> 	~/.scgraph/synthdefs
>>> 	~/.scgraph/textures
>>> 	~/.scgraph/textures/default/
>>>
>>>  Have a look at the examples in 
>>>	/usr/share/scgraph/doc/examples/
>>>  They show you how to make simple animations with scgraph.

EOF
}

post_upgrade() {
  post_install
}
