#!/bin/sh
#
# Uses alternative libs
# Passes all parametrs to spotify

unset MOZ_PLUGIN_PATH
export MOZ_PLUGIN_PATH="/usr/share/spotify/mozplugins"

LD_LIBRARY_PATH="/usr/share/spotify/libs/" /usr/share/spotify/spotify "$@"
