diff --git a/Makefile b/Makefile
index 661c75c..df8ca37 100644
--- a/Makefile
+++ b/Makefile
@@ -35,7 +35,7 @@ clean:
 
 $(INSTDIR)/%: %
 	strip $<
-	install -m 755 -o root -g root $< $@
+	install -D -m 755 -o root -g root $< $@
 
 install: tuxoniceui $(INSTDIR)/tuxoniceui
 
