--- Makefile~	2010-02-11 18:20:29.771930624 +0100
+++ Makefile	2010-02-11 18:20:53.671930770 +0100
@@ -5,7 +5,7 @@
 PREFIX := /usr/local
 INSTDIR := $(DESTDIR)$(PREFIX)/sbin
 
-MODULES = text fbsplash usplash
+MODULES = text fbsplash
 TARGETS = $(patsubst %,tuxoniceui_%,$(MODULES))
 CORE_OBJECTS = userui_core.o
 
@@ -38,13 +38,13 @@
 	make -C $@ all
 
 tuxoniceui_text: $(CORE_OBJECTS) userui_text.o
-	$(CC) $(LDFLAGS) -static $^ -o $@
+	$(CC) $(LDFLAGS) $^ -o $@
 
 tuxoniceui_fbsplash: fbsplash $(CORE_OBJECTS) fbsplash/userui_fbsplash.o
-	$(CC) $(LDFLAGS) -static $(CORE_OBJECTS) fbsplash/userui_fbsplash.o -o $@ $(FBSPLASH_LIBS)
+	$(CC) $(LDFLAGS) $(CORE_OBJECTS) fbsplash/userui_fbsplash.o -o $@ $(FBSPLASH_LIBS)
 
 tuxoniceui_usplash: usplash $(CORE_OBJECTS) usplash/userui_usplash.o
-	$(CC) $(filter-out -static,$(LDFLAGS)) $(CORE_OBJECTS) usplash/userui_usplash.o -o $@ $(USPLASH_LIBS)
+	$(CC) $(filter-out $(LDFLAGS)) $(CORE_OBJECTS) usplash/userui_usplash.o -o $@ $(USPLASH_LIBS)
 
 clean:
 	$(RM) *.o $(TARGETS)
@@ -53,7 +53,7 @@
 
 $(INSTDIR)/%: %
 	strip $<
-	install -m 755 -o root -g root $< $@
+	install -D -m 755 -o root -g root $< $@
 
 install: all $(patsubst %,$(INSTDIR)/%,$(TARGETS))
 
