_news_post() {
 echo "How to use:
Export some environment variables
 export GTK_CSD=0
 export LD_PRELOAD=/usr/lib/gtk3-nocsd.so
before run gtk3-applications.
(Don't use this with QT or other non-gtk applications.)

Or yo may edit specific .desktop file of the target application,
 the \"Exec=\" line should look like this:
Exec=env LD_PRELOAD=/usr/lib/gtk3-nocsd.so evince %U"
}

post_install() {
 _news_post
}

post_upgrade() {
 _news_post
}
