#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

BACULA_FD_CONF=/etc/bacula/bacula-fd.conf
PID=`pidof -o %PPID /usr/sbin/bacula-fd`

case $1 in
  start)
    stat_busy "Starting Bacula File Daemon"
    [ -z "$PID" ] && /usr/sbin/bacula-fd -c $BACULA_FD_CONF
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon bacula-fd
      stat_done
    fi
    ;;

  stop)
    stat_busy "Stopping Bacula File Daemon"
    [ ! -z "$PID" ] && kill $PID &>/dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon bacula-fd
      stat_done
    fi
    ;;
 restart)
    $0 stop
    sleep 3
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0

