post_install() {
  cat <<EOM
>>
>> At the moment (20121215), awesome-git requires modified version of lgi-git package.
>> Also, those who use vicious need to rebuild it with Lua 5.2.
>> See https://aur.archlinux.org/packages/awesome-git/ for more info.
>>
>> LuaDoc local documentation files have no longer been installed.
>> Refer http://awesome.naquadah.org/doc/api/ instead.
>>
EOM
}

post_upgrade() {
  post_install
}
