## arg 1:  the new package version
post_install() {
  echo ">> Installing ruby-opengl and net-ssh ruby gems, this could take a while..."
  gem install --remote ruby-opengl
  gem install --remote net-ssh -v 1.1.2
  echo ">> Install complete!"
}

post_upgrade() {
  post_install $1
}

post_remove() {
  echo ">> The ruby-opengl and net-ssh ruby gems are still installed on your system, if you want to remove them, run 'gem uninstall ruby-opengl net-ssh'"
}
