# Contributors:
#	henning mueller <henning@orgizm.net>

pkgbase='kernel26'
pkgname=kernel26-pax
pkgdesc='The Linux Kernel and modules with PaX patches'
_kernelname=${pkgname#kernel26}
_basekernel=2.6.39
_paxver=test6
pkgver=$_basekernel
pkgrel=5
_patchname="patch-$pkgver-1-ARCH"
arch=(i686 x86_64)
license=(GPL2)
url='http://www.kernel.org'
options=(!strip)
groups=(base)
backup=(etc/mkinitcpio.d/$pkgname.preset)
depends=(
	coreutils linux-firmware
	'module-init-tools>=3.12-2' 'mkinitcpio>=0.6.8-2'
)
replaces=(
	kernel24 kernel24-scsi kernel26-scsi alsa-driver ieee80211 hostap-driver26
	pwc nforce squashfs unionfs ivtv zd1211 kvm-modules iwlwifi rt2x00-cvs
	gspcav1 atl2 wlan-ng26 rt2500 nouveau-drm
)
optdepends=(
	'crda: to set the correct wireless channels of your country.'
	'pax-utils: ELF related utils with PaX flags support.'
	'paxctl: Manages PaX related program header flags.'
	'paxtest: PaX regression test suite.'
)
install=$pkgname.install
source=(
	ftp://ftp.kernel.org/pub/linux/kernel/v2.6/linux-$_basekernel.tar.bz2
	ftp://ftp.archlinux.org/other/kernel26/$_patchname.bz2
	config
	config.x86_64
	$pkgname.install
	$pkgname.preset
	http://grsecurity.net/test/pax-linux-$_basekernel-$_paxver.patch
	README
)
md5sums=(
	1aab7a741abe08d42e8eccf20de61e05
	25bb870bed3865d3771b5e40d6dbfd50
	41d41bb09ea779065520577e84ab7652
	a4cf6da8d1c11b9141776c7b74e33134
	ce2ce0bcde33914fe66618e65571e50b
	3ce02e429ae6b03000c93c0a59d70d3a
	9c58cab4098b632b39ed120df39e75cf
	e4531df249803ca0d5f342dc44e45875
)

build() {
	cd $srcdir/linux-$_basekernel

	# Add -ARCH patches
	# See http://projects.archlinux.org/linux-2.6-ARCH.git/
	patch -Np1 -i $srcdir/$_patchname

	# Add PaX patches
	patch -Np1 -i $srcdir/pax-linux-$_basekernel-$_paxver.patch

	if [ "$CARCH" = "x86_64" ]; then
		cat ../config.x86_64 >./.config
	else
		cat ../config >./.config
	fi

	make prepare

	#make menuconfig # CLI menu for configuration
	#make nconfig # new CLI menu for configuration
	#make xconfig # X-based configuration
	#make oldconfig # using old config from previous kernel version

	#msg "Stopping build"
	#return 1

	yes "" | make config

	make $MAKEFLAGS bzImage modules
}

package() {
	KARCH=x86

	cd $srcdir/linux-$_basekernel

	# get kernel version
	_kernver="$(make kernelrelease)"

	mkdir -p $pkgdir/{lib/modules,lib/firmware,boot}
	make INSTALL_MOD_PATH=$pkgdir modules_install
	cp System.map $pkgdir/boot/System.map26$_kernelname
	cp arch/$KARCH/boot/bzImage $pkgdir/boot/vmlinuz26$_kernelname

	# add vmlinux
	install -m644 -D vmlinux $pkgdir/usr/src/linux-$_kernver/vmlinux

	# install fallback mkinitcpio.conf file and preset file for kernel
	install -m644 -D $srcdir/$pkgname.preset $pkgdir/etc/mkinitcpio.d/$pkgname.preset
	echo -e "# DO NOT EDIT THIS FILE\nALL_kver='$_kernver'" > $pkgdir/etc/mkinitcpio.d/$pkgname.kver

	# remove build and source links
	rm -f $pkgdir/lib/modules/$_kernver/{source,build}

	# remove the firmware
	rm -rf $pkgdir/lib/firmware

	# gzip -9 all modules to safe 100MB of space
	find "$pkgdir" -name '*.ko' -exec gzip -9 {} \;
}
