post_install() {
  echo
  echo "==> To create a certificate for openvasd, type openvas-mkcert"
  echo "==> To create a new user, type openvas-adduser"
  echo "==> To start the OpenVAS server, type openvasd or /etc/rc.d/openvasd start"
  echo
  echo "==> If you are upgrading from a version <=2.0.1-1 you may want to copy.."
  echo "==> ..your /usr/etc/openvas/ (not used anymore) files to /etc/openvas/"
  echo
  echo
}

# vim:set ts=2 sw=2 et:
