# Contributor: Martin Hilbig <blueonyx@gmx.net>
# Contributor: Arch Haskell Team <arch-haskell@haskell.org>
# Package generated by cabal2arch 0.4
pkgname=haskell-hgal-darcs
pkgrel=1
pkgver=20090706
pkgdesc="library for computation automorphism group and canonical labelling of a graph"
url="http://hackage.haskell.org/cgi-bin/hackage-scripts/package/hgal"
license=('GPL')
arch=('i686' 'x86_64')
makedepends=('darcs' 'ghc' 'haskell-cabal')
depends=('ghc' 'haskell-cabal')
options=('strip')
source=()
install=haskell-hgal.install
md5sums=()

_darcstrunk="http://code.haskell.org"
_darcsmod="hgal"

build() {

  
  cd $startdir/src

  msg "Checking for previous build"
  # get the sources
  if [[ -d $startdir/src/$_darcsmod/_darcs ]]
  then
    msg "Retrieving missing patches"
    cd $_darcsmod
    darcs pull -a $_darcstrunk/$_darcsmod
  else
    msg "Retrieving complete sources"
    darcs get --partial --set-scripts-executable $_darcstrunk/$_darcsmod
  fi

  msg "Starting build"
  cd $startdir/src/$_darcsmod

    runhaskell Setup configure --prefix=/usr || return 1
    runhaskell Setup build                   || return 1
    runhaskell Setup copy --destdir=$startdir/pkg || return 1
    runhaskell Setup register   --gen-script || return 1
    runhaskell Setup unregister --gen-script || return 1
    install -D -m744 register.sh   $startdir/pkg/usr/share/haskell/$pkgname/register.sh
    install    -m744 unregister.sh $startdir/pkg/usr/share/haskell/$pkgname/unregister.sh
    runhaskell Setup clean
}
