post_install() {
	cd /opt/fairsoft/current/src/FairSoft

	./configure.sh ../arch.conf

	echo "Add the following line to your ~/.profile"
	echo "  export SIMPATH=/opt/fairsoft/current"
}

post_upgrade() {
	cd /opt/fairsoft/current/src/FairSoft

	./configure.sh ../arch.conf

	echo "Add the following line to your ~/.profile"
	echo "  export SIMPATH=/opt/fairsoft/current"
}

pre_remove() {
	:
}

post_remove() {
	:
}
