.TH VPS 1
.SH NAME
vps \- interactive process tree viewer
.SH SYNOPSIS
.B vps
[\fIOPTION\fR]
.SH DESCRIPTION
.PP
\fBvps\fR is a perl script which provides a terminal\-based interactive view of
all process, in a tree\-structured format. That is, the processes are listed
in parent\-child order, with children indented below their parents. \fBvps\fR
also provides for signalling selected process, and for displaying process
environment variables, and open files.
.PP
The basic display is separated into a top area, where the process tree is
displayed. and a bottom three lines, where additional details on the currently
selected process is displayed.
.PP
The top area includes the tree structure, the process id, and the short name of
the process without arguments. A full command and arguments (subject to fit
within the window) can be displayed below by selecting a process. To the right
of tree structure the following columns are displayed: the process owner (bold
if changed), the start time, the memory usage, and the state.
.PP
The bottom area of the selected process shows on the first line the current
processes' command and arguments. The next line shows the process I.D., the
termainal, the user and group, the memory and resident memory. The third line
shows the process start time, the elapsed time (not currently working under
OS X), and the system time and percentage used.
.PP
The top region is scrollable if the entire process tree does not fit. The
separator between the top and bottom sections works as a scrollbar, displaying
what portion of the scrollable area is currently being viewed.
.SH OPTIONS
.TP
\fB\-h\fR
Display help and exit
.TP
\fB\-n\fR
Non\-interactive mode
.SH USAGE
.PP
\fBvps\fR uses vi\-style commands, with some emacs\-style additions.
.PP
Many operations involve switching the top display to view some other
information (environment variables, open files, help, or a list of signals).
The top view is still controlled with the same characters. To return to the
main view, press "q". In the Signal view, once you have selected the desired
signal, press "S" to send that signal to the current process.
.PP
Cursor Motion Commands:
.TP
\fBj\fR, \fB^N\fR
Move cursor down one line
.TP
\fBk\fR, \fB^P\fR
Move cursor up one line
.TP
\fB^F\fR
Move cursor down one screen
.TP
\fB^B\fR
Move cursor up one screen
.TP
\fB^E\fR
Scroll screen upwards
.br
(cursor remains on same line if possible)
.TP
\fB^Y\fR
Scroll screen downwards
.br
(cursor remains on same line if possible)
.TP
\fB^L\fR
Redraw screen
.PP
Other Commands:
.TP
\fBspace\fR
Rebuild list of processes and redisplay
.TP
\fB.\fR
Update data displayed for current process
.TP
\fBe\fR
Show environment variables for current process
.TP
\fBo\fR
Show open files for current process
.br
(not on OS X)
.TP
\fBS\fR
Send a signal to current process
.TP
\fBq\fR
quit
.TP
\fBnumber\fR
Enter a process ID, and press return to set current process
.br
(if it exists)
.TP
\fB/\fR
Enter a string to search forwards for, and press return
.br
(searches program, arguments, user, and group)
.TP
\fB?\fR
Same as "/" but searches backwards
.TP
\fBn\fR
Repeat last search
.TP
\fB\-\fR
Use narrower indent in tree\-structured display
.TP
\fB=\fR
Use wider indent in tree\-structured display
.TP
\fBh\fR
Help
.SH COMPATIBILITY
.PP
\fBvps\fR is almost exclusively used by the author on xterms. It is written to be
terminal independent, but does have xterm\-specific enhancements. Other
terminals (or their termcap descriptions) may not provide adequate support to
function properly.
.PP
Code modifications are possible, but the code is very crufty, having been
drafted together from different pieces of old projects. Some of the terminal
display functions seem to have support for HP, Dec, and other operating
systems, but this is largely cruft, not actual support.
.SH AUTHOR
.TP
.B vps
written by Thomas A. Fine
.TP
.B vps(1)
written by Tim Yang, based on the online vps readme
.SH COPYRIGHT
.PP
Copyright \(co 2007 Thomas A. Fine
.PP
Freely redistributable in whole or in part, provided the author's credit is
preserved.
.PP
http://hea\-www.harvard.edu/~fine/Tech/vps.html
