# decanet.ru
# coding=utf-8
emoticons = {
	'aa.gif': ['O:-)', 'O:)', 'O+)', 'O=)', '0:-)', '0:)', '0+)', '0=)'],
	'ab.gif': [':-)', ':)', '=)', '+)'],
	'ac.gif': [':-(', ':(', '+(', '=('],
	'ad.gif': [';-)', ';)', '^_~'],
	'ae.gif': [':-P', ':P', ':-p', ':p', '+P', '=P', '+p', '=p', ':-b', ':b', '+b', '=b'],
	'af.gif': ['8-)', '8)', 'B)'],
	'ag.gif': [':-D', ':D', '+D', '=D'],
	'ah.gif': [':-[', ':[', ';-.'],
	'ai.gif': ['=-O', '=O', '=-o', '=0', 'O_O', 'O_o', 'o_O', 'O_0', 'o_0', '0_O', '0_o'],
	'aj.gif': [':-*', ':*', ':-{}', ':{}', '+{}', '={}', '^.^'],
	'ak.gif': [':`(', ':-`('],
	'al.gif': [':-X', ':-x', 'X:', 'x:', ':-#', ':#'],
	'am.gif': ['>:o', '>:O', '>+O', '>:o', '>+o', ':-@'],
	'an.gif': [':-|', ':|', '=|'],
	'ao.gif': [':-/'],
	'ap.gif': ['*JOKINGLY*', '8P', '8p'],
	'aq.gif': [']:->', '}:->', ']:>', '}:>', '>:-]', '>:]', '*DIABLO*'],
	'ar.gif': ['[:-}', '[:}'],
	'as.gif': ['*KISSED*'],
	'at.gif': [':-!', ';-!', ':!', ';!', ':-~', ';-~'],
	'au.gif': ['*TIRED*', '|-0'],
	'av.gif': ['*STOP*'],
	'aw.gif': ['*KISSING*'],
	'ax.gif': ['@}->--', '@}-:--', '@>}--`---'],
	'ay.gif': ['*THUMBS UP*', '*GOOD*'],
	'az.gif': ['*DRINK*'],
	'ba.gif': ['*IN LOVE*'],
	'bb.gif': ['@='],
	'bc.gif': ['*HELP*'],
	'bd.gif': ['\m/'],
	'be.gif': ['%)', '%-)', ':$'],
	'bf.gif': ['*OK*'],
	'bg.gif': ['*WASSUP*', '*SUP*'],
	'bh.gif': ['*SORRY*'],
	'bi.gif': ['*BRAVO*'],
	'bj.gif': ['*ROFL*'],
	'bk.gif': ['*PARDON*', '=]'],
	'bl.gif': ['*NO*'],
	'bm.gif': ['*CRAZY*'],
	'bn.gif': ['*UNKNOWN*'],
	'bo.gif': ['*DANCE*'],
	'bp.gif': ['*YAHOO*', '*YAHOO!*'],
	'bq.gif': [';D', '*ACUTE*'],
	'br.gif': ['*BB*'],
	'bs.gif': ['*BYE*'],
	'bt.gif': ['*HI*'],
	'bu.gif': ['*HAPPY*'],
	'bv.gif': ['*LOL*'],
	'bw.gif': ['*SCRATCH*'],
	'bx.gif': ['*YEEES!*'],
	'by.gif': ['*BEEE*'],
	'bz.gif': ['*BOSS*'],
	'ca.gif': ['*SARCASTIC*'],
	'cb.gif': ['*BOAST*'],
	'cd.gif': ['*db*'],
	'ce.gif': ['*HOHO*'],
	'cf.gif': ['*SHOUT*'],
	'cg.gif': ['*VAVA*'],
	'ch.gif': ['*CENSORED*'],
	'ci.gif': ['*SEARCH*'],
	'cj.gif': ['*BEACH*'],
	'ck.gif': ['*FOCUS*'],
	'cl.gif': ['*HUNTER*'],
	'cm.gif': ['*GIRL_CRAY*'],
	'cn.gif': ['*GIRL_CRAZY*'],
	'co.gif': ['*HOSPITAL*'],
	'cp.gif': ['*GIRL_IN_LOVE*'],
	'cq.gif': ['*PINKGLASSES*'],
	'cr.gif': ['*HYSTERIC*'],
	'cs.gif': ['*TENDER*'],
	'ct.gif': ['*SPRUSE_UP*'],
	'cu.gif': ['*FLIRT*'],
	'cv.gif': ['*GIVE_HEART*'],
	'cw.gif': ['*CURTSEY*'],
	'cx.gif': ['*FEMINIST*'],
	'cy.gif': ['*GIRL_DRINK*'],
	'cz.gif': ['*HAHA*'],
	'da.gif': ['*IMPOSSIBLE*'],
	'db.gif': ['*SIGH*'],
	'dc.gif': ['X-)', 'X)'],
	'dd.gif': ['*SLOW*'],
	'de.gif': ['*MOIL*'],
	'df.gif': ['*YES*'],
	'dg.gif': ['*MEGA_SHOK*'],
	'dh.gif': ['*THANK*'],
	'di.gif': ['*KING*'],
	'dj.gif': ['*LAZY*'],
	'dk.gif': ['*FRIEND*'],
	'dl.gif': ['*PUNISH*'],
	'dm.gif': ['*WIZARD*'],
	'dn.gif': ['*V*'],
	'do.gif': ['*SPITEFUL*'],
	'dp.gif': ['*TEASE*'],
	'dr.gif': ['*SCARE*'],
	'ds.gif': ['*THIS*'],
	'dt.gif': ['*PAINT*'],
	'du.gif': ['*TRAINING*'],
	'dv.gif': ['dv'],
	
}