post_install() {
  echo "to use teiler you need to copy /usr/share/doc/teiler/config.example to $HOME/.config/teiler/config"
  echo "Optional dependencies for teiler:"
  echo " "
  echo "mtpaint:             for editing images"
  echo "byzanz:              for recording video in gif format"
  echo "fb-client:           for uploading to a filebin server"
  echo "dunst:               notification support"
  echo "notification-daemon: another option for notifications"
}

