--- Makefile	2006-12-14 12:34:18.000000000 +0100
+++ Makefile.patched	2009-11-17 15:04:30.000000000 +0100
@@ -14,11 +14,11 @@
 
 # Directory for Standard .qcl files
 
-QCLDIR = /usr/local/lib/qcl
+QCLDIR = ../../pkg/qcl/usr/lib/qcl
 
 # Path for qcl binaries
 
-QCLBIN = /usr/local/bin
+QCLBIN = ../../pkg/qcl/usr/bin
 
 ARCH = `g++ -dumpmachine || echo bin`
 
