_depmod() {
	EXTRAMODULES=extramodules-3.18-ARCH
	depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
}

post_install() {
	cat << EOF
===> You may load sysdig-probe module before starting sysdig:
===> # modprobe sysdig-probe
EOF
	_depmod
}

post_upgrade() {
	_depmod
	echo 'In order to use the new version, reload sysdig-probe module manually.'
}

post_remove() {
	_depmod
}

# vim:set ts=2 sw=2 et:
