# Maintainer: Xavier Devlamynck <magicrhesus@ouranos.be>

# Generated by Xyne::Arch::CPAN 0.07

pkgname=perl-asterisk-ami
pkgver=0.2.8
pkgrel=1
pkgdesc="Perl module for interacting with the Asterisk Manager Interface"
arch=('i686' 'x86_64')
url="http://search.cpan.org/~greenbean/Asterisk-AMI-v$pkgver/"
license=('Artistic 2.0')
source=(http://search.cpan.org/CPAN/authors/id/G/GR/GREENBEAN/Asterisk-AMI-v$pkgver.tar.gz)
md5sums=('620ab0d0470d8c95920ff2f25c3bbbb7')
depends=('perl-anyevent>=5.20' 'perl-digest-md5' 'perl-parent' 'perl-version')
makedepends=('perl-extutils-makemaker')
optdepends=('perl-ev' 'perl-net-ssleay')
provides=('perl-asterisk-ami-common-dev=0.2.8' 'perl-asterisk-ami-common=0.2.8' 'perl-asterisk-ami=0.2.8')
options=(!emptydirs)

build() {
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Makefile.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor
    make
    make install DESTDIR="${pkgdir}"

  else
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Build.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Build.PL INSTALLDIRS=vendor
    ./Build 
    ./Build install destdir=${pkgdir}

  else
    echo "error: failed to detect build method for $pkgname"
    echo "you may be able to fix this by editing the PKGBUILD"
    return 1
  fi fi

  # remove perllocal.pod and .packlist
  find ${pkgdir} -name perllocal.pod -delete
  find ${pkgdir} -name .packlist -delete
}

# vim:set ts=2 sw=2 et:
