# Contributor: Aditya Mahajan <aditya DOT mahajan AT yale DOT edu>
# Package generated by cabal2arch 0.5.2
pkgname=haskell-teams
pkgrel=1
pkgver=0.0.2.1
pkgdesc="Graphical modeling tools for sequential teams"
url="http://hackage.haskell.org/cgi-bin/hackage-scripts/package/teams"
license=('GPL')
arch=('i686' 'x86_64')
makedepends=('ghc' 'haskell-cabal' 'haskell-fgl>=5.4' 'haskell-graphviz>=2009.5.1')
depends=('ghc' 'haskell-cabal' 'haskell-fgl>=5.4' 'haskell-graphviz>=2009.5.1')
options=('strip')
source=(http://hackage.haskell.org/packages/archive/teams/0.0.2.1/teams-0.0.2.1.tar.gz)
install=haskell-teams.install
md5sums=('438cb5a8e0ab8e289e443f75143207b2')
build() {
    cd $startdir/src/teams-0.0.2.1
    runhaskell Setup configure --prefix=/usr || return 1
    runhaskell Setup build                   || return 1
    runhaskell Setup register   --gen-script || return 1
    runhaskell Setup unregister --gen-script || return 1
    install -D -m744 register.sh   $startdir/pkg/usr/share/haskell/$pkgname/register.sh
    install    -m744 unregister.sh $startdir/pkg/usr/share/haskell/$pkgname/unregister.sh
    runhaskell Setup copy --destdir=$startdir/pkg || return 1
}
