#
# CA-certificates ICP-Brasil
#

post_install() {
  echo '#'
  echo '# CA-certificates ICP-Brasil installed'
  echo '#'
  echo '# Refreshing list of trusted CA-certificates...'
  echo '#'
  update-ca-certificates --fresh
}

post_remove() {
  echo '#'
  echo '# CA-certificates ICP-Brasil removed'
  echo '#'
  echo '# Refreshing list of trusted CA-certificates...'
  echo '#'
  update-ca-certificates --fresh
}

