#!/bin/bash
#
# update-guestfs-appliance: download and install a guestfs binary appliance
# Copyright (C) 2013 Nikos Skalkotos <skalkoto@gmail.com>
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

VERSION=1.22.0
SHA512SUM="fa8bfe05d6f567bcb73efec764b85c01a545e965f3992fc40567e2679e7a7f65316daece1cac9a63d7d8a0b03e13fc1548d4d361c7bfd0efb99dd3ca6a0293bd"

set -e

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root" >&2
	exit 1
fi

echo >&2
echo "Downloading binary appliance v$VERSION for libguestfs ... " >&2
echo >&2

TMP=$(mktemp -d)
trap "rm -rf $TMP" EXIT

cd $TMP
wget http://libguestfs.org/download/binaries/appliance/appliance-${VERSION}.tar.xz

echo -n "Checking checksum ... " >&2

checksum=$(mktemp --tmpdir="$TMP")
echo "$SHA512SUM appliance-${VERSION}.tar.xz" > "$checksum"

sha512sum -c "$checksum"

echo >&2
echo "Extracting binary appliance files:" >&2
tar -xvf appliance-${VERSION}.tar.xz

echo >&2
echo "Copying appliance files to /usr/lib/guestfs: " >&2
install -v -m644 -o root -g root --backup=none "$TMP/appliance/"{kernel,initrd,root,README.fixed} /usr/lib/guestfs

echo >&2
echo "Binary appliance installation finished successfully!" >&2
