#!/bin/sh
cd /opt/df_linux
export SDL_DISABLE_LOCK_KEYS=1 # Work around for bug in Debian/Ubuntu SDL patch.
#export SDL_VIDEO_CENTERED=1    # Centre the screen.  Messes up resizing.

# Really we shouldn't need this, but...
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"./libs" # Update library search path.
export LD_PRELOAD=/usr/lib/libdfconnect.so
./dwarfort.exe "$@"
