# PKGBUILD generated by pacpan
pkgname=perl-directory-transactional
_realname=Directory-Transactional
pkgver=0.07
pkgrel=1
pkgdesc="ACID transactions on a directory tree"
arch=(i686 x86_64)
license=('mit')
url="http://search.cpan.org/~nuffin/Directory-Transactional"
options=(!emptydirs)

depends=('perl-scope-guard' 'perl-directory-scratch' 'perl' 'perl-mouse' 'perl-file-nfslock' 'perl-hash-util-fieldhash-compat' 'perl-data-stream-bulk' 'perl-test-exception' 'perl-data-uuid' 'perl-test-tempdir' 'perl-namespace-clean' 'perl-set-object' 'perl-path-class' 'perl-test-use-ok')

#provides=('Directory-Transactional')
provides=('directory-transactional=0.07' 'Directory::Transactional=0.07' 'perl-directory-transactional=0.07' 'Directory::Transactional::AutoCommit=0.07' 'perl-directory-transactional-autocommit=0.07' 'Directory::Transactional::Stream=0.07' 'perl-directory-transactional-stream=0.07' 'Directory::Transactional::TXN::Root=0.07' 'perl-directory-transactional-txn-root=0.07' 'Directory::Transactional::TXN::Nested=0.07' 'perl-directory-transactional-txn-nested=0.07' 'Directory::Transactional::TXN=0.07' 'perl-directory-transactional-txn=0.07')

source=(http://search.cpan.org/CPAN/authors/id/N/NU/NUFFIN/Directory-Transactional-0.07.tar.gz)
md5sums=('441a9e52a0168dd49a5c624d758495c2')

build() {
  _expected_dir="${srcdir}/${_realname}-${pkgver}"
  if [ -d "$_expected_dir" ]; then
    cd "$_expected_dir"
  else
    _expected_dir="${srcdir}/$(bsdtar -t -f $(basename $source) | head -n1)"
    if [ -d "$_expected_dir" ]; then
      cd "$_expected_dir"
    else
      _makefile=$(find $srcdir -iname Makefile.PL)
      if [ ! -z "$_makefile" ]; then
        _expected_dir=$(dirname $_makefile)
        if [ -d "$_expected_dir" ]; then
          cd "$_expected_dir"
        else
          echo "[1;31mERROR[0m unable to detect source directory"
          echo "[1;34m-->[0m this is often due to CPAN's lack of standard naming conventions"
          echo "[1;34m-->[0m it may be possible to fix this by adjusting the build function in the PKGBUILD"
        fi
      fi
    fi
  fi
  # install module in vendor directories.
  PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor || return 1
  make  || return 1
  make install DESTDIR=${pkgdir} || return 1

  # remove perllocal.pod and .packlist
  find ${pkgdir} -name perllocal.pod -delete
  find ${pkgdir} -name .packlist -delete
}
# END OF PACPAN PKGBUILD

