0a1,6
> # Added for ArchLinux PKGBUILD. (Jul 20 2007) - Caelyl
> PREFIX = /usr
> 
> INSTALL = /bin/install -c -D -m 755
> # END
> 
28a35,39
> # Added for ArchLinux PKGBUILD. (Jul 20 2007) - Caelyl
> install:
> 		$(INSTALL) $(TARGET) $(PREFIX)/bin/$(TARGET)
> # END
> 
