post_install() {
    echo ""
    echo "--------------------------------------------------------------------------------"
    echo "You must add '/usr/local/bsvc/bin/' to your PATH in order to use bsvc."
    echo "You can do this by appending the following line to your .{bashrc, zshrc, ...}:"
    echo ""
    echo "export PATH=\$PATH:/usr/local/bsvc/bin/"
    echo "--------------------------------------------------------------------------------"
    echo ""
}

post_remove() {
    echo ""
    echo "--------------------------------------------------------------------------------"
    echo "Remember to delete '/usr/local/bsvc/bin/' from your PATH."
    echo "Have a look into your .{bashrc, zshrc, ...} and delete the following line:"
    echo ""
    echo "export PATH=\$PATH:/usr/local/bsvc/bin/"
    echo "--------------------------------------------------------------------------------"
    echo ""
}
