pre_install() {
  /bin/true
}

post_install() {
  id couchdb &>/dev/null || \
    useradd -r -c "CouchDB daemon" -g daemon -d /var/lib/couchdb -s /bin/false couchdb
  chown -R couchdb:daemon /var/{lib,log,run}/couchdb
}

pre_upgrade() {
  useradd -r -c "CouchDB daemon" -g daemon -d /var/lib/couchdb couchdb
}

post_upgrade() {
  chown -R couchdb:daemon /var/{lib,log,run}/couchdb
}

pre_remove() {
  /bin/true
}

post_remove() {
  userdel couchdb &>/dev/null
}

op=$1
shift
$op $*
