note() {
    printf "${blue}==>${yellow} NOTE:$2${bold} $1${all_off}\n"
}

msg() {
  echo
  note "--------------------------------------------------"
  note "If you do not have permissions to the device then "
  note "  make sure your user-name correct in the file:   "
  note "  /etc/udev/rules.d/80-FinalKey.rules             "
  note "--------------------------------------------------"
  note "Type finalkey --help to begin."
}

post_install() {
  msg
}

post_upgrade() {
  msg
}
