# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=bin_utils
pkgname=ruby-$_gemname
pkgver=0.0.6
pkgrel=1
pkgdesc='Faster alternative to String#unpack and Array#unpack, though not as complete as those methods'
arch=(i686 x86_64)
url='https://github.com/funny-falcon/bin_utils'
license=(MIT)
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('ec0c705772011741d0bcd946ac58688a56e428d4')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"

  rm -rf "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/ext"
}
