#!/bin/sh
APPBASE="/usr/share/java/greenfoot"
JAVAPATH="/usr/lib/jvm/java-7-openjdk"
CP="$APPBASE/bluej.jar:$JAVAPATH/lib/tools.jar"
"$JAVAPATH/bin/java" -cp "$CP" bluej.Boot -greenfoot=true -bluej.compiler.showunchecked=false "$@"
