post_install() {
  cat <<EOF

*** The Gambit-C compiler is renamed to gambitc. The original name of the
*** compiler was gsc, the same as ghostscript's compiler.

EOF
}

post_upgrade() {
  cat <<EOF

*** The Gambit-C compiler is renamed to gambitc. The original name of the
*** compiler was gsc, the same as ghostscript's compiler.

EOF
}

# Local Variables:
# mode: shell-script
# sh-basic-offset: 2
# End:
# vim:set ts=2 sw=2 et:
