post_install() {
  echo "Copy /usr/share/pykeylogger/pykeylogger.ini to home somewhere"
  echo "Edit the \"Log Directory\" location to point somewhere in home (it will be created automatically)"
  echo "Run pykeylogger -c \"path/to/ini/file\""
}

post_upgrade() {
  echo "Copy /usr/share/pykeylogger/pykeylogger.ini to home somewhere"
  echo "Edit the \"Log Directory\" location to point somewhere in home (it will be created automatically)"
  echo "Run pykeylogger -c \"path/to/ini/file\""
}
