#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/sbin/neard`
case "$1" in
  start)
    stat_busy "Starting Near Field Communication Daemon"
    [ -z "$PID" ] && /usr/sbin/neard
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon neard
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Near Field Communication Daemon"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon neard
      stat_done
    fi
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
