# Generated by Xyne::Arch::CPAN 0.07

pkgname=perl-http-oai
pkgver=3.28
pkgrel=1
pkgdesc="API for the OAI-PMH"
arch=('i686' 'x86_64')
url="http://search.cpan.org/dist/HTTP-OAI/"
license=('BSD')
source=('http://search.cpan.org/CPAN/authors/id/T/TI/TIMBRODY/HTTP-OAI-3.28.tar.gz')
md5sums=('09fb4ba4b9da2cda3910fa4b31273568')
depends=('perl-cgi' 'perl-encode>=2.12' 'perl-http-message' 'perl-libwww>=6.02' 'perl-uri' 'perl-xml-libxml>=1.6' 'perl-xml-sax')
makedepends=('perl-extutils-makemaker')
provides=('perl-http-oai-debug' 'perl-http-oai-encapsulation' 'perl-http-oai-error' 'perl-http-oai-getrecord' 'perl-http-oai-harvester' 'perl-http-oai-header' 'perl-http-oai-headers' 'perl-http-oai-identify' 'perl-http-oai-listidentifiers' 'perl-http-oai-listmetadataformats' 'perl-http-oai-listrecords' 'perl-http-oai-listsets' 'perl-http-oai-metadata' 'perl-http-oai-metadata-mets' 'perl-http-oai-metadata-oai_dc' 'perl-http-oai-metadata-oai_eprints' 'perl-http-oai-metadata-oai_identifier' 'perl-http-oai-metadataformat' 'perl-http-oai-partiallist' 'perl-http-oai-record' 'perl-http-oai-repository' 'perl-http-oai-response' 'perl-http-oai-resumptiontoken' 'perl-http-oai-saxhandler' 'perl-http-oai-set' 'perl-http-oai-useragent')
options=(!emptydirs)

build() {
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Makefile.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor || return 1
    make  || return 1
    make install DESTDIR="${pkgdir}" || return 1

  else
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Build.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Build.PL INSTALLDIRS=vendor || return 1
    ./Build  || return 1
    ./Build install destdir=${pkgdir} || return 1

  else
    echo "error: failed to detect build method for $pkgname"
    echo "you may be able to fix this by editing the PKGBUILD"
    return 1
  fi fi

  # remove perllocal.pod and .packlist
  find ${pkgdir} -name perllocal.pod -delete
  find ${pkgdir} -name .packlist -delete
}

# vim:set ts=2 sw=2 et:

