post_install() {
	post_upgrade
}

post_upgrade() {
    cat >&2 <<EOF

==> emacs-for-python installation notes:
    ---------------------------------------------------------------------
    Set pymacs for python2 in ~/.bashrc:
    export PYMACS_PYTHON=python2

    Put in ~/.emacs:
    (load-file "/usr/share/emacs/site-lisp/emacs-for-python/epy-init.el")
    ---------------------------------------------------------------------

EOF
}
