post_install() { 
  echo "This program requires that you register your own API keys for"
  echo "the New York Times, for the search, popular, and newswire"
  echo "APIs. Store these in JSON format in ~/.config/nyt/keys.json as"
  echo "follows:"
  echo "{"
  echo "  \"search\": \"search-api-key\","
  echo "  \"popular\": \"popular-api-key\","
  echo "  \"newswire\": \"newswire-api-key\""
  echo "}"
}

# vim:set ts=2 sw=2 et:
