# -*- mode: sh; -*-

note () {
    cat << EOF

==> To start using this package, add the lines below to your .emacs:
    (add-to-list 'load-path "/usr/share/emacs/site-lisp/expand-region")
    (require 'expand-region)
    ;; Optionally bind a keyboard shortcut to expand-region command
    (global-set-key (kbd "C-@") 'er/expand-region)

EOF
}

post_install() {
    note
}

post_upgrade() {
    note
}


