#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

NAME=mentoHUST
LOWER=mentohust
DAEMON=/usr/bin/mentohust
CLIENT=/sbin/dhcpcd

case "$1" in
	start)
		if ! ck_daemon $NAME; then
			echo "$NAME is already running.  Try '/etc/rc.d/$LOWER restart'"
			exit
		fi
		stat_busy "Starting $NAME"
		$DAEMON >& /dev/null &
		add_daemon $NAME
		stat_done
		;;
	stop)
		stat_busy "Stopping $NAME"
		$DAEMON -k >& /dev/null &
		$CLIENT -k >& /dev/null &
		rm_daemon $NAME
		stat_done
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "usage: $0 {start|stop|restart}"  
esac
