#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

NAME=mentoHUST
DAEMON=/usr/bin/mentohust

case "$1" in
	start)
		if ! ck_daemon $NAME; then
			echo "$NAME is already running.  Try '/etc/rc.d/$NAME restart'"
			exit
		fi
		stat_busy "Starting $NAME"
	       if [ -z `pidof $DAEMON` ]; then
			$DAEMON >& /dev/null &
	       fi
        	add_daemon $NAME
        	stat_done
        fi
		;;
	stop)
		stat_busy "Stopping $NAME"
		$DAEMON -k >& /dev/null
		/sbin/dhcpcd eth0 -k
		rm_daemon $NAME
		stat_done
		;;
	restart)
        $0 stop
        $0 start
		;;
	*)
		echo "usage: $0 {start|stop|restart}"  
esac

