#!/bin/sh
mingw64_prefix=/usr/i686-w64-mingw32

export CFLAGS="-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions --param=ssp-buffer-size=4"
export CXXFLAGS="-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions --param=ssp-buffer-size=4"
../configure --host=i686-w64-mingw32 --enable-shared --enable-static --prefix=${mingw64_prefix} "$@"

