# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Alireza Savand <alireza.savand@gmail.com>

_gemname=virtus
pkgname=ruby-$_gemname
pkgver=1.0.3
pkgrel=1
pkgdesc='Attributes on Steroids for Plain Old Ruby Objects'
arch=(any)
url='https://github.com/solnic/virtus'
license=(MIT)
depends=(ruby ruby-descendants_tracker ruby-equalizer ruby-coercible ruby-axiom-types)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('13333d7a615f6572f0c648bfe8850d62b8335979')


package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
