post_install() {
  
  echo
  echo ">>> Enable Multi Edit plugin:"
  echo ">>> Edit-> Preferences -> Plugins -> Multi Edit"
  echo
  echo ">>> Hot keys:"
  echo ">>> <Ctrl><Shift><C> initiates edit mode"
  echo ">>> <Ctrl><Home> sets start point"
  echo ">>> <Ctrl><End> sets end point"
  echo ">>> <Ctrl><E> sets end point"
  echo ">>> <Ctrl><Enter> column selection"
  echo ">>> <Esc> exits mode"
  echo
}

post_upgrade() {
    post_install
}
