# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=rails-deprecated_sanitizer
pkgname=ruby-$_gemname
pkgver=1.0.3
pkgrel=1
pkgdesc='Deprecated sanitizer API extracted from Action View.'
arch=(any)
url='https://github.com/rails/rails-deprecated_sanitizer'
license=(MIT)
depends=(ruby ruby-activesupport-4.2.0.beta2)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('00c2c5b1c7b7340e8ba0759b61fe74fea5fbb089')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
