# Maintainer: Reuben Castelino <projectdelph[at]gmail[dot]com>
# Generated by gem2arch

_gemname=green_shoes
pkgname=ruby-$_gemname
pkgver=1.1.362
pkgrel=1
pkgdesc="Green Shoes"
arch=('any')
url="http://github.com/ashbb/green_shoes"
license=('GPL')
depends=('ruby')
makedepends=('rubygems')
source=(http://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
md5sums=('4b07cb127ab480ff10acad733d1443be')
sha1sums=('ee409c64c5acbce49d60aa105dab314389f19931')

package() {
  cd "$srcdir"
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install -i "$pkgdir$_gemdir" $_gemname-$pkgver.gem
}
