# arg 1:  the new package version
post_install() {
cat << EOF
==> Ensure your system have 32bit 3D rendering support:
	> Install 'lib32-nvidia-utils' if you use 'nvida' graphics driver.
	> Install 'lib32-catalyst-utils' if you use 'catalyst' graphics driver.
	> For other graphics drivers, check 'lib32-*-dri'.
EOF
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $1
}

op=$1
shift
$op $*
