post_install() {
  /bin/cat << EOF

Adobe Air SDK has been installed to /opt/adobe-air-sdk

You can run Adobe Air apps using the SDK by first unzipping them, and then running: /opt/adobe-air-sdk/bin/adl -nodebug /path/to/app/META-INF/AIR/application.xml /path/to/app &

To run Adobe Air apps directly from the .air file, install the 'adobe-air' package

The Adobe Air SDK is 32bit; if you're running x86_64, the appropriate lib32* are required

EOF
}

