post_install() {
	echo "==> You may want to add yourself to the games group :"
	echo "==> sudo gpasswd -a <username> games"
	echo "==> Install your custom songs in /opt/sm-ssc/Songs ; you can find"
	echo "==> content at http://code.google.com/p/sm-ssc/wiki/FindingContent"
}

post_remove() {
	echo "==> Some files were left over in /opt/sm-ssc, such as songs."
	echo "==> You can delete them if you don't plan on reinstalling sm-ssc."
}
