post_install() {
    echo ""
    echo "You need to add a line:"
    echo "export OSL_HOME=/usr/share/gpsshogi"
    echo "in your .bashrc"
    echo ""
    echo "To play a game, you should use a GUI program like Shogidokoro"
    echo "Shogidokoro can be run with mono: mono Shogidokoro.exe"
    echo "Then, go 対局 -> エンジン管理 -> 追加 and open /usr/bin/gpsusi"
    echo ""
    echo "Shogidokoro's Homepage: http://www.geocities.jp/shogidokoro/"
    echo ""
}
