post_install() {
	gtk-update-icon-cache -qtf /usr/share/icons/Mint-X
	gtk-update-icon-cache -qtf /usr/share/icons/Mint-X-Dark
	gtk-update-icon-cache -qtf /usr/share/pixmaps/pidgin/tray/Mint-X
	gtk-update-icon-cache -qtf /usr/share/pixmaps/pidgin/tray/Mint-X-Dark
	gdk-pixbuf-query-loaders --update-cache
}

post_upgrade() {
	post_install
}

post_remove() {
	gdk-pixbuf-query-loaders --update-cache
}
