#!/bin/bash
export WINEPREFIX="$HOME/.config/ultravnc-viewer"
export WINEDLLOVERRIDES="mscoree,mshtml,winemp3.acm="

if [ ! -d "$WINEPREFIX" ] ; then
  mkdir -p "$WINEPREFIX" || exit 1
  wineboot -u
fi

wine /usr/share/ultravnc-viewer/vncviewer.exe "$@"
