post_install() {
  echo '==> The default location of the configuration files is'
  echo '==> /etc/hostapd where you can find some config examples.'
  echo '==> Some of the key configuration files are:'
  echo '==> hostapd.conf --> primary configuration file'
  echo '==> hostapd.allow --> MAC allow list'
  echo '==> hostapd.deny --> MAC deny list'
  echo '==>'
  echo '==> This how-to is recommended:'
  echo '==> http://wireless.kernel.org/RTFM-AP'
}

post_upgrade() {
	post_install
}
