
pre_install() {
  groupadd -r ovs
}

post_install() {
  if [ ! -f /etc/openvswitch/ovs-vswitchd.conf.db ]; then
    ovsdb-tool create /etc/openvswitch/ovs-vswitchd.conf.db /usr/share/openvswitch/vswitch.ovsschema
  fi

  dkms add -m openvswitch -v ${1%-*}
  dkms build -m openvswitch -v ${1%-*}
}

pre_remove() {
  dkms remove -m openvswitch -v ${1%-*} --all
}

post_remove() {
  groupdel ovs
}

# vim:set ts=2 sw=2 et:

