post_install() {
cat <<"EOF"
To deploy the web application, use:

$ # Setup app directory, copy files
$ mkdir /path/to/webapps/livegrep
$ cd /path/to/webapps/livegrep
$ cp -a /usr/lib/livegrep-git/* .
$ mkdir web/log

$ # Install Node.js dependencies
$ npm install

$ # Create and edit web/config.local.js, see web/config.js for options

$ # Run the indexer
$ node web/index.js

$ # Run the codesearch server
$ node web/cs_server.js &

$ # Run the application server
$ node web/web_server.js
EOF
}
