pre_install() {
	if [ -f "index.php?wpfb_dl=2420" ]; then
		mv 'index.php?wpfb_dl=2420' "torque-$1.tar.gz"
	fi
}

pre_upgrade() {
        if [ -f "index.php?wpfb_dl=2420" ]; then
                mv 'index.php?wpfb_dl=2420' "torque-$1.tar.gz"
        fi
}

post_install() {
	echo "Torque needs to be configured! Please refer to 'https://wiki.archlinux.org/index.php/TORQUE'."
}

# vim:set ts=2 sw=2 et:
