post_install() {

 echo -e "\033[0;31m IMPORTANT"
 echo -e "\033[0;0m  Run \033[0;32m 'burg-install --root-directory=/boot/efi --no-floppy --recheck' \033[0;0m as root for installing to UEFI SYSTEM PARTITION"
 echo -e "\033[0;0m  Run \033[0;32m 'burg-mkconfig -o /boot/efi/boot/burg/burg.cfg' \033[0;0m as root for generating burg.cfg"
 echo -e "\033[0;0m  Then run efibootmgr to make /boot/efi/boot/burg/burg.efi as default\033[0;0m"

}


post_upgrade() {
        post_install
}


