.TH spinach 1 "2011-04-08" "Spinach 0.3" "Spinach"
.SH NAME
spinach \- A small AUR helper written in Bash.
.SH SYNOPSIS
.B spinach
[options] [operation] [package]
.SH DESCRIPTION
.B spinach
is a very tiny AUR helper written in Bash that will help you download, install, and update packages from the AUR. If you want to learn more about it, please go to the website (on the Floft Wiki): http://floft.net/wiki/Scripts/Spinach
.SH OPTIONS
.IP "-ssl"
Use SSL when downloading packages and information from the AUR. This has no effect on the pacman operations enabled with the '-rep' option.
.IP "-col"
Use color in certian places.
.IP "-rep"
Also use pacman for \fIsearch\fR, \fIprint\fR, and \fIinstall\fR operations. Searching will return results from both the AUR and official repositories. Printing information will return information from pacman if available and the AUR if not. Installing will install via the official repositories if found and attempt to install from the AUR otherwise.
.SH COMMON OPERATIONS
.IP "-s"
Search for the specified package (does not support regex; although, for a regex hack see the website mentioned in the description).
.IP "-p"
Print information for the specified package.
.IP "-i"
Install the specified package.
.IP "-u"
Update packages found on the AUR. This will not update packages in the official repos or packages that have been deleted from the AUR.
.SH DO-IT-YOURSELF OPERATIONS
.IP "-d"
Download the specified package from the AUR and extract the tarball in the current directory.
.IP "-dd"
Download the specified package from the AUR and any AUR dependencies to the current directory.
.IP "-o"
List packages that have a different version than the one in the AUR.
.IP "-do"
Download all the AUR packages that have a different version than the one in the AUR to the current directory.
.SH VARIABLES 
.IP "$EDITOR"
Specify the text editor to use in order to view the PKGBUILD and .install files when installing and upgrading packages. Defaults in this order if not specified: vim emacs vi nano most less more cat
.IP "$SPINTMPDIR"
If specified the spinach build and cache directories will be stored in spinach/ in this folder. If not specified, it will default to $TMPDIR if specified and as a last resort /tmp.
.SH EXAMPLES
spinach -s package
.PP
spinach -p package
.PP
spinach -i package
.PP
spinach -u
.TP
spinach -ssl -p package1 -d package2 -d package3 -dd package4 -do
Specify multiple commands.
.TP
source /usr/bin/spinach -col
Source the spinach script to use in other scripts.
.TP
spinach $(/usr/bin/spinach -s openlp | sed -re 's/^([^:]*).*/-dd \1/g' | tr '\n' ' ')
Download all AUR packages returned from a search.
.SH AUTHOR
Garrett (http://floft.net/contact)
