#!/bin/bash
UA="Spinach/0.2.6"
ssl='';col='';nc=''
AURURL="http%s://aur.archlinux.org"
AURPC="$AURURL/rpc.php?type=%s&arg=%s"

#functions so you can `. spinach -col -ssl`
aur_download() {
	p="$1" #package
	
	if [ -e "$p" ]; then
		echo -ne "${col}Exists${nc}: "; echo "$p"
		return 1
	else
		url="$(curl -sf -A "$UA" "$(printf $AURPC "$ssl" info "$p")" | sed -r '
			s/.*No result found.*//g
			s/.*URLPath":"([^"]+)".*/\1/g
			s/\\\//\//g')"
    		if [ -n "$url" ]; then
			curl -sf -A "$UA" "$(printf "$AURURL$url" "$ssl")" -o "$p.tar.gz"
			tar xzf "$p.tar.gz" || return 1
			rm "$p.tar.gz" || return 1
			echo -ne "${col}Saved${nc}: "; echo "$p/"
		else
			echo -ne "${col}Not Found${nc}: "; echo "$p"
			return 1
		fi
	fi
}
aur_download_deps() {
	p="$1" #package

	aur_download "$p" || return 1
	#get PKGBUILD depends
	if [ -e "$p/PKGBUILD" ]; then
		depends="$(cat "$p/PKGBUILD" | tr '\n' ' ' | \
			grep -Eo " (make)?depends=\([^)]*\)" 2>/dev/null | sed -r "
			s/.*\((.*)\).*/\1/mg
			s/(['\"])([^><=']*)[><=]+[^'\"]*\1/\2/mg
			s/['\"]//mg" | tr '\n' ' ' | sed -r "s/\\\$[^ ]+ //mg")"
	else
		echo -ne "${col}Does not exist${nc}: "; echo "$p/PKGBUILD"
		return 1
	fi
	#find AUR, non-installed depends
	for i in $depends; do
		pacman -Qi $(pacman -Qsq "$i"||echo -h) | \
			grep -E "^(Name|Provides)" | sed -r '
			s/^[^:]*: //mg
			s/=[^ ]*//mg' | tr ' ' '\n' | grep "^$i$" &>/dev/null
		provided="$?"
		pacman -Ssq "$i" | grep "^$i$" &>/dev/null
		official="$?"
		
		if [ "$official$provided" == "11" ] && [ ! -e "$i/" ]; then
			aur_download_deps "$i" || return 1
		fi
	done
}
aur_update() {
	quiet="$1"
	p="$(pacman -Qmq 2>/dev/null)" #packages
	#remove ignored
	ignore="$(grep ^IgnorePkg /etc/pacman.conf | sed -e "s/.*=\ //g")"
	for i in $ignore; do
		p="$(echo "$p" | grep -v "$i")"
	done
	#list of aur packages
	list=""
	for i in $p; do
		list="$list $(printf "$AURPC" "$ssl" info "$i")"
	done
	#get versions from aur 
	inaur="$(curl -s -A "$UA" $list | sed -re '
		s/\{[^}]*"results":"No result found"\}//g
		s/\{+[^}]*Name":"([^"]*)"[^}]*Version":"([^"]*)[^}]*\}+/\1\t\2\n/g')"
	#get installed versions
	inlocal="$(pacman -Qi $p | grep -E '^(Name|Version)' | tr '\n' ' ' | \
		sed -r 's/(Name|Version)\s+: /\n/g' | tail -n +2 | sed 's/ $//g')"
	#find differences
	IFS=$'\n'
	for i in $inaur; do
		name="$(echo $i | cut -f1)"
		#up-to-date version
		up="$(echo $i | cut -f2)"
		#installed version
		in="$(echo "$inlocal" | grep -A 1 "^$name$" | tail -n 1)"
		
		if [ -z "$(echo "$up" | grep "No result found")" ] \
		&& [ -n "$up" ] && [ -n "$in" ] && [ "$up" != "$in" ]; then
			if [ -n "$quiet" ]; then
				echo "$name"
			else
				echo -ne "${col}"; echo -n "$name"
				echo -ne "${nc}"; echo " ($in => $up)"
			fi
		fi
	done
}
aur_display_color() {
	if [ -n "$col" ] && type xargs &>/dev/null; then
		cat /dev/stdin | sed -r 's/^([^: \t]+[^:]*): +/\'$col'\1\'$nc': /g' \
			| xargs -0 echo -en
	else
		cat /dev/stdin
	fi
}
aur_info() {
	curl -A "$UA" "$(printf $AURPC "$ssl" info "$1")" 2>/dev/null | sed -r '
	s/.*No result found.*/Error: Package not found/g
	s/\\"/\&QUOT;/g
	s/.*results":\{(.*)\}\}/\1/g
	s/\",\"/\"\n\"/g
	s/\\\//\//mg
	s/"//mg
	s/^([^:]*):/\1: /mg
	s/\\\\/\\/mg
	s/\&QUOT;/"/mg
	s/^URLPath: /URLPath: https:\/\/aur.archlinux.org/mg' | aur_display_color
	echo
}
aur_search() {
	if [ -n "$rep" ]; then
		pacman -Ss "$1" | sed -r 's/^([^/\s]+\/[^ ]+) [^\n]+$/\1/g' | \
			sed -rn '1h;1!H;${;g;s/\n\s+/: /g;p;}' | aur_display_color
	fi
	curl -A "$UA" "$(printf $AURPC "$ssl" search "$1")" 2>/dev/null | sed -r '
	s/.*(No results found).*/\1\n/g
	s/\\"/\&QUOT;/g
	s/.*\[([^"]*)\]}}/\1/g
	s/\{[^}]*"Name":"([^"]*)",[^}]*,"Description":"([^"]*)"[^}]*\}/\1: \2\n/g
	s/^,//mg
	s/\\\//\//mg
	s/\\\\/\\/mg
	s/\&QUOT;/"/mg
	s/^]}//mg' | aur_display_color
}
aur_download_updates() {
	updates="$(aur_update q)"
	for i in $updates; do
		aur_download "$i"
	done
}
aur_spinach_help() {
	echo -e "${col}Usage${nc}: spinach [options] [operations] [package]
	Options:
	-ssl	Use SSL
	-col	Use color
	-rep	Also use repos for search
	
	Operations:
	-d	Download a package
	-dd	Download a package and AUR dependencies
	-i	Print info for a package
	-s	Search for a package
	-u	List out-of-date packages
	-du	Download all updates"
}
blank_arg() {
	if [ -z "$1" ]; then
		echo -e "${col}Error${nc}: Please specify a package."
		exit 1
	fi
}

while [ -n "$1" ]; do
	case "$1" in
		"-u") aur_update;;
		"-du") aur_download_updates;;
		"-i") shift; blank_arg "$1"; aur_info "$1";;
		"-s") shift; blank_arg "$1"; aur_search "$1";;
		"-d") shift; blank_arg "$1"; aur_download "$1";;
		"-dd") shift; blank_arg "$1"; aur_download_deps "$1";;
		"-ssl") ssl="s";;
		"-col") col='\e[0;31m'; nc='\e[0m';;
		"-rep") rep="y";;
		"--version") echo "$UA";; 
		"-h"|"--help") aur_spinach_help;;
	esac
	shift
done
