# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Babken Vardanyan <483ken@gmail.com>

_gemname=simplecov
pkgname=ruby1.9-$_gemname
pkgver=0.5.4
pkgrel=1
pkgdesc='Code coverage for Ruby 1.9 with a powerful configuration library and automatic merging of coverage across test suites'
arch=(any)
url='http://github.com/colszowka/simplecov'
license=()
depends=(ruby1.9 ruby1.9-multi_json ruby1.9-simplecov-html)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('d7e33725bcc63d98f24b81f12a87074423f91de6')

package() {
  local _gemdir="$(ruby-1.9 -e'puts Gem.default_dir')"
  gem-1.9 install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
