# arg 1:  the new package version
post_install() {
cat << EOF
--> 1) Edit /usr/share/viewvc/viewvc.conf
--> 2) Add these lines in /etc/httpd/conf/httpd.conf in the ScriptAlias section
	ScriptAlias /viewvc "/srv/httpd/cgi-bin/viewvc.cgi"
	ScriptAlias /query "/srv/httpd/cgi-bin/query.cgi"
--> 3) restart apache
EOF
}

# arg 1:  the new package version
# arg 2:  the old package version
pre_upgrade() {
  post_install $1
}

op=$1
shift
$op $*
