whisperer(){
    echo "----------------------------------------------------------------" 
    echo "!!!!!!!!!!!!!!!!!!!!!!!!! IMPORTANT !!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    echo "lib32-catalyst-utils works now with [multilib] repository"
    echo "You _NEED_ to read this:"
    echo "https://bbs.archlinux.org/viewtopic.php?pid=817136#p817136"
    echo "----------------------------------------------------------------"
}

post_install() {
    whisperer
}

post_upgrade() {
    whisperer
}