post_install() {
  echo ""
  echo ""
  echo ""
  echo "IMPORTANT! You must modify the following files as root to configure pcw"
  echo ""
  echo "/usr/bin/pcw_win.sh	(uncomment the desired line)"
  echo "/usr/bin/chat.sh	(read comments and set PREFIX SERVERS and LOG)"
  echo "/usr/bin/cw_color.sh	(set NICK, customize colors, etc..)"
  echo ""
  echo ""
  echo "Use chat.sh to start ii and pcw together with settings define in servers file"
}

post_upgrade() {
  post_install
}
