post_install() {
  modutil -force -dbdir sql:/etc/pki/nssdb/ -add "Latvia eID" -libfile /usr/lib/pkcs11/onepin-otlv-pkcs11.so &>/dev/null
  /usr/bin/update-ca-certificates --fresh &>/dev/null
}

post_upgrade() {
  modutil -force -dbdir sql:/etc/pki/nssdb/ -delete "Latvia eID" &>/dev/null
  post_install
}

pre_remove() {
  echo "nothing?" &>/dev/null
}

post_remove() {
	post_install &>/dev/null
	modutil -force -dbdir sql:/etc/pki/nssdb/ -delete "Latvia eID" &>/dev/null
}
