pkgname=seahorse-plugins

post_install() {
  gconfpkg --install $pkgname
  xdg-icon-resource forceupdate
  update-desktop-database -q
  update-mime-database usr/share/mime
}

pre_upgrade() {
  pre_remove $1
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  gconfpkg --install $pkgname
}

post_remove() {
  xdg-icon-resource forceupdate
  update-desktop-database -q
  update-mime-database usr/share/mime
}
