post_install() {
    echo ">>> You must be a member of the games group for the save-related functionality to work."
    echo ">>> You can edit /opt/windandwater/wnw_config.txt to get fullscreen mode."
}
post_upgrade() {
    post_install
}

post_remove() {
    if [ -d /opt/windandwater ]; then
       echo ">>> You may safely delete /opt/windandwater and its contents (save files) if you don't want them."
    fi
}
