post_install() {
  echo "In case you are installing freesub so it can be used with freenetconfd"
  echo "make sure to add the either of the following lines in /etc/ssh/sshd_config:"
  echo "Subsystem netconf /usr/bin/netconf"
  echo "or you can use the one below where you can change host and port if needed"
  echo "Subsystem netconf /usr/bin/freesub -H 127.0.0.1 -P 1831"
}

post_upgrade() {
  post_install $1
}
