post_install() {
    cat <<EOF
An unofficial patch is available at

  http://sorr.forumotion.net/t27-downloads-streets-of-rage-remake-ports

Sadly there is no reliable download location, so you will have to install it
manually.  Extract the archive and replace SorR.dat at /opt/sorr/.
EOF

    update-desktop-database -q
    gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_upgrade() {
    post_install
}
