#!/bin/bash
unset WINEPREFIX

if [ ! -d "$HOME"/.utorrent ] ; then
  mkdir "$HOME"/.utorrent || exit 1
  ln -s /usr/share/utorrent/utorrent.exe "$HOME"/.utorrent/utorrent || exit 1
  cp /usr/share/utorrent/settings.dat "$HOME"/.utorrent || exit 1
fi

XDG_DATA_HOME=/dev/null WINEDEBUG=-all WINEDLLOVERRIDES="mshtml=" \
    /usr/share/utorrent/wine-executor \
    -e "$HOME"/.utorrent/utorrent -i '/directory:/hide:/minimized' -- "$@"

