#!/bin/bash -e

ClearDumps="yes"  # Clean up "[build]-utorrent.XXXX.dmp" dumps in ~/.uTorrent/
Debug="no"        # Supress _all_ output (even that outside of Wine)

# utorrent -> uTorrent (upstream naming)
if [ -d ~/.utorrent/ ]; then
  mv ~/.utorrent/ ~/.uTorrent/
fi

# Link uTorrent.exe
if [ ! -L ~/.uTorrent/uTorrent.exe ]; then
  # Old
  rm -f ~/.uTorrent/utorrent
  # New
  install -d ~/.uTorrent/
  ln -s /usr/share/utorrent/uTorrent.exe \
        ~/.uTorrent/uTorrent.exe
fi

# Store settings in ~/.uTorrent/
if [ ! -f ~/.uTorrent/settings.dat ]; then
  touch ~/.uTorrent/settings.dat
fi

# Clear piling up memory dumps
if [ "$ClearDumps" = 'yes' ]; then
  rm -f ~/.uTorrent/*.dmp
fi

# Add torrent(s)/magnet link(s)
for i; do  # for i = for i in "$@"
  # Add path in Wine form (e.g. "z:/home/user/Desktop/lol.torrent")
  if [ -f /"${i#?:}" ]; then 
    Files+=(z:"${i#?:}")    # When opened through .desktop or Wine path (e.g. z:/*)
  else
    Files+=(z:"$(pwd)/$i")  # When path only partial or in current directory
  fi
done

# Launch app
if [ "$Debug" = 'no' ]; then
  wine ~/.uTorrent/uTorrent.exe "${Files[@]}" &>/dev/null
else
  wine ~/.uTorrent/uTorrent.exe "${Files[@]}"
fi