# arg 1:  the new package version
post_install() {
  depmod -a

  if [ ! -d /afs ]; then
    mkdir /afs
  fi

  echo "==="
  echo "=== You will want to edit /etc/openafs/ThisCell to be your current cell."
  echo "=== The default is andrew.cmu.edu."
  echo "==="
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $1
}

# arg 1:  the old package version
post_remove() {
  depmod -a
}
