--- Makefile.old	2003-10-05 11:05:39.000000000 -0400
+++ Makefile	2008-03-27 16:41:08.421502876 -0400
@@ -24,10 +24,10 @@
 LIBS += `pkg-config --libs gtk+-2.0`
 
 # Location where to install the binary.
-BINDIR = /usr/local/bin
+BINDIR = $(DESTDIR)/bin
 
 # Location where to install the manual-page.
-MANDIR = /usr/local/man/man1
+MANDIR = $(DESTDIR)/man/man1
 
 ##### Maintainer stuff goes here:
 
@@ -86,10 +86,8 @@
 
 # Install the program and manual page. You should be root to do this.
 install: $(BASENAME)
-	@if [ `id -u` != 0 ]; then \
-		echo "You must be root to install the program!"; \
-		exit 1; \
-	fi
+	-mkdir -p $(BINDIR)
+	-mkdir -p $(MANDIR)
 	install -m 755 $(BASENAME) $(BINDIR)
 	if [ -e $(BASENAME).1 ]; then \
 		install -m 644 $(BASENAME).1 $(MANDIR); \
@@ -97,10 +95,6 @@
 	fi
 
 uninstall:;
-	@if [ `id -u` != 0 ]; then \
-		echo "You must be root to uninstall the program!"; \
-		exit 1; \
-	fi
 	rm -f $(BINDIR)/$(BASENAME)
 	rm -f $(MANDIR)/$(BASENAME).1*
 
