.TH shiinatimer 6 "9 August 2011" "version 1.0"

.SH 名前

.BR "shiinatimer　" "-　シンプル、めっちゃかわいいカウントダウンタイマー"

.SH 書式
.BI "shiinatimer " "<no-arguments>"

.BI "wine " "/usr/local/lib/KaraageTimer.exe"

.SH 説明
.I 「まゆしぃのジューシーからあげタイマー」

.BR "shiinatimer " "《KaraageTimer》-　まゆしぃのカウントダウンタイマーです。からあげのあたためはもちろん、カップラーメン等にもご利用頂けます！

.SS 「タイマーをセットする」

ボタンをクリックして、＃の次にカウントダウンする秒数3桁を入力して下さい。

（例：30秒に設定ならば「#030」と入力）"

.SH ファイル
.I /usr/local/lib/KaraageTimer.exe
.RS
Windows実行形式のバイナリ

.SH キャスト
花澤香菜　-　椎名まゆり

.SH 著者
5pb. Inc / Nitroplus

.SH 関連項目
.B wine(1)
