.TH shiinatimer 6 "9 August 2011" "version 1.0"

.SH NAME

.BR "shiinatimer " "- a simple, cute cooking timer with Shiina Mayuri animations and voices"

.SH SYNOPSIS
.BI "shiinatimer " "<no-arguments>"

.BI "wine " "/usr/local/lib/KaraageTimer.exe"

.SH DESCRIPTION
.I Mayushii's Juicy Karaage Timer

.BR "shiinatimer " "(KaraageTimer.exe) is a Mayushii's countdown timer, enjoy using it as your karaage or cup ramen timer!"

.SS How to set the timer:

click on 「タイマーをセットする」 button, input the countdown in three digits, prefixing it with '#' first.

(Example: #030 for 30 seconds)

.SH FILES
.I /usr/local/lib/KaraageTimer.exe
.RS
The Windows executable binary

.SH CAST
Hanazawa Kana as Shiina Mayuri

.SH AUTHORS
5pb. Inc / Nitroplus

.SH SEE ALSO
.B wine(1)
