## arg 1:  the new package version
post_install() {
  octave -f -q --eval "pkg prefix /usr/share/octave/packages /usr/lib/octave/packages; pkg install -verbose -global /usr/share/octave/control.tar.gz"
}

## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
  post_remove
  post_install
}

## arg 1:  the old package version
post_remove() {
  octave -f -q --eval "pkg prefix /usr/share/octave/packages /usr/lib/octave/packages; pkg uninstall control"
}
