post_install() {
    echo "Additionnal steps are required to complete rsslounge installation:"
    echo " 1/ rsslounge is installed in /usr/share/webapps/rsslounge/."
    echo "    You should make your favourite webserver point to that directory."
    echo " 2/ Make sure to add /usr/share/webapps to the open_basedir list in your /etc/php/php.ini file."
    echo " 3/ In case you're using lighttpd or nginx, please refer to the project wiki for additionnal installation steps:"
    echo "        http://code.google.com/p/rsslounge/wiki/Installation_and_FAQ"
    echo " 4/ Open your browser at rsslounge's address (as configured in step 1/) and follow instructions."
}
