# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=rails
pkgname=ruby-$_gemname-2
pkgver=2.3.18
pkgrel=1
pkgdesc='Web-application framework with template engine, control-flow layer, and ORM.'
arch=(any)
url='http://www.rubyonrails.org'
license=(MIT)
depends=(ruby ruby-activesupport-2 ruby-activerecord-2 ruby-actionpack-2 ruby-actionmailer-2 ruby-activeresource-2)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('f4aff07dce1db10ad6145e358344671cc482de70')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/MIT-LICENSE" "$pkgdir/usr/share/licenses/$pkgname/MIT-LICENSE"

  mv "$pkgdir/usr/bin/rails" "$pkgdir/usr/bin/rails2"
}
