
post_install() {
	echo
	echo "Enter the command that will be used in '/etc/rc.d/logkeys start'"
	echo "or just press enter, then the following command will be used:"
	echo "  logkeys --start --no-func-keys --keymap /usr/share/lkmaps/en_GB.map"
	echo "Keyboard map files should be in /usr/share/lkmaps/"
	read logkeys_command
	sed -i "s/logkeys--start--command/${logkeys_command//\//\/}/g" /etc/rc.d/logkeys
}

post_upgrade() {
  post_install $1
}
