post_install() {
    gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
    update-desktop-database -q
    update-mime-database usr/share/mime &> /dev/null

    # Note admin after install/update on how to change th update_check setting.
    cat <<EOF
    To disable in-application reminders,
    add the following setting to your User Preferences file:
    "update_check": false
EOF
}

post_upgrade() {
    post_install
}
