
post_install() {

cat <<EOF
>>> To configure the UPS monitor run one of the following:
>>> # upsetup for textual setup
>>> # xwizsetup for graphical wizard setup
>>> # xupsetup for graphical setup
>>> If the UPS is connected through the USB port, type as 
>>> serial port: /dev/ttyUSB0
>>> After the configuration step you may add "upsmon" to DAEMONS
>>> in /etc/rc.conf
EOF
}

# vim:set ts=2 sw=2 et:
