post_install() {
	# lpr
	echo "Running Brother setup programs..."
	/usr/local/Brother/Printer/dcp585cw/inf/setupPrintcapij dcp585cw -i
	
	# cupswrapper
	/usr/local/Brother/Printer/dcp585cw/cupswrapper/cupswrapperdcp585cw
	
	/etc/rc.d/cupsd restart
}

post_upgrade() {
	/bin/true
}

pre_remove() {
	# lpr
	echo "Running Brother setup programs..."
	/usr/local/Brother/Printer/dcp585cw/inf/setupPrintcapij dcp585cw -e
	
	# cupswrapper
	/usr/local/Brother/Printer/dcp585cw/cupswrapper/cupswrapperdcp585cw -e
}

op=$1
shift

$op "$@"

