dir="/opt/smileol"
pkgname="smileol"

pre_install() {
    pre_remove
}

post_install() {
  # Test PSI
    if test -d /usr/share/psi/iconsets/emoticons ; then
      ln -s ${dir}/${pkgname}.jisp /usr/share/psi/iconsets/emoticons/
    fi
  # Test PSI+
    if test -d /usr/share/psi-plus/iconsets/emoticons ; then
      ln -s ${dir}/${pkgname}.jisp /usr/share/psi-plus/iconsets/emoticons/
    fi
  # Test Gajim
    if test -d usr/share/gajim/data/emoticons ; then
      ln -s ${dir}/${pkgname} /usr/share/gajim/data/emoticons/
    fi
  # Test Pidgin
    if test -d usr/share/pixmaps/pidgin/emotes/ ; then
      ln -s ${dir}/${pkgname} /usr/share/pixmaps/pidgin/emotes/
    fi
}

pre_upgrade() {
    pre_remove
}

post_upgrade() {
    post_install
}

pre_remove() {

  # Test PSI
    if test -L /usr/share/psi/iconsets/emoticons/${pkgname}.jisp ; then
      rm /usr/share/psi/iconsets/emoticons/${pkgname}.jisp
    fi
    if test -e /usr/share/psi/iconsets/emoticons/${pkgname}.jisp ; then
      rm /usr/share/psi/iconsets/emoticons/${pkgname}.jisp
    fi

  # Test PSI+
    if test -L /usr/share/psi-plus/iconsets/emoticons/${pkgname}.jisp ; then
      rm /usr/share/psi-plus/iconsets/emoticons/${pkgname}.jisp
    fi
    if test -e /usr/share/psi-plus/iconsets/emoticons/${pkgname}.jisp ; then
      rm /usr/share/psi-plus/iconsets/emoticons/${pkgname}.jisp
    fi

  # Test Gajim
    if test -L /data/emoticons/${pkgname} ; then
      rm -fr /usr/share/gajim/data/emoticons/${pkgname}
    fi
    if test -e /usr/share/gajim/data/emoticons/${pkgname} ; then
      rm -fr /usr/share/gajim/data/emoticons/${pkgname}
    fi

  # Test Pidgin
    if test -L /usr/share/pixmaps/pidgin/emotes/${pkgname} ; then
      rm -fr /usr/share/pixmaps/pidgin/emotes/${pkgname}
    fi
    if test -e /usr/share/pixmaps/pidgin/emotes/${pkgname} ; then
      rm -fr /usr/share/pixmaps/pidgin/emotes/${pkgname}
    fi
}



  