pre_install() {
  pre_remove
}

post_install() {
  # Test PSI
  [ -d /usr/share/psi/iconsets/emoticons ] && ln -s "/opt/smileol/smileol.jisp" "/usr/share/psi/iconsets/emoticons/smileol.jisp"

  # Test PSI+
  [ -d /usr/share/psi-plus/iconsets/emoticons ] && ln -s "/opt/smileol/smileol.jisp" "/usr/share/psi-plus/iconsets/emoticons/smileol.jisp"

  # Test Gajim
  [ -d /usr/share/gajim/data/emoticons ] && ln -s "/opt/smileol/smileol" "/usr/share/gajim/data/emoticons/smileol"

  # Test Pidgin
  [ -d /usr/share/pixmaps/pidgin/emotes ] && ln -s "/opt/smileol/smileol" "/usr/share/pixmaps/pidgin/emotes/smileol"

  true

}

pre_upgrade() {
  pre_remove
}

post_upgrade() {
  post_install
}

pre_remove() {
  # Test PSI
  [ -L /usr/share/psi/iconsets/emoticons/smileol.jisp ] && rm -fr "/usr/share/psi/iconsets/emoticons/smileol.jisp"

  # Test PSI+
  [ -L /usr/share/psi-plus/iconsets/emoticons/smileol.jisp ] && rm -fr "/usr/share/psi-plus/iconsets/emoticons/smileol.jisp"

  # Test Gajim
  [ -L /usr/share/gajim/data/emoticons/smileol ] && rm -fr "/usr/share/gajim/data/emoticons/smileol"

  # Test Pidgin
  [ -L /usr/share/pixmaps/pidgin/emotes/smileol ] && rm -fr "/usr/share/pixmaps/pidgin/emotes/smileol"

  true
}
