post_upgrade() {
  cd /opt/fusiondirectory
  ./update-fusiondirectory
}

post_install() {
  cd /opt/fusiondirectory
  ./update-fusiondirectory
  echo
  echo "--------------------------------------------------------------------------"
  echo "1. You will need dnszone.schema in your ldap"
  echo "2. You will need bind and ldap2zone"
  echo "--------------------------------------------------------------------------"
}
