post_install() {
	echo '==> ~/.purple/halfLyf is added to the $PATH'
	echo '==> so you can put hL scripts there as well'
	echo '==> the rest of the $PATH is searched'
	echo '==> if the command is not found'
	echo '==> '
	echo '==> NOTE!'
	echo '==> the saved status message is not interpreted by the shell'
	echo '==> so you must use `command` format only'
	echo '==> ... you can find some scripts at http://nrk.cc/src/hl/scripts'
}

op=$1
shift
$op $*
