diff -ur a/Makefile b/Makefile
--- a/Makefile	2012-01-19 13:49:25.072958605 +0000
+++ b/Makefile	2012-01-19 14:05:48.049319288 +0000
@@ -4,7 +4,7 @@
 # Choose here wich include file to use: from kernel 3.0.0 (good for 3.1.0) or from kernel 3.2.0
 
 # kernel 3.0.0 / 3.1.0
-INCLUDE_EXTRA_DVB := include-300
+# INCLUDE_EXTRA_DVB := include-300
 
 # kernel 3.2.0
 #INCLUDE_EXTRA_DVB := include-320
@@ -12,7 +12,7 @@
 # ----------------------------------------
 
 # current dir
-SOURCEDIR := $(PWD)
+#SOURCEDIR := $(PWD)
 
 dvb-usb-rtl2832u-objs := demod_rtl2832.o dvbt_demod_base.o dvbt_nim_base.o \
 	foundation.o math_mpi.o nim_rtl2832_mxl5007t.o nim_rtl2832_fc2580.o \
@@ -31,11 +31,9 @@
 EXTRA_CFLAGS += -I$(KBUILD_SRC)/drivers/media/dvb/dvb-usb/ \
 		-I$(KBUILD_SRC)/drivers/media/dvb/dvb-core/ \
 		-I$(KBUILD_SRC)/drivers/media/dvb/frontends/ \
-		-I$(KBUILD_SRC)/drivers/media/common/tuners/ \
-		-I$(SOURCEDIR)/$(INCLUDE_EXTRA_DVB) 
+		-I$(KBUILD_SRC)/drivers/media/common/tuners/
 
-KINS = /lib/modules
-KDIR = /usr/src/linux-headers-`uname -r`
+KDIR = /lib/modules/$(shell uname -r)/build
 
 default:
 	make -C $(KDIR) SUBDIRS=$(PWD) modules
