post_install() {
    echo --------------------------------------------------------
    echo After install, simply add these options to your kernel
    echo command-line, usually in /boot/grub/menu.lst:  
    echo \'initcall_debug printk.time=y quiet init=/sbin/bootchartd\'
    echo After bootup, run \'pybootchartgui -i\' to get an
    echo  interactive chart rendering tool.
    echo --------------------------------------------------------
}

post_upgrade () {
    post_install
}
