post_install() {
  depmod $(uname -r)
  echo ""
  echo ">> --------------------------------------------------- <<"
  echo "Please add nvidiabl to the modules array of your rc.conf"
  echo ""
}

post_upgrade() {
  depmod $(uname -r)
}


post_remove() {
  depmod $(uname -r)
  echo ""
  echo ">> ------------------------------------------------- <<"
  echo "Remove nvidiabl from the modules array of your rc.conf"
  echo ""
}
