post_install() {
	getent passwd ffsync &>/dev/null || useradd -r -s /usr/bin/false \
		-g http -d /opt/mozilla-firefox-sync-server ffsync >/dev/null

	install -dm 0755 /var/log/ffsync
	chown ffsync:log /var/log/ffsync
}

post_update() {
	if [ ! -d /var/log/ffsync ]; then
		install -dm 0755 /var/log/ffsync
		chown ffsync:log /var/log/ffsync
	fi
}

pre_remove() {
	getent passwd ffsync &>/dev/null && userdel ffsync >/dev/null
	true
}
