#!/bin/sh
# Always run Google Earth from this shell script and not
# Google Earth directly! This script makes sure the app looks
# in the right place for libraries that might also be installed
# elsewhere on your system.
#
# Ryan C. Gordon,  Thu Jul 20 14:32:33 PDT 2006

# Find the real directory of the program more elegantly: http://stackoverflow.com/a/246128/2139899

SOURCE="${BASH_SOURCE[0]}"

while [ -h "$SOURCE" ]; do # resolve until no longer a symlink
  DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if a symlink, resolve the path
done

cd "$(dirname "$SOURCE")"

### Do these separately for clarification
# Fix the coordinates regression
export LC_NUMERIC=en_US.UTF-8

# ..and the fontconfig crash: http://productforums.google.com/forum/#!msg/earth/dlzBfGl4eKM/723naNYBo30J
export FONTCONFIG_FILE=$(pwd)/google-earth-fonts.conf

LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH ./googleearth-bin "$@"
