
post_install() {
    update-desktop-database -q
    update-mime-database usr/share/mime
    for s in 8 16 20 22 24 32 40 42 48 64 72 96 128 192 256
    do
        xdg-icon-resource install /usr/share/icons/hicolor/${s}x${s}/apps/kbibtex.png --size $s --novendor
    done
}
post_remove() {
    for s in 8 16 20 22 24 32 40 42 48 64 72 96 128 192 256
    do
        xdg-icon-resource uninstall /usr/share/icons/hicolor/${s}x${s}/apps/kbibtex.png --size $s --novendor
    done
}

