ACE_USER=acestream
ACE_UID=4035
ACE_GROUP=video

_adduser() {
  if ! getent passwd $ACE_USER &> /dev/null; then
    useradd -u $ACE_UID -g $ACE_GROUP -m -s /bin/false $ACE_USER &>/dev/null
    passwd -l $ACE_USER &>/dev/null
    echo "  ==> User $ACE_USER created"
  fi
}

_deluser() {
  userdel $ACE_USER &>/dev/null
  echo "  ==> User $ACE_USER removed"
}

post_install() { 
  _adduser
}
post_upgrade() {
  _adduser
}
post_remove() {
  _deluser
}
