post_install() {
    glib-compile-schemas /usr/share/glib-2.0/schemas/
    gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
    gtk-update-icon-cache -q -t -f /usr/share/icons/mate
}

pre_upgrade() {
    pre_remove
}

post_upgrade() {
    post_install
}

pre_remove() {
    glib-compile-schemas /usr/share/glib-2.0/schemas/
}

post_remove() {
    gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
    gtk-update-icon-cache -q -t -f /usr/share/icons/mate
}
