.\" Part of knubbler
.\" License: CC-BY-NC-SA-3.0
.\" http://creativecommons.org/licenses/by-nc-sa/3.0/de/
.\" http://creativecommons.org/licenses/by-nc-sa/3.0/de/deed.en
.\" Johann Klähn <kljohann@gmail.com>

.\" Man-Page for Knubbler
.\" ( my very first manpage. ô.O )
.TH KNUBBLER 1
.SH NAME
knubbler \- a scrollable progressbar (percentage input interface)

.SH SYNOPSIS
.B knubbler
.RI [ options ]\ [ fraction ]

.SH DESCRIPTION
Knubbler is a GUI used to enter fractions by scrolling on a progressbar.
This is a very convenient thing to do on touchpads. Knubbler was designed
to be used in shell scripts or keybindings.

The command
.B knubbler 
can be called with a fraction as an optional argument to initialize the
progressbar to a specific value. By default the value is returned as a
fraction as well.

You can use
.B
Enter,
.B Space
or
.B Left Mousebutton
to accept a value or cancel by pressing
.B Escape
or simply closing the window.
You can modify the value by scrolling on the progressbar or clicking with
your right mouse button.
You can also click-and-hold to drag the value. (progressbar "sticks" to cursor)
By pressing a number on your keyboard, you can set it to a multiple of ten.

.SH OPTIONS
Options are parsed using GNU Getopt conventions.
.TP
.B \-i,\ \-\-stdin
Scan
.I STDIN
for a percentage (XX%) and use it to initialize knubbler.
This takes priority over any given fraction.
.TP
.B \-p,\ \-\-percentage
Output like XX% instead of 0.XX
.TP
.B \-l,\ \-\-left-to-right
Display progressbar from left to right instead of bottom to top.
.TP
.BI \-w,\ \-\-window \ WIDTHxHEIGHT
Instead of fullscreen, display in a window with given dimensions.
.TP
.BI \-t,\ \-\-title \ TITLE
Display a short help text at the top of the window.
You can use pango markup.
.TP
.BI \-f,\ \-\-factor \ FACTOR
Sets the accuracy of the progressbar to steps of 100/FACTOR percent.
.PP

.SH RETURN VALUES
On success knubbler returns the value either as a fraction or as a
percentage (see above).
When input is cancelled it will exit with an exit status of 1.

.SH REQUIREMENTS
In addition to Python only PyGTK is used.
