post_install()
{
   echo " "
   echo " "
   echo "Some tips and ideas"
   echo "------------------"
   echo " "
   echo "* edit /opt/analog/analog.cfg and set the right values for your webserver"
   echo "* you could set up a cron job for running analog automatically"
   echo "* you should make analog to be syncronized with logrotation - and older" 
   echo "  analog reports could be saved along with the older logs"
   echo " "
   echo " "
}

op=$1
shift
$op $*
