post_install () {
cat << EOF
 This is an example on how you copy all the configuration files to the ~/minecraft-server directory, which you then can change to your preferences.

    mkdir ~/minecraft-server
    cp -r /usr/share/minecraft/* ~/minecraft-server

 You can then run the server by issuing mineserver, without specifying the configuration file location, since mineserver will look for it in the current directory.
EOF
}
