post_install() {
cat << EOF
>>> Book installed as /usr/share/gnuchess/book-big.bin
>>> To enable it in gnuchess edit the file /usr/share/gnuchess/gnuchess.ini
--------------------------------------------------------------------------- 
[Engine]

OwnBook =  true
BookFile = book-big.bin
---------------------------------------------------------------------------


EOF
}

post_upgrade() {
  post_install $1
}

op=$1
shift

$op $*
