post_install() {
cat << 'EOM'
  ==> PLEASE NOTE:
  ==> To be able to play commercial games on this emulator you need an image
  ==> of a Sony PlayStation BIOS ROM. The BIOS is copyrighted by Sony  
  ==> Computer Entertainment and can therefore not be included in this  
  ==> package.  
  
  ==> BIOS images can be placed in ~/.pcsx/bios or /usr/share/psemu/bios.   
EOM
}

post_upgrade() {
 post_install
}

