#! /bin/sh

source /etc/conf.d/subvein

USER=$(id -un)
if [[ $USER != "subvein" ]]; then
  echo "This program should only be run by the subvein user"
  exit
fi

cleanup()
{
  fusermount -u $HOME/.subvein/overlay
}

if [[ ! -d $HOME/.subvein/overlay ]]; then
  mkdir -p $HOME/.subvein/overlay
fi
if [[ ! -d $HOME/.subvein/data ]]; then
  mkdir -p $HOME/.subvein/data
fi

unionfs -o cow $HOME/.subvein/data=RW:/opt/subvein=RO $HOME/.subvein/overlay
trap cleanup SIGINT
$HOME/.subvein/overlay/SubveinServer $SUBVEIN_ARGS

