post_install() {
	echo "NOTE: To run this game you must edit the text file with your
              CD key.  To do this, go to /opt/ut2004/System,

              $ vi CDkey 

              Edit the CDkey file and put the key by itself,
	      
              For example:

	      xxxxx-xxxxx-xxxxx-xxxxx

	      Save the Cdkey file.
"
}

post_upgrade() {
   /bin/true
}

pre_remove() {
   /bin/true
}

op=$1
shift

$op $*
