# Generated by Xyne::Arch::CPAN 0.07
# Maintainer: yugrotavele <yugrotavele at archlinux dot us>

pkgname=perl-test-critic
_realname=Test-Perl-Critic
pkgver=1.02
pkgrel=1
pkgdesc="Use Perl::Critic in test programs."
arch=('i686' 'x86_64')
url="http://search.cpan.org/dist/Test-Perl-Critic/"
license=('PerlArtistic' 'GPL')
source=('http://search.cpan.org/CPAN/authors/id/T/TH/THALJEF/Test-Perl-Critic-1.02.tar.gz')
md5sums=('7f1e75cc3d933e4deab5097c5b8c812d')
sha256sums=('89b242ff539034336ed87c11ef3e5ecac47c333a6ab8b46aab4cc449e3739a89')
depends=('perl-critic' 'perl-test-simple')
options=(!emptydirs)

build() {
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Makefile.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor || return 1
    make  || return 1
    make install DESTDIR="${pkgdir}" || return 1

  else
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Build.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Build.PL INSTALLDIRS=vendor || return 1
    ./Build  || return 1
    ./Build install destdir=${pkgdir} || return 1

  else
    echo "error: failed to detect build method for $pkgname"
    echo "you may be able to fix this by editing the PKGBUILD"
    return 1
  fi fi

  # remove perllocal.pod and .packlist
  find ${pkgdir} -name perllocal.pod -delete
  find ${pkgdir} -name .packlist -delete
}


