--- Makefile	2008-06-16 15:20:01.000000000 -0300
+++ Makefile.new	2008-12-01 18:22:22.843338556 -0200
@@ -1,20 +1,21 @@
 
 RM=/bin/rm
-INSTALL=/usr/bin/install
-SYSCONFDIR=$(DESTDIR)/usr/local/etc/msn-proxy
-BINDIR=$(DESTDIR)/usr/local/bin
+INSTALL=/bin/install
+SYSCONFDIR=$(DESTDIR)/etc/msn-proxy
+BINDIR=$(DESTDIR)/usr/bin
 
 # FreeBSD
-MYSQLINC=/usr/local/include
-MYSQLLIB=/usr/local/lib/mysql
+#MYSQLINC=/usr/local/include
+#MYSQLLIB=/usr/local/lib/mysql
 
 # Linux (most)
-#MYSQLINC=/usr/lib/mysql
-#MYSQLLIB=/usr/local/mysql/lib/mysql
+MYSQLINC=/usr/lib/mysql
+MYSQLLIB=/var/lib/mysql
 
-CCFLAGS=-g -Wall -O2 -pipe -I/usr/local/include -I$(MYSQLINC) -fno-builtin-log
+CCFLAGS=-I/usr/include -I$(MYSQLINC) -DMYSQLCONFDIR=\""/etc/msn-proxy/mysql"\"
+-DDEFAULT_CONFIG_PATH=\""/etc/msn-proxy"\" -fno-builtin-log
 
-LDFLAGS=-L/usr/local/lib -levent -L$(MYSQLLIB) -lmysqlclient
+LDFLAGS=-L/usr/lib -levent -L$(MYSQLLIB) -lmysqlclient
 
 OBJS=msn-proxy.o server.o sb.o command.o config.o net-io.o client.o syslog.o \
 	ns.o mysql.o sql.o protocol.o check-cmd.o contacts.o msg.o p2p.o \
