post_install() {
    echo "Add in your .vimrc: "
    echo "    let g:VMPhtmlreader = 'your_browser_here'. "
    echo "Or you cant see converted files."
    echo "-----"
    echo "See /usr/share/vim/vimfiles/vim-markdown-preview/README.mkd for help."
    echo "Also, i recommend install vim-markdown from AUR."
}

post_upgrade() {
  post_install $1
}

post_remove() {
  post_install
}

op=$1
shift

$op $*
