# arg 1:  the new package version

_usage_string="=== python-qt4-doc ===

You can find all docs and examples into /usr/share/doc/python-qt4-doc
Run this command to put a doc link on your (user) desktop:
ln -s /usr/share/doc/python-qt4-doc ~/Desktop/PyQt4-Docs

"

post_install() {
    echo "$_usage_string"
    /bin/true
}

post_upgrade() {
    echo "$_usage_string"
    /bin/true
}

op=$1
shift
$op $*
