post_install() {
  echo "------------------------------------------------------------------------------------"
  echo "* Please issue the following command to setup the Gatling environment:"
  echo "    source /etc/profile.d/gatling.sh"
  echo "* Make sure you grant proper write rights for the /opt/gatling/results directory to"
  echo "  the user that will run Gatling."
  echo "------------------------------------------------------------------------------------"
}

post_upgrade() {
  post_install $1
}

# vim:set ts=2 sw=2 et:
