post_install() {
  # Make uploads work
  chmod a+rwx /usr/share/webapps/gleez/application
  chmod a+rwx /usr/share/webapps/gleez/application/cache
  chmod a+rwx /usr/share/webapps/gleez/application/config
  chmod a+rwx /usr/share/webapps/gleez/application/logs
  chmod a+rwx /usr/share/webapps/gleez/application/media
  chmod a+rwx /usr/share/webapps/gleez/application/uploads
  chmod a+rwx /usr/share/webapps/gleez/media

  echo 'You can now configure your (PHP compatible) web server to run Gleez CMS.'
  echo 'We create the documentation together with the community and other Gleez users/developers.'
  echo 'The latest documentation is available on the [Gleez Wiki](https://github.com/gleez/cms/wiki).'
}

post_remove() {
  rm -rf /usr/share/webapps/gleez
  rm /usr/share/licenses/gleez/LICENSE
}

post_upgrade() {
  echo 'Gleez CMS is in /usr/share/webapps now!'
}
