post_install()
{
#	echo "You must restart dictd for it to detect the new dictionary"
#	echo "as root, /etc/rc.d/dictd restart"
	echo "Dictd must be restarted in order to detect the new dictionary:"
	/etc/rc.d/dictd restart
}

post_upgrade()
{
#	echo "You must restart dictd for it to detect the new dictionary"
#	echo "as root, /etc/rc.d/dictd restart"
	echo "Dictd must be restarted in order to detect the new dictionary:"
	/etc/rc.d/dictd restart
}
