diff -N -u -r powertop-1.98/Makefile powertop-1.98-patched/Makefile
--- powertop-1.98/Makefile  2011-05-10 21:48:37.000000000 -0700
+++ powertop-1.98-patched/Makefile  2012-02-23 23:29:18.520273542 -080
@@ -38,7 +38,7 @@
 
 ifeq ($(NL3FOUND),Y)
 CFLAGS += -DCONFIG_LIBNL20
-LIBS += -lnl-genl
+LIBS += -lnl-genl-3
 NLLIBNAME = libnl-3.0
 endif