howto()
{
  echo ""
  echo "***************************************************************"
  echo " To set the window title using the filename, put the following "
  echo " line into ~/.mplayer/config :"
  echo " "
  echo '    use-filename-title = "yes" '
  echo " "
  echo "***************************************************************"
  echo ""
}

post_install() {
    update-desktop-database -q
    howto
}

post_upgrade() {
    post_install
}

post_remove() {
    post_install
}
