--- Makefile.in	2008-02-12 21:01:13.000000000 +0100
+++ Makefile.in.new	2009-03-17 22:37:56.788158343 +0100
@@ -77,11 +77,11 @@
 	rm -f *.o core dv4l dv4lstart libdv4l.so
 
 install: dv4l dv4lstart libdv4l.so
-	install -D -m 0750 -g video dv4l $(bindir)
-	install -D -m 0644 dv4l.1 $(mandir)/man1
-	install -D -m 0644 dv4lstart.1 $(mandir)/man1
-	install -D -m 0755 libdv4l.so @prefix@@libdir@
-	install -D -m 0755 dv4lstart @prefix@@bindir@
+	install -D -m 0750 -g video dv4l ${DESTDIR}$(bindir)/dv4l
+	install -D -m 0644 dv4l.1  ${DESTDIR}$(mandir)/man1/dv4l.1
+	install -D -m 0644 dv4lstart.1  ${DESTDIR}$(mandir)/man1/dv4lstart.1
+	install -D -m 0755 libdv4l.so  ${DESTDIR}@prefix@@libdir@/libdv4l.so
+	install -D -m 0755 dv4lstart  ${DESTDIR}@prefix@@bindir@/dv4lstart
 
 uninstall:
 	rm -f $(bindir)/dv4l
