# arg 1:  the new package version
post_install() {
  echo "After installation just copy the groupvte.conf.example file"
  echo "to ~/.groupvte.conf and tailor it to your needs."
}

post_upgrade() {
  echo "After installation just copy the groupvte.conf.example file"
  echo "to ~/.groupvte.conf and tailor it to your needs."
}

op=$1
shift
[ "$(type -t "$op")" = "function" ] && $op "$@"

# vim:set ts=2 sw=2 et:
