# $Id: texlive.install 149 2009-04-30 00:46:23Z shtrom $
# Taken from texlive-publishers

post_install() {
	echo    ">>> texlive: updating the filename database..."
	texconfig-sys rehash
	echo	"Have a look at 
		/usr/share/texmf/tex/latex/acm-small/acmsmall-guide.pdf,
		/usr/share/texmf/tex/latex/acm-small/acmsmall-sample.pdf and
		/usr/share/texmf/tex/latex/acm-small/readme.txt
to learn how to use this template."
}

post_upgrade() {
	echo    ">>> texlive: updating the filename database..."
	texconfig-sys rehash
	echo	"Have a look at 
		/usr/share/texmf/tex/latex/acm-small/acmsmall-guide.pdf,
		/usr/share/texmf/tex/latex/acm-small/acmsmall-sample.pdf and
		/usr/share/texmf/tex/latex/acm-small/readme.txt
to learn how to use this template."
}

post_remove() {
	echo    ">>> texlive: updating the filename database..."
	texconfig-sys rehash
}
