
post_install() {
	ln -sf /usr/share/wiithon/wiithon.py /usr/games/wiithon
	ln -sf /usr/games/wiithon_wrapper /usr/share/wiithon/wiithon_wrapper
	ln -sf /usr/games/wiithon_unrar /usr/share/wiithon/wiithon_unrar
	ln -sf /usr/games/wiithon_wbfs_file /usr/share/wiithon/wiithon_wbfs_file
	ln -sf /usr/games/wiithon_wdf2iso /usr/share/wiithon/wiithon_wdf2iso
	ln -sf /usr/games/wiithon_iso2wdf /usr/share/wiithon/wiithon_iso2wdf
	ln -sf /usr/games/wiithon_wwt /usr/share/wiithon/wiithon_wwt
}

post_upgrade() {
  post_install $1
}

