54c54
< ICFLAGS	= -g -O3
---
> ICFLAGS	= -g -O3 -fPIC
272a273,280
> libso:
> 	sh ./setup.sh
> 	@+for dir in $(BDIRS); do \
> 		(cd $$dir; \
> 		echo Making all in $$dir ...; \
> 		make CC=$(CC) RANLIB=$(RANLIB) MFLAG= MNEMLIB= ICFLAGS="$(ICFLAGS)" XCFLAGS="$(XCFLAGS)" DDDEBUG="$(DDDEBUG)" MTRDEBUG="$(MTRDEBUG)" LDFLAGS="$(LDFLAGS)" PURE="$(PURE)" EXE="$(EXE)" libso )\
> 	done
> 
