post_install() {
	echo "**********************************************************************"
	echo "** NEXT: Please run 'dtinitconf' in order to set up the required"
	echo "**       /etc/dnssec-tools/dnssec-tools.conf file"
	echo "**********************************************************************"
	if [ ! -e /etc/dnssec-tools/log-rollerd ]; then
		touch /etc/dnssec-tools/log-rollerd
	fi
}


