
kernver="3.3"
extramods="extramodules-${kernver}-ck"
exactkernver="$(cat /lib/modules/${extramods}/version)"

post_install() {
    depmod -v "${exactkernver}" > /dev/null 2>&1
}

post_upgrade() {
    depmod -v "${exactkernver}" > /dev/null 2>&1
    rmmod nvidia || echo 'In order to use the new nvidia module, exit Xserver and unload it manually.'
}

post_remove() {
    depmod -v "${exactkernver}" > /dev/null 2>&1	 
}
