_mount_info()
{
cat << _EOF

  Hi, this version of exo can use different mount options for file systems.
  
  Configuration saved in
    /usr/share/xfce4/mount.rules
  
  Users can copy it file to
    \$HOME/.config/xfce4/mount.rules
  for customization.
  
_EOF
}

post_install() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  _mount_info
}

post_upgrade() {
  post_install $1
  _mount_info
}

post_remove() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}
