pkgname=buzztard

post_install() {
  usr/sbin/gconfpkg --install ${pkgname}
  post_remove
}

pre_upgrade() {
  pre_remove
}

post_upgrade() {
  usr/sbin/gconfpkg --install ${pkgname}
  post_remove
}

pre_remove() {
  usr/sbin/gconfpkg --uninstall ${pkgname}
}

post_remove() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  update-desktop-database -q
  update-mime-database usr/share/mime 
}
