post_install(){
	echo "Config file:"
	echo " /etc/torrent-leecher.conf"
	echo ""
	echo "Log file:"
	echo " /var/log/torrent-leecher.log"
	echo ""
	echo "View logs in realtime:"
	echo " torrent-leecher-logs"
	echo ""
	echo "Usage:"
	echo " -Start daemon/proxy by running '/etc/rc.d/torrent-leecher start' or add it to DAEMONS-array with @-prefix on your '/etc/rc.conf'-file"
	echo " -Set (tracker) proxy on your BitTorrent client to localhost:3456"
}
