# Generated by gem2arch

_gemname=parseconfig
pkgname=ruby-gem-$_gemname
pkgver=1.0.2
pkgrel=1
pkgdesc="Config File Parser for Standard Unix/Linux Type Config Files"
arch=('any')
url="http://github.com/derks/ruby-parseconfig/"
license=('')
depends=('ruby')
makedepends=('rubygems')
source=(http://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
md5sums=('58dac67900241ae0760666237dc2386c')
sha1sums=('9ea5288c516287e058027ab443efc50acff63206')

package() {
  cd "$srcdir"
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir$_gemdir" $_gemname-$pkgver.gem
}
