post_install() {
  printf "%b\n" "$fzfw"
}

post_upgrade() {
  post_install
}

read -d '' fzfw <<'EOF'
fzf-extras
==========

Add the following to your shell config:

    . /etc/profile.d/fzf-extras.sh # when bash
    . /etc/profile.d/fzf-extras.zsh # when zsh

2015-04-04: Updates

- https://github.com/junegunn/fzf/tree/master/shell
- https://github.com/junegunn/fzf/wiki
- https://github.com/junegunn/dotfiles/blob/master/bashrc
EOF
