post_install () {
  post_upgrade
}

post_upgrade () {
  if [[ $(locale -a | grep french) == "french" ]];then
    echo -e "\n\033[46mUn dépôt pour Darling et toutes ses dépendances est disponible, voir : https://github.com/X0rg/Arch-PKGs/wiki/Darling-repository.\033[0m"
  else
    echo -e "\n\033[46mA repository for Darling and his dependencies is available, see: https://github.com/X0rg/Arch-PKGs/wiki/Darling-repository.\033[0m"
  fi
}