# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Babken Vardanyan <483ken@gmail.com>

_gemname=msgpack
pkgname=ruby1.9-$_gemname
pkgver=0.5.8
pkgrel=1
pkgdesc='MessagePack, a binary-based efficient data interchange format.'
arch=(i686 x86_64)
url='http://msgpack.org/'
license=('Apache 2.0')
depends=(ruby1.9)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('96f031e918be8a59675af812599959b2647158fc')

package() {
  local _gemdir="$(ruby-1.9 -e'puts Gem.default_dir')"
  gem-1.9 install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
