post_install() {
  if [ ! `grep gopher /etc/group` ]; then
    groupadd -r gopher &>/dev/null;
  fi

  id gopher &>/dev/null || \
    useradd -r -g gopher -d /srv/gopher -s /bin/false gopher

  if [[ ! -d "/srv/gopher" ]]; then
      mkdir /srv/gopher && chown gopher /srv/gopher
  fi
}

post_upgrade() {
  post_install $1
}

post_remove() {
  getent passwd gopher >/dev/null 2>&1 && userdel gopher
  getent group gopher >/dev/null 2>&1 && groupdel gopher
}
