#!/bin/bash
# tunlr - start and stop tunlr
# see <http://tunlr.net/> for more information

if [ $UID != 0 ]; then
	echo "you must be root to start or stop tunlr"
	exit 1
fi

case "$1" in
	start)
		echo "starting tunlr"
		cp  /etc/resolv.conf /etc/resolv.conf.bak
		cat /etc/tunlr/tunlr_dns > /etc/resolv.conf
		cat /etc/resolv.conf.bak >> /etc/resolv.conf
		echo "restart your web browser to apply the changes"
		;;

	stop)
		echo "stopping tunlr"
		if [ ! -f /etc/resolv.conf.bak ]; then
			echo "/etc/resolv.conf.bak does not exsist. unable to restore DNS config"
			exit 1
		fi
		cp /etc/resolv.conf.bak /etc/resolv.conf
		echo "restart your web browser to apply the changes"
		;;

	update)
		echo "updating tunlr dns server"
		if [ $(ping -q -c 1 tunlr.net &>/dev/null; echo $?) -ne 0 ]; then
			echo "tunlr.net seems to be down. please try again later"
			exit 1
		fi
		rm /etc/tunlr/tunlr_dns
		for srv in $(wget http://tunlr.net/get-started/ -q -O - | grep -Eo '\<[[:digit:]]{1,3}(\.[[:digit:]]{1,3}){3}\>'); do
			echo "adding $srv"
			echo "nameserver $srv" >> /etc/tunlr/tunlr_dns
		done
		;;

	*)
		echo "usage: $0 {start|stop|update}"
		;;

esac

exit 0
