#!/bin/bash

# tunlr 0.1.4 - watch netflix, mtv, cbs, hulu and more outside the u.s.
# for more information please visit <http://tunlr.net/>
#
# Copyright: (C) 2012 edloaa <edloaa at googlemail dot com>
# License: GPL-3 <http://www.gnu.org/licenses/gpl-3.0.txt>

LOG=/tmp/tunlr_errors-$RANDOM
RSLV=/etc/resolv.conf
CONF=/etc/tunlr/tunlr_dns
IP='\<[[:digit:]]{1,3}(\.[[:digit:]]{1,3}){3}\>'

err() {
   echo "failed"
   cat $LOG
   rm $LOG
   exit 1
}

exit_with() {
   if [ -f $LOG ] && [ -O $LOG ]
   then
      rm $LOG
   fi

   exit $1
}

if [ $UID != 0 ] && [[ "$1" =~ start|stop|update ]]
then
   echo "you must be root to run 'tunlr $1'" 1>&2
   exit_with 1
fi

case "$1" in
   start)
      echo -n "starting tunlr... "

      if [ -f $RSLV.bak ]
      then
         echo -e "failed\n$RSLV.bak does already exist - nothing will be changed"
         exit_with 1
      else
         cp $RSLV $RSLV.bak 2>$LOG || err
      fi

      cat $CONF $RSLV.bak >$RSLV 2>$LOG || err
      echo -e "ok\nrestart your web browser to apply the changes"
      ;;

   stop)
      echo -n "stopping tunlr... "

      if [ -f $RSLV.bak ]
      then
         cp $RSLV.bak $RSLV 2>$LOG || err
         rm $RSLV.bak 2>$LOG || err
         echo -e "ok\nrestart your web browser to apply the changes"
      else
         echo -e "failed\n$RSLV.bak does not exist - unable to restore DNS config"
         exit_with 1
      fi
      ;;

   update)
      echo -n "updating tunlr dns server... "
      cp $CONF $CONF.bak &>/dev/null
      > $CONF

      if ping -q -c 1 tunlr.net &>/dev/null
      then
         for SRV in $(wget -q -O - http://tunlr.net/get-started/ | grep -Eo $IP | uniq)
         do
            echo "nameserver $SRV" >>$CONF
         done
      else
         echo -e "failed\ntunlr.net seems to be down - please try again later"
         exit_with 1
      fi

      if [ -s $CONF ]
      then
         echo "ok"
         echo "updated $CONF:"
         cat $CONF
         rm $CONF.bak &>/dev/null
      else
         echo -e "failed\nrestoring old configuration file"
         mv $CONF.bak $CONF
      fi
      ;;

   *)
      echo "usage: $0 {start|stop|update}"
esac

exit_with 0
