#!/bin/bash

# tunlr 0.1.0 - watch netflix, mtv, cbs, hulu and more outside the u.s.
# for more information please visit <http://tunlr.net/>
#
# Copyright: (C) 2012 edloaa <edloaa at googlemail dot com>
# License: GPL-3 <http://www.gnu.org/licenses/gpl-3.0.txt>

log=/tmp/tunlr-errors
rslv=/etc/resolv.conf
conf=/etc/tunlr/tunlr_dns

# see http://tunlr.net/faq/

tgts="netflix.com 
hulu.com
cbs.com
abc.go.com
mtv.com
thewb.com
cwtv.com
crackle.com
nbc.com
fox.com
tv.com
video.pbs.org
vevo.com
history.com
mylifetime.com
pandora.com
lastfm.de
turntable.fm
mog.com
bbc.co.uk
channel4.com
itv.com
zattoo.com"

[ $UID != 0 ] && [ "$1" == "start" -o "$1" == "stop" -o "$1" == "update" ] && {
	echo "you must be root to run 'tunlr $1'"
	exit 1
}

err() {
	echo "failed"
	cat $log
	exit 1
}

case "$1" in
start)
	echo -n "starting tunlr... "
	[ ! -f $rslv.bak ] && cp $rslv $rslv.bak 2>$log
	cat $conf $rslv.bak >$rslv 2>$log || err
	echo "ok"
	echo "restart your web browser to apply the changes"
	;;
stop)
	echo -n "stopping tunlr... "
	if [ -f $rslv.bak ]; then
		cp $rslv.bak $rslv 2>$log || err
		rm $rslv.bak 2>$log || err
		echo "ok"
		echo "restart your web browser to apply the changes"
	else
		echo "failed"
		echo "$rslv.bak does not exsist. unable to restore DNS config"
		exit 1
	fi
	;;
ip)
	if ! grep "$(head -n1 $conf)" $rslv &>/dev/null; then
		echo "run 'tunlr start' to change your dns servers and try again"
		exit 1
	fi
	[ -n "$2" ] && tgts=$(echo "$*" | sed 's/^ip //')
	for i in $tgts; do
		echo -n "$i: "
		ping -c1 -q "$i" | grep -Eo '\<[[:digit:]]{1,3}(\.[[:digit:]]{1,3}){3}\>'
	done
	;;
update)
	echo -n "updating tunlr dns server... "
	cp $conf $conf.bak &>/dev/null
	> $conf
	if ping -q -c 1 tunlr.net &>/dev/null; then
		for srv in $(wget http://tunlr.net/get-started/ -q -O - | grep -Eo '\<[[:digit:]]{1,3}(\.[[:digit:]]{1,3}){3}\>'); do
			echo "nameserver $srv" >>$conf
		done
	else
		echo "failed"
		echo "tunlr.net seems to be down. please try again later"
		exit 1
	fi
	if [ -f $conf ] && [ -s $conf ]; then 
		echo "ok"
		echo "$conf:"
		cat $conf
		rm $conf.bak &>/dev/null
	else
		echo "failed"
		echo "restoring old config file"
		mv $conf.bak $conf
	fi
	;;
*)
	echo "usage: $0 {start|stop|ip <domain name>|update}"
	;;
esac
exit 0
