post_install() {
	echo	""
	echo	"You MUST configure /etc/conf.d/ffdecsawrapper and /etc/cardclient.conf for FFdecsawrapper to work"
	echo	"Phoenix compatible smartcard reader hardware is necessary"
	echo	"Smartcard server software is also required"
	echo	"Oscam works well for this - https://aur.archlinux.org/packages/oscam-svn/"
	echo	""
	echo	"Running depmod..."
	depmod
}

post_upgrade() {
	echo	""
	echo	"Running depmod..."
	depmod
}
