#!/bin/sh

# This script replicates the Cave Story Plus working folder in a specified 
# directory (defaults to ~/.cave-story-plus) by creating symbolic links to
# the installed files. This allows the game to store saves and configuration 
# files without write permissions in the install folder and lets every user
# on system keep their own saves/settings. It then launches the game or
# configuration tool.
# (Original stolen from the doukutsu package.)

INSTALLDIR=/opt/cave-story-plus
USERDATADIR=$HOME/.cave-story-plus

mkdir -p $USERDATADIR
cd $USERDATADIR
for file in $(ls $INSTALLDIR) ; do
    if [ ! -e $file ] ; then
        ln -s $INSTALLDIR/$file
    fi
done

exec ./CaveStory+ $@
