#!/usr/bin/bash
gogdir="/opt/gog/pinball-world"
homedir="$HOME/.gog/pinball-world"
mkdir -p "$homedir"/{game,config}

if [[ ! -e "$homedir/config/dosboxPWORLD.conf" ]]; then
  cp "$gogdir/dosboxPWORLD.conf" "$homedir/config/dosboxPWORLD.conf"
fi

unionfs "$homedir/config=RW:$gogdir=RO" "$homedir/game"
"$homedir"/game/start.sh
fusermount -u "$homedir/game" 
