# Contributor: Arch Haskell Team <arch-haskell@haskell.org>
# Package generated by cabal2arch 0.7
# Note: we list all package dependencies.
# Your package tool should understand 'provides' syntax
#
pkgname=haskell-openclraw-git
_pkgname=haskell-openclraw
pkgrel=1
pkgver=20100618
pkgdesc="The OpenCL Standard for heterogenous data-parallel computing"
url="http://hackage.haskell.org/package/OpenCLRaw"
license=('custom:BSD3')
arch=('i686' 'x86_64')
makedepends=('git')
depends=('ghc' 'haskell-cabal' 'haskell-bytestring' 'haskell-mtl')
options=('strip')
conflicts=('haskell-openclraw')
install=haskell-openclraw.install
md5sums=()

_gitroot="http://github.com/JeffHeard/OpenCLRaw.git"
_gitname="OpenCLRaw"

build() {
  cd "$srcdir"
  msg "Connecting to GIT server...."

  if [ -d $_gitname ] ; then
    cd $_gitname && git pull origin
    msg "The local files are updated."
  else
    git clone $_gitroot $_gitname
  fi

  msg "GIT checkout done or server timeout"
  msg "Starting make..."

  rm -rf "$srcdir/$_gitname-build"
  git clone "$srcdir/$_gitname" "$srcdir/$_gitname-build"
  cd "$srcdir/$_gitname-build"

  #
  # BUILD HERE
  #
    runhaskell Setup configure --prefix=/usr --docdir=/usr/share/doc/${_pkgname} || return 1
    runhaskell Setup build                   || return 1
    runhaskell Setup haddock || return 1
    runhaskell Setup register   --gen-script || return 1
    runhaskell Setup unregister --gen-script || return 1
    install -D -m744 register.sh   ${pkgdir}/usr/share/haskell/$_pkgname/register.sh
    install    -m744 unregister.sh ${pkgdir}/usr/share/haskell/$_pkgname/unregister.sh
    install -d -m755 $pkgdir/usr/share/doc/ghc/html/libraries
    ln -s /usr/share/doc/${_pkgname}/html ${pkgdir}/usr/share/doc/ghc/html/libraries/OpenCLRaw
    runhaskell Setup copy --destdir=${pkgdir} || return 1
    install -D -m644 LICENSE ${pkgdir}/usr/share/licenses/$_pkgname/LICENSE || return 1
    rm -f ${pkgdir}/usr/share/doc/${_pkgname}/LICENSE
}
