# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: uberushaximus <uberushaximus AT gmail DOT com>

_gemname=fiddler
pkgname=ruby-$_gemname
pkgver=1.0.1
pkgrel=1
pkgdesc='Interface to Request Tracker based on Roart Gem'
arch=(any)
url='https://github.com/jaischeema/fiddler'
license=('WTFPL')
depends=(ruby ruby-httpclient ruby-activesupport ruby-awesome_print ruby-active_attr)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('2c7593d24d4f3d5c5e084c13f5def51cd28a8843')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
