post_install() {
cat << EOF
  To install grub to the MBR of /dev/sda, run:  "grub-install --no-floppy --recheck /dev/sda"
  To generate a grub config file, run:          "grub-mkconfig -o /boot/grub/grub.cfg"
  . Keep in mind that a basic, unconfigured grub.cfg has already been provided.
 
  For more information please see http://wiki.archlinux.org/index.php/GRUB2

EOF

}


post_upgrade() {
    post_install
}
