#!/bin/bash

# aurdownload - download and extract packages from AUR
# Version: 1.0.8
# Author:  Michal Krenek (Mikos) <mikos@sg1.cz>
# License: GNU General Public License v.2
#          http://www.gnu.org/licenses/gpl.txt

if [ -z "$*" ]; then
  echo "aurdownload - download and extract packages from AUR"
  echo "Error: You must specify package name(s)"
  echo
  echo "Use --nodelete option for preserving old source code, but remember"
  echo "it must be on the first place right after aurdownload commmand!"
  exit 1
fi

for name in "$@"; do
  echo "Removing old archive '$name.tar.gz'..."
  rm -f "$name.tar.gz"


  echo "Downloading package '$name'..."
  wget -nv "http://aur.archlinux.org/packages/$name/$name.tar.gz"
  if [ $? -ne 0 ]; then
    echo "Can't download '$name.tar.gz'. Skipping this package..."
    echo
    continue
  fi

  echo "Extracting '$name.tar.gz' archive..."
  tar -xvzpf "$name.tar.gz"
  echo

  echo "Deleting $name.tar.gz"
  rm "$name.tar.gz"
done
