post_install() {
  post_upgrade
}

post_upgrade() {
  getent group "tdsm" &> /dev/null || groupadd -r tdsm 1> /dev/null
  getent passwd "tdsm" &> /dev/null || useradd -r -g tdsm -d "/srv/tdsm" -s "/bin/sh" tdsm 1> /dev/null
  chown -R tdsm:tdsm "/srv/tdsm" 1> /dev/null
  chmod 755 "/srv/tdsm"
}

post_remove() {
  if getent passwd "tdsm" > /dev/null; then
    userdel tdsm > /dev/null
  fi
  if getent group "tdsm" > /dev/null; then
    groupdel tdsm > /dev/null
  fi
}
