#!/bin/bash
. /etc/rc.conf
. /etc/rc.d/functions

DAEMON=jenkins

[ -r /etc/conf.d/$DAEMON ] && . /etc/conf.d/$DAEMON
PIDFILE="/var/run/daemons/$DAEMON.pid"
PID=`cat $PIDFILE`

echo $ARGS

case "$1" in
 start)
   stat_busy "Starting $DAEMON"
   if [ -z "$PID" ]; then 
     sudo -u jenkins nohup java -jar /usr/share/java/jenkins/jenkins.war --httpPort=8090 --ajp13Port=-1 > /var/log/jenkins.log < /dev/null &
     echo $! > $PIDFILE
   fi

   if [ $? = 0 ]; then
     add_daemon $DAEMON
     stat_done
   else
     stat_fail
     exit 1
   fi
   ;;
 stop)
   stat_busy "Stopping $DAEMON"
   [ -n "$PID" ] && kill $PID
   if [ $? = 0 ]; then
     rm_daemon $DAEMON
     rm $PIDFILE
     stat_done
   else
     stat_fail
     exit 1
   fi
   ;;
 restart)
   $0 stop
   sleep 1
   $0 start
   ;;
 *)
   echo "usage: $0 {start|stop|restart}"  
esac

