#!/bin/sh
java -Djava.library.path=/usr/lib -Dsun.java2d.noddraw=true -Dsun.awt.noerasebackground=true -Dsun.java2d.d3d=false -Dsun.java2d.opengl=false -Dsun.java2d.pmoffscreen=false \
-cp /usr/share/java/zomboid-demo/zombie.jar:/usr/share/java/lwjgl.jar:/usr/share/java/lwjgl_util.jar:/usr/share/java/input.jar zombie.FrameLoader