#!/usr/bin/env python
from sys import argv
from imgurpython import ImgurClient
client_id="9ccfd4053f037ff"
client_secret="045df64747a22e1e08e40c6c498548ac0de481fe"
access_token="50b2e3cba02a93e0e239633dd745adf24b42658b"
refresh_token="ca46af9f3d56051894668de09d4f4f802d43f9f1"
client=ImgurClient(client_id, client_secret, access_token, refresh_token)
imgpath=argv[1]
img=client.upload_from_path(imgpath, config=None, anon=True)
print(img["link"])
