post_install() {
  #find . -exec sed -i 's/env python/env python2' {} + ;
cat << EOM

==> Since there exists a cheat for Ruby Gem, call the program as:
  % pycheat

==> To change the location export the CHEATPATH environment variable in your shell config file:
  % export CHEATPATH=/path/to/my/cheatsheets

==> You may also append multiple directories to your CHEATPATH:
  % export CHEATPATH=$CHEATPATH:/path/to/more/cheatsheets

EOM
}

# vim: set ts=2 sw=2 et:
