#!/bin/bash

daemon_name="dropboxd"
dropboxd_bin="/usr/bin/dropboxd"
instance_name="dropbox"

. /etc/rc.conf
. /etc/rc.d/functions

get_pid() {
    pidof -o %PPID $instance_name
}

case "$1" in
    start)
        stat_busy "Starting $daemon_name"

        PID=$(get_pid)
        if [ -z "$PID" ]; then
           $dropboxd_bin &>/dev/null &
           # well, is it running NOW?!
           # can't check based on exit codes
           # cuz it doesn't give any! woops!
           if [ -n $(get_pid) ]; then
               add_daemon $daemon_name
               stat_done
            else
                # Didn't start right.
                stat_fail
                exit 1
            fi
        else
            # dropbox is probably already running.
            # not going to restart it because
            # that's not what "start" command is supposed to do
            stat_fail
            exit 1
        fi
        ;;

    stop)
        stat_busy "Stopping $daemon_name"
        PID=$(get_pid)
        if [ -n "$PID" ]; then
            kill $PID &>/dev/null
            
            # catches if the kill command f*cks up.
            # probably not needed.
            if [ $? = 0 ]; then
                rm_daemon $daemon_name
                stat_done
            else
                stat_fail
                exit 1
            fi
        else
            stat_fail
            exit 1
        fi
        ;;

    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    
    *)
        echo "usage: $0 {start|stop|restart}"

esac
