post_install() {
	if [ ! -d "/etc/init.d" ]; then
		mkdir "/etc/init.d"
	fi

	cd /etc/init.d
	ln -s /opt/kaspersky/klnagent/lib/bin/klnagent .

	echo "Please run '/opt/kaspersky/klnagent/lib/bin/setup/klnagent_setup.pl' manually as root user after the installation finishes."
}

pre_remove() {
	/opt/kaspersky/klnagent/lib/bin/setup/uninstall.pl

	cd /etc/init.d
	rm /opt/kaspersky/klnagent/lib/bin/klnagent

	# Remove /etc/init.d if it is empty
	if [ "$(ls -A /etc/init.d)" ]; then
		rmdir /etc/init.d
	fi
}
