--- Makefile-Linux.orig	2010-01-15 21:45:21.791876742 +0300
+++ Makefile-Linux	2010-01-15 21:48:54.509121551 +0300
@@ -27,9 +27,7 @@
 install: installdirs\
 	 install-airoscript install-themes \
 	 install-tools \
-	 install-docs \
-	 install-locale \
-	 post-install
+	 install-docs
 
 installdirs:
 	@$(SHELL) $(srcdir)/mkinstalldirs $(bindir) $(datadir) \
