#!/bin/sh

post_install(){
    echo Adding eduroam to active list...
    if grep eduroam /etc/wicd/encryption/templates/active > /dev/null 
    then
        echo Eduroam was already installed!
    else
        echo eduroam >> /etc/wicd/encryption/templates/active && echo Eduroam added to active list
    fi
}
post_remove(){
    export f=/etc/wicd/encryption/templates/active
    echo -n Deleting eduroam from active list...
    sed -e 's/^eduroam$//g' -i $f
    echo ' [DONE]'
}

post_remove

