post_install() {
 echo '-----------------------------------------------------------------------'
 echo '1) Be sure you edit /etc/checkip.conf to reflect your email address and'
 echo '   server before you run the script.'
 echo
 echo '2) Be sure you add an entry to your users crontab to have the script run'
 echo '   at some regular interval.'
 echo 
 echo '   Edit your users crontab by typing: crontab -e'
 echo '   Examples'
 echo '   Once per hour:       0 * * * *  /usr/bin/checkip.sh > /dev/null 2>&1'
 echo '   Every four hours:   0 */4 * * * /usr/bin/checkip.sh > /dev/null 2>&1' 
 echo '-----------------------------------------------------------------------'
}

post_remove() {
 echo '-----------------------------------------------------------------------'
 echo '          Be sure you remove the entry in your users crontab.'
 echo '-----------------------------------------------------------------------'
}
