post_install() {
 echo '-----------------------------------------------------------------------'
 echo '1) Invoke by issuing a `checkip` and following setup instructions.'
 echo
 echo '2) Be sure to  add an entry to your users crontab to have the script run'
 echo '   at some regular interval.'
 echo 
 echo '   Edit your users crontab by typing: crontab -e'
 echo '   Examples'
 echo '   Once per hour:      0 * * * *   /usr/bin/checkip c &>/dev/null'
 echo '   Every four hours:   0 */4 * * * /usr/bin/checkip c &>/dev/null' 
 echo '-----------------------------------------------------------------------'
}

post_remove() {
 echo '-----------------------------------------------------------------------'
 echo '          Be sure you remove the entry in your users crontab.'
 echo '-----------------------------------------------------------------------'
}
