post_install() {
  gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
echo "
  To use, start 'urserver.service', enable it to start at boot,
  More information about systemd here:
  https://wiki.archlinux.org/index.php/systemd

  To load a custom configuration file:
  Create the file '/etc/default/urserver',
  edit as needed, then restart the server.
     "
}

post_upgrade() {
  post_install
}

post_remove() {
  gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
}
