#Automatically generated by pip2arch on 2012-06-20

pkgname=motmot.flymovieformat
pkgver=0.5.9.1
pkgrel=1
pkgdesc="support for .fmf (fly movie format) files"
url="http://code.astraw.com/projects/motmot/fly-movie-format.html"
depends=('python2' )
makedepends=('python2-distribute' )
license=('BSD')
arch=('any')
source=('http://pypi.python.org/packages/source/m/motmot.FlyMovieFormat/motmot.FlyMovieFormat-0.5.9.1.zip')
md5sums=('c2fefd4417967b308c7e85025f3af8e6')

build() {
    cd $srcdir/motmot.FlyMovieFormat-0.5.9.1
    python2 setup.py build
}

package() {
    cd $srcdir/motmot.FlyMovieFormat-0.5.9.1
    python2 setup.py install --root="$pkgdir" --optimize=1 
}
