post_install() {
    echo -e '\E[1;34m'
    echo " "
    echo " "
    echo "<==== INFORMATION ====>"
    echo " "
    echo " ==> Droid Assault is now installed."
    echo " "
    echo " ==> The full version can be purchased for $ 9.97"
    echo " ==> Homepage: http://www.puppygames.net/droid-assault/"
    echo " "
    echo " ==> Accessing the game by typing 'droidassault'"
    echo " ==> in the terminal."
    echo " "

tput sgr0 
} 
