#!/bin/sh
cd /usr/share/java/runescape-client-bin

CP="/usr/share/java/runescape-client-bin/jagexappletviewer.jar"

"$JAVA_HOME/bin/java" \
    -cp $CP \
    -Dcom.jagex.config=http://www.runescape.com/k=3/l=0/jav_config.ws \
    jagexappletviewer ../pixmaps
