#!/bin/sh
cd /usr/share/java
"$JAVA_HOME/bin/java" -Djava.class.path="/usr/share/java/jagexappletviewer.jar" -Dcom.jagex.config=http://www.runescape.com/k=3/l=en/jav_config.ws jagexappletviewer pixmaps
