post_upgrade() {
	cat << EOF
    Crontab is no longer supported. The prefered method is still with --loop-time.
    Alternatively you can use systemd timer included in the package. Please see man aarchup.
EOF
}

post_install() {
	cat <<EOF
    Please check man pages for installation instructions.
    If you have any problems or would like to request a feature,
    check https://bbs.archlinux.org/viewtopic.php?id=119129
EOF
}
