post_upgrade() {
	cat << EOF
    Now you can optionally use /etc/aarchup.conf to
    configure aarchup instead of passing command-line
    arguments. Check man pages for details.
EOF
}

post_install() {
	cat <<EOF
    Please check man pages for installation instructions.
    If you have any problems or would like to request a feature,
    check https://bbs.archlinux.org/viewtopic.php?id=119129
EOF
}
