#!/bin/bash

# Shell script that emulates the behaviour of "Adobe AIR Application Installer"

if [ "$1" == "" -o "$2" == "" ]; then
	echo "Usage: `basename $0` source_app.air target_path"
	exit 1
fi

source_app=$1
target_path=$2

if [ "${source_app%.air}.air" != "$source_app" ]; then
	echo "Source file must end with .air"
	exit 1
fi

# Create directory structure
mkdir -p $target_path/bin || exit 1
mkdir -p $target_path/share || exit 1

# Unpack shared data
unzip -q -d $target_path/share $source_app || exit 1

# Write launcher script
target_stub=`basename $source_app`
target_stub=$target_path/bin/${target_stub%.air}

cat > $target_stub <<EOF
#!/bin/bash

# This is a generic launcher script for AIR applications on Arch Linux

SCRIPT_PATH=\`readlink -f \$0\`
SCRIPT_DIR=\`dirname \$SCRIPT_PATH\`
BASE_DIR=\`readlink -f \$SCRIPT_DIR/..\`

if [ "\`uname -m\`" == "x86_64" ]; then
	export GTK_PATH=/opt/lib32/usr/lib/gtk-2.0
	export PANGO_RC_FILE=/opt/lib32/config/pango/pangorc
	export GDK_PIXBUF_MODULE_FILE=/opt/lib32/config/gdk/gdk-pixbuf.loaders
	export GTK_IM_MODULE_FILE=/opt/lib32/config/gdk/gdk.immodules
	export G_FILENAME_ENCODING=UTF-8
fi

/opt/adobe-air-sdk/bin/adl -nodebug \$BASE_DIR/share/META-INF/AIR/application.xml \$BASE_DIR/share

EOF

chmod +x $target_stub

