# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Jean-Noël Rouchon <jnoel@sissiou.net>

_gemname=ezcrypto
pkgname=ruby-$_gemname
pkgver=0.7.2
pkgrel=1
pkgdesc='Simplified encryption library.'
arch=(any)
url='http://ezcrypto.rubyforge.org'
license=('MIT')
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('523dfa1fcf82d2f02d1098a8dc28c1112afc9a92')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/MIT-LICENSE" "$pkgdir/usr/share/licenses/$pkgname/MIT-LICENSE"
}
