diff -Naur bcp-20011229.orig/Makefile bcp-20011229/Makefile
--- Makefile.orig	2001-12-29 15:03:13.000000000 +0100
+++ Makefile	2009-04-15 17:58:43.000000000 +0200
@@ -1,4 +1,4 @@
-CFLAGS= -O3 -Wall -fomit-frame-pointer -malign-functions=0
+CFLAGS= -O3 -Wall -fomit-frame-pointer -falign-functions=0
 LDFLAGS= -s
