post_install() {
	echo "Please use systemd units to start/stop GoAgent"
	echo "sudo systemctl start/stop goagent"
	echo " or click goagent.desktop in program menu"
	echo " Need Updata Server!!!!!"
	echo " Use folowing commmend to update your server"
	echo ">>> python /usr/share/GoAgent/server/uploader.zip"
	echo "Notice to edit /ext/goagent, Add your appid"
	echo "First run shoud use root!"
	chown -R nobody:daemon /usr/share/GoAgent/local
}
post_upgrade() {
	post_install
}
pre_upgrade() {
	rm -rf /opt/goagent/local/certs
	rm -rf /usr/share/GoAgent/local/certs
	rm -rf /usr/share/GoAgent/server/.appcfg_cookies
}
pre_remove() {
	rm -rf /opt/goagent/local/certs
	rm -rf /usr/share/GoAgent/local/certs
	rm -rf /usr/share/GoAgent/server/.appcfg_cookies
}
