post_install() {
    gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
    echo "  "
    echo "  The setup created an udev rule, so before using the program you"
    echo "  have to either reboot or manually execute rule's commands."
    echo "  Current user has also to be member of video group, the udev rule"
    echo "  sets permissions only to video group members (and of course root)"
    echo "  "
}
