--- Makefile.orig	2008-07-20 00:55:53.000000000 +0200
+++ Makefile	2008-07-20 00:56:01.000000000 +0200
@@ -4,7 +4,7 @@
 
 OUT = ./everborn
 DUMP_DIR = DUMP/
-CFLAGS = -g `sdl-config --cflags` -Wno-write-strings
+CFLAGS += `sdl-config --cflags` -Wno-write-strings
 #LIBMIXER = /usr/lib/libSDL_mixer.a -lvorbisfile -lmikmod -lsmpeg
 LIBMIXER = -lSDL_mixer
 LIBS = -lGL -lm -lpng `sdl-config --libs` $(LIBMIXER)
