post_install() {
    echo -e '\E[1;34m'
    echo " "
    echo " "
    echo "<==== INFORMATION ====>"
    echo " "
    echo " ==> Titan Attacks is now installed."
    echo " "
    echo " ==> The full version can be purchased for $ 19.95"
    echo " ==> Homepage: http://www.puppygames.net/titan-attacks/"
    echo " "
    echo " ==> Accessing the game by typing 'titanattacks'"
    echo " ==> in the terminal."
    echo " "

tput sgr0 
} 
