post_install() {
    echo 
    echo "By installing and using this software"
    echo "you are bound by the license agreement"
    echo "found in:"
    echo
    echo " /usr/share/doc/adobe-icc/LICENSE"
    echo
    echo "and"
    echo 
    echo " /usr/share/doc/adobe-icc/Color\ Profile\ EULA.pdf"
    echo
    echo "Please read this license carefully, and"
    echo "remove this package if you do not agree."
    echo
}