## arg 1:  the new package version
post_install() {
	ln -s /opt/whitebox/whitebox.sh /usr/bin/whitebox
	update-desktop-database -q
	echo "## Modify the /opt/whitebox/whitebox.sh script to adjust JAVA memory/RAM usage!" 
}
## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
	rm /usr/bin/whitebox
	post_install	
}
## arg 1:  the old package version
post_remove() {
        rm /usr/bin/whitebox
}
