. /etc/rc.conf
. /etc/rc.d/functions

post_install() {
  echo -e "$C_CLEAR"
  printsep
  printhl "If you use the LILO bootloader, you should edit /etc/lilo.conf and run 'lilo' ."
  printsep
  echo -e "$C_CLEAR"
}

post_upgrade() {
  echo -e "$C_CLEAR"
  printsep
  printhl "If you use the LILO bootloader, you should run 'lilo' after upgrading."
  printsep
  echo -e "$C_CLEAR"
}

op=$1
shift

$op $*
