post_install() {
  getent group heat &>/dev/null || groupadd heat >/dev/null
  getent passwd heat &>/dev/null || useradd  -d /var/lib/heat -g heat -s /bin/false heat >/dev/null

  chmod 755 /etc/heat
  chown -R root:heat /etc/heat
  chown heat /var/log/heat
  chown heat:heat /var/lib/heat
}

post_upgrade() {
  post_install
}

pre_remove() {
  getent passwd heat &>/dev/null && userdel heat >/dev/null
  getent group heat &>/dev/null && groupdel heat >/dev/null
  true
}

# vim:set ts=2 sw=2 et:
