post_install() {
  echo "==> FOLLOW CAREFULLY:"
  echo "-------------------------------------------------------------------"
  echo "  # nano /etc/fl_teachertool/teacher/vncreflectorpass"
  echo "    -> REPLACE 'fullcontrolpassword' with a password of your choice"
  echo "    -> REPLACE 'viewonlypassword' with a password of your choice"
  echo "  # teachertool-vncpasswd /etc/fl_teachertool/teacher/teacherpass"
  echo "    -> enter your fullcontrolpassword and then answer 'n'"
  echo "  # teachertool-vncpasswd /etc/fl_teachertool/clientpass"
  echo "    -> note the pathname carefully (not the same as teacherpass)"
  echo "    -> enter your viewonlypassword and then answer 'n'"
  echo "  # chmod 600 /etc/fl_teachertool/teacher/vncreflectorpass"
  echo "  # chmod 600 /etc/fl_teachertool/teacher/teacherpass"
  echo "  # chmod 644 /etc/fl_teachertool/clientpass"
  echo "-------------------------------------------------------------------"
  echo "==> Documentation: /usr/share/doc/fl_teachertool/documentation.html"
}

post_upgrade() {
  post_upgrade $1
}
