post_install()
{
	echo "Setting Antergos as default LightDM Theme"
	sed -i 's|greeter-session=.*|greeter-session=lightdm-webkit-greeter|2' /etc/lightdm/lightdm.conf
	sed -i 's|#greeter-session=|greeter-session=|2' /etc/lightdm/lightdm.conf
	sed -i 's|webkit-theme=.*|webkit-theme=antergos|g' /etc/lightdm/lightdm-webkit-greeter.conf
	sed -i 's|#webkit-theme=|webkit-theme=|g' /etc/lightdm/lightdm-webkit-greeter.conf

}
