post_install() {
  cat << EOM

==> Unfortunately our liblo is out-of-date as of
==> 2008-06-04, so you will not have osc support.

==> A binary of liblo 0.24 is available from the
==> madfire proaudio repository. You will have to
==> recompile psychosynth after installing it.

http://bbs.archlinux.org/viewtopic.php?id=30547

==> You will also have to make sure that OGRE was
==> compiled with "devil", and of course CEGUI.

EOM
}

post_upgrade() {
  post_install
}
