# arg 1:  the new package version
post_install() {
  echo "nerolinux: For Nero to be able to detect CD/DVD drives,"
  echo "nerolinux: add yourself to the 'optical' group."
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  echo "nerolinux: For Nero to be able to detect CD/DVD drives,"
  echo "nerolinux: add yourself to the 'optical' group."
}

# arg 1:  the old package version
pre_remove() {
  /bin/true
}

op=$1
shift

$op $*
