pkgname=vuze-extreme-mod

post_install() {
    gconfpkg --install "$pkgname"
    update-desktop-database -q
#     xdg-icon-resource forceupdate &>/dev/null
}

pre_upgrade() {
    gconfpkg --uninstall "$pkgname"
}

post_upgrade() {
    update-desktop-database -q
#     xdg-icon-resource forceupdate &>/dev/null
}

pre_remove() {
    pre_upgrade
}

post_remove() {
    post_upgrade
#     xdg-icon-resource forceupdate &>/dev/null
}
