#!/bin/sh

#export GTK_PATH=/opt/lib32/usr/lib/gtk-2.0
#export PANGO_RC_FILE=/opt/lib32/config/pango/pangorc
#export GDK_PIXBUF_MODULE_FILE=/opt/lib32/config/gdk/gdk-pixbuf.loaders
#export GTK_IM_MODULE_FILE=/opt/lib32/config/gdk/gdk.immodules

export G_FILENAME_ENCODING=UTF-8
#export LC_ALL=C
/opt/lib32/usr/bin/flashplayer $1