#!/bin/ash

cmdline=$(cat /proc/cmdline)

for arg in $cmdline; do
    case $arg in resume=*)
    	resume=${arg#resume=}
    esac
done
echo "<5>Resume parameter: $resume"

case $resume in
    '')
        echo "<5>No resume parameter" ;;
    *)
        case "$resume" in
            LABEL=*)
                resume="$(echo $resume | sed 's,/,\\x2f,g')"
                resume="/dev/disk/by-label/${resume#LABEL=}" ;;
            UUID=*)
                resume="/dev/disk/by-uuid/${resume#UUID=}" ;;
            PARTUUID=*)
                resume="/dev/disk/by-partuuid/${resume#PARTUUID=}" ;;
            PARTLABEL=*)
                resume="/dev/disk/by-partlabel/${resume#PARTLABEL=}" ;;
        esac        
        echo "<5>Resume device: $resume"
        
        echo "<5>Trying to reach resume device"
        while [ ! -b "$resume" ]; do
        	sleep 1
        done
        if [ -b "$resume" ]; then
        	echo "<5>Got to resume device"
		    if [ -e /sys/power/resume ]; then
		        printf "%d:%d" $(stat -Lc "0x%t 0x%T" "$resume") >/sys/power/resume
		        echo "<5>Wrote major:minor"
		    else
		    	echo "<5>Couldn't write major:minor"
		    fi
        fi
        ;;
esac
