# This is a default template for a post-install scriptlet.
# Uncomment only required functions and remove any functions
# you don't need (and this header).

pre_upgrade() {
chmod 755 /usr/share/apps/ksplash/Themes/SteampunK/{Backgrounds,Animations,"2133x1200","1920x1200","1600x1200","1500x1200"}

#chmod 755 /usr/share/apps/ksplash/Themes/SteampunK/${"Backgrounds" "Animations" "2133x1200" "1920x1200" "1600x1200" "1500x1200"}
}
