post_install() {
	echo " > VMware View client for Linux now has support for redirecting USB devices"
	echo " > to the virtual machine. To make this work you have to launch"
	echo " > /usr/lib/systemd/scripts/vmware-view-usbd or start/enable"
	echo " > systemd service vmware-view-usbd (systemctl start vmware-view-usbd)."

	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
	update-desktop-database -q
}

post_upgrade(){
	post_install
}
