--- Makefile	2012-03-22 23:19:12.547871104 +0100
+++ Makefile.new	2012-03-22 23:27:48.888628413 +0100
@@ -4,11 +4,20 @@
 # Choose here wich include file to use: from kernel 3.0.0 (good for 3.1.0) or from kernel 3.2.0
 
 # kernel 3.0.0 / 3.1.0
-INCLUDE_EXTRA_DVB := include-300
+#INCLUDE_EXTRA_DVB := include-300
 
 # kernel 3.2.0
 #INCLUDE_EXTRA_DVB := include-320
 
+KERNELVERSION = $(shell uname -r | cut -f1-2 -d.)
+ifeq ($(KERNELVERSION),$(filter $(KERNELVERSION),3.0 3.1))
+  INCLUDE_EXTRA_DVB := include-300
+endif
+
+ifeq ($(KERNELVERSION),3.2))
+  INCLUDE_EXTRA_DVB := include-320
+endif
+
 # ----------------------------------------
 
 # current dir
@@ -35,7 +44,7 @@
 		-I$(SOURCEDIR)/$(INCLUDE_EXTRA_DVB) 
 
 KINS = /lib/modules
-KDIR = /usr/src/linux-headers-`uname -r`
+KDIR = /usr/src/linux-`uname -r`
 
 default:
 	make -C $(KDIR) SUBDIRS=$(PWD) modules
