--- Makefile	2010-05-24 17:17:05.000000000 +0200
+++ Makefile_	2010-07-20 02:14:56.000000000 +0200
@@ -1,4 +1,4 @@
-# 
+#
 # xAutoClick
 #
 # Copyright (C) 2006, 2010 Ivo van Poorten
@@ -136,7 +136,7 @@
 	ln -s guigtk1.c guigtk2.c
 
 guiqt4-moc.cpp:	guiqt4.h
-	moc-qt4 -oguiqt4-moc.cpp guiqt4.h
+	moc -oguiqt4-moc.cpp guiqt4.h
 
 #strip:	$(PRG)
 #	strip $(PRG)
