# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Jonas Amundsen <jonasba+aur at gmail dot com>

_gemname=json_better_formatter
pkgname=ruby-$_gemname
pkgver=1.0.0
pkgrel=1
pkgdesc='A streaming-based JSON formatter in Ruby.'
arch=(any)
url='https://github.com/badeball/json_better_formatter'
license=(MIT)
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('58f2811c4148c9b629f2b2b9ab7aa6cfdda2a7fd')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
