post_install() {

    echo "
    ============================== Remember! ==============================
    Read here: http://www.serverdensity.com
    and here: http://www.serverdensity.com/pricing

    Server Density is a free service for monitoring your server
    and make alert. For a free servire you must downgrade your profile.

    However if you want to try the enhanced version (Apache etc.).
    You have 30 trial days. After you have to pay for the service or downgrade
    your profile.
    ======================================================================="

}
