post_install() {
  	cat <<-EndOfMessage
	NOTE 1: Remember to add user to lp group using 
		gpasswd -a USER lp
	NOTE 2: Remember to blacklist "usblp" (!usblp) module in the module Array in the rc.conf
	NOTE 3: Remember to add "cups" to rc.conf Daemons Array
	NOTE 3: Remember to logout after adding groups
	NOTE 5: Remember to execute as root the following executable:	
		/usr/local/Brother/cupswrapper/cupswrapperDCP110C-1.0.0
	EndOfMessage
}
