#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting utorrent-server"
    [ ! -f /var/run/daemons/utserver ] && /usr/share/utserver/utserver.sh >/dev/null 2>&1
    if [ $? -gt 0 ]; then
      stat_fail
    else
      pgrep -of /usr/bin/utserver > /var/run/utserver.pid
      add_daemon utserver
      stat_done
    fi
    ;;

  stop)
    stat_busy "Stopping utorrent-server"
    [ -f /var/run/utserver.pid ] && kill `cat /var/run/utserver.pid` >/dev/null 2>&1
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon utserver
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
