# Generated by gem2arch
# Maintainer: LeeF

_gemname=actionmailer
pkgname=ruby-enterprise-actionmailer-235
pkgver=2.3.5
pkgrel=2
pkgdesc="Service layer for easy email delivery and testing."
arch=('i686' 'x86_64')
url="http://www.rubyonrails.org"
license=('MIT')
depends=('ruby-enterprise' 'ruby-enterprise-actionpack-235')
makedepends=('ruby-enterprise')
source=(http://gems.rubyforge.org/gems/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
md5sums=('623772ef110fe42f4fbefbf99d8c3524')

build() {
  cd $srcdir
  local _gemdir=`/opt/ruby-enterprise/bin/ruby -rubygems -e'puts Gem.default_dir'`
  /opt/ruby-enterprise/bin/gem install --ignore-dependencies --no-rdoc --no-ri -i "$pkgdir$_gemdir" $_gemname-$pkgver.gem
}
