--- yaml-0.2-orig/Makefile	2010-03-06 21:58:10.757823698 -0600
+++ yaml-0.2/Makefile	2010-03-06 22:00:52.444590033 -0600
@@ -22,7 +22,7 @@
 all:    yaml.so
 
 install:
-	cp -f yaml.so $(LUA_LIBDIR)
+	install -D -m644 yaml.so $(LUA_LIBDIR)/yaml.so
 
 uninstall:
 	rm -f $(LUA_LIBDIR)/yaml.so 
