# arg 1:  the new package version
post_install() {
		chgrp -R leterrier /usr/share/abuledu-aller/reglages
		chgrp -R leterrier /usr/share/abuledu-aller/textes
		chmod -R g+w /usr/share/abuledu-aller/reglages
		chmod -R g+w /usr/share/abuledu-aller/textes
		chmod 3777 /usr/share/abuledu-aller/aller/log		
		chmod 777 /usr/share/abuledu-aller/reglages/aller.conf
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $1
}



op=$1
shift
$op $*
