#!/bin/bash
#
# PHP-FastCGI start/stop script

. /etc/rc.conf
. /etc/rc.d/functions

PATH="/bin:/usr/bin:/sbin:/usr/sbin"
PHP_FCGI="/usr/sbin/php-fcgi"
PIDFILE="/var/run/php-fcgi.pid"

test -f ${PHP_FCGI} || exit 0

function start_php_fcgi {
	if [ -f ${PIDFILE} ]; then
                stat_busy "FastCGI is already running"
                stat_done
	else
                fcgi_ver=`/usr/sbin/php-fcgi -v`
                stat_busy "Starting ${fcgi_ver}"
		${PHP_FCGI} &> /dev/null
		result=$?
		if [ "${result}" = "0" ]; then
                        add_daemon php-fcgi
                        stat_done
		else
                        fcgi_Error=`/usr/sbin/php-fcgi 2>&1`
                        stat_busy "$fcgi_Error"
                        stat_fail
		fi
	fi
}

function stop_php_fcgi {
	if [ -f ${PIDFILE} ]; then
                stat_busy "Stopping PHP FastCGI server daemons"
		${PHP_FCGI} -k &> /dev/null
                 stat_done
	else 
		stat_busy "FastCGI is not running"
                stat_done 
	fi
}

case "$1" in
	start)
		start_php_fcgi
		;;
	stop)
		stop_php_fcgi
		;;
	restart)
		stop_php_fcgi
		start_php_fcgi
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

exit 0
