post_install() {
echo "You need an active internet connection, which"
echo "is necessary for this script to work"
echo
echo "You must enable a multilib repository"
echo "and then run at least once \"pkgfile -u\""
echo "with root privileges (preferably recently),"
echo "before running this script"
echo
echo "Syntax: debtap-p64 [option] package_filename"
echo
echo "Run \"debtap-p64 -h\" for help"
}
