# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Bruno Souza (varnion at yandex dot com)

_gemname=terminal-table
pkgname=ruby-$_gemname
pkgver=1.4.5
pkgrel=1
pkgdesc='Simple, feature rich ascii table generation library'
arch=(any)
url='http://github.com/visionmedia/terminal-table'
license=(MIT)
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('17f6a889b8bcc91a1242fabc39bac186f8e9542a')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
