--- Makefile.orig	2012-02-20 20:31:01.987031630 +0100
+++ Makefile	2012-02-20 20:41:40.080241449 +0100
@@ -26,7 +26,7 @@
 export LIB_NAME := texttools
 SOVERSION := 1
 export SONAME := lib$(LIB_NAME).so.$(SOVERSION)
-export LIB_DIR := .
+export LIB_DIR := lib
 
 # Ignore "make" obsolete suffix rules
 .SUFFIXES:
@@ -62,12 +62,13 @@
 	$(MAKE) -C examples $@
 
 install: build
-	install -d $(DESTDIR)/usr/share/ada/adainclude/$(LIB_NAME)
-	install --mode=444 *.ad[sb] C_code/*.[ch] $(DESTDIR)/usr/share/ada/adainclude/$(LIB_NAME)
-	install --mode=444 $(LIB_NAME).gpr $(DESTDIR)/usr/share/ada/adainclude
-	install -d $(DESTDIR)/usr/lib/ada/adalib/$(LIB_NAME)
-	install --mode=444 shared-ali/* $(DESTDIR)/usr/lib/ada/adalib/$(LIB_NAME)
-	install --mode=444 lib$(LIB_NAME).a lib$(LIB_NAME).so $(SONAME) $(DESTDIR)/usr/lib
+	install -d $(DESTDIR)/usr/include/$(LIB_NAME)
+	install --mode=444 *.ad[sb] C_code/*.[ch] $(DESTDIR)/usr/include/$(LIB_NAME)
+	install --mode=444 $(LIB_NAME).gpr $(DESTDIR)/usr/lib/gnat/
+	install -d $(DESTDIR)/usr/lib/$(LIB_NAME)
+	install --mode=444 shared-ali/* $(DESTDIR)/usr/lib/$(LIB_NAME)
+	install --mode=444 lib/lib$(LIB_NAME).a lib/lib$(LIB_NAME).so lib/$(SONAME) $(DESTDIR)/usr/lib/$(LIB_NAME)
+	ln -s $(LIB_NAME)/lib$(LIB_NAME).so $(SONAME) $(DESTDIR)/usr/lib/
 
 ######################################################################
 #  All that C stuff will be unnecessary with gprbuild’s mixed C/Ada
