.TH mrbayes "1" "May 2008" "mrbayes 3.1.2" "User Commands"
.SH NAME
mb \- A program for the Bayesian estimation of phylogeny
.SH SYNOPSIS
.B mb [OPTION]... [FILE]...
.SH DESCRIPTION
A program for the Bayesian estimation of phylogeny.

MrBayes is a program for the Bayesian estimation of
phylogeny. Bayesian inference of phylogeny is based upon a quantity
called the posterior probability distribution of trees, which is the
probability of a tree conditioned on the observations. The
conditioning is accomplished using Bayes's theorem. The posterior
probability distribution of trees is impossible to calculate
analytically; instead, MrBayes uses a simulation technique called
Markov chain Monte Carlo (or MCMC) to approximate the posterior
probabilities of trees.

You can get a full manual in PDF format at their website. The URL is
http://mrbayes.csit.fsu.edu/mb3.1_manual.pdf

.SH OPTIONS
.B \-i
interactive mode

.SH AUTHORS

This manual page has been written by Abhishek Dasgupta
<abhidg@gmail.com> for Archlinux since the original package did not
provide a manual page. It is based upon some slight additions and
alterations to the Ubuntu manual page for the same package.
