post_install() {
	echo "IMPORTANT"
	echo "1. To enable support for tags:"
	echo "   $ ln -s /usr/share/vim/vimfiles/doc/tags/atp-tags ~/.vim/doc/tags"
	echo "   or wherever your personal Vim files are."
	echo "2. To enable support for Python and get the Python parts working:"
	echo "   – You will need a +python Vim; install gVim or recompile with ABS."
	echo "   – Add \"let g:atp_Python = \"/usr/bin/python\"\" to your ~/.vimrc."
	echo ""
}

post_upgrade() {
  post_install $1
}
