post_install() {
	echo	""
	echo	"This package installs the TBS drivers for you. They should not be pre-installed"
	echo	""
	echo	"You MUST configure /etc/conf.d/ffdecsawrapper and /etc/cardclient.conf for FFdecsawrapper to work"
	echo	"Also a SC reader and SC server package is necessary. Oscam works well for this"
	echo	"https://aur.archlinux.org/packages/oscam-svn/"
	echo	""
	echo	" . . . running depmod"
	depmod
}

post_upgrade() {
	echo	" . . . running depmod"
	depmod
}
