post_install() {
/bin/cat << ENDOFMESSAGE
>>>
>>>  Instructions on how to configure your eID with e.g. Firefox can be
>>>  found here: 
>>>  http://users.telenet.be/mydotcom/howto/linux/ubuntubelpic_new.htm
>>>  
>>>  Make sure to install the driver for your card reader, and keep in
>>>  mind you'll need Firefox 3 to file your taxes online. It can be
>>>  found in the AUR - the package is called firefox3.
>>>
ENDOFMESSAGE
}

post_upgrade() {
post_install
}

op=$1
shift
$op $*
