# Maintainer: Alexander Schade <schade[wtf1]in.tum[wtf2][wtf3][wtf4]>
# (where [wtf1] is 0x40, [wtf2] is 0x2E, [wtf3] is 100 in decimal, and [wtf4] is the 26-th prime)
# This PKGBUILD is based on 'cantor' by Adria Arrufat

pkgname=stp
pkgver='gitlatest'
pkgrel=1
pkgdesc="STP is a constraint solver aimed at solving constraints generated by program analysis tools, theorem provers, automated bug finders, biology, cryptography, intelligent fuzzers and model checkers."
arch=('i686' 'x86_64')
url="https://sites.google.com/site/stpfastprover/"
license=('The MIT License')
depends=(gcc-libs glibc boost)
optdepends=()
makedepends=('cmake' 'git')
provides=(stp)
conflicts=(stp)
md5sums=()

_gitroot="https://github.com/stp/stp"
_gitname=stp

build() {
  cd ${srcdir}

  msg "Connecting to GIT server...."

  if [ -d ${_gitname} ]; then
    cd ${_gitname} && git pull origin || return 1
    msg "The local files are updated."
  else
    git clone ${_gitroot} || return 1
  fi

  msg "GIT checkout done or server timeout"
  msg "Starting make..."

  rm -rf ${srcdir}/build || return 1
  git clone ${srcdir}/${_gitname} ${srcdir}/build || return 1
  cd ${srcdir}/build || return 1

  cmake CMakeLists.txt -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr || return 1
  make DESTDIR=${pkgdir} || return 1
}

package() {
  cd ${srcdir}/build || return 1
  make DESTDIR=${pkgdir} install || return 1
}
