#! /bin/bash
# Copyright (c) 2004, Jukka Lehtomaki <jukka.lehtomaki@gmail.com>
rufus=${HOME}/.Rufus
rufusfolder=${HOME}/Rufus
torrents=${HOME}/Rufus/torrents
download_dir=${HOME}/Rufus/incoming
completed_dl_dir=${HOME}/Rufus/incoming/completed
completed_tor_dir=${HOME}/Rufus/torrents/completed
if [ ! -e ${rufus} ] ; then
        mkdir ${rufus}
        echo "Creating ${rufus}"
fi
if [ ! -e ${rufusfolder} ] ; then
        mkdir ${rufusfolder}
        mkdir ${torrents}
        mkdir ${download_dir}
        mkdir ${completed_dl_dir}
        mkdir ${completed_tor_dir}
        echo "Creating ${rufusfolder}"
 fi
cd ${rufus}
python -OO /usr/lib/python2.4/site-packages/rufus/rufus.py
