#!/bin/bash

if [ -e "$1" ]; then
	ls=$(udevadm info --query property --name "$1")
	vendor=$(echo "$ls" | grep 'ID_VENDOR_ID=' | sed 's/ID_VENDOR_ID=//g')
	model=$(echo "$ls" | grep 'ID_MODEL_ID=' | sed 's/ID_MODEL_ID=//g')
	lsusb | grep "$vendor:$model " | sed "s/.*$vendor:$model //g" | sed 's/\//|/g'
else
	echo "$1"
fi
