#!/bin/bash

if [ -e "$1" ]; then
	ls=$(udevadm info --query property --name "$1")
	vendor=$(echo "$ls" | grep 'ID_VENDOR_ID=' | sed 's/ID_VENDOR_ID=//g')
	model=$(echo "$ls" | grep 'ID_MODEL_ID=' | sed 's/ID_MODEL_ID=//g')
	part=$(echo "$1" | sed 's/.*-part//g' | sed 's/\/.*//g')
	dt=$(echo "$1" | sed 's/-part.*//g' | sed 's/.*-//g')
	dev=$(lsusb | grep "$vendor:$model " | sed "s/.*$vendor:$model //g" | sed 's/\//|/g')
	if [ "$part" ]; then
		echo "$dev.$dt.$part"
	else
		echo "$dev.$dt"
	fi
else
	echo "$1"
fi
