vimdocinstall() {
	echo -n "updating Vim help tags... "
	_version_vimruntime=$(pacman -Q vim-runtime | awk \
	'{$0=gensub(/^[^0-9]*([0-9])\.([0-9]).*/,"\\1\\2","1");print }')
	/usr/bin/vim --noplugin -u NONE -U NONE \
		--cmd ":helptags /usr/share/vim/vim${_version_vimruntime}/doc" --cmd ":q" > /dev/null 2>&1
	echo "done."
}

post_install() {
	vimdocinstall
}

post_upgrade() {
	vimdocinstall
}

post_remove() {
	vimdocinstall
}

op=$1
shift

$op $*
