--- Makefile	2007-10-10 14:19:58.000000000 -0500
+++ Makefile-new	2011-03-26 00:00:30.063334475 -0500
@@ -18,6 +18,8 @@
 
 APPS = atlast primdeftest
 
+DESTDIR=
+
 all:	$(APPS)
 
 atlast: $(ATLOBJ)
@@ -67,3 +69,12 @@
 
 lintatlast:
 	lint atlast.c atlmain.c $(LIBRARIES) $(ATLCONFIG)
+install:	
+	install -Dm755 atlast $(DESTDIR)/usr/bin/atlast
+	install -Dm644 atlast.pdf $(DESTDIR)/usr/share/atlast/atlast.pdf
+	install -Dm644 atlast.html $(DESTDIR)/usr/share/atlast/atlast.html
+	install -Dm644 log.txt $(DESTDIR)/usr/share/atlast/log.txt
+	install -Dm755 primdeftest $(DESTDIR)/usr/bin/primdeftest
+	install -Dm644 regout.txt $(DESTDIR)/usr/share/atlast/regout.txt
+	install -Dm644 regress.atl $(DESTDIR)/usr/share/atlast/regress.atl
+	cp -R tex/* $(DESTDIR)/usr/share/atlast/
