post_install() {
    _ruby_version=$(ruby --version | awk '{print $2}')
    echo ""
    echo "Your current ruby version is: $_ruby_version"
    echo ""
    echo "IMPORTANT NOTE: metasploit currently does NOT work with ruby >= 2"
    echo "If you experience problems running metasploit, please downgrade ruby to 1.9.x"
    echo "OR use e.g. RVM and install ruby 1.9.x"
    echo ""
    echo "If you want to use rvm, you can follow the Guide at: "
    echo "  http://git.io/tG90Bg (Getting Ruby)"
    echo "to install RVM."
    echo ""
    echo "To install the dependencies for metasploit, change to '/usr/src/metasploit-git/'"
    echo "as your user for which rvm was installed (it could be root) and run 'gem install bundler && bundle install'"
    echo ""
    echo "To use postgresql with metasploit, follow the instructions on both of these pages:"
    echo "https://wiki.archlinux.org/index.php/Postgresql"
    echo "https://fedoraproject.org/wiki/Metasploit_Postgres_Setup"
    echo ""
    echo "Now you can run 'msfconsole' to start metasploit."
    echo ""
}

post_upgrade() {
    post_install
}
