post_install() {
    _ruby_version=$(ruby --version | awk '{print $2}')
    echo ""
    echo "NOTICE: metasploit-git now resides in /usr/local/src with msf* symlinked to /usr/local/bin"
    echo ""
    echo "Your current ruby version is: $_ruby_version"
    echo ""
    echo "IMPORTANT NOTE: metasploit currently does NOT work with ruby >= 2"
    echo "  If you need multiple version of Ruby, use RVM: http://git.io/tG90Bg or try 'rbenv' from the AUR"
    echo ""
    echo "Now, install your bundle: '$ cd /usr/src/metasploit-git/ ; sudo gem install bundler && sudo bundle install'"
    echo "  (it will complain about sudo breaking your system: this will *not* happen)."
    echo "If you wish to install your bundle as another user who has permissions to write to /opt/ruby1.9, then run:"
    echo "  '$ sudo -u <user> gem install bundler && sudo -u <user> bundle install' or simply install as yourself."
    echo ""
    echo "To use postgresql with metasploit, follow the instructions on both of these pages:"
    echo "  https://wiki.archlinux.org/index.php/Postgresql"
    echo "  https://fedoraproject.org/wiki/Metasploit_Postgres_Setup"
    echo ""
    echo "Now you can run '$ msfconsole' to start metasploit."
    echo ""
}

post_upgrade() {
    post_install
}
