# I copied /var/abs/extra/emacs/emacs.install and used my own value for 
# info_files.

info_dir=/usr/share/info
info_files=('festival-freebsoft-utils.info')

post_install() {
  for f in ${info_files[@]}; do
    install-info ${info_dir}/$f.gz ${info_dir}/dir 2> /dev/null
  done
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  for f in ${info_files[@]}; do
    install-info --delete ${info_dir}/$f.gz ${info_dir}/dir 2> /dev/null
  done
}

op=$1
shift
$op $*
