#!/bin/bash

daemon_name=target

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
	start)
		stat_busy "Starting lio targets"
    /usr/bin/targetcli restoreconfig clear_existing=true
		if [[ $? -gt 0 ]]; then
			stat_fail
			exit 1
		else
      add_daemon $daemon_name
			stat_done
		fi
		;;

	stop)
		stat_busy "Stopping lio targets"
    /usr/bin/targetcli clearconfig confirm=true
		if [[ $? -gt 0 ]]; then
			stat_fail
			exit 1
		else
      rm_daemon $daemon_name
			stat_done
		fi
		;;

	restart)
		$0 stop
		sleep 3
		$0 start
		;;

	status)
		stat_busy "Checking status of lio targets";
    ck_status $daemon_name
    ck_daemon $daemon_name || /usr/bin/targetcli ls
		;;

	*)
		echo "usage: $0 {start|stop|restart|status}"
esac

exit 0

# vim:set ts=2 sw=2 et:
