KERNEL_VERSION=2.6.28-ARCH

post_install() {
  depmod -v $KERNEL_VERSION &> /dev/null
  modprobe ctxfi &> /dev/null
  echo "==> To use this software, you must accept the Creative EULA:"
  echo "  -> /usr/share/licenses/ctxfi/CEULA"
  echo "==> Add 'ctxfi' to the MODULES array of /etc/rc.conf"
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  modprobe -r ctxfi &> /dev/null
}

post_remove() {
  depmod -v $KERNEL_VERSION &> /dev/null
}
