post_install() {
   echo "==> rabbit: rabbit binds by default to all IPs!"
   echo "==> rabbit: so use firewall to deny remote access"
   echo "==> rabbit: and change admin password in /etc/rabbit/users"
   groupadd -g 77 rabbit &>/dev/null
   useradd -u 77 -g rabbit -d /var/lib/rabbit -s /bin/false rabbit &>/dev/null
   chown rabbit:rabbit -R /etc/rabbit /var/{cache/rabbit,log/rabbit}
}

pre_remove() {
   userdel rabbit &>/dev/null
}
