post_install()
{
  # setup x2godesktopsharing group
  if ! getent group x2godesktopshare >/dev/null; then
    groupadd -K GID_MIN=500 -K GID_MAX=999 x2godesktopshare
    echo "  ==> Group x2godesktopshare created."
    echo "      Run 'gpasswd -a $USER' to add users allowed to share their"
    echo "      desktop to this group."
  else
    echo "  ==> Group x2godesktopshare already exists."
  fi
}

post_upgrade()
{
  post_install
}
