#!/bin/bash

if [ ! -d "$HOME"/.ollydbg ] ; then
	mkdir -p "$HOME"/.ollydbg/wine || exit 1
	ln -s /usr/share/ollydbg/ollydbg.exe "$HOME"/.ollydbg/ollydbg.exe || exit 1
	ln -s /usr/share/ollydbg/dbghelp.dll "$HOME"/.ollydbg/dbghelp.dll || exit 1
fi

wine "$HOME"/.ollydbg/ollydbg.exe "$@"

