pre_upgrade()
{
	systemctl stop archipel-agent && (
		touch '/tmp/archipel-was-started'
		echo 'Archipel agent has been stopped.'
	)
}

post_install()
{
	cat <<- EOF
		==> Initialize Archipel Agent config and data files by running:
		# archipel-initinstall
		==> Start Archipel using systemd:
		# systemctl start archipel	
		==> Auto-start Archipel on boot:
		# systemctl enable archipel
	EOF
}

post_upgrade()
{
	systemctl --system daemon-reload
	if [ -f '/tmp/archipel-was-started' ]; then
		rm '/tmp/archipel-was-started'
		systemctl start archipel-agent
		echo 'Archipel agent has been started.'
	fi
}

post_remove()
{
	cat <<- EOF
		==> You may safely delete Archipel Agent config and files:
		# rm -rf /etc/archipel /var/lib/archipel
	EOF
}
