post_install() {
  echo -e "\
1. Add to your .bashrc\n\
\texport GTK_MODULES=golbalmenu-gnome\n\
2. Add to Autostart\n\
\t'globalmenu'\n\
\t'globalmenu-settings show-local-menu FALSE' if you want to hide menus in applications\n\
3. If neccessary, do as root\n\
\t$ cd /usr/lib/gtk-2.0/modules
\t$ ln -s libglobalmenu-plugin.so libglobalmenu-gnome.so\n"
}

post_upgrade() {
if [ -n "$(ps -e | grep globalmenu)" ]
then
echo "restarting globalmenu executable...\n"
killall globalmenu && sleep 2 && /usr/bin/globalmenu
fi
post_install
}

post_remove() {
  echo -e "\
1. Don't forget to clean up your .bashrc\n\
\texport GTK_MODULES=golbalmenu-gnome\n\
2. Clean up Autostart entries\n\
\t'globalmenu'\n\
\t'globalmenu-settings show-local-menu FALSE'\n"
}

# vim:set ts=2 sw=2 et:
