pkgname=ownCloud

post_install() {
       echo "Add line into ahache conf file:"
       echo "Include /etc/httpd/conf/extra/owncloud.conf"
	   echo "LoadModule php5_module modules/libphp5.so"
	   echo "Include conf/extra/php5_module.conf"
	   echo
	   echo "Replace line into /etc/php/php.ini"
	   echo "open_basedir = /srv/http/:/home/:/tmp/:/usr/share/pear/"
	   echo "by"
	   echo "open_basedir = /srv/http/:/home/:/tmp/:/usr/share/pear/:/opt/html/owncloud/"
}
