pkgname=ownCloud

post_install() {
       echo "Add line into ahache conf file:"
       echo "Include conf/extra/owncloud.conf"
	   echo "LoadModule php5_module modules/libphp5.so"
	   echo "Include conf/extra/php5_module.conf"
	   echo
	   echo "Uncomment extensions: 
	   echo "    zip.so, gd.so, iconv.so, xmlrpc.so, pdo_mysql.so, mysql.so, openssl.so"
	   echo "in /etc/php/php.ini"
	   echo "Add extension curl.so in /etc/php/php.ini if you use it"
	   echo
}

post_upgrade()
{
post_install
}
