post_upgrade() {
  _NEWVERSION=`echo $1 | cut -f-1 -d '-'`
  _OLDVERSION=`echo $2 | cut -f-1 -d '-'`
  
  olfifs=$IFS
  IFS=$'\n'
  for line in `cat /usr/share/doc/pyimc/CHANGELOG`
  do
    if [[ $line == *$_OLDVERSION*  ]]
    then
      IFS=$oldifs
      exit 0
    fi
    if [[ $line == *pyimc-* || $line == *Bugs* || $line == *Features* || $line == *Enhancements* ]]
    then
      echo ""
    fi
    echo $line
  done 
  IFS=$oldifs
} 

