post_install() {
	echo "=> A preview image and an installation script have been installed to:"
	echo "=>  /usr/share/opengeu-themes/"
	echo "=> The install-script works partially (configures GTK2) if you have"
	echo "=> got e17-settings-daemon running. It does not set up the E17 theme"
	echo "=> and splash for you, because the install script is not compatible"
	echo "=> with a recent copy of enlightenment_remote, so you must do that manually."
}
