pre_install() {
  echo "The Silkscreen font is licensed under CC Attribution-ShareAlike 2.0."
  echo "License terms can be reviewed at:" 
  echo "http://creativecommons.org/licenses/by-sa/2.0/"
}

# arg 1:  the new package version
post_install() {
  echo -n "Updating font cache... "
  fc-cache /usr/share/fonts/TTF
  mkfontscale /usr/share/fonts/TTF
  mkfontdir /usr/share/fonts/TTF
  echo "done."
}

post_upgrade() {
  post_install $1
}

post_remove() {
  post_install $1
}

op=$1
shift
$op $*
