post_install() {
  if [ ${LANG:0:2} == "fr" ]; then
    _NAME="Pages du manuel"
    _DESC="Naviguer dans les pages du manuel Linux"
  else
    _NAME="Manuel pages"
    _DESC="Navigate through the Linux manual pages"
  fi
  sed -i -- "s/Name=manPagesGui/Name=$_NAME/g" /usr/share/applications/manpagesgui.desktop
  sed -i -- "s/Comment=/Comment=$_DESC/g" /usr/share/applications/manpagesgui.desktop
  mandb --quiet
}

post_upgrade() {
  post_install $1
}
