post_install() {
    /usr/bin/getent group lrun >/dev/null 2>&1 ||  usr/sbin/groupadd -g 593 lrun &>/dev/null

    echo "NOTE: To run lrun as normal user you have to add yourself into lrun group"
}

post_upgrade() {
    /usr/bin/getent group lrun >/dev/null 2>&1 ||  usr/sbin/groupadd -g 593 lrun &>/dev/null
}

post_remove() {
    if /usr/bin/getent group lrun >/dev/null 2>&1; then
        /usr/sbin/groupdel lrun
    fi
}
