infodir=/usr/share/info
filelist=(jabber.info.gz)

post_install() {
  for file in ${filelist[@]}; do
    install-info $infodir/$file $infodir/dir 2> /dev/null
  done
  echo "Please add the following line to your .emacs." 
  echo "(require 'jabber)"
}

post_upgrade() {
  post_install 
}

pre_remove() {
  for file in ${filelist[@]}; do
    install-info --delete $infodir/$file $infodir/dir 2> /dev/null
  done
}
