all_off="$(tput sgr0)"
bold="${all_off}$(tput bold)"
yellow="${bold}$(tput setaf 3)"
blue="${bold}$(tput setaf 4)"
green="${bold}$(tput setaf 2)"

_instructions() {
  printf "${yellow}==>${all_off} ${bold}ATENTION:${all_off}
${green}==>${all_off} ${bold}To disable all other flash plugins:${all_off}
  ${blue}->${all_off} Type '${bold}chrome://plugins/${all_off}' in the adress bar and press Enter
  ${blue}->${all_off} Click on '${bold}Details${all_off}' button on the top right.
  ${blue}->${all_off} Click on '${bold}Disable${all_off}' near all the Flash plugins except the first one.\n"
}

pre_install() {
    if [[ -f '/etc/chromium-browser/default' ]]; then
    sed 's| --ppapi-flash-path=/usr/lib/PepperFlash/libpepflashplayer.so --ppapi-flash-version=1.*[0-999]||' -i '/etc/chromium-browser/default'
  fi
  if [[ -f '/etc/chromium-dev/default' ]]; then
    sed 's| --ppapi-flash-path=/usr/lib/PepperFlash/libpepflashplayer.so --ppapi-flash-version=1.*[0-999]||' -i '/etc/chromium/default'
  fi
  if [[ -f '/etc/chromium-dev/default' ]]; then
    sed 's| --ppapi-flash-path=/usr/lib/PepperFlash/libpepflashplayer.so --ppapi-flash-version=1.*[0-999]||' -i '/etc/chromium-dev/default'
  fi
  if [[ -f '/etc/iron/default' ]]; then
    sed 's| --ppapi-flash-path=/usr/lib/PepperFlash/libpepflashplayer.so --ppapi-flash-version=1.*[0-999]||' -i '/etc/iron/default'
  fi
  true
}

post_install() {
  _instructions
}

pre_upgrade() {
  pre_install $2
  _instructions
}
