pkgname=chrontel-wetab-rpm

post_install() {
	echo; echo '#############################'
	echo 'To start the hdmi-daemon, do:'
	echo '    modprobe i2c-dev'
	echo '    mv /dev/i2c-0 /dev/i2c-2 # very dirty hack'
	echo '    tiitoo-hdmi-daemon'
	echo 'This needs to be executed every single time the system starts. -.-'
	echo 'For more information visit https://wiki.archlinux.org/index.php/WeTab'
}


post_upgrade() {
  post_install $1
}
