--- src/pigment/pigment/pgm/Makefile.am	2010-01-01 16:10:11.000000000 +0100
+++ Makefile.am	2010-01-01 16:09:16.000000000 +0100
@@ -33,8 +33,7 @@ source_h = \
 	$(srcdir)/pgmlinearalgebra.h \
 	$(srcdir)/pgmimagesink.h \
 	$(srcdir)/pgmmodule.h \
-	$(srcdir)/pgmkeysyms.h \
-	pgmenumtypes.h
+	$(srcdir)/pgmkeysyms.h
 
 pgmincludedir = $(includedir)/pigment-@PGM_MAJORMINOR@/pgm
 pgminclude_HEADERS = $(source_h)
