update-icon(){
	xdg-icon-resource forceupdate --theme hicolor &>/dev/null
    update-desktop-database -q
}

remove_slink(){
	# in previous version install script created symbolic links
	[[ -s /usr/local/bin/genymotion ]] && rm /usr/local/bin/genymotion
	[[ -s /usr/local/bin/genymotion-shell ]] && rm /usr/local/bin/genymotion-shell
}

post_install() {
	update-icon
}

post_upgrade() {
	remove_slink
    update-icon
}

post_remove() {
	remove_slink
    update-icon
}

