post_install() {
  gtk-update-icon-cache -q -f -t /usr/share/icons/hicolor
  update-desktop-database -q
  echo ">>> You can find examples and other useful data in"
  echo ">>> '/usr/share/java/modellus/Modellus files'"
}

post_upgrade() {
  gtk-update-icon-cache -q -f -t /usr/share/icons/hicolor
  update-desktop-database -q
}

post_remove() {
  gtk-update-icon-cache -q -f -t /usr/share/icons/hicolor
  update-desktop-database -q
}

