post_install() {
   # Generate a machine number (if there isn't one already)
   if [ ! -f /usr/share/lightworks/machine.num ];
   then
	echo "Generating machine number..."
	echo $((`cat /dev/urandom|od -N1 -An -i` % 2500)) >> /usr/share/lightworks/machine.num
   else
	echo "Using machine number of previous installation."
   fi

   echo "Visit http://www.lwks.com/betas-linux for the latest beta."
}

post_upgrade() {
	post_install
}
