--- Makefile	2013-01-26 12:55:27.000000000 +0100
+++ Makefile.new	2013-03-31 20:33:37.006295481 +0200
@@ -1,8 +1,7 @@
-PREFIX ?= /usr/local
+PREFIX ?= /usr
 bindir ?= $(PREFIX)/bin
 libdir ?= $(PREFIX)/lib
 
-
 # These two commands are used by me, since most of the source files are stored in the Radium tree.
 # You would normally just run "make" to compile the program.
 #
@@ -10,7 +9,7 @@
 # make copy_files && rm -f benchmark && make benchmark && ./benchmark && ./benchmark && ./benchmark
 
 
-CPP = g++ -DDEBUG -O3 -Wall -msse -mfpmath=sse -DUSE_QT_REQTYPE -DUSE_QT4 -g -I. -ffast-math -IQt
+CPP = g++ -O3 -Wall -msse -mfpmath=sse -DUSE_QT_REQTYPE -DUSE_QT4 -I. -ffast-math -IQt -DDEBUG $(CXXFLAGS)
 
 #FAUST = /home/kjetil/faudiostream/compiler/faust -vec
 FAUST = faust -vec
