## arg 1:  the new package version
post_install() {
    echo "Running the official install script provided by Brother"
    /usr/local/Brother/Printer/dcp9270cdn/cupswrapper/cupswrapperdcp9270cdn

    echo -e "\e[32mOpen Cups on http://localhost:631 and add the printer!\e[39m"
    echo -e "\e[32mFor network printing add the printer with ipp://IPADDRESS/ipp/port1\e[39m"
    echo -e "\e[32mwhere IPADDRESS is the network ip address of your Brother!\e[39m"
}

