--- gnome-clock-screensaver-1.0.0/Makefile	2010-01-17 13:29:49.000000000 +0200
+++ Makefile	2010-05-22 00:18:54.896775398 +0300
@@ -20,5 +20,5 @@
 clean:
 	rm -f $(OBJECTS) $(TARGET) core* *.o *~
 install:
-	${INSTALL} -s -m 0755 ${TARGET}  ${GS_LIBEXEC_DIR}
-	${INSTALL}    -m 0644 ${DESKTOP} ${GS_DESKTOP_DIR}
+	${INSTALL} -m755 ${TARGET}  ${DESTDIR}${GS_LIBEXEC_DIR}
+	${INSTALL} -m644 ${DESKTOP} ${DESTDIR}${GS_DESKTOP_DIR}
