#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/ziproxy

PID=`pidof -o %PPID /usr/bin/ziproxy`
case "$1" in
  start)
    stat_busy "Starting Ziproxy"
    [ -z "$PID" ] && /usr/bin/ziproxy -d $ZIPROXY_ARGS >/var/run/ziproxy.pid
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon ziproxy
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Ziproxy"
    [ ! -z "$PID" ] && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon ziproxy
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0

