.TH mycron 1 "2013-01-13" 2.0.1
.SH NAME
mycron - A standards compliant and convenient crontab management system.

.SH SYNOPSIS
.B mycron
.RB [\| -h \|]
.RB [\| \-u
.IR C \|]
.RB [\| -e \|]
.RB [\| -l \|]
.RB [\| -s \|]
.RB [\| -c \|]
.RB [\| -n \|]
.RB [\| -p \|]
.RB [\| -x \|]

.SH DESCRIPTION
mycron is not a cron service/daemon. You need an already set up cron service for using mycron in a reasonable way. You need to set up your cronie\-, dcron\-, vixie\-, whatever\-crontab to execute mycron every minute for taking full advantage of mycron’s crontabs.
.PP
mycron then replaces your regular crontab setup. It allows you to set up cronjobs in a completely new, but very convenient and standards compliant way and becomes your command center for managing, creating, editing and checking (multiple) crontabs.

.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
show inline parameters help
.TP
\fB\-u\fR \fIC\fR, \fB\-\-use\fR=\fIC\fR
use crontab \fIC\fR instead of default crontab. You can combine this with all other parameters.
.TP
\fB\-e\fR, \fB\-\-edit\fR
edit crontab (either the default crontab or the one specified by \fB\-u\fR)
.TP
\fB\-s\fR, \fB\-\-show\fR
output a list showing all available crontabs, except x\- crontabs (see \fB\-x\fR for more details)
.TP
\fB\-c\fR, \fB\-\-check\fR
check the crontab for validity and show all lines that are invalid
.TP
\fB\-n\fR, \fB\-\-no\-colors\fR
don't use colored output
.TP
\fB\-e\fR, \fB\-\-print\-examples\fR
show a list of examples for mycron crontab entries
.TP
\fB\-x\fR, \fB\-\-x\-crontabs\fR
show development crontabs, too. Development crontabs start with \fBx-\fR and are hidden by default when using \fB-s\fR.

.SH BUGS
Please desist from using non-ASCII characters like German umlauts, other special symbols, etc. It will not break mycron or it's validity check, but fails on mycron actually executed by your cron daemon.

.SH FULL DOCUMENTATION
The full documentation of \fBmycron\fR is available online at <http://dev.0x7be.de/mycron.html>. In case of differences the documentation available online is to be looked upon as the more current version.

.SH AUTHOR
Dirk Sohler, <spam@0x7be.de>

.SH SEE ALSO
mycron(5), crontab(1)
