update_databases() {
  xdg-icon-resource forceupdate --theme hicolor &> /dev/null
}

post_install() {
  # Add socketsentry group, GID 172 (reservation pending ;-) - http://wiki.archlinux.org/index.php/UID_and_GID_list)
  getent group socketsentry &> /dev/null || groupadd -f -g 172 socketsentry

  update_databases
  
  cat <<EOF

==> Remember to add allowed users to the socketsentry group:
==> # gpasswd -a USERNAME socketsentry
EOF
}

post_upgrade() {
  update_databases
}

post_remove() {
  update_databases

  # remove socketsentry group
  groupdel socketsentry &>/dev/null || true
}

# vim:set ts=2 sw=2 ft=sh et:
