#!/usr/bin/env bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
    start)
        stat_busy "Starting pvpgn"
        sudo -u pvpgn /usr/sbin/bnetd
        sleep 1
        pgrep bnetd > /dev/null
        if [ $? -gt 0 ]; then
            stat_fail
        else
            stat_done
            add_daemon pvpgn
        fi
        ;;
    stop)
        stat_busy "Stopping pvpgn"
        PID=$(pidof /usr/sbin/bnetd)
        kill $PID > /dev/null
        if [ $? -gt 0 ]; then
            stat_fail
        else
            rm_daemon pvpgn
            stat_done
        fi
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
