.TH DUMPRTP 1 "29 July 2002" "Linux" "Debian"

.SH NAME
dumprtp \- get an RTP unicast/multicast/broadcast stream and output it

.SH SYNOPSIS
.B ts_filter [\fIip_addr port\fR]

.SH DESCRIPTION
.B dumprtp
fetches a unicast,broadcast or multicast stream from an IP address 
and outputs it to stdout. It may be used with \fBdvbstream\fR to broadcast,
for example, DVB video and audio over a LAN.
.PP
With no arguments, \fBdumprtp\fR outputs from multicast address \fI224.0.1.2\fR,
port \fI5004\fR by default (this is the default used by \fBdvbstream\fR.
To change this, give the address and the port number on  the command line.


.SH SEE ALSO
.BR mpegtools(1)
and
.BR dvbstream(1).

.SH AUTHORS
.B dumprtp
was written by  David Podeur (<david@convergence.de>) for Convergence integrated media GmbH
and is made available under the GNU Public License.
.PP
This man page was written by Alastair McKinstry, <mckinstry@computer.org>.

