.TH DVBSTREAM "1" "4 March 2005" "Linux" "Debian"
.SH NAME
dvbstream \- Transmit a DVB transport stream via RTP
.SH SYNOPSIS
.B dvbstream [\fI \-f freq\fR] [\fI \-p v\|h\fR] [\fI \-s symbolrate\fR]
[\fI \-c cardnum\fR] [\fI \-o \fR] [\fI \-ps \fR]
[\fI \-i ipaddr \fR] [\fI \-r port\fR]
[\fI\-a apid\fR] [\fI\ -v vpid\fR] p\fI \-t ttpid\fR] [\fI\-n secs \fR] [\fI pid1 ... \fR]


.SH DESCRIPTION
.B dvbstream
takes a TS (transport stream) from A DVB (Digital Video Broadcast, either
DVB-S for satellite cards, DVB-C for cable, or DVB-T for terrestrial) and
broadcasts (a subset of) it over a LAN using the RTP protocol.
.TP
Some options are not available on Budget DVB cards.
.SH OPTIONS
.TP
\fB\-f\fR
The Frequency to tune into, in MHz.
.TP
\fB\-p\fR, \fI v|h\fR
The polarisation; either \fIh\fR (horizontal) or \fIv\fR (vertical).
.TP
\fB\-s\fR \fIsymbolrate\fR
The symbol rate of the DVB stream, typically 27500.
.TP
\fB\-c\fR \fIcardnum\fR
Select which DVB card to use. The \fIcardnum\fR must be between 0 and 3.
.TP
\fB\-a\fR \fIapid\fR
Select which audio PID to output on the TV-OUT of the DVB card (Full cards only).
.TP
\fB\-v\fR \fIvpid\fR
Select which video PID to output on the TV-OUT of the DVB card (Full cards only).
.TP
.TP
\fB\-t\fR \fIttpid\fR
Select which Teletext PID to output on the TV-OUT of the DVB card (Full cards only).
\fB\-n\fR \fIsecs\fR
Timeout and shut down after \fIsecs\fR seconds.
.TP
.TP
\fB\-ps\fR
Output a PS rather than a (default) PES stream.
.TP
\fB\-o\fR
Output to stdout rather than broadcast.
.TP
\fB\-i ipaddr\fR
IP Multicast port to output to (default is 224.0.1.2)
.TP
\fB\-r port\fR
IP multicast port to outpu to (default is 5004).

.SH SERVER USAGE

If you wanted to broadcast TVC International from Astra 19E, you would
type the following command:
.sp
dvbstream -f 12441 -p v -s 27500 512 660
.sp
You can specify up to 8 PIDs on the command-line to include in the
multicasted transport stream.  A 10MBit/s network should be able to
handle one video and one audio stream, or eight audio streams.
.PP
If you also want to view the TV channel on the TV-OUT of your DVB-S
card (or using xawtv or similar), then you can use the "-v" and "-a"
flags before the video and audio PIDs respectively:
.sp
dvbstream -f 12441 -p v -s 27500 -v 512 -a 660
.sp
dvbstream also has the ability to map PIDS to different values before
you stream it.  For example, if you type 
.sp
dvbstream -f 12441 -p v -s 27500 -v 512:1 -a 660:2
.sp
then the video stream will become "PID 1" and the audio stream will
become "PID 2".
.PP
Also, with driver versions from October 2001 onwards, you can
broadcast the entire transport stream (if you are using a budget card)
with the command:
.sp
dvbstream 8192
.sp
8192 is a "dummy PID" (legal PIDS are in the range 0-8191) and the
driver interprets this to mean the entire TS.  Obviously, it would
make no sense to use the map feature on this "pid".

.SH CLIENT USAGE

To receive the stream on any other machine on your LAN, use the
dumprtp utility (from ts-rtp).  An slightly improved version is
included in this archive. e.g.
.sp
dumprtp > received.ts
.sp
If you have a DVB card on the second machine, you can use the rtpfeed
command to decode the stream.  Type "rtpfeed -h" for usage
information.  rtpfeed was written by Guenter Wildmann
<a8909020@unet.univie.ac.at> - please address any bugs or comments to
Guenter.
.PP
If you don't have a DVB card on the client machine, You can use mpg123
and the mpegtools provided with the DVB driver for live audio
decoding:
.sh
dumprtp | ts2es apid | mpg123 -
.sh
This command line is included with dvbstream as the "rtpradio.sh" script.
.PP
If you only want audio, you can run dvbstream with eight audio PIDs,
and then your clients can choose which PID to play.
.PP
For live TV channel playing, the best solution I have found is mplayer
(http://www.mplayerhq.hu).  Please install the latest CVS version -
mplayer is being rapidly improved.
.PP
You can then view TV being streamed over the network using the
following command:
.sp
dumprtp | ts2ps vpid apid | mplayer -cache 2048 -
.sp
This command line is included with dvbstream as the "rtptv.sh" script.

.SH MPLAYER "RTP-PS" SUPPORT

The file "mplayer-libmpdemux-network.c.patch" contains a patch for the
current (31 Jan 2001) CVS version of mplayer to "enable" the
experimental RTP support.  To apply it, check out a fresh copy of
mplayer using and change into the "main/libmpdemux" directory.
.PP
Then apply the command:
.sp
patch < /path_to/dvbstream-0.4pre2/mplayer-libmpdemux-network.c.patch
.sp
You can then build mplayer as normal.  To receive a RTP stream
broadcast with dvbstream's "-ps" option, you just need to type the
following command on the client machine:
.sp
mplayer rtp://224.0.1.2:5004/ -cache 2048
.sp

.SH TELNET INTERFACE

From v0.4 onwards, DVBstream incorporates a "telnet" interface to
allow you to remotely start and stop the streaming, and tune the card
to a different channel.
.PP
The following commands are supported:
.PP
.sp
TUNE freq pol srate
STOP
ADDV pid[:map]
ADDA pid[:map]
ADDT pid[:map]
ADD pid[:map]
QUIT
.sp

.I STOP 
closes down all PIDs and stops the streaming.  The other commands
should be self-explanatory.  See the scripts in the TELNET directory
for example usage.
x
.SH HISTORY 
.B dvbstream
fixes a number of bugs that were present in the original
.B ts-rtp
application.

.SH "SEE ALSO"
.BR rtpfeed (1),
.BR dumprtp (1),
and
.BR ts2es (1)
 
.SH AUTHORS
.B dvbstream
was written by  Dave Chapman <dave@dchapman.com> 2001, 2002.
and is made available under the GNU Public License.
.PP
This man page was written by Alastair McKinstry, <mckinstry@computer.org>.

