.TH TS_FILTER 1 "29 July 2002" "Linux" "Debian"

.SH NAME
ts_filter \- extract a single stream from a multiplexed TS

.SH SYNOPSIS
.B ts_filter <\fIpid\fR>

.SH DESCRIPTION
.B ts_filter
is a simple filter to extract a single MPEG stream from a multiplexed
MPEG Transport stream. It may be used with \fBdvbstream\fR
and other MPEG programs to extract a single stream for display.
.PP
.B ts_filter
takes the PID of the stream to extract on the command line, and filters the
standard input, outputting to standard output.

.SH SEE ALSO
.BR mpegtools(1),
and
.BR dvbstream(1).

.SH AUTHORS
.B dvbstream
was written by  Dave Chapman <dave@dchapman.com> 2001, 2002.
and is made available under the GNU Public License.
.PP
This man page was written by Alastair McKinstry, <mckinstry@computer.org>.

