post_install() {

      echo "After installing/updating Telegram you must run these two commands to the terminal:"
      echo "$ sudo chmod 777 /usr/bin/telegram"
      echo "$ telegram"
#     echo "Before, delete the old: rm -r ~/.local/share/applications/telegramdesktop.desktop. And rm -r ~/.TelegramDesktop"
      
}

post_remove()
{
      echo "Remove the .desktop: rm -r ~/.local/share/applications/telegramdesktop.desktop. And rm -r ~/.TelegramDesktop"
}

# vim: ts=2 sw=2 et:
