post_install() {
 cat << EOF
> This package sets the default paper format to A4 borderless
> Feel free to change this by using the /usr/bin/brprintconfij2 command
EOF
/usr/bin/brprintconfij2 -P FAX1940CN -pt A4_B || echo True
}

post_upgrade() {
 cat << EOF
> This package sets the default paper format to A4 borderless
> Feel free to change this by using the /usr/bin/brprintconfij2 command
EOF
/usr/bin/brprintconfij2 -P FAX1940CN -pt A4_B || echo True
}

op=$1
shift
$op $*
