msg()
{
  echo "read installation tips on /usr/share/doc/grub4dos/README_arch.txt"
}


## arg 1:  the new package version
post_install()
{
  msg
}


## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade()
{
  msg
}


## arg 1:  the old package version
post_remove()
{
  echo "To really remove sample:"
  echo "1. restore original mbr"
  echo "2. rm /grldr"
}

# vim:set ts=2 sw=2 et:
