--- Makefile	2003-05-04 23:42:09.000000000 +0000
+++ Makefile	2007-10-03 14:02:52.000000000 +0000
@@ -14,11 +14,11 @@
 SHELL		=	/bin/sh
 PERL		=	/usr/bin/perl
 SRCDIR		=	.
-INSTALL		=	/usr/bin/install
+INSTALL		=	/bin/install
 INSTALL_FILE	=	${INSTALL} -m 644 -o root -g root
 INSTALL_PERL	=	${INSTALL} -m 755 -o root -g root
 UNINSTALL	=	/bin/rm -f
-prefix		=	/usr/local
+prefix		=	/usr
 bindir		=	${prefix}/bin
 mandir		=	${prefix}/man
 bashdir		=	/etc/bash_completion.d
@@ -46,11 +46,17 @@
 	${PERL} -MCPAN -e 'install AppConfig'
 
 
-check:
+makedirs:
+	@echo -e "\n** Creating directories, if necessary\n"
+	@if [ ! -d ${DESTDIR}${bindir} ]; then mkdir -p ${DESTDIR}${bindir} || (echo Can\'t create ${DESTDIR}${bindir}, exiting; exit 1); fi
+	@if [ ! -d ${DESTDIR}${mandir}/man1 ]; then mkdir -p ${DESTDIR}${mandir}/man1 || (echo Can\'t create ${DESTDIR}${mandir}/man1, exiting; exit 1); fi
+	@if [ ! -d ${DESTDIR}${bashdir} ]; then mkdir -p ${DESTDIR}${bashdir} || (echo Can\'t create ${DESTDIR}${bashdir}, exiting; exit 1); fi
+
+check: makedirs
 	@echo -e "\n** Environment sanity checks\n"
-	@echo -n "testing bindir for write permission..."; if [ -w ${bindir} ]; then echo "ok"; else echo " ${bindir} failed test."; exit 1; fi
-	@echo -n "testing mandir for write permission..."; if [ -w ${mandir}/man1 ]; then echo "ok"; else echo "${mandir} failed test."; exit 1; fi
-	@echo -n "testing bashdir for write permission..."; if [ -w ${bashdir} ]; then echo "ok"; else echo " no ${bashdir}, so bash tab completion won't be installed."; fi
+	@echo -n "testing bindir for write permission..."; if [ -w ${DESTDIR}${bindir} ]; then echo "ok"; else echo " ${DESTDIR}${bindir} failed test."; exit 1; fi
+	@echo -n "testing mandir for write permission..."; if [ -w ${DESTDIR}${mandir}/man1 ]; then echo "ok"; else echo "${DESTDIR}${mandir} failed test."; exit 1; fi
+	@echo -n "testing bashdir for write permission..."; if [ -w ${DESTDIR}${bashdir} ]; then echo "ok"; else echo " no ${DESTDIR}${bashdir}, so bash tab completion won't be installed."; fi
 	@echo -n "testing for Perl..."; if [ -x ${PERL} ]; then echo "ok"; else echo " please install Perl"; exit 1; fi
 	@echo -n "testing for Perl Module AppConfig..."; if [ `${PERL} -MAppConfig -e 'print "1";' 2>/dev/null` ]; then echo "ok"; else echo " please install AppConfig (try: \"make cpan-appconfig\")"; exit 1; fi
 
@@ -66,10 +72,10 @@
 
 install: check
 	@echo -e "\n** Installing connmgr\n"
-	for i in ${LINKS}; do ${INSTALL_PERL} ${SRCDIR}/tmp/$$i ${bindir}/$$i; done
-	${INSTALL_FILE} ${SRCDIR}/tmp/connmgr.1.gz ${mandir}/man1/connmgr.1.gz
-	${INSTALL_FILE} ${SRCDIR}/tmp/connmgrrc.5.gz ${mandir}/man1/connmgrrc.5.gz
-	if [ -w ${bashdir} ]; then ${INSTALL_FILE} ${SRCDIR}/tmp/bash-completion ${bashdir}/connmgr; fi
+	for i in ${LINKS}; do ${INSTALL_PERL} ${SRCDIR}/tmp/$$i ${DESTDIR}${bindir}/$$i; done
+	${INSTALL_FILE} ${SRCDIR}/tmp/connmgr.1.gz ${DESTDIR}${mandir}/man1/connmgr.1.gz
+	${INSTALL_FILE} ${SRCDIR}/tmp/connmgrrc.5.gz ${DESTDIR}${mandir}/man1/connmgrrc.5.gz
+	if [ -w ${bashdir} ]; then ${INSTALL_FILE} ${SRCDIR}/tmp/bash-completion ${DESTDIR}${bashdir}/connmgr; fi
 	@echo
 
 
