# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Artem Vorotnikov <artem@vorotnikov.me>

_gemname=zurb-foundation
_gemname1=$_gemname-5
pkgname=ruby-$_gemname
pkgver=5.2.2
pkgrel=1
pkgdesc='ZURB Foundation on Sass/Compass'
arch=(any)
url='http://foundation.zurb.com'
license=()
depends=(ruby ruby-sass)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname1-$pkgver.gem)
noextract=($_gemname1-$pkgver.gem)
sha1sums=('48a4b5910ce613573251fd8dd53862bac4423d6d')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname1-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname1-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname1-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
