#!/bin/bash
# Description: Starts the OpenNebula service as the 'oneadmin' user

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
	start)
		stat_busy 'Starting OpenNebula'
		su - oneadmin /usr/bin/one start
		if [ $? = 0 ]; then
			stat_done
		else
			stat_fail
			exit 1
		fi
		;;
	stop)
		stat_busy 'Stopping OpenNebula'
		su - oneadmin /usr/bin/one stop
		if [ $? = 0 ]; then
			stat_done
		else
			stat_fail
			exit 1
		fi
		;;
	restart)
		stat_busy 'Restarting OpenNebula'
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "Usage: oned {start|stop|restart}" >&2
		exit 1
		;;
esac
exit 0
