# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=rest-client
pkgname=ruby-$_gemname-1.6
pkgver=1.6.8
pkgrel=1
pkgdesc='Simple HTTP and REST client for Ruby, inspired by microframework syntax for specifying actions.'
arch=(any)
url='https://github.com/rest-client/rest-client'
license=(MIT)
depends=(ruby ruby-mime-types-1)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('f5023bd7999242fddc09f3173fa838bf2f319a9c')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  # non-HEAD version should not install any files in /usr/bin
  rm -r "$pkgdir/usr/bin/"
}
