# This PKGBUILD was generated by cpan4pacman via CPANPLUS::Dist::Pacman
# Maintainer: Francois Charette <firmicus@gmx.net>
pkgname=perl-class-hash
pkgver=1.01
pkgrel=1
pkgdesc="Perl extension for hashes that look like classes"
url="http://search.cpan.org/~hanenkamp/Class-Hash/"
depends=('perl')
arch=('i686' 'x86_64')
license="Artistic License"
options=('')
source=(http://search.cpan.org/CPAN/authors/id/H/HA/HANENKAMP/Class-Hash/Class-Hash-$pkgver.tar.gz)
md5sums=('5366af138b4353755decf464afedccc4')

build() {
  cd  $startdir/src/Class-Hash-$pkgver
  eval `perl -V:archname`
  # Force module installation to "current" perl directories.
  /usr/bin/perl Makefile.PL \
      INSTALLARCHLIB=/usr/lib/perl5/current/${archname} \
      INSTALLSITELIB=/usr/lib/perl5/site_perl/current \
      INSTALLSITEARCH=/usr/lib/perl5/site_perl/current/${archname}
  /usr/bin/make || return 1
  /usr/bin/make DESTDIR=$startdir/pkg install
  # remove *.pod, .packlist:
  /usr/bin/find $startdir/pkg -name '.packlist' -exec rm  '{}' \;
  /usr/bin/find $startdir/pkg -name '*.pod' -exec rm  '{}' \;
}
