post_upgrade() {
    getent group "calypso" &>/dev/null || groupadd -r "calypso"
    getent passwd "calypso" &>/dev/null || useradd -r -s /usr/bin/false -g calypso -G git,http -d /etc/calypso/ "calypso"
}

post_remove() {
    getent group "calypso" &>/dev/null && groupdel calypso 1>/dev/null
    getent passwd "calypso" &>/dev/null && userdel calypso 1>/dev/null
}

post_install() {
    post_upgrade
}
