2a3
> -include ../Makefile.config
4,5c5,6
< PY_PREFIX = $(shell python getprefix.py)
< PY_VERSION = $(shell python getversion.py)
---
> PY_PREFIX = $(shell $(PYTHON_BIN) getprefix.py)
> PY_VERSION = $(shell $(PYTHON_BIN) getversion.py)
