#!/bin/sh

if [ -r "$HOME"/.fs2_open/options ]; then
	. "$HOME"/.fs2_open/options
else
	. /usr/share/fs2_open/options
fi

cd /opt/fs2_open

if [ -x /opt/fs2_open/fs2_open_3.7.0_RC1 ]; then
	/opt/fs2_open/fs2_open_3.7.0_RC1 "$@" "$FS2OPTS"
else
	 /opt/fs2_open/fs2_open_3.7.0_RC1_DEBUG "$@" "$FS2OPTS"
fi
