#!/bin/bash

# *** LICENSE ***
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# *** CONTRIBUTORS ***
# Contributor: Changaco <changaco ατ changaco δοτ net>

if [ $# = 0 ]
then
	echo "Error: sudo requires an argument"
	exit 1
fi

PS1=":" # for .bashrc files which test this var
if [ -e "$HOME/.bashrc" ]; then
	. $HOME/.bashrc 1>/dev/null 2>/dev/null
fi

args="$@"
l=0
d="$(pwd)"
for arg in $@
do
	if [ "$arg" == "-l" ]; then
		echo "(ALL) ALL"
		exit 0
	elif alias | grep "alias $arg='" 1>/dev/null 2>/dev/null; then
		cmd="$(alias | grep "alias $arg='" | sed -e "s/.*='\(.*\)'/\1/")"
		shift
		cmd+=" $@"
		su -m -c "cd \"$d\"; $cmd;"
		exit 0
	elif which "$arg" 1>/dev/null 2>/dev/null; then
		cmd="$@"
		su -m -c "cd \"$d\"; $cmd;"
		exit 0
	fi
	shift
done
echo "Error: no valid command found in the arguments"
exit 1
