#Informational script for pacman-based systems.
post_install() {
  echo "Before running either the client or the server:"
  echo "  * create the directory \"~/.config/yuxtapa/\""
  echo "  * copy there \"client.conf\" and/or \"server.conf\" from \"/usr/share/yuxtapa/\""
  echo "  * modify the configurations to your needs"
  echo "  * the manual with more information is at /usr/share/doc/yuxtapa/index.html"
}
