
check_libdri_so(){
    if [ ! -e /usr/lib/xorg/modules/extensions/libdri.so ]; then
        ln -sf /usr/lib/xorg/modules/extensions/libdri.xorg /usr/lib/xorg/modules/extensions/libdri.so
    fi
}

whisperer(){
    echo "----------------------------------------------------------------"
    echo "Don't forget to add fglrx into MODULES array of /etc/rc.conf"
    echo "----------------------------------------------------------------"
    echo "Add nomodeset to your kernel line in /boot/grub/menu.lst , ie.:"
    echo "kernel /boot/vmlinuz26 root=/dev/sda1 ro nomodeset"
    echo "---------------------------------------- ^^^^^^^^^ -------------"
    echo "If experiencing problems with building module or using more than"
    echo "one kernel use catalyst_build_module command as root, more info:"
    echo "# catalyst_build_module help"
    echo "- ^^^^^^^^^^^^^^^^^^^^^ ----------------------------------------"
    echo "For more info and more troubleshooting visit:"
    echo "http://wiki.archlinux.org/index.php/ATI_Catalyst"
    echo "----------------------------------------------------------------"
    echo ""
    echo "Now you MUST to run:"
    echo "catalyst_build_module"
    echo "Running this command as non-root is a better way"
}

post_install() {
    check_libdri_so
    whisperer
}

post_upgrade() {
    check_libdri_so
    whisperer
}

post_remove() {
    check_libdri_so
    echo "----------------------------------------------------------------"
    echo "Don't forget to remove fglrx from MODULES array of /etc/rc.conf"
    echo "----------------------------------------------------------------"
    echo "Manually remove (with pacman -R) those packages:"
    for p in lib/modules/*; do
	if [ -e $p/video/fglrx.ko ]; then
	      echo "catalyst-${p##*lib/modules/}"
	fi
    done
}
