
check_libdri_so(){
    if [ ! -e /usr/lib/xorg/modules/extensions/libdri.so ]; then
        ln -sf /usr/lib/xorg/modules/extensions/libdri.xorg /usr/lib/xorg/modules/extensions/libdri.so
    fi
}

whisperer(){
    echo "----------------------------------------------------------------"
    echo "Don't forget to add fglrx into MODULES array of /etc/rc.conf"
    echo "----------------------------------------------------------------"
    echo "Add nomodeset to your kernel line in /boot/grub/menu.lst , ie.:"
    echo "kernel /boot/vmlinuz26 root=/dev/sda1 ro nomodeset"
    echo "---------------------------------------- ^^^^^^^^^ -------------"
    echo "If experiencing problems with building module or using more than"
    echo "one kernel use catalyst_build_module command as root, more info:"
    echo "# catalyst_build_module help"
    echo "- ^^^^^^^^^^^^^^^^^^^^^ ----------------------------------------"
    echo "For more info and more troubleshooting visit:"
    echo "http://wiki.archlinux.org/index.php/ATI_Catalyst"
    echo "----------------------------------------------------------------"
    echo ""
    echo "Now you MUST to run:"
    echo "catalyst_build_module"
    echo "Running this command as non-root is a better way"
}

signature(){
echo '5dc3fdbdb935e885163b0fa688b0a180:65edca859706c5b4260b3694b8d18cb16df6c8888176c5c442722f93b18393b56a:6bf698d9da54d0b02f0c3f90eb85c3b46ff5cddf8a03d1b174036b97b0d3c3b16ba79b8bda0dd0bd2e0a3890eb85c2b469f1ca8f8b53d1b6740a3795b183c3b56ba2' > /etc/ati/signature
}

post_install() {
    check_libdri_so
    signature
    whisperer
}

post_upgrade() {
    check_libdri_so
    signature
    whisperer
}

post_remove() {
    check_libdri_so
    echo "----------------------------------------------------------------"
    echo "Don't forget to remove fglrx from MODULES array of /etc/rc.conf"
    echo "----------------------------------------------------------------"
}
