post_install() {
echo "                           -IdentiCurse Config-"
echo "  To setup identiCurse please copy the file /usr/share/identicurse/config.json"
echo "                       and save it as ~/.identicurse"
echo ""
echo "Look at the README in /usr/identicurse if you need to change your account info"
echo "         or wish to see an overview of the programmes features"
}

post_upgrade() {
  post_install 
}
