# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Rhys <rhys@johnguant.com>

_gemname=rumai
pkgname=ruby-$_gemname
pkgver=4.1.3
pkgrel=1
pkgdesc='Ruby interface to the wmii window manager'
arch=(any)
url='http://snk.tuxfamily.org/lib/rumai/'
license=()
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('8abdc46f1f1458423fc6cd2688cebce0e220bac4')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
