#!/bin/bash

# wakeupneo 1.0.0 - "The Matrix" scene written in bash
# Copyright: (C) 2012 edloaa <edloaa at googlemail dot com>
# License: GPL-3 <http://www.gnu.org/licenses/gpl-3.0.txt>

teip() {
	str="$@"
	while [ -n "$str" ]; do
		printf "%c" "$str"
		str=${str#?}
		if [ $((RANDOM%2)) -eq 0 ]; then
			sleep .1
		else
			sleep .2
		fi
	done
}

slcl() {
	sleep 2
	clear 
}

trap '' 2 20

msg='Wake up, Neo...
The Matrix has you...
Follow the white rabbit.'

clear
echo -en '\e[1;32m'

echo "$msg" | \
while read line; do
	teip "$line"
	slcl
done

echo -n "Knock, kock, Neo."
slcl

echo -en '\e[0m'
