# Generated by gem2arch

_gemname=rocco
pkgname=ruby-$_gemname
pkgver=0.8.2
pkgrel=1
pkgdesc="Docco in Ruby"
arch=('any')
url="http://rtomayko.github.com/rocco/"
license=('')
depends=('ruby' 'ruby-redcarpet>=0' 'ruby-mustache>=0')
makedepends=('rubygems')
source=(http://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
md5sums=('b8102245b0ed329f8bd280e4cf4534ba')
sha1sums=('a3cc304637e91d1afe4625eac18f35b06355ec31')

package() {
  cd "$srcdir"
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
}
