pre_install() {
  echo
}

post_install() {
    if [ -r "/etc/prelink.conf" ] && [ -w "/etc/prelink.conf" ] && \
            ! grep -q -- "^-b /usr/lib/SpiderOak\$" "/etc/prelink.conf"; then
        echo "-b /usr/lib/SpiderOak" >>"/etc/prelink.conf"
    fi
  echo
  echo "Do not use prelink on /usr/lib/SpiderOak/*"
  echo "done"
}

post_remove() {
  sed -i "\,^-b /usr/lib/SpiderOak\$, d" "/etc/prelink.conf"
}
