
post_install() {
  cat <<EOT
#############################################################
# Copy the directory /usr/share/linapple/config/linapple to #
# \$XDG_CONFIG_HOME/linapple before running linapple.        #
# \$XDG_CONFIG_HOME is usually loacated at \$HOME/.config     #
#############################################################
EOT
}

post_upgrade() {
  post_install
}

# vim:set ts=2 sw=2 et:
