# Generated by Xyne::Arch::CPAN 0.07

pkgname=perl-dns-zoneparse
pkgver=1.100.0
pkgrel=1
pkgdesc="Parse and manipulate DNS Zone Files."
arch=('i686' 'x86_64')
url="http://search.cpan.org/dist/DNS-ZoneParse/"
license=('unknown')
source=('http://search.cpan.org/CPAN/authors/id/M/MS/MSCHILLI/DNS-ZoneParse-1.10.tar.gz')
md5sums=('663b517d731f939742550fa45118650e')
sha256sums=('b96db6acf39bde6578dc3b83caa2e85fa4f5481c110ede83f1f95e1a3fb4124c')
depends=('perl' 'perl-storable>=0.407.0')
makedepends=('perl-extutils-makemaker')
options=(!emptydirs)

build() {
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Makefile.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor || return 1
    make  || return 1
    make install DESTDIR="${pkgdir}" || return 1

  else
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Build.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Build.PL INSTALLDIRS=vendor || return 1
    ./Build  || return 1
    ./Build install destdir=${pkgdir} || return 1

  else
    echo "error: failed to detect build method for $pkgname"
    echo "you may be able to fix this by editing the PKGBUILD"
    return 1
  fi fi

  # remove perllocal.pod and .packlist
  find ${pkgdir} -name perllocal.pod -delete
  find ${pkgdir} -name .packlist -delete
}

# vim:set ts=2 sw=2 et:

