#!/bin/sh
cd /usr/share/df_linux/
export SDL_DISABLE_LOCK_KEYS=1 # Work around for bug in Debian/Ubuntu SDL patch.
#export SDL_VIDEO_CENTERED=1 # Centre the screen.  Messes up resizing.
LD_PRELOAD=/usr/lib32/libz.so.1 ./libs/Dwarf_Fortress $* # Go, go, go! :)

