#!/bin/bash

[ -f /etc/conf.d/tomcat7 ] && . /etc/conf.d/tomcat7

. /etc/rc.conf
. /etc/rc.d/functions

JSVC_BIN=/usr/share/tomcat7/bin/jsvc
PID_FILE=/var/run/tomcat7.pid

case "$1" in
  start)
    stat_busy "Starting Tomcat 7"
    $JSVC_BIN \
      -user tomcat7 \
      -Dcatalina.home=/usr/share/tomcat7 \
      -Dcatalina.base=/usr/share/tomcat7 \
      -Djava.io.tmpdir=/tmp \
      -wait 10 \
      -pidfile $PID_FILE \
      -outfile $OUT_FILE \
      -errfile $ERROR_FILE \
      $CATALINA_OPTS \
      -cp /usr/share/tomcat7/bin/commons-daemon.jar:/usr/share/tomcat7/bin/bootstrap.jar:/usr/share/tomcat7/bin/tomcat-juli.jar \
      org.apache.catalina.startup.Bootstrap

    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon tomcat7
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Tomcat 7"
    $JSVC_BIN \
      -stop \
      -pidfile $PID_FILE \
      org.apache.catalina.startup.Bootstrap

    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon tomcat7
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
