# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: tuftedocelot <tuftedocelot@fastmail.fm>

_gemname=gimli
pkgname=ruby-$_gemname
pkgver=0.5.7
pkgrel=2
pkgdesc='Utility for converting markup files to pdf files.'
arch=(any)
url='https://github.com/walle/gimli'
license=()
depends=(ruby ruby-github-markup ruby-redcarpet ruby-redcloth ruby-coderay ruby-nokogiri ruby-wkhtmltopdf-binary ruby-optiflag ruby-posix-spawn)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('a6a752ac5dbdf2478daf12b322e19ab2cd1aec19')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
