post_install() {
	echo "Updating icon cache..."
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
        echo "
        >> If you're using compiz animation plugin, add 
                 & !(name=notify-osd)
        >> to the Close Animation's Window Match section
        >> to avoid flickering."
	echo "> You probably need relogin."
}

post_upgrade() {
	post_install
}

post_uninstall() {
	echo "Updating icon cache..."
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}
