.TH RS 1
.SH NAME
fshell \- An RScheme Interpreter with Preloaded Modules
.SH SYNOPSIS
.B fshell
.I 
.RI "[options]"
.SH "DESCRIPTION"
.BR fshell
is the rscheme interpreter with preloaded modules. For more
information see the
.BR rs
man page.

.SH SEE ALSO
.BR rs(1), rsc(1)

.SH AUTHOR
Donovan Kolbly <d.kolbly@rscheme.org>



