.TH RSC 1
.SH NAME
rsc \- An Offline Compiler from RScheme to C
.SH SYNOPSIS
.B rsc
.I 
.RI "[arguments]"
.SH "DESCRIPTION"
This manual page documents briefly the
.BR rsc
command.
.PP
RScheme is a scheme interpreter and compiler with object extensions,
threads, a persistent store, an optional real-time garbage collector,
and many other nifty features.
.P
The offline compiler from RScheme to C described in Chapter 15 of the 
RScheme documentation (see below). On a debian system you can also find
an example in \fI/usr/share/doc/rscheme/module-example/fR.

.SH SEE ALSO
.BR rs(1), fshell(1)
.P
The RScheme manual can be found at
\fIhttp://www.rscheme.org/rs/doc.prepub/db/Welcome.html\fR.
On a Debian system the manual is available in html format at
\fI/usr/share/doc/rscheme/html/\fR or through the dhelp help system.

.SH AUTHOR
Donovan Kolbly <d.kolbly@rscheme.org>

This manual page was compiled from the RScheme documentation for the
Debian GNU/Linux distribution because the original program does not
have a manual page.


