post_install() {
  cat << 'EOM'
  --> Please cd to /opt/fah-v7/ and execute ./FAHClient --configure
  --> as root to configure your settings. If you are using systemd, 
  --> then run "systemctl enable foldingathome-v7.service" to enable
  --> the folding service. If you are using initscripts, then add
  --> "foldingathome-v7" to the list of daemons in /etc/rc.conf.
  --> If you would like join the Arch Linux team, use team number 
  --> 45032.  
EOM
}

