diff -r 95a123079c5e -r 9dc7d52ff8ec Makefile
--- a/Makefile	Fri Dec 16 15:07:48 2011 -0500
+++ b/Makefile	Fri Dec 30 11:49:26 2011 -0500
@@ -1,7 +1,7 @@
+CC=dmd
+CFLAGS=-v1 -I./src/ -O -release -inline -od$(OBJDIR)
 PREFIX=/usr/
 BUILDPREFIX=./usr/
-CC=dmd
-CFLAGS=-O -release -inline -od$(OBJDIR)
 OBJDIR=/tmp/
 
 EXECUTABLE=obmenugen
@@ -16,6 +16,7 @@
 
 
 $(EXECUTABLE): $(SOURCES)
+	mkdir -p $(BUILDPREFIX)/$(BINDIR)
 	$(CC) $(CFLAGS) -of$(BUILDPREFIX)/$(BINDIR)$@ $^
 
 
