#!/usr/bin/ruby
#-- vim:sw=2:et
#++
# Author:: Okasu <oka.sux@gmail.com>

require 'open-uri'
require 'cgi'
from = ARGV[0]
to = ARGV[1]
subj = CGI.escape(ARGV[2..-1].to_s.gsub(/[\[\]",]/, ""))
open("http://translate.google.com/?sl=#{from}&tl=#{to}&oe=UTF-8&text=#{subj}") do |page|
  page_content = page.read
  rare_word = page_content.scan(/'">.+<\/span><\/s/).to_s.gsub(/['"><\[\]\/\\]/, "")
  words = page_content.scan(/<li>noun<div><div>.*<\/div><\/li><\/ol>/).to_s.gsub(/<\/?\w+>/, ">").squeeze(">").each_line(">").to_a.uniq
  if words == ["[]"]
    puts rare_word[0..-6].gsub("&#39;","'").gsub(/span.*fff/, "")
    break
  end
  words[1..-2].each do |word|
    case word
    when "noun>"; puts "Nouns:"; next
    when "verb>"; puts "\nVerbs:"; next
    when "adjective>"; puts "\nAdjectives:"; next
    when "adverb>"; puts "\nAdverbs:"; next
    end
    puts word.chop
  end
end
