post_install()
{
    if [ ! -f /etc/X11/xdm/svg-theme/logo.svg ]; then
        cd /etc/X11/xdm/svg-theme
        ln -s -f /usr/share/pixmaps/xdm-svg-theme/Gnulinux.svg logo.svg
    fi
    doc="/usr/share/doc/xdm-svg-theme/README"
    echo -e "\n---- Contents of ${doc}: ----"
    cat "${doc}"
}

pre_remove()
{
    rm -f /etc/X11/xdm/svg-theme/logo.svg 2> /dev/null
    rm -f /var/cache/xdm-svg-theme/* 2> /dev/null
}
