# Contributor: Alex Peltzer <alex.peltzer@gmail.com>
# Maintainer: Alex Peltzer <alex.peltzer@gmail.com>

pkgname=mapdamage
realpkgname=mapDamage
pkgver=2
pkgrel=1
pkgdesc="A computational framework writtein Python and R, which tracks and quantifies DNA damage patterns among ancient DNA sequencing reads generated by NGS platforms."
arch=('x86_64')
url="http://ginolhac.github.io/mapDamage/"
license=('GPL')
depends=('python2' 'sh' 'r' 'git' 'cython2')
makedepends=('python2-pysam' 'gsl')
source=("https://github.com/ginolhac/mapDamage.git" "installDependencies.R")
md5sums=('SKIP' '55413f5a3168c8ebd0eb4d37944ab68a')

build() {
  msg "Building the package for Python 2"
  cd "$srcdir"
  git clone --recursive $source
  cd $realpkgname
  python2 setup.py install --root="$pkgdir/" --optimize=1
}

package() {
  msg "Installing the R Dependencies"
  Rscript installDependencies.R
}



