#!/bin/bash

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

if [ ! -f ~/.config/compiz-gtk-decorator-theme.cfg ]; then
  if zenity --question --title="First run setup" --text="<b>First run setup</b>\n\n<b>Do you want to set the title bar\nfont to the system font?</b>\n\nIf unsure, click Yes."; then
    gconftool-2 -s /apps/metacity/general/titlebar_uses_system_font -t bool true
  else
    gconftool-2 -s /apps/metacity/general/titlebar_uses_system_font -t bool false
  fi
  if zenity --question --title="First run setup" --text="<b>Apply bugfix to window control buttons?</b>\n\nIf unsure, click Yes.\n\nIf you've custom configured your window\nbutton positions in GConf already, click No,\nas this will reset it."; then
    gconftool-2 -s /apps/metacity/general/button_layout -t string ":minimize,maximize,close"
  fi
  touch ~/.config/compiz-gtk-decorator-theme.cfg
  zenity --info --text="<b>First run setup complete.</b>\n\nIf you ever want to be asked those questions again, delete:\n<b>~/.config/compiz-gtk-decorator-theme.cfg</b>\nand run the Compiz GTK decorator theme selector again."
fi
  

main_window() {
  selection=$(
    zenity --height 450 --width 300 --list --ok-label="Apply" --cancel-label="Close" \
    --title="Compiz GTK decorator theme" \
    --column="Installed Metacity themes:" \
    "Compiz GWD default" $(cat /usr/share/themes/*/metacity-1/metacity-theme-*.xml | grep "</name>" | sed 's/^.*<name>//' | sed 's|</name>||' | sed 's/ /-/' | sed -n 'G; s/\n/&&/; /^\([ -~]*\n\).*\n\1/d; s/\n//; h; P')
  )
}

while [ $? = 0 ]; do
if [ "$selection" == "Compiz GWD default" ]; then
  gconftool-2 -u /apps/metacity/general/theme
elif [ "$selection" != "" ]; then
  gconftool-2 -s /apps/metacity/general/theme -t string "$selection"
fi
main_window
done

IFS=$SAVEIFS
