post_install() {
  echo "Before you can use this plasmoid you"
  echo "have to restart Plasma Desktop with:"
  echo "kquitapp plasma-desktop && sleep 2 && plasma-desktop"
  echo "or by logging out and back in" 
}

post_upgrade() {
  echo "To use the updated version immediately you"
  echo "have to restart Plasma Desktop with:"
  echo "kquitapp plasma-desktop && sleep 2 && plasma-desktop"
  echo "or by logging out and back in" 
}
