_update_font_maps() {
	cat /usr/share/u2ps/ps/Fontmap.* > /usr/share/u2ps/ps/Fontmap
	cat /usr/share/u2ps/ps/resmap.* > /usr/share/u2ps/ps/resmap
}

post_install() {
	_update_font_maps

	if [ ! -f /usr/share/u2ps/ps/Fontmap.freemono ]; then
		echo
		echo "FreeMono fset not found"
		echo "Consider installing u2ps-freemono or u2ps-freemono-kochi"
		echo
	fi
}

post_remove() {
	_update_font_maps
}

post_upgrade() {
	_update_font_maps
}
