# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './src/settingsw.ui'
#
# Created: Sun Dec 26 11:27:38 2010
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SettingsW(object):
    def setupUi(self, SettingsW):
        SettingsW.setObjectName(_fromUtf8("SettingsW"))
        SettingsW.resize(610, 355)
        self.verticalLayout_10 = QtGui.QVBoxLayout(SettingsW)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.tabWidget = QtGui.QTabWidget(SettingsW)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_main = QtGui.QWidget()
        self.tab_main.setObjectName(_fromUtf8("tab_main"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_main)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_10 = QtGui.QLabel(self.tab_main)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 24))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_8.addWidget(self.label_10)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.ch_fst = QtGui.QRadioButton(self.tab_main)
        self.ch_fst.setText(_fromUtf8("&fst"))
        self.ch_fst.setObjectName(_fromUtf8("ch_fst"))
        self.horizontalLayout_8.addWidget(self.ch_fst)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.ch_vsthost = QtGui.QRadioButton(self.tab_main)
        self.ch_vsthost.setText(_fromUtf8("&dssi-vst"))
        self.ch_vsthost.setObjectName(_fromUtf8("ch_vsthost"))
        self.horizontalLayout_8.addWidget(self.ch_vsthost)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.groupBox_8 = QtGui.QGroupBox(self.tab_main)
        self.groupBox_8.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_9 = QtGui.QLabel(self.groupBox_8)
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_8)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1)
        self.i_nogui = QtGui.QLabel(self.groupBox_8)
        self.i_nogui.setMaximumSize(QtCore.QSize(16, 16777215))
        self.i_nogui.setText(_fromUtf8(""))
        self.i_nogui.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/dialog-ok-apply.png")))
        self.i_nogui.setObjectName(_fromUtf8("i_nogui"))
        self.gridLayout_2.addWidget(self.i_nogui, 0, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_8)
        self.label_12.setText(_fromUtf8(""))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 0, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_8)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 1, 1, 1)
        self.i_presets = QtGui.QLabel(self.groupBox_8)
        self.i_presets.setMaximumSize(QtCore.QSize(16, 16777215))
        self.i_presets.setText(_fromUtf8(""))
        self.i_presets.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/dialog-ok-apply.png")))
        self.i_presets.setObjectName(_fromUtf8("i_presets"))
        self.gridLayout_2.addWidget(self.i_presets, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_8)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 2, 1, 1, 1)
        self.i_lash = QtGui.QLabel(self.groupBox_8)
        self.i_lash.setMaximumSize(QtCore.QSize(16, 16777215))
        self.i_lash.setText(_fromUtf8(""))
        self.i_lash.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/dialog-ok-apply.png")))
        self.i_lash.setObjectName(_fromUtf8("i_lash"))
        self.gridLayout_2.addWidget(self.i_lash, 2, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_8)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 3, 1, 1, 1)
        self.i_tempo = QtGui.QLabel(self.groupBox_8)
        self.i_tempo.setMaximumSize(QtCore.QSize(16, 16777215))
        self.i_tempo.setText(_fromUtf8(""))
        self.i_tempo.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/dialog-ok-apply.png")))
        self.i_tempo.setObjectName(_fromUtf8("i_tempo"))
        self.gridLayout_2.addWidget(self.i_tempo, 3, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_8)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 4, 1, 1, 1)
        self.i_midi = QtGui.QLabel(self.groupBox_8)
        self.i_midi.setText(_fromUtf8("ALSA | Jack"))
        self.i_midi.setObjectName(_fromUtf8("i_midi"))
        self.gridLayout_2.addWidget(self.i_midi, 4, 2, 1, 2)
        self.verticalLayout_8.addWidget(self.groupBox_8)
        self.tabWidget.addTab(self.tab_main, _fromUtf8(""))
        self.tab_paths = QtGui.QWidget()
        self.tab_paths.setObjectName(_fromUtf8("tab_paths"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_paths)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_paths)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.listPaths = QtGui.QListWidget(self.groupBox_3)
        self.listPaths.setAlternatingRowColors(True)
        self.listPaths.setObjectName(_fromUtf8("listPaths"))
        self.horizontalLayout_5.addWidget(self.listPaths)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.b_add = QtGui.QPushButton(self.groupBox_3)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/list-add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_add.setIcon(icon)
        self.b_add.setObjectName(_fromUtf8("b_add"))
        self.verticalLayout_6.addWidget(self.b_add)
        self.b_remove = QtGui.QPushButton(self.groupBox_3)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/list-remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_remove.setIcon(icon1)
        self.b_remove.setObjectName(_fromUtf8("b_remove"))
        self.verticalLayout_6.addWidget(self.b_remove)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem4)
        self.b_edit = QtGui.QPushButton(self.groupBox_3)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/document-edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_edit.setIcon(icon2)
        self.b_edit.setObjectName(_fromUtf8("b_edit"))
        self.verticalLayout_6.addWidget(self.b_edit)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.line_3 = QtGui.QFrame(self.groupBox_3)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_3.addWidget(self.line_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.l_recursive_ico = QtGui.QLabel(self.groupBox_3)
        self.l_recursive_ico.setMaximumSize(QtCore.QSize(16, 16777215))
        self.l_recursive_ico.setText(_fromUtf8(""))
        self.l_recursive_ico.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/dialog-information.png")))
        self.l_recursive_ico.setObjectName(_fromUtf8("l_recursive_ico"))
        self.horizontalLayout_6.addWidget(self.l_recursive_ico)
        self.l_recursive = QtGui.QLabel(self.groupBox_3)
        self.l_recursive.setObjectName(_fromUtf8("l_recursive"))
        self.horizontalLayout_6.addWidget(self.l_recursive)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_paths)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_11 = QtGui.QLabel(self.groupBox_6)
        self.label_11.setText(_fromUtf8("WINEPREFIX:"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        self.lineWinePrefix = QtGui.QLineEdit(self.groupBox_6)
        self.lineWinePrefix.setObjectName(_fromUtf8("lineWinePrefix"))
        self.gridLayout_3.addWidget(self.lineWinePrefix, 0, 1, 1, 1)
        self.b_reset_wine = QtGui.QPushButton(self.groupBox_6)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/edit-undo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_reset_wine.setIcon(icon3)
        self.b_reset_wine.setObjectName(_fromUtf8("b_reset_wine"))
        self.gridLayout_3.addWidget(self.b_reset_wine, 0, 2, 1, 1)
        self.label_ladish = QtGui.QLabel(self.groupBox_6)
        self.label_ladish.setObjectName(_fromUtf8("label_ladish"))
        self.gridLayout_3.addWidget(self.label_ladish, 1, 0, 1, 1)
        self.lineLadishFolder = QtGui.QLineEdit(self.groupBox_6)
        self.lineLadishFolder.setObjectName(_fromUtf8("lineLadishFolder"))
        self.gridLayout_3.addWidget(self.lineLadishFolder, 1, 1, 1, 1)
        self.b_reset_ladish = QtGui.QPushButton(self.groupBox_6)
        self.b_reset_ladish.setIcon(icon3)
        self.b_reset_ladish.setObjectName(_fromUtf8("b_reset_ladish"))
        self.gridLayout_3.addWidget(self.b_reset_ladish, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.tabWidget.addTab(self.tab_paths, _fromUtf8(""))
        self.tab_misc = QtGui.QWidget()
        self.tab_misc.setObjectName(_fromUtf8("tab_misc"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_misc)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.gr_con = QtGui.QGroupBox(self.tab_misc)
        self.gr_con.setObjectName(_fromUtf8("gr_con"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.gr_con)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.ch_sysout = QtGui.QCheckBox(self.gr_con)
        self.ch_sysout.setObjectName(_fromUtf8("ch_sysout"))
        self.verticalLayout_4.addWidget(self.ch_sysout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.ch_midiin = QtGui.QCheckBox(self.gr_con)
        self.ch_midiin.setObjectName(_fromUtf8("ch_midiin"))
        self.horizontalLayout.addWidget(self.ch_midiin)
        self.co_midiin = QtGui.QComboBox(self.gr_con)
        self.co_midiin.setEditable(True)
        self.co_midiin.setObjectName(_fromUtf8("co_midiin"))
        self.horizontalLayout.addWidget(self.co_midiin)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.line_2 = QtGui.QFrame(self.gr_con)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_4.addWidget(self.line_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.l_pyjack_ico = QtGui.QLabel(self.gr_con)
        self.l_pyjack_ico.setMaximumSize(QtCore.QSize(16, 16))
        self.l_pyjack_ico.setText(_fromUtf8(""))
        self.l_pyjack_ico.setPixmap(QtGui.QPixmap(_fromUtf8(":/icons/dialog-error.png")))
        self.l_pyjack_ico.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.l_pyjack_ico.setObjectName(_fromUtf8("l_pyjack_ico"))
        self.horizontalLayout_2.addWidget(self.l_pyjack_ico)
        self.l_pyjack = QtGui.QLabel(self.gr_con)
        self.l_pyjack.setMaximumSize(QtCore.QSize(16777215, 16))
        self.l_pyjack.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.l_pyjack.setObjectName(_fromUtf8("l_pyjack"))
        self.horizontalLayout_2.addWidget(self.l_pyjack)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addWidget(self.gr_con)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_misc)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.ch_wineserver = QtGui.QCheckBox(self.groupBox_2)
        self.ch_wineserver.setObjectName(_fromUtf8("ch_wineserver"))
        self.verticalLayout.addWidget(self.ch_wineserver)
        self.ch_warn = QtGui.QCheckBox(self.groupBox_2)
        self.ch_warn.setObjectName(_fromUtf8("ch_warn"))
        self.verticalLayout.addWidget(self.ch_warn)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.tabWidget.addTab(self.tab_misc, _fromUtf8(""))
        self.tab_adv = QtGui.QWidget()
        self.tab_adv.setObjectName(_fromUtf8("tab_adv"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab_adv)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_adv)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.ch_winert = QtGui.QCheckBox(self.groupBox_4)
        self.ch_winert.setObjectName(_fromUtf8("ch_winert"))
        self.gridLayout_4.addWidget(self.ch_winert, 0, 0, 1, 1)
        self.spinRT = QtGui.QSpinBox(self.groupBox_4)
        self.spinRT.setMinimum(1)
        self.spinRT.setMaximum(99)
        self.spinRT.setProperty(_fromUtf8("value"), 15)
        self.spinRT.setObjectName(_fromUtf8("spinRT"))
        self.gridLayout_4.addWidget(self.spinRT, 0, 1, 1, 1)
        self.ch_winesvrt = QtGui.QCheckBox(self.groupBox_4)
        self.ch_winesvrt.setObjectName(_fromUtf8("ch_winesvrt"))
        self.gridLayout_4.addWidget(self.ch_winesvrt, 1, 0, 1, 1)
        self.spinSVRT = QtGui.QSpinBox(self.groupBox_4)
        self.spinSVRT.setMinimum(1)
        self.spinSVRT.setProperty(_fromUtf8("value"), 10)
        self.spinSVRT.setObjectName(_fromUtf8("spinSVRT"))
        self.gridLayout_4.addWidget(self.spinSVRT, 1, 1, 1, 1)
        self.ch_chrt = QtGui.QCheckBox(self.groupBox_4)
        self.ch_chrt.setObjectName(_fromUtf8("ch_chrt"))
        self.gridLayout_4.addWidget(self.ch_chrt, 2, 0, 1, 2)
        self.line = QtGui.QFrame(self.groupBox_4)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_4.addWidget(self.line, 3, 0, 1, 2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.label = QtGui.QLabel(self.groupBox_4)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 4, 0, 1, 2)
        self.verticalLayout_9.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_adv)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox_5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineArgs = QtGui.QLineEdit(self.groupBox_5)
        self.lineArgs.setObjectName(_fromUtf8("lineArgs"))
        self.gridLayout.addWidget(self.lineArgs, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineFinal = QtGui.QLineEdit(self.groupBox_5)
        self.lineFinal.setText(_fromUtf8(""))
        self.lineFinal.setReadOnly(True)
        self.lineFinal.setObjectName(_fromUtf8("lineFinal"))
        self.gridLayout.addWidget(self.lineFinal, 1, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox_5)
        self.tabWidget.addTab(self.tab_adv, _fromUtf8(""))
        self.verticalLayout_10.addWidget(self.tabWidget)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem12)
        self.buttonBox = QtGui.QDialogButtonBox(SettingsW)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_10.addWidget(self.buttonBox)
        self.label_2.setBuddy(self.lineArgs)
        self.label_3.setBuddy(self.lineFinal)

        self.retranslateUi(SettingsW)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SettingsW.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SettingsW.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsW)

    def retranslateUi(self, SettingsW):
        SettingsW.setWindowTitle(QtGui.QApplication.translate("SettingsW", "FeSTige - Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("SettingsW", "Utility to use:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("SettingsW", "Features:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("SettingsW", "VSTs with no custom GUI:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("SettingsW", "VST Presets:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("SettingsW", "Ladish Support:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("SettingsW", "Handle Transport info:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("SettingsW", "MIDI Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_main), QtGui.QApplication.translate("SettingsW", "Main", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("SettingsW", "Extra VST Paths", None, QtGui.QApplication.UnicodeUTF8))
        self.b_add.setText(QtGui.QApplication.translate("SettingsW", "&Add", None, QtGui.QApplication.UnicodeUTF8))
        self.b_remove.setText(QtGui.QApplication.translate("SettingsW", "&Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.b_edit.setText(QtGui.QApplication.translate("SettingsW", "&Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.l_recursive.setText(QtGui.QApplication.translate("SettingsW", "Note that recursive search is supported. No need for extra folders here.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("SettingsW", "Outro", None, QtGui.QApplication.UnicodeUTF8))
        self.b_reset_wine.setText(QtGui.QApplication.translate("SettingsW", "Rese&t", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ladish.setText(QtGui.QApplication.translate("SettingsW", "Default Ladish Folder:", None, QtGui.QApplication.UnicodeUTF8))
        self.b_reset_ladish.setText(QtGui.QApplication.translate("SettingsW", "Rese&t", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_paths), QtGui.QApplication.translate("SettingsW", "Paths", None, QtGui.QApplication.UnicodeUTF8))
        self.gr_con.setTitle(QtGui.QApplication.translate("SettingsW", "Connections", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_sysout.setText(QtGui.QApplication.translate("SettingsW", "Auto-Connect new VSTs to System &Output", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_midiin.setText(QtGui.QApplication.translate("SettingsW", "Auto-Connect &Midi Input to:", None, QtGui.QApplication.UnicodeUTF8))
        self.l_pyjack.setText(QtGui.QApplication.translate("SettingsW", "PyJack status goes here", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("SettingsW", "Misc", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_wineserver.setText(QtGui.QApplication.translate("SettingsW", "&Run \"wineserver -p\" at FeSTige startup", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_warn.setText(QtGui.QApplication.translate("SettingsW", "Show &warnings", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_misc), QtGui.QApplication.translate("SettingsW", "Misc", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("SettingsW", "Real-Time Scheduling", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_winert.setText(QtGui.QApplication.translate("SettingsW", "Enable &Wine Real-Time Scheduling (*)", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_winesvrt.setText(QtGui.QApplication.translate("SettingsW", "Enable Wine&Server Real-Time Schedulling (*)", None, QtGui.QApplication.UnicodeUTF8))
        self.ch_chrt.setText(QtGui.QApplication.translate("SettingsW", "Manipulate real-time attributes with &chrt (Incompatible with ladish!)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SettingsW", "<i>(*) This option requires Wine compiled with the RT patch</i>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("SettingsW", "Command to run", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("SettingsW", "&Extra arguments:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("SettingsW", "&Final command: <i>(preview)</i>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_adv), QtGui.QApplication.translate("SettingsW", "Advanced", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
