post_install() {
    getent group icecc &>/dev/null || groupadd -r icecc >/dev/null
    getent passwd icecc &>/dev/null || useradd -r -g icecc -s /bin/false -c "Icecream Daemon" -d /var/cache/icecream icecc 2>/dev/null
}

post_upgrade() {
    post_install
}

post_remove() {
    getent passwd icecc &>/dev/null && userdel icecc >/dev/null
    getent group icecc &>/dev/null && groupdel icecc >/dev/null
    true
}
