infodir=/usr/share/info
filelist=(gcl-si.info gcl-tk.info gcl-tk.info-1 gcl-tk.info-2 gcl.info
          gcl.info-1 gcl.info-2 gcl.info-3 gcl.info-4 gcl.info-5 gcl.info-6
          gcl.info-7 gcl.info-8 gcl.info-9)

post_install() {
  for file in ${filelist[@]}; do
    install-info $infodir/$file $infodir/dir 2> /dev/null
  done
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  for file in ${filelist[@]}; do
    install-info --delete $infodir/$file $infodir/dir 2> /dev/null
  done
}
