pkgname=awn

post_install() {
  usr/sbin/gconfpkg --install ${pkgname}
  xdg-icon-resource forceupdate --theme hicolor &>/dev/null
  update-desktop-database -q
}

pre_upgrade() {
  pre_remove
}

post_upgrade() {
  post_install
}

pre_remove() {
  usr/sbin/gconfpkg --uninstall ${pkgname}
}

post_remove() {
  xdg-icon-resource forceupdate --theme hicolor &>/dev/null
  update-desktop-database -q
}

# vim:set ts=2 sw=2 et:
