post_install() {
  ndiswrapper -m
  KERNEL_VERSION='2.6.25-ice'
  depmod -ae -v $KERNEL_VERSION > /dev/null 2>&1 
  /bin/true
}

post_upgrade() {
  ndiswrapper -m
  KERNEL_VERSION='2.6.25-ice'
  depmod -ae -v $KERNEL_VERSION > /dev/null 2>&1 
  /bin/true
}

pre_remove() {
  /bin/true
}

post_remove() {
  KERNEL_VERSION='2.6.25-ice'
  depmod -ae -v $KERNEL_VERSION > /dev/null 2>&1
  /bin/true
}

op=$1
shift

$op $*
