# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: jhaohai <jhaohai@foxmail.com>

_gemname=narray
pkgname=ruby-$_gemname
pkgver=0.6.0.9
pkgrel=1
pkgdesc='N-dimensional Numerical Array class for Ruby'
arch=(i686 x86_64)
url='http://masa16.github.io/narray/'
license=(Ruby)
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('5197cc88ed6a8f7e6635e9500323595b75b78cb3')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
