post_install() {
  /bin/cat << EOF

===> sbagen post-install message:

===> Complimentary files for use with sbagen are located in /usr/share/sbagen
===>
===> Run sbagen from /usr/share/sbagen when using the examples that require
===> ogg files to include them properly.
===> 
===> sbagen uses oss - to run through alsa (allowing dmix etc to work
===> correctly) install aoss and run like this: 'aoss sbagen arguments'

EOF
}

