info_text() {
    /bin/cat << EOF

NOTE: The 'sbagen' command is now a symlink to 'sbagen-alsa', which uses alsa-oss to run sbagen with Alsa instead of OSS. You can still run sbagen using OSS using 'sbagen-oss'

Samples, examples, scripts and documents are located in /usr/share/sbagen

Examples using external media expect sbagen to run in the folder containing it
 
EOF
}

post_install() {
    info_text
}

post_upgrade() {
    info_text
}
