# Maintainer: tuftedocelot@fastmail.fm
# Generated by gem2arch

_gemname=sanitize
pkgname=ruby-$_gemname
pkgver=3.0.3
pkgrel=1
pkgdesc="Whitelist-based HTML sanitizer."
arch=('any')
url="https://github.com/rgrove/sanitize/"
license=('')
depends=('ruby' 'ruby-nokogiri')
makedepends=('rubygems')
source=(http://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
md5sums=('18979bd9c2ce6fdd323d9c121d2fb0e7')

package() {
  cd "$srcdir"
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
}
