post_install() {
cat << _EOF

==> MyUPB installation instructions:
    ----------------------------------------
	Before using your new MyUPB installation, you must configure your web server for hosting the /usr/share/webapps/myupb/ directory.
        Then you have to add "/usr/share/webapps/myupb/" in the open_basedir (/etc/php/php.ini) and execute the http://localhost/path/to/myupb/install.php.
	Then you should execute the update.php.
_EOF

}

post_update() {
	   post_install
}