post_install() {
  post_upgrade
}

post_upgrade() {
  getent group "phxd" &>/dev/null || groupadd -r phxd 1>/dev/null
  getent passwd "phxd" &>/dev/null || useradd -r -g phxd -d "/var/empty" -s "/bin/sh" phxd 1>/dev/null
  chown -R phxd:phxd "/srv/phxd" 1>/dev/null
}

post_remove() {
  if getent passwd "phxd" >/dev/null; then
    userdel phxd >/dev/null
  fi
  if getent group "phxd" >/dev/null; then
    groupdel phxd >/dev/null
  fi
}
