#!/bin/bash
export WINEARCH=win32 WINEPREFIX="$HOME/.ytd/wine"

if [ ! -d "$HOME"/.ytd ] ; then
  mkdir -p "$HOME"/.ytd/wine || exit 1
  cp -r /usr/share/ytd/ytd.xml "$HOME"/.ytd || exit 1
  
  ln -s /usr/share/ytd/ytd.exe "$HOME"/.ytd/ytd.exe || exit 1
  ln -s /usr/share/ytd/msdl_dll.dll "$HOME"/.ytd/msdl_dll.dll || exit 1
  ln -s /usr/share/ytd/rtmpdump_dll.dll "$HOME"/.ytd/rtmpdump_dll.dll || exit 1
  ln -s -T /usr/share/ytd/locale "$HOME"/.ytd/locale || exit 1
fi

wine "$HOME"/.ytd/ytd.exe "$@"
