# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Rhys <rhys@johnguant.com>

_gemname=aruba
pkgname=ruby-$_gemname
pkgver=0.6.1
pkgrel=1
pkgdesc='aruba-0.5.4'
arch=(any)
url='http://github.com/cucumber/aruba'
license=(MIT)
depends=(ruby ruby-cucumber ruby-childprocess ruby-rspec-expectations)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('cbc8a9cd04056cee0bae21284ff3f2e1551fac63')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
