# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Matanya Moses <matanya@foss.co.il>

_gemname=xml-simple
pkgname=ruby-$_gemname
pkgver=1.1.3
pkgrel=1
pkgdesc='A simple API for XML processing.'
arch=(any)
url='https://github.com/maik/xml-simple'
license=(Ruby)
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('66a2584518d93e94e466328e80081d9f2952d4a8')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
