# arg 1:  the new package version
post_install() {
  cat <<EOM

Please read http://www.slrn.org/documentation.html to learn how to setup slrn

Quick instructions:
1. Set the environment variable NNTPSERVER e.g.
   NNTPSERVER="my.news.server" && export NNTPSERVER

2. create a file which holds the list of newsgroups
   $ slrn -f \${HOME}/.jnewsrc --create

3. run slrn
   $ slrn -f \${HOME}/.jnewsrc

EOM
}

post_upgrade() {
  post_install $1
}

op=$1
shift
$op $*
# vim: ft=sh
