post_install() {
  echo "
Installation instructions:

  Get the game via Steam (in wine) or from another installation and copy the 
  directory \"Steam/steamapps/common/terraria/Content\" and to \"/opt/linaria\".
  It can usually find Steam in \"~/.wine/drive_c/Program Files\", but you may
  have installed it elsewhere.

Music instructions:
  http://www.terrariaonline.com/threads/72997/
"
}

pre_remove() {
  rm -fr /opt/linaria/Content
}
