# Generated by script URL
pkgname=keepass-lt
pkgver=2.26
pkgrel=1
pkgdesc="Lithuanian locale for keepass"
license=('GPL')
depends=('keepass>=2.26')
url="http://keepass.info/translations.html"
md5sums=('2fa57199451b7f0afcf72a221471950e')
source=(http://downloads.sourceforge.net/keepass/KeePass-${pkgver}-Lithuanian.zip)
install=keepass-lt.install
arch=('any')
package(){
	install -D -m644 Lithuanian.lngx $pkgdir/usr/share/keepass/Lithuanian.lngx
}
