# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>
# Contributor: Alfredo Palhares <masterkorp@masterkorp.net>
# Contributor: Matthew Monaco <net 0x01b matt>
# Contributor: Rogof <com gmail fake.bios>

_gemname=gherkin
pkgname=ruby-$_gemname-2.11
pkgver=2.11.8
pkgrel=2
pkgdesc='gherkin-2.11.8'
arch=(i686 x86_64)
url='http://github.com/cucumber/gherkin'
license=(GPL)
depends=(ruby ruby-multi_json)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('9b488ad84bd8e8fc238df62b8543b17948cbb07a')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
