post_install()
{
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  update-desktop-database -q
  cat << EOF
  >>> To make wildmidi use the Freepats patches,
  >>> create a new /etc/wildmidi.cfg file with the following line
  >>> dir /usr/share/timidity/freepats (taken from /etc/timidity++/timidity-freepats.cfg)
  >>> and append to it the content of /etc/timidity++/freepats/freepats.cfg.
EOF
}

post_upgrade()
{
  post_install
}

post_remove()
{
  post_install
}
