post_install() {
  getent group jetty >/dev/null 2>&1 || groupadd -g 66 jetty
  getent passwd jetty >/dev/null 2>&1 || useradd -u 66 -g jetty -d /var/lib/jetty -s /bin/false jetty
  chown -R jetty:jetty /var/{log,lib}/jetty
}

post_upgrade(){
  post_install $1
}

pre_remove() {
  if getent passwd jetty >/dev/null 2>&1; then
      userdel jetty
  fi
  if getent group jetty >/dev/null 2>&1; then
      groupdel jetty
  fi
}

