#!/bin/bash

# create the ~/.typhoon_2001 directory if needed
if [ ! -d ~/.typhoon_2001 ]; then
  mkdir -p ~/.typhoon_2001
  ln -s /usr/share/typhoon_2001/*.mod		~/.typhoon_2001
  ln -s /usr/share/typhoon_2001/typhoon		~/.typhoon_2001
  ln -s /usr/share/typhoon_2001/tp.dat		~/.typhoon_2001
  cp -a /usr/share/typhoon_2001/game		~/.typhoon_2001
fi

pushd ~/.typhoon_2001 > /dev/null &&
~/.typhoon_2001/typhoon
popd > /dev/null
