# PKGBUILD generated by pacpan
pkgname=perl-data-uuid-libuuid
_realname=Data-UUID-LibUUID
pkgver=0.04
pkgrel=1
pkgdesc="~"
arch=(i686 x86_64)
license=('~')
url="http://search.cpan.org/~nuffin/Data-UUID-LibUUID"
options=(!emptydirs)

depends=('perl' 'perl-test-use-ok' 'perl-sub-exporter' 'perl-asa')

#provides=('Data-UUID-LibUUID')
provides=('data-uuid-libuuid=0.04' 'Data::UUID::LibUUID=0.04' 'perl-data-uuid-libuuid=0.04' 'Data::UUID::LibUUID::DataUUIDCompat=undef' 'perl-data-uuid-libuuid-datauuidcompat=undef')

source=(http://search.cpan.org/CPAN/authors/id/N/NU/NUFFIN/Data-UUID-LibUUID-0.04.tar.gz)
md5sums=('36b3edbebca201081a8df7160482973d')

build() {
  _expected_dir="${srcdir}/${_realname}-${pkgver}"
  if [ -d "$_expected_dir" ]; then
    cd "$_expected_dir"
  else
    _expected_dir="${srcdir}/$(bsdtar -t -f $(basename $source) | head -n1)"
    if [ -d "$_expected_dir" ]; then
      cd "$_expected_dir"
    else
      _makefile=$(find $srcdir -iname Makefile.PL)
      if [ ! -z "$_makefile" ]; then
        _expected_dir=$(dirname $_makefile)
        if [ -d "$_expected_dir" ]; then
          cd "$_expected_dir"
        else
          echo "[1;31mERROR[0m unable to detect source directory"
          echo "[1;34m-->[0m this is often due to CPAN's lack of standard naming conventions"
          echo "[1;34m-->[0m it may be possible to fix this by adjusting the build function in the PKGBUILD"
        fi
      fi
    fi
  fi
  # install module in vendor directories.
  PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor || return 1
  make  || return 1
  make install DESTDIR=${pkgdir} || return 1

  # remove perllocal.pod and .packlist
  find ${pkgdir} -name perllocal.pod -delete
  find ${pkgdir} -name .packlist -delete
}

