post_install() {
  echo "******"
  echo "*"
  echo "* Documentation can be found at:"
  echo "* https://ripple.com/wiki/Ripple_Client"
  echo "*"
  echo "* Next steps:"
  echo "* 1. Customize /usr/share/ripple-client/src/js/config.js as needed"
  echo "* 2. Customize /usr/share/ripple-client/config.json as needed"
  echo "* 3. firefox /usr/share/ripple-client/build/bundle/web/index.html"
  echo "*"
  echo "******"
}
