post_install() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  echo 'For first time run lifeograph user must create empty config file:'
  echo '(see this bug: https://bugs.launchpad.net/lifeograph/+bug/704316)'
  echo 'mkdir $XDG_CONFIG_HOME/lifeograph/'
  echo 'touch $XDG_CONFIG_HOME/lifeograph/lifeo.conf'
}

pre_upgrade() {
  pre_remove $1
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}
