#!/bin/bash
#
# twat (thinkwatt):
# record power consumption, calculate average and create a gnuplot graph
#
# TO-DO:
# * add more options (e.g. for specifying a different gnuplot title or png output)

# utilities {{{
message() {
  cat << EOF
usage:	thinkwatt [ -r <seconds> | -p | -a ] file

options:	
	-r, --record	the all-in-one argument:
			will record consumption to a specified (or temporary) file and then create a gnuplot graph from it
	-p, --plot	create a plot image from a specified data file
	-a, --average	calculate the average power consumption from a specified data file
	-h, --help	show this help text
	
examples:
	thinkwatt -r 300 (will record for 5 minutes to a tmp file)
	thinkwatt -r 60 /foo/bar/consumption.dat
	thinkwatt -p /foo/bar/consumption.dat
	
notes:
	when using the option -r please avoid spaces in path- and filenames
EOF
  exit 1
}

errorout() { echo "error: $*" >&2; exit 1; }

check_ac() {
  local acfile=/sys/class/power_supply/AC/online
  [[ $(cat $acfile) = 0 ]] || errorout 'please unplug the ac adapater first'
}
check_datafile() {
  [[ -f "$@" ]] || errorout "$@ does not exist"
  local valid_file=$(file "$@" | grep -s "^$@: ASCII text$")
  [[ $valid_file ]] || errorout "$@ is not a valid data file"
  local valid_data=$(grep -s '^[0-9]*[,.]\?.*[0-9]$' "$@")
  [[ $valid_data ]] || errorout "$@ does not contain valid data"
}
check_last() {
  for last; do :;done
}
countdown() {
  secs="$1"
  while [ $secs -gt 0 ]
  do
    [[ $die == yes ]] && return 0
    sleep 1 &
    cat "$powerfile" >> "$tmpfile1"
    printf "\r%02d/$seconds seconds left" $((secs))
    secs=$(( $secs - 1 ))
    wait
  done
  echo
}

trap ctrl_c INT
function ctrl_c() {
	echo
        read -p "plot already recorded data before exiting? y/n "
	[[ "$REPLY" = "y" ]] && die=yes || exit 0
}
# }}}

# plotting variables {{{
DATE=$(date +%Y-%m-%d,\ %T)
TITLE="power consumption of my laptop, created by thinkwatt on $DATE"
XLABEL="sec (seconds)"
YLABEL="W (Watt)"
TERMINAL="png"
GRID=yes

## some more options for gnuplot, enable and modify them here if you like
MYTICS=2
MXTICS=2
#YTICS=1
#XTICS=(better leave this alone)
GRIDSET="mytics"
#TITLE1="your custom title for line1"
#TITLE2="your custom title for line2"
#TITLE3="your custom title for line3"
#YRANGE="[4000:16000]"
#XRANGE="[0:2000]"

# use $TDIR to have twat save files in a different directory.
# twat will save two files:
# 1) a .plt file (containing plot instructions) in case you want to reuse/modify it
# 2) a .png file (the plot graphic)
TDIR="/tmp/thinkwatt"
PLOTFILE="$TDIR/$$.plt"
# }}}

# record {{{
record() {

  local seconds="$1"
  local datafile="$2"
  
  [[ "$seconds" =~ ^[0-9]+$ ]] || errorout "please specify the time in seconds."
  [[ -d "$datafile" ]] && errorout "$datafile is a directory"
  if [[ -f "$datafile" ]];then
    read -p "overwrite $datafile? y/n "
    [[ "$REPLY" = "y" ]] || exit 0
  elif [[ -e "$datafile" ]];then
    echo "$datafile exists and can/should not be written to"
  fi

  SMAPI=$(lsmod | grep -s smapi)
  if [[ "$SMAPI" ]];then
    local powerfile=/sys/devices/platform/smapi/BAT0/power_now
  else
    echo "for more accurate results use tp_smapi"
    local powerfile=/sys/class/power_supply/BAT0/power_now
  fi
  
  local tmpfile1=/tmp/$$.dat
  touch "$tmpfile1" || errorout "could not create $tmpfile1"
  trap "rm $tmpfile1" EXIT
  
  # do the actual recording included in countdown()
  countdown "$seconds"
  
  [[ -d "$TDIR" ]] || mkdir -p "$TDIR" || errorout "could not create $TDIR"
  local tmpfile=$TDIR/$$.dat
  
  # file formatting
  if [[ "$SMAPI" ]];then
    # we strip the leading "-" from the data file
    sed -i 's/-//g' "$tmpfile1"
  else
    # strip the trailing last 3 characters
     sed -i 's/.\{3\}$//' "$tmpfile1"
  fi
  # and divide by 1000 to convert from mW to W
  cat "$tmpfile1" | awk '{print $1/1000}' > "$tmpfile"
  
  if [[ "$datafile" ]];then
    local dir=$(dirname "$datafile")
    local file=$(basename "$datafile")

    [[ -d "$dir" ]] || mkdir -p "$dir"
    
    outputfile="$datafile"
    PNGFILE=$dir/$(basename "$file" .dat).png
  
    mv "$tmpfile" "$datafile"
  else
    local file=$(basename "$tmpfile")
    outputfile="$tmpfile"
    local istemp=true
  fi
  
  echo "average was $(average $outputfile) W"
  
  plot "$outputfile"

}
# }}}

# calculate average {{{
average() {

  [[ "$@" ]] || errorout 'please specify a file to read from.'
  [[ -f "$@" ]] || errorout 'file not found.'
  check_datafile "$@"
  
  awk 'BEGIN{s=0;}{s+=($1);}END{print s/NR;}' "$@"
  
}
# }}}

# make the plot file {{{
makeplotfile() {

  cat << EOF
# gnuplot file
# created by thinkwatt
# $DATE

set title "$TITLE"
set xlabel "$XLABEL"
set ylabel "$YLABEL"
set terminal $TERMINAL
set output "$PNGFILE"
EOF
[[ $YRANGE ]] && echo "set yrange $YRANGE"
[[ $XRANGE ]] && echo "set yrange $YRANGE"
[[ $GRID == yes ]] && echo "set grid"
[[ $YTICS ]] && echo "set ytics $YTICS"
[[ $MYTICS ]] && echo "set mytics $MYTICS"
[[ $XTICS ]] && echo "set xtics $XTICS"
[[ $MXTICS ]] && echo "set mxtics $MXTICS"
[[ $GRIDSET ]] && echo "set grid $GRIDSET"

echo 
if [[ $TITLE1 ]];then
  echo "plot \"$datfile\" using (\$1) with lines title \"$TITLE1\" lt 2, \\"
else
  echo "plot \"$datfile\" using (\$1) with lines lt 2, \\"
fi

if [[ $TITLE2 ]];then
  if [[ $avg ]];then
    echo "\"$datfile\" using (\$1) smooth bezier title \"$TITLE2\" lt 1, \\"
  else
    echo "\"$datfile\" using (\$1) smooth bezier title \"$TITLE2\" lt 1"
  fi
else
  if [[ $avg ]];then
    echo "\"$datfile\" using (\$1) smooth bezier lt 1, \\"
  else
    echo "\"$datfile\" using (\$1) smooth bezier lt 1"
  fi
fi

[[ $avg ]] && echo "$avg title \"$file (average, $avg W)\""

}
# }}}

# do the plotting
plot() {

  # check if we have gnuplot and $TDIR is present
  have_gnuplot=$(find $(sed 's/:/ /g' <<<$PATH) | grep -is gnuplot)
  [[ $have_gnuplot  ]] || errorout 'to plot you have to install gnuplot first'
  [[ -d "$TDIR" ]] || mkdir -p "$TDIR" || errorout "could not create $TDIR"
  
  # is input file a valid data file?
  local datfile="$@"
  check_datafile "$datfile"
  [[ "$datfile" ]] || errorout 'please specify a file to read from.'
  [[ -f "$datfile" ]] || errorout 'file not found.'
   
  # define some of the variables for the plot file
  local avg=$(average "$datfile" | cut -c1-4)
  local dir=$(dirname "$datfile")
  local file=$(basename "$datfile")
  [[ -z $TITLE1 ]] && local TITLE1="$file (actual)"
  [[ -z $TITLE2 ]] && local TITLE2="$file (trend)"
  [[ $PNGFILE ]] || PNGFILE=$(basename "$datfile" .dat).png
  
  # now we can plot   
  makeplotfile > "$PLOTFILE" || errorout "failed writing the plotfile"
  gnuplot "$PLOTFILE" || errorout "failed plotting"

  if [[ $tmpfile ]];then
    if [[ $istemp ]];then
      echo "graph saved as $PNGFILE"
    else
      echo "graph and data file saved to $dir"
    fi
  else
    echo "graph saved as $PNGFILE"
  fi

}

# parse options {{{
parse_options() {

  [[ -z "$1" ]] && message

  while [[ -n "$1" ]]; do
    case "$1" in
      -r|--record)  mode='record'	;;
      -p|--plot)    mode='plot'		;;
      -a|--average) mode='average'	;;
      -h|--help)    message		;;
      *)            args+=( "$1" )	;;
    esac
    shift
  done
}
# }}}

# main {{{
main() {

  case "$mode" in
    record)  record "${args[@]}"	;;
    average) average "${args[@]}"	;;
    plot)    plot "${args[@]}"		;;
    *)       errorout 'invalid mode. use -r, -p or -a.' ;;
  esac
  
}
# }}}

parse_options "$@"
check_ac
main
