## arg 1:  the new package version
post_install() {
    echo "export AWS_CREDENTIAL_FILE=/opt/as-cmd-tools/credential-file\nexport AWS_AUTO_SCALING_HOME=/opt/as-cmd-tools \nexport PATH=$PATH:$AWS_AUTO_SCALING_HOME/bin" > /etc/profile.d/as-cmd-tools.sh
    echo "setenv AWS_CREDENTIAL_FILE /opt/as-cmd-tools/credential-file\nsetenv AWS_AUTO_SCALING_HOME /opt/as-cmd-tools \nsetenv PATH ${PATH}:${AWS_AUTO_SCALING_HOME}/bin" > /etc/profile.d/as-cmd-tools.csh
    chmod 755 /etc/profile.d/as-cmd-tools.sh
    chmod 755 /etc/profile.d/as-cmd-tools.csh
    echo "Remember to edit the file /opt/as-cmd-tools/credential-file with your AWS Access Key and AWS Secret Key!"
}
