## arg 1:  the new package version
post_install() {
    echo "export AWS_AUTO_SCALING_HOME=/opt/as-cmd-tools \nexport PATH=$PATH:$AWS_AUTO_SCALING_HOME/bin" > /etc/profile.d/as-cmd-tools.sh
    echo "setenv AWS_AUTO_SCALING_HOME /opt/as-cmd-tools \nsetenv PATH ${PATH}:${AWS_AUTO_SCALING_HOME}/bin" > /etc/profile.d/as-cmd-tools.csh
    chmod 755 /etc/profile.d/as-cmd-tools.sh
    chmod 755 /etc/profile.d/as-cmd-tools.csh
}
