pkgname=glc-git

post_install() {
	echo " >> glc scripts are installed in '/usr/share/glc/scripts'"
	echo " >> run '[script].sh --help' for command-line options"
	echo " >> the play.sh uses mplayer to play streams ..."
	echo " >> so install it if you want to use that script"
	echo " >> see the Getting Started Section of -"
	echo " >> http://nullkey.ath.cx/projects/glc/wiki for more info"
}


op=$1
shift
$op $*
