
post_install() {
    dkms install -m v4l2loopback -v ${1%-*}
      cat << EOF
==> To build and install your modules run: dkms install v4l2loopback/${1%-*}
==> To do this automatically at startup run: systemctl enable dkms.service
EOF
}

pre_remove() {
    # Remove all modules using dkms
    [ -n "${1%-*}" ] && dkms remove v4l2loopback/${1%-*} --all &>/dev/null || true
}

pre_upgrade() {
    pre_remove "$2"
}

post_upgrade() {
    post_install "$1"
}

