#AUTHOR: Will Price <will.price94@gmail.com>
#Generated by `npm2PKGBUILD`


_npmname=gitbook
_npmver=1.0.2
pkgname=nodejs-gitbook # All lowercase
pkgver=1.0.2
pkgrel=1
pkgdesc="Library and cmd utility to generate GitBooks"
arch=(any)
url="http://www.gitbook.io/"
license=()
depends=('nodejs' )
optdepends=()
source=(http://registry.npmjs.org/$_npmname/-/$_npmname-$_npmver.tgz)
noextract=($_npmname-$_npmver.tgz)
sha1sums=(f356f03cf8c73816d349669f178fdb4d3700a4e0)

build() {
  cd $srcdir
  local _npmdir="$pkgdir/usr/lib/node_modules/"
  mkdir -p $_npmdir
  cd $_npmdir
  npm install -g --prefix "$pkgdir/usr" $_npmname@$_npmver
}

# vim:set ts=2 sw=2 et:
