post_install() {
 echo '--------------------------------------------------------------------------'
 echo '                            SETUP INSTRUCTIONS'
 echo
 echo '                https://wiki.archlinux.org/index.php/E4rat'
 echo '--------------------------------------------------------------------------'
 echo
 echo '--------------------------------------------------------------------------'
 echo '                                 SUMMARY'
 echo 'add to grub kernel line:'
 echo '    init=/usr/sbin/e4rat-collect'
 echo
 echo 'log data for 2 min, then'
 echo '   sudo init 1'
 echo '   e4rat-realloc  /var/lib/e4rat/startup.log'
 echo
 echo 'substitute init=/usr/sbin/e4rat-collect with'
 echo '    init=/usr/sbin/e4rat-preload'
 echo '--------------------------------------------------------------------------'
}
