#Automatically generated by pip2arch on 2014-07-03

pkgname=python-mangopi
pkgver=0.2.1.1
pkgrel=1
pkgdesc="A manga API with a pluggable site architecture."
url="https://github.com/jiaweihli/mangopi/"
depends=('python' )
makedepends=('python3' )
license=('MIT')
arch=('any')
source=('https://pypi.python.org/packages/source/m/mangopi/mangopi-0.2.1.1.tar.gz')
md5sums=('4a27a5c2e2e2e5e90f504c72915952d3')

build() {
    cd $srcdir/mangopi-0.2.1.1
    python setup.py build
}

package() {
    cd $srcdir/mangopi-0.2.1.1
    python setup.py install --root="$pkgdir" --optimize=1 
}
