post_install() {
  cat <<-EndOfMessage

  ==> Several settings can be changed like screen resolution in the
  ==> configuration file.  You will need to copy it to your home directory
  ==> then edit it:
  ==>
  ==> cp /opt/WorldOfGoo/properties/config.txt ~/.WorldOfGoo/

	EndOfMessage

  update-desktop-database -q
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_upgrade() {
  post_install
}
