pre_install() {
	
	if [ ! -f "/usr/share/transmission/web/index.original.html" ]; then
		echo "Backup the old index.html file"
		mv /usr/share/transmission/web/index.html  /usr/share/transmission/web/index.original.html
	fi
}
post_install() {
	 mv /usr/share/transmission/web/index.htm /usr/share/transmission/web/index.html
}
post_remove() {
	if [ -f "/usr/share/transmission/web/index.original.html" ]; then
	mv /usr/share/transmission/web/index.original.html /usr/share/transmission/web/index.html
	fi
}
