#!/bin/sh

. /etc/rc.conf
. /etc/rc.d/functions
# Test custom variables
test -f /etc/conf.d/ss5 && . /etc/conf.d/ss5

PID=$(pidof -o %PPID /usr/sbin/ss5)

# See how we were called.
case "$1" in
  start)
        # Start daemon.
        stat_busy "Starting ss5... "
	success=0
        /usr/sbin/ss5 -t $SS5_OPTS || success=$?
	if [ $success -eq 0 ]; then
	    add_daemon ss5
            #touch /var/lock/subsys/ss5
	    stat_done
	else
	    stat_fail
	fi
        ;;
  stop)
        # Stop daemon.
	stat_busy "Shutting down ss5... "
	[[ -n "$PID" ]] && kill $PID &>/dev/null
	if [ $? -eq 0 ]; then
            #rm -f /var/lock/subsys/ss5
	    rm -f /var/run/ss5/ss5.pid
	    rm_daemon ss5
	    stat_done
	else
            stat_fail
	fi
        ;;
  reload)
        # Reload configuration
	stat_busy "Reloading ss5... "
	pkill -HUP ss5
	if [ $? -eq 0 ]; then
	    stat_done
	else
            stat_fail
	;;
        fi
  restart)
        # Restart daemon
	$0 stop
	sleep 1
	$0 start
	;;
  status)
	stat_busy "Checking ss5 status... "
	ck_status ss5
	;;
  *)
        echo "Usage: $0 {start|stop|status|restart|reload}"
        exit 1
	;;
esac
exit 0
