--- Makefile.orig	2011-08-31 09:58:43.840096370 +0200
+++ Makefile	2011-08-31 09:59:03.830096507 +0200
@@ -47,5 +47,6 @@
 	rm -f $(objects) voipmonitor gzstream/*.o libgzstream.a
 
 install: 
-	install voipmonitor /usr/local/sbin/
+	mkdir -p $(DESTDIR)/usr/local/sbin/
+	install voipmonitor $(DESTDIR)/usr/local/sbin/
 
