post_install() {
  echo "NOTE:"
  echo "  pkgupdate will *not* sync your pacman database. You will need"
  echo "  to create a cronjob for that. For example, create an executable"
  echo "  (chmod +x) shell script including \"pacman -Sy\" (without the"
  echo "  quotes) and place it in /etc/cron.hourly to sync your database"
  echo "  every hour. See https://wiki.archlinux.org/index.php/Cron for"
  echo "  more elaborate cronjobs."
}

post_upgrade() {
  post_install $1
}
