# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>
# Contributor: Alfredo Palhares <masterkorp@masterkorp.net>

_gemname=capistrano-chef
pkgname=ruby-$_gemname
pkgver=1.0.0
pkgrel=1
pkgdesc='Capistrano extensions for Chef integration'
arch=(any)
url='https://github.com/cramerdev/capistrano-chef'
license=(MIT)
depends=(ruby ruby-capistrano ruby-chef)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('f5e1f7540f841624d708db3a1bdbbf473697ef60')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
