post_install() {
    hooks=$(grep ^HOOKS etc/mkinitcpio.conf | grep vbox)
    if [ "$hooks" = "" ]; then
        sed 's/^HOOKS="\([^"]*\)"/HOOKS="\1 vbox"/' -i etc/mkinitcpio.conf
    fi
    heads=$(grep ^SyncFirst etc/pacman.conf | grep linux-headers)
    if [ "$heads" = "" ]; then
	sed '/^SyncFirst/s|$| linux-headers|' -i etc/pacman.conf
    fi
}

post_remove() {
    sed '/^HOOKS/s/ *vbox//' -i etc/mkinitcpio.conf
    sed '/^SyncFirst/s/ *linux-headers//' -i etc/pacman.conf
}
