
pre_install() {
  echo "..."
  echo ">>>backs up the original module.";
  echo
  mv  /lib/modules/`uname -r`/kernel/drivers/media/dvb-core/dvb-core.ko.gz /lib/modules/`uname -r`/kernel/drivers/media/dvb-core/dvb-core.ko.gz.backup
}

post_remove() {
  echo "..."
  echo ">>>restore the original module."
  echo
  mv  /lib/modules/`uname -r`/kernel/drivers/media/dvb-core/dvb-core.ko.gz.backup /lib/modules/`uname -r`/kernel/drivers/media/dvb-core/dvb-core.ko.gz
}
