# Generated by gem2arch

_gemname=versionomy
pkgname=ruby-$_gemname
pkgver=0.4.4
pkgrel=1
pkgdesc="Versionomy is a generalized version number library."
arch=('any')
url="http://dazuma.github.com/versionomy"
license=('')
depends=('ruby' 'ruby-blockenspiel>=0.4.5')
makedepends=('rubygems')
source=(http://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
md5sums=('5f3b84daf316ac84f3f22fdfa2b61594')
sha1sums=('00b4bf8d7853ae906a60832045d605652b2ba1f9')

package() {
  cd "$srcdir"
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
}
