# Maintainer: Daenyth <Daenyth+Arch AT gmail DOT com>
#Automatically generated by pip2arch on 2011-03-10

pkgname=python-zencoder
pkgver=0.2
pkgrel=1
pkgdesc="Integration library for Zencoder"
url="http://github.com/schworer/zencoder-py"
depends=('python2' )
makedepends=()
license=('MIT')
arch=('any')
source=('http://pypi.python.org/packages/source/z/zencoder/zencoder-0.2.tar.gz')
md5sums=('656a419f4a094aff7d620463a53b06c6')

build() {
    cd $srcdir/zencoder-0.2
    python2 setup.py install --root="$pkgdir" --optimize=1
}
