#!/bin/sh
post_upgrade() {
  post_install $1
}

post_install() {
  echo "Qooxdoo SDK was installed into /opt/qooxdoo/<version> directory"
  echo "but you can use the symlink /opt/qooxdoo/current instead."
  echo ""
  echo "Read Getting Started guide on http://qooxdoo.org/ if you"
  echo "have any questions."
  echo ""
  echo "You may call qx-create-application to create a new qooxdoo application."
}

op=$1
shift
$op $*

