update_cache() {
	xdg-icon-resource forceupdate --theme UltraFlatIcons
	xdg-icon-resource forceupdate --theme UltraFlatIconsDark
	xdg-icon-resource forceupdate --theme UltraFlatIconsOrange
	xdg-icon-resource forceupdate --theme UltraFlatIconsOrangeDark
	xdg-icon-resource forceupdate --theme UltraFlatIconsOrangeBright
	xdg-icon-resource forceupdate --theme UltraFlatIconsOrangeBrightDark
}

post_install() {
	update_cache
}

post_upgrade() {
	update_cache
}