# This program depends on libcrypto 0.9.8, but works fine with 1.0.0.
# Therefore, we need to create a link to the new binary.
post_install() {
  ln -s -f /usr/lib/libcrypto.so /usr/lib/libcrypto.so.0.9.8
}


# If the created link still exists on removal, remove it as well.
post_remove() {
  if [ -L /usr/lib/libcrypto.so.0.9.8 ]; then
    rm /usr/lib/libcrypto.so.0.9.8
  fi
}


# vim:set ts=2 sw=2 et:
