LIB = -L.. -lcurie 
INC = -I../../include

TGT = bad-allocation bad-resize cpio curie-main directory environment exit filesystem gc graph immutable io io-special memory-allocator memory-pool memory-primitives multiplex-io multiplex-sexpr read-write regex sexpr-custom sexpr-read sexpr-set sexpr-sort sexpr-write string-set time tree-node-removal tree-plain tree-random tree-random-node-removal tree-value

all: $(TGT)

$(TGT):
	gcc -o $@ $@.c $(LIB) $(INC)
	@-./$@

clean:
	rm -f $(TGT)
