#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

DAEMON=/usr/sbin/ccpd
PID=$(pidof -o %PPID ${DAEMON})

start ()
{
  stat_busy "Starting CCPD"
  [ -z "${PID}" ] && ${DAEMON} 2>/dev/null
  if [ $? -gt 0 ]; then
    stat_fail
  else
    add_daemon ccpd
    stat_done
  fi
}

stop ()
{
  stat_busy "Stopping CCPD"
  [ ! -z "${PID}" ]  && kill ${PID} &> /dev/null
  if [ $? -gt 0 ]; then
    stat_fail
  else
    rm_daemon ccpd
    stat_done
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
