# Generated by gem2arch
# Maintainer: LeeF

_gemname=spruz
pkgname=ruby-enterprise-$_gemname
pkgver=0.2.2
pkgrel=0
pkgdesc="Useful stuff."
arch=('i686' 'x86_64')
url="http://flori.github.com/spruz"
license=('MIT')
depends=('ruby-enterprise')
makedepends=('ruby-enterprise')
source=(http://gems.rubyforge.org/gems/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
md5sums=('3026237f53182d8bac462f72425aee1a')

build() {
  cd $srcdir
  local _gemdir=`ruby -rubygems -e'puts Gem.default_dir'`
  gem install --ignore-dependencies --no-rdoc --no-ri  -i "$pkgdir$_gemdir" $_gemname-$pkgver.gem
}
