_pkgname=cut2col
_pkgver=v34c

post_install()
{

	if [ -h /usr/bin/${_pkgname} ] 
	then
		rm -f /usr/bin/${_pkgname} || return 1
	fi
	
	echo -e "#!/bin/bash\ncd /opt/${_pkgname}\njava -jar ${_pkgname}-${_pkgver}.jar" > /usr/bin/${_pkgname} || return 1
	chmod +x /usr/bin/${_pkgname} || return 1
 
}
 
post_upgrade()
{
  post_install $1
}


post_remove() 
{
	if [ -h /usr/bin/${_pkgname} ] 
	then
		rm -f /usr/bin/${_pkgname} || return 1
	fi
}
