post_install() {
  cat << END_OF_MESSAGE
--------------------------------------------------------------------------------
Mono needs root certificates in order to do HTTPS communication properly, but it
doesn't come with any by default. Run one of these commands to install them:
For all users; run as root:   mozroots --import --machine --sync
For the current user only:    mozroots --import --sync
--------------------------------------------------------------------------------
END_OF_MESSAGE
}
