#!/bin/bash
PRG="$0"
# Get standard environment variables
PRGDIR=/opt/udig
DATA_ARG=false

for ARG in $@ 
do
	if [ $ARG = "-data" ]; then DATA_ARG=true; fi
done

if $DATA_ARG; then 
	$PRGDIR/private-bin $@
else
	$PRGDIR/private-bin -data ~/uDigWorkspace $@
fi
