post_install() {
    echo "** Please copy /usr/share/kde4/services/magnet_kio.protocol to \$(kde4-config --localprefix)/share/kde4/services/magnet.protocol as each user then run kbuildsycoca4"
    echo "** Otherwise ktorrent will still handle magnet URLs"
}
post_upgrade() {
    post_install
}

post_remove() {
    echo "** Remember to remove \$(kde4-config --localprefix)/share/kde4/services/magnet.protocol as each user"
}
