# arg 1:  the new package version
post_install() {
  cat << EOM

--> Add the following line to the modules section of your apache config
   LoadModule auth_pgsql_module modules/mod_auth_pgsql.so
   
--> The following lines have to be in .htaccess file to use authentication.
   AuthUserFile /dev/null
   AuthBasicAuthoritative Off
EOM
  /bin/true
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $i
}

op=$1
shift
$op $*
