post_install() {
  cat <<EOT
=======================================================================
In order to set initial status of devices at boot, you need to add
samsung-tools at the end of the DAEMONS array in /etc/rc.conf.

Support for 'laptop-mode-tools' is dropped.
In its place, Samsung Tools installs scripts in /etc/pm/power.d/
used to enable power management features.
You can enable/disable each feature by toggling the execute bit
for each individual script.

From version 1.3, Samsung Tools has support for custom commands
to be automatically executed when devices are toggled.
This is done with scripts found in /etc/samsung-tools/scripts/.
For instance, if you need to run a command when wireless is turned on,
just add it to /etc/samsung-tools/scripts/wireless-on. 
=======================================================================
EOT
}

post_upgrade() {
  post_install
}

post_remove() {
  rm -rf /usr/lib/samsung-tools/
}
