--- a/seed7/src/mk_linux.mak	2011-03-06 05:51:35.000000000 -0500
+++ b/seed7/src/mk_linux.mak	2011-03-20 10:12:23.000000000 -0400
@@ -2,8 +2,12 @@
 # To compile use a command shell and call:
 #   make -f mk_linux.mak depend
 #   make -f mk_linux.mak
+# To install use a command shell and call:
+#   make -f mk_linux.mak install
 # If you are under windows you should use MinGW with mk_mingw.mak, mk_nmake.mak or mk_msys.mak instead.
 
+DESTDIR =
+prefix = /usr
 # CFLAGS =
 # CFLAGS = -Wall -Wstrict-prototypes -Winline -Wconversion -Wshadow -Wpointer-arith
 # CFLAGS = -O2 -fomit-frame-pointer -Wall -Wstrict-prototypes -Winline -Wconversion -Wshadow -Wpointer-arith
@@ -25,6 +29,12 @@
 LIBS = -lX11 -lncurses -lm
 # LIBS = -lX11 -lncurses -lm -lgmp
 # LIBS = -lX11 -lncurses -lm_p -lc_p
+BIN_DIR = $(prefix)/bin
+BASE_DIR = $(prefix)/share/seed7
+LIB_DIR = $(BASE_DIR)/lib
+RLIB_DIR = $(BASE_DIR)/bin
+DOC_DIR = $(BASE_DIR)/doc
+PRG_DIR = $(BASE_DIR)/prg
 SEED7_LIB = seed7_05.a
 COMP_DATA_LIB = s7_data.a
 COMPILER_LIB = s7_comp.a
@@ -116,6 +126,19 @@
 clean:
 	rm -f *.o ../bin/*.a depend a_depend b_depend c_depend version.h
 
+install: ../bin/hi
+	mkdir -p $(DESTDIR)$(BIN_DIR) $(DESTDIR)$(RLIB_DIR) $(DESTDIR)$(LIB_DIR) $(DESTDIR)$(DOC_DIR) $(DESTDIR)$(PRG_DIR)
+	cp ../bin/hi $(DESTDIR)$(BIN_DIR)/hi
+	cp -t $(DESTDIR)$(RLIB_DIR) ../bin/*.a
+	cp -t $(DESTDIR)$(DOC_DIR) ../doc/*
+	cp -t $(DESTDIR)$(LIB_DIR) ../lib/*.s7i
+	cp -t $(DESTDIR)$(PRG_DIR) ../prg/*
+	rm $(DESTDIR)$(PRG_DIR)/hi
+
+uninstall:
+	rm -r $(BASEDIR)
+	rm $(prefix)/bin/hi
+
 dep: depend
 
 strip:
@@ -165,10 +188,10 @@
 	echo "#define LINKER_OPT_OUTPUT_FILE \"-o \"" >> version.h
 	echo "#define LINKER_FLAGS \"$(LDFLAGS)\"" >> version.h
 	echo "#define SYSTEM_LIBS \"$(LIBS)\"" >> version.h
-	cd ../bin; echo "#define SEED7_LIB \"`pwd`/$(SEED7_LIB)\"" >> ../src/version.h; cd ../src
-	cd ../bin; echo "#define COMP_DATA_LIB \"`pwd`/$(COMP_DATA_LIB)\"" >> ../src/version.h; cd ../src
-	cd ../bin; echo "#define COMPILER_LIB \"`pwd`/$(COMPILER_LIB)\"" >> ../src/version.h; cd ../src
-	cd ../lib; echo "#define SEED7_LIBRARY \"`pwd`\"" >> ../src/version.h; cd ../src
+	cd ../bin; echo "#define SEED7_LIB \"$(RLIB_DIR)/$(SEED7_LIB)\"" >> ../src/version.h; cd ../src
+	cd ../bin; echo "#define COMP_DATA_LIB \"$(RLIB_DIR)/$(COMP_DATA_LIB)\"" >> ../src/version.h; cd ../src
+	cd ../bin; echo "#define COMPILER_LIB \"$(RLIB_DIR)/$(COMPILER_LIB)\"" >> ../src/version.h; cd ../src
+	cd ../lib; echo "#define SEED7_LIBRARY \"$(LIB_DIR)\"" >> ../src/version.h; cd ../src
 
 depend: a_depend b_depend c_depend version.h
 	$(CC) $(CFLAGS) -M $(SRC) > depend
