post_install() {
  cat << EOF

Installing driver
--------------------
	1. Edit /etc/mkinitcpio.conf, add psb_gfx to MODULES list
	2. Rebuild initrd image with mkinitcpio -p kernel26-mainline
    3. Set up xorg.conf like this:
        Section "Device"
            Identifier     "GMA500"
            Driver         "fbdev"
        EndSection

EOF
}

post_remove() {
	echo "Don't forget to remove psb_gfx from MODULES in /etc/mkinitcpio.conf"
}
