post_install() {
  cat << EOF

Installing driver
--------------------
	1. Edit /etc/mkinitcpio.conf, add psb_gfx to MODULES list
	2. Rebuild initrd image with mkinitcpio -p linux
    3. Follow this instructions:
        https://wiki.archlinux.org/index.php/Poulsbo#FBDEV_Driver_.28xf86-video-fbdev.29
        to install and configure fbdev driver


EOF
}

post_remove() {
	echo "Don't forget to remove psb_gfx from MODULES in /etc/mkinitcpio.conf"
}
