post_install() {
		echo "To get started, run cindex with a list of directories to index:"
		echo
		echo "    cindex /usr/include $HOME/src"
		echo
		echo "Then run csearch to run grep over all the indexed sources:"
		echo
		echo "    csearch DATAKIT"
	    echo
	    echo "For details, run either command with the -help option, and"
	    echo "read http://swtch.com/~rsc/regexp/regexp4.html."
}

post_upgrade() {
		post_install
}
