pre_install() {
  /bin/true
}


post_install() {

echo -e "==================================\n\n\n"
echo "use it at own risk!!!"
echo -e "\n\n\n=================================="

}


pre_upgrade() {
   /bin/true
}


post_upgrade() {
echo -e "==================================\n\n\n"
echo "use it at own risk!!!"
echo -e "\n\n\n=================================="


}


pre_remove() {
   /bin/true
}


post_remove() {
   /bin/true
}


op=$1
shift
$op $*
