#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

stat_busy "Recompiling psmouse kernel module"
cp -r /usr/src/psmouse-elantech /tmp/.psmouse-elantech
cd /tmp/.psmouse-elantech
make -C /usr/src/linux-`uname -r`/ M=`pwd` psmouse.ko &&
gzip -9 < psmouse.ko > psmouse.ko.gz &&
install -D -m 0644 psmouse.ko.gz /lib/modules/`uname -r`/updates/drivers/input/mouse/psmouse.ko.gz &&
rm -r /tmp/.psmouse-elantech &&
stat_done || stat_fail

stat_busy "Running depmod now"
depmod -a && stat_done || stat_fail

printhl "Do not panic if mouse cursor does not move for a second"
stat_busy "Reloading psmouse kernel module"
modprobe -r psmouse && sleep 0.5 && modprobe psmouse && stat_done || stat_fail
