post_install() {
    echo "Please use systemd units to start/stop smartladder:"
    echo "sudo systemctl start/stop smartladder"

    chown -R nobody:daemon /usr/share/smartladder/goagent+
}

post_upgrade() {
    post_install
}

pre_upgrade() {
    rm -rf /opt/smartladder/goagent+/certs
    rm -rf /usr/share/smartladder/goagent+/certs
}

pre_remove() {
    rm -rf /opt/smartladder/goagent+/certs
    rm -rf /usr/share/smartladder/goagent+/certs
}
