post_install() {
  echo -e ""
  echo -e ">> Don't forget to source colemak.vim in your ~/.vimrc"
  echo -e ">> echo 'source /usr/share/vim/vimfiles/keymap/colemak.vim' >> ~/.vimrc"
}

post_upgrade() {
  echo -e ""
  echo -e ">> New path for colemak.vim"
  echo -e ">> echo 'source /usr/share/vim/vimfiles/keymap/colemak.vim' >> ~/.vimrc"
}

post_remove() {
  echo -e ""
  echo -e "Don't forget to delete the 'source colemak.vim' line from your ~/.vimrc" 
}

# vim:set ts=2 sw=2 et:
