#!/bin/bash

export NODE_PATH=/opt/cloud9/server:/opt/cloud9/support/connect/lib:/opt/cloud9/support/asyncjs/lib:/opt/cloud9/support/jsdav/lib:/opt/cloud9/support/jsdav/support:/opt/cloud9/support/jsdav/support/jsftp:/opt/cloud9/support/jsdav/support/node-sftp/lib:/opt/cloud9/support/socket.io/lib:/opt/cloud9/support/socket.io-client/lib:/opt/cloud9/support/uglify-js:/opt/cloud9/support/ace/lib:/opt/cloud9/support/ace/support/pilot/lib:/opt/cloud9/support/lib-v8debug/lib:/opt/cloud9/support:/opt/cloud9/demo/plugin:/opt/cloud9/demo/template:$NODE_PATH

node /opt/cloud9/bin/cloud9.js

