pkgname=kernel26-natty-git
kernver=2.6.38-natty-git+

post_install () {
	echo ">"
	echo "> Generating initramfs, using mkinitcpio.  Please wait..."
	echo ">"
	/sbin/mkinitcpio -p $pkgname

	echo ">"
	echo "> Updating module dependencies. Please wait ..."
	depmod $kernver
	if [[ -f /var/lib/ureadahead/pack ]]; then 
		rm /var/lib/ureadahead/pack
		echo "> ureadahead will be reprofiled at the next boot"
	fi
}

post_upgrade() {
	post_install
}

post_remove() {
	rm -f -- "/boot/$pkgname.img"
}
