diff --git a/src/Makefile.in b/src/Makefile.in
index 664523f..1675f0c 100644
--- a/src/Makefile.in
+++ b/src/Makefile.in
@@ -1,9 +1,16 @@
 name=bdsim
 G4TARGET=$(name)
 G4EXLIB=true
-
+ifndef G4TMP
+  G4TMP=@BINDIR@/tmp
+endif
+ifndef G4LIBDIR
+  G4LIBDIR=@G4LIBDIR@
+endif
 G4WORKDIR=@BINDIR@
-G4INSTALL=@G4INSTALL@
+ifndef G4INSTALL
+  G4INSTALL=@G4INSTALL@
+endif
 ROOTSYS=@ROOTSYS@
 G4VERSION=@G4VERSION@
 G4MINORVERSION=@G4MINORVERSION@
@@ -53,16 +61,18 @@ LDLIBS3 += $(ROOTLIBS)
 
 # standard Geant4 make procedure
 include $(G4INSTALL)/config/binmake.gmk
+include $(G4INSTALL)/config/architecture.gmk
 
 
 CPPFLAGS += -DG4VERSION=$(G4VERSION) -DG4MINORVERSION=$(G4MINORVERSION) 
 CPPFLAGS += @USE_ROOT@ -DCLHEP_VERSION=@CLHEP_VERSION@ 
 CPPFLAGS += -I./parser
+CPPFLAGS += -I./include
 CPPFLAGS += $(ROOTCFLAGS) 
 CPPFLAGS += @USE_GDML@ @USE_LCDD@ @LCDD_CFLAGS@ 
-CPPFLAGS += -g -Wall -Wno-non-virtual-dtor -I.
+CPPFLAGS += -g -Wno-non-virtual-dtor -I.
 
-LDFLAGS += -L$(G4LIBDIR) -L./parser -lgmad @LCDD_LIBS@
+LDFLAGS += -L./parser -lgmad @LCDD_LIBS@ -L$(G4LIB)
 
 ifeq ($(G4SYSTEM),Darwin-g++)
 OGLLIBS=@OGLLIBS@