# Generated by gem2arch
# Maintainer: LeeF
# Contributor: Christian Neukirchen <chneukirchen@gmail.com>

_gemname=rack
pkgname=ruby-enterprise-rack-101
pkgver=1.0.1
pkgrel=4
pkgdesc="a modular Ruby webserver interface"
arch=('i686' 'x86_64')
url="http://rack.rubyforge.org"
license=('MIT')
depends=('ruby-enterprise')
makedepends=('ruby-enterprise')
provides=('ruby-enterprise-rack')
source=(http://gems.rubyforge.org/gems/$_gemname-$pkgver.gem ruby-enterprise-rack.install)
install=ruby-enterprise-rack.install
noextract=($_gemname-$pkgver.gem)
md5sums=('22268803c9b8b785ed30fcee5bce3ce7'
		'd9e0f15cfe65a87108d4a0f80f67d029')

build() {
  cd $srcdir
  local _gemdir=`ruby -rubygems -e'puts Gem.default_dir'`
  gem install --ignore-dependencies --no-rdoc --no-ri -i "$pkgdir$_gemdir" $_gemname-$pkgver.gem
}
