# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: kusakata <shohei atmark kusakata period com>

_gemname=temple
pkgname=ruby-$_gemname
pkgver=0.6.7
pkgrel=1
pkgdesc='Template compilation framework in Ruby'
arch=(any)
url='https://github.com/judofyr/temple'
license=(MIT)
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('a0ef4798547acc4a5c0f4081c3a85f891a8421fa')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
