#!/bin/sh

# Please note that Sublime Text 2 for some reason opens an empty instance
# if the project you're trying to open is already open in another instance,
# instead of just giving it focus.

BIN=/opt/sublime-text-dev/sublime_text

${BIN} "${@}" &
