
post_install() {
    echo ">>> You must read and agree to the terms in the EULAs found"
    echo ">>> in /usr/share/licenses/Strife/ before using this software!"
    echo ">>>"
    echo ">>> In order to play Strife, add your user to the 'games' group."
    echo ">>> # gpasswd -a USERNAME games"
    echo ">>> Remember to logout and log back in for the changes to take effect."
}

post_upgrade() {
    post_install $1
}
