post_install() {
  PYVER=`python -V 2>&1 | \
        sed 's/Python[[:space:]]\+\([0-9]\+\.[0-9]\+\).*/\1/'`
  echo "Byte-compiling Python modules.."
  python /usr/lib/python$PYVER/compileall.py 2>/dev/null 1>&2
  echo "Done."
}

post_upgrade() {
  PYVER=`python -V 2>&1 | \
        sed 's/Python[[:space:]]\+\([0-9]\+\.[0-9]\+\).*/\1/'`
  echo "Byte-compiling Python modules.."
  python /usr/lib/python$PYVER/compileall.py 2>/dev/null 1>&2
  echo "Done."
}

op=$1 
shift 

$op $*
