# Maintainer:  Andrzej Giniewicz <gginiu@gmail.com>

pkgname=wacom-mainline-linux-git
pkgver=20120107
pkgrel=1
pkgdesc="Kernel drivers for Wacom tablets, mainline branch"
arch=('i686' 'x86_64')
url="http://linuxwacom.sourceforge.net/"
license=('GPL')
depends=('linux')
makedepends=('linux-headers')
options=('!libtool')
conflicts=('linuxwacom-cvs' 'input-wacom' 'input-wacom-cvs' 'linuxwacom-baboo-cth-ctl'
           'wacom-next-linux-git' 'wacom-linux-git')
install=wacom-mainline-linux-git.install

_gitrepo="linux/kernel/git/torvalds"
_gitname="linux.git"
_gitroot="git://git.kernel.org/pub/scm/$_gitrepo/$_gitname"

function _get_source() {
  _dir=$1
  _file=$2
  msg "Downloading $_dir/$_file"
  wget -q "http://git.kernel.org/?p=$_gitrepo/$_gitname;a=blob_plain;f=drivers/$_dir/$_file;hb=HEAD" -O $_file
}

build() {
  cd "$srcdir"
  _get_source "input/tablet" "wacom.h"
  _get_source "input/tablet" "wacom_wac.h"
  _get_source "input/tablet" "wacom_wac.c"
  _get_source "input/tablet" "wacom_sys.c"
  _get_source "input/touchscreen" "wacom_w8001.c"
#  _get_source "hid" "hid-core.c"
#  _get_source "hid" "hid-input.c"
#  _get_source "hid" "hidraw.c"
#  _get_source "hid" "hid-debug.c"
#  _get_source "hid" "hid-ids.h"
#  _get_source "hid" "hid-wacom.c"

  echo "# generated by PKGBUILD" > Makefile
#  echo "hid-y := hid-core.o hid-input.o hidraw.o" >> Makefile
#  echo "hid-objs := hid-debug.o" >> Makefile
  echo "wacom-objs := wacom_sys.o wacom_wac.o" >> Makefile
#  echo "obj-m += hid.o" >> Makefile
#  echo "obj-m += hid-wacom.o" >> Makefile
  echo "obj-m += wacom.o" >> Makefile
  echo "obj-m += wacom_w8001.o" >> Makefile
  make -C /lib/modules/$(uname -r)/build SUBDIRS="$(pwd)" modules
}

function _install_module() {
  rm -rf "$1.ko.gz"
  gzip -9 "$1.ko"
  install -D -m 644 "$1.ko.gz" "${pkgdir}"/lib/modules/$(uname -r)/updates/"$1.ko.gz"
}

package() {
#  _install_module "hid"
#  _install_module "hid-wacom"
  _install_module "wacom"
  _install_module "wacom_w8001"
}

