<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='en' lang='en'>
<head>
<title>svntogit/community.git - Git clone of the 'community' subversion repository</title>
<meta name='generator' content='cgit v0.8.3.4-124-ge7dc'/>
<meta name='robots' content='index, nofollow'/>
<link rel='stylesheet' type='text/css' href='/cgit.css'/>
<link rel='alternate' title='Atom feed' href='http://projects.archlinux.org/svntogit/community.git/atom/pragha/trunk/pragha.install?h=master' type='application/atom+xml'/>
<link rel="stylesheet" href="/archnavbar.css" />
<link rel="icon" href="/favicon.ico" type="image/x-icon" />
<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
</head>
<body>
	<div id="archnavbar"><!-- Arch Linux global navigation bar -->
		<div id="archnavbarlogo">
			<p><a href="http://www.archlinux.org/" title="Arch news, packages, projects and more"></a></p>
		</div>
		<div id="archnavbarmenu">
			<ul id="archnavbarlist">
				<li id="anb-home"><a href="http://www.archlinux.org/" title="Arch news, packages, projects and more">Home</a></li>
				<li id="anb-packages"><a href="http://www.archlinux.org/packages/" title="Arch Package Database">Packages</a></li>
				<li id="anb-forums"><a href="http://bbs.archlinux.org/" title="Community forums">Forums</a></li>
				<li id="anb-wiki"><a href="http://wiki.archlinux.org/" title="Community documentation">Wiki</a></li>
				<li id="anb-bugs"><a href="http://bugs.archlinux.org/" title="Report and follow bugs">Bugs</a></li>
				<li id="anb-aur"><a href="http://aur.archlinux.org/" title="Arch Linux User Repository">AUR</a></li>
				<li id="anb-download"><a href="http://www.archlinux.org/download/" title="Get Arch Linux">Download</a></li>
			</ul>
		</div>
	</div><!-- #archnavbar -->
<div id='cgit'><table id='header'>
<tr>
<td class='main'><a href='/'>index</a> : <a title='svntogit/community.git' href='/svntogit/community.git/'>svntogit/community.git</a></td><td class='form'><form method='get' action=''>
<select name='h' onchange='this.form.submit();'>
<option value='master' selected='selected'>master</option>
</select> <input type='submit' name='' value='switch'/></form></td></tr>
<tr><td class='sub'>Git clone of the 'community' subversion repository</td><td class='sub right'>Arch Linux Trusted Users</td></tr></table>
<table class='tabs'><tr><td>
<a href='/svntogit/community.git/'>summary</a><a href='/svntogit/community.git/refs/'>refs</a><a href='/svntogit/community.git/log/pragha/trunk/pragha.install'>log</a><a class='active' href='/svntogit/community.git/tree/pragha/trunk/pragha.install'>tree</a><a href='/svntogit/community.git/commit/pragha/trunk/pragha.install'>commit</a><a href='/svntogit/community.git/diff/pragha/trunk/pragha.install'>diff</a><a href='/svntogit/community.git/stats/pragha/trunk/pragha.install'>stats</a></td><td class='form'><form class='right' method='get' action='/svntogit/community.git/log/pragha/trunk/pragha.install'>
<select name='qt'>
<option value='grep'>log msg</option>
<option value='author'>author</option>
<option value='committer'>committer</option>
<option value='range'>range</option>
</select>
<input class='txt' type='text' size='10' name='q' value=''/>
<input type='submit' value='search'/>
</form>
</td></tr></table>
<div class='path'>path: <a href='/svntogit/community.git/tree/'>root</a>/<a href='/svntogit/community.git/tree/pragha'>pragha</a>/<a href='/svntogit/community.git/tree/pragha/trunk'>trunk</a>/<a href='/svntogit/community.git/tree/pragha/trunk/pragha.install'>pragha.install</a></div><div class='content'>blob: 7db3520363f462a336c1c9ed1a0ea05810865bc2 (<a href='/svntogit/community.git/plain/pragha/trunk/pragha.install'>plain</a>)
<table summary='blob content' class='blob'>
<tr><td class='linenumbers'><pre><a class='no' id='n1' name='n1' href='#n1'>1</a>
<a class='no' id='n2' name='n2' href='#n2'>2</a>
<a class='no' id='n3' name='n3' href='#n3'>3</a>
<a class='no' id='n4' name='n4' href='#n4'>4</a>
<a class='no' id='n5' name='n5' href='#n5'>5</a>
<a class='no' id='n6' name='n6' href='#n6'>6</a>
<a class='no' id='n7' name='n7' href='#n7'>7</a>
<a class='no' id='n8' name='n8' href='#n8'>8</a>
</pre></td>
<td class='lines'><pre><code>post_install<span class="hl opt">() {</span>
 gtk<span class="hl opt">-</span>update<span class="hl opt">-</span>icon<span class="hl opt">-</span>cache <span class="hl opt">-</span>q <span class="hl opt">-</span>f <span class="hl opt">-</span>t usr<span class="hl opt">/</span>share<span class="hl opt">/</span>icons<span class="hl opt">/</span>hicolor
<span class="hl opt">}</span>

post_remove<span class="hl opt">() {</span>
 gtk<span class="hl opt">-</span>update<span class="hl opt">-</span>icon<span class="hl opt">-</span>cache <span class="hl opt">-</span>q <span class="hl opt">-</span>f <span class="hl opt">-</span>t usr<span class="hl opt">/</span>share<span class="hl opt">/</span>icons<span class="hl opt">/</span>hicolor
<span class="hl opt">}</span>
 
</code></pre></td></tr></table>
</div> <!-- class=content -->
</div>
<div class="foot" style="padding-left:1em;padding-right:1em;">
<p>Copyright &copy; 2002-2010 <a href="mailto:jvinet@zeroflux.org"
title="contact Judd Vinet">Judd Vinet</a> and <a href="mailto:aaron@archlinux.org"
title="contact Aaron Griffin">Aaron Griffin</a>. The Arch Linux name and logo
are recognized trademarks. Some rights reserved. The registered trademark
Linux&copy; is used pursuant to a sublicense from LMI, the exclusive licensee
of Linus Torvalds, owner of the mark on a world-wide basis.</p>
</div>
</div> <!-- id=cgit -->
</body>
</html>
