#!/bin/sh

post_install(){
    echo Adding eduroam to active list...
    if grep eduroam-rub /etc/wicd/encryption/templates/active > /dev/null 
    then
        echo Eduroam was already installed!
    else
        echo eduroam-rub >> /etc/wicd/encryption/templates/active && echo Eduroam added to active list
    fi
}
post_remove(){
    echo -n Deleting eduroam from active list...
    sed -e '/^eduroam-rub$/d' -i /etc/wicd/encryption/templates/active
    echo ' [DONE]'
}

post_remove

