post_install() {
	# lpr
	/usr/local/Brother/Printer/dcpj315w/inf/setupPrintcapij dcpj315w -i
	
	# cupswrapper
	/usr/local/Brother/Printer/dcpj315w/cupswrapper/cupswrapperdcpj315w
	
	/etc/rc.d/cups restart
}

post_upgrade() {
	/bin/true
}

pre_remove() {
	# lpr
	/usr/local/Brother/Printer/dcpj315w/inf/setupPrintcapij dcpj315w -e
	
	# cupswrapper
	/usr/local/Brother/Printer/dcpj315w/cupswrapper/cupswrapperdcpj315w -e
}

op=$1
shift

$op "$@"

