
post_install() {
	
	echo "----------------------------------------------------------"
	echo "To be able to play, save configs, and update the client,"
	echo "add your user to the games group:"
	echo " # gpasswd -a USERNAME games"

	echo ""

	echo "To fix startup black screen:"
	echo " # killall cosmic & rm /opt/cosmicbreak-jp/programs/option3.ser"
	echo "----------------------------------------------------------"

}
