post_install() {
  echo '>>> Rebuilding module dependencies...'
  depmod -a
  echo '>>> Done.'
  echo
  echo '>>> To prevent conflicts with the other Realtek'
  echo '>>> driver, blacklist or remove the r8169 driver.'
}

post_upgrade() {
  echo '>>> Rebuilding module dependencies...'
  depmod -a
  echo '>>> Done.'
}

post_remove() {
  echo '>>> Rebuilding module dependencies...'
  depmod -a
  echo '>>> Done.'
}
