post_install() {
  echo -e "\033[0;31m IMPORTANT"
  echo -e "\033[0;0m  You need to register for a \033[0;32mForvo API key\033[0;0m and copy it into your forvocl \033[0;32m'config.yml'\033[0;0m file before first run."
  echo

  # Following is Simplified Chinese translation.
  echo -e "\033[0;31m 安装完毕后重要步骤"
  echo -e "\033[0;0m  首次使用前你需要注册一个 \033[0;32mForvo API key\033[0;0m 并粘贴到你的 forvocl \033[0;32m'config.yml'\033[0;0m 文件中。"
  echo
}

