#Automatically generated by pip2arch on 2012-06-20

pkgname=motmot.imops
pkgver=0.5.7
pkgrel=1
pkgdesc="image format conversion (e.g. between MONO8, YUV422, and RGB)"
url="http://code.astraw.com/projects/motmot/imops.html"
depends=('python2' )
makedepends=('python2-distribute' )
license=('BSD')
arch=('any')
source=('http://pypi.python.org/packages/source/m/motmot.imops/motmot.imops-0.5.7.zip')
md5sums=('66213aef9011bed2efbb74e86e625b39')

build() {
    cd $srcdir/motmot.imops-0.5.7
    python2 setup.py build
}

package() {
    cd $srcdir/motmot.imops-0.5.7
    python2 setup.py install --root="$pkgdir" --optimize=1 
}
