# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=github_api
pkgname=ruby-$_gemname-0.10.1
pkgver=0.10.1
pkgrel=3
pkgdesc='Ruby wrapper for the GitHub API v3'
arch=(any)
url='https://github.com/peter-murach/github'
license=(MIT)
depends=(ruby ruby-addressable ruby-hashie ruby-faraday-0.8 ruby-multi_json ruby-oauth2 ruby-nokogiri-1.5)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('d8da2a85d09da9f343d67ac5066798f3bc8bd173')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE.txt" "$pkgdir/usr/share/licenses/$pkgname/LICENSE.txt"
}
