post_install()
{
	echo "Set greeter-session=light-webkit-greeter in /etc/lightdm/lightdm.conf"
	echo "Also set webkit-theme=userdock in /etc/lightdm/lightdm-webkit-greeter.conf"
	echo "See https://wiki.archlinux.org/index.php/LightDM#Testing on how to test greeters"

	echo "Please note that this theme doesn't support choosing the session at login,"
	echo "and must be changed in /etc/lightdm/lightdm.conf user-session=SESSION"
}

