post_install() {
  chmod 755 /opt/smartgithg-ea/bin/smartgithg.sh
  ln -s /opt/smartgithg-ea/bin/smartgithg.sh /usr/bin/smartgithg-ea

  echo "update desktop mime database..."
  update-desktop-database
  gtk-update-icon-cache -f /usr/share/icons/hicolor/
}

post_upgrade() {
	gtk-update-icon-cache -f /usr/share/icons/hicolor/
}

post_remove() {
  rm -rf /opt/smartgithg-ea
  unlink /usr/bin/smartgithg-ea
  update-desktop-database
  gtk-update-icon-cache -f /usr/share/icons/hicolor/
}
