TRANSPAC_USER=transpac
TRANSPAC_UID=557
TRANSPAC_GROUP=transpac
TRANSPAC_HOME=/var/lib/transpac
TRANSPAC_CACHE=/var/cache/transpac

post_install() {
	if [ -z $(getent passwd $TRANSPAC_USER) ] ; then
		groupadd $TRANSPAC_GROUP
		useradd -u $TRANSPAC_UID -g $TRANSPAC_GROUP -d $TRANSPAC_HOME -s /bin/false $TRANSPAC_USER
	fi

	mkdir -p $TRANSPAC_CACHE
	chown $TRANSPAC_USER:$TRANSPAC_GROUP $TRANSPAC_CACHE
}

post_remove() {
	userdel $TRANSPAC_USER &>/dev/null
}