#!/bin/sh
cd /opt/oilrush/

# Resolution...
width=1024
height=768
resolution=$(xrandr -q | grep '*' | grep -o "[0-9]*x[0-9]*")
if [ -n "$resolution" ]; then
        width=$(echo "$resolution" | cut -d'x' -f1)
        height=$(echo "$resolution" | cut -d'x' -f2)
fi

export LD_LIBRARY_PATH=./bin:$LD_LIBRARY_PATH
unset LIBGL_ALWAYS_INDIRECT
./bin/OilRush_x86d	-video_app opengl \
					-sound_app openal \
					-extern_plugin Network \
					-data_path ../ \
					-engine_config ../oilrush-version.cfg \
					-system_script waterwar/unigine.cpp \
					-console_command "world_load waterwar/menu" \
					-video_multisample 0 \
					-video_fullscreen 1 \
					-video_mode -1 \
					-video_width $width \
					-video_height $height
