--- Makefile.old	2012-03-05 20:43:12.950155611 -0800
+++ Makefile	2012-03-05 20:43:03.823977359 -0800
@@ -37,12 +37,12 @@
 
 # Defaults
 ifeq ($(OS), Darwin)
-	cxxflags_default = -c -O2 -DNDEBUG
+	cxxflags_default = -O2 -DNDEBUG
 else
-	cxxflags_default = -c -O2 -DNDEBUG
+	cxxflags_default = -O2 -DNDEBUG
 endif
-cxxflags_small   = -c 
-cxxflags_debug   = -c -g
+cxxflags_small   = 
+cxxflags_debug   = -g
 cxxflags_shared  = -f$(PIC)
 libname          = libwebsocketpp
 libname_hdr      = websocketpp
@@ -135,17 +135,18 @@
 
 # Compile object files
 $(objdir)/sha1.o: $(srcdir)/sha1/sha1.cpp
-	$(CXX) $< -o $@ $(CXXFLAGS)
+	$(CXX) $< -o $@ -c $(CXXFLAGS)
 	
 $(objdir)/base64.o: $(srcdir)/base64/base64.cpp
-	$(CXX) $< -o $@ $(CXXFLAGS)
+	$(CXX) $< -o $@ -c $(CXXFLAGS)
 
 $(objdir)/%.o: $(srcdir)/%.cpp
-	$(CXX) $< -o $@ $(CXXFLAGS)
+	$(CXX) $< -o $@ -c $(CXXFLAGS)
 
 ifeq ($(SHARED),1)
 install: banner install_headers $(lib_target)
 	@echo "Install shared library"
+	mkdir -p $(inst_path)
 	cp -f ./$(lib_target) $(inst_path)
 	cd $(inst_path) ; \
 	ln -sf $(lib_target) $(libname_shared_major_version) ; \
@@ -157,6 +158,7 @@
 else
 install: banner install_headers $(lib_target)
 	@echo "Install static library"
+	mkdir -p $(inst_path)
 	cp -f ./$(lib_target) $(inst_path)
 	@echo "Install static library: Done."
 endif
