#!/bin/bash

post_install() {
	echo
	echo "Prezto is enabled for all users by default."
	echo "To change that, edit /etc/zsh/zshrc file."
	echo "Global settings reside in the /etc/zsh/ directory."
	echo "To personalize Zsh and Prezto, edit your local ~/.zshrc and ~/.zpreztorc files."
	echo "A user can also have a custom, overriding Prezto installation in ~/.zprezto/"
	echo
}
