post_install() {
  cat << EOF
==>
==> In order to get documentation in scvim, execute:
==>   $ scvim_make_help -c -s /usr/share/Supercollider/Help
==> 
==> Then to read documentation from within scvim type
==>   :SChelp
==>
==> Also enable syntax highlighting with
==>   :setfiletype supercollider
==>
EOF
}

post_upgrade() {
  post_install
}

post_remove() {
cat << EOF
==>
==> If you enabled documentation in scvim, now you can delete it from your user folder with
==> rm -rf ~/.scvim
==>
EOF
}
