post_install() {
  echo
  echo "-------------------------------------------------------------------------"
  echo "1. Include required schema files in slapd.conf:"
  echo "include /etc/openldap/schema/cosine.schema"
  echo "include /etc/openldap/schema/inetorgperson.schema"
  echo "include /etc/openldap/schema/openldap.schema"
  echo "include /etc/openldap/schema/nis.schema"
  echo "include /etc/openldap/schema/misc.schema"
  echo "include /etc/openldap/schema/fusiondirectory/trust.schema"
  echo "include /etc/openldap/schema/fusiondirectory/samba3.schema"
  echo "include /etc/openldap/schema/fusiondirectory/gosystem.schema"
  echo "include /etc/openldap/schema/fusiondirectory/gofon.schema"
  echo "include /etc/openldap/schema/fusiondirectory/goto.schema"
  echo "include /etc/openldap/schema/fusiondirectory/goto-mime.schema"
  echo "include /etc/openldap/schema/fusiondirectory/gosa-samba3.schema"
  echo "include /etc/openldap/schema/fusiondirectory/gofax.schema"
  echo "include /etc/openldap/schema/fusiondirectory/goserver.schema"
  echo
  echo "2. Configure suffix, rootdn and rootpw in slapd.conf"
  echo "3. put slapd into hosts.allow"
  echo "4. Start slapd"
  echo "-------------------------------------------------------------------------"
}