#!/bin/bash

if [ -e "/etc/rc.d/netfs" ]; then
	case "$2" in
		up)
			/etc/rc.d/groupvpn start
		;;
		vpn-up)
			/etc/rc.d/groupvpn start
		;;
		down)
			/etc/rc.d/groupvpn stop
		;;
		vpn-down)
			/etc/rc.d/groupvpn stop
		;;
	esac
fi
