post_install() {
  echo "You still need to install at least one vendor-specific implementation of
  OpenCL that matches your hardware (see the suggested packages). Note that 
  butterflow is using the libcl package as the provider of the OpenCL ICD 
  library and loader and that a driver is not supplied. For information on how 
  to satisfy this requirement, please read this Wiki page:
  https://wiki.archlinux.org/index.php/Opencl"
}
