# Generated by Xyne::Arch::CPAN 0.07

pkgname=perl-pdf-reuse
pkgver=0.35
pkgrel=3
pkgdesc="Reuse and mass produce PDF documents"
arch=('i686' 'x86_64')
url="http://search.cpan.org/dist/PDF-Reuse/"
license=('PerlArtistic' 'GPL')
source=('http://search.cpan.org/CPAN/authors/id/L/LA/LARSLUND/PDF-Reuse-0.35.tar.gz')
md5sums=('1e2541eacaf8df4f4012312f6c353688')
sha256sums=('bd6566d18b5d7dfc4c6c83abd7374df321db7e49b2cf6763ff7104d9285fa575')
depends=('perl-autoloader' 'perl-io-compress' 'perl-data-dumper' 'perl-digest-md5' 'perl-exporter' 'perl-font-ttf' 'perl-text-pdf')
provides=('perl-pdf-reuse-util')
options=(!emptydirs)

build() {
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Makefile.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor || return 1
    make  || return 1
    make install DESTDIR="${pkgdir}" || return 1

  else
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Build.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Build.PL INSTALLDIRS=vendor || return 1
    ./Build  || return 1
    ./Build install destdir=${pkgdir} || return 1

  else
    echo "error: failed to detect build method for $pkgname"
    echo "you may be able to fix this by editing the PKGBUILD"
    return 1
  fi fi

  # remove perllocal.pod and .packlist
  find ${pkgdir} -name perllocal.pod -delete
  find ${pkgdir} -name .packlist -delete
}

# vim:set ts=2 sw=2 et:

