
post_install() {
  update-desktop-database -q
  echo "******"
  echo "*"
  echo "* To add trackma-curses to your applications comment out or remove"
  echo "* 'NoDisplay=true' from trackma-curses.desktop"
  echo "*" 
  echo "* wMAL has been renamed to Trackma, be sure to move your config files" 
  echo "* from ~/.wmal to ~/.trackma and change any startup applications."
  echo "*" 
  echo "*" 
  echo "******"
}

post_upgrade() {
  post_install
}

post_remove() {
  update-desktop-database -q 
}
