update_help_tags() {
    echo -n "Updating vim help tags..."
    /usr/bin/vim --noplugins -u NONE -U NONE \
        --cmd ":helptags /usr/share/vim/vimfiles/doc" --cmd ":q" > /dev/null 2>&1
    echo "done."
}
post_install() {
    update_help_tags
    echo "
    To configure vimoutliner, copy
    /usr/share/vim/vimfiles/vimoutliner/vimoutlinerrc to
    ~/.vim/vimoutliner/vimoutlinerrc and edit"
}

post_upgrade() {
  update_help_tags
}

post_remove() {
  update_help_tags
}
