post_install() {
cat << EOM

-------------------------------------------------------------------------------------
Manual post-installation steps:
-------------------------------------------------------------------------------------
Read /usr/share/webapps/otrs/INSTALL.md
     /usr/share/webapps/otrs/README.database.md
     /usr/share/webapps/otrs/README.webserver.md
-------------------------------------------------------------------------------------
Extentions ITSM     is located /usr/share/webapps/otrs/extentions/itsm
Extentions Packages is located /usr/share/webapps/otrs/extentions/packages
-------------------------------------------------------------------------------------

EOM
}

pre_upgrade(){
  if [ ! -h /usr/share/webapps/otrs/Kernel/Config.pm ]
  then
    mkdir -p /etc/webapps/otrs
    cp /usr/share/webapps/otrs/Kernel/Config.pm /etc/webapps/otrs/Config.pm
    chown http:http -R /etc/webapps/otrs
  fi
}

post_upgrade() {
cat << EOM

-------------------------------------------------------------------------------------
Manual post-upgrade steps:
-------------------------------------------------------------------------------------
Read /usr/share/webapps/otrs/UPGRADING.md
-------------------------------------------------------------------------------------
Extentions ITSM     is located /usr/share/webapps/otrs/extentions/itsm
Extentions Packages is located /usr/share/webapps/otrs/extentions/packages
-------------------------------------------------------------------------------------

EOM
}
