post_install() {
cat << EOM

-------------------------------------------------------------------------------------
Manual post-installation steps:
-------------------------------------------------------------------------------------
Read /srv/http/otrs/INSTALL
     /srv/http/otrs/README.database
     /srv/http/otrs/README.webserver
-------------------------------------------------------------------------------------
Extentions ITSM     is located /srv/http/otrs/extentions/itsm
Extentions Packages is located /srv/http/otrs/extentions/packages
-------------------------------------------------------------------------------------

EOM
}

post_upgrade() {
cat << EOM

-------------------------------------------------------------------------------------
Manual post-upgrade steps:
-------------------------------------------------------------------------------------
Read /srv/http/otrs/UPGRADING
-------------------------------------------------------------------------------------
Extentions ITSM     is located /srv/http/otrs/extentions/itsm
Extentions Packages is located /srv/http/otrs/extentions/packages
-------------------------------------------------------------------------------------

EOM
}
