post_install() {
  echo "Manual post-installation steps:"
  echo "-------------------------------------------------------------------------------------"
  echo "Read /srv/http/otrs/INSTALL"
  echo "     /srv/http/otrs/README.database"
  echo "     /srv/http/otrs/README.webserver"
  echo "-------------------------------------------------------------------------------------"
  echo "Extentions is located /srv/http/otrs/extentions"
  echo "-------------------------------------------------------------------------------------"
}

post_upgrade() {
  echo "Manual post-upgrade steps:"
  echo "-------------------------------------------------------------------------------------"
  echo "Read /srv/http/otrs/UPGRADING"
  echo "-------------------------------------------------------------------------------------"
  echo "Extentions is located /srv/http/otrs/extentions"
  echo "-------------------------------------------------------------------------------------"
}
