pre_install() {
  mkdir -p /usr/share/pixmaps/pidgin/tray/backup/
  mv /usr/share/pixmaps/pidgin/tray/hicolor/16x16/ /usr/share/pixmaps/pidgin/tray/backup/
  mv /usr/share/pixmaps/pidgin/tray/hicolor/22x22/ /usr/share/pixmaps/pidgin/tray/backup/ 
}

post_install() {
  echo -ne "\nINFO: Pidgin's default tray icons are backed-up, they will be restored on this package' uninstall.\n\n"
}

post_remove() {
  mv /usr/share/pixmaps/pidgin/tray/backup/16x16/ /usr/share/pixmaps/pidgin/tray/hicolor/
  mv /usr/share/pixmaps/pidgin/tray/backup/22x22/ /usr/share/pixmaps/pidgin/tray/hicolor/
  
  rm -rf /usr/share/pixmaps/pidgin/tray/backup/
  echo -ne "\n\nINFO: Pidgin's default tray icons are restored.\n\n"
}

# vim:set ts=2 sw=2 et:
