post_install() { post_upgrade "${@}"; }

post_upgrade() {

    grep -qe '^HOOKS=.*rootaufs' /etc/mkinitcpio.conf || cat <<'MSG'
>>> Add hook to /etc/mkinitcpio.conf:
    > HOOKS="[...] rootaufs"
MSG

    cat <<'MSG'
>>> Run mkinitcpio to update your initramfs image
    # mkinitcpio -p linux

MSG

}


post_remove() {

    cat <<'MSG'

>>> Remove `rootaufs` from HOOKS in /etc/mkinitcpio.conf
>>> Run mkinitcpio to update your initramfs image (remove hook)
    # mkinitcpio -p linux

MSG

}
