post_install() {
	echo
	echo "Becareful, you must edit /etc/mailmotiond/mailmotiond.conf"
	echo

	# Create directories

	mkdir -p "$pkgdir/var/log/mailmotiond/"

	# Fixing right

	chmod 644 "$pkgdir/etc/mailmotiond/mailmotiond.conf"
	chmod 755 "$pkgdir/var/log/mailmotiond"
	chmod 755 "$pkgdir/usr/bin/mailmotiond"

	# Fixing membership

	chown vismais: "/var/log/mailmotiond"
	chown vismais: "/etc/mailmotiond/mailmotiond.conf"

	true
}

post_remove() {
	true
}
