post_install() {
  echo
  echo ' ======================================================'
  echo '  >> Warning: when putting a new TkPasMan into use,'
  echo '  >> be sure to UNencrypt your password file before,'
  echo '  >> because another SSL encoding might be configured.'
  echo ' ======================================================'
  echo
}

post_upgrade() {
  post_install $1
}

# vim:set ts=2 sw=2 et:
