function addhook_message {
    echo "Add 'chkboot' to the 'HOOKs' array in '/etc/mkinitcpio.conf' and make sure to"
    echo "place it as far right as possible at the end of the array. Once this has been"
    echo "done, the file saved and run 'mkinitcpio' to regenerate the images"
}

post_install() {
    addhook_message
}

post_upgrade() {
    if [ $(mkinitcpio -L | grep -o -c "chkboot") = 0 ]; then
        addhook_message
    fi
}
