# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=github_api
pkgname=ruby-$_gemname
pkgver=0.12.2
pkgrel=1
pkgdesc='Ruby wrapper for the GitHub API v3'
arch=(any)
url='http://peter-murach.github.io/github/'
license=(MIT)
depends=(ruby ruby-addressable ruby-hashie ruby-faraday ruby-multi_json ruby-oauth2 ruby-nokogiri ruby-descendants_tracker)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('b2a605f824fe2d7c2c4c65f65b6739419e736d5e')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE.txt" "$pkgdir/usr/share/licenses/$pkgname/LICENSE.txt"
}
