post_install() {
cat << EOF

==> To start hiawatha run the following as root :
    systemctl start hiawatha.service

==> To enable it on boot :
    systemctl enable hiawatha.service

==> If hiawatha fails to start, check the status of the unit with :
    systemctl status hiawatha.service

EOF
}
post_upgrade() {
cat << EOF

==> Before using the new service unit, it may be wise to issue the following :
    systemctl --system daemon-reload
EOF
post_install
}
