post_install() {
  echo ">> Place the 'hid-*' modules for your devices in MODULES= in /etc/rc.conf to enable them on system boot."
  echo ">> These modules needs to be recompiled for every kernel version upgrade."
  KERNEL_VERSION='3.7.10-1-ARCH'
  depmod $KERNEL_VERSION > /dev/null 2>&1
}

post_upgrade() {
  post_install
}

post_remove() {
  KERNEL_VERSION='3.7.10-1-ARCH'
  depmod $KERNEL_VERSION > /dev/null 2>&1
}

