# Contributor: DonVla <donvla@users.sourceforge.net>
# tile-windows install file

post_install() {
    cat << EOF

==>  If desired, run 'mkdir ~/.tile',
==>  'cp /etc/tile/wmprofiles /etc/tile/rc ~/.tile/' and edit the files
==>
==>  When run, if you do not want to use complete full screen, use the "-p" with one
==>  of the values from wmprofiles. also, use -m or -w for multi-desktop operation.
==>  
==>  Also check 'tile --help' or simply 'man tile'

EOF
}
