post_install () {
  echo "Note the fslint tools do a lot of inode access and to speed them up you can use the following method to not update access times on disk while gathering inode information:"
  echo "mount -o remount,noatime mountpoint"
  echo "fslint-gui"
  echo "mount -o remount,atime mountpoint"
  echo "Command Line Executables are installed in: /usr/share/fslint/fslint you may want to add them in your PATH, to run them without GUI."
}
