KERNEL_VERSION=2.6.31-ARCH

post_install() {
  depmod $KERNEL_VERSION
  rm -f usr/lib/xorg/modules/extensions/libdri.so
  ln -sf libdri.ati usr/lib/xorg/modules/extensions/libdri.so
  echo 'ef63bf6953f207b95a61f7eaf13ff0f9:d74d895c7ec23e896250c48bdc0fc8ced8568f2a7eb353f07a55ced2c70fc4:8b548b0d6bcb32da6d0494d8c25ac8c0d9518a5930c63fdb3e02c78c9207939c8b5b8a5f6b9435d86d0495d9c40c96c9d8028a5c3097638b3956c78c920b' > /etc/ati/signature
  echo "NOTE: You may need to use the tool 'aticonfig' to generate an xorg.conf file."
}

post_upgrade() {
  depmod $KERNEL_VERSION
  rm -f usr/lib/xorg/modules/extensions/libdri.so
  ln -sf libdri.ati usr/lib/xorg/modules/extensions/libdri.so
  echo 'ef63bf6953f207b95a61f7eaf13ff0f9:d74d895c7ec23e896250c48bdc0fc8ced8568f2a7eb353f07a55ced2c70fc4:8b548b0d6bcb32da6d0494d8c25ac8c0d9518a5930c63fdb3e02c78c9207939c8b5b8a5f6b9435d86d0495d9c40c96c9d8028a5c3097638b3956c78c920b' > /etc/ati/signature
}

post_remove() {
  depmod $KERNEL_VERSION
  # If the symlink is dead, remove it
  if [ ! -e usr/lib/xorg/modules/extensions/libdri.so ]; then
    rm -f usr/lib/xorg/modules/extensions/libdri.so
    ln -sf libdri.xorg usr/lib/xorg/modules/extensions/libdri.so
  fi
  echo "NOTE: Don't forget to recover your original xorg.conf file."
}
