# arg 1:  the new package version
post_install() {
  cat << EOM

--> To use mod_ecl, you only have to type into httpd.conf:
Include /etc/httpd/conf/extra/ecl_module.conf
--> To test the installation, restart Apache and create
--> a hello.lsp file into your htdoc folder containing:
(print "Hello world!")
--> Then open the link to the file in your browser.

EOM
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $1
}
