post_install() {
cat << EOF

>>> You'll need the original Shadow Warrior data files
>>> from either the shareware or full game version to play.

>>> Change to the directory where the game data is located, then
>>>  do 'install -m644 SW.GRP /usr/share/jfsw/sw.grp'
>>> and 'install -m644 SW.RTS /usr/share/jfsw/sw.rts'
>>> to copy the files and set proper permissions.

EOF
}

post_upgrade() {
post_install $1
}

op=$1
shift

$op $*
