PHPENV_VERSION=5.4.32

post_install() {
	export $(grep -o -P 'PHPENV_USER=(.*)' /etc/environment)
	ENV_DIR="/usr/lib/phpenv/versions/php${PHPENV_VERSION}"
	chown -R $PHPENV_USER:$PHPENV_USER $ENV_DIR
	su -s /bin/bash -l -c "/home/${PHPENV_USER}/.phpenv/bin/phpenv rehash" $PHPENV_USER
}

post_upgrade() {
	post_install
}

post_remove() {
	su -s /bin/bash -l -c "/home/${PHPENV_USER}/.phpenv/bin/phpenv rehash" $PHPENV_USER
}