pkgname=doublecmd-gtk2-bin-nightly

post_install() {
    case ${HOSTTYPE} in
        x86_64)
          ln -s /lib/libpcre.so.0 /lib/libpcre.so.3
          ;;
        esac
    # echo "Before using doublecmd, copy /opt/doublecmd/multiarc.ini to your HOME/.config/doublecmd/"
}

post_upgrade() {
    post_install $1
}

pre_remove() {
    case ${HOSTTYPE} in
        x86_64)
          rm /lib/libpcre.so.3
          ;;
        esac
}

