#!/bin/bash

# general config
. /etc/rc.conf
. /etc/rc.d/functions

PID=`cat /var/run/udhcpd.pid 2> /dev/null`

case "$1" in
  start)
    stat_busy "Starting udhcpd"
    [ -z "$PID" ] && /usr/sbin/udhcpd &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon udhcpd
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping udhcpd"
    [ ! -z "$PID" ] && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon udhcpd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
