 
post_install() {
   echo
   echo "  ###############################################################################################################"
   echo "  #          To enable speech go to Options/Sounds/Sound Files Folder/Browse -> /usr/share/scid/sounds          #"
   echo "  ###############################################################################################################"
   echo
}

post_upgrade() {
post_install $1
}