#Automatically generated by pip2arch on 2015-04-14

pkgname=python-crossbar
pkgver=0.10.4
pkgrel=1
pkgdesc="Crossbar.io - The Unified Application Router"
url="http://crossbar.io/"
depends=('python' )
makedepends=('python3' )
license=('GPL3')
arch=('any')
source=("https://pypi.python.org/packages/source/c/crossbar/crossbar-$pkgver.tar.gz")
md5sums=('af7bf2b91fd1dd4c390804662cc25a0e')

build() {
    cd $srcdir/crossbar-$pkgver
    python setup.py build
}

package() {
    cd $srcdir/crossbar-$pkgver
    python setup.py install --root="$pkgdir" --optimize=1
    rm $pkgdir/usr/{LICENSE,COPYRIGHT}
}
