pre_install() {
	/bin/true
}

post_install() {
	echo You need to perform the following step to complete installation:
	echo 1. In your MediaWiki \$IP/LocalSettings.php file add:
	#echo    \"require_once\(\"\$IP/extensions/Renameuser/Renameuser.php\"\)\;\"
	echo    \"require_once\(\"\$IP/extensions/Renameuser/SpecialRenameuser.php\"\)\;\"
	/bin/true
}

pre_upgrade() {
	/bin/true
}

post_upgrade() {
	/bin/true
}

pre_remove() {
	/bin/true
}

post_remove() {
	/bin/true
}
