# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=thrift
pkgname=ruby-$_gemname
pkgver=0.9.2.0
pkgrel=1
pkgdesc='Ruby bindings for Apache Thrift'
arch=(i686 x86_64)
url='http://thrift.apache.org'
license=('Apache 2.0')
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('f014a0a1df92dc09ad75f8bce17d8a73de800ca1')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"

  rm -rf "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/ext"
}
