post_install() {
	echo -e "Quickstart:"
	echo -e "\t1) Create a dir .snapshots in the subvol you want to be snapper'ed"
	echo -e "\t2) Copy /etc/snapper/config-templates/default to /etc/snapper/configs/<config-name> (e.g: root)"
	echo -e "\t3) Edit it and set the full path to the subvol, e.g. /mnt/rootfs/arch-root"
	echo -e "\t4) Add <config-name> to /etc/conf.d/snapper's SNAPPER_CONFIGS" 
	echo -e "\tNote: There is a default cronjob file in /etc/cron.hourly and cron.daily."
	echo -e "\tSet TIMELINE_CREATE=no in /etc/snapper/configs/<config-name> to disable automatic snapshots."
}
