post_upgrade() {
	post_install $1
}

post_install() {
   echo "The jre package is licensed software."
	echo "You MUST read and agree to the license stored in"
	echo "/opt/java5/jre/LICENSE before using it."

  echo 'add the following to your ~/.bashrc:'
  echo "alias usejava5='JAVA_HOME=/opt/java5; . /opt/java5/jre/bin/usejava.sh'"
  echo "alias usejava='JAVA_HOME=/opt/java; . /opt/java5/jre/bin/usejava.sh'"
}

