post_install() {
  echo "On multi-core/thread systems libf77blas.so and libstcblas.so are single-"
  echo "threaded, libptcblas.so and libptf77blas.so are multi-threaded. By default"
  echo "libcblas.so and libblas.so point to the multi-threaded versions."
  echo "The default can be changed by making libcblas.so and libblas.so* point to"
  echo "the single threaded libraries, i.e."
  echo "ln -sf libf77blas.so libblas.so; ln -sf libstcblas.so libcblas.so"
}
