post_install() {
	if ! getent group sddm > /dev/null; then
		groupadd --system sddm
	fi
	if ! getent passwd sddm > /dev/null; then
		useradd -c "Simple Desktop Display Manager" --system -d /var/lib/sddm -s /sbin/nologin -g sddm sddm
		passwd -l sddm > /dev/null
		chown -R sddm:sddm /var/lib/sddm > /dev/null
	fi
}

post_upgrade() {
	post_install $1
}

post_remove() {
	if getent passwd sddm >/dev/null; then
		userdel sddm
	fi
	if getent group sddm >/dev/null; then
		groupdel sddm
	fi
}
