post_install() {
cat << EOF

==> Remove nexus entry in rc.conf

==> To start nexus use this commands as root :
	systemctl start nexus.service

==> To enable it on boot :
	systemctl enable nexus.service

==> If nexus doesn't start, reload systemd with this command :
	systemctl --system daemon-reload

==> set environment variables, such as \$JAVA_HOME.
    edit conf file : /etc/conf.d/nexus

EOF
}
post_upgrade() {
	post_install
}
