--- SE/Makefile	2010-12-13 21:44:37.346667149 +0100
+++ SE/Makefile	2010-12-13 21:46:31.403333813 +0100
@@ -13,7 +13,7 @@
 #                                                                              *
 #******************************************************************************/
 
-PREFIX  =       /usr
+PREFIX  =       $(DESTDIR)/usr
 LIB	=	$(PREFIX)/lib/
 INCLUDE	=	$(PREFIX)/include/
 MAN3	=	$(PREFIX)/share/man/man3/
@@ -53,36 +53,20 @@
 	$(INSTALL) -c -m 644 eventcounter.h $(INCLUDE)
 	$(INSTALL) -c -m 644 seqev.h $(INCLUDE)
 	$(INSTALL) -c -m 644 Sequencer.3 $(MAN3)
-	-rm -f $(MAN3)/initSequencer.3
-	-rm -f $(MAN3)/rmSequencer.3
-	-rm -f $(MAN3)/Sticket.3
 	ln $(MAN3)/Sequencer.3 $(MAN3)/initSequencer.3
 	ln $(MAN3)/Sequencer.3 $(MAN3)/rmSequencer.3
 	ln $(MAN3)/Sequencer.3 $(MAN3)/Sticket.3
 	$(INSTALL) -c -m 644 Eventcounter.3 $(MAN3)
-	-rm -f $(MAN3)/initEventcounter.3
-	-rm -f $(MAN3)/rmEventcounter.3
-	-rm -f $(MAN3)/Eawait.3
-	-rm -f $(MAN3)/Eread.3
-	-rm -f $(MAN3)/Eadvance.3
 	ln $(MAN3)/Eventcounter.3 $(MAN3)/initEventcounter.3
 	ln $(MAN3)/Eventcounter.3 $(MAN3)/rmEventcounter.3
 	ln $(MAN3)/Eventcounter.3 $(MAN3)/Eawait.3
 	ln $(MAN3)/Eventcounter.3 $(MAN3)/Eread.3
 	ln $(MAN3)/Eventcounter.3 $(MAN3)/Eadvance.3
 	$(INSTALL) -c -m 644 sequencer.3 $(MAN3)
-	-rm -f $(MAN3)/create_sequencer.3
-	-rm -f $(MAN3)/rm_sequencer.3
-	-rm -f $(MAN3)/sticket.3
 	ln $(MAN3)/sequencer.3 $(MAN3)/create_sequencer.3
 	ln $(MAN3)/sequencer.3 $(MAN3)/rm_sequencer.3
 	ln $(MAN3)/sequencer.3 $(MAN3)/sticket.3
 	$(INSTALL) -c -m 644 eventcounter.3 $(MAN3)
-	-rm -f $(MAN3)/create_eventcounter.3
-	-rm -f $(MAN3)/rm_eventcounter.3
-	-rm -f $(MAN3)/eawait.3
-	-rm -f $(MAN3)/eread.3
-	-rm -f $(MAN3)/eadvance.3
 	ln $(MAN3)/eventcounter.3 $(MAN3)/create_eventcounter.3
 	ln $(MAN3)/eventcounter.3 $(MAN3)/rm_eventcounter.3
 	ln $(MAN3)/eventcounter.3 $(MAN3)/eawait.3
