## arg 1:  the new package version
post_install() {

cat <<EOF
>>> Do not forget to add "ROHC" to the 'module' entry of the 'service'
    section of your daemon configuration file /etc/opensand/daemon.conf.
EOF
}

## arg 1:  the old package version
post_remove() {

cat <<EOF
>>> Do not forget to remove "ROHC" from the 'module' entry of the 'service'
    section of your daemon configuration file /etc/opensand/daemon.conf.
EOF
}

# vim:set ts=2 sw=2 et:
