# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=resource_kit
pkgname=ruby-$_gemname
pkgver=0.1.1
pkgrel=1
pkgdesc='Resource Kit provides tools to aid in making API Clients. Such as URL resolving, Request / Response layer, and more.'
arch=(any)
url='https://github.com/digitaloceancloud/resource_kit'
license=(MIT)
depends=(ruby ruby-faraday ruby-addressable)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('5451b8c6175b73a17f19b6e54df6f23f7f556647')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE.txt" "$pkgdir/usr/share/licenses/$pkgname/LICENSE.txt"
}
