post_install() {
cat << EOF
==> To be able to save your setting and stats
==> and also to add more content (songs, characters, etc.),
==> add your user to the games group:
==> # gpasswd -a USERNAME games
==>
==> The root directory for StepMania is /opt/stepmania.
==> Please refer to the StepMania documentation to learn
==> about adding content to your StepMania installation.
EOF
}

pre_remove() {
  # delete old cache
  rm -rf /opt/stepmania/Cache
}

op=$1
shift

$op $*
