post_install() {
cat << EOF

To enable the System76 driver service at boot, run the following command as root:

systemctl enable system76.service

To manually start the service (without having to reboot), run the following command as root:

systemctl start system76.service


Before removing the System76 service, run the following commands as root:

systemctl stop system76.service
systemctl disable system76.service

EOF
}

post_upgrade() {
	post_install
}
