post_install() {
	useradd -d "/usr/lib/openqa" -G kvm openqa || :
	chown -R openqa /usr/lib/openqa || :
	chown -R openqa /var/lib/openqa/* || :
	chown -R openqa /var/cache/openqa/* || :
	echo "> Make sure to load mod_rewrite and get"
	echo "> apache to /etc/httpd/conf/extra/openqa.conf read"
}

post_upgrade() {
	chown -R openqa /usr/lib/openqa || :
	chown -R openqa /var/lib/openqa/* || :
	chown -R openqa /var/cache/openqa/* || :
}
