post_install() {
  printf " For this service to work correctly: the swap file will need the name-location of: /var/swapfile, and /dev/loop0 will need to be available.  To prevent warnings on boot of an unproperly initialized swap file be sure to comment or delete the swap file line in the fstab file.  To enable and start the service:" | fmt -c -w 80 -g 80
 printf " sudo systemctl enable loop-swapfile\n"
 printf " sudo systemctl start  loop-swapfile\n"
}

post_upgrade() {

post_install

}

