#!/usr/bin/env bash

if [[ -x '/opt/JDownloader' ]]; then
	umask u=rwx,g=rwx,o=rwx
	cd '/opt/JDownloader'
else
	mkdir -p "${HOME}/.jd"
	cd "${HOME}/.jd"
fi

if [ ! -f "JDownloader.jar" ]; then
	wget -O Updater.zip http://upd0.appwork.org/jcgi/JDownloader
	unzip -t -qq Updater.zip
	[ $? -eq 0 ] && unzip -o -qq Updater.zip
	rm -f Updater.zip
	[ -f "Updater.jar" ] && exec java -jar Updater.jar "$@"
else
	exec java -jar JDownloader.jar "$@"
fi
