post_install() {
  echo ">>> Updating module dependencies. Please wait ..."
  KERNEL_VERSION=$(uname -r)
  depmod -v $KERNEL_VERSION > /dev/null 2>&1
}

post_upgrade() {
  echo ">>> Updating module dependencies. Please wait ..."
  KERNEL_VERSION=$(uname -r)
  depmod -v $KERNEL_VERSION > /dev/null 2>&1
}

post_remove() {
  echo ">>> Updating module dependencies. Please wait ..."
  KERNEL_VERSION=$(uname -r)
  depmod -v $KERNEL_VERSION > /dev/null 2>&1
}

op=$1
shift
$op $*
