#!/bin/bash

diylcdir="$HOME/.diylc"
sharedir="/usr/share/diylc"

if [[ ! -d "$diylcdir" ]]; then
    mkdir -p "$diylcdir"/{templates,log,themes}
    cp "${sharedir}/config.xml" "$diylcdir"
    ln -s "${sharedir}/templates/"* "${diylcdir}/templates"
    ln -s "${sharedir}/themes/"* "${diylcdir}/themes"
    ln -s "${sharedir}"/{update.xml,diylc.l4j.ini} "$diylcdir"
fi

cd "$diylcdir"

"$JAVA_HOME/bin/java" \
    -Xms512m \
    -Xmx2048m \
    -Dorg.diylc.scriptRun=true \
    -jar "/usr/share/java/diylc/diylc.jar"
