#!/bin/bash
[ -f /etc/conf.d/verlihub ] && . /etc/conf.d/verlihub
. /etc/rc.conf
. /etc/rc.d/functions
PID=`pidof -o %PPID /usr/bin/verlihub`
case "$1" in
  start)
    stat_busy "Starting verlihub"
    if [ -z "$PID" ]; then
       /usr/bin/verlihub --start --quiet --background &>/dev/null &
      if [ $? -gt 0 ]; then
        stat_fail
        exit 1
      else
        sleep 1 # wait on children
        echo `pidof -o %PPID /usr/bin/verlihub` >/var/run/verlihub.pid
        add_daemon verlihub
        stat_done
      fi
    else
      stat_fail
      exit 1
    fi
    ;;

  stop)
    stat_busy "Stopping verlihub"
    if [ ! -z "$PID" ]; then
      kill $PID &> /dev/null      
      if [ $? -gt 0 ]; then
        stat_fail
        exit 1
      else
        rm -f /var/run/verlihub.pid &>/dev/null
        rm_daemon verlihub
        stat_done
      fi
    else
      stat_fail
      exit 1
    fi
    ;;

  restart)
    $0 stop
    sleep 3
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
