post_install() {
  cat << EOF
==> To set up Emacs to automatically edit files ending in .vert or .frag using
    glsl-mode add the following to your ~/.emacs file (GNU Emacs) or
    ~/.xemacs/init.el file (XEmacs):

    (autoload 'glsl-mode "glsl-mode" nil t)
    (add-to-list 'auto-mode-alist '("\\.vert\\'" . glsl-mode))
    (add-to-list 'auto-mode-alist '("\\.frag\\'" . glsl-mode))
EOF
}

post_upgrade() {
  post_install $1
}
