post_install(){
  useradd -g daemon -d /var/spool/newsd -s /bin/false news &>/dev/null
  chown -R news:daemon var/spool/newsd &>/dev/null
}

post_upgrade(){
  getent passwd news >/dev/null 2>&1 || useradd -g daemon -d /var/spool/newsd -s /bin/false news &>/dev/null
  chown -R news:daemon var/spool/newsd &>/dev/null
}

post_remove(){
  if getent passwd news >/dev/null 2>&1; then
    userdel news
  fi
}

