post_install() {
	echo ' > The CGI executable has been installed to'
	echo ' >   /usr/share/webapps/cqrlogo/cqrlogo.cgi'
	echo ' > and the FastCGI version is available as'
	echo ' >   /usr/share/webapps/cqrlogo/cqrlogo.fcgi'
	echo ' >'
	echo ' > You need to tell your webserver to execute'
	echo ' > the file on request. Example for apache:'
	echo ' >   <IfModule alias_module>'
	echo ' >     ScriptAlias /cqrlogo "/usr/share/webapps/cqrlogo/cqrlogo"'
	echo ' >   </IfModule>'
}
