# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Hugo Osvaldo Barrera <hugo@barrera.io>

_gemname=mail
pkgname=ruby-$_gemname-2.5.3
pkgver=2.5.3
pkgrel=1
pkgdesc='Mail provides a nice Ruby DSL for making, sending and reading emails.'
arch=(any)
url='http://github.com/mikel/mail'
license=()
depends=(ruby ruby-mime-types-1 ruby-treetop-1.4 ruby-i18n)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('0873049814d041071e4f26c7e3eb95af1573ceea')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
