_update_fc() {
	fc-cache -f > /dev/null
	mkfontscale /usr/share/fonts/TTF
	mkfontdir /usr/share/fonts/TTF
}

post_install() {
	echo -n "ecofont installed. Updating font cache... "
	_update_fc
	echo "done."
}

post_upgrade() {
	echo -n "ecofont upgraded. Updating font cache... "
	_update_fc
	echo "done."
}

post_remove() {
	echo -n "ecofont removed. Updating font cache... "
	_update_fc
	echo "done."
}
