#!/bin/sh

GCC_VERSION=4.1.2
INSTALL_PATH="/usr"

clean() {
    cd "$INSTALL_PATH/include/d/$GCC_VERSION/"
    rm -f object.d object.di std
    cd "$INSTALL_PATH/lib"
    rm -f libgphobos.a
}


case $1 in
tango)
    clean

    cd "$INSTALL_PATH/include/d/$GCC_VERSION/"
    ln -s object.di.tango object.di
    ln -s std.tango std

    cd "$INSTALL_PATH/lib"
    ln -s libgphobos.a.tango libgphobos.a
    ;;

phobos)
    clean

    cd "$INSTALL_PATH/include/d/$GCC_VERSION/"
    ln -s object.d.phobos object.d
    ln -s std.phobos std

    cd "$INSTALL_PATH/lib"
    ln -s libgphobos.a.phobos libgphobos.a
    ;;

status)
    cd "$INSTALL_PATH/include/d/$GCC_VERSION/"
    if [ -f object.d ]; then
        echo Phobos
    elif [ -f object.di ]; then
        echo Tango
    else
        echo Unknown
    fi
esac
