post_install() {
  getent group miserware &>/dev/null || groupadd -r miserware >/dev/null
  getent passwd granola &>/dev/null || useradd -s /sbin/nologin -g miserware -r granola >/dev/null

  chown granola /etc/granola.conf
  chown -R granola:miserware /var/lib/miserware
}

post_remove() {
  rm -fr /var/lib/miserware &>/dev/null
  getent passwd granola &>/dev/null && userdel granola >/dev/null
  getent group miserware &>/dev/null && groupdel miserware >/dev/null
}

# vim:set ts=2 sw=2 et:
