#!/bin/zsh

# Toggles Touchpad-power using synclient
#
# Author: Jonas Weber


CURRENTSETTING=`synclient | grep TouchpadOff | cut -d "=" -f 2`

if [[ $CURRENTSETTING = " 0" ]];
then
	synclient TouchpadOff=1
else
	synclient TouchpadOff=0
fi

