infodir=/usr/share/info
filelist=(wimpwm-ref.info)

post_install() {
  for file in ${filelist[@]}; do
    install-info $infodir/$file $infodir/dir 2> /dev/null
  done
  echo "Copy /usr/share/wimpwm/0.1.1/system.wimpwm to ~/.wimpwm"
  echo "and adjust it to your needs. Read wimpwm-ref.info for advice." 
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  for file in ${filelist[@]}; do
    install-info --delete $infodir/$file $infodir/dir 2> /dev/null
  done
}

# vim:set ts=2 sw=2 et:
