post_install() {
	echo "Shaarli has been installed under /usr/share/webapps/shaarli."
	echo "See Shaarli's official website for more informations."
	echo "You need a webserver able to serve php files, such as nginx or apache, in order to be able to use shaarli."
	echo "You can find an example configuration file for nginx under /etc/webapps/shaarli/ ."
	echo "Navigate to your shaarli's website URL in order to complete the installation."
}
