#!/bin/sh
DBHOST=$1
DBNAME=$2
USERNAME=$3
PASSWORD=$4

ZM_PATH_ZMS=/cgi-zm/nph-zms
ZM_PATH_SOCKS=/var/lib/zm/socks
ZM_PATH_LOGS=/var/log/zm
ZM_WEB_LIST_THUMBS=1
ZM_WEB_MONTAGE_WIDTH=320
ZM_WEB_MONTAGE_HEIGHT=240
ZM_OPT_CAMBOZOLA=1
ZM_OPT_MPEG=ffmpeg
ZM_PATH_FFMPEG=/usr/bin/ffmpeg
ZM_OPT_NETPBM=1
ZM_EXTRA_DEBUG_LOG=/var/log/zm/zm_debug.log
ZM_OPT_USE_AUTH=0

sql=/tmp/$$
echo "" >$sql
for n in ZM_PATH_ZMS ZM_PATH_SOCKS ZM_PATH_LOGS ZM_WEB_LIST_THUMBS ZM_WEB_MONTAGE_WIDTH ZM_WEB_MONTAGE_HEIGHT ZM_OPT_CAMBOZOLA ZM_OPT_MPEG ZM_PATH_FFMPEG ZM_OPT_NETPBM ZM_EXTRA_DEBUG_LOG ZM_OPT_USE_AUTH; do
	eval "val=\$$n"
	echo "UPDATE Config SET Value='$val' WHERE Name='$n';" >>$sql
done

cat $sql | mysql --user=$USERNAME --password=$PASSWORD --host=$DBHOST $DBNAME
rm -f $sql


exit 0
