--- ZoneMinder-1.24.0.orig/Makefile	2008-03-13 17:41:47.000000000 -0700
+++ ZoneMinder-1.24.0/Makefile	2008-03-15 06:21:22.000000000 -0700
@@ -687,8 +687,8 @@
 # Yes, you are correct. This is a HACK!
 install-data-hook:
 	( cd $(DESTDIR)$(sysconfdir); chown $(webuser):$(webgroup) $(sysconf_DATA); chmod 600 $(sysconf_DATA) )
-	-( if ! test -e $(RUNDIR); then mkdir $(RUNDIR); fi )
-	( if ! test -e $(ZM_RUNDIR); then mkdir $(ZM_RUNDIR); fi; chown $(webuser):$(webgroup) $(ZM_RUNDIR); chmod u+w $(ZM_RUNDIR) )
+	-( if ! test -e$(DESTDIR)$(RUNDIR); then mkdir -p $(DESTDIR)$(RUNDIR); fi )
+	( if ! test -e $(DESTDIR)$(ZM_RUNDIR); then mkdir -p $(DESTDIR)$(ZM_RUNDIR); fi; chown $(webuser):$(webgroup) $(DESTDIR)$(ZM_RUNDIR); chmod u+w $(DESTDIR)$(ZM_RUNDIR) )
 
 uninstall-hook:
 	@-( cd $(DESTDIR)$(webdir); rm -rf events graphics images sounds temp )
