#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/yaskkserv

PID=`pidof -o %PPID /usr/sbin/yaskkserv_$YASKKSERV_TYPE`
case "$1" in
  start)
    stat_busy "Starting yaskkserv"
    [ -z "$PID" ] && /bin/su nobody -s /bin/sh -c "/usr/sbin/yaskkserv_$YASKKSERV_TYPE $YASKKSERV_ARGS $YASKKSERV_JISYO"
    if [ $? -gt 0 ]; then
      stat_fail
    else
      echo $PID > /run/yaskkserv.pid
      add_daemon yaskkserv
      stat_done
    fi
	;;
  stop)
    stat_busy "Stopping yaskkserv"
    [ ! -z "$PID" ] && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm -f /run/yaskkserv.pid
      rm_daemon yaskkserv
      stat_done
    fi
	;;
  restart)
    $0 stop
    $0 start
	;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
