#!/bin/bash

set -e

. /etc/conf.d/yaskkserv

/bin/su - nobody -s /bin/sh -c "/usr/sbin/yaskkserv_$YASKKSERV_TYPE $YASKKSERV_ARGS $YASKKSERV_JISYO"
/usr/bin/pgrep -u nobody -xn yaskkserv_$YASKKSERV_TYPE > /run/yaskkserv.pid
