post_install() {
cd /usr/share/amsn2/amsn2/ui/front_ends/qt4/
sh ./generateFiles.sh

cat << _EOF
==> Installation notes:
==> amsn2 start with gtk interface. 
==> If you want any other available frontends 
==> ['web', 'qt4', 'gtk', 'curses'] 
==> you can launch 'amsn2 web' 'amsn2 qt4'
==> 'amsn2 gtk' 'amsn2 curses' rispectively

_EOF
     }

post_upgrade() {
     	post_install
	}

op=$1
shift
$op $*

