#!/bin/sh

PROFILEDIR=/etc/profile.d

rootcheck()
{
    if [ $UID != "0" ] ; then
	echo "ERROR: You cannot perform this operation unless you are root."
	exit
    fi
}

case "$1" in
    "help" | "" | "-h" | "--help")
	echo "Usage:"
	echo "qt-config --current"
	echo "This will show the currently active qt profile"
	echo
	echo "qt-config <qt profile name>"
	echo "Example: qt-config qt4"
	echo "This will change the profile to qt4"
	echo "Logout and login or run 'source /etc/profile' to apply changes"
	echo
	echo "Those of you who dont know what a profile is, please dont use this utility"
	;;

    "qt4")
	rootcheck
	if [ -e $PROFILEDIR/qt4.sh ] ; then 
	    chmod a-x $PROFILEDIR/qt*.sh 2> /dev/null
	    r1=$?
	    chmod a+x $PROFILEDIR/qt4.sh 2> /dev/null
	    if [ $? -gt 0 ] || [ $r1 -gt 0 ] ; then
		echo profile change failed
		exit 1
	    fi
	    echo "Profile changed to qt4"
	    echo "Logout and login or run 'source /etc/profile' to apply changes"

	else
	    echo "qt4 profile not found"
	    exit 1
	fi
	source $PROFILEDIR/qt4.sh
	;;
    
    "qt3")
	rootcheck
	if [ -e $PROFILEDIR/qt.sh ] ; then
	    chmod a-x $PROFILEDIR/qt*.sh 2> /dev/null
	    r1=$?
	    chmod a+x $PROFILEDIR/qt.sh 2> /dev/null
	    if [ $? -gt 0 ] || [ $r1 -gt 0 ] ; then
		echo profile change failed
		exit 1
	    fi
	    echo "Profile changed to qt3"
	    echo "Logout and login or run 'source /etc/profile' to apply changes"
	else
	    echo "qt3 profile not found"
	fi
	source $PROFILEDIR/qt.sh
	;;

    "--current")
	if [ -x $PROFILEDIR/qt.sh ] ; then
	    echo "qt3"
	fi
	if [ -x $PROFILEDIR/qt4.sh ] ; then
	    echo "qt4"
	fi
	;;
    
    *)
	echo "${1} profile not found"
	;;
esac

