signa(){
    #get rid of Testing use only watermark
    echo "9777c589791007f4aeef06c922ad54a2:ae59f5b9572136d99fdd36f0109d358fa643f2bd4a2644d9efbb4fe91a9f6590a145:f612f0b01f2565cd9bd834f8119b309bae11a1ed4a2661c49fdf3fad11986cc4f641f1ba1f2265909a8e34ff1699309bf211a7eb4d7662cd9f8e3faf14986d92f646f1bc" > etc/ati/signature
}

whisperer(){
    echo "----------------------------------------------------------------"
    echo "Add nomodeset to your kernel line in /boot/grub/menu.lst , ie.:"
    echo "kernel /boot/vmlinuz-linux root=/dev/sda1 ro nomodeset"
    echo "----------------------------------------------------------------"
    echo "You can use the tool 'aticonfig' to generate an xorg.conf file."
    echo "--------------------- ^^^^^^^^^ --------------------------------"
    echo "fglrx was added into /etc/modules-load.d/catalyst.conf"
    echo "----------------------------------------------------------------"
    echo "	atieventsd (needs acpid pkg) on systemd:"
    echo "systemctl enable atieventsd"
    echo "systemctl start atieventsd"
    echo "----------------------------------------------------------------"
    echo "For more info and troubleshooting visit:"
    echo "http://wiki.archlinux.org/index.php/ATI_Catalyst"
    echo "----------------------------------------------------------------"
    echo -e '\E[37;44m'"\033[1m----------------------------------------------------------------\033[0m"
    echo -e '\E[37;44m'"\033[1m				ATTENTION!\033[0m"
    echo -e '\E[37;44m'"\033[1m----------------------------------------------------------------\033[0m"
    echo "To enable 'automatic re-compilation while system shutdown/reboot' "
    echo "testing feature run these commands as root:"
    echo "systemctl enable catalyst-hook"
    echo "systemctl start catalyst-hook"
    echo ""
    echo "More info here:"
    echo "https://bbs.archlinux.org/viewtopic.php?pid=1255575#p1255575"
    echo -e '\E[37;44m'"\033[1m----------------------------------------------------------------\033[0m"
}

captain_hook(){
    # add hook fglrx to mkiniticpio
    hooks=$(grep ^HOOKS etc/mkinitcpio.conf | grep fglrx)
    if [ "$hooks" = "" ]; then
        sed 's/^HOOKS="\([^"]*\)"/HOOKS="\1 fglrx"/' -i etc/mkinitcpio.conf
    fi
}

post_install() {
    captain_hook
    usr/bin/catalyst_build_module ra
    usr/bin/catalyst_build_module all
    whisperer
#    signa
}

post_upgrade() {
    usr/bin/catalyst_build_module ra
    usr/bin/catalyst_build_module all
    whisperer
#    signa
}

pre_remove(){
    usr/bin/catalyst_build_module ra
}

post_remove() {
    # remove hook fglrx
    sed '/^HOOKS/s/ *fglrx//' -i etc/mkinitcpio.conf

    # remove log
    rm -f var/log/catalyst-install.log

    echo "----------------------------------------------------------------"
    echo " Don't forget to recover your original xorg.conf file."
    echo "----------------------------------------------------------------"
}
