#!/bin/bash

kernver=${KERNVER:-$(uname -r)}
arch=${ARCH:-$(uname -m)}
arch=${arch/i686/i386}

patch_files(){
    file_patch="${kernver/-*}.patch"
    if [[ -f "${file_patch}" ]]; then
        patch -Np5 -i ${file_patch} || return 1
    fi
}

install_module()
{
    workdir=$(mktemp -du /tmp/catalyst.XXXXXX)
    cp "/usr/share/ati/build_mod" "${workdir}" -R
    cd "$workdir"
    patch_files
    make -C /lib/modules/${kernver}/build  \
        SUBDIRS="`pwd`" ARCH=${arch} modules &>/dev/null || return 1

    install -m755 -d "/lib/modules/${kernver}/video/"
    install -m644 fglrx.ko "/lib/modules/${kernver}/video/" || return 1

    depmod ${kernver}
    rm -rf "${workdir}"
}

remove_module(){
    for p in /lib/modules/*; do
        rm "$p/video/fglrx.ko" &>/dev/null
        rmdir -p "$p/video/" --ignore-fail-on-non-empty &>/dev/null
        depmod $(basename $p)
    done
}

case "$1" in
    help|--help)
        echo "usage: $0 {version|remove}"
        echo "    With no version, it will use the current kernel version."
        ;;
    remove)
        remove_module
        ;;
    *)
        echo "Building fglrx module for ${kernver} ... "
        test "$1" != "" && kernver="$1"
        install_module && echo "Ok." || echo "Failed!!"
        ;;
esac

