post_install() {
	post_upgrade
}

post_upgrade() {
    su -l -s /bin/sh -c "source /opt/pyshell/pyshell" $USER
    #logo
    cat >&2 <<EOF

==> PyShell installation notes:
    ----------------------------------------
    type:
        >> source /opt/pyshell/pyshell
    ----------------------------------------

==> PyShell documentation:
    ----------------------------------------
    type:
        >> man pyshell
    ----------------------------------------
EOF
}
