post_install() {
cat << EOF
==> If you want to create your own designer plugins you will need
==> to create them with the same version that the integration was
==> built with. Qt must be configured with
==> '-qtnamespace QtCppIntegration -qtlibinfix CppIntegration'
==> as of Qt Eclipse Integration 1.5.1, to create custom
==> designer plugins.


==> It is highly recommended by us to start Eclipse once from the
==> command line with

==> eclipse -clean
EOF
}

post_upgrade() {
	post_install $1
}

