KERNEL_VERSION=2.6.36-hpmini

post_install() {
  echo -e ""
  echo -e ">> Updating module dependencies"
  depmod -a -v $KERNEL_VERSION > /dev/null 2>&1
  echo -e ">>"
  echo -e ">> If you don't need the headers you can remove it with:"
  echo -e ">> pacman -R kernel-hpmini-headers"
  echo -e ">>"
}

post_upgrade() {
  echo -e ""
  echo -e ">> Updating module dependencies"
  depmod -a -v $KERNEL_VERSION > /dev/null 2>&1
  echo -e ">>"
}

