# Generated by gem2arch-ruby-enterprise

_gemname=activesupport
pkgname=ruby-enterprise-$_gemname
pkgver=2.3.11
pkgrel=0
pkgdesc="Support and utility classes used by the Rails framework."
arch=('i686' 'x86_64')
url="http://www.rubyonrails.org"
license=('')
depends=('ruby-enterprise')
makedepends=('ruby-enterprise')
source=(http://gems.rubyforge.org/gems/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
md5sums=('713edf8f82c8b0dfa61fedb489626c75')

build() {
  cd $srcdir
  local _gemdir=`/opt/ruby-enterprise/bin/ruby -rubygems -e'puts Gem.default_dir'`
  /opt/ruby-enterprise/bin/gem install --ignore-dependencies --no-rdoc --no-ri  -i "$pkgdir$_gemdir" $_gemname-$pkgver.gem
}
