post_install() {
    EXTRAMODULES='extramodules-3.7-pae'
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
    echo 'You may need to reboot in order to use the nvidia module.'
}

post_upgrade() {
    EXTRAMODULES='extramodules-3.7-pae'
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
}

post_remove() {
    EXTRAMODULES='extramodules-3.7-pae'
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
}
