*** Makefile	2005-01-23 19:40:20.000000000 +0100
--- Makefile	2010-05-28 16:01:10.000000000 +0200
***************
*** 16,22 ****
  CXXFLAGS = -pipe -Wall -W -O2  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
  LEXFLAGS = 
  YACCFLAGS= -d
! INCPATH  = -I/usr/local/qt/mkspecs/default -I. -I$(QTDIR)/include -I.ui/ -I. -I.moc/
  LINK     = g++
  LFLAGS   =  -Wl,-rpath,$(QTDIR)/lib
  LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -L/usr/X11R6/lib -lqt-mt -lXext -lX11 -lm
--- 16,22 ----
  CXXFLAGS = -pipe -Wall -W -O2  -DQT_NO_DEBUG -DQT_SHARED -DQT_THREAD_SUPPORT
  LEXFLAGS = 
  YACCFLAGS= -d
! INCPATH  = -I/opt/qt/mkspecs/default -I. -I$(QTDIR)/include -I.ui/ -I. -I.moc/
  LINK     = g++
  LFLAGS   =  -Wl,-rpath,$(QTDIR)/lib
  LIBS     = $(SUBLIBS) -L$(QTDIR)/lib -L/usr/X11R6/lib -lqt-mt -lXext -lX11 -lm
***************
*** 107,113 ****
  $(MOC): 
  	( cd $(QTDIR)/src/moc && $(MAKE) )
  
! Makefile: Qtballit.pro  /usr/local/qt/mkspecs/default/qmake.conf /usr/local/qt/lib/libqt-mt.prl
  	$(QMAKE) -o Makefile Qtballit.pro
  qmake: 
  	@$(QMAKE) -o Makefile Qtballit.pro
--- 107,113 ----
  $(MOC): 
  	( cd $(QTDIR)/src/moc && $(MAKE) )
  
! Makefile: Qtballit.pro  /opt/qt/mkspecs/default/qmake.conf /opt/qt/lib/libqt-mt.prl
  	$(QMAKE) -o Makefile Qtballit.pro
  qmake: 
  	@$(QMAKE) -o Makefile Qtballit.pro
*** qtballit.ui.h	2005-01-22 21:45:47.000000000 +0100
--- qtballit.ui.h	2010-05-28 17:21:16.000000000 +0200
***************
*** 889,895 ****
  
  void qtballit::mostraManuale()
  {
!   const char command_man[]="$BROWSER ./qtballit_man.htm";
      
  system(command_man);
  }
--- 889,895 ----
  
  void qtballit::mostraManuale()
  {
!   const char command_man[]="firefox /usr/share/doc/qtballit/qtballit_man.htm";
      
  system(command_man);
  }
***************
*** 897,903 ****
  
  void qtballit::mostraTabella()
  {
!   const char command_tab[]="$BROWSER ./qtballit_tabella.htm";
      
  system(command_tab);
  
--- 897,903 ----
  
  void qtballit::mostraTabella()
  {
!   const char command_tab[]="firefox /usr/share/doc/qtballit/qtballit_tabella.htm";
      
  system(command_tab);
