*** Makefile	2014-03-13 02:06:28.486430040 +0900
--- Makefileb	2014-03-13 02:07:30.485812557 +0900
***************
*** 202,211 ****
  # The dependency for intlh.inst is different in gettext and all other
  # packages.  Because we cannot you GNU make features we have to solve
  # the problem while rewriting Makefile.in.
! @GT_YES@intlh.inst: intlh.inst.in ../config.status
! @GT_YES@	cd .. \
! @GT_YES@	&& CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= \
! @GT_YES@	  $(SHELL) ./config.status
  @GT_NO@.PHONY: intlh.inst
  @GT_NO@intlh.inst:
  
--- 202,208 ----
  # The dependency for intlh.inst is different in gettext and all other
  # packages.  Because we cannot you GNU make features we have to solve
  # the problem while rewriting Makefile.in.
! @GT_YES@intlh.inst: intlh.inst.in ../config.status && cd .. && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status
  @GT_NO@.PHONY: intlh.inst
  @GT_NO@intlh.inst:
  
