# -*- mode: sh; -*-

note () {
    cat << EOF

==> To start using this package, add following lines to your .emacs:

    (add-to-list 'load-path "/usr/share/emacs/site-lisp/jdibug/")
    (require 'jdibug)

EOF
}

post_install() {
    install-info --name=jdibug /usr/share/info/jdibug.info --info-dir=/usr/share/info/
    note
}

pre_remove() {
    install-info --remove /usr/share/info/jdibug.info --info-dir=/usr/share/info/
}

post_upgrade() {
    note
}
