#Automatically generated by pip2arch on 2015-02-12
pkgname=python2-pydy
pkgver=0.2.1
pkgrel=1
pkgdesc="Python tool kit for multi-body dynamics."
url="http://pydy.org"
depends=('python2-numpy>=1.6.1'
         'python2-sympy>=0.7.4.1'
         'python2-scipy>=0.9.0'
         'python2-matplotlib>=0.99.0'
         'ipython2>=0.13.0')
makedepends=('python2-setuptools')
optdepends=('cython2: code generation backend'
            'python2-theano: code generation backend')
license=('CUSTOM')
arch=('any')
source=("https://pypi.python.org/packages/source/p/pydy/pydy-${pkgver}.tar.gz")
md5sums=('013b41ec1f46b50a484cd1f42c0f55fb')

build() {
  cd $srcdir/pydy-$pkgver
  python2 setup.py build
}

package() {
  cd $srcdir/pydy-$pkgver
  python2 setup.py install --root="$pkgdir" --optimize=1
}
