# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Babken Vardanyan <483ken@gmail.com>

_gemname=factory_girl
pkgname=ruby1.9-$_gemname
pkgver=4.4.0
pkgrel=1
pkgdesc='factory_girl provides a framework and DSL for defining and using model instance factories.'
arch=(any)
url='https://github.com/thoughtbot/factory_girl'
license=(MIT)
depends=(ruby1.9 ruby1.9-activesupport)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('0c95bdef541fb8254e5c8fc136f5304140418a97')

package() {
  local _gemdir="$(ruby-1.9 -e'puts Gem.default_dir')"
  gem-1.9 install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
