post_install() {
	echo '--------------------------------------------------------------------------'
	echo '  Define what to sync in /etc/asd.conf'
	echo '  Read the manpage before use!'
	echo '  More at: https://wiki.archlinux.org/index.php/Anything-sync-daemon'
	echo '--------------------------------------------------------------------------'
}

pre_remove() {
[[ -f /run/daemons/asd ]] && /etc/rc.d/asd stop
}
