post_install() {
	/sbin/install_java_jce_policy install
	echo "===> Everytime jre is updated, you must run:"
	echo "===> /sbin/install_java_jce_policy install"
	echo "===> Otherwise, the programs which need this package will break."
}

pre_upgrade() {
	/sbin/install_java_jce_policy uninstall
}

post_upgrade() {
	/sbin/install_java_jce_policy install
}

pre_remove() {
	/sbin/install_java_jce_policy uninstall
}

op=$1
shift
$op $*
