post_install() {
	systemctl --system daemon-reload
	echo "----------------------------------------------------------"
	echo "edit /etc/conf.d/xbmcmanager according to the output of :"
	echo "/opt/vc/bin/tvservice -s"
	echo "----------------------------------------------------------"
	echo "run 'systemctl start xbmcmanager' to start xbmc-pi-manager" 
	echo "and 'systemctl enable xbmcmanager' to run it at boot time"
	echo "----------------------------------------------------------"
        echo "Please ensure that xbmc.service is disabled !"
        echo "run 'systemctl disable xbmc"
	echo "----------------------------------------------------------"
}

post_upgrade() {
	post_install
}

post_remove() {
	systemctl --system daemon-reload
}

