#!/bin/bash

SAVEIFS=$IFS
IFS=$(echo -en "\n\b")

if [ ! -f /usr/bin/metacity ]; then
  zenity --warning --text="<b>You do not appear to have Metacity installed.</b>\n\nThe Compiz GTK window decorator uses Metacity libraries to operate. The Metacity theme is what this tool adjusts.\n\nInstall the metacity package if you would like to use the Compiz GTK window decorator."
fi

main_window() {
  selection=$(
    zenity --height 450 --width 300 --list --ok-label="Apply" --cancel-label="Close" \
    --title="Compiz GTK decorator theme" \
    --column="Installed Metacity themes:" \
    "Compiz GWD default" $(cat /usr/share/themes/*/metacity-1/metacity-theme-*.xml | grep "</name>" | sed 's/^.*<name>//' | sed 's|</name>||' | sed 's/ /-/' | sed -n 'G; s/\n/&&/; /^\([ -~]*\n\).*\n\1/d; s/\n//; h; P')
  )
}

while [ $? = 0 ]; do
if [ "$selection" == "Compiz GWD default" ]; then
  gsettings set org.gnome.desktop.wm.preferences theme ""
elif [ "$selection" != "" ]; then
  gsettings set org.gnome.desktop.wm.preferences theme "$selection"
fi
main_window
done

IFS=$SAVEIFS
