post_install() {
    echo ""
    echo ""
    echo ">>>                   WARNING !!!             <<<"
    echo ""
    echo ">>>         RUN   "sudo depmod"   now !       <<<"
    echo ""
    echo ""
}

post_upgrade() {
    echo ""
    echo ""
    echo ">>>                   WARNING !!!             <<<"
    echo ""
    echo ">>>          RUN   "sudo depmod" now !        <<<"
    echo ""
    echo ""
}
