post_install() {
    getent group qprofd >/dev/null 2>&1 || groupadd qprofd &>/dev/null
    getent passwd qprofd >/dev/null 2>&1 || useradd -g qprofd -r -s /bin/false qprofd &>/dev/null

    if [[ ! -d run/qprofd ]]; then
        usr/bin/systemd-tmpfiles --create qprofd.conf
    fi
}

post_upgrade() {
    post_install
}

post_remove() {
  if getent passwd qprofd >/dev/null 2>&1; then
    userdel qprofd
  fi

  if getent group qprofd >/dev/null 2>&1; then
    groupdel qprofd
  fi
}

