--- Makefile	2006-05-02 16:17:13.000000000 -0300
+++ Makefile	2007-05-28 21:44:09.000000000 -0300
@@ -14,7 +14,7 @@
 # Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 
 
-PREFIX    ?= /usr/local
+PREFIX    ?= /usr
 LANGUAGES ?= xx
 
 PLINC      = $(shell perl -e \
