# Generated by gem2arch
# Maintainer: LeeF

_gemname=git
pkgname=ruby-enterprise-$_gemname
pkgver=1.2.5
pkgrel=0
pkgdesc="Ruby/Git is a Ruby library that can be used to create, read and manipulate Git repositories by wrapping system calls to the git binary"
arch=('i686' 'x86_64')
url="http://github.com/schacon/ruby-git"
license=('MIT')
depends=('ruby-enterprise')
makedepends=('ruby-enterprise')
source=(http://gems.rubyforge.org/gems/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
md5sums=('3506583cd89c17530dc1c6bf498b4e91')

build() {
  cd $srcdir
  local _gemdir=`ruby -rubygems -e'puts Gem.default_dir'`
  gem install --ignore-dependencies --no-rdoc --no-ri  -i "$pkgdir$_gemdir" $_gemname-$pkgver.gem
}
