pkgver="1.1.2_2"

post_install() {
	echo "Running setup program..."
	sudo /usr/local/Brother/Printer/mfc6490cw/cupswrapper/cupswrappermfc6490cw
	echo "done."

	cat << EOF
==> Now visit the CUPS configuration page to add your printer @ http://localhost:631/admin
EOF
}

pre_remove() {
	echo "Running setup program to uninstall..."
	sudo /usr/local/Brother/Printer/mfc6490cw/cupswrapper/cupswrappermfc6490cw -e
	echo "done."
}
