post_install() {
  update-desktop-database -q
  [[ "$(vercmp $1 0.4.3)" ]] && cat << EOF

>>> If you get in troubles loading menu plugin, try deleting old config file:
>>> rm ~/.config/adeskbar/default.cfg
>>>
>>> or better patch it (without loosing configuration) with:
>>> sed -i "s/menuframe/menu/" ~/.config/adeskbar/default.cfg

EOF
}

post_upgrade() {
  post_install
}

post_remove() {
  post_install
}