post_install() {
  gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
  gtk-update-icon-cache -q -t -f /usr/share/icons/ubuntu-mono-light
  gtk-update-icon-cache -q -t -f /usr/share/icons/ubuntu-mono-dark
}

post_upgrade() {
  post_install
}

post_remove() {
  gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
  gtk-update-icon-cache -q -t -f /usr/share/icons/ubuntu-mono-light
  gtk-update-icon-cache -q -t -f /usr/share/icons/ubuntu-mono-dark
}

