HS_DIR=usr/share/haskell/haskell-pcap
post_install() {
  ${HS_DIR}/register.sh
  if [ -e /usr/share/doc/ghc/html/libraries/arch-gen-contents-index ]; then
    /usr/share/doc/ghc/html/libraries/arch-gen-contents-index
  else
    (cd usr/share/doc/ghc/html/libraries; ./gen_contents_index)
  fi
}
pre_upgrade() {
  ${HS_DIR}/unregister.sh
}
post_upgrade() {
  ${HS_DIR}/register.sh
  if [ -e /usr/share/doc/ghc/html/libraries/arch-gen-contents-index ]; then
    /usr/share/doc/ghc/html/libraries/arch-gen-contents-index
  else
    (cd usr/share/doc/ghc/html/libraries; ./gen_contents_index)
  fi
}
pre_remove() {
  ${HS_DIR}/unregister.sh
}
post_remove() {
  if [ -e /usr/share/doc/ghc/html/libraries/arch-gen-contents-index ]; then
    /usr/share/doc/ghc/html/libraries/arch-gen-contents-index
  else
    (cd usr/share/doc/ghc/html/libraries; ./gen_contents_index)
  fi
}
