.TH MINMAD 1 "NOVEMBER 2011"
.SH NAME
minmad \- minimal mp3 mplayer
.SH SYNOPSIS
.B minmad
.RI " filename"
.SH DESCRIPTION
.B minmad
is a minimal commandline mp3 player using libmad, 
and employs vim-like keyboard shortcuts.
.SH KEY BINDINGS
.IP \fBp\fR\ |\ \fBSpace\fR
Toggle play
.TP 
.B h
Rewind
.TP
.B l
Forward
.IP [\fI0-9\fR]+\fBj\fR
Fast forward by a specified amount
.IP [\fI0-9\fR]+\fBk\fR
Fast rewind by a specified amount
.IP [\fI0-9\fR]+\fB%\fR
Jump to specified percent of mp3
.TP
.B i
Display file information
.TP
.B q
Quit program
.SH AUTHOR
Ali Gholami Rudi <aligrudi at gmail dot com>
