WEBDIR="/usr/share/webapps/graylog2"

post_install() {
	chown -R http $WEBDIR/{tmp,log} > /dev/null 2>&1
	echo "  You can start the web application using the builtin webserver with the following command:"
	echo "  # su -s /bin/sh - http -c \"cd /usr/share/webapps/graylog2/; script/rails server -e production\""
	echo "  or you can use any other method supported by rails (E.g. passenger / thin)"
}

post_upgrade() {
	chown -R http $WEBDIR/{tmp,log} > /dev/null 2>&1
}