# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Babken Vardanyan <483ken@gmail.com>

_gemname=metasploit-concern
pkgname=ruby1.9-$_gemname
pkgver=0.1.1
pkgrel=1
pkgdesc='Automatically include Modules from app/concerns'
arch=(any)
url='https://github.com/rapid7/metasploit-concern'
license=(BSD-3-clause)
depends=(ruby1.9 ruby1.9-activesupport)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('de2f34790e4e1990677ec0ff3ebde2646e58d9c2')

package() {
  local _gemdir="$(ruby-1.9 -e'puts Gem.default_dir')"
  gem-1.9 install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
