# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=pjax_rails
pkgname=ruby-$_gemname
pkgver=0.4.0
pkgrel=1
pkgdesc='PJAX integration for Rails 3.1+'
arch=(any)
url='https://github.com/rails/pjax_rails'
license=(MIT)
depends=(ruby ruby-railties ruby-jquery-rails)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('fe4755e5a8d1138dd8bb8d3717ef0569dd2fbef1')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
