post_install() {

cat <<-EoM

==> KDE 4 now uses dbus for settings and as currently there is no way to set
==> the wallpaper via the command line.  Scripted Image Wallpaper Plugin has the
==> ability to set the wallpaper at certain times, dates, through specific
==> websites by allowing scripting of them.  Example scripts can be found at:
==> http://www.kde-look.org/content/show.php?content=117118.  After setup you
==> may be required to logout/login for scripted-image to work correctly.

EoM

}

post_upgrade() {

post_install

}
