# Generated by gem2arch
# Maintainer: LeeF

_gemname=activesupport
pkgname=ruby-enterprise-activesupport-235
pkgver=2.3.5
pkgrel=1
pkgdesc="Support and utility classes used by the Rails framework."
arch=('i686' 'x86_64')
url="http://www.rubyonrails.org"
license=('MIT')
depends=('ruby-enterprise')
makedepends=('ruby-enterprise')
source=(http://gems.rubyforge.org/gems/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
md5sums=('c4cbb7dd1ea612fd1c6b181a211cd468')

build() {
  cd $srcdir
  local _gemdir=`ruby -rubygems -e'puts Gem.default_dir'`
  gem install --ignore-dependencies --no-rdoc --no-ri -i "$pkgdir$_gemdir" $_gemname-$pkgver.gem
}
