# arg 1:  the new package version

KERNEL_VERSION=2.6.38-one-dev

post_upgrade() {
  depmod -ae -v $KERNEL_VERSION  > /dev/null 2>&1		 
  
  echo "Fan control should now be achieved by the acerhdf kernel module"
  echo "If you previously used the acerfand script make sure it is deactivated first"
  echo "Then add acerhdf to the modules section in rc.conf"
  echo "AND either add \"acerhdf.kernelmode=1\" to the kernel boot line in /boot/grub/menu.lst"
  echo "OR create /etc/modprobe.d/acerhdf.conf with the following contents:"
  echo " options acerhdf kernelmode=1"
}

# arg 1:  the new package version
# arg 2:  the old package version
post_install() {
  post_upgrade

  echo "\nAdd the following entry to /boot/grub/menu.lst:"
  echo "# (next number) Arch Linux"
  echo "title  Arch Linux ArchOne Devel [/boot/vmlinuz-one-dev]"
  echo "root   (hd0,0)"
  echo "kernel /boot/vmlinuz-one-dev root=/dev/sda1 ro snd_hda_intel.model=acer-aspire"
}

# arg 1:  the old package version
post_remove() {
  depmod -ae -v $KERNEL_VERSION	 > /dev/null 2>&1	 
  echo "Don't forget to remove the vmlinuz-one-dev entry from /boot/grub/menu.lst"
}

op=$1
shift
$op $*
