# arg 1:  the new package version

KERNEL_VERSION=2.6.39-one-dev

post_upgrade() {
  depmod -ae -v $KERNEL_VERSION  > /dev/null 2>&1		 
}

# arg 1:  the new package version
# arg 2:  the old package version
post_install() {
  post_upgrade

  echo "\nAdd the following entry to /boot/grub/menu.lst:"
  echo "# (next number) Arch Linux"
  echo "title  Arch Linux ArchOne Devel [/boot/vmlinuz-one-dev]"
  echo "root   (hd0,0)"
  echo "kernel /boot/vmlinuz-one-dev root=/dev/sda1 ro snd_hda_intel.model=acer-aspire"
}

# arg 1:  the old package version
post_remove() {
  depmod -ae -v $KERNEL_VERSION	 > /dev/null 2>&1	 
  echo "Don't forget to remove the vmlinuz-one-dev entry from /boot/grub/menu.lst"
}

op=$1
shift
$op $*
