
post_install() {
    echo ">>>"
    echo ">>>>To play iostvoy with the Retail Version:"
    echo ">>>   Copy the pak0.pk3 file from the original game CD to"
    echo ">>>      /opt/iostvoy/baseEF/"
    echo ">>>"
    echo ">>>>When you have the .pk3 file(s) installed, run the game:"
    echo ">>>      stvoyHM"
    echo ">>>"
}

post_upgrade() {
    post_install $1
}

pre_remove() {
    /bin/true
}

op=$1
shift

$op $*

