post_install() {
  _ffver=`pacman -Q firefox | cut -f2 -d\ | cut -f1 -d-`
  emid=`pacman -Ql firefox-firesheep | cut -f6 -d/|tail -1`
  /usr/lib/firefox-${_ffver}/extensions/$emid/platform/Linux_x86_64-gcc3/firesheep-backend --fix-permissions
  echo ""
  echo ">>> Fixed backend permissions: firesheep-backend --fix-permissions"
  echo ">>> Security: suid bit set on firesheep-backend binary"
  echo ""
  /bin/true
}

post_upgrade() {
    post_install
}
