--- Makefile.old	2011-01-13 18:03:26.782758479 +0100
+++ Makefile	2011-01-13 18:03:34.209499413 +0100
@@ -1,6 +1,6 @@
 OBJS=cbmbasic.o runtime.o plugin.o
-CFLAGS=-arch i386 -arch x86_64 -arch ppc -Wall -O3
-LDFLAGS=-arch i386 -arch x86_64 -arch ppc
+#CFLAGS=-arch i386 -arch x86_64 -arch ppc -Wall -O3
+#LDFLAGS=-arch i386 -arch x86_64 -arch ppc
 
 all: cbmbasic
 
