post_install() {
  ln -s /usr/share/cvpncg/cvpncg.py  /usr/bin/cvpncg
  ln -s /usr/bin/vpnclient /usr/local/bin/
  echo "----------"
  echo "This package provides a GUI for the cisco vpnclient."
  echo "Cisco vpnclient MUST be installed for this package to work."
  echo "----------"
}

post_upgrade() {
  post_install
}

post_remove() {
  usr/sbin/userdel policykit &>/dev/null
  usr/sbin/groupdel policykit &>/dev/null
}
