--- Makefile.orig	2009-03-06 02:36:54.635304641 +0100
+++ Makefile	2009-03-06 02:36:44.275785346 +0100
@@ -3,10 +3,10 @@
 PROG=tuxboy
 ARCH=`uname -m`
 PLATFORM=Linux
-DEST=../system/$(PLATFORM)_$(ARCH)/$(PROG)
+DEST=../tuxboy
 
-LFLAGS=	`sdl-config --libs` -lSDL_image -lSDL_ttf #-lwiiuse
-CFLAGS=	-c -g -O3 `sdl-config --cflags` -pedantic -std=c99 -Wall -Wextra \
+LFLAGS=	`sdl-config --libs` -lSDL_image -lSDL_ttf -lwiiuse
+CFLAGS+=	-c `sdl-config --cflags` -pedantic -std=c99 -Wall -Wextra \
 		-Wshadow -Wunknown-pragmas -Winline -Wdisabled-optimization \
 		-Wwrite-strings #-Wconversion #-Wunreachable-code 
 
@@ -35,3 +35,12 @@
 	@strip --strip-all $(DEST)$(TYPE)
 	@upx-nrv -q --ultra-brute -9 $(DEST)$(TYPE)
 
+install: main
+	install -Dm755 $(DEST) $(DESTDIR)/usr/bin/tuxboy
+	install -Dm644 ../system/settings.txt $(DESTDIR)/etc/tuxboy/tuxboy.cfg
+	install -Dm644 ../system/sans.ttf $(DESTDIR)/usr/share/tuxboy/system/sans.ttf
+	mkdir -p $(DESTDIR)/usr/share/tuxboy/system/gfx
+	install -m644 ../system/gfx/* $(DESTDIR)/usr/share/tuxboy/system/gfx/
+	mkdir -p $(DESTDIR)/usr/share/tuxboy/roms
+	mv -f $(DESTDIR)/usr/share/tuxboy/system/gfx/tuxboy.png $(DESTDIR)/usr/share/tuxboy/system/gfx/icon.png
+	install -Dm644 ../system/gfx/tuxboy.png $(DESTDIR)/usr/share/pixmaps/tuxboy.png
