#!/bin/bash
case $1 in 
    --remove)
	for folder in google-chrome chromium ; do 
	    if [ -d $HOME/.config/$folder/Default/Extensions ]  ; then
		find $HOME/.config/$folder/Default/Extensions -name Orta*crx -exec rm '{}' \;
		echo Removed Orta Themes from $folder >&2
	    fi
	done
	;;
    *)
	for folder in google-chrome chromium ; do 
	    if [ -d $HOME/.config/$folder/Default/Extensions ]  ; then
		find /usr/share/themes/orta-chromium-themes -name Orta*crx -exec install -m644 '{}' $HOME/.config/$folder/Default/Extensions \;
		echo Installed Orta Themes for $folder >&2
	    fi
	done
esac
