#!/bin/bash
# Start the heimdal admin daemon
#
# Author: Elias <elias@linexa.de>
# [2010-08-20]

# Information about the daemon
title="kadmind"           # No spaces allowed in here
start_after="" # dependencies for start-up
stop_after=""                     # dependencies for stop
runlevel="3"                         # start/stop in this runlevel
sequence="28"                        # "checkinstall <insert-name-here> enable"
                                     # will create links to:
                                     #   /etc/rc.d/rc${runlevel}.d/S${sequence}${title}
                                     #   /etc/rc.d/rc${runlevel}.d/S$((100 - ${sequence}))${title}
                   
# check whether daemon is running
# returns 0 if running, >0 if not
check() {
	  [ -f /var/run/kadmind.pid ]
}

# start procedure
start() {
  if check ; then # daemon is running
     warning "${title} is already running. Type 'service restart ${title}'" # Issue a warning
  else 
    /usr/sbin/kadmind & &>/dev/null
    evaluate_retval ${title}    # Print [  done  ] or [ failed ] depending on outcome
  fi
}

# stop procedure
stop() {
  if check ; then # daemon is running
    kill $(cat /var/run/kadmind.pid) &> /dev/null
    evaluate_retval ${title}    # Print [  done  ] or [ failed ] depending on outcome
  else # daemon not running
    warning "${title} is not running."  # Issue a warning
  fi
}

# restart procedure
restart() {
  stop
  sleep 1
  start
}

# reload action
reload() {
  restart
}
