#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

get_pid() {
	local pid_file=/var/run/minecraft-server.pid
	local pid=$(pidof -o %PPID minecraft-server)

	if [ -r "${pid_file}" ]; then
		cat "${pid_file}"
	elif [ -n "${pid}" ]; then
		echo "${pid}"
	else
		echo ''
	fi
}

start() {
	stat_busy 'Starting minecraft-server'

	local PID=$(get_pid)
	if [ -z "$PID" ]; then
		nohup /usr/bin/minecraft-server > /dev/null 2> /dev/null < /dev/null &
		echo $! > /var/run/minecraft-server.pid
		if [ $? -gt 0 ]; then
			stat_die
		else
			add_daemon minecraft-server
			stat_done
		fi
	else
		stat_die
	fi
}

stop() {
	stat_busy 'Stopping minecraft-server'
	local PID=$(get_pid)
	[ -n "$PID" ] && kill $PID &> /dev/null
	if [ $? -gt 0 ]; then
		stat_fail
	else
		local pid_file=/var/run/minecraft-server.pid
		[ -f "${pid_file}" ] && rm -f "${pid_file}"
		rm_daemon minecraft-server
		stat_done
	fi
}


case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		while [ -n "$(get_pid)" ]; do
			sleep 1
		done
		start
		;;
	status)
		stat_busy 'Checking minecraft-server status'
		ck_status minecraft-server
		;;
	*)
	echo "usage: $0 {start|stop|restart|status}"
esac

exit 0
