--- Makefile.orig	2009-09-10 15:07:23.635081076 +0400
+++ Makefile	2009-09-10 15:07:41.721786847 +0400
@@ -9,7 +9,7 @@
 CC =		gcc
 CFLAGS =	-O
 #CFLAGS =	-g
-LDFLAGS =	-s -static
+LDFLAGS =	-s
 #LDFLAGS =	-g -static
 LDLIBS =	$(SYSV_LIBS)
 
