post_install() {
  echo
  echo "There is a bug in the LibreOffice UNO implementation. To enable integration with"
  echo "LibreOffice:"
  echo "echo export PYTHONPATH=$PYTHONPATH:/usr/lib/libreoffice/basis-link/program >> /etc/profile.d/libreoffice.sh"
  echo

  update-desktop-database -q
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_upgrade() {
  update-desktop-database -q
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_remove() {
  post_upgrade
}
