post_install() {
      
	cat << EOF
==> Optional dependencies:
==> For flac support: gstreamer0.10-flac
==> For musepack support: gstreamer0.10-musepack
==> For mp4 & m4a support:gstreamer0.10-faad
==> For iPod support: libgpod
==> For musicbrainz & Audio CD support: python-musicbrainz2 tunepimp
==> For DAAP support: python-daap
==> Other nice-to-haves: python-sexy gnome-python hal
EOF
}

post_upgrade() {
  post_install $1
}


op=$1
shift
$op $*
