post_install() {
  ln -s  /opt/lampp/htdocs/spotcommander/bin/spotcommander /usr/bin/spotcommander
}
pre_upgrade(){
cp /opt/lampp/htdocs/spotcommander/db/favourites.db /tmp/spotcommander-favourites.db
cp /opt/lampp/htdocs/spotcommander/db/playlists.db /tmp/spotcommander-playlists.db
}

post_upgrade() {
rm /usr/bin/spotcommander   
ln -s  /opt/lampp/htdocs/spotcommander/bin/spotcommander /usr/bin/spotcommander
cp /tmp/spotcommander-favourites.db /opt/lampp/htdocs/spotcommander/db/favourites.db 
cp /tmp/spotcommander-playlists.db /opt/lampp/htdocs/spotcommander/db/playlists.db 
}

post_remove() {
  rm /usr/bin/spotcommander
}

