post_install() {
  cat << EOF
> Since version 0.4.0, Kanatest uses font-based characters instead of images.
> If you get garbage instead of kana chars, then go to preferences and select
> a Japanese friendly font, for example:
>
> - FreeSerif or FreeSans (package: ttf-freefont)
> - AR PL ShanHeiSun Uni  (package: ttf-arphic-uming)
> - AR PL ZenKai Uni      (package: ttf-arphic-ukai)
EOF
}

post_upgrade() {
  post_install
}

op=$1
shift
$op $*
