post_install() {
  udevadm control --reload-rules &> /dev/null

  echo "---------------------------------------------------------
Before using PK2CMD you have to agree with LICENSE:
/usr/share/licenses/pk2cmd-plus/LICENSE

For help type: pk2cmd
---------------------------------------------------------"
}

post_upgrade() {
  post_install
}

post_remove() {
  udevadm control --reload-rules &> /dev/null
}
