post_install() {
  echo "------------------------------------------------------------------------------------"
  echo "To use the 'play' command, you must own the /opt/play-framework directory:          "
  echo "  $ sudo chown -R $USER: /opt/play-framework                                        "
  echo "------------------------------------------------------------------------------------"
}

post_upgrade() {
  post_install $1
}

# vim:set ts=2 sw=2 et:
