--- Makefile
+++ Makefile
@@ -33,13 +33,13 @@ EXECUTABLE = $(TARGET)/openhexagon.$(TARGET)
 CFLAGS = -g -std=c++11
 
 # Libraries
-DEPENDENCIES += -llua
+DEPENDENCIES += /usr/lib/liblua.so.5.1
 DEPENDENCIES += libs/$(TARGET)/libjsoncpp.a
-DEPENDENCIES += libs/$(TARGET)/libsfml-audio.$(LIBSUFFIX)
-DEPENDENCIES += libs/$(TARGET)/libsfml-graphics.$(LIBSUFFIX)
-DEPENDENCIES += libs/$(TARGET)/libsfml-network.$(LIBSUFFIX)
-DEPENDENCIES += libs/$(TARGET)/libsfml-system.$(LIBSUFFIX)
-DEPENDENCIES += libs/$(TARGET)/libsfml-window.$(LIBSUFFIX)
+DEPENDENCIES += -lsfml-audio
+DEPENDENCIES += -lsfml-graphics
+DEPENDENCIES += -lsfml-network
+DEPENDENCIES += -lsfml-system
+DEPENDENCIES += -lsfml-window
 
 # Parameters
 INCLUDES = -Ilibs/include -I.. -I../SSVStart -I../SSVEntitySystem -I../SSVMenuSystem -I../SSVLuaWrapper
