--- Makefile	2013-03-03 04:10:40.000000000 -0300
+++ Makefile	2013-03-10 18:37:46.545221779 -0300
@@ -33,12 +33,12 @@
 CFLAGS = -g -std=c++11
 
 # Libraries
-DEPENDENCIES += -llua
+DEPENDENCIES += /usr/lib/liblua.so.5.1
 DEPENDENCIES += libs/$(TARGET)/libjsoncpp.a
-DEPENDENCIES += libs/$(TARGET)/libsfml-audio.$(LIBSUFFIX)
-DEPENDENCIES += libs/$(TARGET)/libsfml-graphics.$(LIBSUFFIX)
-DEPENDENCIES += libs/$(TARGET)/libsfml-system.$(LIBSUFFIX)
-DEPENDENCIES += libs/$(TARGET)/libsfml-window.$(LIBSUFFIX)
+DEPENDENCIES += -lsfml-audio
+DEPENDENCIES += -lsfml-graphics
+DEPENDENCIES += -lsfml-system
+DEPENDENCIES += -lsfml-window
 
 # Parameters
 INCLUDES = -Ilibs/include -I.. -I../SSVEntitySystem -I../SSVStart -I../SSVLuaWrapper
