#!/usr/bin/env bash

if [ ! -d "$HOME/.OpenHexagon" ]; then
    echo "Copying Hexagon directory to ~/.OpenHexagon"
    mkdir "$HOME/.OpenHexagon"
    for i in $(ls "/usr/share/OpenHexagon"); do
        if [ "$i" = "Profiles" ]; then
            cp -r "/usr/share/OpenHexagon/$i" "$HOME/.OpenHexagon/Profiles"
        elif [ "$i" != "OpenHexagon" ]; then
            ln -s "/usr/share/OpenHexagon/$i" "$HOME/.OpenHexagon"
        fi
    done
fi
cd "$HOME/.OpenHexagon"
/usr/share/OpenHexagon/OpenHexagon
