pkgname=songbird-svn

post_install() {
	#echo " :: Updating desktop database..."
	update-desktop-database -q
	echo " >>> Songbird uses gstreamer to play music.  To play back all"
	echo " >>> formats, you should install gstreamer0.10-good,"
	echo " >>> gstreamer0.10-bad and gstreamer0.10-ugly"
}

post_upgrade() {
	#echo " :: Updating desktop database..."
	update-desktop-database -q
}

post_remove() {
	#echo " :: Updating desktop database..."
	update-desktop-database -q
}

op=$1
shift

$op $*
