post_install() {
    echo -e "If you will be running hostsblock on your main /etc/hosts file, make sure to backup your original.\n" 
    echo -e "Please copy and customize the config file under /usr/share/hostsblock/hostsblock.conf to /etc/hostsblock.conf.\n"
    echo -e "To run as a cron job, symlink (as root) /usr/bin/hostsblock into one of your cron directories, e.g.: \n	ln -sf /usr/bin/hostsblock /etc/cron.daily/hostsblock\n"
}
