post_install() {
    echo -e "If you will be running hostsblock on your main /etc/hosts file, make sure to backup your original.\n" 
    echo -e "Please customize the config files under /usr/share/hostsblock/.\n"
    echo -e "To run as a cron job, symlink (as root) /usr/bin/hostsblock into one of your cron directories, e.g.: \n	ln -sf /usr/bin/hostsblock /etc/cron.daily/hostsblock\n"
}
post_update() {
    echo "WARNING: New config file format. Check them out under /etc/hostsblock/"
    post_install
}
