info_dir='/usr/share/info/zgv'
info_files=(zgv.info zgv-1 zgv-2 zgv-3 zgv-4)

post_install() {
	[ -x usr/bin/install-info ] || return 0
	for f in ${info_files[@]}; do
		usr/bin/install-info ${info_dir}/$f.gz ${info_dir}/dir 2> /dev/null
	done
}

post_upgrade() {
	post_install $1
}

pre_remove() {
	[ -x usr/bin/install-info ] || return 0
	for f in ${info_files[@]}; do
		usr/bin/install-info --delete ${info_dir}/$f.gz ${info_dir}/dir 2> /dev/null
	done
}
# vim:set ts=2 sw=2 et:

