pkgname=nautilus

post_install() {
  usr/sbin/gconfpkg --install ${pkgname}
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  update-mime-database usr/share/mime > /dev/null
  update-desktop-database -q
}

pre_upgrade() {
  pre_remove
}

post_upgrade() {
  post_install
}

pre_remove() {
  usr/sbin/gconfpkg --uninstall ${pkgname}
}

post_remove() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  update-mime-database usr/share/mime > /dev/null
  update-desktop-database -q
}

