# Message displayed after a fresh install.
post_install() {
    echo "Add these lines to ~/.emacs:"
    echo "  (load-library \"haskell-site-file\")"
    echo "  (add-to-list 'auto-mode-alist '(\"\\\\.hs\\\\'\" . haskell-mode))"
}

# Message displayed afteer package removal.
post_remove() {
    echo "Remove these lines from ~/.emacs:"
    echo "  (load-library \"haskell-site-file\")"
    echo "  (add-to-list 'auto-mode-alist '(\"\\\\.hs\\\\'\" . haskell-mode))"
}
