
post_install() {

echo
echo "**************************************************************************************"
echo "*  Don't forget to create a hidden directory '.mesonplayer' in your home directory   *"
echo "*  and a 'plugins' folder in that directory.                                         *"
echo "**************************************************************************************"
echo
}