--- Makefile	2013-04-05 20:58:36.000000000 +0200
+++ Makefile.patch	2013-04-07 20:48:21.946474157 +0200
@@ -33,7 +33,7 @@
 DIST_TAR = $(PLUGIN)-$(VERSION).tar
 DIST_TAR_XZ = $(DIST_TAR).xz
 
-ICON_DIR = ~/.local/share/icons/hicolor/128x128/apps
+ICON_DIR = $(DESTDIR)/usr/share/icons/hicolor/128x128/apps
 
 all: valacheck valencia.plugin libvalencia.so
 
@@ -53,14 +53,13 @@
 	$(VALAC) $(VFLAGS) -X --shared -X -fPIC $(PACKAGES) $(SOURCES) -o $@
 
 install: libvalencia.so valencia.plugin
-	@ [ `whoami` != "root" ] || ( echo 'Run make install as yourself, not as root.' ; exit 1 )
-	mkdir -p ~/.local/share/gedit/plugins
-	cp $(OUTPUTS) ~/.local/share/gedit/plugins
+	mkdir -p $(DESTDIR)/usr/lib/gedit/plugins
+	cp $(OUTPUTS) $(DESTDIR)/usr/lib/gedit/plugins
 	mkdir -p $(ICON_DIR)
 	cp -p valencia.png $(ICON_DIR)
 
 uninstall:
-	rm -f $(foreach o, $(OUTPUTS), ~/.local/share/gedit/plugins/$o)
+	rm -f $(foreach o, $(OUTPUTS), /usr/lib/gedit/plugins/$o)
 	rm -f $(ICON_DIR)/valencia.png
 
 parser:  expression.vala parser.vala program.vala scanner.vala util.vala
