--- Makefile.orig	2010-05-29 03:06:04.456027657 +0200
+++ Makefile	2010-05-29 03:08:15.506244949 +0200
@@ -28,7 +28,7 @@
 DIST_TAR_BZ2 = $(DIST_TAR).bz2
 DIST_TAR_GZ = $(DIST_TAR).gz
 
-ICON_DIR = ~/.local/share/icons/hicolor/128x128/apps
+ICON_DIR = $(DESTDIR)/usr/share/icons/hicolor/128x128/apps
 
 all: valencia.gedit-plugin libvalencia.so
 	
@@ -41,9 +41,8 @@
 	$(VALAC) $(VFLAGS) -X --shared -X -fPIC --vapidir=. $(PACKAGES) $(SOURCES) -o $@
 
 install: libvalencia.so valencia.gedit-plugin
-	@ [ `whoami` != "root" ] || ( echo 'Run make install as yourself, not as root.' ; exit 1 )
-	mkdir -p ~/.gnome2/gedit/plugins
-	cp $(OUTPUTS) ~/.gnome2/gedit/plugins
+	mkdir -p $(DESTDIR)/usr/lib/gedit-2/plugins
+	cp $(OUTPUTS) $(DESTDIR)/usr/lib/gedit-2/plugins
 	mkdir -p $(ICON_DIR)
 	cp -p valencia.png $(ICON_DIR)
 
