post_remove() {
	# This section is a copy/paste from the debian postrm script
	# http://bazaar.launchpad.net/~bit-team/backintime/trunk/view/head:/common/debian_specific/postrm
	# I believe allowing all of this functionality would be an Arch no-no
	# for example removing files in a user homedir
	# I did keep the few lines that point to orphaned files though

	rm -rf /usr/share/backintime/common/*.pyc
	rm -rf /usr/share/backintime/plugins/*.pyc
	rm -rf /etc/udev/rules.d/99-backintime-*.rules
}
