#!/usr/bin/env bash

. /etc/rc.conf
. /etc/rc.d/functions

if [[ -f /etc/profile.d/jre.sh ]]; then
    . /etc/profile.d/jre.sh
elif [[ -f /etc/profile.d/openjdk6.sh ]]; then
    . /etc/profile.d/openjdk6.sh
fi

WD=/opt/crashplan
CRASHPLAN=$WD/lib/com.backup42.desktop.jar
ARGS=com.backup42.service.CPService
PIDFILE=/var/run/crashplan.pid
VARS=$WD/install.vars
CONFIG=$WD/bin/run.conf

test -f $VARS || exit 0
test -f $CONFIG || exit 0
test -f $CRASHPLAN || exit 0

. $VARS
. $CONFIG



if [[ ${LC_ALL} ]]; then
    LOCALE=`sed 's/\..*//g' <<< ${LC_ALL}`
    export LC_ALL="${LOCALE}.UTF-8"
elif [[ ${LC_CTYPE} ]]; then
    LOCALE=`sed 's/\..*//g' <<< ${LC_CTYPE}`
    export LC_CTYPE="${LOCALE}.UTF-8"
elif [[ ${LANG} ]]; then
    LOCALE=`sed 's/\..*//g' <<< ${LANG}`
    export LANG="${LOCALE}.UTF-8"
else
    export LANG="en_US.UTF-8"
fi

[[ -f $PIDFILE ]] && PID=`cat $PIDFILE`

case "$1" in
    start)
	stat_busy "Starting CrashPlan Engine"
	PWD=`pwd`
	cd $WD
	[[ -z "$PID" ]] && nice -n 19 $JAVA_HOME/bin/java $SRV_JAVA_OPTS -classpath $CRASHPLAN:$WD/lang $ARGS > $WD/log/engine_output.log 2> $WD/log/engine_error.log &
	if [ $? -gt 0 ]; then
	    stat_fail
	else
	    PID=`/bin/ps -eo 'pid,cmd'| grep 'app=CrashPlanService' | grep -v grep | awk '{sub("^ ", "", $0); print $0}' | cut -d " " -f 1`
	    echo $PID > $PIDFILE
	    add_daemon crashplan
	    stat_done
	fi
	cd $PWD
	;;
    stop)
	stat_busy "Stopping CrashPlan Engine"
	[[ ! -z "&PID" ]] && kill $PID &> /dev/null
	if [ $? -gt 0 ]; then
	    stat_fail
	else
	    rm_daemon crashplan
	    rm $PIDFILE
	    stat_done
	fi
	;;
    restart)
	$0 stop
	sleep 1
	$0 start
	;;
    status)
	PID=`/bin/ps -eo 'pid,cmd'| grep 'app=CrashPlanService' | grep -v grep | awk '{sub("^ ", "", $0); print $0}' | cut -d " " -f 1`
	if [[ -n "$PID" ]]; then
	    echo "CrashPlan (pid $PID) is running."
	else
	    echo "CrashPlan is stopped."
	fi
	;;
    *)
	echo "Usage: $0 <start|stop|restart|status>" >&2
	exit 3
	;;
esac

