_install_msg() {
	echo 
	echo "==> To enable the RightScale RightLink services:"
	echo "systemctl enable rightscale.service"
	echo "systemctl enable rightlink.service"
	echo "systemctl enable rightlink-decommission.service"
	echo
	echo "==> To start RightScale RightLink:"
	echo "systemctl start rightscale.service"
	echo "systemctl start rightlink.service"
}

post_install() {
	_install_msg
}

post_upgrade() {
 	_install_msg
}

# vim:set ts=2 sw=2 et: