BABELSTY=`kpsewhich babel.sty`

update_texlsr() {
    echo "Updating TeX filename database..."
    /usr/bin/mktexlsr
}

post_install() {
    update_texlsr $1

    echo -n "Updating babel.sty..."
    sed -i -e '/turkish/i\\\DeclareOption{thai}{\\input{thai.ldf}}' $BABELSTY
    echo "done."
}

post_upgrade() {
    update_texlsr $1
}

post_remove() {
    update_texlsr $1

    echo -n "Updating babel.sty..."
    sed -i -e '/thai.ldf/d' $BABELSTY
    echo "done."
}
