post_install() {    
  groupadd role &> /dev/null
  useradd -g role -d /opt/role -s /bin/false role &> /dev/null
  mkdir -p /opt/role/db
  chown -R role:role /opt/role/db
  touch /var/log/role.log
  chown role:role /var/log/role.log
}

post_upgrade() {
  chown -R role:role /opt/role/db
  touch /var/log/role.log
  chown role:role /var/log/role.log
}

pre_remove() {
  groupdel role &> /dev/null
  userdel role &> /dev/null
}
