--- Makefile.orig	2009-10-21 16:41:50.000000000 -0200
+++ Makefile	2009-11-10 17:15:16.615745732 -0200
@@ -55,7 +55,7 @@
 ifeq ($(UNAME),SunOS)
     LPuid=-oroot
     LPgid=-glp
-    INSTALL=/usr/ucb/install
+    INSTALL=$(DESTDIR)/usr/ucb/install
 endif
 # If we aren't root, don't try to set ownership
 ifneq ($(EUID),0)
@@ -586,7 +586,7 @@
 	#
 	# Install current database files
 	#
-	@if [ -d $(FOODB) ]; then \
+	@if [ -d /usr/share/foomatic/db/source ]; then \
 	    for dir in driver printer opt; do \
 		echo install -m 644 foomatic-db/$$dir/*.xml $(FOODB)/$$dir/; \
 		$(INSTALL) -c -m 644 foomatic-db/$$dir/*.xml $(FOODB)/$$dir/; \
@@ -725,12 +725,12 @@
 MODEL=$(DESTDIR)/usr/share/cups/model
 LOCALMODEL=$(DESTDIR)/usr/local/share/cups/model
 PPD=$(DESTDIR)/usr/share/ppd
-VARPPD=/var/lp/ppd
+VARPPD=$(DESTDIR)/var/lp/ppd
 install-ppd:
 	#
 	# Install PPD files for CUPS
 	#
-	if [ -x /usr/sbin/ppdmgr -a -s $(VARPPD)/ppdcache ]; then \
+	if [ -x /usr/sbin/ppdmgr -a -s /var/lp/ppd/ppdcache ]; then \
 	    $(INSTALL) $(LPgid) -d $(VARPPD)/user; \
 	    cd PPD; \
 	    for ppd in *.ppd; do \
@@ -739,7 +739,7 @@
 		gzip < $$ppd > $(VARPPD)/user/$$manuf/$$ppd.gz; \
 	    done; \
 	    ppdmgr -u; \
-	elif [ -d $(PPD) ]; then \
+	elif [ -d /usr/share/ppd ]; then \
 	    find $(PPD) -name '*foo2zjs*' | xargs rm -rf; \
 	    find $(PPD) -name '*foo2hp*' | xargs rm -rf; \
 	    find $(PPD) -name '*foo2xqx*' | xargs rm -rf; \
@@ -753,13 +753,13 @@
 		gzip < $$ppd > $(PPD)/foo2zjs/$$ppd.gz; \
 	    done; \
 	fi
-	if [ -d $(MODEL) ]; then \
+	if [ -d /usr/share/cups/model ]; then \
 	    rm -f $(MODEL)/KonicaMinolta*; \
 	    cd PPD; \
 	    for ppd in *.ppd; do \
 		gzip < $$ppd > $(MODEL)/$$ppd.gz; \
 	    done; \
-	elif [ -d $(LOCALMODEL) ]; then \
+	elif [ -d /usr/local/share/cups/model ]; then \
 	    rm -f $(LOCALMODEL)/KonicaMinolta*; \
 	    cd PPD; \
 	    for ppd in *.ppd; do \
@@ -775,13 +775,13 @@
 	#
 	# Install GNOME desktop
 	#
-	if [ -d $(APPL) ]; then \
+	if [ -d /usr/share/applications ]; then \
 	    $(INSTALL) -c -m 644 hplj1020.desktop $(APPL); \
 	fi
-	if [ -d $(OLDAPPL) ]; then \
+	if [ -d /usr/share/gnome/apps/System ]; then \
 	    $(INSTALL) -c -m 644 hplj1020.desktop $(OLDAPPL); \
 	fi
-	if [ -d $(PIXMAPS) ]; then \
+	if [ -d /usr/share/pixmaps ]; then \
 	    $(INSTALL) -c -m 644 hplj1020_icon.png $(PIXMAPS); \
 	fi
 
@@ -793,8 +793,8 @@
 	$(INSTALL) -c -m 755 hplj10xx_gui.tcl $(SHAREZJS)
 	
 
-USBDIR=/etc/hotplug/usb
-UDEVDIR=/etc/udev/rules.d
+USBDIR=$(DESTDIR)/etc/hotplug/usb
+UDEVDIR=$(DESTDIR)/etc/udev/rules.d
 RULES=hplj10xx.rules
 install-hotplug: install-hotplug-test install-hotplug-prog
 
@@ -814,10 +814,10 @@
 	#
 
 install-hotplug-prog:
-	if [ -d $(UDEVDIR) ]; then \
+	if [ -d /etc/udev/rules.d ]; then \
 	    $(INSTALL) -c -m 644 $(RULES) $(UDEVDIR)/11-$(RULES); \
 	fi
-	[ -d $(USBDIR) ] || $(INSTALL) -d -m 755 $(USBDIR)/
+	[ -d /etc/hotplug/usb ] || $(INSTALL) -d -m 755 $(USBDIR)/
 	$(INSTALL) -c -m 755 hplj1000 $(USBDIR)/
 	ln -sf $(USBDIR)/hplj1000 $(USBDIR)/hplj1005
 	ln -sf $(USBDIR)/hplj1000 $(USBDIR)/hplj1018
@@ -1100,9 +1100,9 @@
 # Make phony print devices for testing full spooler interface without printing
 #
 tmpdev:
-	DEV=/tmp/OAK; > $$DEV; chmod 666 $$DEV
-	DEV=/tmp/OAKCM; > $$DEV; chmod 666 $$DEV
-	DEV=/tmp/testfile; > $$DEV; chmod 666 $$DEV
+	DEV=$(DESTDIR)/tmp/OAK; > $$DEV; chmod 666 $$DEV
+	DEV=$(DESTDIR)/tmp/OAKCM; > $$DEV; chmod 666 $$DEV
+	DEV=$(DESTDIR)/tmp/testfile; > $$DEV; chmod 666 $$DEV
 
 #
 # Test files for debugging
@@ -1234,7 +1234,7 @@
 	$(INSTALL) -c -m 644 README $(DOCDIR)
 	$(INSTALL) -c -m 644 ChangeLog $(DOCDIR)
 
-GROFF=/usr/local/test/bin/groff
+GROFF=$(DESTDIR)/usr/local/test/bin/groff
 GROFF=groff
 manual.pdf: $(MANPAGES)
 	-$(GROFF) -t -man $(MANPAGES) | ps2pdf - $@
