## arg 1:  the new package version
post_install() {
  cat << EOF

To enable the CPU frequency scaling service at boot, run the following command as root:
systemctl enable cpufreq.service

To manually start the service (without having to reboot), run the following command as root:
systemctl start cpufreq.service

EOF
}

## arg 1:  the old package version
pre_remove() {
  systemctl stop cpufreq.service
  systemctl disable cpufreq.service
}

# vim:set ts=2 sw=2 et:
