post_install() {
    # Work around missing libudev.so.0
    ln -sf libudev.so /usr/lib/libudev.so.0

	# chrome-sandbox isn't included in the prebuilt package, so symlink
    # it from an existing Chromium installation
    ln -sf /usr/lib/chromium/chrome-sandbox /usr/lib/chromiumos-ui/
}

post_upgrade() {
    post_install
}

post_remove() {
    rm -f /usr/lib/libudev.so.0
    rm -f /usr/lib/chromiumos-ui/chrome-sandbox
}
