post_install() {

    echo ""
    echo "This is a package containing the Automated Builds provided by mingw-w64 project."
    echo "This compiler toolchain supports building only win64 executables and dlls, not win32, ie. no multilib."    
    echo ""
	echo "If you want to test c++ binaries with win64,"
	echo "you should copy or link /opt/mingw_w64/bin/*.dll"
	echo "into your .wine/drive_c/windows/system32"
	echo ""
    
}

post_upgrade() {
    post_install
}
