# Maintainer: Bob Davidson <segfaulted.ant@gmail.com>

pkgname=ksplice-git
_gitname="ksplice"
pkgver=20131111
pkgrel=1
pkgdesc="Update the Linux kernel without rebooting"
arch=('i686' 'x86_64')
url="https://github.com/jirislaby/ksplice"
license=('GPL2')
# https://github.com/jirislaby/ksplice
source=('ksplice-git::git://github.com/jirislaby/ksplice.git'
        'opgen-python3.patch')
md5sums=('SKIP'
         '4da34b819df441719bddfeb60e2e7a8b')
makedepends=('python')

pkgver() {
  date +%Y%m%d
}

build() {
  cd $srcdir/$pkgname

  patch -Np0 -i "${srcdir}/opgen-python3.patch"

  ./configure --prefix=/usr \
              --libexecdir=/usr/lib/ksplice \
              --sbindir=/usr/bin

  # opgen-python3.patch generated by 2to3 provides python3 support,
  # the following line can be used to use python2 instead:
  # sed -i 's/python/python2/g' Makefile.in Makefile kmodsrc/x86/libudis86/opgen.py

  make
}

package() {
  cd $srcdir/$pkgname
  make DESTDIR=$pkgdir install
}

