--- ../../source/Makefile	2009-09-24 16:40:18.000000000 +0200
+++ Makefile	2010-02-09 23:20:27.000000000 +0100
@@ -15,7 +15,7 @@
 #  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 
 
-PREFIX = /usr/local
+PREFIX = /usr
 SUFFIX := $(shell uname -m | sed -e 's/^unknown/$//' -e 's/^i.86/$//' -e 's/^x86_64/$/64/')
 LIBDIR = lib$(SUFFIX)
 SHARED = $(PREFIX)/share
@@ -55,10 +55,10 @@
 
 
 install:	all
-	/usr/bin/install -m 755 ambdec $(PREFIX)/bin
-	/usr/bin/install -m 755 ambdec_cli $(PREFIX)/bin
-	/usr/bin/install -d $(SHARED)/ambdec
-	/usr/bin/install -m 644 ../share/* $(SHARED)/ambdec
+	/bin/install -Dm 755 ambdec temp$(PREFIX)/bin/ambdec
+	/bin/install -Dm 755 ambdec_cli temp$(PREFIX)/bin/ambdec_cli
+	/bin/install -d temp$(SHARED)/ambdec
+	/bin/install -m 644 ../share/* temp$(SHARED)/ambdec
 
 
 clean:
