#!/bin/sh

export GTK_PATH="/opt/lib32/usr/lib/gtk-2.0/"
export PANGO_RC_FILE="/opt/lib32/config/pango/pangorc"
export LD_LIBRARY_PATH="/opt/lib32/usr/lib/zattoo:/opt/lib32/usr/lib/:/opt/lib32/lib/:$LD_LIBRARY_PATH"
exec /opt/bin32-zattoo/bin/zattoo "$@"
