# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Matanya Moses <matanya@foss.co.il>

_gemname=capistrano-campfire
pkgname=ruby-$_gemname
pkgver=0.2.1
pkgrel=1
pkgdesc='Post to Campfire from capistrano'
arch=(any)
url='http://github.com/technicalpickles/capistrano-campfire'
license=(MIT)
depends=(ruby ruby-capistrano ruby-tinder)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('ddd29e9ca00a463d9e6966617160aa417f9fa091')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
