post_install() {

cat << EOF

To enable the cdemu service at boot, run the following command as root:
systemctl enable cdemu.service

To manually start the service (without having to reboot), run the following command as root:
systemctl start cdemu.service

EOF
post_upgrade

}

post_upgrade() {

cat << EOF

Before removing the cdemu service, run the following commands as root:

systemctl stop cdemu.service
systemctl disable cdemu.service

EOF

}
