# Maintainer: RubenKelevra <cyrond@gmail.com>

pkgname=rk-desktop-gnome-removenative
pkgver=2014.2.14
pkgrel=1
pkgdesc="Metapackage that removes some useless native-gnome apps."
url="http://notyetthere.com"
arch=('i686' 'x86_64')
license=('GPLv3')
makedepends=("yaourt"
)
depends=(
)
conflicts=("rk-desktop-gnome-native"
"gnome-contacts"
"empathy"
"telepathy-gabble"
"telepathy-idle"
"telepathy-salut"
"telepathy-rakia"
"telepathy-haze"
"telepathy-farstream"
"epiphany"
"totem"
"totem-plugin"
"grilo-plugins"
"bijiben"
"brasero"
"evolution"
"evolution-data-server"
"gedit"
"nautilus"
"libnautilus-extension"
"folks"
"nautilus-sendto"
"seahorse-nautilus"
"gnome-photos"
"cheese"
"gnome-video-effects"
"devhelp"
"gnome-clocks"
"gnome-devel-docs"
"gnome-documents"
"unoconv"
"gnome-maps"
"gnome-music"
)
optdepends=(
)
