#!/bin/bash

if [ ${UID} -ne 0 ]
then
	echo "$0 : you must be root to do that !" 1&>2
	exit 1
fi

Backup=0
Rom_dir="/usr/share/flash-ecafe"
Rom_old="EC_R026.rom"
Rom_new="EC_R044.rom"
Backup_dir=~/BIOS
Log="flash-ecafe.log"

Erreur ()
{
	echo "Erreur ! Abandon."
	exit 1
}

echo "****************************************************"
echo "Ce programme va flasher le BIOS de votre carte mère."
echo "****************************************************"
echo "Les 2 BIOS (ancien et nouveau) ainsi qu'un fichier"
echo "log seront sauvegardés dans ${Backup_dir}"
echo "****************************************************"
echo "ATTENTION, le clavier est buggé avec le"
echo "nouveau BIOS. Voir le forum d'archlinux.fr"
echo "pour plus de détails."
echo "http://forums.archlinux.fr/post32209.html#p32209"
echo "****************************************************"
echo "!!! ATTENTION !!! L'ordinateur s'éteindra à la fin"
echo "du processus. Sauvegardez tous vos travaux en cours"
echo "avant de continuer."
echo "****************************************************"
read -p "Continuer ? (o/n) : "
[[ ${REPLY} == 'o' ]] || [[ ${REPLY} == 'O' ]] || exit 1

{
	mkdir "${Backup_dir}" || Erreur
	cp "${Rom_dir}/${Rom_new}" "${Backup_dir}" || Erreur
	/usr/share/flash-ecafe/afulnx_32 "${Backup_dir}/${Rom_old}" /O || Erreur
	/usr/share/flash-ecafe/afulnx_32 "${Rom_dir}/${Rom_new}" /E || Erreur
	# ATTENTION !!! Ici, le PC s'éteint !
} 2>&1 | tee "${Backup_dir}/${Log}"

