--- Makefile	2009-08-27 14:12:41.000000000 +0200
+++ Makefile.chevorrei	2009-08-27 14:13:45.000000000 +0200
@@ -28,7 +28,8 @@
 autowah_if.o:	ladspaplugin.h autowah.h
 
 install:	all
-	cp  *.so /usr/lib/ladspa
+	mkdir -p $(DESTDIR)/usr/lib/ladspa
+	cp  *.so $(DESTDIR)/usr/lib/ladspa
 
 clean:
 	/bin/rm -f *~ *.o *.so
