## arg 1:  the new package version
post_install() {
  echo
  echo "As per the installation notes at http://tt-rss.org/redmine/wiki/tt-rss/InstallationNotes"
  echo "you must perform the following steps to finish installing tt-rss:"
  echo "1. Install database schema (schema/ttrss_schema_XXXX.sql) into your database"
  echo "2. Copy config.php-dist to config.php and edit it (you have to fill in database configuration parameters, but it is recommended to look over entire configuration" 
  echo
}
