show_message() {
   echo ">>> If you use KDE, two optional plasmoids can be downloaded from here:"
   echo ">>> http://s.insynchq.com/builds/insync.plasmoid"
   echo ">>> http://s.insynchq.com/builds/gdrive_webview.plasmoid"
   echo ">>> Help installing Plasmoids:"
   echo ">>> http://userbase.kde.org/Plasma/Installing_Plasmoids"
}

post_install() {
   show_message
}

post_upgrade() {
   show_message
}

post_remove() {
   return 1
}
