# Generated by Xyne::Arch::CPAN 0.07

pkgname=perl-podlators
pkgver=2.3.1
pkgrel=3
pkgdesc="Convert POD data to various other formats"
arch=('i686' 'x86_64')
url="http://search.cpan.org/dist/podlators/"
license=('perl')
source=('http://search.cpan.org/CPAN/authors/id/R/RR/RRA/podlators-2.3.1.tar.gz')
md5sums=('ec01b306c60a5bea04b533f12ce63742')
sha256sums=('20238600f4aa4b4f88bb6ec436601fbf5de5d8094c4e24f11722c83d979b6ef0')
depends=('perl-file-spec>=0.800.0' 'perl-pod-simple>=3.60.0')
makedepends=('perl-extutils-makemaker')
provides=('perl-pod-man=2.230.0' 'perl-pod-parselink=1.100.0' 'perl-pod-text-color=2.60.0' 'perl-pod-text-overstrike=2.40.0' 'perl-pod-text-termcap=2.60.0' 'perl-pod-text=3.140.0')
options=(!emptydirs)

build() {
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Makefile.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor || return 1
    make  || return 1
    make install DESTDIR="${pkgdir}" || return 1

  else
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Build.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Build.PL INSTALLDIRS=vendor || return 1
    ./Build  || return 1
    ./Build install destdir=${pkgdir} || return 1

  else
    echo "error: failed to detect build method for $pkgname"
    echo "you may be able to fix this by editing the PKGBUILD"
    return 1
  fi fi

  # remove perllocal.pod and .packlist
  find ${pkgdir} -name perllocal.pod -delete
  find ${pkgdir} -name .packlist -delete
}

# vim:set ts=2 sw=2 et:


