pkgname=mate-media

post_install() {
  usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas
  usr/sbin/mateconfpkg --install ${pkgname}
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

pre_upgrade() {
  pre_remove $1
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  usr/sbin/mateconfpkg --uninstall ${pkgname}
  usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas
}

post_remove() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}
