post_install() {
    ln -s '/usr/lib/systemd/system/keyboardctl.service' '/etc/systemd/system/sysinit.target.wants/keyboardctl.service'
}

post_upgrade() {
    rm '/etc/systemd/system/sysinit.target.wants/keyboardctl.service'
    ln -s '/usr/lib/systemd/system/keyboardctl.service' '/etc/systemd/system/sysinit.target.wants/keyboardctl.service'
}

pre_remove() {
    rm '/etc/systemd/system/sysinit.target.wants/keyboardctl.service'
}
