# Contributor: Arch Haskell Team <arch-haskell@haskell.org>
# Package generated by cabal2arch 0.3.4
pkgname=haskell-enumsets
pkgrel=1
pkgver=0.4
pkgdesc="Efficient Sets for Small Enumerations"
url="http://hackage.haskell.org/cgi-bin/hackage-scripts/package/enumsets"
license=('custom:BSD3')
arch=('i686' 'x86_64')
makedepends=('ghc' 'haskell-collections-api')
source=(http://hackage.haskell.org/packages/archive/enumsets/0.4/enumsets-0.4.tar.gz)
install=haskell-enumsets.install
md5sums=('c93047bfc04a26bd85a4cd2b6568c1c3')
build() {
    cd $startdir/src/enumsets-0.4
    runhaskell Setup configure --prefix=/usr || return 1
    runhaskell Setup build                   || return 1
    runhaskell Setup register   --gen-script || return 1
    runhaskell Setup unregister --gen-script || return 1
    install -D -m744 register.sh   $startdir/pkg/usr/share/haskell/$pkgname/register.sh
    install    -m744 unregister.sh $startdir/pkg/usr/share/haskell/$pkgname/unregister.sh
    runhaskell Setup copy --destdir=$startdir/pkg || return 1
    install -D -m644 LICENSE $startdir/pkg/usr/share/licenses/$pkgname/LICENSE || return 1
}
