# arg 1:  the new package version
post_install() {
groupadd -g 233 leterrier
chgrp leterrier /var/leterrier/ -R

echo "Add your user to group 'leterrier' to use all leterrier applications."
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $1
}

# arg 1:  the old package version
pre_remove() {
  usr/sbin/groupdel leterrier &>/dev/null
}

op=$1
shift
$op $*
