post_install() {
  echo "---------------------------------------------------------
Before using MPLAB C32 you have to agree with LICENSE:
/usr/share/licenses/microchip-mplabc32_bin/LICENSE

To use with MPALB X (microchip-mplabx-bin), in MPLAB X go to:
Tools->Options->Embedded->Add

and enter:
/opt/microchip/mplabc32/v2.02/bin
---------------------------------------------------------"
}

post_upgrade() {
  post_install
}
