# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Babken Vardanyan <483ken@gmail.com>

_gemname=arel-helpers
pkgname=ruby1.9-$_gemname
pkgver=2.0.1
pkgrel=1
pkgdesc='Useful tools to help construct database queries with ActiveRecord and Arel.'
arch=(any)
url='http://github.com/camertron'
license=()
depends=(ruby1.9 ruby1.9-activerecord)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('9a277f9e7f9dee8d82002098758204c776b8ea62')

package() {
  local _gemdir="$(ruby-1.9 -e'puts Gem.default_dir')"
  gem-1.9 install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
