post_install () {
  echo "==> To enable url-picker add the following to ~/.Xdefaults or ~/.Xresources"
  echo "==> (change to whatever suits your needs)"
  echo "==> URxvt.perl-ext-common:  default,url-picker"
  echo "==> URxvt.keysym.M-u:       perl:url-picker"
  echo ""
  echo "==> For wrapped URL functionality, the terminal must not interrupt the URL"
  echo "==> For example, if you are a mutt user, in your .muttrc file:"
  echo "==> set markers=no"
}

post_upgrade () {
  post_install $1
}

