post_install() {
	mkdir -p /var/{lib,log,run}/cassandra
	getent passwd cassandra > /dev/null || useradd -r -s /bin/sh -d /var/lib/cassandra cassandra
	chown cassandra:cassandra /var/{lib,run}/cassandra
	chown cassandra:log /var/log/cassandra
	systemctl load cassandra
}

pre_remove() {
  systemctl stop cassandra
}

post_remove() {
  userdel cassandra
  systemctl daemon-reload
}

post_upgrade() {
  systemctl daemon-reload
  systemctl try-restart cassandra
}