# This is a default template for a post-install scriptlet.
# Uncomment only required functions and remove any functions
# you don't need (and this header).

## arg 1:  the new package version
post_install() {
	systemctl --system daemon-reload
}

## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
	post_install
}

## arg 1:  the old package version
post_remove() {
	post_install
}
