#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID gw6c`
case "$1" in
   start)
     stat_busy "Starting Freenet6 Gateway client"
     [ -z "$PID" ] && gw6c
     if [ $? -gt 0 ]; then
       stat_fail
     else
       echo $PID > /var/run/gw6c.pid
       add_daemon gw6c
       stat_done
     fi
     ;;
   stop)
     stat_busy "Stopping Freenet6 Gateway client"
     [ ! -z "$PID" ]  && kill -HUP $PID > /dev/null
     if [ $? -gt 0 ]; then
       stat_fail
     else
       rm /var/run/gw6c.pid
       rm_daemon gw6c
       stat_done
     fi
     ;;
   restart)
     $0 stop
     sleep 1
     $0 start
     ;;
   *)
     echo "usage: $0 {start|stop|restart}"
esac
exit 0
