# Generated by Xyne::Arch::CPAN 0.07

pkgname=perl-net-z3950-zoom
pkgver=1.280.0
pkgrel=1
pkgdesc="Perl extension for invoking the ZOOM-C API."
arch=('i686' 'x86_64')
url="http://search.cpan.org/dist/Net-Z3950-ZOOM/"
license=('unknown')
source=('http://search.cpan.org/CPAN/authors/id/M/MI/MIRK/Net-Z3950-ZOOM-1.28.tar.gz')
md5sums=('812c3f22d7ee4a0b521ea6d94c78d22e')
sha256sums=('c8fef9e47cc7d4783966623efbf3e843d719cc93c4b5df9706b7e81b533d976a')
depends=('perl-marc-record>=1.380.0')
provides=('perl-net-z3950-op=0.990.0' 'perl-net-z3950=0.990.0' 'perl-zoom' 'perl-zoom-ccl-error' 'perl-zoom-connection' 'perl-zoom-error' 'perl-zoom-event' 'perl-zoom-exception' 'perl-zoom-log' 'perl-zoom-options' 'perl-zoom-package' 'perl-zoom-query' 'perl-zoom-query-ccl2rpn' 'perl-zoom-query-cql' 'perl-zoom-query-cql2rpn' 'perl-zoom-query-pqf' 'perl-zoom-record' 'perl-zoom-resultset' 'perl-zoom-scanset')
options=(!emptydirs)

build() {
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Makefile.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor || return 1
    make  || return 1
    make install DESTDIR="${pkgdir}" || return 1

  else
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Build.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Build.PL INSTALLDIRS=vendor || return 1
    ./Build  || return 1
    ./Build install destdir=${pkgdir} || return 1

  else
    echo "error: failed to detect build method for $pkgname"
    echo "you may be able to fix this by editing the PKGBUILD"
    return 1
  fi fi

  # remove perllocal.pod and .packlist
  find ${pkgdir} -name perllocal.pod -delete
  find ${pkgdir} -name .packlist -delete
}

# vim:set ts=2 sw=2 et:

