post_install() {
  # create user for uuidd
  if ! getent group uuidd >/dev/null; then
    groupadd -r uuidd
  fi

  if ! getent passwd uuidd >/dev/null; then
    useradd -r -s /sbin/nologin -d / -g uuidd uuidd
  fi

  # ensure /run/uuidd exists
  systemd-tmpfiles --create uuidd.conf
}

post_upgrade() {
  post_install
}

post_remove() {
  if getent passwd uuidd >/dev/null; then
    userdel uuidd
  fi

  if getent group uuidd >/dev/null; then
    userdel uuidd
  fi
}
