post_install() {
    cat <<EOF
==> Put this in your $HOME/.emacs file to enable tuareg-mode autoloading
==> and autorecognition of ocaml source files:

  (setq auto-mode-alist (cons '("\\\\.ml[iylp]?\\\\'" . tuareg-mode) auto-mode-alist))
  (autoload 'tuareg-mode "tuareg" "Major mode for editing Caml code" t)
  (autoload 'camldebug "camldebug" "Run the Caml debugger" t)
EOF
}


post_upgrade() {
	post_install $1
}

op=$1
shift
$op $*
