post_install()
{
echo " "
echo "add the following lines to your .emacs"
echo "==================================================================="
echo " "
echo "(require 'undo-tree)"
echo ";;if you want replace the standard Emacs' undo system with the undo-tree-mode,uncomment the next line"
echo ";(global-undo-tree-mode)"
echo " "
echo "==================================================================="
echo " "
    
}

post_upgrade()
{
    post_install
}
