#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/sbin/verynice-fork`
case "$1" in
  start)
    stat_busy "Starting VeryNice-fork"
    [ -z "$PID" ] && su -s /bin/sh -c "/usr/sbin/verynice-fork &> /dev/null &"
    if [ $? -gt 0 ]; then
      stat_fail
    else
      echo $PID > /var/run/verynice-fork.pid
      add_daemon verynice-fork
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping VeryNice-fork"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm /var/run/verynice-fork.pid
      rm_daemon verynice-fork
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0

