post_install() {
	# This is easy to automate. Do it!
	sed -i 's/^[^#]/#&/' /etc/acpi/events/anything

	echo ">>> See /etc/acpi/eee.conf for configurable options."
	#echo ">>>"
	#echo ">>> To enable fsb settings at boot add DAEMONS=(... fsb ...) to your rc.conf"
	#echo ">>>"
}

post_upgrade() {
    echo ">>> Check /etc/acpi/eee.conf for new options every time you update"
    #echo ">>>"
    #echo ">>> To enable fsb settings at boot add DAEMONS=(... fsb ...) to your rc.conf"
    #echo ">>>"
}
