.\" Process this file with
.\" groff -man -Tascii sodium.1
.\"
.TH SODIUM 1 "JANUARY 2001" "sodium-1.6" "User commands"
.SH NAME
sodium \- Arrange ions around biological macromolecules
.SH SYNOPSIS
\fBsodium\fR [\fB<\fIconfig-file\fR] [\fB>\fIlog-file\fR] [\fB&\fR]
.SH DESCRIPTION
This program places the required number of sodium ions around a system of
electric charges, e.g., the atoms of a biological macromolecule (protein, DNA,
protein/DNA complex).
The ions are placed in the nodes of a cubic grid, in which the electrostatic
energy achieves the smallest values.
The energy is re-computed after placement of each ion.
A simple Coulombic formula is used for the energy:

	Energy(R) = Sum(i_atoms,ions)  Q_i / |R-R_i| .

All the constants are dropped out from this formula, resulting in some weird
energy units; that doesn't matter for the purpose of energy comparison.

To speed the program up, the atoms of the macromolecule are re-located to the
grid nodes, closest to their original locations.
The resulting error is believed to be minor, compared to that resulting from
the one-by-one ions placement, or from using the simplified energy function.

The coordinates of the placed ions are printed out in the PDB format for
further usage.
It is recommended that the placed ions are equilibrated in a separate Monte
Carlo or Molecular Dynamics simulation.

Trivial modifications to the program should allow the placement of any
combination of multivalent ions of different charges.
.SH SPEED AND MEMORY REQUIREMENTS
The requested memory and speed heavily depend on the number of atoms in the
macromolecule (as a linear function) and the cell size of the used grid (as an
inverse cube).
For 24,000 atoms, 0.5 A grid and 48 ions to place, the program required 74Mb of
RAM and was executed in about 1.5 hours on a single DEC Alpha processor.
.SH A SAMPLE CONFIGURATION FILE
NUM_IONS      48
.br
R_ION_PRODNA  6.5
.br
R_ION_ION     11.0
.br
GRID_STEP     0.5
.br
BORDER_WIDTH  10.0
.br
PDB_NAME      lac_w_dna_charges_orient.pdb
.br
PDB_OUT       ions_0.5.pdb
.SH  EXPLANATION OF THE CONFIGURATION PARAMETERS
NUM_IONS
.RS
the number of ions to place around the macromolecule.
.RE
R_ION_PRODNA
.RS
the closest distance (in Angstroms) allowed between any of the placed ions and
any atom of the macromolecule.
Due to an error in atomic positions, introduced by using the grid, it is
recommended to make this parameter slightly larger than the actually allowed
closest distance.
.RE
R_ION_ION
.RS
the closest distance between any two ions (in Angstroms).
This parameter prevents the placed ions from clustering around a single
negative charge, and would prevent positively and negatively charged ions from
being placed too close to each other.  Setting this parameter to zero relies on
the "natural" electrostatic repulsion between the placed ions to prevent the
ions from coming too close.

.RE
GRID_STEP
.RS
the cell size of the cubic grid on which the ions are placed (in Angstroms).
Grids with smaller cells allow more precise placement (in part, due to the
least disturbance of the macromolecular atoms, relocated to the grid nodes).
However, a finer grid slows the computations down and requires significantly
more RAM.
.RE
BORDER_WIDTH
.RS
the thickness of the grid margin, surrounding the macromolecule (in Angstroms).
.RE
PDB_NAME
.RS
the name of the file, containing the coordinates of the atoms of the
macromolecule in PDB format.
The 10th column (B column) of the PDB file should contain the charges of the
atoms.
Such file can be generated from a usual PDB/PSF couple, e.g., by using the
following X-PLOR (http://atb.csb.yale.edu/xplor) script:

  structure @lac_w_dna.psf end
  coor @lac_w_dna.pdb
    vector do (B=CHARGE) (all)
    write coor output="lac_w_dna_charges.pdb" end
    stop

To reduce the number of nodes in the grid, it is also recommended that the
molecule has its axes of inertia aligned along the axes of the coordinate
system.
This can be achieved by using another X-PLOR script:

  structure @lac_w_dna.psf end
    coor @lac_w_dna_charges.pdb
    coor orient end
    write coor output="lac_w_dna_charges_orient.pdb" end
    stop
.RE
PDB_OUT
.RS
the name for the PDB file which will contain the coordinates of the placed
ions.
.RE
.SH AUTHOR
Alexander Balaeff <sure@ks.uiuc.edu>
