'\" t
.\"     Title: bardecode
.\"    Author: Jakub Wilk <jwilk@debian.org>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 08/15/2014
.\"    Manual: ExactImage Manual
.\"    Source: bardecode
.\"  Language: English
.\"
.TH "BARDECODE" "1" "08/15/2014" "bardecode" "ExactImage Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
bardecode \- barcode recognition tool of the ExactImage toolkit
.SH "SYNOPSIS"
.HP \w'\fBbardecode\fR\ 'u
\fBbardecode\fR [\fIoption\fR...] \fIfile\fR...
.HP \w'\fBbardecode\fR\ 'u
\fBbardecode\fR {\fB\-h\fR | \fB\-\-help\fR}
.SH "DESCRIPTION"
.PP
ExactImage is a fast C++ image processing library\&. Unlike many other library frameworks it allows operation in several color spaces and bit depths natively, resulting in low memory and computational requirements\&.
.PP
\fBbardecode\fR
is a barcode recognition tool\&.
.SH "OPTIONS"
.PP
\fB\-t \fR\fB\fIn\fR\fR, \fB\-\-threshold \fR\fB\fIn\fR\fR
.RS 4
Set bi\-level threshold value to
\fIn\fR\&. The default is 150\&.
.RE
.PP
\fB\-c n\fR, \fB\-\-concurrent\-lines n\fR
.RS 4
Set number of lines that are scanned concurrently\&. The default is 4\&.
.RE
.PP
\fB\-s \fR\fB\fIn\fR\fR, \fB\-\-line\-skip \fR\fB\fIn\fR\fR
.RS 4
Set number of lines that are skipped\&. The default is 8\&.
.RE
.PP
\fB\-d \fR\fB\fIn\fR\fR, \fB\-\-directions \fR\fB\fIn\fR\fR
.RS 4
Set bitfield of directions to be scanned:
.PP
0
.RS 4
none
.RE
.PP
1
.RS 4
left\-to\-right
.RE
.PP
2
.RS 4
top\-down
.RE
.PP
4
.RS 4
right\-to\-left
.RE
.PP
8
.RS 4
down\-top
.RE
.PP
15
.RS 4
any
.RE
.sp
The default is 15 (any)\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Display help text and exit\&.
.RE
.SH "EXAMPLES"
.sp
.if n \{\
.RS 4
.\}
.nf
$ bardecode files/*
files/1\&.tif: XDM152EU\-U [type: code39 at: (1094,392)]
files/2\&.tif: 471186080198 [type: ean13 at: (1148,32)]
files/3\&.tif: 06396500104997 [type: code128 at: (578,83)]
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
\fBexactimage\fR(7)
.SH "AUTHORS"
.PP
\fBJakub Wilk\fR <\&jwilk@debian\&.org\&>
.RS 4
Wrote this manual page for the Debian system\&.
.RE
.PP
\fB\m[blue]\fB\%http://www.exactcode.de/site/open_source/exactimage/\fR\m[]\fR
.RS 4
This manual page incorporates texts found on the ExactImage homepage\&.
.RE
.SH "COPYRIGHT"
.br
.PP
This manual page was written for the Debian system (and may be used by others)\&.
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or (at your option) any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in
/usr/share/common\-licenses/GPL\-2\&.
.sp
