'\" t
.\"     Title: edentify
.\"    Author: Jakub Wilk <jwilk@debian.org>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 08/15/2014
.\"    Manual: ExactImage Manual
.\"    Source: edentify
.\"  Language: English
.\"
.TH "EDENTIFY" "1" "08/15/2014" "edentify" "ExactImage Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
edentify \- image indentifiction tool of the ExactImage toolkit
.SH "SYNOPSIS"
.HP \w'\fBedentify\fR\ 'u
\fBedentify\fR [{\fB\-f\fR\ |\ \fB\-\-format\fR}\ \fIformat\-string\fR] [\fB\-v\fR\ |\ \fB\-\-verbose\fR] \fIfile\fR...
.HP \w'\fBedentify\fR\ 'u
\fBedentify\fR {\fB\-h\fR | \fB\-\-help\fR}
.SH "DESCRIPTION"
.PP
ExactImage is a fast C++ image processing library\&. Unlike many other library frameworks it allows operation in several color spaces and bit depths natively, resulting in low memory and computational requirements\&.
.PP
\fBedentify\fR
is is a command line frontend for the image processing library and mimicks ImageMagick\*(Aqs
\fBidentify\fR\&. It is used to identify images, that is print the codec, pixel dimensions, resolution and physical sizes (if any resolution is specified in the image data) as well as the color space\&.
.SH "OPTIONS"
.PP
\fB\-f \fR\fB\fIformat\-string\fR\fR, \fB\-\-format \fR\fB\fIformat\-string\fR\fR
.RS 4
Set a user\-defined format string\&. You can use the following format characters:
.PP
%d
.RS 4
directory
.RE
.PP
%f
.RS 4
filename
.RE
.PP
%t
.RS 4
filename without extension
.RE
.PP
%e
.RS 4
filename extension
.RE
.PP
%i
.RS 4
path (directory + filename)
.RE
.PP
%w
.RS 4
width
.RE
.PP
%h
.RS 4
height
.RE
.PP
%q
.RS 4
quantum depth
.RE
.PP
%x
.RS 4
x resolution
.RE
.PP
%y
.RS 4
y resolution
.RE
.PP
%z
.RS 4
image depth
.RE
.PP
%P
.RS 4
page width and height
.RE
.PP
%%
.RS 4
literal percent character
.RE
.PP
t
.RS 4
new line character
.RE
.PP
n
.RS 4
new line character
.RE
.PP
r
.RS 4
carriage return character
.RE
.RE
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
Make the output more verbose\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Display help text and exit\&.
.RE
.SH "EXAMPLES"
.sp
.if n \{\
.RS 4
.\}
.nf
$ edentify lenea\&.tiff
lenea\&.tiff: TIFF 512x512 24 bits, 3 channels
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
\fBexactimage\fR(7)
.SH "AUTHORS"
.PP
\fBJakub Wilk\fR <\&jwilk@debian\&.org\&>
.RS 4
Wrote this manual page for the Debian system\&.
.RE
.PP
\fB\m[blue]\fB\%http://www.exactcode.de/site/open_source/exactimage/\fR\m[]\fR
.RS 4
This manual page incorporates texts found on the ExactImage homepage\&.
.RE
.SH "COPYRIGHT"
.br
.PP
This manual page was written for the Debian system (and may be used by others)\&.
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or (at your option) any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in
/usr/share/common\-licenses/GPL\-2\&.
.sp
