'\" t
.\"     Title: empty-page
.\"    Author: Jakub Wilk <jwilk@debian.org>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 08/15/2014
.\"    Manual: ExactImage Manual
.\"    Source: empty-page
.\"  Language: English
.\"
.TH "EMPTY\-PAGE" "1" "08/15/2014" "empty-page" "ExactImage Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
empty-page \- empty page detector of the ExactImage toolkit
.SH "SYNOPSIS"
.HP \w'\fBempty\-page\fR\ 'u
\fBempty\-page\fR [\fIoption\fR...] {\fB\-i\fR\ |\ \fB\-\-input\fR}\ \fIinput\-file\fR 
.HP \w'\fBempty\-page\fR\ 'u
\fBempty\-page\fR {\fB\-h\fR | \fB\-\-help\fR}
.SH "DESCRIPTION"
.PP
ExactImage is a fast C++ image processing library\&. Unlike many other library frameworks it allows operation in several color spaces and bit depths natively, resulting in low memory and computational requirements\&.
.PP
\fBempty\-page\fR
counts dark pixels of a black and white image and decides with a threshold whether the page is most probably empty, and thus can be removed from the image processing stream\&.
.SH "OPTIONS"
.PP
\fB\-i \fR\fB\fIfile\fR\fR, \fB\-\-input \fR\fB\fIfile\fR\fR
.RS 4
Read image from the specified file\&.
.RE
.PP
\fB\-m \fR\fB\fIn\fR\fR, \fB\-\-margin \fR\fB\fIn\fR\fR
.RS 4
Set width of border margin to skip\&. For speed reasons, the margin has to be a multiple of 8\&. The default is 16\&.
.RE
.PP
\fB\-p \fR\fB\fIx\fR\fR, \fB\-\-percentage \fR\fB\fIx\fR\fR
.RS 4
Set fraction of permissible dark pixels\&. The default is
0\&.05
(5%)\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Display help text and exit\&.
.RE
.SH "EXAMPLES"
.sp
.if n \{\
.RS 4
.\}
.nf
$ empty\-page \-i test\&.tif
The image has 75461 dark pixels from a total of 1060992 (7\&.11231%)\&.
non\-empty
.fi
.if n \{\
.RE
.\}
.SH "EXIT STATUS"
.PP
The exit status is 0 if the image is mostly white, 1 otherwise\&.
.SH "SEE ALSO"
.PP
\fBexactimage\fR(7)
.SH "AUTHORS"
.PP
\fBJakub Wilk\fR <\&jwilk@debian\&.org\&>
.RS 4
Wrote this manual page for the Debian system\&.
.RE
.PP
\fB\m[blue]\fB\%http://www.exactcode.de/site/open_source/exactimage/\fR\m[]\fR
.RS 4
This manual page incorporates texts found on the ExactImage homepage\&.
.RE
.SH "COPYRIGHT"
.br
.PP
This manual page was written for the Debian system (and may be used by others)\&.
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or (at your option) any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in
/usr/share/common\-licenses/GPL\-2\&.
.sp
