'\" t
.\"     Title: hocr2pdf
.\"    Author: Jakub Wilk <jwilk@debian.org>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 08/15/2014
.\"    Manual: ExactImage Manual
.\"    Source: hocr2pdf
.\"  Language: English
.\"
.TH "HOCR2PDF" "1" "08/15/2014" "hocr2pdf" "ExactImage Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
hocr2pdf \- hOCR to PDF converter of the ExactImage toolkit
.SH "SYNOPSIS"
.HP \w'\fBhocr2pdf\fR\ 'u
\fBhocr2pdf\fR [\fIoption\fR...] {\fB\-i\fR\ |\ \fB\-\-input\fR}\ \fIinput\-file\fR  {\fB\-o\fR\ |\ \fB\-\-output\fR}\ \fIoutput\-file\fR 
.HP \w'\fBhocr2pdf\fR\ 'u
\fBhocr2pdf\fR {\fB\-h\fR | \fB\-\-help\fR}
.SH "DESCRIPTION"
.PP
ExactImage is a fast C++ image processing library\&. Unlike many other library frameworks it allows operation in several color spaces and bit depths natively, resulting in low memory and computational requirements\&.
.PP
\fBhocr2pdf\fR
creates well layouted, searchable PDF files from hOCR (annotated HTML) input obtained from an OCR system\&.
.SH "OPTIONS"
.PP
\fB\-i \fR\fB\fIfile\fR\fR, \fB\-\-input \fR\fB\fIfile\fR\fR
.RS 4
Read image from the specified file\&. Note that input hOCR is read from the standard input\&.
.RE
.PP
\fB\-o \fR\fB\fIfile\fR\fR, \fB\-\-output \fR\fB\fIfile\fR\fR
.RS 4
Save output PDF to the specified file\&.
.RE
.PP
\fB\-n\fR, \fB\-\-no\-image\fR
.RS 4
Don\*(Aqt place the image over the text\&. By default the text layer is hidden behind the image\&.
.RE
.PP
\fB\-s\fR, \fB\-\-sloppy\-text\fR
.RS 4
Sloppily place text, group words, do not draw single glyphs\&.
.RE
.PP
\fB\-r \fR\fB\fIn\fR\fR, \fB\-\-resolution \fR\fB\fIn\fR\fR
.RS 4
Override resolution of the input image to
\fIn\fR
dpi\&. The default resolution (if not specified in the input file) is 300 dpi\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Display help text and exit\&.
.RE
.SH "EXAMPLE"
.sp
.if n \{\
.RS 4
.\}
.nf
$ hocr2pdf \-i scan\&.tiff \-o test\&.pdf < cuneiform\-out\&.hocr
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
\fBexactimage\fR(7)
.SH "AUTHORS"
.PP
\fBJakub Wilk\fR <\&jwilk@debian\&.org\&>
.RS 4
Wrote this manual page for the Debian system\&.
.RE
.PP
\fB\m[blue]\fB\%http://www.exactcode.de/site/open_source/exactimage/\fR\m[]\fR
.RS 4
This manual page incorporates texts found on the ExactImage homepage\&.
.RE
.SH "COPYRIGHT"
.br
.PP
This manual page was written for the Debian system (and may be used by others)\&.
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or (at your option) any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in
/usr/share/common\-licenses/GPL\-2\&.
.sp
