_depmod() {
  _extramodules='extramodules-3.10-ARCH'
  depmod $(cat /usr/lib/modules/${_extramodules}/version)
}

post_install() {
    _depmod

cat << EOF
===> # modprobe snd-usb-hiface to load the module
EOF
}

post_upgrade() {
  _depmod 

  rmmod snd-usb-hiface || echo 'In order to use the new version, reload snd-usb-hiface manually.'
}

post_remove() {
  _depmod 

  rmmod snd-usb-hiface || echo 'Unload snd-usb-hiface'
}
