post_install() {
    cat << EOF
==> Plugins had been installed in both /usr/bin/pymunin-* and /usr/lib/munin/plugins/
==> To start using them with munin, just create symbolic links in the munin
==> plugins configuration directory (/etc/munin/plugins) then configure them
==> in /etc/munin/plugin-conf.d
==>
==> Ext Utils installed in /usr/share/pymunin/ext (opcinfo.php apcinfo.php)
EOF
}
# vim:set ts=2 sw=2 et:
