post_install() {
  update-desktop-database -q
  cat <<MSG
==> IMPORTANT TRACKIR SUPPORT:
    not included in this build check the linuxtrack-svn-wine-trackir package on the aur
    or copy the udev rule:
    cp /usr/share/linuxtrack/51-TIR.rules /etc/udev/rules.d/
    chmod 644 /usr/share/linuxtrack/51-TIR.rules
==> IMPORTANT VIRTUAL MOUSE SUPPORT:
    not compiled in this build check the linuxtrack-svn-wine-trackir package on the aur
MSG

}

post_upgrade() {
  post_install
}

post_remove() {
}