# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Babken Vardanyan <483ken@gmail.com>

_gemname=rspec-collection_matchers
pkgname=ruby1.9-$_gemname
pkgver=1.0.0
pkgrel=1
pkgdesc='rspec-collection_matchers-1.0.0'
arch=(any)
url='https://github.com/rspec/rspec-collection_matchers'
license=(MIT)
depends=(ruby1.9 ruby1.9-rspec-expectations)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('e6f147fbe9871d062b602e6f28fde703fbf81e48')

package() {
  local _gemdir="$(ruby-1.9 -e'puts Gem.default_dir')"
  gem-1.9 install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE.txt" "$pkgdir/usr/share/licenses/$pkgname/LICENSE.txt"
}
