post_install() {
echo '!!!!IMPORTANT!!!!'
echo "Run /usr/bin/openoffice-dark-gtk-fix.sh as root to use the script"
echo "By default it will fix libreoffice, if you use something else it should still work if you edit the OOO_INSTALLATION_DIR variable inside the script."
echo "You'll need to run the script each time you update openoffice."
echo '!!!!IMPORTANT!!!!'.
echo 'To uninstall, run the script with the --uninstall option'
}
