post_install() {
cat << _EOF

==> installation notes:
    ----------------------------------------
    ==> don't use cect599 its a future feature for ipod, psp,...
    ==> divx4linux for encode divx
    ==> faac for encode audio AAC
    ==> you can use the mount point to encode dvd , iso 
    ----------------------------------------
==> neodivxlazarus 1.2.0.978 (03/07/2008) neodivx@neodivx.be

_EOF

}

post_upgrade() {
	post_install
}

op=$1
shift
$op $*
