# arg 1:  the new package version
# arg 2:  the old package version

KERNEL_NAME=-nx
KERNEL_VERSION=2.6.39-nx

post_install () {
  # updating module dependencies
  echo ">>> Updating module dependencies. Please wait ..."
  depmod $KERNEL_VERSION 
  # generate init ramdisks
  echo ">>> MKINITCPIO SETUP"
  echo ">>> ----------------"
  echo ">>> Generating initial ramdisk, using mkinitcpio.  Please wait..."
  /sbin/mkinitcpio -p kernel26${KERNEL_NAME}
}

post_upgrade() {
  post_install
}
