57d56
< AR = ar
59d57
< STRIP = strip
100c98
< 	$(AR) cr $@ $^
---
> 	$(AR) crs $@ $^
118c116
< 		-e "s|@libname@|GLEW|g" \
---
> 		-e "s|@libname@|glew32|g" \
150c148
< 		-e "s|@libname@|GLEWmx|g" \
---
> 		-e "s|@libname@|glew32mx|g" \
