102c102
< 	$(AR) cr $@ $^
---
> 	$(AR) crs $@ $^
127c127
< .PHONY: glew.pc
---
> #.PHONY: glew.pc
137c137
< 		-e "s|@libname@|GLEW|g" \
---
> 		-e "s|@libname@|glew32|g" \
177c177
< 		-e "s|@libname@|GLEWmx|g" \
---
> 		-e "s|@libname@|glew32mx|g" \
