56d55
< AR = ar
70c69
< LIB.OBJS = $(LIB.SRCS:.c=.o)
---
> LIB.OBJS = $(LIB.SRCS:.c=.static_o)
92c91
< 	$(AR) cr $@ $^
---
> 	$(AR) crs $@ $^
110a110,112
> src/glew.static_o: src/glew.c include/GL/glew.h include/GL/wglew.h include/GL/glxew.h
> 	$(CC) $(CFLAGS) -DGLEW_STATIC -o $@ -c $<
> 
147a150
> 	$(INSTALL) -m 0644 lib/$(LIB.STATIC) $(LIBDIR)/
150d152
< 	$(INSTALL) -m 0644 lib/$(LIB.STATIC) $(LIBDIR)/
