#!/bin/bash
#Author F. Boulogne fboulogne at april.org
#GPLV3.
. /etc/rc.conf
. /etc/rc.d/functions


PID=`pidof -o %PPID /usr/bin/lvpnc`
case "$1" in
  start)
    stat_busy "Starting vpnautoconnect Daemon"
      [ -z "$PID" ] && /usr/bin/lvpnc -c /etc/vpnautoconnect.cfg &>/dev/null
      if [ $? -gt 0 ]; then
        stat_fail
      else
        add_daemon vpnautoconnect
        stat_done
      fi
    ;;
  stop)
    stat_busy "Stopping vpnautoconnect Daemon"
    [ ! -z "$PID" ] && kill -INT $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon vpnautoconnect
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 3
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
# vim: ft=sh ts=2 sw=2
