#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
    stat_busy "Starting polipo"
    polipo daemonise=true
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon polipo
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping polipo"
    kill `pidof /usr/bin/polipo`
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon polipo
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
    ;;
esac
