post_install() {
  echo ">>> Updating module dependencies..."
  /sbin/depmod -a
  echo ">>> Reloading virtualbox modules..."
  local modules=()
  for module in vbox{netflt,netadp,drv}; do
    if grep -q "^$module" /proc/modules; then
      modprobe -r "$module"
      modules+=("$module")
    fi
  done
  for module in "${modules[@]}"; do
      modprobe "$module"
  done
}

post_upgrade() {
  post_install
}