# Maintainer: Evan Teitelman <teitelmanevan at gmail dot com>

pkgname=python2-everything
pkgver=1.1
pkgrel=1
pkgdesc="Includes all of the Python2 packages in the official repos"
arch=(x86_64 i686)
url="https://github.com/EvanTeitelman/pkgbuilds"
license=('custom')
depends=(python2-antlr2
python2-atspi
python2-beaker
python2-bonobo
python2-cairo
python2-chardet
python2-crypto
python2-cssselect
python2-dbus
python2-distribute
python2-django
python2-egenix-mx-base
python2-egg
python2-feedparser
python2-fpconst
python2-gconf
python2-gdata
python2-geoip
python2-gksu2
python2-gnomecanvas
python2-gnomedesktop
python2-gnomekeyring
python2-gnomevfs
python2-gobject
python2-gobject2
python2-gtkhtml2
python2-gtkspell
python2-gtop
python2-iwscan
python2-libgnome
python2-logilab-astng
python2-logilab-common
python2-lxml
python2-mako
python2-markupsafe
python2-metacity
python2-mpd
python2-nose
python2-notify
python2-numpy
python2-opengl
python2-pip
python2-pyasn1
python2-pycurl
python2-pygame
python2-pylint
python2-pyopenssl
python2-pyqt4
python2-pyspi
python2-pysqlite
python2-qscintilla
python2-rdflib
python2-rsvg
python2-sip
python2-soappy
python2-speechd
python2-telepathy
python2-totem-plparser
python2-urwid
python2-virtualenv
python2-wnck
python2-wpactrl
python2-xdg
python2-zope-interface
python2-application
python2-apptools
python2-babel
python2-basemap
python2-beautifulsoup3
python2-beautifulsoup4
python2-boto
python2-bottle
python2-bsddb
python2-cchardet
python2-cheetah
python2-cherrypy
python2-cjson
python2-configglue
python2-configobj
python2-cssutils
python2-cx_freeze
python2-dateutil
python2-decorator
python2-dirspec
python2-distutils-extra
python2-dnspython
python2-docs
python2-docutils
python2-envisage
python2-eyed3
python2-flask
python2-flup
python2-fonttools
python2-foolscap
python2-formencode
python2-fuse
python2-gasp
python2-genshi
python2-geotypes
python2-gevent
python2-gevent-beta
python2-gflags
python2-gnupginterface
python2-gnutls
python2-greenlet
python2-grequests
python2-gtkspellcheck
python2-html5lib
python2-httplib2
python2-imaging
python2-iniparse
python2-ipaddr
python2-ipy
python2-irc
python2-isodate
python2-itsdangerous
python2-jinja
python2-keybinder2
python2-lcms
python2-ldap
python2-lockfile
python2-m2crypto
python2-marisa
python2-markdown
python2-matplotlib
python2-mechanize
python2-meld3
python2-memcached
python2-migrate
python2-mpdclient2
python2-mpi4py
python2-munkres
python2-musicbrainz2
python2-musicbrainzngs
python2-mysql2pgsql
python2-nautilus
python2-ndg-httpsclient
python2-netifaces
python2-nltk
python2-numarray
python2-numexpr
python2-oauth
python2-oauthlib
python2-openbabel
python2-packagekit
python2-paramiko
python2-pdfrw
python2-pexpect
python2-poppler
python2-progressbar
python2-protobuf
python2-psutil
python2-psycopg1
python2-psycopg2
python2-pyacoustid
python2-pybluez
python2-pycdio
python2-pychart
python2-pychm
python2-pycountry
python2-pycuda
python2-pyenchant
python2-pyface
python2-pygit2
python2-pygments
python2-pyinotify
python2-pylast
python2-pylorcon
python2-pymongo
python2-pyopencl
python2-pyparsing
python2-pyproj
python2-pyquery
python2-pyro
python2-pyserial
python2-pysqlite-legacy
python2-pytables
python2-pytools
python2-pytz
python2-pyudev
python2-pyxattr
python2-pyxmpp
python2-pyzmq
python2-reportlab
python2-requests
python2-rope
python2-rsa
python2-rst2pdf
python2-scipy
python2-sensors
python2-sh
python2-simplejson
python2-six
python2-slip
python2-south
python2-sphinx
python2-sqlalchemy
python2-sqlobject
python2-stevedore
python2-sympy
python2-tagpy
python2-tempita
python2-termcolor
python2-tornado
python2-traits
python2-traitsui
python2-ubuntuone-storageprotocol
python2-unidecode
python2-virtkey
python2-virtualenv-clone
python2-vobject
python2-vorbissimple
python2-webpy
python2-werkzeug
python2-xapian
python2-xlib
python2-yaml)

package() {
  :
}
