# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Rhys Davies <rhys@johnguant.com>

_gemname=dbd-sqlite
pkgname=ruby-$_gemname
pkgver=0.1.2
pkgrel=1
pkgdesc='SQLite 2.x DBI DBD'
arch=(any)
url='http://www.rubyforge.org/projects/ruby-dbi'
license=()
depends=(ruby ruby-dbi ruby-sqlite-ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('39a6269c964c2fbd66abf9917f99783b889a0430')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
