pkgname=sidplay-residfp

post_install() {
  cat << _EOF 

==> IMPORTANT!
==> This package provides a sidplay2.ini file in /usr/share/sidplay-residfp
==> (If you updated from 0.1.1 or earlier, the settings are very different,
     so be sure to look at the provided sidplay2.ini)
==> To use it, do the following as the users you use sidplay-residfp with:
==> mkdir ~/.sidplay
==> cp /usr/share/sidplay-residfp/sidplay2.ini ~/.sidplay/sidplay2.ini
==> (and edit it to fit your needs)

_EOF
}
