reload_udev() {
	echo " > Reloading udev."
	udevadm control --reload
}

post_install() {
	if ! getent group yubikey > /dev/null 2>&1; then
		echo " > Adding group 'yubikey', add your users there"
		echo " > to have them access the Yubico Key."
		groupadd -g 621 yubikey
	fi
	reload_udev
}

post_upgrade() {
	post_install
}

post_remove() {
	if getent group yubikey > /dev/null 2>&1; then
		echo " > Removing yubikey group."
		groupdel yubikey
	fi
	reload_udev
}
