Index: Makefile
===================================================================
--- Makefile	(revision 615)
+++ Makefile	(working copy)
@@ -30,8 +30,8 @@
 
 #By default, 'make' compiles X11 version on local platform
 all: .DEPENDS skype_messaging_x11.c skype_messaging_dbus.c
-	gcc ${LIBPURPLE_CFLAGS} -Wall -pthread ${GLIB_CFLAGS} -I. -g -pipe libskype.c -o libskype.so -shared -fPIC -DPIC
-	gcc ${LIBPURPLE_CFLAGS} -Wall -pthread ${GLIB_CFLAGS} -I. -g -pipe libskype.c -o libskype_dbus.so -shared -fPIC -DPIC ${DBUS_CFLAGS}
+	$(CC) ${LIBPURPLE_CFLAGS} -Wall -pthread ${GLIB_CFLAGS} $(CFLAGS) $(LDFLAGS) -I. -g libskype.c -o libskype.so -shared -fPIC -DPIC
+	$(CC) ${LIBPURPLE_CFLAGS} -Wall -pthread ${GLIB_CFLAGS} $(CFLAGS) $(LDFLAGS) -I. -g libskype.c -o libskype_dbus.so -shared -fPIC -DPIC ${DBUS_CFLAGS}
 
 install: locales
 	mkdir -p $(DESTDIR)/usr/share/pixmaps/pidgin/emotes/skype
