--- Makefile.orig	2012-11-22 17:29:12.139095366 +0100
+++ Makefile	2012-11-22 17:30:17.662190248 +0100

@@ -31,8 +31,8 @@
 
 #By default, 'make' compiles X11 and DBus versions on local platform
 all: .DEPENDS skype_messaging_x11.c skype_messaging_dbus.c
-	gcc ${LIBPURPLE_CFLAGS} -Wall -pthread ${GLIB_CFLAGS} -I. -g -pipe libskype.c -o libskype.so -shared -fPIC -DPIC ${X11_LIBS}
-	gcc ${LIBPURPLE_CFLAGS} -Wall -pthread ${GLIB_CFLAGS} -I. -g -pipe libskype.c -o libskype_dbus.so -shared -fPIC -DPIC ${DBUS_CFLAGS}
+	$(CC) ${LIBPURPLE_CFLAGS} -Wall -pthread $(CFLAGS) $(LDFLAGS) ${GLIB_CFLAGS} -I. -g -pipe libskype.c -o libskype.so -shared -fPIC -DPIC ${X11_LIBS}
+	$(CC) ${LIBPURPLE_CFLAGS} -Wall -pthread $(CFLAGS) $(LDFLAGS) ${GLIB_CFLAGS} -I. -g -pipe libskype.c -o libskype_dbus.so -shared -fPIC -DPIC ${DBUS_CFLAGS}
 
 install: locales
 	mkdir -p $(DESTDIR)/usr/share/pixmaps/pidgin/emotes/skype
