post_install()
{
    echo    "---------------------------------------------------------------------------------"
    echo    "Please make sure you are running Minecraft at least once before using this script"
    echo    "---------------------------------------------------------------------------------"
}

post_upgrade()
{
    echo    "---------------------------------------------------------------------------------"
    echo    "Please make sure you are running Minecraft at least once before using this script"
    echo    "---------------------------------------------------------------------------------"
}
