.TH "ihu" "1" "January 2007" "I Hear U" "User Commands"
.SH "NAME"
.LP 
IHU \- Peer-to-peer (P2P) Voice-over-IP (VoIP) application
.SH "SYNTAX"
.LP 
ihu [OPTIONS]
.SH "DESCRIPTION"
.LP 
I Hear U (IHU) is a Voice-over-IP (VoIP) application for Linux that
creates an audio stream between two computers easily and with the
minimal traffic on the network.

Its main features are:

 * Peer-to-Peer: the communication takes place directly between the
   computers (UDP and TCP both supported), without need of session
   protocols (such as SIP or H323) or other servers in the middle.

 * Good audio performance: IHU was born to give the best audio
   performance, low latency above all. For this purpose IHU is
   compatible with ALSA, now the default Linux sound architecture,
   but also with JACK, a low latency sound server. For the audio
   compression, IHU uses Speex, a codec optimized for speech.

 * Crypted stream: you have also the possibility to Encrypt/Decrypt the
   stream using a fast hybrid cryptographic system (RSA + Blowfish)

 * Command-line support: the Qt GUI is not strictly necessary, you can run
   also a textual IHU from command-line (for example if you need to run
   the program on remote computers).

The possibilities of use of IHU are endless, for example you can use it
like a phone to talk with your friends all around the world, or at home
or work to talk between computers in the LAN (talkback), etc.
.SH "OPTIONS"
.TP
.B \-\-wait
Wait for incoming calls
.TP
.B \-\-call  HOST
Call HOST (DNS or IP address)
.TP
.B \-\-file  FILE
Play a IHU FILE
.TP
.B \-\-encrypt
Encrypt the outgoing stream
.TP
.B \-\-noinput
Disable audio INPUT
.TP
.B \-\-nooutput
Disable audio OUTPUT
.TP
.B \-\-nogui
Start without GUI (no interaction)
.SH "FILES"
.TP
\fI~/.qt/ihurc\fP
This is where IHU reads its config information. You have to edit this
file to change the settings directly when using the --nogui option.
.br 
.SH "SEE ALSO"
.LP
http://ihu.sourceforge.net/
.SH "AUTHORS"
.LP 
Matteo Trotta <mtrotta@users.sourceforge.net>
.PP
This manual page was written by Darwin Bautista <djclue917@gmail.com> for
Arch Linux (but may be used by others).  
