post_install(){
    cat <<EOF
You should update your .emacs in order to use python2-emacs-google with emacs

;;
;; emacs-google
;; 
(setq google-calendar-code-directory "/usr/lib/python2/site-packages/emacs-google/")
EOF
}

post_update(){
    cat <<EOF
You should update your .emacs in order to use python2-emacs-google with emacs

;;
;; emacs-google
;; 
(setq google-calendar-code-directory "/usr/lib/python2/site-packages/emacs-google/")
EOF
}
