post_install() {
  chmod 755 /opt/smartsvn_7/bin/smartsvn.sh
  ln -s /opt/smartsvn_7/bin/smartsvn.sh /usr/bin/smartsvn7

  echo "update desktop mime database..."
  update-desktop-database
  gtk-update-icon-cache -f /usr/share/icons/hicolor/
}

post_upgrade() {
	gtk-update-icon-cache -f /usr/share/icons/hicolor/
}

post_remove() {
  rm -rf /opt/smartsvn_7
  unlink /usr/bin/smartsvn7
  update-desktop-database
  gtk-update-icon-cache -f /usr/share/icons/hicolor/
}

