# arg 1:  the new package version
post_install() {
	echo
	echo " ---------------------------------------------------------------------"
	echo "  Don't forget to install PyXMMS or PyBMP for audio-player-support..."
	echo "  PyXMMS: http://aur.archlinux.org/packages.php?do_Details=1&ID=140"
	echo "  PyBMP:  http://borgforge.net/projects/pybmp/"
	echo " ---------------------------------------------------------------------"
	echo
}

op=$1
shift
$op $*
