post_install() {
    echo "  -> Updating icon cache..."
    gtk-update-icon-cache -q -f -t /usr/share/ccsm/icons/hicolor
    echo " -> Updating XDG menu database..."
    update-desktop-database -q
}

post_upgrade() {
    post_install
}

pre_remove() {
    rm /usr/share/ccsm/icons/hicolor/icon-theme.cache    
}

post_remove() {
    echo " -> Updating XDG menu database..."
    update-desktop-database -q
}
