post_install() {
gtk-update-icon-cache -f -q /usr/share/icons/hicolor
update-desktop-database -q
echo "Make sure you have installed a ttf font, like ttf-dejavu"
}

post_upgrade() {
  post_install $1
}

post_remove() {
update-desktop-database -q
gtk-update-icon-cache -f -q /usr/share/icons/hicolor

# make sure everything is gone, maybe someone has installed
# extensions for all users using unopkg --shared
rm -rf /usr/lib/ooo4kids
}
