#!/bin/sh

. /usr/share/lejos_nxj/lejos_nxj_vars

java -Dnxj.home="${NXJ_HOME}" -DCOMMAND_NAME="${NXJ_COMMAND}" -classpath "${NXJ_CP_TOOL}" js.tinyvm.TinyVM --bootclasspath "${NXJ_CP_BOOT}" --writeorder "LE" --classpath "." "$@"
