#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID="$(cat /var/run/coredpy.pid 2>/dev/null)"
case "$1" in
    start)
        stat_busy "Starting Core Service"
        ([ -z "$PID" ] || [ -z "$(ps -ef | grep "$PID" | grep cored)" ]) && /usr/sbin/cored.py -d
        if [ $? -gt 0 ]; then
            stat_fail
        else
            PID=`cat /var/run/coredpy.pid`
            add_daemon cored
            stat_done
        fi
        ;;
    stop)
        stat_busy "Stopping Core Service"
        [ ! -z "$PID" ] && kill $PID &>/dev/null
        if [ $? -gt 0 ]; then
            stat_fail
        else
            rm_daemon cored
            rm /var/run/coredpy.pid
            stat_done
        fi
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "usage: $0 {start|stop|restart}"  
esac
exit 0
