# Maintainer: Alexander Bauer <sasha@crofter.org>
pkgname=nodeatlas
pkgver=v0.6.0_44_g90422b2
pkgrel=1
pkgdesc="Federated node mapping for mesh networks"
url="https://github.com/ProjectMeshnet/nodeatlas"
arch=('x86_64' 'i686')
license=('GPL3')
depends=('glibc')
makedepends=('go>=1.2')
conflicts=()
replaces=()
backup=()

source=("${url}/archive/90422b26c386269fd9f204e6d0d1926ce5722e09.tar.gz")

# Checksums are generated by updpkgsums prior to build.
sha256sums=('58bbab240ea14c80435eeb34b5cf62c976e451d62add559c584f3cbcfd83a165')

build() {
  cd "${srcdir}/${pkgname}-90422b26c386269fd9f204e6d0d1926ce5722e09"
  DESTDIR="${pkgdir}" prefix="/usr" make
}

package() {
  cd "${srcdir}/${pkgname}-90422b26c386269fd9f204e6d0d1926ce5722e09"
  DESTDIR="${pkgdir}" prefix="/usr" make install
}

# vim:set ts=2 sw=2 et:
