post_install() {
    echo ""
    echo "You need to compile the core library files into javascript."
    echo "As root, run the following command:"
    echo ""
    echo "# cd /usr/share/pyjamas/examples"
    echo "# python2 buildall.py"
    echo ""
}

post_remove() {
    rm -rf /usr/share/pyjamas
}

pre_upgrade() {
    find /usr/share/pyjamas -type f -newer /usr/share/pyjamas/README -delete
}

post_upgrade() {
    post_install $1
}
