--- src/rig-1.11/Makefile	2002-06-04 19:07:50.000000000 -0700
+++ Makefile-modified	2013-03-16 19:02:58.195335666 -0700
@@ -1,16 +1,20 @@
-PREFIX=/usr/local
+PREFIX=${DESTDIR}usr
 BINDIR=${PREFIX}/bin
-MANDIR=${PREFIX}/man
+MANDIR=${PREFIX}/share/man
 DATADIR=${PREFIX}/share/rig
 
 all: rig rig.6
 rig: rig.cc
-	g++ -g rig.cc -o rig -Wall -DDATADIR="\"$(DATADIR)\""
+	g++ -g rig.cc -o rig -Wall -fpermissive -DDATADIR="\"/$(DATADIR)\""
 
 rig.6: rig.6.in
-	sed s@DATADIR@"$(DATADIR)"@g < rig.6.in > rig.6
+	sed s@DATADIR@"/$(DATADIR)"@g < rig.6.in > rig.6
 
 install: rig rig.6
+	mkdir -p ${PREFIX}
+	mkdir -p ${BINDIR}
+	mkdir -p ${MANDIR}/man6/
+	mkdir -p ${DATADIR}
 	install -g 0 -m 755 -o 0 -s rig $(BINDIR)
 	install -g 0 -m 644 -o 0 rig.6 $(MANDIR)/man6/rig.6
 	install -g 0 -m 755 -o 0 -d $(DATADIR)
