post_install() {
  depmod -A
  echo "NOTE: You have to rebuild your initramfs because of the blacklisted"
  echo "      modules. If you using the stock kernel, do this with"
  echo "      $> mkinitcpio -p linux"
  echo ""
  echo "      Add roccat, roccat-common and your specific mouse driver to"
  echo "      /etc/modules-load.d/modules.conf if you want to load it on boot."
}

post_upgrade() {
  depmod -a
}

post_remove() {
  depmod -a
}

