post_install()
{
    install -D -m644 LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
    echo "Running NX post_install script..."
    /usr/NX/nxserver --install fedora
}

pre_remove()
{
    echo "Running NX pre_remove script..."
    /usr/NX/scripts/setup/nxserver --uninstall fedora
}

post_remove()
{
    echo "Removing /usr/NX..."
    rm -rf /usr/NX
}

pre_upgrade() {
    pre_remove
}

post_upgrade() {
    post_install
}
