post_install() {
flag=0
for i in /home/*;do
  directory=$(echo $i)"/.config/cairo-dock/third-party/"
  if test -d $directory 
  then
  if [ $flag = 0 ];then
    echo -e "\e[1;4;91mPlease remove this dir which is now useless and can be in conflict with this package installation:\\r\033[0m"
  fi
    echo -e "\e[1;4;91m$directory\\r\033[0m"
    flag=1
  fi
done
if [ $flag = 1 ];then
  echo "Press any key to continue..."
  read -p ""
fi
}

post_upgrade() {
  post_install
}