# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Alireza Savand <alireza.savand@gmail.com>

_gemname=lotusrb
pkgname=ruby-$_gemname
pkgver=0.1.0
pkgrel=1
pkgdesc='A complete web framework for Ruby'
arch=(any)
url='http://lotusrb.org'
license=(MIT)
depends=(ruby ruby-lotus-utils ruby-lotus-router ruby-lotus-controller ruby-lotus-view)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('d0ff65e8a890e7580948b64e0c91bd440632fc79')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE.md" "$pkgdir/usr/share/licenses/$pkgname/LICENSE.md"
}
