post_install() {
  echo ""
  echo "   * To start the game you need to go to 8-bit color mode."
  echo "   * Add the following line to \"Screen\" section in your xorg.conf:"
  echo "        DefaultDepth  8"
  echo ""
  echo "   * Then run the server by typing:"
  echo "        xfireserv /usr/share/xfirepower/maps.list"
  echo ""
  echo "   * If right mouse button don't work, you may rotate a tank"
  echo "   * with cursor and 'z'."
  echo ""
}

# vim:set ts=2 sw=2 et:
