# arg 1: The new package version
post_install() {

   _VERSION=`echo $1 | cut -f-1 -d '-'`

   # General info
   echo
   echo "When REALbasic starts up, agree to the license and then"
   echo "choose the first option to be able to use it for free."
   echo "It will connect to the internet and retrieve a license."
   echo
   echo "For printing support in REALbasic you must intall cups."
   echo
}

op=$1
shift

$op $*
