# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: kusakata <shohei atmark kusakata period com>

_gemname=typed-array
pkgname=ruby-$_gemname
pkgver=0.1.2
pkgrel=1
pkgdesc='Provides methods for creating type-enforced Arrays'
arch=(any)
url='http://github.com/yaauie/typed-array'
license=(MIT)
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('1ab9c8867f925a6643715b1e1f8433cf3b6106d4')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE.txt" "$pkgdir/usr/share/licenses/$pkgname/LICENSE.txt"
}
