post_install() {
  /usr/bin/udevadm control --reload
  /usr/bin/depmod -A $(ls -v /usr/lib/modules | grep lts | grep -v extra | tail -n 1) > /dev/null 2>&1
}

post_upgrade() {
  /usr/bin/udevadm control --reload
  /usr/bin/depmod -a $(ls -v /usr/lib/modules | grep lts | grep -v extra | tail -n 1) > /dev/null 2>&1
}

post_remove() {
  /usr/bin/depmod -a $(ls -v /usr/lib/modules | grep lts | grep -v extra | tail -n 1) > /dev/null 2>&1
  /usr/bin/udevadm control --reload
}

