post_install() {
  echo "chruby scripts are installed at /usr/share/chruby/"
  echo "you probably need to source them at your ~/.bashrc or ~/.zshrc"
  echo "for more info see /usr/share/doc/chruby/README.md"
}

post_upgrade() {
  post_install
}

post_remove() {
  echo "Don't forget to update your ~/.bashrc or ~/.zshrc"
  echo "if you have references to /usr/share/chruby/{chruby.sh,auto.sh}"
}

# vim:set ts=2 sw=2 et:
