pre_install() {
  getent group mock &>/dev/null || sudo groupadd -r mock
  echo 'You must add yourself to the mock group in order to run mock.'
  ln -s /etc/mock/pam.d/mock /etc/pam.d/mock 
  
  mkdir -p /etc/security/console.apps
  ln -s /etc/mock/security/console.apps/mock /etc/security/console.apps/mock 
}

post_remove() {
  groupdel mock

  unlink /etc/pam.d/mock 
  unlink /etc/security/console.apps/mock 
  echo 'Make sure to empty out /var/lib/mock and /var/cache/mock'
}
