diff -Naur uuid-1.6.2.orig/Makefile.in uuid-1.6.2/Makefile.in
--- uuid-1.6.2.orig/Makefile.in	2010-12-21 08:27:31.550117859 -0700
+++ uuid-1.6.2/Makefile.in	2010-12-21 08:50:36.578086743 -0700
@@ -62,13 +62,13 @@
 PHP         = @PHP@
 PG_CONFIG   = @PG_CONFIG@
 
-LIB_NAME    = libuuid.la
+LIB_NAME    = libossp-uuid.la
 LIB_OBJS    = uuid.lo uuid_md5.lo uuid_sha1.lo uuid_prng.lo uuid_mac.lo uuid_time.lo uuid_ui64.lo uuid_ui128.lo uuid_str.lo
 
-DCE_NAME    = libuuid_dce.la
+DCE_NAME    = libossp-uuid_dce.la
 DCE_OBJS    = uuid_dce.lo $(LIB_OBJS)
 
-CXX_NAME    = libuuid++.la
+CXX_NAME    = libossp-uuid++.la
 CXX_OBJS    = uuid++.lo $(LIB_OBJS)
 
 PRG_NAME    = uuid
@@ -231,7 +231,7 @@
 	$(SHTOOL) mkdir -f -p -m 755 $(DESTDIR)$(mandir)/man1
 	$(SHTOOL) install -c -m 755 uuid-config $(DESTDIR)$(bindir)/
 	$(SHTOOL) install -c -m 644 $(S)/uuid-config.1 $(DESTDIR)$(mandir)/man1/
-	$(SHTOOL) install -c -m 644 $(S)/uuid.pc $(DESTDIR)$(libdir)/pkgconfig/
+	$(SHTOOL) install -c -m 644 $(S)/uuid.pc $(DESTDIR)$(libdir)/pkgconfig/ossp-uuid.pc
 	$(SHTOOL) install -c -m 644 uuid.h $(DESTDIR)$(includedir)/
 	-@if [ ".$(WITH_DCE)" = .yes ]; then \
 	    echo "$(SHTOOL) install -c -m 644 $(S)/uuid_dce.h $(DESTDIR)$(includedir)/"; \
@@ -241,7 +241,7 @@
 	    echo "$(SHTOOL) install -c -m 644 $(S)/uuid++.hh $(DESTDIR)$(includedir)/"; \
 	    $(SHTOOL) install -c -m 644 $(S)/uuid++.hh $(DESTDIR)$(includedir)/; \
 	fi
-	$(SHTOOL) install -c -m 644 $(S)/uuid.3 $(DESTDIR)$(mandir)/man3/
+	$(SHTOOL) install -c -m 644 $(S)/uuid.3 $(DESTDIR)$(mandir)/man3/ossp-uuid.3
 	-@if [ ".$(WITH_CXX)" = .yes ]; then \
 	    echo "$(SHTOOL) install -c -m 644 $(S)/uuid++.3 $(DESTDIR)$(mandir)/man3/"; \
 	    $(SHTOOL) install -c -m 644 $(S)/uuid++.3 $(DESTDIR)$(mandir)/man3/; \
@@ -276,7 +276,7 @@
 	-@if [ ".$(WITH_CXX)" = .yes ]; then \
 	    $(LIBTOOL) --mode=uninstall $(RM) $(DESTDIR)$(libdir)/$(CXX_NAME); \
 	fi
-	-$(RM) $(DESTDIR)$(mandir)/man3/uuid.3
+	-$(RM) $(DESTDIR)$(mandir)/man3/ossp-uuid.3
 	-@if [ ".$(WITH_CXX)" = .yes ]; then \
 	    echo "$(RM) $(DESTDIR)$(mandir)/man3/uuid++.3"; \
 	    $(RM) $(DESTDIR)$(mandir)/man3/uuid++.3; \
@@ -290,7 +290,7 @@
 	    echo "$(RM) $(DESTDIR)$(includedir)/uuid++.hh"; \
 	    $(RM) $(DESTDIR)$(includedir)/uuid++.hh; \
 	fi
-	-$(RM) $(DESTDIR)$(libdir)/pkgconfig/uuid.pc
+	-$(RM) $(DESTDIR)$(libdir)/pkgconfig/ossp-uuid.pc
 	-$(RM) $(DESTDIR)$(mandir)/man1/uuid-config.1
 	-$(RM) $(DESTDIR)$(bindir)/uuid-config
 	-$(RMDIR) $(DESTDIR)$(mandir)/man1 >/dev/null 2>&1 || $(TRUE)
diff -Naur uuid-1.6.2.orig/uuid-config.in uuid-1.6.2/uuid-config.in
--- uuid-1.6.2.orig/uuid-config.in	2010-12-21 08:27:31.546784588 -0700
+++ uuid-1.6.2/uuid-config.in	2010-12-21 08:48:38.170684057 -0700
@@ -121,7 +121,7 @@
             output_extra="$output_extra $uuid_ldflags"
             ;;
         --libs)
-            output="$output -luuid"
+            output="$output -lossp-uuid"
             output_extra="$output_extra $uuid_libs"
             ;;
         * )
diff -Naur uuid-1.6.2.orig/uuid.pc.in uuid-1.6.2/uuid.pc.in
--- uuid-1.6.2.orig/uuid.pc.in	2010-12-21 08:27:31.546784588 -0700
+++ uuid-1.6.2/uuid.pc.in	2010-12-21 08:48:38.174017223 -0700
@@ -37,6 +37,6 @@
 Version: @UUID_VERSION_RAW@
 URL: http://www.ossp.org/pkg/lib/uuid/
 Cflags: -I${includedir}
-Libs: -L${libdir} -luuid
+Libs: -L${libdir} -lossp-uuid
 Libs.private: @LIBS@
