pkgname=dummy
pkgver=1
pkgrel=1
arch=('any')
pkgdesc="Best package in the universe"
url="http://bitbucket.org/wooptoo/bin/src/tip/repo-cache"
license=('GPL')
depends=()
makedepends=()
source=()
md5sums=()
