#!/bin/sh
#update icon-caches
post_install()
{
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/smoothX-Xfce /usr/share/icons/smoothX-Blue-N /usr/share/icons/smoothX-Brown-N /usr/share/icons/smoothX-Brown-New /usr/share/icons/smoothX-Dark-NG /usr/share/icons/smoothX-Yellow-New /usr/share/icons/smoothX-Violet /usr/share/icons/smoothX-Trans /usr/share/icons/smoothX-Red /usr/share/icons/smoothX-Green-NG /usr/share/icons/smoothX-Green-N /usr/share/icons/smoothX-Green-New /usr/share/icons/smoothX-Ubuntu-NG /usr/share/icons/smoothX-Purple-N /usr/share/icons/smoothX-Purple-NG /usr/share/icons/smoothX-Leather /usr/share/icons/smoothX-Olive-N
fi
}




