#!/bin/sh
exec= gtk-update-icon-cache -t -f ~/usr/share/icons/smoothX-Xfce &
exec= gtk-update-icon-cache -t -f ~/usr/share/icons/smoothX-Blue-N &
exec= gtk-update-icon-cache -t -f ~/usr/share/icons/smoothX-Butterfly &
exec= gtk-update-icon-cache -t -f ~/usr/share/icons/smoothX-Red &
exec= gtk-update-icon-cache -t -f ~/usr/share/icons/smoothX-Trans &
exec= gtk-update-icon-cache -t -f ~/usr/share/icons/smoothX-Violet &
exit



