post_install() {
  echo ">>> If Xilinx ISE 14.7 was not already installed when this package was"
  echo ">>> built, you will need to manually create a link to its data2mem command."
  echo ">>> i686:"
  echo ">>> # ln -s /opt/Xilinx/14.7/ISE_DS/ISE/bin/lin/data2mem /opt/papilio-loader/programmer/linux32/data2mem"
  echo ">>> x86_64:"
  echo ">>> # ln -s /opt/Xilinx/14.7/ISE_DS/ISE/bin/lin64/data2mem /opt/papilio-loader/programmer/linux32/data2mem"
}

post_upgrade() {
  post_install
}
