# Contributor: Arch Haskell Team <arch-haskell@haskell.org>
# Package generated by cabal2arch 0.3.4
pkgname=haskell-data-cordering
pkgrel=1
pkgver=0.4
pkgdesc="A useful variant of the Prelude Ordering data type."
url="http://hackage.haskell.org/cgi-bin/hackage-scripts/package/Data-COrdering"
license=('custom:BSD3')
arch=('i686' 'x86_64')
makedepends=('ghc')
source=(http://hackage.haskell.org/packages/archive/Data-COrdering/0.4/Data-COrdering-0.4.tar.gz)
install=haskell-data-cordering.install
md5sums=('960498e338b22492643eafb65b630cd2')
build() {
    cd $startdir/src/Data-COrdering-0.4
    runhaskell Setup configure --prefix=/usr || return 1
    runhaskell Setup build                   || return 1
    runhaskell Setup register   --gen-script || return 1
    runhaskell Setup unregister --gen-script || return 1
    install -D -m744 register.sh   $startdir/pkg/usr/share/haskell/$pkgname/register.sh
    install    -m744 unregister.sh $startdir/pkg/usr/share/haskell/$pkgname/unregister.sh
    runhaskell Setup copy --destdir=$startdir/pkg || return 1
    install -D -m644 LICENSE $startdir/pkg/usr/share/licenses/$pkgname/LICENSE || return 1
}
