#!/usr/bin/env bash
# Copyright (c) 2014, Alexander Neumann <alexander@bumpern.de>

# expand globbing to empty list if no files match
shopt -s nullglob

# debug function
debug() {
    if [[ -n "$DEBUG" ]]; then
        echo "DEBUG: $*"
    fi
}

# try to load global configuration
GLOBAL_CONFIG="/etc/default/uens"
if [[ -r "$GLOBAL_CONFIG" ]]; then
    source "$GLOBAL_CONFIG"
fi

# set default values
USER_CONFIG_DIR="${USER_CONFIG_DIR:-$HOME/.config/uens}"
USER_CONFIG="${USER_CONFIG:-$USER_CONFIG_DIR/config}"
LOGFILE="${LOGFILE:-/var/run/uens/events.log}"
DEBUG=${DEBUG-}

# try to load user configuration
if [[ -r "$USER_CONFIG" ]]; then
    source "$USER_CONFIG"
fi

SCRIPTS="${SCRIPTS:-$HOME/.config/uens/scripts/}"

# read events
tail -n 0 -F "$LOGFILE" 2>/dev/null | while read TIMESTAMP SOURCE EVENT OTHER; do
    debug "read: source $SOURCE, event $EVENT $OTHER"

    # try to run script
    TORUN=($SCRIPTS/run-${SOURCE}-${EVENT}*)

    if [[ "${#TORUN[@]}" = 0 ]]; then
        debug "no scripts to run for event $EVENT from source $SOURCE"
        continue
    fi

    for file in "${TORUN[@]}"; do
        debug "running script $file"
        if [[ -x "$file" ]]; then
            "$file" "$SOURCE" "$EVENT" "$OTHER"
        else
            echo "would run ${file}, but it is not executable!" >&2
        fi
    done
done
