post_install() {
  getent group jboss-as >/dev/null 2>&1 || groupadd jboss-as
  getent passwd jboss-as >/dev/null 2>&1 || useradd -g jboss-as -d /usr/share/jboss-as -s /bin/bash jboss-as
  chown -R jboss-as:jboss-as /usr/share/jboss-as/
}

post_upgrade() {
  post_install $1
}

post_remove() {
  if getent passwd jboss-as >/dev/null 2>&1; then
    userdel jboss-as
  fi
  if getent group jboss-as >/dev/null 2>&1; then
    groupdel jboss-as
  fi
}
