pre_install() {
if [ "$1" = "install" ]; then 
  if [ -f /etc/Yozosoft/Yozo_Office/installinfo.cfg ]; then
    echo "Yozo Office is exist. Please uninstall Yozo Office, then install this office."
    exit 1
  fi
  if [ -f /etc/Evermore/EIOffice/installinfo.cfg ]; then
    echo "EIOffice is exist. Please uninstall EIOffice, then install this office."
    exit 1
  fi
fi
}

post_install() {
set -e

unpackP=/usr/local/Yozosoft/Yozo_Office/Jre/bin/unpack200 
libP=/usr/local/Yozosoft/Yozo_Office/Jre/lib
echo "unpack jar packages, wait a while."
$unpackP -r $libP/rt.pack.gz $libP/rt.jar
$unpackP -r $libP/jsse.pack.gz $libP/jsse.jar
$unpackP -r $libP/charsets.pack.gz $libP/charsets.jar
$unpackP -r $libP/plugin.pack.gz $libP/plugin.jar
$unpackP -r $libP/javaws.pack.gz $libP/javaws.jar
$unpackP -r $libP/deploy.pack.gz $libP/deploy.jar
$unpackP -r $libP/resources.pack.gz $libP/resources.jar

$unpackP -r $libP/ext/localedata.pack.gz $libP/ext/localedata.jar
$unpackP -r $libP/ext/bcprov-jdk14-124.pack.gz $libP/ext/bcprov-jdk14-124.jar
$unpackP -r $libP/ext/jai_core.pack.gz $libP/ext/jai_core.jar
$unpackP -r $libP/ext/tools.pack.gz $libP/ext/tools.jar
$unpackP -r $libP/ext/ojdbc14.pack.gz $libP/ext/ojdbc14.jar
$unpackP -r $libP/ext/mysql-connector-java-5.1.18-bin.pack.gz $libP/ext/mysql-connector-java-5.1.18-bin.jar
$unpackP -r $libP/ext/swt.pack.gz $libP/ext/swt.jar
$unpackP -r $libP/ext/DJNativeSwing-SWT.pack.gz $libP/ext/DJNativeSwing-SWT.jar
$unpackP -r $libP/ext/jhall.pack.gz $libP/ext/jhall.jar
$unpackP -r $libP/ext/bcel-5.1.pack.gz $libP/ext/bcel-5.1.jar

$unpackP -r /usr/local/Yozosoft/Yozo_Office/Yozo_Office.pack.gz /usr/local/Yozosoft/Yozo_Office/Yozo_Office.jar 
if [ -z "$2" -a "$1" = "configure" ]; then
echo "handling file association, waiting a while..."
/usr/local/Yozosoft/Yozo_Office/Jre/bin/java -client -jar /usr/local/Yozosoft/Yozo_Office/Mimelnk/fileAssociate.jar -i
fi
}

post_remove() {
set -e

if [ "$1" = "remove" ]; then
echo "cancelling file association, waiting a while..."

if [ -f /usr/local/Yozosoft/Yozo_Office/System/unpatch.ini ]; then
 while read line
 do
  truncate=${line#*=}
  if [ -f $truncate ]; then
    rm -f $truncate
  fi
 done < /usr/local/Yozosoft/Yozo_Office/System/unpatch.ini
fi

/usr/local/Yozosoft/Yozo_Office/Jre/bin/java -client -jar /usr/local/Yozosoft/Yozo_Office/Mimelnk/fileAssociate.jar -u

rm -f $HOME/Yozo_Office/UserConfig/BarData $HOME/Yozo_Office/UserConfig/system.dll
if [ -f /usr/local/Yozosoft/Yozo_Office/patcheio.log ] ; then
	rm -f /usr/local/Yozosoft/Yozo_Office/patcheio.log
fi
rm -rf /usr/local/Yozosoft/Yozo_Office/System
if [ -d $HOME/Yozo_Office/CustomizedSEImages ]; then
	rm -rf $HOME/Yozo_Office/CustomizedSEImages
fi
if [ -f /usr/local/Yozosoft/Yozo_Office/ScienceEditorImages/logicalData ]; then
	rm -f /usr/local/Yozosoft/Yozo_Office/ScienceEditorImages/logicalData
fi
rm -rf /usr/local/Yozosoft/Yozo_Office/Upgrade/Patch
rm -f /usr/local/Yozosoft/Yozo_Office/Yozo_Office.jar 
libP=/usr/local/Yozosoft/Yozo_Office/Jre/lib
#rm -f $libP/rt.jar $libP/jsse.jar $libP/charsets.jar $libP/plugin.jar $libP/javaws.jar $libP/deploy.jar $libP/resources.jar
#rm -f $libP/ext/localedata.jar $libP/ext/bcprov-jdk14-124.jar $libP/ext/jai_core.jar $libP/ext/tools.jar $libP/ext/ojdbc14.jar $libP/ext/mysql-connector-java-5.1.18-bin.jar $libP/ext/swt.jar $libP/ext/DJNativeSwing-SWT.jar $libP/ext/jhall.jar $libP/ext/bcel-5.1.jar
rm -rf $libP
fi
}
