post_install() {
echo -e "要建立文件關聯，請運行:\n要建立文件关联，请运行:\nto handle file association, please run:"
echo -e "java -client -jar /usr/local/Yozosoft/Yozo_Office/Mimelnk/fileAssociate.jar -i\n"
echo -e "要取消文件關聯，請運行:\n要取消文件关联，请运行:\nto cancell file association, please run:"
echo -e "java -client -jar /usr/local/Yozosoft/Yozo_Office/Mimelnk/fileAssociate.jar -u\n"
}

pre_remove() {
echo "cancelling file association, waiting a while..."
java -client -jar /usr/local/Yozosoft/Yozo_Office/Mimelnk/fileAssociate.jar -u
}
