# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=dep_selector
pkgname=ruby-$_gemname
pkgver=1.0.3
pkgrel=1
pkgdesc='Given packages, versions, and a dependency graph, find a valid assignment of package versions'
arch=(i686 x86_64)
url='http://github.com/opscode/dep-selector'
license=('Apache v2')
depends=(ruby ruby-ffi ruby-dep-selector-libgecode)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('3d8410d44d1f0d24fde2e87833e83d2b8c893934')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
