# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Matanya Moses <matanya@foss.co.il>

_gemname=tinder
pkgname=ruby-$_gemname
pkgver=1.9.4
pkgrel=1
pkgdesc='Ruby wrapper for the Campfire API'
arch=(any)
url='http://github.com/collectiveidea/tinder'
license=()
depends=(ruby ruby-eventmachine ruby-faraday-0.8 ruby-faraday_middleware ruby-hashie ruby-json ruby-mime-types-1 ruby-multi_json ruby-twitter-stream)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('b4edf4f8944613cea32efdbcea425e1685aa956b')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/MIT-LICENSE" "$pkgdir/usr/share/licenses/$pkgname/MIT-LICENSE"
}
