post_install() {
  echo "------------------------------------------------------------------------------------"
  echo "To activate zsh-syntax-highlighting, add the following line at the end of ~/.zshrc:"
  echo "source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
  echo "------------------------------------------------------------------------------------"
}

# vim:set ts=2 sw=2 et:
