#!/bin/sh
#
# foldingathome-gpu-wrapper: Run or setup the Folding@Home GPU client (via Wine).
#

setup_environment() {
  export WINEPREFIX="/var/lib/foldingathome-gpu/$1"
  export LD_LIBRARY_PATH="/opt/foldingathome-gpu:$LD_LIBRARY_PATH"
  
  if [ ! -d "$WINEPREFIX" ]; then
  	mkdir "$WINEPREFIX" || return 1
  fi
  
  cd "$WINEPREFIX" && \
  ln -sf /etc/foldingathome-gpu/client.cfg && \
  ln -sf /opt/foldingathome-gpu/cudart.dll.so cudart32_30_14.dll && \
  ln -sf /opt/foldingathome-gpu/cufft.dll.so cufft32_30_14.dll && \
  . /etc/conf.d/foldingathome-gpu || return 1
}

start_foldingathome_gpu() {
	setup_environment "gpu$1" && \
  /usr/bin/wine /opt/foldingathome-gpu/Folding@home-Win32-gpu.exe $FAH_GPU_FLAGS -gpu "$1"
}

setup_foldingathome_gpu() {
	setup_environment gpu_setup && \
  /usr/bin/wine /opt/foldingathome-gpu/Folding@home-Win32-gpu.exe $FAH_GPU_FLAGS -configonly
	wineserver -k && rm -r "$WINEPREFIX"
}

case "$*" in
	setup)
		setup_foldingathome_gpu
		;;
	*[![:digit:]]*)
		printf '%s\n' $'Usage: foldingathome-gpu-wrapper [ \033[4mgpu_slot\033[0m | setup ]'
		exit 1
		;;
	"")
		start_foldingathome_gpu 0
		;;
	*)
		start_foldingathome_gpu "$1"
		;;
esac
