--- luv-old/Makefile	2013-12-30 14:11:49.914443860 -0500
+++ luv/Makefile	2013-12-30 14:05:38.124434219 -0500
@@ -4,7 +4,7 @@
   LIBS=-lm -lluajit-5.1 -framework CoreServices -framework Cocoa -L/usr/local/lib/
   SHARED_LIB_FLAGS=-bundle -o luv.so temp/luv.o libuv/libuv.a temp/common.o
 else
-  CFLAGS=-Ilibuv/include -g -I/usr/local/include/luajit-2.0 -DLUV_STACK_CHECK -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Werror -fPIC
+  CFLAGS=-Ilibuv/include -g -I/usr/include/lua5.1 -DLUV_STACK_CHECK -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -Werror -fPIC
   LIBS=-lm -lrt
   SHARED_LIB_FLAGS=-shared -o luv.so temp/luv.o libuv/libuv.a temp/common.o
 endif
