#!/usr/bin/env bash

. /etc/diaspora-sa/diaspora-sa.conf
. ~/.config/diaspora-sa/diaspora-sa.conf
cd /opt/diaspora-sa
/opt/diaspora-sa/fs2_open_diaspora "$@" "$FS2OPTS" || /opt/diaspora-sa/fs2_open_diaspora "$@" "$FS2OPTS"
