#!/bin/bash

menu () {
    local CANCEL_OPT

    local OPT
    local OPTIND
    local OPTARG
    while getopts ':c:' OPT; do
        case "$OPT" in
            c) CANCEL_OPT="$OPTARG"
        esac
    done

    shift $(( $OPTIND - 1 ))

    N=1
    while [[ "$#" -gt 0 ]]; do
        printf ' \033[1;36m%2s\033[m  %s\n' "$N" "$1" >&2
        shift

        N=$(( $N + 1 ))
    done

    if [[ -n "$CANCEL_OPT" ]]; then
        printf '\n \033[1;35m 0\033[m  %s\n' "$CANCEL_OPT" >&2
    fi

    printf '\n  \033[m> \033[m' >&2
    read NUM

    printf '%s' "$NUM"
}

pick_device () {
    local -i Choice
    local DevString
    local -a DevStringArr
    local -a DevNames
    while read ROW; do
        local Name="$(cut -d' ' -f 1 <<<"$ROW")"
        local Type="$(cut -d' ' -f 2 <<<"$ROW")"
        local FsType="$(cut -d' ' -f 3 <<<"$ROW")"
        local Label="$(cut -d' ' -f 4 <<<"$ROW")"
        local Uuid="$(cut -d' ' -f 5 <<<"$ROW")"

        if [ "$Type" == 'part' ] && [ "$FsType" != 'swap' ]; then
            DevString="$(printf "\033[1m$Label\033[m  /dev/$Name  $Uuid\033[m")"

            DevStringArr+=("$DevString")
            DevNames+=("$Name")
        fi
    done < <(lsblk -ro NAME,TYPE,FSTYPE,LABEL,UUID | tail -n +2)

    # Select the device
    if [ "${#DevStringArr}" -eq 0 ]; then
        printf "\033[1;31m¡No hay dispositivos en los que buscar!\033[m\n" >&2
        exit 1
    elif [ "${#DevStringArr}" -eq 1 ]; then
        Choice=1
    else
        Choice="$(menu "${DevStringArr[@]}")"
    fi

    Choice=$(( $Choice - 1 ))
    printf '%s' "${DevNames[$Choice]}"
}

mount_device () {
    devmon -g --unmount "/dev/$1" &>/dev/null
    devmon -g --mount "/dev/$1" | tail -n 1 | grep -oE '[^ ]+$'
}

pick_video () {
    tput smcup
    File="$(dialog --stdout --title "Elige Vídeo" --fselect "$1" 14 48)"
    tput rmcup
}

DevName="$(pick_device)"
printf 'Montando dispositivo \033[1m%s\033[m...\n' "/dev/$DevName"
MntPoint="$(mount_device "$DevName")"
printf 'Dispositivo \033[1m%s\033[m montado en \033[1m%s\033[m\n' "/dev/$DevName" "$MntPoint"

VideoFile="$(pick_video "$MntPoint")"
printf 'Playing video \033[1m%s\033[m...\n' "$VideoFile"
omxplayer -b "$VideoFile"

printf 'Desmontando dispositivo \033[1m%s\033[m...\n' "/dev/$DevName"
devmon -g --unmount "/dev/$DevName" &>/dev/null
