# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: kusakata <shohei atmark kusakata period com>

_gemname=active_utils
pkgname=ruby-$_gemname
pkgver=2.0.1
pkgrel=1
pkgdesc='Common utils used by active_merchant, active_fulfillment, and active_shipping'
arch=(any)
url='http://github.com/shopify/active_utils'
license=(MIT)
depends=(ruby ruby-activesupport ruby-i18n)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('13da4be0192e132c59e90cab1adae2b4c9066d84')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/MIT-LICENSE" "$pkgdir/usr/share/licenses/$pkgname/MIT-LICENSE"
}
