post_install() {
#    sed -i '1s/^/"\M-x": "term-do\\C-M"\n/' /etc/inputrc
#    sed -i '1s/^/"\M-z": "term-do -r\\C-M"\n/' /etc/inputrc
  echo '==> Consider adding keybindings:'
  echo '  set echo-control-characters off
  $if Bash
    "\M-x": "term-do\C-M"
    "\M-z": "term-do -r\C-M"
  $endif'
  echo 'if you use urxvt'
  echo '==> Call `term-do -d` in .bashrc for daemon mode'
}

# vim:set ts=2 sw=2 et:
