post_install() {
    echo -e '\E[1;32m'
    echo "  Mad Skills Motocross Demo is now installed."
    echo "  Please review the EULA which you can find under:"
    echo -e '\E[1;31m'
    echo "      /opt/mad-skills-motocross-demo/EULA.txt"
    echo -e '\E[1;32m'
    echo "  To purchase the full game please visit:"
    echo -e '\E[1;31m'
    echo "      http://www.madskillsmotocross.com/"
    echo ""
    echo ""
    tput sgr0 
} 
