pkgname=hlds

post_install() {
  echo "Update your dedicated server using, for example: /opt/hlds/steam -command update -game gamename -dir /opt/hlds -username yoursteamaccountgoeshere -password yourrealpasswordgoeshere"
  echo "   Replace gamename above with cstrike for CS, tfc for TFC, dod for Day of Defeat, "counter-strike source" for CS:S (yes, you need the quotations)"
  echo "Start server, example: hlds_run -game cstrike +maxplayers 20 +map de_dust +ip 1.1.1.1 +port 27015"
}

