# Contributor: Don Stewart <dons@galois.com>
# Package generated by cabal2arch 0.3.1
pkgname=drift
pkgrel=1
pkgver=2.2.3
pkgdesc="Program to derive type class instances"
url="http://hackage.haskell.org/cgi-bin/hackage-scripts/package/DrIFT"
license=('custom:BSD3')
arch=('i686' 'x86_64')
makedepends=('ghc')
source=(http://hackage.haskell.org/packages/archive/DrIFT/2.2.3/DrIFT-2.2.3.tar.gz)
md5sums=('d0b1124cb209a68747bb4b2123e2d93e')
build() {
    cd $startdir/src/DrIFT-2.2.3
    runhaskell Setup configure --prefix=/usr || return 1
    runhaskell Setup build                   || return 1
    runhaskell Setup copy --destdir=$startdir/pkg || return 1
    install -D -m644 LICENSE $startdir/pkg/usr/share/licenses/$pkgname/LICENSE || return 1
}
