#! /bin/bash

kate_theme_dir='/usr/share/config/kateschemarc.d/'
kate_theme_file='/usr/share/config/kateschemarc'

kate_hl_dir='/usr/share/config/katesyntaxhighlightingrc.d/'
kate_hl_file='/usr/share/config/katesyntaxhighlightingrc'

echo ';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;' >  $kate_theme_file
echo '; This file is automatically generated by kate-update-themes, any ;' >> $kate_theme_file
echo '; to this file will be overwritten.  If you want to add a theme,  ;' >> $kate_theme_file
echo '; add it to /usr/share/config/kateschemarc.d/ instead.            ;' >> $kate_theme_file
echo ';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;' >> $kate_theme_file
for f in "$kate_theme_dir"* ; do
	echo ''                     >> "$kate_theme_file"
	echo ";;;;; From $f. ;;;;;" >> "$kate_theme_file"
	cat "$f" >> "$kate_theme_file"
done

echo ';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;' >  $kate_hl_file
echo '; This file is automatically generated by kate-update-themes, any ;' >> $kate_hl_file
echo '; to this file will be overwritten.  If you want to add a         ;' >> $kate_hl_file
echo '; highlighting definition, add it to                              ;' >> $kate_hl_file
echo '; /usr/share/config/katesyntaxhighlightingrc.d/ instead.          ;' >> $kate_hl_file
echo ';;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;' >> $kate_hl_file
for f in "$kate_hl_dir"* ; do
	echo ''                     >> "$kate_hl_file"
	echo ";;;;; From $f. ;;;;;" >> "$kate_hl_file"
	cat "$f" >> "$kate_hl_file"
done
