--- Makefile	2013-02-02 07:09:00.890956604 -0500
+++ Makefile.52	2013-02-02 07:28:03.198922658 -0500
@@ -3,7 +3,7 @@
 PKG_CONFIG=pkg-config
 LUA=lua
 
-LUA_CFLAGS=`$(PKG_CONFIG) --cflags lua5.1 2>/dev/null || $(PKG_CONFIG) --cflags lua`
+LUA_CFLAGS= # Not needed on Arch at least.
 SOCFLAGS=-fPIC
 SOCC=$(CC) -shared $(SOCFLAGS)
 CFLAGS=-fPIC -g -Wall -Werror $(LUA_CFLAGS) -fvisibility=hidden -Wno-unused-function --std=gnu99
