#!/bin/sh
CONF_DIR=~/.yaoqiang
BUG_FILE=$CONF_DIR/.bug_327_fix
if [ -f $BUG_FILE ];
then
    java -jar /opt/yaoqiang-bpmn-editor/yaoqiang.jar
else
    # bug #327 cleanup on first run
    java -jar /opt/yaoqiang-bpmn-editor/yaoqiang.jar -clean
    touch $BUG_FILE
fi
