post_install() {
  chmod 755 /opt/cytoscape-beta/cytoscape.sh
  ln -s /opt/cytoscape-beta/cytoscape.sh /usr/bin/cytoscape-beta

  echo "update desktop mime database..."
  update-desktop-database
  gtk-update-icon-cache -f /usr/share/icons/hicolor
}

post_upgrade() {
  gtk-update-icon-cache -f /usr/share/icons/hicolor
}

post_remove() {
  #rm -rf /opt/cytoscape-beta
  unlink /usr/bin/cytoscape-beta
  update-desktop-database
  gtk-update-icon-cache -f /usr/share/icons/hicolor
}

