post_install() {
	echo	""
	echo	"You MUST configure /etc/conf.d/ffdecsawrapper and /etc/cardclient.conf for FFdecsawrapper to work"
	echo	"A phoenix type smartcard reader and smartcard server software package are also necessary"
	echo	"Oscam works well for this - https://aur.archlinux.org/packages/oscam-svn/"
	echo	""
	echo	"running depmod..."
	depmod
}

post_upgrade() {
	echo	""
	echo	"running depmod..."
	depmod
}

post_remove() {
	echo	""	
	echo	"running depmod..."
	depmod
}
