post_install() {
	EXTRAMODULES='extramodules-3.4-ARCH'
	depmod -a $(cat /usr/lib/modules/$EXTRAMODULES/version)
	echo 'You may now access this module via a modprobe nct6775'
}

post_upgrade() {
	EXTRAMODULES='extramodules-3.4-ARCH'
	depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
	rmmod nct6775 || echo 'You may now access this module via a modprobe nct6775'
}

post_remove() {
	EXTRAMODULES='extramodules-3.4-ARCH'
	depmod -a $(cat /usr/lib/modules/$EXTRAMODULES/version)
}
