#Automatically generated by pip2arch on 2014-12-13
pkgname=upnp-inspector
_name=UPnP-Inspector
pkgver=0.2.2
pkgrel=1
pkgdesc="UPnP Device and Service analyzer"
url="http://coherence.beebits.net/wiki/UPnP-Inspector"
depends=('python2' 'coherence' 'pygtk')
makedepends=('python2')
license=('MIT')
arch=('any')
source=("http://coherence.beebits.net/download/${_name}-${pkgver}.tar.gz")
md5sums=('6823a57f4501c8af6a7b8547b8133759')

build() {
  cd $srcdir/$_name-$pkgver
  python2 setup.py build
}

package() {
  cd $srcdir/$_name-$pkgver
  python2 setup.py install --root="$pkgdir" --optimize=1
}
