#!/bin/bash
#
# How to configure your play framework application in 3 steps:
# * Choose a unique daemon name {appname} of your application. You could use the domain of it but with _ instead of . ( example: blog_greweb_fr )
# 1) Create a symlink of /etc/rc.d/skeleton_playapp in /etc/rc.d/{appname}
# 2) Copy this /etc/conf.d/playapp_sample file in /etc/conf.d/{appname}
# 3) Modify variables below to fit your needs.
#
# * If you want to autorun your application on boot : add {appname} in the /etc/rc.conf DAEMONS variable
# * You can manually stop, start or restart your application with the command: rc.d {stop|start|restart} {appname}
#

PLAY_APP=  # (required) Path of your play application
PLAY_USER= # (optional) The Linux user to use to run the play server. Using root if not setted
PLAY_ARGS= # (optional) The play args to run the play server with. Setting to "--%prod" can be useful to override the play profile id
