#!/bin/bash
# /etc/rc.d/skeleton_playapp : a generic playframework daemon for multiple instance of play applications (with a symlink).
# @see /etc/conf.d/playapp_sample for usage

NAME=`basename $0`
. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/$NAME
. /etc/profile.d/jre.sh

USER=${USER-"root"}
pidfile=$PLAY_APP/server.pid
PID=`cat $pidfile 2> /dev/null`
[[ -e $pidfile ]] && ( [ -n "`ps -p $PID | grep $PID`" ] || rm -f $pidfile) # rm pidfile if not process is running 
PID=`cat $pidfile 2> /dev/null`

case $1 in
start)
  stat_busy "Starting Play framework $PLAY_APP app"
  if [[ -z $PID ]] && su - $PLAY_USER -c "export PATH=$PATH; play start $PLAY_APP $PLAY_ARGS"; then
		add_daemon $NAME
    stat_done
	else
		stat_fail
		exit 1
	fi
	;;

stop)
	stat_busy "Stopping Play framework $PLAY_APP app"
	if [[ ! -z $PID ]]  && play stop $PLAY_APP; then
		rm_daemon $NAME
    stat_done
	else
		stat_fail
		exit 1
	fi
	;;

restart)
	$0 stop
  $0 start
	;;

*)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1

esac
