# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Rhys Davies <rhys@johnguant.com>

_gemname=sqlite-ruby
pkgname=ruby-$_gemname
pkgver=2.2.3
pkgrel=1
pkgdesc='SQLite/Ruby is a module to allow Ruby scripts to interface with a SQLite database.'
arch=(i686 x86_64)
url='http://sqlite-ruby.rubyforge.org'
license=()
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('6f672af52910c4206697fb5cffc83407b97d4b63')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
