post_install() {
	post_upgrade
}

post_upgrade() {
    #su -l -s /bin/sh -c "source /opt/pearl/pearl" $USER
    cat >&2 <<EOF

==> Pearl installation notes:
    ----------------------------------------
    To start using Pearl:
        >> source /opt/pearl/pearl
    ----------------------------------------

==> Pearl documentation:
    ----------------------------------------
    type:
        >> man pearl
    ----------------------------------------
EOF
}
