#!/bin/bash

daemon_name=vmware

. /etc/rc.conf
. /etc/rc.d/functions

if [ -f /etc/rc.d/vmware.d/init.d/vmware ] ; then
  VMWARECTL=/etc/rc.d/vmware.d/init.d/vmware
elif [ -f /etc/rc.d/vmware ] ; then
  VMWARECTL=/etc/rc.d/vmware
else
  echo -n "VMWare daemon startup script not found (/etc/rc.d/vmware or /etc/rc.d/vmware.d/init.d/vmware)"
  stat_fail
  exit 1
fi

case "$1" in
  start)
    ck_daemon hal && /etc/rc.d/hal start
    stat_busy "Starting VMware Host"
    if $VMWARECTL start ; then
      add_daemon $daemon_name
      stat_done
    else
      stat_fail
      exit 1
    fi
    ;;

  stop)
    stat_busy "Stopping VMware Host"
    if $VMWARECTL stop ; then
      rm_daemon $daemon_name
      stat_done
    else
      stat_fail
      exit 1
    fi
    ;;

  status)
    stat_busy "Checking Apache Web Server status";
    ck_status $daemon_name
    ;;

  *)
    echo "usage: $0 {start|stop|reload|restart|status}"
esac

exit 0
