#!/bin/bash

KERNEL=`uname -r | sed 's/-.*//'`

VMWARE_VERSION=`vmware-installer -l | egrep "vmware-workstation|vmware-player" | cut -s -d " " -f 2- | cut -d '.' -f -3`
VMWARE_VERSION=${VMWARE_VERSION// }

echo "Reverting vmware patches applied for version ${VMWARE_VERSION}"

timestamp=`date +%Y%m%d-%H%M%S`
if [ `whoami` != "root" ]
then
  echo "This need to be run as root"
  exit 1
fi

#DEPRECATED SINCE VMWORKSTATION 8
#echo "Reverting vmware modconfig libraries:"
#for mod in `echo \
#/usr/lib/vmware/lib/libvmware-modconfig-console.so/libvmware-modconfig-console.so  \
#/usr/lib/vmware/lib/libvmware-modconfig.so/libvmware-modconfig.so \
#`
#do
#  mv "${mod}".bak "${mod}"
#  res=$?
#  if [ $res -ne 0 ]
#  then
#    echo "* Failed to revert "`basename ${mod}`" (or nothing to revert)"
#  else
#    echo "* "`basename ${mod}`" reverted successfully"
#  fi
#done

echo "Reverting vmware modules source code:"

SRC="/usr/lib/vmware/modules/source/"
for mod in `ls $SRC*.tar-* | sed "s/.*\/\(.*\).tar-.*/\1/" | sort | uniq`
do
  echo "* Reverting ${mod} ..."
  LAST=`ls $SRC$mod.tar-${VMWARE_VERSION}* | sort | head -n 1`
  cp $LAST $SRC$mod.tar
  res=$?
  if [ $res -ne 0 ]
  then
    echo "  [${mod}-only] Failed to revert (or nothing to revert)"
  else
    echo "  [${mod}-only] Reverted successfully"
  fi

done
