#!/bin/bash

KERNEL=`uname -r | sed 's/-.*//'`
VMWARE_VERSION=`vmware-installer -l | egrep "vmware-workstation|vmware-player" | cut -s -d " " -f 2- | cut -d '.' -f -3`
VMWARE_VERSION=${VMWARE_VERSION// }

VMWARE="/usr/lib/vmware/patches/"

echo "Patching vmware ${VMWARE_VERSION} for kernel ${KERNEL}"

timestamp=`date +%Y%m%d-%H%M%S`
if [ `whoami` != "root" ]
then
  echo "This need to be run as root"
  exit 1
fi

cd $VMWARE

#DEPRECATED SINCE VMWORKSTATION 8
#echo "Not patching vmware modconfig libraries (not required since vmware player/workstation 8.0)"

echo "Patching vmware modules source code:"
for mod in `ls *-${VMWARE_VERSION}-*${KERNEL}.diff | sed "s/-.*${VMWARE_VERSION}.*${KERNEL}.diff//"`
do
  echo "* Patching ${mod} ..."
  SRC="/usr/lib/vmware/modules/source/${mod}.tar"
  cp ${SRC} ${SRC}-${VMWARE_VERSION}-${timestamp}
  tar -xf ${SRC}
  cd ${mod}-only
  patch -p1 < ../${mod}-*${VMWARE_VERSION}*-${KERNEL}.diff
  res=$?
  cd ..
  if [ $res -ne 0 ]
  then
    echo "  [${mod}-only] Failed to apply patch"
    rm -rf ${mod}-only
    exit 1
  else
    echo "  [${mod}-only] Patch applied successfully"
  fi

  tar cf ${mod}.tar ${mod}-only
  cp ${mod}.tar ${SRC}
  rm -rf ${mod}.tar ${mod}-only
done
