#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

get_pid() {
  local pid
  if [[ -f /run/coredpy.pid ]]; then
    pid=$(cat /run/coredpy.pid)
    if [[ -n $pid ]]; then
      ps -p $pid &> /dev/null
      if [[ $? -eq 0 ]]; then
        echo $pid
      fi
    fi
  fi
}

case "$1" in
  start)
    stat_busy "Starting CORE daemon"
    PID=$(get_pid)
    if [[ -z $PID ]]; then
      [[ -f /run/coredpy.pid ]] && rm -f /run/coredpy.pid
      # RUN
      /usr/sbin/cored.py -d
      #
      if [[ $? -gt 0 ]]; then
        stat_fail
        exit 1
      else
        add_daemon cored
        stat_done
      fi
    else
      stat_fail
      exit 1
    fi
    ;;

  stop)
    stat_busy "Stopping CORE daemon"
    PID=$(get_pid)
    # KILL
    [[ -n $PID ]] && kill $PID &> /dev/null
    #
    if [[ $? -gt 0 ]]; then
      stat_fail
      exit 1
    else
      rm -f /run/couredpy.pid &> /dev/null
      rm_daemon cored
      stat_done
    fi
    ;;

  restart)
    $0 stop
    sleep 3
    $0 start
    ;;

  status)
    stat_busy "Checking CORE status";
    ck_status cored
    ;;

  *)
    echo "usage: $0 {start|stop|restart|status}"
esac

exit 0

# vim:set ts=2 sw=2 et:
