post_install() {
  echo
  echo
  echo "------------------------------------------------------------"
  echo "-                                                          -"
  echo "-               Please restart CUPS!!!                     -"
  echo "-                                                          -"
  echo "-        You need to add your user to the lp group.        -"
  echo "-                                                          -"
  echo "-                                                          -"
  echo "- Please refer to the table at http://foo2zjs.rkkda.com/   -"
  echo "-                                                          -"
  echo "-   to choose the appropriate driver for your printer.     -"
  echo "-                                                          -"
  echo "-      PLEASE NOTE THAT THIS IS A TESTING PACKAGE:         -"
  echo "-                                                          -"
  echo "- It uses the printer definitions provided by the standard -"
  echo "- foomatic-db package in [Extra] instead of  the  specific -"
  echo "- ones provided  by foo2zjs  package (avoiding the need of -"
  echo "- the   ugly   foomatic-db-foo2zjs   package).  Some   are -"
  echo "- virtually  identical, while others  are quite different. -"
  echo "-                                                          -"
  echo "- If your printer works without problems and is not listed -"
  echo "- below, please report  it in  the  comments,  remove  the -"
  echo "- vote from foo2zjs  and give it  to  foo2zjs-testing.  If -"
  echo "- this package will present no issues, it wil be replacing -"
  echo "- the stable foo2zjs package.                              -"
  echo "-                                                          -"
  echo "-           List of printers known to work:                -"
  echo "-                                                          -"
  echo "-      - Dell C1765nfw Color MFP                           -"
  echo "-      - Epson AcuLaser M1400                              -"
  echo "-      - HP LaserJet 1018                                  -"
  echo "-      - HP LaserJet 1020                                  -"
  echo "-      - HP LaserJet 1022                                  -"
  echo "-      - HP LaserJet P1005                                 -"
  echo "-      - HP LaserJet P1102                                 -"
  echo "-      - HP LaserJet P1102w                                -"
  echo "-      - HP LaserJet P1505                                 -"
  echo "-      - HP LaserJet Professional M1212nf MFP              -"
  echo "-                                                          -"
  echo "------------------------------------------------------------"
  echo
}

post_upgrade() {
  echo
  echo
  echo "------------------------------------------------------------"
  echo "-                                                          -"
  echo "-               Please restart CUPS!!!                     -"
  echo "-                                                          -"
  echo "------------------------------------------------------------"
  echo
}

post_remove() {
  echo
  echo
  echo "------------------------------------------------------------"
  echo "-                                                          -"
  echo "-               Please restart CUPS!!!                     -"
  echo "-                                                          -"
  echo "------------------------------------------------------------"
  echo
}
