# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Matanya Moses <matanya@foss.co.il>

_gemname=passenger
pkgname=ruby-$_gemname
pkgver=4.0.37
pkgrel=1
pkgdesc='A fast and robust web server and application server for Ruby, Python and Node.js'
arch=(i686 x86_64)
url='https://www.phusionpassenger.com/'
license=(MIT)
depends=(ruby ruby-daemon_controller ruby-rack)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('c5d013735f919f9911649c14aee9cacc2fdade5e')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
