# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Rhys <rhys@johnguant.com>

_gemname=dashing
pkgname=ruby-$_gemname
pkgver=1.3.4
pkgrel=1
pkgdesc='The exceptionally handsome dashboard framework.'
arch=(any)
url='http://shopify.github.com/dashing'
license=()
depends=(ruby ruby-sass-3.2 ruby-coffee-script-2.2 ruby-execjs-2.0 ruby-sinatra ruby-sinatra-contrib ruby-thin ruby-rufus-scheduler-2 ruby-thor-0.18 ruby-sprockets-2.10 ruby-rack)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('d0b7c6248119385993f7ef8b9dce3072aa5811aa')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
