# PKGBUILD generated by pacpan
pkgname=perl-memcached-libmemcached
_realname=Memcached-libmemcached
pkgver=0.2101
pkgrel=1
pkgdesc="Thin fast full interface to the libmemcached client API"
arch=(i686 x86_64)
license=('~')
url="http://search.cpan.org/~timb/Memcached-libmemcached"
options=(!emptydirs)

depends=('perl')

#provides=('Memcached-libmemcached')
provides=('memcached-libmemcached=0.2101' 'Memcached::libmemcached::memcached_servers=undef' 'perl-memcached-libmemcached-memcached_servers=undef' 'Memcached::libmemcached::memcached_set=undef' 'perl-memcached-libmemcached-memcached_set=undef' 'Memcached::libmemcached::memcached_flush=undef' 'perl-memcached-libmemcached-memcached_flush=undef' 'Memcached::libmemcached::memcached_version=undef' 'perl-memcached-libmemcached-memcached_version=undef' 'Memcached::libmemcached::memcached_get=undef' 'perl-memcached-libmemcached-memcached_get=undef' 'Memcached::libmemcached=0.2101' 'perl-memcached-libmemcached=0.2101' 'Memcached::libmemcached::memcached_callback=undef' 'perl-memcached-libmemcached-memcached_callback=undef' 'Memcached::libmemcached::memcached_server_st=undef' 'perl-memcached-libmemcached-memcached_server_st=undef' 'Memcached::libmemcached::memcached_stats=undef' 'perl-memcached-libmemcached-memcached_stats=undef' 'Memcached::libmemcached::memcached_auto=undef' 'perl-memcached-libmemcached-memcached_auto=undef' 'Memcached::libmemcached::API=undef' 'perl-memcached-libmemcached-api=undef' 'Memcached::libmemcached::memcached_verbosity=undef' 'perl-memcached-libmemcached-memcached_verbosity=undef' 'Memcached::libmemcached::memcached_create=undef' 'perl-memcached-libmemcached-memcached_create=undef' 'Memcached::libmemcached::memcached_quit=undef' 'perl-memcached-libmemcached-memcached_quit=undef' 'Memcached::libmemcached::memcached_behavior=undef' 'perl-memcached-libmemcached-memcached_behavior=undef' 'Memcached::libmemcached::memcached_delete=undef' 'perl-memcached-libmemcached-memcached_delete=undef' 'Memcached::libmemcached::memcached_strerror=undef' 'perl-memcached-libmemcached-memcached_strerror=undef')

source=(http://search.cpan.org/CPAN/authors/id/T/TI/TIMB/Memcached-libmemcached-0.2101.tar.gz)
md5sums=('9d588d1119d2bfd0f33768bccc263198')

build() {
  _expected_dir="${srcdir}/${_realname}-${pkgver}"
  if [ -d "$_expected_dir" ]; then
    cd "$_expected_dir"
  else
    _expected_dir="${srcdir}/$(bsdtar -t -f $(basename $source) | head -n1)"
    if [ -d "$_expected_dir" ]; then
      cd "$_expected_dir"
    else
      _makefile=$(find $srcdir -iname Makefile.PL)
      if [ ! -z "$_makefile" ]; then
        _expected_dir=$(dirname $_makefile)
        if [ -d "$_expected_dir" ]; then
          cd "$_expected_dir"
        else
          echo "[1;31mERROR[0m unable to detect source directory"
          echo "[1;34m-->[0m this is often due to CPAN's lack of standard naming conventions"
          echo "[1;34m-->[0m it may be possible to fix this by adjusting the build function in the PKGBUILD"
        fi
      fi
    fi
  fi
  # install module in vendor directories.
  PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor || return 1
  make  || return 1
  make install DESTDIR=${pkgdir} || return 1

  # remove perllocal.pod and .packlist
  find ${pkgdir} -name perllocal.pod -delete
  find ${pkgdir} -name .packlist -delete
}

