
post_install() {

echo
echo "********************************************************************"
echo "*                                                                  *"
echo "*  Copy /usr/share/doc/torrtux/.torrtuxrc to your home directory   *"
echo "*  and configure your torrent client.                              *"
echo "*                                                                  *"
echo "********************************************************************"
echo
}