
post_install() {

echo
echo "********************************************************************"
echo "*                                                                  *"
echo "*  Don't forget to configure your torrent client in ~/.torrtuxrc   *"
echo "*                                                                  *"
echo "********************************************************************"
echo
}
