# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: uberushaximus <uberushaximus AT gmail DOT com>

_gemname=geokit
pkgname=ruby-$_gemname
pkgver=1.8.4
pkgrel=1
pkgdesc='Geokit: encoding and distance calculation gem'
arch=(any)
url='http://github.com/geokit/geokit'
license=(MIT)
depends=(ruby ruby-multi_json)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('07efddc5a132f9a3a5f82fd7175a1a16488425ae')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/MIT-LICENSE" "$pkgdir/usr/share/licenses/$pkgname/MIT-LICENSE"
}
