post_install() {
	echo ""
	echo "Vcmi is a game engine and it doesn't contain data files. Therefore you"
	echo "have to have a original copy of Heroes of Might and Magic 3. You can"
	echo "prepare the data files using a vcmibuilder script or you can make this"
	echo "manually. Please follow the instructions from this website:"
	echo "http://wiki.vcmi.eu/index.php?title=Installation_on_Linux#Preparing_data"
	echo ""
}
