post_install() {
  grep xml.cisco.com /etc/hosts > /dev/null
  if [ $? -ne 0 ]
  then
    echo '127.0.0.127 xml.cisco.com' >> /etc/hosts
  fi

  if [ ! -f /usr/share/webapps/iou-web/data/database.sdb ]
  then
    cp -a /usr/share/webapps/iou-web/data/template.sdb /usr/share/webapps/iou-web/data/database.sdb
  fi
}

post_upgrade() {
  grep xml.cisco.com /etc/hosts > /dev/null
  if [ $? -ne 0 ]
  then
    echo '127.0.0.127 xml.cisco.com' >> /etc/hosts
  fi

  if [ ! -f /usr/share/webapps/iou-web/data/database.sdb ]
  then
    cp -a /usr/share/webapps/iou-web/data/template.sdb /usr/share/webapps/iou-web/data/database.sdb
  fi

  php -q /usr/share/webapps/iou-web/update.php 
}

post_remove() {
  grep xml.cisco.com /etc/hosts > /dev/null
  if [ $? -ne 1 ]
  then
    sed -i '/xml.cisco.com/d' /etc/hosts
  fi
}