# generated by the gambas3 ide
# Maintainer : 910JQK <v910JQK@gmail.com>

pkgname=opencc-gbgui
_realname=opencc-gbgui
pkgdesc="A GUI frontend of OpenCC that writen by gambas."
pkgver=0.0.3
pkgrel=2
arch=('any')
url="http://poker-lee.tk"
changelog=ChangeLog
license=('custom')
depends=('gambas3-gb-image>=3.0.90' 'gambas3-gb-image<=3.99.0' 'gambas3-gb-gtk>=3.0.90' 'gambas3-gb-gtk<=3.99.0' 'gambas3-gb-form>=3.0.90' 'gambas3-gb-form<=3.99.0' 'opencc')
makedepends=('gambas3-devel')
source=(${_realname}-$pkgver.tar.bz2 license.txt\
        'opencc-gbgui.desktop' 'opencc-gbgui.png')
md5sums=('e35966b9fe0b7b879fbe55ff9d5fe85f'
         '35403466a659acad9657584fb79a6020'
         '123fc3d27ed8d0b5109bc339fc4244a7'
         '31419dbcd0e9612344185ff007cefd01')

build() {
  cd ${srcdir}/${_realname}

  /usr/bin/gbc3 -e -a -g -x  && gba3
}

package() {
  cd ${srcdir}/${_realname}

  install -d ${pkgdir}/usr/bin
  install -m755 opencc-gbgui.gambas ${pkgdir}/usr/bin/opencc-gbgui
  install -D ../opencc-gbgui.png \
    ${pkgdir}/usr/share/pixmaps/opencc-gbgui.png
  install -D ../opencc-gbgui.desktop \
    ${pkgdir}/usr/share/applications/opencc-gbgui.desktop
  install -Dm644 ${srcdir}/license.txt ${pkgdir}/usr/share/licenses/opencc-gbgui/license.txt
}
