post_install() {
	post_upgrade
	
	cat <<EOF
>>> Configure apache using /etc/webapps/i-librarian/apache.example.conf
>>> Edit /etc/php/php.ini and uncomment extension=pdo_sqlite.so
>>> Restart apache then open http://localhost/librarian
EOF
}

post_upgrade() {
    getent group http >& /dev/null && \
    getent passwd http >& /dev/null && \
    chown -R http:http /usr/share/webapps/i-librarian/library
}
