#! /bin/sh

. /etc/rc.conf
. /etc/rc.d/functions

JONAS_BIN_PATH=/opt/jonas/bin/jonas
DAEMON_NAME=jonas

case "$1" in
  # start
  start)
    stat_busy "Starting JOnAS"
    ${JONAS_BIN_PATH} start > /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon ${DAEMON_NAME}
      stat_done
    fi
    ;;
  # stop
  stop)
    stat_busy "Stopping JOnAS"
    ${JONAS_BIN_PATH} stop > /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon ${DAEMON_NAME}
      stat_done
    fi
    ;;
  # restart
  restart)
    $0 stop
    sleep 3
    $0 start
    ;;
  # Other supported args with no particular action here
  admin | version | check)
    ${JONAS_BIN_PATH} "$1"
  ;;
  # Default (Force usage display)
  *)
    ${JONAS_BIN_PATH}
esac
exit 0
