post_install() {
    cat <<- EOF
        :: You need the Quake 1 data to play
        :: Copy your 'id1' directory to '/usr/share/quake/'
        ::
        :: In order for the desktop file to work you need 
        :: to create a link to the desired binary, i.e.
        ::   ln -s /usr/bin/darkplaces-glx /usr/bin/darkplaces
        :: or
        ::   ln -s /usr/bin/darkplaces-sdl /usr/bin/darkplaces
    EOF
}
