post_install() {
  cp /srv/craftbukkit/spigot.jar /srv/craftbukkit/spigot.jar.1649
  echo ">>> spigot.jar has been backed up as /srv/craftbukkit/spigot.jar.1649"
  echo ">>> It is recommended to back this up personally as well"
}

post_remove() {
	rm /srv/craftbukkit/spigot.jar
	mv /srv/craftbukkit/spigot.jar.1649 /srv/craftbukkit/spigot.jar
  echo ">>> Patched spigot.jar has been removed and build 1649 has been restored."
}
