# Generated by gem2arch
# Maintainer: LeeF
# Contributor: Jim Weirch <jim dot weirich at gmail dot com>

_gemname=rake
pkgname=ruby-enterprise-rake-083
pkgver=0.8.3
pkgrel=2
pkgdesc="Ruby based make-like utility."
arch=('i686' 'x86_64')
url="http://rake.rubyforge.org"
license=('MIT')
depends=('ruby-enterprise')
makedepends=('ruby-enterprise')
provides=('ruby-enterprise-rake')
source=(http://gems.rubyforge.org/gems/$_gemname-$pkgver.gem ruby-enterprise-rake.install)
install=ruby-enterprise-rake.install
noextract=($_gemname-$pkgver.gem)
md5sums=('2765845a465d89c46d01b4b5bba94ca7'
		'd9e0f15cfe65a87108d4a0f80f67d029')

build() {
  cd $srcdir
  local _gemdir=`ruby -rubygems -e'puts Gem.default_dir'`
  gem install --ignore-dependencies --no-rdoc --no-ri -i "$pkgdir$_gemdir" $_gemname-$pkgver.gem
}
