post_install() {
  post_upgrade
}

pre_install() {
  groupadd -r _skype
  useradd -g _skype -G audio,video -c "Skype-only user account" -d /var/skype -m -r -s /bin/nologin _skype
}

post_upgrade() {
  if [[ -x usr/bin/xdg-icon-resource ]]; then
    usr/bin/xdg-icon-resource forceupdate &>/dev/null || true
  fi
  update-desktop-database -q
}

post_remove() {
  groupdel _skype
  userdel _skype
  post_upgrade
}
