# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: uberushaximus <uberushaximus AT gmail DOT com>

_gemname=active_attr
pkgname=ruby-$_gemname
pkgver=0.8.2
pkgrel=1
pkgdesc='What ActiveModel left out'
arch=(any)
url='https://github.com/cgriego/active_attr'
license=('MIT')
depends=(ruby ruby-activemodel ruby-activesupport)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('a199a53a9fc74f3b8898fba7620781214aa1492b')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
