# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Matanya Moses <matanya@foss.co.il>

_gemname=jsduck
pkgname=ruby-$_gemname
pkgver=5.3.4
pkgrel=1
pkgdesc='Simple JavaScript Duckumentation generator'
arch=(any)
url='https://github.com/senchalabs/jsduck'
license=(GPL-3)
depends=(ruby ruby-rdiscount ruby-json ruby-parallel-0.7 ruby-rkelly-remix ruby-dimensions-1.2)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('75e0bb99b2c3e814489adcbd7526a8b95550ba79')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/COPYING" "$pkgdir/usr/share/licenses/$pkgname/COPYING"
}
