*** Makefile	2009-05-14 17:22:37.000000000 +0200
--- Makefile.orig	2011-03-19 11:07:01.546668898 +0100
***************
*** 63,71 ****
  			rtmp_init.o  sanity.o rtmp_wep.o rtmp_info.o \
  			rtmp_tkip.o wpa.o md5.o rt2x00debug.o
  
! ifdef TOPDIR
  obj-m += $(MODULE_NAME).o
! endif
  
  EXTRA_CFLAGS += -I$(src)
  ifneq ($(FCREV),)
--- 63,72 ----
  			rtmp_init.o  sanity.o rtmp_wep.o rtmp_info.o \
  			rtmp_tkip.o wpa.o md5.o rt2x00debug.o
  
! # tp  3-nov-2009 - removed ifdef for 2.6.31-14-generic under dkms
! # ifdef TOPDIR
  obj-m += $(MODULE_NAME).o
! # endif
  
  EXTRA_CFLAGS += -I$(src)
  ifneq ($(FCREV),)
