# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Fontastic

_gemname=remote_syslog
pkgname=ruby-$_gemname
pkgver=1.6.14
pkgrel=1
pkgdesc='Monitor plain text log file(s) for new entries and send to remote syslog collector'
arch=(any)
url='http://github.com/papertrail/remote_syslog'
license=(GPL)
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('2e4ae62a3d60f2bccfa7f3acd9be17db4a94102c')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
