post_install() {
  echo "update desktop database..."
  update-desktop-database -q
  echo "#############################################"
  echo "#   Warning : Files created with GeoGebra   #" 
  echo "#   beta may not work in future versions    #"
  echo "#############################################" 
}

post_upgrade() {
  post_install $1
}

post_remove() {
  echo "update desktop database..."
  update-desktop-database -q
}

