#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

NAME="Serviio Media Server"
PID=$(pgrep -f serviio.MediaServer -n)

case "$1" in
start)
stat_busy "Starting $NAME"
[ -z "$PID" ] && /usr/bin/serviio &
if [ $? -gt 0 -o -n "$PID" ]; then
stat_fail
else
add_daemon serviio
stat_done
fi
;;
stop)
stat_busy "Stopping $NAME"
[ ! -z "$PID" ] && /usr/bin/serviio -stop &> /dev/null
if [ $? -gt 0 ]; then
stat_fail
else
rm_daemon serviio
stat_done
fi
;;
restart)
$0 stop
sleep 5
$0 start
;;
*)
echo "usage: $0 {start|stop|restart}"
;;
esac
exit 0 
