post_install() {
  cat << EOF
==> To set up Emacs to automatically number lines add the following
    to your ~/.emacs file (GNU Emacs) or ~/.xemacs/init.el file
    (XEmacs un-tested):
       (require 'linum)
       ;; Number lines in all modes
       (global-linum-mode 1)
       ;; Apply numbering to specific modes (example for lisp-mode) [cannot use with global-linum-mode]
       ;;(add-hook 'lisp-mode-hook (lambda () (linum-mode 1)))
EOF
}

post_upgrade() {
  post_install $1
}
