#!/bin/bash

# Speech announcement
P=/usr/share/sounds/FB4Linux-intro.ogg
if (which mplayer >/dev/null) then mplayer $P &
elif (which cvlc >/dev/null) then cvlc --play-and-exit $P &
elif (which ffplay >/dev/null) then ffplay -nodisp -autoexit $P &
fi

# Start program
/usr/bin/FB4Linux