#!/bin/sh

#######################
# BEGIN PRETTY OUTPUT #
#######################
source `which nvprettyprint`
ppbegin
#####################
# END PRETTY OUTPUT #
#####################

###################
# BEGIN PRECHECKS #
###################
#Check if credentials are still cached in sudo
function checksudo() {
	if ! sudo -n -p "" 2>/dev/null -- echo -n ""; then
		ppinfo "Please enter your password for sudo: "
		if sudo -p "" -- echo -n ""; then
			ppinfo "Success: "
			ppwarning "password accepted\n"
			return 0
		else
			pperror "Failed: "
			ppwarning "Password not accepted\n"
			ppwarning "sudo failed to run. Is sudo set up correctly?\n"
			exit 1
		fi
	fi
}
#################
# END PRECHECKS #
#################

#########################
# BEGIN TURNING ON CARD #
#########################
checksudo
sudo nvenablecard
#######################
# END TURNING ON CARD #
#######################

#########################
# BEGIN RUNNING PROGRAM #
#########################
case "${ARCH}" in
	i686)
		if which optirun 2>/dev/null >/dev/null; then
			pptitle "Running ${@} with optirun"
			optirun ${@}
		else
			pperror "Failed: "
			ppwarning "optirun not found\n"
		fi
		;;
	x86_64)
		#Check if the program is supposed to be run with optirun(64) or optirun32
		case "${OPTIRUNARCH}" in
			x86)
				#Only continue of the processor architecture is 64 bit
				if which optirun32 2>/dev/null >/dev/null; then
					pptitle "Running ${@} with optirun32"
					optirun32 ${@}
				else
					pperror "Failed: "
					ppwarning "optirun32 not found\n"
				fi
				#(which optirun32 2>/dev/null && pptitle "Running ${@} with optirun32" && (optirun32 ${@} || true)) || (pperror "Failed: " && ppwarning "optirun32 not found\n")
				;;
			x64)
				if which optirun64 2>/dev/null >/dev/null; then
					pptitle "Running ${@} with optirun64"
					optirun64 ${@}
				elif which optirun 2>/dev/null >/dev/null; then
					pptitle "Running ${@} with optirun"
					optirun ${@}
				else
					pperror "Failed: "
					ppwarning "neither optirun64 nor optirun were found\n"
				fi
				#Ugly line that checks if optirun or optirun64 exists and gives a error message if neither is found. It also ignores the error code of the program being run.
				#((which optirun64 2>/dev/null && pptitle "Running ${@} with optirun64" && (optirun64 ${@} || true)) || (which optirun 2>/dev/null && pptitle "Running ${@} with optirun" && (optirun ${@} || true))) || (pperror "Failed: " && ppwarning "Neither optirun64 nor optirun were found\n")
				;;
		esac
		;;
esac
#######################
# END RUNNING PROGRAM #
#######################

##########################
# BEGIN TURNING OFF CARD #
##########################
checksudo
sudo nvdisablecard
########################
# END TURNING OFF CARD #
########################

###################
# BEGIN ENDCHECKS #
###################
ppend
#################
# END ENDCHECKS #
#################
