#!/bin/bash

#####################
# BEGIN HELP OUTPUT #
#####################
source `which nvprettyprint`
ppbegin
pptitletext "Special thanks to Erik Andresen for finding the right ACPI calls from the DSDT table\n\n"
ppseparate "This package contains the following user scripts:\n\n"
ppinfo "  nvrun          "
ppwarning "- Wrapper for optirun that disables and enables the nVidia\n"
ppwarning "                     card before and after running the program.\n"
ppinfo "  nvrun64        "
ppwarning "- Same as "
ppinfo "nvrun"
ppwarning " on a 64 bit system; does not exist on\n"
ppwarning "                     a 32 bit system\n"
ppinfo "  nvrun32        "
ppwarning "- Runs a 32 bit program on a 64 bit system; does not\n"
ppwarning "                     exist on a 32 bit system\n"
ppinfo "  nvenablecard   "
ppwarning "- Script to manually turn on the nVidia graphics card\n"
ppinfo "  nvdisablecard  "
ppwarning "- Script to manually turn off the nVidia graphics card\n"
ppinfo "  nvhelp         "
ppwarning "- This help screen you are looking at right now"
pperror " :P\n"
ppseparate "\nBehind the scenes scripts:\n\n"
ppinfo "  nvcommand      "
ppwarning "- This command does all the magic. It runs "
ppinfo "nvenablecard"
ppwarning ",\n"
ppwarning "                     optirun(32,64) and then runs "
ppinfo "nvdisablecard"
ppwarning ".\n"
ppinfo "  nvpwrctl       "
ppwarning "- This script actually turns the nVidia graphics card\n"
ppwarning "                     on and off through Erik Andresen's ACPI calls.\n"
ppinfo "  nvprettyprint  "
ppwarning "- This script contains all the bash functions for the\n"
ppwarning "                     colored output.\n"
ppend
###################
# END HELP OUTPUT #
###################

