# PKGBUILD generated by pacpan
pkgname=perl-file-pushd
_realname=File-pushd
pkgver=1.00
pkgrel=1
pkgdesc="change directory temporarily for a limited scope"
arch=(i686 x86_64)
license=('apache')
url="http://search.cpan.org/~dagolden/File-pushd"
options=(!emptydirs)

depends=('perl>=5.10.1')

#provides=('File-pushd')
provides=('file-pushd=1.00' 'File::pushd=1.00' 'perl-file-pushd=1.00')

source=(http://search.cpan.org/CPAN/authors/id/D/DA/DAGOLDEN/File-pushd-1.00.tar.gz)
md5sums=('c0d63d05db01a6da3aebd7cd6f93e520')

build() {
  _expected_dir="${srcdir}/${_realname}-${pkgver}"
  if [ -d "$_expected_dir" ]; then
    cd "$_expected_dir"
  else
    _expected_dir="${srcdir}/$(bsdtar -t -f $(basename $source) | head -n1)"
    if [ -d "$_expected_dir" ]; then
      cd "$_expected_dir"
    else
      _makefile=$(find $srcdir -iname Makefile.PL)
      if [ ! -z "$_makefile" ]; then
        _expected_dir=$(dirname $_makefile)
        if [ -d "$_expected_dir" ]; then
          cd "$_expected_dir"
        else
          echo "[1;31mERROR[0m unable to detect source directory"
          echo "[1;34m-->[0m this is often due to CPAN's lack of standard naming conventions"
          echo "[1;34m-->[0m it may be possible to fix this by adjusting the build function in the PKGBUILD"
        fi
      fi
    fi
  fi
  # install module in vendor directories.
  PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor || return 1
  make  || return 1
  make install DESTDIR=${pkgdir} || return 1

  # remove perllocal.pod and .packlist
  find ${pkgdir} -name perllocal.pod -delete
  find ${pkgdir} -name .packlist -delete
}

# vim:set ts=2 sw=2 et:

