# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Rhys Davies <rhys@johnguant.com>

_gemname=deprecated
pkgname=ruby-$_gemname-2
pkgver=2.0.1
pkgrel=1
pkgdesc='An easy way to handle deprecating and conditionally running deprecated code'
arch=(any)
url='http://rubyforge.org/projects/deprecated/'
license=()
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('366fe846dbe85b7abc45e70e3439afdfd2bbe6dd')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
