#!/bin/bash
(
  OXCDIR=/opt/openxencenter-svn
  CONFIGDIR=$HOME/.openxencenter
  CONFIG=oxc.conf

  if [ ! -e "$CONFIGDIR/$CONFIG" ];then
    mkdir $CONFIGDIR
    cp {$OXCDIR,$CONFIGDIR}/$CONFIG
  fi

  cd $OXCDIR
  python window.py|grep -v "gtk-vnc-DEBUG"|grep -v ^$
)
