#!bash

post_install() {
  # Yes, this should be /var/lib/charybdis, but the damn thing
  # insists on using ${localstatedir}/log/charybdis for logs
  # *but* ${localstatedir}/charybdis for state.

  getent passwd charybdis >&/dev/null ||
    useradd -d '/var/charybdis' -r charybdis

  chown charybdis:charybdis {/etc,/var,/var/log}/charybdis

  systemd-tmpfiles --create charybdis.conf
}

post_remove() {
  grep -qs '^charybdis:' /etc/passwd &&
    userdel charybdis
}

# vim: ts=2:sw=2:et
