# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Simon Kohlmeyer <simon.kohlmeyer@gmail.com>

_gemname=watchr
pkgname=ruby-$_gemname
pkgver=0.7
pkgrel=1
pkgdesc='Modern continious testing (flexible alternative to autotest)'
arch=(any)
url='http://mynyml.com/ruby/flexible-continuous-testing'
license=()
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('73c5dc3809a9cd0a0ce9761f647c9de4dc88b939')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
