
post_install() {
  mkdir -p /var/lib/downpour/tmp
  mkdir -p /var/lib/downpour/downloads

  /bin/cat <<EOF

***********************************************
*  Start daemon as root with 'downpourd'      *
*  Stop daemon as root with 'downpourd stop'  *
*  Start webinterface : localhost:6280        *
*  Log in Username : admin                    *
*  Password : password                        *
***********************************************

EOF
}
