post_install() {
  echo
  echo "                     ### WARNING ###"
  echo "Unless you have xulrunner<2.0 (firefox<4.0) installed,"
  echo "you can't run 'diogenes' standalone application."
  echo "In this case, type 'diogenes-server' in a terminal"
  echo "or launch it from the application menu;"
  echo "then point your browser at http://127.0.0.1:8888/"
}
post_upgrade() {
  post_install
}
op=$1
shift
$op $*
