# arg 1:  the new package version
# This is to remove the old line in ld.so.conf
# Library path will be provided in /etc/ld.so.conf.d/brlcad.conf
# from now on.
post_install() {
	pre_remove
	echo "Add /opt/brlcad/lib to ld.so.conf.d if necessary"
}

post_upgrade() {
	pre_remove
}

pre_remove() {
    cat etc/ld.so.conf | grep -v '/opt/brlcad/lib' >/tmp/.pacbrlcad
    mv /tmp/.pacbrlcad etc/ld.so.conf
    chmod 644 etc/ld.so.conf
    sbin/ldconfig -r .
}
