# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>
# Contributor: Alfredo Palhares <masterkorp@masterkorp.net>

_gemname=capistrano
pkgname=ruby-$_gemname-2
pkgver=2.15.5
pkgrel=3
pkgdesc='Capistrano - Welcome to easy deployment with Ruby over SSH'
arch=(any)
url='http://github.com/capistrano/capistrano'
license=(MIT)
depends=(ruby ruby-highline ruby-net-ssh ruby-net-sftp ruby-net-scp ruby-net-ssh-gateway)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('186ade52dd274b0ee0728f8a31797eba35a9242a')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  # non-HEAD version should not install any files in /usr/bin
  rm -r "$pkgdir/usr/bin/"
}
