# Generated by gem2arch-ruby-enterprise

_gemname=activeresource
pkgname=ruby-enterprise-$_gemname
pkgver=2.3.11
pkgrel=0
pkgdesc="Think Active Record for web resources."
arch=('i686' 'x86_64')
url="http://www.rubyonrails.org"
license=('')
depends=('ruby-enterprise' 'ruby-enterprise-activesupport=2.3.11')
makedepends=('ruby-enterprise')
source=(http://gems.rubyforge.org/gems/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
md5sums=('1db8bd1a5daa398c84052fe3662d3edb')

build() {
  cd $srcdir
  local _gemdir=`/opt/ruby-enterprise/bin/ruby -rubygems -e'puts Gem.default_dir'`
  /opt/ruby-enterprise/bin/gem install --ignore-dependencies --no-rdoc --no-ri  -i "$pkgdir$_gemdir" $_gemname-$pkgver.gem
}
