post_install() {

    echo ""
    echo "This is a package containing the Automated Builds provided by mingw-w64 project."
    echo "This compiler toolchain supports building only win32 executables and dlls, not win64."    
    echo ""
	echo "If you want to test c++ binaries with win64,"
	echo "you should copy or link /opt/mingw_w32/i686-w64-mingw32/lib/*.dll"
	echo "into your .wine/drive_c/windows/system32"
	echo ""
    
}

post_upgrade() {
    post_install
}
