all: libgrchartX.a tstchart

tstchart: tstchart.o libgrchartX.so
	gcc -m64 -o xtstchart tstchart.o -lmgrxX -L `pwd` -lX11 -lgrchartX

tstchart.o: tstchart.c grchart.h
	gcc -m64 -c tstchart.c -D__X11__

libgrchartX.a: grchart.o
	ar -r $@ $< 

libgrchartX.so: grchart.o
	gcc -shared -m64 -o $@ $< -lmgrxX 

grchart.o: grchart.c grchart.h
	gcc -m64 -c grchart.c -D__X11__ -fPIC
