# This is a default template for a post-install scriptlet.
# Uncomment only required functions and remove any functions
# you don't need (and this header).

## arg 1:  the new package version
pre_install() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor

#}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $1
}

## arg 1:  the new package version
post_install() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
#}

