diff -paur qxw-20130906/Makefile qxw-20130906.new/Makefile
--- qxw-20130906/Makefile	2013-11-08 17:57:25.000000000 +0100
+++ qxw-20130906.new/Makefile	2014-01-24 18:41:42.516304854 +0100
@@ -56,11 +56,8 @@ clean:
 
 .PHONY: install
 install:
-	mkdir -p $(DESTDIR)/usr/games
-	cp -a qxw $(DESTDIR)/usr/games/qxw
-	mkdir -p $(DESTDIR)/usr/include/qxw
-	cp -a qxwplugin.h $(DESTDIR)/usr/include/qxw/qxwplugin.h
-	mkdir -p $(DESTDIR)/usr/share/applications
-	cp -a qxw.desktop $(DESTDIR)/usr/share/applications/qxw.desktop
+	install -Dm755 qxw $(DESTDIR)/usr/bin/qxw
+	install -Dm644 qxwplugin.h $(DESTDIR)/usr/include/qxw/qxwplugin.h
+	install -Dm644 qxw.desktop $(DESTDIR)/usr/share/applications/qxw.desktop
 
 ## REL-
