#!/bin/bash

# general config
. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/sid-filter.conf

PID=`pidof -o %PPID /usr/sbin/sid-filter`
case "$1" in
    start)
        stat_busy "Starting SenderID Milter"
        if [ -z "$PID" ]; then
            /usr/sbin/sid-filter $SID_FILTER > /dev/null &
        fi
        if [ ! -z "$PID" -o $? -gt 0 ]; then
            stat_fail
        else
            add_daemon sid-filter
            stat_done
        fi
        ;;
    stop)
        stat_busy "Stopping SenderID Milter"
        [ ! -z "$PID" ] && kill $PID &> /dev/null
        if [ $? -gt 0 ]; then
            stat_fail
        else
            rm_daemon sid-filter
            stat_done
        fi
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "usage: $0 {start|stop|restart}"
        ;;
esac
exit 0
