# -*- mode: sh; -*-

note () {
    cat << EOF

==> To start using this package, add the following code to your .emacs:

    (add-to-list 'load-path "/usr/share/emacs/site-lisp/auto-complete")
    (require 'auto-complete-config)
    (add-to-list 'ac-dictionary-directories "/usr/share/emacs/site-lisp/auto-complete/dict")
    (ac-config-default)

EOF
}

post_install() {
    note
}

post_upgrade() {
    note
}


