post_install() {
  echo ""
  echo "WARNING!"
  echo "Remember run go-openoffice-dark-gtk-fix.sh as root each time go-oo gets updated (or it stops working)"
  echo "Your /usr/lib/go-openoffice/program/soffice is being replaced"
  echo "Backup copy of your soffice is saved in /usr/lib/go-openoffice/program/soffice.bak"
  echo ""

  /bin/sh /usr/bin/go-openoffice-dark-gtk-fix.sh
}

post_upgrade() {

  /bin/sh /usr/bin/go-openoffice-dark-gtk-fix.sh
  /bin/cp /usr/lib/go-openoffice/program/soffice.bak /usr/lib/go-openoffice/program/soffice1
	
  echo ""
  echo "WARNING!"
  echo "Your /usr/lib/go-openoffice/program/soffice was replaced"
  echo "Backup copy of your soffice is saved in /usr/lib/go-openoffice/program/soffice.bak"
}

post_remove() {
  echo ""
  echo -e "\033[37;41;1m W A R N I N G \033[0m"
  echo -e "\033[37;41;1m Before the start Go-oo you must restore the default 'soffice' and 'soffice.bin' with: \033[0m"
  echo " mv /usr/lib/go-openoffice/program/soffice.bak /usr/lib/go-openoffice/program/soffice"
  echo " mv /usr/lib/go-openoffice/program/soffice1.bin /usr/lib/go-openoffice/program/soffice.bin"
  echo ""
}
