--- Makefile	2012-01-21 17:15:41.000000000 +0100
+++ Makefile.new	2012-01-21 17:15:27.000000000 +0100
@@ -160,7 +160,7 @@
 LIBGIF_LIBS = -lgif
 LIBJPEG_LIBS = -ljpeg
 LIBOBJS = 
-LIBS = 
+LIBS = -lrt 
 LIBSDL_CFLAGS = 
 LIBSDL_LIBS = 
 LIBTOOL = $(SHELL) $(top_builddir)/libtool
