post_install () {
  echo ">>> Updating module dependencies..."
  /sbin/depmod -A ${KERNEL_VERSION}${LOCAL_VERSION}
  echo ">>> done, now you can load the nvidia-g210m-acpi module to disable nvidia card"
}

post_upgrade() {
  echo ">>> Updating module dependencies..."
  /sbin/depmod -A ${KERNEL_VERSION}${LOCAL_VERSION}
  echo ">>> done, now you can load the nvidia-g210m-acpi module to disable nvidia card"
}



