whisper() {
 echo "amdapp-sdk package was split into 3 packages:"
 echo "amdapp-sdk :: main package"
 echo "amdapp-sdk-aparapi :: AparapiUtil and aparapi samples"
 echo "amdapp-sdk-opencv  :: OpenCVUtils and opencv samples"
 echo ""
}

post_install() {
 echo "    Samples can be found in /opt/AMDAPP/SDK/samples"
 echo ""
 whisper
}

post_upgrade() {
 post_install $1
 printf "Running ldconfig... "
 ldconfig || return 1
 echo "ok"
}


# vim:set ts=2 sw=2 et:
