post_install() {
	cat <<EOF

==> Quick start:
1) start avahi-daemon
2) start the pkgdistcache daemon via
     /etc/rc.d/pkgdistcached start
   (optionally add pkgdistcached to the DAEMONS array
   in /etc/rc.conf)
3) edit /etc/pacman.conf, set the option:
     XferCommand = /usr/bin/pkgdistcache-client %u %o

EOF
}

post_upgrade() {
	/bin/true
}

pre_remove() {
	/bin/true
}

op=$1
shift

$op "$@"

