# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: kusakata <shohei atmark kusakata period com>

_gemname=shoulda
pkgname=ruby-$_gemname
pkgver=3.5.0
pkgrel=1
pkgdesc='Making tests easy on the fingers and eyes'
arch=(any)
url='https://github.com/thoughtbot/shoulda'
license=(MIT)
depends=(ruby ruby-shoulda-context ruby-shoulda-matchers)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('473f0a8f5cdcaf298b70cb4dd0c418a853a35058')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/MIT-LICENSE" "$pkgdir/usr/share/licenses/$pkgname/MIT-LICENSE"
}
