# arg 1:  the new package version
post_install() {
  cat << EOD
==> To start using this package, add the lines below to your .emacs:

    (require 'auto-install)
    (setq auto-install-directory "~/emacs.d/auto-install")

==> Please refer to http://www.emacswiki.org/AutoInstall for more details.
EOD
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $1
}

# vim:set ts=2 sw=2 et:
