# This is a default template for a post-install scriptlet.
# Uncomment only required functions and remove any functions
# you don't need (and this header).

## arg 1:  the new package version
post_install() {
  update-mime-database /usr/share/mime
}

## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
  update-mime-database /usr/share/mime
}

## arg 1:  the old package version
post_remove() {
  update-mime-database /usr/share/mime
}

# vim:set ts=2 sw=2 et:
