# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=cramp
pkgname=ruby-$_gemname
pkgver=0.15.3
pkgrel=1
pkgdesc='Asynchronous web framework.'
arch=(any)
url='http://cramp.in'
license=(MIT)
depends=(ruby ruby-activesupport-3 ruby-rack ruby-eventmachine ruby-faye-websocket ruby-thor-0.18)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('f35fd136803b1115b72dc83d340d969de4234bb4')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/MIT-LICENSE" "$pkgdir/usr/share/licenses/$pkgname/MIT-LICENSE"
}
