#!/bin/sh

. /etc/rc.conf
. /etc/rc.d/functions

DAEMON_FULL='Nyancat Telnet'
DAEMON_SHORT='nyancat'

case "$1" in
	start)
		stat_busy "Starting $DAEMON_FULL daemon"
		if [ -s "/var/run/$DAEMON_SHORT.pid" ]; then
			stat_fail
			stat_busy "$DAEMON_FULL is already running / pid file present. Please use 'stop'"
			stat_die
		fi

		socat -D TCP4-LISTEN:telnet,fork EXEC:"$DAEMON_SHORT -t",su=nobody >"/var/log/$DAEMON_SHORT.log" 2>&1 &
		sleep 1s
		if kill -0 "$!" 2>/dev/null; then
			echo $! >"/var/run/$DAEMON_SHORT.pid"
			add_daemon $DAEMON_SHORT
			stat_done
		else
			stat_fail
		fi
		;;
	stop)
		stat_busy "Stopping $DAEMON_FULL"
		DAEMON_PID=`cat "/var/run/$DAEMON_SHORT.pid" 2>/dev/null`
		if [ -n "$DAEMON_PID" ]; then
			if kill -QUIT "$DAEMON_PID" &>/dev/null; then
				stat_done
			else
				stat_fail
			fi
		else
			stat_fail
		fi
		rm -f "/var/run/$DAEMON_SHORT.pid"

		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "usage: $0 {start|stop|restart}"
esac
