pre_install() {
    if [ -e /usr/share/applications/blaba.desktop ]; then rm /usr/share/applications/blaba.desktop; fi
}

post_install() {
    update-desktop-database -q
    ln -sf /opt/blaba/blaba /usr/bin/blaba
}

pre_upgrade() {
    pre_install
}

post_upgrade() {
    post_install
}

post_remove() {
    if [ -e /usr/bin/blaba ]; then rm /usr/bin/blaba; fi
    if [ -e /usr/share/applications/blaba.desktop ]; then rm /usr/share/applications/blaba.desktop; fi
    update-desktop-database -q
}
