post_install() {
    cat <<__EOF__
==> Copy /usr/share/aws/awssecret to ~/.awssecret
  -> replace line 1 with your Access Key ID
  -> replace line 2 with your Secret Access Key
  -> chmod 600 ~/.awssecret
==> Copy /usr/share/aws/awsrc to ~/.awsrc
  -> see http://timkay.com/aws/ for usage and configuration details
__EOF__
}

post_upgrade() {
    post_install
}

post_remove() {
    echo "==> Don't forget to remove ~/.awssecret"
}
