# generated by the gambas3 ide
# Maintainer : Hamish Paul Wilson <hamish@icculus.org>

pkgname=soulcapture
_realname=soulcapture
pkgdesc="Soul Capture is a free software utility that can be used to capture both the video and audio playback of OpenGL applications such as games."
pkgver=2.0.0
pkgrel=1
arch=('any')
url="http://icculus.org/piga/"
changelog=ChangeLog
license=('custom')
depends=('gambas3-gb-image>=3.0.90' 'gambas3-gb-image<=3.99.0' 'gambas3-gb-gui>=3.0.90' 'gambas3-gb-gui<=3.99.0' 'gambas3-gb-form>=3.0.90' 'gambas3-gb-form<=3.99.0' 'ffmpeg' 'glc')
makedepend=('gambas3-devel')
source=(${_realname}-$pkgver.tar.bz2 license.txt\
        'soulcapture.desktop' 'soulcapture.png')
md5sums=('859acd622558e034d0832a082bcecedc'
         '35403466a659acad9657584fb79a6020'
         '011cfdca6e73e6b7c50f9d86d42161bb'
         'f8f7b9dcc3322a03c0d36c8f00a0cce0')

build() {
  cd ${srcdir}/${_realname}

  /usr/bin/gbc3 -e -a -g -x  && gba3
}

package() {
  cd ${srcdir}/${_realname}

  install -d ${pkgdir}/usr/bin
  install -m755 soulcapture.gambas ${pkgdir}/usr/bin/soulcapture
  install -D ../soulcapture.png \
    ${pkgdir}/usr/share/pixmaps/soulcapture.png
  install -D ../soulcapture.desktop \
    ${pkgdir}/usr/share/applications/soulcapture.desktop
  install -Dm644 ${srcdir}/license.txt ${pkgdir}/usr/share/licenses/soulcapture/license.txt
}
