# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=gpio
pkgname=ruby-$_gemname
pkgver=0.0.6
pkgrel=1
pkgdesc='a ruby gem and repository to contribute gpio code for devices such as Raspberry Pi to read sensors and control outputs.'
arch=(any)
url='http://klappy.github.com/gpio'
license=(unspecified)
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('d4c505f11a58716113586f0658ed61df908f79e3')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
