_pkgdir=/usr/lib/chromium-dev	##edited

post_install() {
    if [ ! -e ${_pkgdir}/libffmpegsumo.so.FREE ]; then
	mv ${_pkgdir}/libffmpegsumo.so ${_pkgdir}/libffmpegsumo.so.FREE
    fi
    touch ${_pkgdir}/libffmpegsumo.so.NONFREE		##added
    mv ${_pkgdir}/libffmpegsumo.so.NONFREE ${_pkgdir}/libffmpegsumo.so
}

post_upgrade() {
    post_install
}

post_remove() {
    if [ -e ${_pkgdir}/libffmpegsumo.so.FREE ]; then
	mv ${_pkgdir}/libffmpegsumo.so.FREE ${_pkgdir}/libffmpegsumo.so
    fi
}
