# arg 1:  the new package version
post_install() {
  groupadd -g 140 liquidsoap &>/dev/null
  useradd -u 140 -g liquidsoap -d /home/liquidsoap -s /bin/false liquidsoap &>/dev/null

  cat << EOM

You have also optional dependencies:


    * libortp for experimental RTP input/output
    * festival is a general multi-lingual speech synthesis system developed at CSTR

EOM
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  userdel liquidsoap &>/dev/null
  groupdel liquidsoap &>/dev/null
}
