#!/bin/sh
if [[ $1 = "--readme" || ! -f $HOME/.probability0 ]]; then
	exec $TERM -title "Probability 0 manual" -e less /usr/share/probability0/probability0.txt &
	touch $HOME/.probability0
fi

cd /usr/share/probability0
exec python2 pzero.pyc

