13,14c13,14
< INCLUDE_OPTS += -I/usr/include/crypto++ -fPIC -DTEST_NETWORK -DUSE_CRYPTOPP -D__STDC_LIMIT_MACROS 
< LIBRARY_OPTS += -lcrypto++ -lpthread
---
> INCLUDE_OPTS += -I/usr/include/crypto++ -fPIC -DTEST_NETWORK -DUSE_CRYPTOPP -D__STDC_LIMIT_MACROS -Icryptopp 
> LIBRARY_OPTS += -lcryptopp -lpthread
