post_install() {
	echo "=> kernel26-eee-monolithic: Please note that you'll have to edit your grub menu.lst."
        echo "=> Someting like this should work:"
        echo "=> title Kernel-eee-mono"
        echo "=> root (hdX,Y) # Just copy X, Y from your stock kernel entry"
        echo "=> kernel /boot/vmlinuz30-eee root=/dev/sda1 ro rootwait i915.modeset=1 # Again, edit the root-path according to your setup"
}
