# Maintainer: Iwan Timmer <irtimmer@gail.com>
# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Contributor: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=listen
pkgname=ruby-$_gemname-1.1
pkgver=1.1.0
pkgrel=1
pkgdesc='Listen to file modifications'
arch=(any)
url='https://github.com/guard/listen'
license=(MIT)
depends=(ruby ruby-rb-fsevent ruby-rb-inotify ruby-rb-kqueue)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('de37f743d3498d4e6fb72f63b08b7e58c696f64b')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
