pre_remove()
{
    rm -f -v /usr/bin/bii
    rm -f -v /usr/bin/pythonrunner
    rm -f -v /usr/bin/noderunner

    rm -r -f -v  "/usr/share/doc/biicode"
    rm -r -f -v  "/usr/lib/biicode"
    rm -r -f -v  "/usr/lib/bii"
}

post_install()
{
    ln -s -f /usr/lib/biicode/bii                 /usr/bin/bii
    ln -s -f /usr/lib/biicode/bin/pythonrunner.sh /usr/bin/pythonrunner
    ln -s -f /usr/lib/biicode/bin/noderunner.sh   /usr/bin/noderunner
}
