# Message displayed after a fresh install.
post_install() {
    cat << _EOF

    Add to your ~/.emacs
    (require 'key-chord)
    (key-chord-mode 1)
    and some chords, for example
    (key-chord-define-global "hj"     'undo)
    (key-chord-define-global ".."     "<>\C-b")

_EOF
    }

 
# Message displayed afteer package removal.
post_remove() {
    echo "Remove these lines from ~/.emacs:"
    echo "  (require 'key-chord)"
    echo "  (key-chord-mode 1)"
}
