post_install() {
echo ""
echo ":: If the animations are flickering on your nvidia card with the latest"
echo ":: driver, add the following line to your xorg config file, into the nvidia"
echo ":: device section, to fix it:"
echo ""
echo ":: Option "HWCursor" "off" "
echo ""
}

post_upgrade() {
echo ""
echo ":: If the animations are flickering on your nvidia card with the latest"
echo ":: driver, add the following line to your xorg config file, into the nvidia"
echo ":: device section, to fix it:"
echo ""
echo ":: Option "HWCursor" "off" "
echo ""
}

pre_remove() {
/bin/true
}

op=$1
shift

$op "$@"