pre_install() {
	/bin/true
}

post_install() {
	echo jEdit has been installed successfully.
	echo
	echo "To start jEdit, run the **jedit** command in a terminal window:"
	echo $ jedit _filename_ ...
	echo
	echo To find out about supported command-line options, run:
	echo $ man jedit
}

pre_upgrade() {
	/bin/true
}

post_upgrade() {
	post_install
}

pre_remove() {
	/bin/true
}

post_remove() {
	/bin/true
}

op=$1
shift
$op $*
