post_install() {
  KERNEL_VERSION=`uname -r`
  depmod -a -v $KERNEL_VERSION > /dev/null 2>&1
  echo "*************** Loading fusion kernel module ******************"
  modprobe fusion
  echo "***************************************************************"
  echo "Please add fusion in the MODULES entry in the HARWARE section of "
  echo "your /etc/rc.conf file if you want this module to be loaded at boot time."
  echo "You can also load this module at any time by typing 'modprobe fusion' from the"
  echo "command line as root"
}

post_upgrade() {
  rmmod fusion
  post_install
}

pre_remove() {
	rmmod fusion
}

post_remove() {
  KERNEL_VERSION=`uname -r`
  depmod -a -v $KERNEL_VERSION > /dev/null 2>&1
}

op=$1
shift
$op $*
