pre_install() {
  getent group fanout > /dev/null
  if [ $? -ne 0 ]; then
    echo 'Adding group fanout'
    groupadd -f fanout
  fi
  id fanout &> /dev/null
  if [ $? -ne 0 ]; then
    echo 'Adding user fanout'
    useradd -r fanout -g fanout
  fi
}

post_install() {
  chown -R fanout:fanout /var/log/fanout
}

post_remove() {
  userdel fanout
  getent group fanout &> /dev/null && groupdel fanout
  true
}
