# This is a default template for a post-install scriptlet.
# Uncomment only required functions and remove any functions
# you don't need (and this header).


post_install() {
  echo "Install glib-schema"
  glib-compile-schemas /usr/share/glib-2.0/schemas
}

post_upgrade() {
  echo "Recompile glib-schemas"
  glib-compile-schemas /usr/share/glib-2.0/schemas
}

post_remove() {
  echo "Recompile glib-schemas"
  glib-compile-schemas /usr/share/glib-2.0/schemas
}

# vim:set ts=2 sw=2 et:
