post_install() {
  groupadd zabbix
  useradd -g zabbix -d /dev/null zabbix 
  chown -R zabbix:zabbix /var/log/zabbix /var/run/zabbix /etc/zabbix
  echo "zabbix-agent    10050/tcp  Zabbix Agent" >> /etc/services
  echo "zabbix-agent    10050/udp  Zabbix Agent" >> /etc/services
  echo "zabbix-trapper  10051/tcp  Zabbix Trapper" >> /etc/services
  echo "zabbix-trapper  10051/udp  Zabbix Trapper" >> /etc/services
}

post_upgrade() {
	cat <<EOM

	Upgrade to 2.0.3-4:
	Add "PidFile=/var/run/zabbix/zabbix_agentd.pid" to "/etc/zabbix/zabbix_agentd.conf".
EOM
}

post_remove() {
   userdel zabbix
   rm -rf /var/run/zabbix
}
