#!/bin/bash
#
# Source function library.
. /etc/rc.conf
. /etc/rc.d/functions


start () {
  stat_busy "Starting zabbix-agent"
  mkdir -p /var/log/zabbix
  mkdir -p /var/run/zabbix
  chown -R zabbix:zabbix /var/log/zabbix /var/run/zabbix
  /usr/sbin/zabbix_agentd &>/dev/null
  if [ $? -gt 0 ]; then
     stat_fail
  else
     add_daemon zabbix-agentd
     stat_done
  fi
 }

stop() {
  stat_busy "Stopping zabbix-agent"
  killall zabbix_agentd
  if [ $? -gt 0 ]; then
     stat_fail
  else
     rm_daemon zabbix-agentd
     stat_done
  fi
  }

# See how we were called.
case $1 in	
  start)
   start
   ;;
  stop)
   stop
   ;;
  restart)
   stop
   start
   ;;
  *)
  echo $"Usage: zabbix-agent {start|stop|restart}"
  exit 1
 esac

exit $RETVAL
