pre_install() {

cd /lib/modules/`uname -r`/kernel/drivers/net/wireless/rtlwifi

mv rtlwifi.ko.gz oldrtlwifi.ko.gz
  
}

post_install() {
	dkms install -m rtl8723e -v 1
}

pre_upgrade(){
	dkms remove -m rtl8723e -v 1 --all
}

post_upgrade() {
	dkms install -m rtl8723e -v 1 
}

pre_remove() {
	dkms remove -m rtl8723e -v 1 --all
}

post_remove() {

cd /lib/modules/`uname -r`/kernel/drivers/net/wireless/rtlwifi

mv oldrtlwifi.ko.gz rtlwifi.ko.gz

depmod -a

}
