post_install() {
    mv /usr/include/event2/event-config.h /usr/include/event2/event-config-64.h
    ln -s event-config-stub.h /usr/include/event2/event-config.h
}

post_upgrade() {
    if [ ! -r /usr/include/event2/event-config.h ]; then
        post_install
    else
        echo WARNING: libx32-libevent is upgraded before libevent,
        echo WARNING: you probably need to reinstall libx32-libevent.
    fi
}

post_remove() {
    if [ -r /usr/include/event2/event-config.h ]; then
        rm /usr/include/event2/event-config.h
        mv /usr/include/event2/event-config-64.h /usr/include/event2/event-config.h
    fi
}

