post_install()
{
	echo "Please set \$BROWSER and \$EDITOR in your ~/.bashrc"
	echo "For instance:"
	echo ""
	echo "export BROWSER=lynx"
	echo "export EDITOR=nano -c"
	echo ""
	echo "If you are a nano user, -c will show a character count."
	echo ""
	echo "Please add your identi.ca credentials to ~/.netrc by adding the following line:"
	echo ""
	echo "machine identi.ca login FooBar password barfoo"
	echo ""
}

