# -*- mode: sh; -*-

note () {
    cat << EOF

==> To start using this package, add the lines below to your .emacs:

    (add-to-list 'load-path "/usr/share/emacs/site-lisp/nav")
    (require 'nav)
    (nav-disable-overeager-window-splitting)
    ;; Optional: set up a quick key to toggle nav
    ;; (global-set-key [f8] 'nav-toggle)

EOF

}

post_install() {
    note
}

# pre_remove() {
# }

post_upgrade() {
    note
}
