post_install() {
echo -e "\n"    
echo "*************************************"
echo " HOW TO ENABLE SOUND IN CRACK-ATTACK"     
echo -e "*************************************\n"
echo "If, after installing this package, you still have no sound,"
echo -e "then you probably compiled crack-attack without sound support.\n"
echo "If so, rebuild crack-attack adding '--enable-sound=yes' to the "
echo -e "configure command line.\n"
}

post_upgrade() {
    post_install $1
}
