# Generated by gem2arch

_gemname=awesome_print
pkgname=ruby-$_gemname
pkgver=1.2.0
pkgrel=1
pkgdesc="Pretty print Ruby objects with proper indentation and colors"
arch=('any')
url="http://github.com/michaeldv/awesome_print"
license=('')
depends=('ruby')
makedepends=('rubygems')
source=(http://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
md5sums=('d341e1e59844980d453a0b647bb7f34e')
sha1sums=('03832f432715b91b2f3a2c2fc2a03c1816b6dde3')

package() {
  cd "$srcdir"
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
}
