post_install() {
  depmod -a
  echo ""
  echo "[+] modprobe acpi_call"
  echo ">>> run /usr/bin/test_off.sh to test/view different acpi_call functions to see if it disables your secondary/hybrid video card"
}

post_upgrade() {
  depmod -a
  echo ""
  echo "[+] modprobe acpi_call"
  echo ">>> run /usr/bin/test_off.sh to test/view different acpi_call functions to see if it disables your secondary/hybrid video card"
}

post_remove() {
  depmod -a
}

op=$1
shift
$op $*
