post_remove() {
  echo -e "\n >>> All files created after installation are in the /opt/opensimulator-osgrid."
  echo -e " >>> If you want, you may delete them manually."
}

post_install() {
  echo -e "\n >>> WARNING: there are currently bugs in mono 2.4.3 or higher that"
  echo -e ">>> make SQLITE unusable in opensimulator.  If you intend to use"
  echo -e ">>> SQLITE as the database backend, install the mono-old package"
}
