post_upgrade() {
	echo ">>> Please merge the pacnew files of"
	echo ">>> /opt/opensimulator-osgrid/bin/OpenSim.ini and"
	echo ">>> opt/opensimulator-osgrid/bin/config-include/GridCommon.ini"
	echo ">>> according to the instructions in"
	echo ">>> http://news.osgrid.org/2013/03/03/update-release-changes-for-osgrid-opensimulator-0-7-6-dev-e70c71a/"
}
	

post_remove() {
  echo -e ">>> All files created after installation are in the /opt/opensimulator-osgrid."
  echo -e ">>> If you want, you may delete them manually."
}
