post_install(){
	/usr/share/brother/cupswrapper/cupswrapperMFC210C-1.0.2
}

post_upgrade(){
	_ppd_file=$(grep -l 'ModelName: "Brother MFC-210C"' /etc/cups/ppd/* | grep MFC210C.ppd)

	/usr/share/brother/cupswrapper/cupswrapperMFC210C-1.0.2
	
	if [ "$_ppd_file" == "" ]; then
		lpadmin -x MFC210C
	fi

}

pre_remove() {
	/usr/share/brother/cupswrapper/cupswrapperMFC210C-1.0.2 -e
	rm -f /usr/lib/cups/filter/brlpdwrapperMFC210C
}

