
pre_install() {
  /bin/true
}

post_install() {
  echo " ==> Setting permissions to allow auto-update"
  chgrp -R users /opt/dofus-beta/share
  chmod -R g+w /opt/dofus-beta/share
  echo " ==> Note: The first auto-update will download all game"
  echo " ==>       content and may take a long time (~1GB)."
}

pre_upgrade() {
  echo " ==> Backing up last downloads..."
  [ -e /opt/dofus-beta/share/DofusInvoker.swf ] && cp /opt/dofus-beta/share/DofusInvoker.swf /opt/dofus-beta/share/DofusInvoker.swf.bak
  [ -e /opt/dofus-beta/share/reg/Reg.swf ] && cp /opt/dofus-beta/share/reg/Reg.swf /opt/dofus-beta/share/reg/Reg.swf.bak
  [ -e /opt/dofus-beta/share/UpLauncher ] && cp /opt/dofus-beta/share/UpLauncher /opt/dofus-beta/share/UpLauncher.bak
  [ -e /opt/dofus-beta/share/uplauncherComponents.xml ] && cp /opt/dofus-beta/share/uplauncherComponents.xml /opt/dofus-beta/share/uplauncherComponents.xml.bak
}

post_upgrade() {
  echo " ==> Restoring last downloads..."
  [ -e /opt/dofus-beta/share/DofusInvoker.swf.bak ] && mv /opt/dofus-beta/share/DofusInvoker.swf.bak /opt/dofus-beta/share/DofusInvoker.swf
  [ -e /opt/dofus-beta/share/reg/Reg.swf.bak ] && mv /opt/dofus-beta/share/reg/Reg.swf.bak /opt/dofus-beta/share/reg/Reg.swf
  [ -e /opt/dofus-beta/share/UpLauncher.bak ] && mv /opt/dofus-beta/share/UpLauncher.bak /opt/dofus-beta/share/UpLauncher
  [ -e /opt/dofus-beta/share/uplauncherComponents.xml.bak ] && mv /opt/dofus-beta/share/uplauncherComponents.xml.bak /opt/dofus-beta/share/uplauncherComponents.xml
  echo " ==> Setting permissions to allow auto-update"
  chgrp -R users /opt/dofus-beta/share
  chmod -R g+w /opt/dofus-beta/share
}

pre_remove() {
  /bin/true
}

post_remove() {
  echo " ==> Note: To completely remove Dofus from your disk,"
  echo " ==>       delete the folder /opt/dofus and its subfolders."
  echo " ==>       This is due to the auto-updater's temp files."
}

# vim:set ts=2 sw=2 et:
