--- Makefile.original	2013-05-30 20:21:43.117873227 +0200
+++ Makefile	2013-05-30 20:23:14.217882337 +0200
@@ -52,9 +52,9 @@
 	gzip -c $< > $@
 
 install: install-files
-	groupadd -f --system gpio
-	chgrp gpio $(DESTDIR)/bin/gpio-admin
-	chmod u=rwxs,g=rx,o= $(DESTDIR)/bin/gpio-admin
+#	groupadd -f --system gpio
+#	chgrp gpio $(DESTDIR)/bin/gpio-admin
+#	chmod u=rwxs,g=rx,o= $(DESTDIR)/bin/gpio-admin
 .PHONY: install
 
 install-files: all
