post_install() {
    getent passwd i2p &>/dev/null || {
        echo -n ">>> Creating i2p system user... "
        /usr/sbin/useradd --system --user-group --home /opt/i2p i2p
        echo "done"
    }
    chown i2p:i2p /run/i2p
    chown -R i2p:i2p /opt/i2p
}

post_upgrade() {
    if [[ "$2" = 0.9.4* && "$1" = 0.9.5* ]]; then
    cat << EOF
The original i2prouter script has been rewritten in a simpler and cleaner manner.
Due to the change in pid location, you will need to stop i2p from its web-console or
by manually terminating the process. Else it behaves exactly the same as the original.

EOF
    fi
    chown i2p:i2p /run/i2p
    chown -R i2p:i2p /opt/i2p
}

pre_remove() {
    getent passwd i2p &>/dev/null && {
        echo -n ">>> Removing i2p system user... "
        /usr/sbin/userdel i2p
        echo "done"
    }
}
