#!/bin/bash

USER=sylar

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /opt/dropbox/dropbox`

case "$1" in
  start)
    stat_busy "Starting Dropbox Service"
    [ -z "$PID" ] && su -c "/usr/bin/dropboxd &" $USER
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon dropboxd
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping Dropbox Service"
    [ ! -z "$PID" ] && kill $PID > /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon dropboxd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 3
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
    ;;
esac
exit 0

