post_upgrade() {
	## arg 1:  the new package version
	## arg 2:  the old package version
	oldpkgver=${2%-*}
	#newpkgver=${1%-*}

	if [[ $oldpkgver < 2.17 ]]; then
		echo
		echo '--> Please check ~/.config/clean-chroot-manager.conf against the'
		echo '--> provided /usr/share/clean-chroot-manager/ccm.skel to ensure it is'
		echo '--> updated as the script does not do this automatically.'
	else
		/bin/true
	fi	
}
