# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>
# Contributor: eagletmt <eagletmt@gmail.com>

_gemname=em-synchrony
pkgname=ruby-$_gemname
pkgver=1.0.3
pkgrel=1
pkgdesc='Fiber aware EventMachine libraries'
arch=(any)
url='https://github.com/igrigorik/em-synchrony'
license=(MIT)
depends=(ruby ruby-eventmachine)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('f7af3e0837f4585f6b37873f124f9b824e528d22')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
