#!/bin/bash

package=$(basename $0)

export WINEPREFIX="$HOME/."$package"/wine"

if [ ! -d "$HOME"/."$package" ] ; then
  mkdir -p "$HOME"/."$package"/wine || exit 1
  wineprefixcreate || exit 1
fi

wine /usr/share/"$package"/"$package".exe $*
