#! /bin/sh
x[1]=37
x[2]=22
x[3]=35
x[4]=34
x[5]=18
x[6]=5
Format[1]=1080p
Format[2]=720p
Format[3]=480p
Format[4]=360p_128kbs
Format[5]=360p_96kbs
Format[6]=240p
x=~/.youtube-dl-$RANDOM-$RANDOM.flv

for (( i = 1; i <= 6; i++ ))
do
    echo ${Format[$i]}
    youtube-dl --output=$x --format=${x[$i]} "$1"
    if test -e $x;
    then 
      ffmpeg -i $x -acodec libmp3lame -ac 2 -ab 192k -vn -y "$2"
      rm $x
      exit
    fi
done



