# Generated by gem2arch
# Maintainer: Reuben Castelino <projectdelphai at gmail dot com>

_gemname=httparty
pkgname=ruby-$_gemname
pkgver=0.13.3
pkgrel=1
pkgdesc="Makes http fun! Also, makes consuming restful web services dead easy."
arch=('any')
url="http://jnunemaker.github.com/httparty"
license=('GPL')
depends=('ruby' 'ruby-json>=1.8' 'ruby-multi_xml>=0.5.2')
makedepends=('rubygems')
source=(http://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
md5sums=('e19c2b90663f0a7920a5912d80f9c3b3')
sha1sums=('846a70b4773998c2bcc7c9638fba3328141c14ea')

package() {
  cd "$srcdir"
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
}
