post_install() {
  echo "Don't forget to set your home directory in /etc/conf.d/dimdaemon.conf and add dimdaemond to the DAEMONS array in your rc.conf."
  echo "If you use instead systemd you can enable dimdaemon to start at boot by issuing systemd enable dimdaemon.service."
}
post_upgrade() {
  echo "If you want dimdaemon to start at boot, add dimdaemond to the DAEMONS array in your rc.conf."
  echo "If you use instead systemd, you can enable dimdaemon to start at boot by issuing systemd enable dimdaemon.service."
}
