# arg 1:  the new package version
post_install() {
  echo "To be able to use lxdream you will need a copy of the Dreamcast BIOS.
        A guide to dump the BIOS is available at the following URL:
  http://forums.ngemu.com/misc-dreamcast-discussion/51969-how-dump-your-own-dc-bios-flash.html"
  post_update()
}

post_update() {
  [ -f "/usr/bin/update-desktop-database" ] && update-desktop-database -q
}

op=$1
shift
[ "$(type -t "$op")" = "function" ] && $op "$@"

# vim:set ts=2 sw=2 et:
