post_install() {
    echo "Make sure to add yourself to the games group if you want to play."
    echo "64bit users, make sure you have a right dri package for your card"
    echo "lib32-(ati/intel/noveau)-dri or lib32-(catalyst/nvidia)-utils."
    echo "Happy folding ^-^."
}

post_remove() {
    echo "Making sure all data is removed. Updating game will cause pacman to lose track of the files!"
    rm -r /usr/share/games/foldit
}

