post_install() {
  echo 'Do not forget to configure your vdirsyncer installation.'
  echo 'A sample and self explanatory configuration file has been put in /etc/skel/khal.conf.'
  echo 'Copy it in ~/.config/khal/khal.conf and edit it as needed.'
}

post_upgrade(){
  echo 'You may want to remove your old local sqlite database (usually in ~/.config/khal/khal.db, following your prefs in your config file) before doing the first khal --sync, as the database internal structure may have changed.'
}