# Message displayed for a fresh install.
post_install()
{ 
  echo ""
  echo "***************************************************************"
  echo " DAGII has been installed. Try running dagii -h to see a list"
  echo " of command-line options. Common usage follows:"
  echo " dagii /some/path/gamefolder/or_game.zip"
  echo "***************************************************************"
  echo ""
}

# Message for an update.
post_upgrade()
{
  post_install
}

op=$1
shift
$op $*
