#!/bin/bash

declare -A perms

perms=(
	# MPROTECT and RANDMMAP off
	['PSmXEr']='
		/usr/lib/chromium/chromium
		/usr/lib/firefox/firefox-bin
		/usr/lib/firefox/plugin-container
		/usr/lib/thunderbird/thunderbird-bin
	'
	# PAGEEXEC and MPROTECT off
	['pSmXER']='
		/opt/Osmos/Osmos.bin32
		/opt/Osmos/Osmos.bin64
		/usr/share/worldofgoo/WorldOfGoo.bin32
		/usr/share/worldofgoo/WorldOfGoo.bin64
	'
	# MPROTECT off
	['PSmXER']='
		/opt/android-sdk/tools/emulator-arm
		/opt/android-sdk/tools/emulator-x86
		/opt/quake3/ioquake3.i386
		/opt/quake3/ioquake3.x86_64
		/usr/bin/glxdemo
		/usr/bin/glxgears
		/usr/bin/glxinfo
		/usr/bin/mplayer
		/usr/bin/valgrind
		/usr/lib/valgrind/cachegrind-amd64-linux
		/usr/lib/valgrind/cachegrind-x86-linux
		/usr/lib/valgrind/callgrind-amd64-linux
		/usr/lib/valgrind/callgrind-x86-linux
		/usr/lib/valgrind/drd-amd64-linux
		/usr/lib/valgrind/drd-x86-linux
		/usr/lib/valgrind/exp-bbv-amd64-linux
		/usr/lib/valgrind/exp-bbv-x86-linux
		/usr/lib/valgrind/exp-dhat-amd64-linux
		/usr/lib/valgrind/exp-dhat-x86-linux
		/usr/lib/valgrind/exp-sgcheck-amd64-linux
		/usr/lib/valgrind/exp-sgcheck-x86-linux
		/usr/lib/valgrind/helgrind-amd64-linux
		/usr/lib/valgrind/helgrind-x86-linux
		/usr/lib/valgrind/lackey-amd64-linux
		/usr/lib/valgrind/lackey-x86-linux
		/usr/lib/valgrind/massif-amd64-linux
		/usr/lib/valgrind/massif-x86-linux
		/usr/lib/valgrind/memcheck-amd64-linux
		/usr/lib/valgrind/memcheck-x86-linux
		/usr/lib/valgrind/none-amd64-linux
		/usr/lib/valgrind/none-x86-linux
		/usr/lib/xbmc/xbmc.bin
	'
	# All off
	['psmxer']='
		/usr/lib/jvm/java-6-openjdk/bin/java
		/usr/lib/jvm/java-6-openjdk/jre/bin/java
	'
)

[ "$UID" = "0" ] || {
	sudo $0
	exit $!
}

echo Some programs do not work properly without deactivating some of the PaX
echo features. Please close all instances of them if you want to change the
echo configuration for the following binaries:

for perm in ${!perms[@]}; do
	for path in ${perms[$perm]}; do
		[ -f $path ] && echo " * $path"
	done
done

echo
echo Continue writing PaX headers? \[Y/n\]

read a

case $a in
	"Y"|"y"|"")
		for perm in ${!perms[@]}; do
			for path in ${perms[$perm]}; do
				[ -f $path ] && {
					echo $perm $path
					paxctl -c$perm $path
				}
			done
		done
		;;
	*)
		exit 0
		;;
esac
