# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>
# Contributor: Alfredo Palhares <masterkorp@masterkorp.net>
# Contributor: Emiliano Vavassori <syntaxerrormmm(at)gmail.com>
# Contributor: nbryskin

_gemname=excon
pkgname=ruby-$_gemname-0.25.0
pkgver=0.25.0
pkgrel=2
pkgdesc='speed, persistence, http(s)'
arch=(any)
url='https://github.com/geemus/excon'
license=(MIT)
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('fafb1299a1ba901c93881e96cc2ee0c18d60aef6')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
