#!/bin/bash

# source application-specific settings
SQUID_ARGS=
[ -f /etc/conf.d/c-icap ] && . /etc/conf.d/c-icap

. /etc/rc.conf
. /etc/rc.d/functions

PID_FILE=/var/run/c-icap/c-icap.pid
PID=`cat ${PID_FILE}`
case "$1" in

  start)
    stat_busy "Starting c-icap"
    if [ ${CICAP_RUN} != "yes" ]; then
      echo "Configure c-icap and then enable it in /etc/conf.d/c-icap"
      stat_fail
    else
      [ -z "$PID" ] && /usr/bin/c-icap ${CICAP_ARGS}
      if [ $? -gt 0 ]; then
        echo "File ${PID_FILE} exists."
        stat_fail
      else
        add_daemon c-icap
        stat_done
      fi
    fi
    ;;

  stop)
    stat_busy "Stopping c-icap"
    echo -n "stop" > ${CICAP_SOCKET}
    if [ $? -gt 0 ]; then
      stat_fail
    else
      # wait for c-icap to shutdown so we can safely do a restart
      while [ ! -z "`pidof -o %PPID /usr/bin/c-icap`" ]; do
        stat_append "."
        sleep 1
      done
      rm_daemon c-icap
      stat_done
    fi
    ;;

  restart)
    $0 stop
    sleep 5
    $0 start
    ;;
  reload)
    echo -n "reconfigure" > ${CICAP_SOCKET}
    ;;
  *)
    echo "usage: $0 {start|stop|restart|reload}"  
esac
exit 0
