#!/bin/sh

sd_booted() {
  [ -e sys/fs/cgroup/systemd ]
}

machine_id_setup() {
  if [ ! -f etc/machine-id ]; then
    systemd-machine-id-setup
  fi
}

post_install() {
  machine_id_setup

  echo "systemd has been installed to /bin/systemd. Please ensure you append"
  echo "init=/bin/systemd to your kernel command line in your bootloader."
}

post_upgrade() {
  machine_id_setup

  if sd_booted; then
    systemctl daemon-reload
    systemctl daemon-reexec
  fi
}

# vim:set ts=2 sw=2 et:
