# arg 1:  the new package version
post_install()
{
echo "For the defaults, line 1 goes into passwd, and 2 into group."
echo "portage:x:250:250:portage:/var/tmp/portage:/bin/false"
echo "portage::250:portage"
echo ""
}

post_remove()
{
echo "Do you want to purge the ebuild storage folder?[y/n]"
read input
if [ "$input" == "y" ] ; then 
  rm -r /usr/portage
  echo "Purged!"
else
  echo "Nothing to do!See you later cowboy"
fi

}
