post_install() {
   echo
   echo "This package provides a file: /etc/profile.d/xc16-toolchain-bin.sh"
   echo "It will add the toolchain binaries to the PATH variable for every user."
   echo "It also defines XC16_TOOLCHAIN_ROOT pointing to the toolchain install dir."
   echo "Log out and log back in to update your environment varibles or run:"
   echo "source /etc/profile"
   echo "now to do so immediately for this shell."
   echo
}
