post_install() {
  mkdir -p /usr/share/backgrounds
  ln -s /usr/share/archlinux/wallpaper/archlinux-berry.jpg /usr/share/backgrounds/pantheon-greeter
  glib-compile-schemas usr/share/glib-2.0/schemas

  echo "You can change the wallpaper by modifing the symlink \"/usr/share/backgrounds/pantheon-greeter\""
}


post_remove() {
  unlink /usr/share/backgrounds/pantheon-greeter
  glib-compile-schemas usr/share/glib-2.0/schemas
}


post_update(){
    mkdir -p /usr/share/backgrounds
}
