post_install() {
	echo "---------------------------------------------------------------------"
	echo "Execute acvd and acvdq without arguments to see the available options."
	echo "The output of the program is written in the file simplification.ply."
	echo "Additionally, when running ACVD, a file output_1.ply is also written."
	echo "It is the output mesh before post-processing using quadrics."
	echo "---------------------------------------------------------------------"
}	


