#!/bin/sh

. /etc/rc.conf
. /etc/rc.d/functions

CONF="/etc/conf.d/spawn-fcgi-php.conf"

if [ -r $CONF ]; then
	. $CONF
else
	echo "File $CONF not found"
	stat_die
fi


start(){
	echo "Starting server $(basename $PHPCGI)"
	if [ -s "$PIDFILE" ]; then 
		echo -e "\n$(basename $PHPCGI) is running. Stop it first"
		stat_die
	fi
	$DAEMON $OPTIONS
	if (( ! $? )); then
		add_daemon spawn-fcgi-php
		stat_done
	else
		stat_die
	fi
}
stop(){
	echo "Stopping server $(basename $PHPCGI)"
	if [ -s "$PIDFILE" ]; then
		kill `<$PIDFILE`
		 if (( ! $? )); then
			rm -f "$PIDFILE"
			rm_daemon spawn-fcgi-php	
			stat_done
		else
			rm -f "$PIDFILE"
			stat_die
		fi
	else
		echo "$(basename $PHPCGI) is not running. File $PIDFILE not found"
	fi
}
restart(){
	stop
	start
}
status(){
	ps aux | grep $PHPCGI | grep -v grep
}

case $1 in
	start)
	start
	;;
	stop)
	stop
	;;
	restart)
	restart
	;;
	status)
	status
	;;
	*)
	echo "Usage: $0 start|stop|restart|status"
esac
