#!/bin/sh

. /etc/rc.conf
. /etc/rc.d/functions

CONF="/etc/conf.d/spawn-fcgi-php.conf"

if [ -r $CONF ]; then
	. $CONF
else
	echo "File $CONF not found"
	stat_die
fi
start(){ #{{{
	stat_busy "Starting server $(basename $PHPCGI)"
	if [ -s "$PIDFILE" ]; then 
		echo -e "\n$(basename $PHPCGI) is running. Stop it first"
		stat_die
	fi
	$DAEMON $OPTIONS >/dev/null
	if [ $? -eq 0 ]; then
		add_daemon spawn-fcgi-php
		stat_done
	else
		stat_fail
		exit 1
	fi
} #}}}
stop(){ #{{{
	stat_busy "Stopping server $(basename $PHPCGI)"
	if [ -s "$PIDFILE" ]; then
		kill `<$PIDFILE`
		 if [ $? -eq 0 ]; then
			rm -f "$PIDFILE"
			rm_daemon spawn-fcgi-php	
			stat_done
		else
			rm -f "$PIDFILE"
			stat_fail
			exit
		fi
	else
		echo "$(basename $PHPCGI) is not running. File $PIDFILE not found"
	fi
} #}}}
restart(){ #{{{
	stop
	sleep 1
	start
} #}}}
status(){ #{{{
	ps aux | grep $PHPCGI | grep -v grep
} #}}}
case $1 in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	status)
		status
		;;
	*)
		echo "Usage: $0 start|stop|restart|status"
esac
