# arg 1:  the new package version
post_install() {
cat << EOF

Find and edit in /etc/sane.d/dll.conf this
...
epson
...

in

...
#epson
epkowa
...

or run this su command 

perl -p -i.bak -e 's/epson\n/epkowa\n#epson\n/g' /etc/sane.d/dll.conf

EOF
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
post_install $1
}

# arg 1:  the old package version
pre_remove() {
cat << EOF

==> Don't forget to update your /etc/sane.d/dll.conf

EOF
}

op=$1
shift

$op $*
