post_install() {
	post_upgrade
	passwd -l facette &>/dev/null
}

post_upgrade() {
	# create user/group that the daemon will run as by default, do not delete this on uninstall, as it will own files
	getent group facette >/dev/null || groupadd facette
	getent passwd facette >/dev/null || useradd -c 'facette' -g facette -b '/var/lib' -m -s /bin/false facette

	chown facette:facette /var/log/facette
	chown facette:facette /var/run/facette
	chown facette:facette /var/lib/facette
}
