# arg 1:  the new package version
post_install() {
  /bin/cat <<THEEND
NOTE
----
To configure Linux Terminal Server Project:
Run the ltspadmin command. This utility is used to manage the LTSP Client packages. It will query the LTSP download repository, and get the list of currently available packages.
See http://www.ltsp.org/documentation/index.php for more information.
THEEND
}

op=$1
shift
$op $*
