post_install() {
  post_remove
  cat << EOF

>>> If you get in troubles related to glib.USER_DIRECTORY_MUSIC in running gsharkdown,
>>> install xdg-user-dirs optional dependency and run:
>>>
>>> xdg-user-dirs-update
>>>
>>> or, if you do not want to install it,
>>> create a user-dirs.dirs file in your \$XDG_CONFIG_HOME:
>>>
>>> echo XDG_MUSIC_DIR="\$HOME/Music" >> ~/.config/user-dirs.dirs

EOF
}

post_upgrade() {
  post_install
}

post_remove() {
  update-desktop-database -q
}