# arg 1:  the new package version
post_install()
{
  /sbin/depmod > /dev/null 2>&1
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade()
{
  /sbin/depmod > /dev/null 2>&1
}

# arg 1:  the old package version
pre_remove() {
  /sbin/rmmod ov51x-jpeg > /dev/null 2>&1
}

# arg 1:  the old package version
post_remove()
{
  /sbin/depmod > /dev/null 2>&1
}

op=$1
shift
$op $*

