infofiles=(
	/usr/share/info/h8300-hitachi-coff-ld.info.gz
	/usr/share/info/h8300-hitachi-coff-as.info-3.gz
	/usr/share/info/h8300-hitachi-coff-as.info-2.gz
	/usr/share/info/h8300-hitachi-coff-as.info-1.gz
	/usr/share/info/h8300-hitachi-coff-as.info.gz
	/usr/share/info/h8300-hitachi-coff-configure.info.gz
	/usr/share/info/h8300-hitachi-coff-standards.info.gz
	/usr/share/info/h8300-hitachi-coff-binutils.info.gz
	/usr/share/info/h8300-hitachi-coff-bfd.info-2.gz
	/usr/share/info/h8300-hitachi-coff-bfd.info-1.gz
	/usr/share/info/h8300-hitachi-coff-bfd.info.gz
)

post_install() {
	for file in ${infofiles[@]}; do
		install-info $file /usr/share/info/dir 2>/dev/null
	done
}

post_upgrade() {
	for file in ${infofiles[@]}; do
		install-info $file /usr/share/info/dir 2>/dev/null
	done
}

pre_remove() {
	for file in ${infofiles[@]}; do
		install-info --delete $file /usr/share/info/dir 2>/dev/null
	done
}

