--- ./Makefile.am	2012-12-14 20:41:31.791011557 -0800
+++ ./Makefile.am	2012-12-14 20:43:39.027042030 -0800
@@ -12,7 +12,7 @@
 
 bin_PROGRAMS	= bfgminer
 
-bin_SCRIPTS	= *.cl
+pkgdata_SCRIPTS	= *.cl
 
 bfgminer_LDFLAGS	= $(PTHREAD_FLAGS)
 bfgminer_LDADD	= $(DLOPEN_FLAGS) @LIBCURL_LIBS@ @JANSSON_LIBS@ @PTHREAD_LIBS@ \
@@ -109,18 +109,18 @@
 
 if HAS_MODMINER
 bfgminer_SOURCES += driver-modminer.c
-bitstreamsdir = $(bindir)/bitstreams
+bitstreamsdir = $(pkgdatadir)/bitstreams
 dist_bitstreams_DATA = bitstreams/*
 endif
 
 if HAS_X6500
 bfgminer_SOURCES += driver-x6500.c ft232r.c ft232r.h jtag.c jtag.h
-bitstreamsdir = $(bindir)/bitstreams
+bitstreamsdir = $(pkgdatadir)/bitstreams
 dist_bitstreams_DATA = bitstreams/*
 endif
 
 if HAS_ZTEX
 bfgminer_SOURCES += driver-ztex.c libztex.c libztex.h
-bitstreamsdir = $(bindir)/bitstreams
+bitstreamsdir = $(pkgdatadir)/bitstreams
 dist_bitstreams_DATA = bitstreams/*
 endif
