#!/bin/bash
# Modified by T. Jameson Little.
# Run pub.dart on the Dart VM. This script assumes the Dart SDK's directory
# structure.

# Hard-coding this path is ugly, but it's necessary in order to place this in
# /usr/bin. The script assumes we're calling it from within the dart-sdk folder,
# so we have to hack it.
BIN_DIR="/opt/dart-sdk/bin"
export DART_SDK="$(cd "${BIN_DIR%/*}" ; pwd -P)"

exec "$BIN_DIR"/dart "$DART_SDK"/util/pub/pub.dart $@
