pre_install() {
  [ -f /etc/xdg/menus/arch-applications.menu ] && patch /etc/xdg/menus/arch-applications.menu /etc/xdg/menus/arch-applications.menu.patch && echo "etc/xdg/menus/arch-applications.menu patched"
}

pre_remove() {
  [ -f /etc/xdg/menus/arch-applications.menu ] && patch /etc/xdg/menus/arch-applications.menu /etc/xdg/menus/revoke-arch-applications.menu.patch &&  echo "etc/xdg/menus/arch-applications.menu revoked"
}