#! /bin/sh -e
########################################################
# This script generates an iPXE entry on grub.cfg      #
# if ipxe is installed on the system.                  #
########################################################

prefix="/usr"
exec_prefix="${prefix}"

datarootdir="/usr/share"
datadir="${datarootdir}"

. "${datadir}/grub/grub-mkconfig_lib"

IPXE_IMAGE="/boot/ipxe/ipxe.lkrn"
CLASS="--class ipxe --class gnu --class tool"

if [ -e $IPXE_IMAGE ] && is_path_readable_by_grub $IPXE_IMAGE; then
  # image exists, create menu entry
  echo "Found iPXE image: ${IPXE_IMAGE}" >&2
  cat << EOF
menuentry "iPXE - Open Source Boot Firmware" ${CLASS} {
EOF
  prepare_grub_to_access_device $(${grub_probe} --target=device ${IPXE_IMAGE}) | sed -e "s/^/  /"
  cat << EOF
  linux16 (\$root)$(make_system_path_relative_to_its_root ${IPXE_IMAGE})
}
EOF
fi
