post_install() {
  getent group s-blogspam &>/dev/null || groupadd s-blogspam
  getent passwd s-blogspam &>/dev/null || useradd -g s-blogspam -d /var/lib/blogspam -s /bin/false s-blogspam
  passwd -l s-blogspam &>/dev/null
  install -d -o s-blogspam -g s-blogspam /var/lib/blogspam
}

pre_remove() {
  getent passwd s-blogspam &>/dev/null && userdel s-blogspam >/dev/null
  getent group s-blogspam &>/dev/null && groupdel s-blogspam >/dev/null
  return 0
}
