post_install() {
  echo "You might want to install a dictionary along with Zhudi"
  echo "You can download the CFDICT at: http://www.chine-informations.com/chinois/open/CFDICT/cfdict.zip"
  echo "Or you can download the CEDICT at: http://www.mdbg.net/chindict/export/cedict/cedict_1_0_ts_utf-8_mdbg.zip"
  echo "After having downloaded a dictionary, place it in ~/.zhudi and rename it to "dict.u8". You can now launch:"
  echo "zhudi-split"
  echo "You will now be able to enjoy zhudi by simply launching it:"
  echo "zhudi"
}
