#Automatically generated by pip2arch on 2012-06-20

pkgname=motmot.wxvideo
pkgver=0.5.6
pkgrel=1
pkgdesc="wx viewer of image sequences"
url="http://code.astraw.com/projects/motmot"
depends=('python2' )
makedepends=('python2-distribute' )
license=('BSD')
arch=('any')
source=('http://pypi.python.org/packages/source/m/motmot.wxvideo/motmot.wxvideo-0.5.6.zip')
md5sums=('23aa5122ed710b0f79dbf24088c74000')

build() {
    cd $srcdir/motmot.wxvideo-0.5.6
    python2 setup.py build
}

package() {
    cd $srcdir/motmot.wxvideo-0.5.6
    python2 setup.py install --root="$pkgdir" --optimize=1 
}
