post_install() {
  if [ ! "`grep ^_smtpd /etc/group`" ]; then
    echo "adding new group: _smtp"
    /usr/sbin/groupadd -g 87 _smtp
  fi
                    
  if [ ! "`grep ^_smtp /etc/passwd`" ]; then
    echo "adding new user: _smtp"
    /usr/sbin/useradd -g _smtp -u 90 -d /var/empty -s /bin/false -c 'SMTP Protocol' _smtp
  fi
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  /bin/true
}

post_remove() {
  /bin/true
}

# vim: ts=2 sw=2 et ft=sh
