#!/bin/bash

CONF=/etc/conf.d/opensmtpd
RUNDIR=/var/run/opensmtpd

. /etc/rc.conf
. /etc/rc.d/functions

[ -f $CONF ] && . $CONF

PID=`pidof -o %PPID /usr/sbin/smtpd`
case "$1" in
  start)
    stat_busy "Starting OpenNTPD"
    [ -d $RUNDIR ] || mkdir $RUNDIR
    [ -z "$PID" ] && /usr/sbin/smtpd $PARAMS
    if [ $? -gt 0 ]; then
      stat_fail
    else
      PID=`pidof -o %PPID /usr/sbin/smtpd`
      echo $PID >/var/run/opensmtpd.pid
      add_daemon opensmtpd
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping OpenNTPD"
    [ ! -z "$PID" ]  && kill $PID &>/dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon opensmtpd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
