# Generated by gem2arch

_gemname=metasploit_data_models
pkgname=ruby-$_gemname
pkgver=0.16.6
pkgrel=1
pkgdesc="Database code for MSF and Metasploit Pro"
arch=('any')
url="https://rubygems.org/gems/metasploit_data_models"
license=('')
depends=('ruby' 'ruby-activerecord>=3.2.13' 'ruby-activesupport>=0' 'ruby-pg>=0')
makedepends=('rubygems')
source=(http://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
md5sums=('e0fd6c9ca3d4c14ce8265af5161e79ec')
sha1sums=('1712aed85f1e58fb589736bfa99d9ae142af0f51')

package() {
  cd "$srcdir"
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
}
