# arg 1:  the new package version
post_install() {
cat << EOF
Note:
==> Please, read the README.txt file in /usr/share/doc/intensityengine/ first.
==> Start scripts are in /usr/share/games/intensityengine/
==> 
==> You should have an "Intensity (client)" entry in your menu.
==> If not, just run:
==> /usr/bin/intensity
EOF
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $1
}

op=$1
shift
$op $*