# Maintainer:  Philipp Ittershagen <p.ittershagen at googlemail dot com>
# Contributor: Alec Ari <neotheuser@ymail.com>

pkgname=rtai-kernel
pkgver=2.6.35.7
pkgrel=4
patch=hal-linux-2.6.35.7-x86-2.8-01.patch
patch2=fix-gcc-4.6-errors.patch
pkgdesc="Kernel 2.6.35.7 with RTAI"
arch=('i686' 'x86_64')
license=('GPL2')
groups=('base')
url="https://www.rtai.org"
depends=('gcc' 'make' 'patch')
makedepends=('ncurses' 'dialog')
install=$pkgname.install
options=(!strip)
source=(http://www.kernel.org/pub/linux/kernel/v2.6/linux-$pkgver.tar.bz2
        $patch $patch2 $pkgname.config ${pkgname}64.config $pkgname.preset)

md5sums=('f741879bcd3a5366a1bbe0ad5cdb7935'
         '89dbb514372ccf6aaceac7eadebbab6c'
         '14524672f01da65ef28946cf7778d9c2'
         '7eaad37fbb45bd6aafe997a9a9c4bf7a'
         '6f90be9662675436bbb3cf46bc6b0ece'
         'dd6f60692cbd3e8787ab8bfe8adefbec')

build() {
  KARCH=x86

  cd $srcdir/linux-$pkgver

  # Apply RTAI patch
  patch -Np1 < ../$patch || return 1

	# Apply gcc fixes
  patch -Np1 < ../$patch2 || return 1

  #Move configs (Arch specific)
  if [ "$CARCH" = "x86_64" ]; then
    mv -vi ../${pkgname}64.config .config
  else
    mv -vi ../${pkgname}.config .config
  fi

  #DO NOT uncomment the make menuconfig line unless you know what you are doing
  #By editing the config, DO NOT expect support
  #make menuconfig

  #Build and install kernel with modules
  #Make with X number of cores
	make -j$(cat /proc/cpuinfo | grep processor | wc -l) all || return 1
  make INSTALL_MOD_PATH=$pkgdir modules_install || return 1
  mkdir $pkgdir/boot
  cp arch/$KARCH/boot/bzImage $pkgdir/boot/vmlinuz-rtai

	# Remove firmware files, as they are provided by another package
	rm -rf $pkgdir/lib/firmware

  #Install preset file for mkinitcpio
  mkdir -p $pkgdir/etc/mkinitcpio.d

  install -m644 -D $srcdir/${pkgname}.preset $pkgdir/etc/mkinitcpio.d/${pkgname}.preset || return 1
  #Install kver file for mkinitcpio
  echo -e "# DO NOT EDIT THIS FILE AT ALL\nALL_kver='$pkgver-RTAI'" > $pkgdir/etc/mkinitcpio.d/${pkgname}.kver

  #Install kernel source and config for RTAI userspace
  mkdir -p $pkgdir/usr/src
  cp -PR $srcdir/linux-$pkgver $pkgdir/usr/src/
}
