custom=rtai-kernel
KERNEL_VERSION=2.6.35.7-RTAI

post_install () {
  echo "Running depmod..."
  depmod -v $KERNEL_VERSION > /dev/null 2>&1
  #Make the initial ramdisk
  echo "Creating the initrd..."
  /sbin/mkinitcpio -p $custom
  echo "You must now edit menu.lst or grub.cfg and add vmlinuz-rtai and rtai-initrd.img to the file"
  echo "For a significant improvement in latency..."
  echo "Please add the following on the kernel command line within the GRUB file:"
  echo "isolcpus=1"
}
