pre_install() {
/bin/true
}

post_install() {
cat << EOF
This is a system wide installation of Rapid Euphoria language.
Check /etc/profile.d/euphoria.sh for setting the correct environment or simply reboot.
Please read the docs in /opt/euphoria/html.
EOF
}


# arg 1:the new package version
# arg 2:the old package version
pre_upgrade() {
#
#do pre-upgrade stuff here
#
/bin/true
}

post_upgrade() {
/bin/true
}

pre_remove() {
/bin/true
}

post_remove() {
/bin/true
}

op=$1
shift
$op $*

