post_install() {
	for src in /etc/hadoop/default/*; do
		dest=$( echo $src | sed 's|^/etc/hadoop/default/|/etc/hadoop/|' )
		if [ -f $dest ]; then
			diff $src $dest > /dev/null 2>/dev/null
			ret=$?
			
			if [ $ret -ne 0 ]; then
				echo ">>> Not updating $dest - it exists and is different than $src. Please check if it needs to be modified."
			fi
		else
			echo ">>> Copying $src to $dest"
			cp $src $dest
		fi
	 done
}

post_upgrade() {
	post_install
}
