#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/profile.d/hadoop.sh

case "$1" in
 start)
   stat_busy "Starting hadoop all"
   /usr/lib/hadoop/bin/start-all.sh
   if [ $? = 0 ]; then
     add_daemon hadoop
     stat_done
   else
     stat_fail
     exit 1
   fi
   ;;
 stop)
   stat_busy "Stopping hadoop all"
   /usr/lib/hadoop/bin/stop-all.sh
   if [ $? = 0 ]; then
     rm_daemon hadoop-all
     stat_done
   else
     stat_fail
     exit 1
   fi
   ;;
 restart)
   $0 stop
   sleep 1
   $0 start
   ;;
 *)
   echo "usage: $0 {start|stop|restart}"  
esac
