post_install() {
  install-info /usr/share/info/recode.info /usr/share/info/dir	       
  /bin/true
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  install-info /usr/share/info/recode.info.gz /usr/share/info/dir
  /bin/true
}

# arg 1:  the old package version
pre_remove() {
  install-info --delete /usr/share/info/recode.info.gz /usr/share/info/dir
  /bin/true
}

op=$1
shift
[ "$(type -t "$op")" = "function" ] && $op "$@"
