#!/usr/bin/env bash
#  Proto-script to setup environment to use CERN /afs binary releases
#
#  First version: 12 April 2002, J.A.
#  Modified:      24 May   2002, J.A.
#  Modified:      16 June  2003, I.M. 
#  Modified:      18 March 2004, I.M. 
#  Version 0.4.0
#

# Edits by Yngve Inntjore Levinsen to use this as g4env for Arch Linux

printusage() {
	echo -e "Usage: g4env <command>\n"
}
printenv() {
	env | grep G4
	env | grep CLHEP
	env | grep XERCES
}
if (( $# == 0 )) 
then
	echo -e "\nERROR: You need to specify a command\n"
	printusage
	exit 1
elif [ $1 == "-h" ] || [ $1 == "--help" ] 
then
	printusage
	exit 0
fi
# Configuration parameters, for release
#
g4version="%%G4VERSION%%"

# Configuration parameters, for system and compiler
#


   export G4SYSTEM=Linux-g++
   export G4INSTALL=/usr/share/Geant4-${g4version}
   export G4INCLUDE=/usr/include/geant4
   export G4DATA=/usr/share/geant4/data
   export G4LIB=/usr/lib/geant4-$g4version
   export CLHEP_BASE_DIR=/usr
   export XERCESCROOT=/usr

   export G4ABLADATA=$G4INSTALL/data/G4ABLA
   export G4LEDATA=$G4INSTALL/data/G4EMLOW
   export G4NEUTRONHPDATA=$G4INSTALL/data/G4NDL
   export G4LEVELGAMMADATA=$G4INSTALL/data/PhotonEvaporation
   export G4RADIOACTIVEDATA=$G4INSTALL/data/RadioactiveDecay
   export G4ELASTICDATA=$G4INSTALL/data/G4ELASTIC
   export G4REALSURFACEDATA=$G4INSTALL/data/RealSurface

   # Geant 4 interface, visualisation and other variables
   export G4UI_USE_TERMINAL=1
   export G4UI_USE_TCSH=1
   export G4UI_USE_GAG=1
   export G4UI_USE_XAW=1
   export G4UI_USE_XM=1
   #
   export G4VIS_USE_DAWN=1
   export G4VIS_USE_DAWNFILE=1
   export G4VIS_USE_OPENGLX=1
   export G4VIS_USE_OPENGLXM=1
   export G4VIS_USE_RAYTRACER=1
   export G4VIS_USE_RAYTRACERX=1
   export G4VIS_USE_VRML=1
   export G4VIS_USE_VRMLFILE=1
   #
   # Geant 4 build variables
   export G4VIS_BUILD_VRML_DRIVER=1
   export G4UI_BUILD_XAW_SESSION=1
   export G4UI_BUILD_XM_SESSION=1
   export G4LIB_BUILD_G3TOG4=1
   export G4VIS_BUILD_OPENGLX_DRIVER=1
   export G4VIS_BUILD_RAYTRACERX_DRIVER=1
   export G4VIS_BUILD_OPENGLXM_DRIVER=1
   export G4UI_BUILD_TERMINAL_SESSION=1
   export G4UI_BUILD_GAG_SESSION=1
   export G4VIS_BUILD_RAYTRACER_DRIVER=1
   export G4VIS_BUILD_DAWNFILE_DRIVER=1
   export G4VIS_BUILD_DAWN_DRIVER=1
   export G4VIS_BUILD_VRMLFILE_DRIVER=1
   export G4LIB_BUILD_GDML=1

   export G4LIB_USE_G3TOG4=1

   # The following is used to store your executables 
   #            (in subdirectories, one per system)

   if [ $LD_LIBRARY_PATH ] 
   then
      LD_LIBRARY_PATH=${G4LIB}:${CLHEP_BASE_DIR}/lib:${XERCESCROOT}/lib:${LD_LIBRARY_PATH}
   else
      LD_LIBRARY_PATH=${G4LIB}:${CLHEP_BASE_DIR}/lib:${XERCESCROOT}/lib
   fi
   export LD_LIBRARY_PATH
   
   if [ $G4WORKDIR ]
   then
     echo "G4WORKDIR already set"   
   else
     echo "Setting G4WORKDIR"
     export G4WORKDIR=`pwd`
   fi

   # The following is used to store your executables 
   #            (in subdirectories, one per system)
   if [ $G4BIN ]
   then
     echo "G4BIN already set"
   else
    export G4BIN=$G4WORKDIR/bin
   fi
   if [ ! $G4BINDIR ]
   then
       export G4BINDIR=$G4BIN
   fi
if [ $1 == "--env" ]
then
	printenv
	exit 0
else
	$@
fi

