#!/bin/sh

_varname='G4LEVELGAMMADATA'
_packagename='geant4-levelgammadata'
_foldername='PhotonEvaporation'
_dataversion=2.2

post_install() {

echo "export ${_varname}=/usr/share/${_packagename}/${_foldername}${_dataversion}" >> /etc/profile.d/geant4.sh
echo "setenv ${_varname} /usr/share/${_packagename}/${_foldername}${_dataversion}" >> /etc/profile.d/geant4.csh

}

post_remove() {

sed -i "/${_varname}/d" /etc/profile.d/geant4.sh
sed -i "/${_varname}/d" /etc/profile.d/geant4.csh

}