#!/bin/sh

_varname='G4LEDATA'
_packagename='geant4-ledata'
_foldername='G4EMLOW'
_dataversion=6.23

post_install() {

echo "export ${_varname}=/usr/share/${_packagename}/${_foldername}${_dataversion}" >> /etc/profile.d/geant4.sh
echo "setenv ${_varname} /usr/share/${_packagename}/${_foldername}${_dataversion}" >> /etc/profile.d/geant4.csh

}

post_remove() {

sed -i "/${_varname}/d" /etc/profile.d/geant4.sh
sed -i "/${_varname}/d" /etc/profile.d/geant4.csh

}

