post_install() {
echo ">>"
echo ">> To have veetle working:"
echo ">> cp -r /usr/share/veetle/vlc /home/_YOURUSER_/.veetle_vlc"
echo ">>"
}

post_upgrade() {
echo ">>"
echo ">> To have veetle working:"
echo ">> rm -r /home/_YOURUSER:/.veetle_vlc"
echo ">> cp -r /usr/share/veetle/vlc /home/_YOURUSER_/.veetle_vlc"
echo ">>"
}

post_remove() {
echo ">>"
echo ">> To completely remove the package:"
echo ">> rm -r /home/_YOURUSER_/.veetle_vlc"
echo ">>"
}
