post_install() {
  update-desktop-database -q
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  echo 
  echo "### NOTE ###"
  echo
  echo "Tool presets are located in /usr/share/gimp/2.0/tool-options."
  echo "Copy the directory to ~/.gimp-2.6 if you want to use them."
  echo
  echo "    cp -rf /usr/share/gimp/2.0/tool-options ~/.gimp-2.6"
  echo
}

post_upgrade() {
  post_install
}

post_remove() {
  post_install
}
