post_install() {
	xdg-icon-resource forceupdate --theme hicolor &> /dev/null
	cat << _EOF

  If you want to run the Transmission daemon at boot,
  add transmissiond to the DAEMONS array in /etc/rc.conf.
  You have to set the user in /etc/conf.d/transmissiond.

_EOF
}

post_upgrade() {
		xdg-icon-resource forceupdate --theme hicolor &> /dev/null
}

post_remove() {
	xdg-icon-resource forceupdate --theme hicolor &> /dev/null
}
