#Automatically generated by pip2arch on 2012-02-05

pkgname=python-plac
pkgver=0.9.1
pkgrel=1
pkgdesc="The smartest command line arguments parser in the world"
url="http://code.google.com/p/plac/"
depends=('python' )
makedepends=('python-distribute' )
license=('CUSTOM')
arch=('any')
source=('http://pypi.python.org/packages/source/p/plac/plac-0.9.0.tar.gz')
md5sums=('e24a5e5e05893cb33cbc03f6a7a779b9')

build() {
    cd $srcdir/plac-0.9.0
    python setup.py build
}

package() {
    cd $srcdir/plac-0.9.0
    python setup.py install --root="$pkgdir" --optimize=1 
}
