
post_install() {
cat << _EOF

==> byobu installation notes:
---------------------------------------------------
    The tmux backend is now stable enough to use it by
    default. See /etc/byobu/backend if you want to keep
    using screen.

    As usual, wipe out your byobu config ("~/.byobu" or
    "~/.config/byobu") if you run into trouble. 
_EOF
}

post_upgrade() {
    post_install
}

op=$1
shift
$op $*

