
post_install() {
cat << _EOF

==> byobu installation notes:
    -------------------------------------------------
    /!\ Warning: the format of ~/.config/byobu/status
        has changed a lot. If you encounter difficulties,
        don't hesitate to delete it.

    There is a preliminary support of tmux (instead of
    screen) as a backend, see /etc/byobu/backend.
    Use it at your own risk.
_EOF

}

post_upgrade() {
        post_install
}

op=$1
shift
$op $*
