post_install() {
    echo "Before starting gollum, be sure to create the directory and run git
    init. To use the provided systemd unit file, change the GitDir file path to
    point to your repo. See the homepage for more configuration options. The
    service file can be used in either --user or for the whole system."
}

post_upgrade() {
    echo "Before starting gollum, be sure to create the directory and run git
    init."
}
