post_install() {
  _depmod
}

post_upgrade() {
  [ "$(vercmp $2 2.6.30-3)" -lt 0 ] && _kmsmsg
  _depmod
}

_depmod() {
  # installed by the linux-eee-ck package, defines KERNEL_VERSION
  . usr/share/linux-eee-ck/currver
  depmod -a $KERNEL_VERSION
}

_kmsmsg() {
  echo "NOTE:"
  echo "   KMS (kernel mode-setting) is now enabled by default in this kernel."
  echo "   For more information, see http://www.toofishes.net/blog/kms-kernel/"
}
