# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: tuftedocelot <tuftedocelot@fastmail.fm>

_gemname=gollum-grit_adapter
pkgname=ruby-$_gemname
pkgver=1.0.0
pkgrel=1
pkgdesc='Adapter for Gollum to use Grit at the backend.'
arch=(any)
url='https://github.com/gollum/grit_adapter'
license=(MIT)
depends=(ruby ruby-gitlab-grit)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('98b4cac14299e436bfbf8930abfc1aaa0c6a28f8')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
