#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

NAME="Apple II Boot Daemon"
ARGS=
DEPENDS=atalkd
DAEMON=`basename "$0"`

[ -r /etc/conf.d/$DAEMON ] && . /etc/conf.d/$DAEMON

PID=`get_pid $DAEMON`

case "$1" in
 start)
   stat_busy "Starting $NAME"
   [ `get_pid $DEPENDS` ] && [ -z "$PID" ] && $DAEMON $ARGS &>/dev/null
   if [ $? = 0 ]; then
     stat_done
   else
     stat_fail
     if [ ! `get_pid $DEPENDS` ];then echo "Error: \"$DAEMON\" refusing to start, dependency \"$DEPENDS\" not met" >&2;fi
     exit 1
   fi
   ;;
 stop)
   stat_busy "Stopping $NAME"
   [ -n "$PID" ] && kill $PID &>/dev/null
   if [ $? = 0 ]; then
     stat_done
   else
     stat_fail
     exit 1
   fi
   ;;
 restart)
   $0 stop
   sleep 1
   $0 start
   ;;
 *)
   echo "usage: $0 {start|stop|restart}"  
esac