[ "${ICECATDIR}" = "" ] && ICECATDIR="/usr/lib/icecat-3.0.1-g1"
post_install () {
	echo " >>> consider using /usr/bin/icecat-launcher.sh"
	echo " >>> to launch IceCat"
	echo " >>> source /etc/profile.d/icecat.sh"
	source /etc/profile.d/icecat.sh ##this doesn't work, thus comment above
	update-desktop-database -q
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
	post_install $1
}

post_remove() {
	update-desktop-database -q
}

op=$1
shift

$op $*
