gtiles_schema=/etc/gconf/schemas/gtiles.schemas

post_install() {
    GCONF_CONFIG_SOURCE=$(gconftool-2 --get-default-source) \
        gconftool-2 --makefile-install-rule ${gtiles_schema} > /dev/null 2>&1
    pkill -HUP gconfd-2 > /dev/null 2>&1
}

post_upgrade() {
    post_install $*
}

pre_remove() {
    GCONF_CONFIG_SOURCE=$(gconftool-2 --get-default-source) \
        gconftool-2 --makefile-uninstall-rule ${gtiles_schema} > /dev/null 2>&1
    pkill -HUP gconfd-2 > /dev/null 2>&1
}
