post_install() {
    echo -n "Updating vim help tags..."
    /usr/bin/vim --noplugins -u NONE -U NONE \
        --cmd ":helptags /usr/share/vim/doc" --cmd ":q" > /dev/null 2>&1
    echo "done."

    echo "add in ~/.vimrc"
    echo "autocmd FileType python set omnifunc=pythoncomplete#Complete"
    echo "set runtimepath=~/.vim,$VIM/vimfiles,$VIMRUNTIME"
}

post_upgrade() {
  post_install $1
}

post_remove() {
  post_install
}

op=$1
shift

$op $*
