post_install() {
	echo "==> Please copy the config files in /usr/share/higan to ~/.config/higan"
	echo "==> Higan needs these files to run correctly."
	echo "==> Ananke may need a config directory in ~/.config/ananke"
}

post_upgrade() {
	echo "==> Please copy the config files in /usr/share/higan to ~/.config/higan"
	echo "==> Higan needs these files to run correctly."
	echo "==> Ananke may need a config directory in ~/.config/ananke"
}
