post_install() {
  cat << EOF
------------------------------------------------------------------------
  Read /opt/shadowsocks-nodejs/README.md for configuration.
  Use 'systemctl start shadowsocks-nodejs.service' to run as a service.
  You may also invoke 'sslocal -c /path/to/config.json'.
  Happy bypassing firewalls and may the odds be ever in your favor.
------------------------------------------------------------------------
EOF
}
