# This is a default template for a post-install scriptlet.
# Uncomment only required functions and remove any functions
# you don't need (and this header).

pre_install() {
  echo Installing $1
}

post_install() {
  echo Finished installing $1
}

pre_upgrade() {
  echo Upgrading $2 to $1
}

post_upgrade() {
  echo Finished upgrading $2 to $1
}

pre_remove() {
  echo Removing $1
}

post_remove() {
  echo Finished removing $1
}

# vim:set ts=2 sw=2 et: