## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
  pkgver=${2%-*}
  if [ x$pkgver == x"1.0.0" ]; then
    /bin/cat << EOF
Veracity 1.0 repositories need to be reindexed. When Veracity notices,
it will tell you:
"You need to 'vv reindex'."

If you want to be proactive, you can 'vv reindex --repo my_repo' before
you see this message.
EOF
  fi
}
# vim:set ts=2 sw=2 et:
