pkgname=metacity

post_install() {
  usr/sbin/gconfpkg --install ${pkgname}
 echo "	    **optional: use gconf-editor to configure metacity!"
 echo "	    **run metacity-ubuntu first, run gconf-editor"
 echo "	    **go to: "/apps/metacity/" "
 echo "	    **in "/apps/metacity" edit some options inside in some folders to make metacity perfect for you ;) "
}

pre_upgrade() {
  pre_remove $1
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  usr/sbin/gconfpkg --uninstall ${pkgname}
}
