
post_install() {
  echo "rewrite the network config in /etc/rc.conf"
  echo "make a backup of the old lines"
  echo "e.g. "
  echo "eth0=\"addr add 192.168.1.2 dev eth0\""
  echo "INTERFACES=(eth0)"
  
  echo "gateway=\"default via 192.168.1.1 dev eth0\""
  echo "ROUTES=(gateway)"
  
  
  echo "and replace network with network-ip in DAEMONS in /etc/rc.conf"
}

post_remove() {
  echo "use the original config syntax"
  echo "and replace network-ip with network in DAEMONS in /etc/rc.conf"
}
