post_install() {
cat << EOF
==> The license key is not set.
==> Go to http://salilab.org/modeller/registration.html to get a license key,
==> and then set the 'license' variable to it in the file
==> /usr/share/modeller/modlib/modeller/config.py
==> example: license = 'XXXX'

Also note that in order to run the examples you will need to copy them in
a writable directory, for example ~/.modeller/
EOF
}

post_upgrade() {
 post_install $1
}
