#!/bin/bash
post_install()
{
  update-mime-database /usr/share/mime
  rm -f /usr/sbin/enigma-dev /opt/enigma/lateralgm.jar
  ln -s /usr/sbin/lateralgm /usr/sbin/enigma-dev
  ln -s /opt/enigma/lgm*.jar /opt/enigma/lateralgm.jar
}

pre_upgrade()
{
  rm -rf /opt/enigma/ENIGMAsystem/SHELL/Preprocessor_Environment_Editable /opt/enigma/definitions.h
  find /opt/enigma -type f -name "*.a" -exec rm {} \;
  find /opt/enigma -depth -type d -exec rmdir {} --ignore-fail-on-non-empty \;
}

post_upgrade()
{
  update-mime-database /usr/share/mime
  rm -f /opt/enigma/lateralgm.jar
  ln -s /opt/enigma/lgm*.jar /opt/enigma/lateralgm.jar
}

post_remove()
{
  rm -rf /usr/sbin/enigma-dev /opt/enigma/lateralgm.jar /opt/enigma/ENIGMAsystem/SHELL/Preprocessor_Environment_Editable /opt/enigma/definitions.h
  find /opt/enigma -type f -name "*.a" -exec rm {} \;
  find /opt/enigma -depth -type d -exec rmdir {} --ignore-fail-on-non-empty \;
}
