#!/bin/bash
if [[ "$2" == "i386" || "$2" == "i486" || "$2" == "i586" || "$2" == "i686" ]]; then
  sed -i 's/g++/g++ -m32 -mtune=generic/' $1
elif [[ "$2" == "amd64" || "$2" == "x86_64" ]]; then
  sed -i 's/g++/g++ -m64 -mtune=generic/' $1
elif [[ -n $2 ]]; then
  echo "Unable to compile for the $2 architecture."
  return 1
fi