#!/bin/sh
psp_prefix=/usr/psp

PATH=${mingw32_prefix}/bin:$PATH cmake \
    -DCMAKE_INSTALL_PREFIX:PATH=${psp_prefix} \
    -DCMAKE_INSTALL_LIBDIR:PATH=${psp_prefix}/lib \
    -DINCLUDE_INSTALL_DIR:PATH=${psp_prefix}/include \
    -DLIB_INSTALL_DIR:PATH=${psp_prefix}/lib \
    -DSYSCONF_INSTALL_DIR:PATH=${psp_prefix}/etc \
    -DSHARE_INSTALL_DIR:PATH=${psp_prefix}/share \
    -DBUILD_SHARED_LIBS:BOOL=ON \
    -DCMAKE_TOOLCHAIN_FILE=/usr/share/mingw/toolchain-psp.cmake \
    "$@"
    
