post_remove() {
		if [ -L  /opt/olsc/AusweisApp/libpcsclite.so ]; then
    		rm -f /opt/olsc/AusweisApp/libpcsclite.so
		fi

		if [ -L /opt/olsc/AusweisApp/PdfSecureAPI.dll  ]; then
    		rm -f /opt/olsc/AusweisApp/PdfSecureAPI.dll
		fi

		if [ -L /opt/olsc/AusweisApp/PdfValidatorAPI.dll ]; then
    		rm -f /opt/olsc/AusweisApp/PdfValidatorAPI.dll
		fi

		if [ -L /opt/olsc/AusweisApp/PdfViewerAPI.dll ]; then
    		rm -f /opt/olsc/AusweisApp/PdfViewerAPI.dll
		fi

		if [ -L /opt/olsc/AusweisApp/PDFParser.dll ]; then
    		rm -f /opt/olsc/AusweisApp/PDFParser.dll
		fi

		if [ -L /opt/olsc/AusweisApp/libPdfSecureAPI.so ]; then
    		rm -f /opt/olsc/AusweisApp/libPdfSecureAPI.so
		fi

		if [ -L /opt/olsc/AusweisApp/libPdfValidatorAPI.so ]; then
    		rm -f /opt/olsc/AusweisApp/libPdfValidatorAPI.so
		fi

		if [ -L /opt/olsc/AusweisApp/libPdfViewerAPI.so ]; then
    		rm -f /opt/olsc/AusweisApp/libPdfViewerAPI.so
		fi

		if [ -L /opt/olsc/AusweisApp/libPDFParser.so ]; then
   		rm -f /opt/olsc/AusweisApp/libPDFParser.so
		fi


		if [ -L /opt/olsc/AusweisApp/PdfSecureAPI.ols ]; then
    		rm -f /opt/olsc/AusweisApp/PdfSecureAPI.ols
		fi

		if [ -L /opt/olsc/AusweisApp/PdfValidatorAPI.ols ]; then
    		rm -f /opt/olsc/AusweisApp/PdfValidatorAPI.ols
		fi

		if [ -L /opt/olsc/AusweisApp/PdfViewerAPI.ols ]; then
    		rm -f /opt/olsc/AusweisApp/PdfViewerAPI.ols
		fi

		if [ -L /opt/olsc/AusweisApp/PDFParser.ols ]; then
   		rm -f /opt/olsc/AusweisApp/PDFParser.ols
		fi
	
		if [ -d /opt/olsc/AusweisApp/jvm ]; then
    		rm -rf /opt/olsc/AusweisApp/jvm
		fi

		if [ -d /opt/olsc/AusweisApp/ext ] ; then
   		rm -rf /opt/olsc/AusweisApp/ext
		fi

		if [ -d /usr/share/applications/signcubes.desktop ] ; then
   		rm -f /usr/share/applications/signcubes.desktop
		fi

		if [ -d /usr/share/menu/signcubesv3 ] ; then
    		rm -f /usr/share/menu/signcubesv3
		fi

		if [ -L /usr/share/pixmaps/olsc.png ] ; then
    		rm -f /usr/share/pixmaps/olsc.png
		fi

# delete plug-ins links
		if [ -L /usr/lib/firefox-addons/plugins/libeCardClient30-plugin.so ] ; then
    		rm /usr/lib/firefox-addons/plugins/libeCardClient30-plugin.so
		fi
		if [ -L /usr/lib/firefox-addons/plugins/libsiqeCardClient-plugin.so ] ; then
   		rm /usr/lib/firefox-addons/plugins/libsiqeCardClient-plugin.so
		fi

		if [ -L /usr/lib/firefox-addons/plugins/libeCardClient35-plugin.so ] ; then
   		rm /usr/lib/firefox-addons/plugins/libeCardClient35-plugin.so
		fi

		if [ -L /usr/lib/mozilla/plugins/libsiqeCardClient-plugin.so ] ; then
   		rm /usr/lib/mozilla/plugins/libsiqeCardClient-plugin.so
		fi

		if [ -L /usr/lib/xulrunner-1.9/plugins/libsiqeCardClient-plugin.so ] ; then
   		rm /usr/lib/xulrunner-1.9/plugins/libsiqeCardClient-plugin.so
		fi


		if [ -L /usr/lib/firefox-addons/extensions/{4F3D26C8-9907-48ff-BC74-B8C572D317BF} ] ; then
   		rm /usr/lib/firefox-addons/extensions/{4F3D26C8-9907-48ff-BC74-B8C572D317BF}
		fi

		if [ -L /usr/lib/mozilla/extensions/{4F3D26C8-9907-48ff-BC74-B8C572D317BF} ] ; then
   		rm /usr/lib/mozilla/extensions/{4F3D26C8-9907-48ff-BC74-B8C572D317BF}
		fi

		if [ -L /usr/lib/xulrunner-1.9/extensions/{4F3D26C8-9907-48ff-BC74-B8C572D317BF} ] ; then
   		rm /usr/lib/xulrunner-1.9/extensions/{4F3D26C8-9907-48ff-BC74-B8C572D317BF} 
		fi

		if [ -L /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{4F3D26C8-9907-48ff-BC74-B8C572D317BF} ] ; then
   		rm /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{4F3D26C8-9907-48ff-BC74-B8C572D317BF}
		fi
}

post_install() {
	########################################
	#linking plug-ins
	########################################

	# justify the firefox version to a 2 digit integer
	# so that the version match can be executed 
	# point of interest is major and minor versions
	#FFVERS=`firefox -v | awk {'print $3'} | sed -e 's/\([0-9]\)\.\([0-9]\).*/\1\2/'`

	      #Plugins
	###      if [ -e /opt/olsc/AusweisApp/libsiqeCardClient30.so ] ; then
	###	  if [ -e /usr/lib/firefox-addons/plugins ] ; then
	###              if [ ! -L /usr/lib/firefox-addons/plugins/libsiqeCardClient-plugin.so ] ; then
	###                ln -s /opt/olsc/AusweisApp/libsiqeCardClient30.so /usr/lib/firefox-addons/plugins/libsiqeCardClient-plugin.so
	###              fi
	###          fi
	 ###         # debian stuff - iceweasel
	###          if [ -e /usr/lib/mozilla/plugins ] ; then
	###                if [ ! -L /usr/lib/mozilla/plugins/libsiqeCardClient-plugin.so ] ; then
	###          	  ln -s /opt/olsc/AusweisApp/libsiqeCardClient30.so /usr/lib/mozilla/plugins/libsiqeCardClient-plugin.so
	###                fi
	###              else
	###              if [ -e /usr/lib/xulrunner-1.9/plugins ] ; then
	###                if [ ! -L /usr/lib/xulrunner-1.9/plugins/libsiqeCardClient-plugin.so ] ; then
	###			ln -s /opt/olsc/AusweisApp/libsiqeCardClient30.so /usr/lib/xulrunner-1.9/plugins/libsiqeCardClient-plugin.so
	###                fi
	###              fi 
	###          fi
	###        fi

	if [ ! -e /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384} ] ; then
	   mkdir -p /usr/share/mozilla/extensions/\{ec8030f7-c20a-464f-9b0e-13a3a9e97384\}
	fi
	# register FF extension
	     
	# for Update 1.3 to 1.4
	# cleanup the old links if they are there...
	# old plugins used to have a link to dir
	# this used to show to dir eCardClientext_FFxx_Lin32
	if [ -L /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{4F3D26C8-9907-48ff-BC74-B8C572D317BF} ] ; then
	  rm /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{4F3D26C8-9907-48ff-BC74-B8C572D317BF}
	fi


	ln -s /opt/olsc/AusweisApp/mozilla/eCardClientExt_FFxx_Lin /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{4F3D26C8-9907-48ff-BC74-B8C572D317BF}

	#            if [ $FFVERS -ge 40 ] ; then
	#             # ff 4.0.x   
	#                ln -s /opt/olsc/AusweisApp/mozilla/eCardClientExt_FF40_Lin32 /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{4F3D26C8-9907-48ff-BC74-B8C572D317BF}
	#		else
	#            # ff 3.x
	#                ln -s /opt/olsc/AusweisApp/mozilla/eCardClientExt_FF3x_Lin32 /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{4F3D26C8-9907-48ff-BC74-B8C572D317BF}
	#	    fi	

	if [ ! -L /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{4F0963A3-1658-4fde-9585-23A25CC288BF} ] ; then
	     ln -s /opt/olsc/AusweisApp/mozilla/eCardClientPIn_FFxx_Lin /usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{4F0963A3-1658-4fde-9585-23A25CC288BF}
	fi

	########################################
	#linking pcsclite
	########################################

	if [ ! -L /opt/olsc/AusweisApp/libpcsclite.so ] ; then
	if [ -e  /opt/olsc/pcsc/lib/libpcsclite.so.1.0.0 ] ; then
	   ln -s /opt/olsc/pcsc/lib/libpcsclite.so.1.0.0 /opt/olsc/AusweisApp/libpcsclite.so

		else

		if [ -e /lib/libpcsclite.so.1.0.0 ] ; then
			ln -s /lib/libpcsclite.so.1.0.0 /opt/olsc/AusweisApp/libpcsclite.so
		fi
		if [ -e /usr/lib/libpcsclite.so.1.0.0 ] ; then
			ln -s /usr/lib/libpcsclite.so.1.0.0 /opt/olsc/AusweisApp/libpcsclite.so
		fi
	  fi
	fi

	if [ -e /etc/orbitrc ] ; then
		echo "ORBIIOPIPv4=1" >> /etc/orbitrc
	else
		echo "ORBIIOPIPv4=1" > /etc/orbitrc
	fi
		echo "ORBLocalOnly=1" >> /etc/orbitrc
}
