infodir=usr/share/info
filelist=(manual_eqtlbma.info)

post_install() {
  [[ -x usr/bin/install-info ]] || return 0
  for file in "${filelist[@]}"; do
    install-info "$infodir/$file.gz" "$infodir/dir" 2> /dev/null
  done
  echo "Tutorial R scripts installed in /usr/share/eqtlbma"
}

post_upgrade() {
  for file in "${filelist[@]}"; do
    install-info "$infodir/$file.gz" "$infodir/dir" 2> /dev/null
  done
}

pre_remove() {
  [[ -x usr/bin/install-info ]] || return 0
  for file in "${filelist[@]}"; do
    install-info --delete "$infodir/$file.gz" "$infodir/dir" 2> /dev/null
  done
}

# vim:set ts=2 sw=2 et:
