post_upgrade() {
echo ""
echo "This version of the package makes a couple of noteworthy changes:"
echo ""
echo "- wpa_auto.conf file is moved to /etc/conf.d and renamed to \"wpa_auto\" to conform with" 
echo "Arch Linux standard location and naming of daemon configuration files."
echo ""
echo "- since wpa_supplicant package changed the location of the wpa_supplicant.conf file,"
echo "the default wpa_auto configuration file has been updated accordingly."
echo ""
}
