post_install() {
    [[ ! `grep syncthing /etc/passwd` ]] && useradd -r -U -s /bin/false -d / syncthing
    echo -e "\nStart syncthing for a given user with 'systemctl start syncthing@username' and access the web gui @ http://localhost:8080\n\nFor more information, run 'man syncthing'\n"
    systemctl --system daemon-reload
}

post_upgrade() {
    post_install
}

post_remove() {
    [[ `grep syncthing /etc/passwd` ]] && userdel syncthing
    return 0
}
