post_install() {
echo "Put this in your \$HOME/.emacs file to enable"
echo ' (load "/usr/share/emacs/site-lisp/dismal/dismal-mode-defaults")'
echo "adding info file"
install-info --entry="* dismal: (dismal). The Emacs spreadsheat mode" \
	     /usr/share/info/dismal.info /usr/share/info/dir 2> /dev/null
}

post_upgrade() {
  post_install $1
}

post_remove() {
   install-info --delete /usr/share/info/dismal.info \
   /usr/share/info/dir 2> /dev/null
}
