#!/bin/sh

set -e

INSTDIR="/usr/share/netflix-desktop";
USER_INSTDIR="${HOME}/.netflix-desktop";

EXITCODE=0;

exit_with_error() {
	echo "$1" >&2;
	exit 1;
}

# Go through the list of expected files and copy each one to our installation folder
while read desired_checksum filename permissions url; do
    found_file=0;
    filepath=${USER_INSTDIR}/$filename;
    if [ ! -f $filepath ]; then
        wget -O $filepath $url
        if [ $? -ne 0 ]; then
            EXITCODE=1;
        fi
    fi
    actual_checksum=`sha256sum $filepath | { read checksum file; echo $checksum; }`;
    if [ "$actual_checksum" = "$desired_checksum" ]; then
        found_file=1;
        echo -e "\n'$filename' was downloaded successfully!\n\n" 1>&2;
        error=0;
        chmod $permissions $filepath 1>&2 || error=1;
        if [ "$error" -eq "1" ]; then
            echo -e "\nFailed to set permissions on '$filename'.\n\n" 1>&2;
            EXITCODE=1;
        fi
    fi
    if [ "$found_file" -eq "0" ]; then
        echo -e "Failed to download '$filename'.\n\n" 1>&2;
        EXITCODE=1;
    fi
done < ${INSTDIR}/filesums

# Let the user know everything went ok (or not)
if [ -z "$QUIETMODE" ] ; then
    if [ $EXITCODE = 0 ] ; then
        echo -e "\nEverything downloaded and installed.\n\n"
    else
        exit_with_error "One or more components could not be downloaded."
    fi
fi

exit $EXITCODE;
