post_install() {
	echo 
	echo " for this to work, add this line in /etc/pulse/default.pa"
	echo " load-module module-dbus-protocol"
	echo " also, it may be possible that youe need to restart pulseaudio (depends on your configuration)"
}

post_remove() {
	echo
	echo " You can remove load-module module-dbus-protocol line from "
	echo " /etc/pulse/default.pa if nothing else you intalled depends it"
}

