# Generated by gem2arch
# Maintainer: LeeF
# Contributor: Christian Neukirchen <chneukirchen@gmail.com>

_gemname=rack
pkgname=ruby-enterprise-$_gemname
pkgver=1.2.1
pkgrel=2
pkgdesc="a modular Ruby webserver interface"
arch=('i686' 'x86_64')
url="http://rack.rubyforge.org"
license=('MIT')
depends=('ruby-enterprise')
makedepends=('ruby-enterprise')
source=(http://gems.rubyforge.org/gems/$_gemname-$pkgver.gem ruby-enterprise-rack.install)
install=ruby-enterprise-rack.install
noextract=($_gemname-$pkgver.gem)
md5sums=('ad93c6bf876bb75af374b416593a4c08'
		'd9e0f15cfe65a87108d4a0f80f67d029')

build() {
  cd $srcdir
  local _gemdir=`ruby -rubygems -e'puts Gem.default_dir'`
  gem install --ignore-dependencies --no-rdoc --no-ri -i "$pkgdir$_gemdir" $_gemname-$pkgver.gem
}
