post_install() {
  update-desktop-database -q
  echo "------------------------------------------------------------------------------------"
  echo "To activate zsh-syntax-highlighting, add the following line at the end of ~/.zshrc:"
  echo "source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
  echo "------------------------------------------------------------------------------------"
}

post_upgrade() {
  post_install $1
}

post_remove() {
  post_install $1
}

# vim:set ts=2 sw=2 et:
