--- Makefile.am	2011-05-28 03:25:14.000000000 -0700
+++ Makefile_new.am	2014-08-08 22:23:17.357973594 -0700
@@ -1,8 +1,5 @@
 # Process this file with automake to produce a Makefile.in file.
-SUBDIRS = data intl po m4 src doc
-if build_tests
-SUBDIRS += tests
-endif
+SUBDIRS = data intl po m4 src
 
 ACLOCAL_AMFLAGS = -I m4
 
