post_install() {
    # rename the *.pkg.* file so that pacman can successfully install this package.  
    rename "wmpiki-0.2.4-2-x86_64.pkg.tar.xz" "wmpiki-v24-0.2.4-2-x86_64.pkg.tar.xz" "wmpiki-0.2.4-2-x86_64.pkg.tar.xz"
    #rename "wmpiki-0.2.4-2-x86_64.pkg.tar.xz" "wmpiki-v24-2.
}
post_upgrade() {
     rename "wmpiki-0.2.4-2-x86_64.pkg.tar.xz" "wmpiki-v24-0.2.4-2-x86_64.pkg.tar.xz" "wmpiki-0.2.4-2-x86_64.pkg.tar.xz"
 }
