post_install() {
  echo "THIS PACKAGE NEED CONFIGURATIONS:"
  echo "You must edit /usr/bin/gnome-shell-google-calendar.py"
  echo "see /usr/share/gnome-shell-google-calendar/README.rst."
  echo "To start the script at gnome login copy gnome-shell-google-calendar.desktop"
  echo "from /usr/share/gnome-shell-google-calendar/ to ~/.config/autostart/"
}

post_upgrade() {
  echo "THIS PACKAGE NEED CONFIGURATIONS:"
  echo "You must edit /usr/bin/gnome-shell-google-calendar.py"
  echo "see /usr/share/gnome-shell-google-calendar/README.rst."
  echo "To start the script at gnome login copy gnome-shell-google-calendar.desktop"
  echo "from /usr/share/gnome-shell-google-calendar/ to ~/.config/autostart/"
 }
