post_install() {
  ln -s "/usr/share/gnome-shell-google-calendar/gnome-shell-google-calendar.py" "/usr/bin/gnome-shell-google-calendar"
  chmod 755 "/usr/bin/gnome-shell-google-calendar"
  echo "Run manually first time to identify vs gnome-keyring."
}

post_remove() {
 rm "/usr/bin/gnome-shell-google-calendar"
}

post_upgrade() {
  if [ ! -f "/usr/bin/gnome-shell-google-calendar" ];
  then
    ln -s "/usr/share/gnome-shell-google-calendar/gnome-shell-google-calendar.py" "/usr/bin/gnome-shell-google-calendar"
    chmod 755 "/usr/bin/gnome-shell-google-calendar"
  fi
  echo "Old config files are not needed anymore and package dependencies changed. Check pacman -Qdt."
  echo "Run manually first time to identify vs gnome-keyring."
}
