post_install() {
  echo '
-------------------------------------------------------------------------
A default configuration file for traydevice is provided in :

/usr/share/udisksvm/default.xml

Before using the udisksvm script, THIS FILE MUST BE COPIED AS :

$HOME/.config/traydevice/default.xml

which is the default configuration file traydevice looks for.

Other infos for using the script are given in /usr/share/udisksvm/README
-------------------------------------------------------------------------
'
}

post_upgrade() {
  echo '
------------------------------------------------------------------------------
If a $HOME/.config/traydevice/default.xml already exists, BE SURE CHANGES IN : 

/usr/share/udisksvm/default.xml

ARE COPIED TO :

$HOME/.config/traydevice/default.xml

FOR TRAYDEVICE TO USE THEM.

Other infos for using the script are given in /usr/share/udisksvm/README
------------------------------------------------------------------------------
'
}

# vim:set ts=2 sw=2 et:
