post_install() {
  echo '
-------------------------------------------------------------------------
The configuration file used by traydevice is :

/usr/share/udisksvm/udisksvm.xml

Infos for using the script are given in /usr/share/udisksvm/README
-------------------------------------------------------------------------
'
}

post_upgrade() {
  echo '
------------------------------------------------------------------------------
The configuration file used by traydevice is :

/usr/share/udisksvm/udisksvm.xml

Infos for using the script are given in /usr/share/udisksvm/README
------------------------------------------------------------------------------
'
}

# vim:set ts=2 sw=2 et:
