# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=knife-digital_ocean
pkgname=ruby-$_gemname
pkgver=2.3.0
pkgrel=1
pkgdesc='A plugin for chef'\''s knife to manage instances of DigitalOcean servers'
arch=(any)
url='https://github.com/rmoriz/knife-digital_ocean'
license=('Apache 2.0')
depends=(ruby ruby-chef ruby-droplet_kit)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('cd0a66db11ab10b84458d5ef69d099747d252203')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE.txt" "$pkgdir/usr/share/licenses/$pkgname/LICENSE.txt"
}
