post_install() {
  getent group jboss >/dev/null 2>&1 || groupadd jboss
  getent passwd jboss >/dev/null 2>&1 || useradd -g jboss -d /usr/share/jboss7 -s /bin/bash jboss
  chown -R jboss:jboss /usr/share/jboss7/
  echo ">>> Make sure JAVA_HOME is set correctly"
}

post_upgrade() {
  post_install $1
}

post_remove() {
  if getent passwd jboss >/dev/null 2>&1; then
    userdel jboss
  fi
  if getent group jboss >/dev/null 2>&1; then
    groupdel jboss
  fi
}
