post_install() {
  sudo sh -c "getent group jboss >/dev/null 2>&1 || groupadd jboss"
  sudo sh -c "getent passwd jboss >/dev/null 2>&1 || useradd -g jboss -d /usr/share/jboss7 -s /bin/bash jboss"
  sudo chown -R jboss:jboss /usr/share/jboss7/
  echo ">>> Make sure JAVA_HOME is set correctly"
}

post_remove() {
  if getent passwd jboss >/dev/null 2>&1; then
    sudo userdel jboss
  fi
  if getent group jboss >/dev/null 2>&1; then
    sudo groupdel jboss
  fi
}
