#!/usr/bin/bash

build() {
    local mod
    for mod in dm-persistent-data dm-mod dm-bio-prison dm-cache dm-cache-mq crc32c_intel dm_cache_mq dm_cache dm_persistent_data dm_bio_prison dm_bufio libcrc32c dm_crypt dm_mod
    do
        add_module "$mod"
    done

    add_binary "/usr/bin/dmsetup"
    add_binary "/usr/bin/cache_check"
    add_binary "/usr/bin/cache_dump"
    add_binary "/usr/bin/cache_metadata_size"
    add_binary "/usr/bin/cache_repair"
    add_binary "/usr/bin/cache_restore"
    add_file "/usr/lib/udev/rules.d/10-dm.rules"
    add_file "/usr/lib/udev/rules.d/13-dm-disk.rules"
    add_file "/usr/lib/udev/rules.d/95-dm-notify.rules"
    add_file "/usr/lib/initcpio/udev/11-dm-initramfs.rules" "/usr/lib/udev/rules.d/11-dm-initramfs.rules"

    add_runscript
}

help() {
  cat <<HELPEOF
This hook enables dm-cache volumes in initramfs.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
