#!/bin/bash

post_install() {
touch /etc/dm-cachetab
chmod 600 /etc/dm-cachetab

systemctl enable dm-cache

cat<<INSTALLEOF
* insert your dmsetup lines into "/etc/dm-cachetab"
* add "dm-cache" to "HOOKS" in "/etc/mkinitcpio.conf"
* rebuild the initramfs ("mkinitcpio -p linux")
INSTALLEOF
}

post_remove() {
cat<<REMOVEEOF
Remove "dm-cache" from "HOOKS" in "/etc/mkinitcpio.conf",
then rebuild the initramfs ("mkinitcpio -p linux").
REMOVEEOF
}

post_upgrade() {
post_install
}

