*** Makefile	2013-11-15 21:39:00.951928153 +0900
--- Makefile2	2013-11-15 21:39:23.268198923 +0900
***************
*** 1,4 ****
! prefix  = /usr/local
  bindir  = $(prefix)/bin
  datadir = $(prefix)/share/azminipt
  menudir = ~/.local/share/applications
--- 1,4 ----
! prefix  = /usr
  bindir  = $(prefix)/bin
  datadir = $(prefix)/share/azminipt
  menudir = ~/.local/share/applications
***************
*** 12,18 ****
  CXXFLAGS = -O2 -Wall
  INCLUDE = -I./azxclass/include -I/usr/include/freetype2
  LFLAGS	= -s
! LINKS	= -lrt -lX11 -lXext -lXft -lpthread -lz
  MACRO	= -D_AZCVPNG_RESDIR="\"$(datadir)\""
  RM	= rm -f
  
--- 12,18 ----
  CXXFLAGS = -O2 -Wall
  INCLUDE = -I./azxclass/include -I/usr/include/freetype2
  LFLAGS	= -s
! LINKS	= -lrt -lX11 -lXext -lXft -lpthread -lz -lfontconfig -lfreetype
  MACRO	= -D_AZCVPNG_RESDIR="\"$(datadir)\""
  RM	= rm -f
  
***************
*** 52,60 ****
  	$(CXX) $(LFLAGS) -o $@ $^ $(AXLIB) $(LINKS)
  
  $(OBJDIR)%.o: $(SRCDIR)%.cpp
- 	@if [ ! -d $(OBJDIR) ]; then \
- 		mkdir $(OBJDIR); \
- 	fi
  	$(CXX) $(CXXFLAGS) $(MACRO) $(INCLUDE) -c $< -o $@
  
  debug:
--- 52,57 ----
