post_install() {
    if [[ "$(uname -m)" == "x86_64" ]];then
        libdir="usr/lib32/skype"
    else
        libdir="usr/lib/skype"
    fi

    cat <<EOF
To run Skype with the poll-fix hack, either run with \`skype-with-poll-fix\`,
or just run with \`LD_PRELOAD=/$libdir/skype-poll-fix.so skype\`.

For details on configuring the poll-fix, read
https://github.com/ValdikSS/skype-poll-fix#configuration
EOF
}
