--- Makefile	2011-07-15 10:35:37.000000000 -0400
+++ Makefile	2011-08-28 22:43:23.000000000 -0400
@@ -32,7 +32,7 @@
 
 VERSION := $(shell head -n 1 VERSION)
 install:
-	ocamlfind install -patch-version ${VERSION} $(LIBRARY) lib/META $(INTF) $(IMPL) $(NATIMPL) $(OTHERS) $(DOC)
+	ocamlfind install -ldconf ignore -patch-version ${VERSION} $(LIBRARY) lib/META $(INTF) $(IMPL) $(NATIMPL) $(OTHERS) $(DOC)
 	install -d -m 755 $(BINDIR)
 	install $(BIN) $(BINDIR)
 
