post_install() {
    xdg-icon-resource install --theme ubuntu-mono-dark --novendor --size 16 /usr/share/feedindicator/dark/indicator-feedindicator.png indicator-feedindicator
    xdg-icon-resource install --theme ubuntu-mono-dark --novendor --size 16 /usr/share/feedindicator/dark/indicator-feedindicator-attention.png indicator-feedindicator-attention
    xdg-icon-resource install --theme ubuntu-mono-light --novendor --size 16 /usr/share/feedindicator/light/indicator-feedindicator.png indicator-feedindicator
    xdg-icon-resource install --theme ubuntu-mono-light --novendor --size 16 /usr/share/feedindicator/light/indicator-feedindicator-attention.png indicator-feedindicator-attention
    xdg-icon-resource install --theme hicolor --novendor --size 16 /usr/share/feedindicator/hicolor/indicator-feedindicator.png indicator-feedindicator
    xdg-icon-resource install --theme hicolor --novendor --size 16 /usr/share/feedindicator/hicolor/indicator-feedindicator-attention.png indicator-feedindicator-attention
    
    xdg-desktop-menu install --novendor /usr/share/feedindicator/Feedindicator.desktop
}

