.TH "Puma-EM" "1" "0.6.1" "Idesbald van den Bosch" ""
.SH "NAME"
.LP 
puma\-em \- Computational electromagnetics software, MoM + MLFMM
.SH "SYNTAX"
.LP 
puma-em [\fI\-n <number of processes>\fP] [\fI\-i <input dir>\fP] [\fI\-s <simulation dir>\fP]
.SH "DESCRIPTION"
.LP 
\fBPuma\-EM\fP is a code that allows the computation of various electromagnetic quantities when a target is
excited by an electromagnetic source. These quantities are the scattered fields and the currents on the
surface of the target.
.SH "OPTIONS"
.LP 
.TP 
\fB\-n \fR <\fInumber of processes\fP>
Runs the code on <number of processes> processes with MPI\fP.
.TP 
\fB\-i \fR <\fIinput dir\fP>
The code uses <input dir> for input\fP.
.TP 
\fB\-s \fR <\fIsimulation dir\fP>
The code uses <simulation dir> for simulation\fP.
.SH "FILES"
.LP 
\fI<input dir>/simulation_parameters.py\fP 
.br 
\fI<input dir>/MLFMA_parameters.py\fP 
.SH "AUTHORS"
.LP 
Idesbald van den Bosch <http://sourceforge.net/projects/puma\-em/>
