_ensure_mount_path() {
	mkdir -p -m 775 /mnt/sshfs
	chown :users /mnt/sshfs
}

post_install() {
	_ensure_mount_path
}

pre_remove() {
	echo "Unmounting any sftpman-mounted filesystems.."
	# The sleep.d script knows how to unmount sftpman filesystems for all users.
	# It's usually used during suspend/hibernate.
	/etc/pm/sleep.d/49-sftpman suspend
}

post_remove() {
	rmdir --ignore-fail-on-non-empty /mnt/sshfs
}
