diff --git a/Makefile.common b/Makefile.common
index e9fabcc..6e08da9 100644
--- a/Makefile.common
+++ b/Makefile.common
@@ -26,7 +26,7 @@
 #	You should have received a copy of the GNU General Public License
 #	along with simavr.  If not, see <http://www.gnu.org/licenses/>.
 
-CFLAGS	+= -g --std=gnu99 -O2
+CFLAGS	+= -fPIC -g --std=gnu99 -O2
 CFLAGS	+= ${patsubst %,-I%,${subst :, ,${IPATH}}}
 LDFLAGS += -lelf 
 
@@ -36,7 +36,7 @@ AVR_INC := ${AVR_ROOT}/avr-4/
 AVR := ${AVR_ROOT}/bin/avr-
 LFLAGS += -L/opt/local/lib
 else
-AVR_ROOT := /usr/lib/avr
+AVR_ROOT := /usr/avr
 AVR_INC := ${AVR_ROOT}
 AVR := avr-
 endif
diff --git a/simavr/Makefile b/simavr/Makefile
index c147f2b..c820bf8 100644
--- a/simavr/Makefile
+++ b/simavr/Makefile
@@ -18,7 +18,7 @@
 
 target	= run_avr
 
-CFLAGS	+= -O3  -mfpmath=sse -msse2 -Wall
+CFLAGS	+= -fPIC -O3  -mfpmath=sse -msse2 -Wall
 #CFLAGS	+= -DCONFIG_SIMAVR_TRACE=1
 
 cores	= ${wildcard cores/*.c}
