--- a/Makefile.common
+++ b/Makefile.common
@@ -36,7 +36,7 @@ AVR_INC := ${AVR_ROOT}/avr-4/
 AVR := ${AVR_ROOT}/bin/avr-
 LFLAGS += -L/opt/local/lib
 else
-AVR_ROOT := /usr/lib/avr
+AVR_ROOT := /usr/avr
 AVR_INC := ${AVR_ROOT}
 AVR := avr-
 endif
