rebuild_module_dependencies() {
	_PACKAGES=`pacman -Qsq linux`
	_KERNELS=`pacman -Ql $PACKAGES | grep '/modules.builtin$' | sed 's/.*\/lib\/modules\/\(.*\)\/modules.builtin/\1/g'`
	for kernver in $_KERNELS; do
		echo -n ">>> Rebuilding module dependencies for $kernver ..."
		depmod $kernver > /dev/null 2>&1
		echo ' done.'
	done
}

post_install() {
	rebuild_module_dependencies
}
post_upgrade() {
	rebuild_module_dependencies
}
post_remove() {
	rebuild_module_dependencies
}
