post_install() {
	echo '------------------------------------------------------------------------------------'
	echo 'Run the script at startup or at login, for example, simply symlink the included'
	echo 'xbmc_prevent_xscreensaver.desktop to your autostart dir:'
	echo
	echo ' ln -s /usr/share/applications/xbmc_prevent_xscreensaver.desktop ~/.config/autostart'
	echo '------------------------------------------------------------------------------------'
}
