# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Babken Vardanyan <483ken@gmail.com>

_gemname=factory_girl_rails
pkgname=ruby1.9-$_gemname
pkgver=4.4.1
pkgrel=1
pkgdesc='factory_girl_rails provides integration between factory_girl and rails 3'
arch=(any)
url='http://github.com/thoughtbot/factory_girl_rails'
license=(MIT)
depends=(ruby1.9 ruby1.9-railties ruby1.9-factory_girl)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('9755a7481c75aaaa1166e1e068bb09a1a96ae406')

package() {
  local _gemdir="$(ruby-1.9 -e'puts Gem.default_dir')"
  gem-1.9 install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
