post_install() {
    usr/bin/glib-compile-schemas /usr/share/glib-2.0/schemas
    usr/bin/update-desktop-database -q
    usr/bin/gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

pre_upgrade() {
    if [ -f /usr/share/gconf/schemas/indicator-sensors.schemas ]; then
        usr/bin/gconfpkg --uninstall indicator-sensors
    fi
}

post_upgrade() {
    post_install $1
}

post_remove() {
    post_install $1
}
