post_install() {
  EXTRAMODULES='extramodules-3.3-ARCH'
  depmod $(cat /lib/modules/$EXTRAMODULES/version)
}

post_upgrade() {
  EXTRAMODULES='extramodules-3.3-ARCH'
  depmod $(cat /lib/modules/$EXTRAMODULES/version)
  rmmod nvidia || echo 'In order to use the new nvidia module, exit Xserver and unload it manually.'
}

post_remove() {
  EXTRAMODULES='extramodules-3.3-ARCH'
  depmod $(cat /lib/modules/$EXTRAMODULES/version)
}
