KERNEL_VERSION=2.6.23-ARCH

post_install() {
  echo "=====  Usage Instructions  ====="
  echo "a) 'modprobe pctel'"
  echo "b) the device is '/dev/ttyS_PCTEL0'"
  echo "c) your user should be in the 'tty' group"
  echo
  depmod -v $KERNEL_VERSION >/dev/null 2>&1
}

post_upgrade() {
  depmod -v $KERNEL_VERSION >/dev/null 2>&1
}

post_remove() {
  depmod -v $KERNEL_VERSION >/dev/null 2>&1
}

op=$1
shift
[ "$(type -t "$op")" = "function" ] && $op "$@"
