# Generated by Xyne::Arch::CPAN 0.07

pkgname=perl-fuse-simple
pkgver=1.0.0
pkgrel=1
pkgdesc="CPAN package - Fuse::Simple - Simple way to write filesystems in Perl using FUSE"
arch=('i686 x86_64')
url="http://search.cpan.org/dist/Fuse-Simple/"
license=('unknown')
source=('http://search.cpan.org/CPAN/authors/id/N/NO/NOSEYNICK/Fuse-Simple-1.00.tar.gz')
md5sums=('64d3db272b16b37d3278cfd3795a50ba')
sha256sums=('dbf82e43a06854d922d2380ea106a94681418ac98915461e52f8f6adca33acb2')
depends=('perl' 'perl-fuse')
options=(!emptydirs)

build() {
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Makefile.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor || return 1
    make  || return 1
    make install DESTDIR="${pkgdir}" || return 1

  else
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Build.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Build.PL INSTALLDIRS=vendor || return 1
    ./Build  || return 1
    ./Build install destdir=${pkgdir} || return 1

  else
    echo "error: failed to detect build method for $pkgname"
    echo "you may be able to fix this by editing the PKGBUILD"
    return 1
  fi fi

  # remove perllocal.pod and .packlist
  find ${pkgdir} -name perllocal.pod -delete
  find ${pkgdir} -name .packlist -delete
}

# vim:set ts=2 sw=2 et:
