# create symlinks
post_install() {
    ln -s /usr/share/sunbird/sunbird /usr/bin/sunbird
    ln -s /usr/share/sunbird/icons/mozicon50.png /usr/share/icons/hicolor/48x48/sunbird.png
    ln -s /usr/share/sunbird/icons/mozicon16.png /usr/share/icons/hicolor/16x16/sunbird.png
    ln -s /usr/share/sunbird/icons/mozicon128.png /usr/share/icons/hicolor/128x128/sunbird.png
}
# remove symlinks
post_remove() {
 rm /usr/bin/sunbird
 find /usr/share/icons/hicolor -name 'sunbird.png' -exec rm {} \;
}
# vim:set ts=2 sw=2 et:
