post_install() {
    
    dkms install -m nvidia -v $(echo $1 | cut -d "-" -f1)
    depmod -a

    echo -------------------------------
    echo By using this package you accept the NVIDIA license, 
    echo which has been installed in /usr/share/licenses/nvidia/LICENSE
    echo If you do not accept this license, you must remove the package immediately.
    echo -------------------------------
    echo These drivers are beta. We recommend to use the drivers from the extra repo.
    echo -------------------------------
    echo
}

pre_upgrade() {
    local curver=$2
    # $2 is unset due to a bug. Query current version using pacman as fallback
    [ -n "$curver" ] || curver=$(LANG=C pacman -Qi dkms-nvidia-beta | awk '/^Version/{print $3}' | cut -d "-" -f1)
    pre_remove $curver
}

post_upgrade() {
    post_install $(echo $1 | cut -d "-" -f1)
}

pre_remove() {
    dkms remove -m nvidia -v $(echo $1 | cut -d "-" -f1) --all
}

post_remove() {
    depmod -a
}
