.if !\n(.g \{\
.	if !\w|\*(lq| \{\
.		ds lq ``
.		if \w'\(lq' .ds lq "\(lq
.	\}
.	if !\w|\*(rq| \{\
.		ds rq ''
.		if \w'\(rq' .ds rq "\(rq
.	\}
.\}
.ie t .ds Tx \s-1T\v'.4n'\h'-.1667'E\v'-.4n'\h'-.125'X\s0
. el  .ds Tx TeX
.de Id
. ds Yr \\$4
. substring Yr 0 3
. ds Mn \\$4
. substring Mn 5 6
. ds Dy \\$4
. substring Dy 8 9
. \" ISO 8601 date, complete format, extended representation
. ds Dt \\*(Yr-\\*(Mn-\\*(Dy
..
.TH CJDSCRIPT 1 \*(Dt "cjdscript (git)" "User Commands"
.hy 0
.
.SH "ABOUT"
This script maintains and executes the collection of (working) scripts included with cjdns\.
.
.SH "REQUIREMENTS"
This script requires git and the collection of coreutils, and the scripts you can run using it require a running copy of cjdns\.
.
.SH "USAGE"
.
.IP "\(bu" 2
Install the dependancies required for the desired scripts
.
.IP "\(bu" 2
Run cjdscript without any arguments to run some initial setup functions
.
.IP "\(bu" 2
Run \fBcjdscript \-h\fR for a list of available commands and scripts you can now run
.
.IP "\(bu" 2
Run \fBcjdscript \-u\fR to update the scripts and recheck them against local deps
.
.P
\fBNote\fR: The default directory for cjdscript is ~/\.cjdscript; feel free to blow this directory away and start over if you run into issues\.
.
.SH "CREDITS"
Written by Kevin MacMartin: GitHub Projects \fIhttps://github\.com/prurigro?tab=repositories\fR | Arch Linux AUR Packages \fIhttps://aur\.archlinux\.org/packages/?SeB=m&K=prurigro\fR
.
.SH "LICENSE"
This script is open source and licensed under the GPLv3 \fIhttp://www\.gnu\.org/copyleft/gpl\.html\fR\.
