# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Rhys <rhys@johnguant.com>

_gemname=tagen
pkgname=ruby-$_gemname
pkgver=2.0.2
pkgrel=1
pkgdesc='a lightweight core and extra extensions for Ruby.'
arch=(any)
url='http://github.com/GutenYe/tagen'
license=()
depends=(ruby ruby-pd ruby-activesupport)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('338f5e6b28753c889fef66c0d359fd008aa6df1e')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
