post_install() {
  echo "==> "
  echo "==> Tor has been preconfigured to run as a client only"
  echo "==> Tor is experimental software, Do not rely on it for strong anonymity."
  echo "==> "
  systemd-sysusers tor.conf
  systemd-tmpfiles --create tor.conf
}

post_upgrade() {
  systemd-sysusers tor.conf
  systemd-tmpfiles --create tor.conf
}

pre_remove() {
  getent passwd tor &>/dev/null && userdel tor &> /dev/null
  getent group tor &>/dev/null && groupdel tor &> /dev/null
}
