post_install() {
	/sbin/install_java_jce_ustrength install
	echo "===> Everytime jre is updated, you must run:"
	echo "===> /sbin/install_java_jce_ustrength7 install"
	echo "===> Otherwise, the programs which need this package will break."
}

pre_upgrade() {
	/sbin/install_java_jce_ustrength uninstall
}

post_upgrade() {
	/sbin/install_java_jce_ustrength install
}

pre_remove() {
	/sbin/install_java_jce_ustrength uninstall
}

op=$1
shift
$op $*
