# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Rhys <rhys@johnguant.com>

_gemname=gtksourceview2
pkgname=ruby-$_gemname
pkgver=2.2.3
pkgrel=1
pkgdesc='Ruby/GtkSourceView2 is a Ruby binding of gtksourceview-2.x.'
arch=(i686 x86_64)
url='http://ruby-gnome2.sourceforge.jp/'
license=('LGPLv2.1 or later')
depends=(ruby ruby-gtk2)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('23d27a33f98ec14ecc3b0d76cb9983134ad0babe')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
