# arg 1:  the new package version
post_install() {
		chgrp -R leterrier /usr/share/abuledu-associations/{reglages,categorie,images}
		chmod -R g+w /usr/share/abuledu-associations/{reglages,categorie,images}
		TESTG=`getent group | grep profs` || true
			if [ -z "${TESTG}" ]; then
			  groupadd profs
			fi
		chmod 3777 /usr/share/abuledu-associations/reglages -R
		chown :profs /usr/share/abuledu-associations/reglages -R
		chmod 3777 /usr/share/abuledu-associations/categorie -R
		chown root:profs /usr/share/abuledu-associations/categorie -R
		chmod 3777 /usr/share/abuledu-associations/images -R
		chown root:profs /usr/share/abuledu-associations/images -R
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $1
}



op=$1
shift
$op $*
