post_install() {
  update-desktop-database -q
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  echo "if you are running x86_64, you need the lib32 opt depends for your driver"
}

pre_install(){
  update-desktop-database -q
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
    chattr -i /usr/bin/steam
}

post_upgrade() {
  post_install $1 $2
}

pre_upgrade(){
    pre_install $1 $2
}

post_remove() {
  pre_install $1 removing
}

