# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: tuftedocelot <tuftedocelot@fastmail.fm>

_gemname=gitlab-grit
pkgname=ruby-$_gemname-2.6.5
pkgver=2.6.5
pkgrel=1
pkgdesc='Ruby Git bindings.'
arch=(any)
url='http://github.com/gitlabhq/grit'
license=(MIT)
depends=(ruby ruby-charlock_holmes ruby-posix-spawn ruby-mime-types-1 ruby-diff-lcs)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('a5ecb1130380a26b43a96ebdb064db081781ec3c')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
