.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SFN" "1" "February 2013" "" ""
.
.SH "NAME"
\fBsfn\fR \- send files over network
.
.SH "SYNOPSIS"
\fBsfn\fR \fB\-\-listen\fR [options] [files to send]
.
.br
\fBsfn\fR \fB\-\-connect\fR <address> [options] [files to send]
.
.SH "DESCRIPTION"
sfn is an utility to send files over network using direct TCP connection\. After launched, sfn establishes a connection, sends all the files from command line (if any), receives all the files from another side and then exits\.
.
.SH "OPTIONS"
.
.TP
\fB\-\-version\fR, \fB\-v\fR
Show version and exit\.
.
.TP
\fB\-\-help\fR, \fB\-h\fR
Show help and exit\.
.
.TP
\fB\-\-port\fR, \fB\-p\fR
Use specified port\. Defaults to 3214\.
.
.TP
\fB\-\-prefix\fR, \fB\-f\fR
Add prefix to received files\' path and name\. For example: \fB/home/user/downloads/\fR, \fBsfn\-\fR, \fB/etc/file\-\fR\.
.
.TP
\fB\-\-no\-external\-ip\fR, \fB\-n\fR
Don\'t perform external IP detection and reverse DNS lookup\.
.
.SH "EXAMPLES"
Listen on port 3333, place all received files into current workdir:
.
.IP "" 4
.
.nf

$ sfn \-s \-p 3333
.
.fi
.
.IP "" 0
.
.P
Connect to server \fB55\.66\.77\.88\fR, send a file named \fBnumbers\.txt\fR and place received ones into \fB/tmp/sfn\fR:
.
.IP "" 4
.
.nf

$ sfn \-c 55\.66\.77\.88 \-f /tmp/sfn/ numbers\.txt
.
.fi
.
.IP "" 0
.
.P
Please note that trailing slash in \fB/tmp/sfn/\fR is mandatory because it is simply a prefix\.
.
.P
Listen on default port, send some files and don\'t try to determine our external IP:
.
.IP "" 4
.
.nf

$ sfn \-s \-n for\-james\-*\.txt
.
.fi
.
.IP "" 0
.
.P
Connect to \fBmyserver\.dyndns\.org\fR, receive some files, prefix their names with \fBsfn\-received\-\fR and place them into \fB~/Downloads\fR:
.
.IP "" 4
.
.nf

$ sfn \-c myserver\.dyndns\.org \-f ~/Downloads/sfn\-received\-
.
.fi
.
.IP "" 0
.
.SH "BUGS"
If you have found a bug, create an issue in the project\'s issue tracker: \fIhttps://github\.com/m1kc/sfn/issues\fR or simply drop me a note on email\. Thanks\.
.
.SH "COPYRIGHT"
Copyright (c) m1kc <\fIm1kc@yandex\.ru\fR>, 2013
