post_install() {
	echo "
# To generate a KDM theme with your current plasma theme and wallpaper,
# run 'kdm-theme-generator' as your normal user. 
# The theme will be installed in your $KDEHOME directory, 
# which you can determinee by running 'kde4-config --localprefix'.

# To use the theme, run 'install-kdm-theme' as your normal user,
# open System Settings -> Advanced -> Login manager -> Theme,
# select 'MyKdmTheme', and click 'Apply'
"
}

post_upgrade() {
	post_install $1
}
