# Generated by Xyne::Arch::CPAN 0.07

pkgname=perl-memoize-memcached
pkgver=0.03
pkgrel=1
pkgdesc="use a memcached cache to memoize functions"
arch=('i686' 'x86_64')
url="http://search.cpan.org/dist/Memoize-Memcached/"
license=('PerlArtistic' 'GPL')
source=('http://search.cpan.org/CPAN/authors/id/D/DT/DTRISCHUK/Memoize-Memcached-0.03.tar.gz')
md5sums=('74117cfc00a7c4915b169eaae0c8b91c')
sha256sums=('88ca77cc20963c93581f55b5f4124bc2d20e243e8211ba482b2023d49dace756')
depends=('perl-cache-memcached' 'perl-memoize')
makedepends=('perl-extutils-makemaker')
options=(!emptydirs)

build() {
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Makefile.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor || return 1
    make  || return 1
    make install DESTDIR="${pkgdir}" || return 1

  else
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Build.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Build.PL INSTALLDIRS=vendor || return 1
    ./Build  || return 1
    ./Build install destdir=${pkgdir} || return 1

  else
    echo "error: failed to detect build method for $pkgname"
    echo "you may be able to fix this by editing the PKGBUILD"
    return 1
  fi fi

  # remove perllocal.pod and .packlist
  find ${pkgdir} -name perllocal.pod -delete
  find ${pkgdir} -name .packlist -delete
}

# vim:set ts=2 sw=2 et:

