# Message displayed after a fresh install.
post_install() {
    echo "Evil requires the undo-tree.el script to function properly."
    echo "Enable Evil by adding the following lines to ~/.emacs:"
    echo "  (require 'evil)"
    echo "  (evil-mode 1)"
}

# Message displayed afteer package removal.
post_remove() {
    echo "Remove these lines from ~/.emacs:"
    echo "  (require 'evil)"
    echo "  (evil-mode 1)"
}
