diff -rupN vcftools_0.1.9/Makefile src/vcftools_0.1.9/Makefile
--- vcftools_0.1.9/Makefile	2012-05-10 07:52:12.000000000 +0200
+++ src/vcftools_0.1.9/Makefile	2012-09-11 12:34:21.000000000 +0200
@@ -21,7 +21,7 @@ export MODDIR = ${PREFIX}/lib/perl5/site
 
 DIRS = cpp perl
 install:
-	    @mkdir -p $(BINDIR); mkdir -p $(MODDIR); \
+	    @mkdir -p $(BINDIR); \
         for dir in $(DIRS); do cd $$dir && $(MAKE) $(MAKEFLAGS) && cd ..; done
 
 clean:
diff -rupN vcftools_0.1.9/perl/Makefile src/vcftools_0.1.9/perl/Makefile
--- vcftools_0.1.9/perl/Makefile	2012-05-10 07:52:10.000000000 +0200
+++ src/vcftools_0.1.9/perl/Makefile	2012-09-11 12:32:05.000000000 +0200
@@ -4,8 +4,8 @@ BIN = vcf-compare fill-aa vcf-annotate v
 MOD = FaSlice.pm Vcf.pm VcfStats.pm
 
 install:
-	    @for i in $(BIN); do cp $(CURDIR)/$$i $(BINDIR)/$$i; done; \
-        for i in $(MOD); do cp $(CURDIR)/$$i $(MODDIR)/$$i; done; 
+	    @for i in $(BIN); do install -D -m755 $(CURDIR)/$$i $(BINDIR)/$$i; done; \
+        for i in $(MOD); do install -D -m755 $(CURDIR)/$$i $(MODDIR)/$$i; done; 
 
 clean:
 		@for i in $(BIN); do rm -f $(BINDIR)/$$i; done; \
