# arg 1:  the new package version
post_install() {
	echo -n "Running texhash and updmap-sys..."
	texhash
	updmap-sys --enable Map=uhc-base.map
	updmap-sys --enable Map=uhc-extra.map
	echo "Done."
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
/bin/true
}

# arg 1:  the old package version
post_remove() {
        echo -n "Running texhashi and updmap-sys..."
        texhash
	updmap-sys --syncwithtrees
        echo "Done."
}

op=$1
shift
$op $*
