post_install() {
  mktexlsr
  echo To use SympyTeX, include the line
  echo
  echo "     \usepackage{sympytex}"
  echo
  echo In the preamble of your latex document.
  echo Build your document using the following commands.
  echo
  echo "     latex example.tex"
  echo "     python example.sympy"
  echo "     latex example.tex"
  echo
  echo More info at http://elec.otago.ac.nz/w/index.php/SympyTeX
}

post_upgrade() {
  mktexlsr
}

post_remove() {
  mktexlsr
  }
  