# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=origami
pkgname=ruby-$_gemname
pkgver=1.2.7
pkgrel=1
pkgdesc='Origami aims at providing a scripting tool to generate and analyze malicious PDF files.'
arch=(any)
url='http://code.google.com/p/origami-pdf'
license=(LGPL-3)
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('e34a4cf81dbb194a4ffe1939ff609e95479e53f1')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/COPYING.LESSER" "$pkgdir/usr/share/licenses/$pkgname/COPYING.LESSER"
}
