.Dd June 2008
.Dt A68G 1
.
.Sh NAME
a68g \- Algol 68 Genie, an Algol 68 interpreter
.
.Sh SYNOPSIS
a68g
.Op Fl apropos | help | info [string]
.Op Fl assertions | Fl noassertions
.Op Fl backtrace | Fl nobacktrace
.Op Fl brackets
.Op Fl check | Fl norun
.Op Fl debug | Fl monitor
.Op Fl echo Ar string
.Op Fl execute Ar unit
.Op Fl extensive
.Op Fl frame Ar number
.Op Fl handles Ar number
.Op Fl heap Ar number
.Op Fl listing
.Op Fl moids
.Op Fl overhead Ar number
.Op Fl pragmats | Fl nopragmats
.Op Fl precision Ar number
.Op Fl preludelisting
.Op Fl print Ar unit
.Op Fl reductions
.Op Fl run
.Op Fl source | Fl nosource
.Op Fl stack Ar number
.Op Fl statistics
.Op Fl terminal
.Op Fl timelimit Ar number
.Op Fl trace | Fl notrace
.Op Fl tree | Fl notree
.Op Fl unused
.Op Fl verbose
.Op Fl version
.Op Fl warnings | Fl nowarnings
.Op Fl xref | Fl noxref
.Ar filename
.
.Sh DESCRIPTION
Algol 68 Genie (Algol68G) is an Algol 68 interpreter. It can be used for executing Algol 68 programs or scripts. Algol 68 is a rather lean orthogonal general-purpose language that is a beautiful means for denoting algorithms. Algol 68 was designed as a general-purpose programming language by IFIP Working Group 2.1 (Algorithmic Languages and Calculi) that has continuing responsibility for Algol 60 and Algol 68. 
.
.Sh OPTIONS
Options are passed to a68g either from the file .a68g.rc in the working directory, the environment variable A68G_OPTIONS, the command-line or from pragmats. 
.Pp
Option precedence is as follows: pragmat options supersede command-line options, command-line options supersede options in environment variable A68G_OPTIONS, A68G_OPTIONS supersedes options in .a68g.rc. 
.Pp
Listing options, tracing options and -pragmat, -nopragmat, take their effect when they are encountered in a left-to-right pass of the program text, and can thus be used, for example, to generate a cross reference for a particular part of the program. 
.Pp
Options are not case sensitive. In the list below, uppercase letters are mandatory for recognition. For instance
.Pp
    a68g -prec 200 -ti 60 ...
.Pp
means
.Pp
    a68g -precision 200 -timelimit 60 ...
.Pp
Where numeric arguments are required, suffices k, M or G are allowed for multiplication with 2 ** 10, 2 ** 20 or 2 ** 30 respectively.
.Bl -tag -width Ds
.
.It Fl APropos | Help | INfo Ar [string]
Print info on options if string is omitted, or print info on string otherwise.
.
.It Fl Assertions | Fl NOAssertions
Control elaboration of assertions.
.
.It Fl BACKtrace | Fl NOBACKtrace
Control whether a stack backtrace is done in case a runtime-error occurs.
.
.It Fl BRackets
Consider [ .. ] and { .. } as being equivalent to ( .. ). Traditional Algol 68 syntax allows ( .. ) to replace [ .. ] in bounds and slices.
.
.It Fl Check | Fl NORun
Check syntax only, the interpreter does not start.
.
.It Fl DEBUG | Fl MONitor
Start in the monitor. Invoke the monitor in case a runtime-error occurs; the program will pause in the monitor on the line that contains the error.
.
.It Fl ECHO Ar string
Echo string to standout.
.
.It Fl Execute Ar unit
Execute the Algol 68 unit. In this way one-liners can be executed from the command line.
.
.It Fl EXTensive
Generate an extensive listing.
.
.It Fl FRAME Ar number
Set the frame stack size to
.Ar number
bytes.
.
.It Fl HANDLES Ar number
Set the handle space size to
.Ar number
bytes.
.
.It Fl HEAP Ar number
Set the heap size to
.Ar number
bytes.
.
.It Fl LISTing
Generate a concise listing.
.
.It Fl MOIDS
Generate an overview of modes in the listing file.
.
.It Fl OVERHEAD Ar number
Set overhead for stack checking.
.
.It Fl PORTcheck | Fl NOPORTcheck
Enable or disable portability warning messages.
.
.It Fl PRagmats | Fl NOPRagmats
Control elaboration of pragmats.
.
.It Fl PRECision Ar number
Set the precision for LONG LONG modes to
.Ar number
significant digits.
.
.It Fl PRELUDElisting
Generate a listing of preludes.
.
.It Fl Print Ar unit
Print the value yielded by the Algol 68 unit. In this way one-liners can be executed from the command line.
.
.It Fl QUOTEstropping
Use quote stropping.
.
.It Fl REDuctions
Print reductions made by the parser.
.
.It Fl RUN
Override the norun option.
.
.It Fl SOURCE | Fl NOSOURCE
Control the listing of source lines in the listing file.
.
.It Fl STACK Ar number
Set the stack size to
.Ar number
bytes.
.
.It Fl STatistics
Generate statistics in the listing file.
.
.It Fl TImelimit Ar number
Interrupt the interpreter after
.Ar number
seconds, generating a time limit exceeded error.
.
.It Fl TRace | Fl NOTRace
Control tracing of the running program.
.
.It Fl TREE | Fl NOTREE
Control listing of the syntax tree in the listing file.
.
.It Fl UNUSED
Generate an overview of unused tags in the listing file.
.
.It Fl UPPERstropping
Use upper stropping, which is the default stropping regime.
.
.It Fl VERBose
Use verbose mode.
.
.It Fl Version
Print the version of the running image of a68g.
.
.It Fl Warnings | Fl NOWarnings
Enable warning messages or suppress suppressible warning messages.
.
.It Fl Xref | Fl NOXref
Control generation of a cross-reference in the listing file.
.
.El
.
.Sh AUTHOR
Author of Algol68G is Marcel van der Veer <algol68g@xs4all.nl>.

