# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: kusakata <shohei atmark kusakata period com>

_gemname=couchrest
pkgname=ruby-$_gemname
pkgver=1.2.0
pkgrel=2
pkgdesc='Lean and RESTful interface to CouchDB.'
arch=(any)
url='http://github.com/couchrest/couchrest'
license=('Apache 2.0')
depends=(couchdb ruby ruby-rest-client ruby-mime-types-1 ruby-multi_json)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('7cc039700e15bfc79355df4e516650537a51b440')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
