--- Makefile	2005-04-13 17:59:17.000000000 +0100
+++ Makefile-new	2011-11-02 10:48:32.746394975 +0000
@@ -1,7 +1,7 @@
 VERSION=0.6
 
 DEBUG=-g # -pg
-CFLAGS+=-Wall -O2 -DVERSION=\"${VERSION}\" $(DEBUG)
+CFLAGS+=-Wall -O2 -DVERSION=\"${VERSION}\" -DLARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 $(DEBUG)
 LDFLAGS=-lgpgme $(DEBUG)
 
 OBJS=nasty.o
@@ -12,7 +12,8 @@
 	$(CC) -Wall -W $(OBJS) $(LDFLAGS) -o nasty
 
 install: nasty
-	cp nasty /usr/bin
+	mkdir -p $(DESTDIR)/usr/bin
+	cp nasty $(DESTDIR)/usr/bin
 
 clean:
 	rm -f $(OBJS) nasty core
