post_install() {
    # update icon cache
    gtk-update-icon-cache -fq /usr/share/icons/Bamboo-zen
}

post_upgrade() {
	# directory name changed from bamboo-zen to Bamboo-zen
	if [ -d /usr/share/icons/bamboo-zen ]; then
   	rm -rf /usr/share/icons/bamboo-zen
	fi
    # update icon cache
    gtk-update-icon-cache -fq /usr/share/icons/Bamboo-zen
}

pre_remove() {
    rm -f /usr/share/icons/Bamboo-zen/icon-theme.cache
}

