
post_install() {

  /bin/cat <<EOF

****************************************************************************
*                                                                          *
*    Install 'streamripper' and/or 'mplayer' to make this script work!     *
*                                                                          *
****************************************************************************

EOF
}

post_upgrade() {
  post_install
}
