#!/usr/bin/bash -l

# Bootstrap X
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Start GNOME daemons
/usr/lib/gnome-settings-daemon/gnome-settings-daemon &
/usr/lib/notification-daemon-1.0/notification-daemon &
/usr/lib/gnome-settings-daemon/gnome-fallback-media-keys-helper &
/usr/lib/gnome-settings-daemon/gnome-fallback-background-helper &
/usr/bin/gnome-screensaver &
/usr/bin/nm-applet &
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)

# Export Keyring variables
export SSH_AUTH_SOCK
export GPG_AGENT_INFO
export GNOME_KEYRING_CONTROL
export GNOME_KEYRING_PID

# Nicer, less sticky pointer
unclutter -idle 1 -jitter 10 -root &
xsetroot -cursor_name 'left_ptr' &

sleep 1 && exec xmonad

