#!/usr/bin/bash -l

# Start GNOME daemons
/usr/lib/gnome-settings-daemon/gnome-settings-daemon &
/usr/lib/notification-daemon-1.0/notification-daemon &
gnome-screensaver &

# Start GNOME Keyring
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export SSH_AUTH_SOCK
export GPG_AGENT_INFO
export GNOME_KEYRING_CONTROL
export GNOME_KEYRING_PID

nm-applet &

unclutter -idle 1 -jitter 10 -root &
xsetroot -cursor_name 'left_ptr' &

sleep 1 && xmonad
