# generated by the gambas3 ide
# Maintainer : Luca D'Isanto <lukadisanto@gmail.com>

pkgname=vpnc-qt
_realname=vpnc-qt
pkgdesc="Graphical interface for vpnc (client VPN Cisco compatible)"
pkgver=2.1.1
pkgrel=1
arch=('any')
url="https://sourceforge.net/projects/vpnc-gui/"
changelog=ChangeLog
license=('custom')
depends=('gambas3-gb-image>=3.5' 'gambas3-gb-image<=3.99.0' 'gambas3-gb-qt4>=3.5' 'gambas3-gb-qt4<=3.99.0' 'gambas3-gb-form>=3.5' 'gambas3-gb-form<=3.99.0' 'gambas3-gb-desktop>=3.5' 'gambas3-gb-desktop<=3.99.0' 'gambas3-gb-qt4-ext>=3.5' 'gambas3-gb-qt4-ext<=3.99.0' 'sudo' 'vpnc' 'gambas3-ide' 'gambas3-runtime')
makedepend=('gambas3-devel')
source=(${_realname}-$pkgver.tar.bz2 license.txt\
        'vpnc-qt.desktop' 'vpnc-qt.png')
md5sums=('c5dfae5336409d6920b415223e92cf28'
         '35403466a659acad9657584fb79a6020'
         'bbe9bbcb03c9a394db1380d668331121'
         '9a8fea28b71220ffdf905c45b0f015d3')

build() {
  cd ${srcdir}/${_realname}

  /usr/bin/gbc3 -e -a -g -p -m -x  && gba3
}

package() {
  cd ${srcdir}/${_realname}

  install -d ${pkgdir}/usr/bin
  install -m755 vpnc-qt.gambas ${pkgdir}/usr/bin/vpnc-qt
  install -D ../vpnc-qt.png \
    ${pkgdir}/usr/share/pixmaps/vpnc-qt.png
  install -D ../vpnc-qt.desktop \
    ${pkgdir}/usr/share/applications/vpnc-qt.desktop
  install -Dm644 ${srcdir}/license.txt ${pkgdir}/usr/share/licenses/vpnc-qt/license.txt
}
