.TH pacgem 8  "February 6, 2010" "version 0.1" "Arch Linux"
.SH NAME
pacgem \- Install Ruby Gems using the Arch Linux Package Manager (pacman)
.SH SYNOPSIS
.B pacgem
[options] gems...
.SH DESCRIPTION
Pacgem allows direct installation of ruby gems under Arch Linux.
It generates a temporary PKGBUILD which is converted to a package file.
The package file is installed using `sudo pacman`.
.TP
\-d, \-\-destdir DIR
Destination directory for package files
.PP
\-n, \-\-noinstall
       Do not install package files
.PP
\-\-noautodepends
       Disable automatic dependency generation for shared objects (*.so)
.PP
\-\-nocolor
       Disable colored output
.PP
\-\-trace
       Show a full traceback on error
.PP
\-h, \-\-help
       Show help message
.SH EXAMPLES
.TP
pacgem --noinstall rake    Create ruby-rake package in the directory ./ruby-rake
.PP
pacgem rake-1.0            Create temporary ruby-rake package and install it
.PP
pacgem 'rake>1.0'          Different version specification
.PP
pacgem thin 'rake~>1.0'    Different version specification
.PP
.SH AUTHOR
Daniel Mendler (mail at daniel-mendler.de)
.SH SEE ALSO
pacman(8)


