.TH pacgem 8  "February 6, 2010" "version 0.1" "Arch Linux"
.SH NAME
pacgem \- Install Ruby Gems using the Arch Linux Package Manager (pacman)
.SH SYNOPSIS
.B pacgem
[options] gems...
.SH DESCRIPTION
Pacgem allows direct installation of ruby gems under Arch Linux.
It generates a temporary PKGBUILD which is converted to a package file.
The package file is installed using `sudo pacman`.
.TP
\-d, \-\-destdir DIR
Destination directory for package files
.PP
\-n, \-\-noinstall
       Do not install package files
.PP
\-\-trace
       Show a full traceback on error
.PP
\-h, \-\-help
       Show help message
.SH EXAMPLES
.TP
pacgem --noinstall rack    Create ruby-rack package in the directory ./ruby-rack
.PP
pacgem rack-1.0            Create temporary ruby-rack package and install it
.PP
pacgem 'rack>1.0'          Different version specification
.PP
pacgem thin 'rack~>1.0'    Different version specification
.PP
.SH AUTHOR
Daniel Mendler (mail at daniel-mendler.de)
.SH SEE ALSO
pacman(8)


