# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=rspec
pkgname=ruby-$_gemname-2
pkgver=2.99.0
pkgrel=1
pkgdesc='rspec-2.99.0'
arch=(any)
url='http://github.com/rspec'
license=(MIT)
depends=(ruby ruby-rspec-core-2 ruby-rspec-expectations-2 ruby-rspec-mocks-2)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('0a609299795f06ec771fd882f07b76b2260161be')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/License.txt" "$pkgdir/usr/share/licenses/$pkgname/License.txt"
}
