#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions


PID=`pidof -o %PPID /usr/sbin/esets_daemon`
case "$1" in
  start)
    stat_busy "Starting ESET security for linux"
    [ -z "$PID" ] && /usr/sbin/esets_daemon
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon esets
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping ESET security for linux"
    [ ! -z "$PID" ] && kill -TERM $PID &> /dev/null
    if [ $? -gt 0 ]; then
        stat_fail
    else
      rm_daemon esets
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  reload)
    stat_busy "Reloading ESET security for linux"
    [ ! -z "$PID" ] && kill -HUP $PID &> /dev/null
    if [ $? -gt 0 ]; then
        stat_fail
    else
      stat_done
    fi
    ;;
  force-reload)
    stat_busy "Force-reloading ESET security for linux"
    [ ! -z "$PID" ] && kill -USR1 $PID &> /dev/null
    if [ $? -gt 0 ]; then
        stat_fail
    else
      stat_done
    fi
    ;;
  *)
    echo "usage: $0 {start|stop|restart|reload|force-reload}"  
esac
exit 0
# vim: ts=2 sw=2 et ft=sh
