# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>
# Contributor: Alfredo Palhares <masterkorp@masterkorp.net>

_gemname=gssapi
pkgname=ruby-$_gemname-1.0.0
pkgver=1.0.0
pkgrel=2
pkgdesc='A FFI wrapper around the system GSSAPI library.'
arch=(any)
url='http://github.com/zenchild/gssapi'
license=(MIT)
depends=(ruby ruby-ffi)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('beeabdcb692ce18c3cac637e7fc6fc1b28534d97')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/COPYING.txt" "$pkgdir/usr/share/licenses/$pkgname/COPYING.txt"
}
