post_upgrade() {
  ln -s /usr/lib/5.1/luatrace /usr/lib/5.2/luatrace
  cd /usr/share/lua/5.2
  ln -s ../5.1/jit .
  ln -s ../5.1/uatrace .
  ln -s ../5.1/luatrace .
  ln -s ../5.1/uatrace.lua .
  ln -s ../5.1/luatrace.lua .
}

post_install() {
  post_upgrade
}

post_remove() {
  rm -f /usr/lib/5.2/luatrace  	
  rm -rf /usr/share/5.2/luatrace  	
  rm -rf /usr/share/5.2/uatrace  	
  rm -f /usr/share/5.2/luatrace.lua  	
  rm -f /usr/share/5.2/uatrace.lua  	
  rm -f /usr/share/5.2/jit
}
