*** makefile	2013-05-23 00:01:36.000000000 +0900
--- makefile2	2013-09-29 11:44:37.106789405 +0900
***************
*** 94,102 ****
  #
  
  
! CC    = mpicc -openmp -O3 -I/usr/local/include
! FC    = mpif90 -openmp -O3 -I/usr/local/include
! LIB   = -L/usr/local/lib -lfftw3 -llapack -lblas -lg2c -static
  
  
  
--- 94,102 ----
  #
  
  
! CC = mpicc -fopenmp -O3 -I/usr/include
! FC = mpif90 -fopenmp -O3 -I/usr/include
! LIB = -L/usr/lib -lfftw3 -lblas -llapack -lmpi_f77 -lmpi_f90 -lgfortran
  
  
  
***************
*** 474,480 ****
  Divide_Conquer_Dosout.o: Divide_Conquer_Dosout.c openmx_common.h
  	$(CC) -c Divide_Conquer_Dosout.c
  Krylov.o: Krylov.c openmx_common.h
! 	$(CC) -c Krylov.c
  #
  #
  #
--- 474,480 ----
  Divide_Conquer_Dosout.o: Divide_Conquer_Dosout.c openmx_common.h
  	$(CC) -c Divide_Conquer_Dosout.c
  Krylov.o: Krylov.c openmx_common.h
! 	$(CC) -c Krylov.c -msse -msse2 -msse3
  #
  #
  #
