--- Stx/Makefile	2007-02-01 14:03:48.000000000 +0100
+++ Makefile	2008-10-30 11:37:56.000000000 +0100
@@ -13,7 +13,7 @@ MSGDIR=$(LIBDIR)/messages
 EMACSDIR=$(BASE)/share/emacs/site-lisp
 SCRIPTS=stx2any strip_stx gather_stx_titles html2stx extract_usage_from_stx
 MANPAGES:=$(SCRIPTS:=.1)
-MESSAGES:=$(SCRIPTS:=.usage) version.msg
+MESSAGES:=$(SCRIPTS:=.usage) # version.msg
 INST_SCRIPTS=$(SCRIPTS:=.inst)
 DOCDIR=$(BASE)/share/doc/stx2any
 DOCBASE:=stx2any Stx-doc Stx-ref strip_stx gather_stx_titles html2stx \
@@ -50,7 +50,7 @@ else
 	./scripts/extract_usage_from_stx $< >$@
 endif
 
-version.msg: debian/changelog
+version.msg:
 	sed -e 's#^\([^(]*\)(\([^)]*\)).*#\1\2#' -e '1q' $< >$@
 
 %.m4: %.lm4 
