#!/usr/bin/env python
#
# pacfix.py: a script by pierluigi to list all the packages currently installed according to /var/log/pacman.log
#            2008-07-04: Modified by Chris Giles to prevent failure when "pacman.log" has lines with only two words


pkg=[]

logfile = open("/var/log/pacman.log","r")
log=logfile.readlines()
for myline in log:
    myarray = myline.strip("\n").split(" ")
    if len(myarray) >= 3 :
        if (myarray[2]=="installed" or myarray[2]=="upgraded"):
            if (pkg.count(myarray[3])==0):
                pkg.append(myarray[3])
        if (myarray[2]=="removed"):
            if (pkg.count(myarray[3])!=0):
                pkg.remove(myarray[3])
pkg.sort()
for p in pkg:
    print(p)
