.TH archbootstrap-ee 1
.SH NAME
archbootstrap-ee \- Bootstraps a new Arch Linux system
.SH SYNOPSIS
.br
\fBarchbootstrap-ee\fP
\fB--target=\fP\fI<dir>\fP
\fB[--arch=\fP\fI<arch>\fP\fB]\fP
\fB[--mirror=\fP\fI<url>\fP\fB]\fP
\fB[--pkgcache=\fP\fI<dir>\fP\fB]\fP
\fB[--packages=\fP\fI<file>\fP\fB]\fP
.SH DESCRIPTION
Installs a new Arch Linux system using
.BR pacman (8).
The resulting system is completely unconfigured as
.B archbootstrap-ee
basically advises pacman to install all
.B [core]
packages to another location.
.SH OPTIONS
.IP --target=<dir>
Specifies the target directory, may not be unset.
.IP --arch=<arch>
Forces a target architecture. Note that a i686 host can't install a clean x86_64 system as some packages contain installscripts which depend on running binaries.
.IP --mirror=<url>
Points archbootstrap-ee to another mirror. You should always use this option so save bandwith on archlinux.org, which will be the default if no mirror will be specified.
.IP --pkgcache=<dir>
Another cache directory for packages will be used if specified. Will default to /var/cache/pacman/pkg if host and target have the same architecture or *pkg32/64 if they are different.
.IP --packages=<file>
If not specified, archbootstrap-ee will install all packages from \fB[core]\fP. Otherwise, it points to a file containing whitespace seperated package names which will get installed instead.
.SH DIAGNOSTICS
.B archbootstrap-ee
returns 0 on success, non-zero otherwise.
.SH BUGS
No known bugs(yet).
.SH AUTHOR
Lisa Denia <eiffel56@gmail.com>
.SH "SEE ALSO"
.BR pacman (8)