post_install() {
	echo "Gem installation complete please run the appropriate installer for your setup."
	echo ""
	echo "Examples:"
	echo -e "\t /opt/ruby-enterprise/lib/ruby/gems/1.8/bin/passenger-install-apache2-module"
	echo -e "\t /opt/ruby-enterprise/lib/ruby/gems/1.8/bin/passenger-install-nginx-module"
}

post_upgrade() {
	echo "Gem upgrade complete please rerun the appropriate installer for your setup."
	echo ""
	echo "Examples:"
	echo -e "\t /opt/ruby-enterprise/lib/ruby/gems/1.8/bin/passenger-install-apache2-module"
	echo -e "\t /opt/ruby-enterprise/lib/ruby/gems/1.8/bin/passenger-install-nginx-module"
}