# Generated by gem2arch
# Maintainer: LeeF

_gemname=passenger
pkgname=ruby-enterprise-$_gemname
pkgver=3.0.2
pkgrel=0
pkgdesc="Easy and robust Ruby web application deployment"
arch=('i686' 'x86_64')
url="http://www.modrails.com/"
license=('GPL2')
depends=('ruby-enterprise' 'ruby-enterprise-rake>=0.8.1' 'ruby-enterprise-fastthread>=1.0.1' 'ruby-enterprise-daemon-controller>=0.2.5' 'ruby-enterprise-file-tail' 'ruby-enterprise-rack')
makedepends=('ruby-enterprise')
source=(http://gems.rubyforge.org/gems/$_gemname-$pkgver.gem passenger.install)
noextract=($_gemname-$pkgver.gem)
md5sums=('791dbca04e65dade1f7a0817d9b7bdf7' 'dc10c44e694feaaaf5bb975e6b5ce038')
install='passenger.install'

build() {
	cd $srcdir
	local _gemdir=`ruby -rubygems -e'puts Gem.default_dir'`
	gem install --ignore-dependencies --no-rdoc --no-ri  -i "$pkgdir$_gemdir" $_gemname-$pkgver.gem
}
