# $Id$
# Maintainer: Julio Castillo  <juliocc@gmail.com>
pkgname=kprof
pkgver=1.4.3
pkgrel=2
pkgdesc="A KDE3 visual tool helping developers to analyze the profiling results generated by code profilers."
license=("GPL")
makedepends=('kdebase')
depends=('gcc')
makedepends=('qt3')
source=(http://dl.sf.net/kprof/$pkgname-$pkgver.tar.bz2)
md5sums=('d2b1286f8fea7eb1d3e67215e07d296f')
install=(kprof.install)
url=(http://kprof.sourceforge.net/)
arch=('i686')

build() {
  cd ${startdir}/src/${pkgname}
  patch -p1 < ${startdir}/kprof-1.4.3.patch
  patch -p1 < ${startdir}/kprof-gcc43.patch
  ./configure --prefix=/usr
  make || return 1
  make DESTDIR=${startdir}/pkg install
}
