post_install() {
	echo "To configure this daemon edit /etc/conf.d/distccd-raspi.conf"
	echo "Example: DISTCC_ARGS="--user nobody --allow 127.0.0.1 --allow 192.168.0.0/24""
	echo "This service will conflict classic distccd, so please stop it before running."
	echo "To start it use: systemctl start distccd-raspi"

	echo "For more info visit ArchLinux wiki: https://wiki.archlinux.org/index.php/Distcc"
}