# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Contributor: Balló György <ballogyor+arch at gmail dot com>

_gemname=gobject-introspection
pkgname=ruby-$_gemname
pkgver=2.2.4
pkgrel=1
pkgdesc='Ruby/GObjectIntrospection is a Ruby binding of GObjectIntrospection.'
arch=(i686 x86_64)
url='http://ruby-gnome2.sourceforge.jp/'
license=(LGPL2.1)
depends=(ruby-glib2 gobject-introspection-runtime)
makedepends=(gobject-introspection)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('cda3de014da77ff150ff7227e5d5c49c74320361')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
