post_install() {
  echo ""
  echo "[+] run '/usr/bin/maltego' to call the application (make SURE 'java' is in your \$PATH)"
  echo ">>> documentation resides @ '/usr/share/maltego/doc/M3GuideGUI.pdf', also check online @ 'https://www.paterva.com/web6/documentation/'"
  echo ""
  echo ">>> this application is non-functional until you obtain a Maltego Community Edition activation code and account"
  echo ">>> REGISTER a FREE ACCOUNT for Maltego Community Editon @ 'https://www.paterva.com/web6/community/maltego/'"
  echo ""
}
