_svc="postgresql"
_rlvl="default"

post_install() {
	local datadir="/var/lib/data"
	local _usr="postgres"
	local _grp=$_usr
	echo "	==> requires $_usr user"
	echo "	==> requires $_grp group"
	echo "	==> requires datadir $datadir"
	echo "	==> run as user $_usr: 'initdb -D $datadir'"
	_cmd="rc-update add ${_svc} ${_rlvl}"
	echo "	==> run '${_cmd}'"
}

post_upgrade() {
	post_install "$1"
}

post_remove() {
	_cmd="rc-update del ${_svc} ${_rlvl}"
	echo "	==> run '${_cmd}'"
}
