# Install file for brother-ql700-cupswrapper

post_install() {
	ln -s /opt/brother/PTouch/ql700/{inf,lpd} /usr/share/brother/PTouch/ql700/.
	/usr/share/brother/PTouch/ql700/cupswrapper/cupswrapperql700pt1
	systemctl restart cups
}

pre_remove() {
	/usr/share/brother/PTouch/ql700/cupswrapper/cupswrapperql700pt1 -e
}

post_remove() {
	rm /usr/share/brother/PTouch/ql700/{inf,lpd}
	systemctl restart cups
}

