## arg 1:  the new package version
post_install() {
  echo ""
  echo "Don't forget to run 'nautilus -q' to reload your nautilus before attempting to use this extension."
  echo "If after an upgrade this extensioin doesn't work, try reinstalling pyexiv2."
  echo ""
}

## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
  post_install $1
}

## arg 1:  the old package version
post_remove() {
  post_install $1
}
