Index: Makefile.Linux
===================================================================
--- Makefile.Linux	(revision 631)
+++ Makefile.Linux	(working copy)
@@ -3,9 +3,7 @@
 DEPS = $(addsuffix .d,$(basename $(CSRCS) $(CCSRCS) ))
 OBJS = $(addsuffix .o,$(basename $(CSRCS) $(CCSRCS) ))
 
-CCOPTS = -Wall -O0 -g
-
-PYTHONVER     = 2.6
+PYTHONVER     = 2.7
 EXTRAFMWKS    = -lX11 -lGL -lGLU -lSDL -lGLEW
 EXTRALIBS     = -lpython$(PYTHONVER)
 EXTRADEFINES  =
@@ -16,19 +14,19 @@
 	
 %.o : %.c
 	@echo "compiling C file $< to $@ ..."
-	@gcc -c -MMD $(CCOPTS) $(INCLUDEPATH) $< -o $@
+	@gcc -c -MMD $(CFLAGS) $(INCLUDEPATH) $< -o $@
 
 %.o : %.cpp
 	@echo "compiling C file $< to $@ ..."
-	@g++ -c -MMD $(CCOPTS) $(INCLUDEPATH) $< -o $@
+	@g++ -c -MMD $(CXXFLAGS) $(INCLUDEPATH) $< -o $@
 
 %.o : %.m
 	@echo "compiling ObjC file $< to $@ ..."
-	@gcc -c -MMD $(CCOPTS) $(INCLUDEPATH) $< -o $@
+	@gcc -c -MMD $(CFLAGS) $(INCLUDEPATH) $< -o $@
 
 %.o : %.mm
 	@echo "compiling ObjC++ file $< to $@ ..."
-	@g++ -c -MMD $(CCOPTS) $(INCLUDEPATH) $< -o $@
+	@g++ -c -MMD $(CXXFLAGS) $(INCLUDEPATH) $< -o $@
 
 $(EXE) : $(OBJS)	
 	@echo "linking as $@ ."
