#!/bin/bash

. /etc/rc.d/functions
SWCLOCK_STATE=/var/lib/swclock.state

case "$1" in
	start)
		if [ ! -f "$SWCLOCK_STATE" ]; then
			echo "Cannot load swclock state: $SWCLOCK_STATE is missing!" >&2
			stat_fail
			exit 1
		fi
		stat_busy "Loading time from file $SWCLOCK_STATE"
		state=$(cat SWCLOCK_STATE)
		if date -s "$state" ; then
			stat_done
		else
			stat_fail
		fi
		;;
	stop)
		stat_busy "Writing time to file $SWCLOCK_STATE"
		if date > $SWCLOCK_STATE ; then
			stat_done
		else
			stat_fail
		fi
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "usage: $0 {start|stop|restart}"
esac
exit 0
