diff --git a/src/makefile b/src/makefile
index 0302da1..0a85b3e 100644
--- a/src/makefile
+++ b/src/makefile
@@ -19,7 +19,10 @@ DEBUGFLAGS=
 STRIP=-s
 endif
 
-CFLAGS = -DXP_UNIX -DX86_LINUX $(DEBUGFLAGS)
+ JSFLAGS = -I/usr/include/js -DXP_UNIX
+
+%.o: %.c
+	$(CC) $(CFLAGS) $(JSFLAGS) -c -o $@ $<
 
 #  Normal load flags
 LFLAGS = $(STRIP)
@@ -47,11 +50,11 @@ EBOBJS = main.o buffers.o url.o auth.o http.o sendmail.o fetchmail.o \
 $(EBOBJS) : eb.h eb.p messages.h tcp.h
 
 edbrowse: $(EBOBJS) tcp.o dbstubs.o
-	cc $(LFLAGS) -o edbrowse $(EBOBJS) tcp.o dbstubs.o $(LIBS)
+	$(CC) $(LDFLAGS) -o edbrowse $(EBOBJS) tcp.o dbstubs.o $(LIBS)
 
 #  You probably need to be root to do this.
 install:
-	install -Dm755 edbrowse $(bindir)/edbrowse
+	install -Dm755 edbrowse $(DESTDIR)$(bindir)/edbrowse
 
 #  If you had to build the javascript library yourself,
 #  link it into /usr/lib.
@@ -75,7 +78,7 @@ edbrowseinf: $(EBOBJS) tcp.o dbops.o dbinfx.o
 
 #  odbc access
 edbrowseodbc: $(EBOBJS) tcp.o dbops.o dbodbc.o
-	cc $(LFLAGS) -o edbrowseodbc $(EBOBJS) tcp.o dbops.o dbodbc.o $(LIBS) -lodbc
+	$(CC) $(LDFLAGS) -o edbrowseodbc $(EBOBJS) tcp.o dbops.o dbodbc.o $(LIBS) -lodbc
 
 #  Build function prototypes.
 #  mkproto is my program, not a general unix utility.
