--- gnapi-0.2.2/Makefile	2011-03-22 18:25:50.000000000 +0100
+++ gnapi-0.2.2m/Makefile	2011-12-21 21:41:17.280144568 +0100
@@ -21,7 +21,7 @@
 DESTDIR? =
 CFLAGS += -g -Wall -O2 -Wformat-security `pkg-config --cflags gtk+-2.0 gconf-2.0 gnome-vfs-2.0 libsoup-2.4 gmodule-2.0 libnautilus-extension`
 STRIP = strip --strip-unneeded
-GFLAGS = `pkg-config --libs gtk+-2.0 gconf-2.0 gnome-vfs-2.0 libsoup-2.4 gmodule-2.0` -lnotify -lavformat
+GFLAGS = `pkg-config --libs gtk+-2.0 gconf-2.0 gnome-vfs-2.0 libsoup-2.4 gmodule-2.0` -lnotify -lavformat -ldl -lavcodec
 NFLAGS = `pkg-config --libs gtk+-2.0 gconf-2.0 libsoup-2.4`
 OSFLAGS = `pkg-config --libs gtk+-2.0 libsoup-2.4` -fPIC
 NAUTFLAGS = `pkg-config --libs libnautilus-extension gtk+-2.0` -fPIC
