# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol dot pomozov at gmail dot com>

_gemname=tarantool-record
pkgname=ruby-$_gemname
pkgver=0.4.3
pkgrel=1
pkgdesc='Tarantool KV-storage ActiveModel-aware Record.'
arch=(any)
url='https://github.com/mailru/tarantool-ruby'
license=(BSD-2-Clause)
depends=(ruby ruby-tarantool ruby-activemodel)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('6c18eef71025b7a77c2d830d5d3e4f09698f2553')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
