--- Makefile	2013-04-15 21:33:15.000000000 +0200
+++ Makefile1	2014-01-25 14:32:08.442049283 +0100
@@ -38,13 +38,13 @@
 
 # install CSparse
 install:
-	$(CP) Lib/libcxsparse.a $(INSTALL_LIB)/libcxsparse.$(VERSION).a
-	( cd $(INSTALL_LIB) ; ln -sf libcxsparse.$(VERSION).a libcxsparse.a )
-	$(CP) Include/cs.h $(INSTALL_INCLUDE)
-	chmod 644 $(INSTALL_LIB)/libcxsparse*.a
-	chmod 644 $(INSTALL_INCLUDE)/cs.h
+	$(CP) Lib/libcxsparse.a $(DESTDIR)/$(INSTALL_LIB)/libcxsparse.$(VERSION).a
+	( cd $(DESTDIR)/$(INSTALL_LIB) ; ln -sf libcxsparse.$(VERSION).a libcxsparse.a )
+	$(CP) Include/cs.h $(DESTDIR)/$(INSTALL_INCLUDE)
+	chmod 644 $(DESTDIR)/$(INSTALL_LIB)/libcxsparse*.a
+	chmod 644 $(DESTDIR)/$(INSTALL_INCLUDE)/cs.h
 
 # uninstall CSparse
 uninstall:
