post_install() {

  /bin/cat << EOF

To install this applet do the following:

- In cinnamon-settings disable the 'Window Icon List' applet
and select 'Window list with windows preview'

- To make it appear on the left side of the panel, open 'dconf-editor'
and scroll to 'org/cinnamon/enabled-applets' and find
'panel1:right:0:windowPreviewWindowList@dalcde' or similar entry,
and change the :right: to :left:
EOF
}
