# arg 1:  the new package version
post_install() {
        echo 'You can download PDF sets with the "lhapdf" command like:'
        echo '    $ lhapdf ls'
        echo '    $ sudo lhapdf get CT10'
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
        echo 'You have to update your manually downloaded PDF sets with the "lhapdf" command like:'
        echo '    $ lhapdf ls'
        echo '    $ sudo lhapdf get --upgrade CT10'
}
