# Generated by Xyne::Arch::CPAN 0.07

pkgname=perl-biblio-endnotestyle
pkgver=0.05
pkgrel=1
pkgdesc="reference formatting using Endnote-like templates"
arch=('i686' 'x86_64')
url="http://search.cpan.org/dist/Biblio-EndnoteStyle/"
license=('unknown')
source=('http://search.cpan.org/CPAN/authors/id/M/MI/MIRK/Biblio-EndnoteStyle-0.05.tar.gz')
md5sums=('282a4d0e0e70ac5c9775216b55164861')
sha256sums=('44b46523f862659a3de2f5b0d95ee86cb70ab34e7dfcec274c7d60ddf7e65345')
makedepends=('perl-extutils-makemaker')
depends=()
options=(!emptydirs)

build() {
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Makefile.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor || return 1
    make  || return 1
    make install DESTDIR="${pkgdir}" || return 1

  else
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Build.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Build.PL INSTALLDIRS=vendor || return 1
    ./Build  || return 1
    ./Build install destdir=${pkgdir} || return 1

  else
    echo "error: failed to detect build method for $pkgname"
    echo "you may be able to fix this by editing the PKGBUILD"
    return 1
  fi fi

  # remove perllocal.pod and .packlist
  find ${pkgdir} -name perllocal.pod -delete
  find ${pkgdir} -name .packlist -delete
}

# vim:set ts=2 sw=2 et:

