--- Makefile.orig	2009-01-19 16:11:33.000000000 +0100
+++ Makefile	2011-03-28 10:43:59.000000000 +0200
@@ -8,7 +8,7 @@
 # (at your option) any later version.
 
 DESTDIR	=
-prefix	= /usr/local
+prefix	= /usr
 bindir	= $(prefix)/bin
 sbindir	= $(prefix)/sbin
 mandir	= $(prefix)/share/man
