post_install() {
    glib-compile-schemas /usr/share/glib-2.0/schemas
    update-desktop-database -q
    gtk-update-icon-cache -q -t -f usr/share/icons/hicolor/
    gtk-update-icon-cache -q -t -f usr/share/icons/HighContrast
}

pre_upgrade() {
    if [ -f /usr/share/gconf/schemas/meld.schemas ]; then
        gconfpkg --uninstall meld
    fi
}

post_upgrade() {
    post_install $1
}

post_remove() {
    post_install $1
}
