--- a/makefile.gnu	2012-07-28 17:42:21.000000000 +0200
+++ b/makefile.gnu	2012-08-28 18:58:28.000000000 +0200
@@ -15,14 +15,11 @@
 HG = hg
 LINK = ln
 INSTALL = install
-PYTHON = python # NB. we use python-foo, since hg implies python
+PYTHON = python2
 RM = rm -fr
 
 # Set up project name and version
 project := eihort
-version := $(shell $(HG) log -r . --template '{latesttag}' | \
-  $(PYTHON) -c 'import re, sys; \
-    print re.sub(r"^\s*v", "", sys.stdin.read()).strip();')
 
 # Figure out system and machine
 system := $(shell $(PYTHON) -c 'import platform; \
@@ -112,7 +109,7 @@
 CXXFLAGS += $(SDL_FLAGS)
 
 ifeq ($(system),linux)
-CXXFLAGS += $(shell pkg-config --cflags --libs SDL_image glew lua5.1)
+CXXFLAGS += $(shell pkg-config --cflags --libs SDL_image glew lua)
 else
 CXXFLAGS += -lGLEW -lSDL_image -llua
 endif
