post_install() {
  update-desktop-database -q
  
  cat << _EOF
 
==> If you wish to use the Xonotic version from [community] archlinux repo along with this launcher, add
	"/usr/bin/xonotic-sdl -basedir /usr/share/xonotic" or "/usr/bin/xonotic-glx -basedir /usr/share/xonotic"
	as the Xonotic binary path on xonotic-launcher settings.
	    
_EOF
}

post_upgrade() {
  update-desktop-database -q
}

post_remove() {
  update-desktop-database -q
}
