# -*- mode: sh; -*-

note () {
    cat << EOF

==> To start using this package, add the lines below to your .emacs:

    (add-to-list 'load-path "/usr/share/emacs/site-lisp/cc-mode/")
EOF
}

post_install() {
    install-info --name=cc-mode /usr/share/info/cc-mode.info.gz --info-dir=/usr/share/info/
    note
}

pre_remove() {
    install-info --remove /usr/share/info/cc-mode.info.gz --info-dir=/usr/share/info/
}

post_upgrade() {
    note
}
