#!/bin/bash

. /etc/ckboot.conf

/bin/mkdir -p "$hashdir"

rm /tmp/ckboot &> /dev/null

/usr/bin/sha512sum $(find /boot -type f) > "$hashdir/filehash"
/bin/dd if="$mbrdsk" bs=512 count="$mbrblk" 2>/dev/null | /usr/bin/sha512sum > "$hashdir/mbrhash"
