## arg 1:  the new package version
post_install() {
  echo "the executable is called bloom-facebook"
  echo "bloom-facebook config directory is located in ~/Bloom for each user running Bloom"
}

## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
  post_install
}


## arg 1:  the old package version
post_remove() {
  echo "bloom-facebook config directory is located in ~/Bloom and can be removed now."
}

# vim:set ts=2 sw=2 et:
