--- Makefile.orig	2011-01-29 10:50:40.000000000 -0500
+++ Makefile	2011-01-29 10:54:55.000000000 -0500
@@ -2,9 +2,7 @@
 CC=gcc
 PKG=noip-2.1.tgz
 
-PREFIX=/usr/local
-CONFDIR=${PREFIX}/etc
-BINDIR=${PREFIX}/bin
+PREFIX=/usr
 
 # these defines are for Linux
 LIBS=
@@ -21,25 +19,5 @@
 # LIBS=-lsocket -lnsl
 # ARCH=sun
 
-${TGT}: Makefile ${TGT}.c 
-	${CC} -Wall -g -D${ARCH} -DPREFIX=\"${PREFIX}\" ${TGT}.c -o ${TGT} ${LIBS}
-
-install: ${TGT} 
-	if [ ! -d ${BINDIR} ]; then mkdir -p ${BINDIR};fi
-	if [ ! -d ${CONFDIR} ]; then mkdir -p ${CONFDIR};fi
-	cp ${TGT} ${BINDIR}/${TGT}
-	${BINDIR}/${TGT} -C -c /tmp/no-ip2.conf
-	mv /tmp/no-ip2.conf ${CONFDIR}/no-ip2.conf
-
-package: ${TGT}
-	rm  -f *.bak
-	mv ${TGT} binaries/${TGT}-`uname -m`
-	scp a-k:/local/bin/noip2 binaries/noip2-`ssh a-k uname -m`
-	cd ..; tar zcvf /tmp/${PKG} noip-2.0/*
-	scp /tmp/${PKG} a-k:/opt/www/${PKG}
-	rm /tmp/${PKG}
-
-clean: 
-	rm -f *o
-	rm -f binaries/*
-	rm -f ${TGT}
+${TGT}: Makefile ${TGT}.c
+	${CC} -Wall -g -D${ARCH} -DPREFIX=\"${PREFIX}\" -DCONFIG_FILEPATH=\"/etc\" -DCONFIG_FILENAME=\"/etc/no-ip2.conf\" ${TGT}.c -o ${TGT} ${LIBS}
