#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID -x /usr/sbin/mfscgiserv`
case "$1" in
  start)
    stat_busy "Starting MooseFS CGI Web Frontend Daemon"
    if [ -z "$PID" ]; then 
       /usr/sbin/mfscgiserv
    fi
    if [ ! -z "$PID" -o $? -gt 0 ]; then
      stat_fail
    else
      PID=`pidof -o %PPID -x /usr/sbin/mfscgiserv`
      echo $PID > /var/run/mfscgiserv.pid
      add_daemon mfscgiserv
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping MooseFS CGI Web Frontend Daemon"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon mfscgiserv
      rm /var/run/mfscgiserv.pid
      stat_done
    fi
    ;;
  restart)
    $0 stop
    if [ ! -z $PID ]; then
      while ps -p $PID > /dev/null; do sleep 1; done
    fi
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
