post_install() {
  echo ""
  echo "You can find Pixilang code examples here: /usr/share/pixilang/examples"
  echo ""
  echo "More information about pixilang available on this websites:"
  echo "http://www.warmplace.ru/soft/pixilang/"
  echo "http://www.warmplace.ru/forum/"
  echo "http://code.google.com/p/pixilang"
  echo ""
  echo "Pixilang official manual: http://code.google.com/p/pixilang/w/list"
  echo ""
}
