.\" Copyright (c) 2012 Matthias Krüger
.\"
.\" This file is part of pacmanlog2gource
.\"
.\" Pacmanlog2gource is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 1 of the License, or
.\" (at your option) any later version.
.\"
.\" Pacmanlog2gource is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with Freedroid; see the file COPYING. If not, write to the 
.\" Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
.\" MA  02111-1307  USA
.\"
.\"
.\" Process this file with
.\" groff -man -Tascii pacmanlog2gource.1
.\" or
.\" nroff -man pacmanlog2gource.1
.\" or
.\" man -l pacmanlog2gource.1 
.\" 
.\" to test the local copy of the man page source file.
.\" 
.\" See mdoc(7) for further reference.
.\"
.\"
.Dd $Mdocdate: February 22 2011 $
.\" 
.Dt PACMANLOG2GOURCE 1 URM
.Os
.Sh NAME
.Nm pacmanlog2gource
.Nd A bash script to convert a copy of /var/log/pacman.log into a log file allowing later visualization using 'gource'
.\"
.\"
.\"
.Sh SYNOPSIS
.Nm
.Op Fl n c g f a o t i m h d
.\"
.\"
.\"
.Sh DESCRIPTION
pacmanlog2gource is a script (written in bash) to convert a copy of /var/log/pacman.log into a log file allowing later visualisation using the program 'gource'.
The script gets a copy of /var/log/pacman.log into ~/.pacmanlog2gource/ and converts this 'local' log afterwards (the original log isn't modified).
The converted log can be visualized using 'gource'.
There are two kind of logs: the tree-log shows packages in groups (ttf, python, library, xorg etc...).
The pie-log doesn't have the packages grouped.
This looks cluttered but packages that you installed earlier and didn't remove in between are shown in the middle of the screen which may be interesting to watch as well.


.\"
.\"
.\"
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl h
List command-line options.
.\"
.It Fl n
Don't update the log when pacmanlog2gource is started
.\"
.It Fl c
Suppress colors in shell output.
.\"
.It Fl g
Update the log if no further option is given, visualize log using gource afterwards.
.\"
.It Fl f 
Capture a video using ffmpeg (enforces -g).
.\"
.It Fl p 
Use pie-log (default is tree-log).
.\"
.It Fl a
Skip architecture in title.
.\"
.It Fl o
Skip hostname in title.
.\"
.It Fl t
Skip timestamps in title.
.\"
.It Fl i
Show information on pacmanlog2gource.
.\"
.It Fl m
Skip package names.
.\"
.It Fl d
Show debug information (set -x).
.El
.\"
.\"
.\"
.Sh FILES
.Pa $HOME/.pacmanlog2gource/pacman_gource_tree.log
contains the tree-log
 
.Pa $HOME/.pacmanlog2gource/pacman_gource_pie.log
contains the pie log


.Pp
.\"
.\"
.\"
.Sh CONTACT
Feel free to drop any comments and/or questions at
.\"
.Pa https://aur.archlinux.org/packages.php?ID=53027
or
.Pa https://bbs.archlinux.org/viewtopic.php?pid=1082389
.\"
or fork it on github
.Pa https://github.com/matthiaskrgr/pacmanlog2gource
.\"
.\"
.\"
.Sh SEE ALSO
.\"
.Xr gource 1
.Xr ffmpeg 1
.\"
.\"
.\"
.Sh AUTHORS
.Nm
was written by
.An Matthias Krüger
