#! /bin/bash

INSTALLDIR=/usr/share/nxengine
USERDATADIR=$HOME/.nxengine

if [ ! -d "~/.nxengine" ]; then
	rm -rf $USERDATADIR
	mkdir $USERDATADIR
	ln -s $INSTALLDIR/* $USERDATADIR
fi
cd $USERDATADIR
./nx
