
post_install() {
echo "(require 'ac-slime), two AC sources will be defined,"
echo "namely ac-source-slime-simple and ac-source-slime-fuzzy. Simply add"
echo "one of these to your ac-sources list for lisp source buffers."
echo ""
echo "For convenience, the function set-up-slime-ac can be used to modify your"
echo "ac-sources list:"
echo ""
echo "(add-hook 'slime-mode-hook 'set-up-slime-ac)"
}

# vim:set ts=2 sw=2 et:
