post_install() {
  /bin/cat << EOF

 -->
 --> Renouveau create multiple files in current directory.
 --> After finishing tests, make archive from all
 --> output files and send it to this email address:
 -->
 --> renouveau.dumps@gmail.com
 -->
 --> Make sure that screensaver is disabled while running
 --> renouveau tests. Don't move with test window and don't
 --> cover it with mouse cursor or other windows.
 -->

EOF
}

post_upgrade() {
  post_install
}
