post_install() {
  cat << EOF
==> To run this module, add Awesome to ~/.config/noteo/noteo.conf
==> You may wish to delete the Popup module from the list of modules.
-Example:
   module-names = Awesome,
-Important
   You must add a textbox widget named noteo to your awesome bar, like
   textbox noteo {
           text_align = "left"
           align = "right"
           width = "500"
   } 
EOF

}

op=$1
shift
$op $*