pkgname=cinnamon

post_install() {
  glib-compile-schemas usr/share/glib-2.0/schemas
  usr/sbin/gconfpkg --install ${pkgname}
  echo "To abilitate Cinnamon remember to change session with dconf-editor"
  echo "Assign to session-name key in org.gnome.desktop.session the value "cinnamon" "
}

pre_upgrade() {
  pre_remove ${1}
}

post_upgrade() {
  post_install ${1}
}

pre_remove() {
  usr/sbin/gconfpkg --uninstall ${pkgname}
}

post_remove() {
  glib-compile-schemas usr/share/glib-2.0/schemas
}
