pkgname=cinnamon

post_install() {
  glib-compile-schemas usr/share/glib-2.0/schemas
  gconfpkg --install ${pkgname}
  echo "To abilitate Cinnamon you can also assign to session-name" 
  echo "key in org.gnome.desktop.session the value "cinnamon" "
}

pre_upgrade() {
  pre_remove ${1}
}

post_upgrade() {
  post_install ${1}
}

pre_remove() {
  gconfpkg --uninstall ${pkgname}
}

post_remove() {
  glib-compile-schemas /usr/share/glib-2.0/schemas
}
