post_install() {
  echo
  echo "Adding trytond group... "
  groupadd  trytond
  echo
  echo "Adding trytond user... "
  useradd -c "Tryton Server Daemon" -d / -g trytond -s /bin/false trytond

# cat << EOM
#
#Note:
#==> Please don't forget to configure your PostgreSQL database for the program.
#
#EOM
}

post_remove() {
  echo "Removing trytond system user... "
  userdel trytond && echo "trytond [done]"
}

op=$1
shift
[ "$(type -t "$op")" = "function" ] && $op "$@"
