# PKGBUILD generated by pacpan
pkgname=perl-data-entropy
_realname=Data-Entropy
pkgver=0.005
pkgrel=1
pkgdesc="entropy (randomness) management"
arch=(i686 x86_64)
license=('perl')
url="http://search.cpan.org/~zefram/Data-Entropy"
options=(!emptydirs)

depends=('perl>=5.10.1' 'perl-http-headers' 'perl-data-float' 'perl-params-classify' 'perl-crypt-rijndael')
makedepends=('perl>=5.10.1' 'perl-data-float' 'perl-crypt-rijndael')

#provides=('Data-Entropy')
provides=('data-entropy=0.005' 'Data::Entropy::RawSource::CryptCounter=0.005' 'perl-data-entropy-rawsource-cryptcounter=0.005' 'Data::Entropy=0.005' 'perl-data-entropy=0.005' 'Data::Entropy::Algorithms=0.005' 'perl-data-entropy-algorithms=0.005' 'Data::Entropy::RawSource::RandomnumbersInfo=0.005' 'perl-data-entropy-rawsource-randomnumbersinfo=0.005' 'Data::Entropy::Source=0.005' 'perl-data-entropy-source=0.005' 'Data::Entropy::RawSource::RandomOrg=0.005' 'perl-data-entropy-rawsource-randomorg=0.005' 'Data::Entropy::RawSource::Local=0.005' 'perl-data-entropy-rawsource-local=0.005')

source=(http://search.cpan.org/CPAN/authors/id/Z/ZE/ZEFRAM/Data-Entropy-0.005.tar.gz)
md5sums=('633433c01664e73e0e8b8416ed3294c9')

build() {
  _expected_dir="${srcdir}/${_realname}-${pkgver}"
  if [ -d "$_expected_dir" ]; then
    cd "$_expected_dir"
  else
    _expected_dir="${srcdir}/$(bsdtar -t -f $(basename $source) | head -n1)"
    if [ -d "$_expected_dir" ]; then
      cd "$_expected_dir"
    else
      _makefile=$(find $srcdir -iname Makefile.PL)
      if [ ! -z "$_makefile" ]; then
        _expected_dir=$(dirname $_makefile)
        if [ -d "$_expected_dir" ]; then
          cd "$_expected_dir"
        else
          echo "[1;31mERROR[0m unable to detect source directory"
          echo "[1;34m-->[0m this is often due to CPAN's lack of standard naming conventions"
          echo "[1;34m-->[0m it may be possible to fix this by adjusting the build function in the PKGBUILD"
        fi
      fi
    fi
  fi
  # install module in vendor directories.
  PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor || return 1
  make  || return 1
  make install DESTDIR=${pkgdir} || return 1

  # remove perllocal.pod and .packlist
  find ${pkgdir} -name perllocal.pod -delete
  find ${pkgdir} -name .packlist -delete
}

# vim:set ts=2 sw=2 et:

