
post_install() {
    printf '\n  Example configuration located at /usr/share/codepad/codepad.conf\n'
    printf '\n  a configuration file is installed for you at /usr/local/etc/codepad.conf\n'
    printf '\n  Configuration file search path in descending priority:'
    printf '\n    /home/$USER/.codepad.conf'
    printf '\n    /usr/local/etc/codepad.conf'
    printf '\n    /etc/codepad.conf\n\n'
}

