post_install() {
    EXTRAMODULES='extramodules-`uname -r|cut -c -3`-ARCH'
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
    #echo 'In order to use nvidia module, reboot the system.'
}

post_upgrade() {
    EXTRAMODULES='extramodules-`uname -r|cut -c -3`-ARCH'
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
}

post_remove() {
    EXTRAMODULES='extramodules-`uname -r|cut -c -3`-ARCH'
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
}
