post_install() {
    EXTRAMODULES='extramodules-`uname -r`'
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
    #echo 'In order to use nvidia module, reboot the system.'
}

post_upgrade() {
    EXTRAMODULES='extramodules-`uname -r`'
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
}

post_remove() {
    EXTRAMODULES='extramodules-`uname -r`'
    depmod $(cat /usr/lib/modules/$EXTRAMODULES/version)
}
