post_install() {

_trns_name=grub2-btrfs

echo

cat << EOF 

 After installing type the following commands to setup grub2 for BIOS (assuming /dev/sda) in the MBR :-
 
 --------------------------------------------------------------------------------
 sudo modprobe dm-mod
 --------------------------------------------------------------------------------
 sudo ${_trns_name}-install --boot-directory=/boot --no-floppy --recheck /dev/sda
 --------------------------------------------------------------------------------
 sudo cp /etc/grub.d/{unifont.pf2,ascii.pf2} /boot/${_trns_name}/
 --------------------------------------------------------------------------------
 
 To generate a core.img file alone without setting up grub2 in the MBR, add "--grub-setup=/bin/true" to ${_trns_name}-install :-
 
 -------------------------------------------------------------------------------------------------------
 sudo ${_trns_name}-install --grub-setup=/bin/true --boot-directory=/boot --no-floppy --recheck /dev/sda
 -------------------------------------------------------------------------------------------------------
 
 You can then chainload grub2's core.img from grub-legacy as a linux kernel or a multiboot kernel.
 
EOF

echo 
 
}


post_upgrade() {
        post_install
}

