post_install() {
echo "You must have Java 1.5 or later installed first and it"
echo "must be in your PATH. Type 'java -version' at the command"
echo "prompt to check this."

echo "In order to automatically display the results in a browser"
echo "you may have to amend totalvalidatorbasic/default_browser.sh."
echo "Use totalvalidatorbasic/total_validator.sh to run the tool."
}

post_upgrade() {
	post_install
}

post_remove() {
	post_install
}
