post_install() {
  echo -n "Updating GTK+ icon cache..."
  gtk-update-icon-cache -fq -t /usr/share/icons/hicolor

  [ $? -eq 0 ] && echo " Done." || echo " FAILED!"

  echo -n "Updating desktop MIME database..."
  update-desktop-database -q

  echo -n "Updating MIME database..."
  update-mime-database /usr/share/mime

  [ $? -eq 0 ] && echo " Done." || echo " FAILED!"
}

post_upgrade() {
  post_install $1
}

post_remove() {
  post_install $1
}
