# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=fog
pkgname=ruby-$_gemname-1.15.0
pkgver=1.15.0
pkgrel=2
pkgdesc='brings clouds to you'
arch=(any)
url='http://github.com/fog/fog'
license=(MIT)
depends=(ruby ruby-builder ruby-excon-0.25 ruby-formatador ruby-multi_json ruby-mime-types ruby-net-scp ruby-net-ssh ruby-nokogiri ruby-ruby-hmac)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('9a99c1bf46d7c515a8a58f6c3dae72af467f9b13')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  # non-HEAD version should not install any files in /usr/bin
  rm -r "$pkgdir/usr/bin/"
}
