post_install() {
	echo "=> All languages: af,ar,be,bg,bn-IN,ca,cs,cy,da,de,el,en-GB,es-AR,"
  	echo "es-ES,et,eu,fi,fr,fy-NL,ga-IE,gl,gu-IN,he,hu,id,is,it,ja,ka,kn,ko,"
  	echo "ku,lt,mk,mn,mr,nb-NO,nl,nn-NO,pa-IN,pl,pt-BR,pt-PT,ro,ru,si,sk,sl,"
  	echo "sq,sr,sv-SE,te,th,tr,uk,zh-CN,zh-TW"
  	echo "=> Open up firefox32 and go to:"
  	echo "about:config => filter => general.useragent.locale"
  	echo "Change the value by your language (example: fr) and restart firefox"
}

op=$1
shift

$op $*

