pkgname=gimp-elsamuko-plugins
post_install(){
    echo "If you want use Octave plugin then install octave-image package and copy example files from /usr/share/$pkgname/examples/filter_pack to the ~/.gimp-octave"
    echo "Plugin get-curves: the curve will be saved in GIMP's curves folder (~/.gimp-version/curves/) and can be opened by GIMP's color curve tool"
    echo "You can copy example curves from /usr/share/$pkgname/examples/curves to your curves folder."
}
post_upgrade(){
    post_install
}
