post_install() {
	# lpr
	/usr/local/Brother/Printer/dcp365cn/inf/setupPrintcapij dcp365cn -i
	
	# cupswrapper
	/usr/local/Brother/Printer/dcp365cn/cupswrapper/cupswrapperdcp365cn
	
	/etc/rc.d/cups restart
}

post_upgrade() {
	/bin/true
}

pre_remove() {
	# lpr
	/usr/local/Brother/Printer/dcp365cn/inf/setupPrintcapij dcp365cn -e
	
	# cupswrapper
	/usr/local/Brother/Printer/dcp365cn/cupswrapper/cupswrapperdcp365cn -e
}

op=$1
shift

$op "$@"

