post_install() {
	cat << EOF

==> To use your wireless card, AirGTKrack will need root access.
==> This is done by setting up a daemon so you may want to start it by :
==> 	/etc/rc.d/airgtkrack start

==> If you want to start it automatically, add airgtkrack to DAEMONS variable.
==> It can be found into /etc/rc.conf file.

EOF
}

post_upgrade() {
	cat << EOF

==> You may want to restart the running airgtkrack daemon by
==> 	/etc/rc.d/airgtkrack restart

EOF
}

op=$1
shift

$op $*

