# $Id: x86test.install,v 1.7 2008/01/30 14:39:33 travis Exp $
# arg 1:  the new package version
post_install() {
echo "> You might add on entry to you lilo.conf such as,"
echo
echo ">>> image=/boot/x86test/x86test_zImage"
echo ">>>         label=x86test"
echo
echo "> or to GRUB's menu.lst like,"
echo
echo ">>> title x86test"
echo ">>> root (hd0,0)"
echo ">>> kernel /boot/x86test/x86test_zImage"
echo
echo "> substitute the appropoite device for (hd0,0)."

    # Run ldconfig after installation
    #  the makefile wants to do this after make install
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
    post_install $1 
}

post_remove() {
    echo "> You might remove on entry to you lilo.conf such as,"
	echo
	echo ">>> image=/boot/x86test/x86test_zImage"
	echo ">>>         label=x86test"
	echo
	echo "> or to GRUB's menu.lst like,"
	echo
	echo ">>> title x86test"
	echo ">>> root (hd0,0)"
	echo ">>> kernel /boot/x86test/x86test_zImage"
	echo
	echo "> substitute the appropoite device for (hd0,0)."
}

op=$1
shift
$op $*
