#!/bin/bash

# Xwayland-wrapper - Pass options and signals between Xweston and Xwayland

# Check for options file, bail if not found because we were respawned
[ ! -f "$XWAYLAND_OPTS" ] && exit

# Two ugly hacks in one line:
# - Use setsid to prevent being stopped on SIGTT*
# - Restart as interactive shell to allow overriding ignored SIGUSR1
[ "$1" != "--" ] && exec setsid $SHELL -i "$0" -- "$@"
shift

exec 3<$XWAYLAND_OPTS

read xwayland_opts <&3
read xinit_pid <&3

exec 3<&-

rm $XWAYLAND_OPTS
unset XWAYLAND_OPTS

# Parent, send SIGUSR1 to xinit
trap "kill -USR1 $xinit_pid" USR1

(
	# Child, ignore SIGUSR1 to let the X server know to send this signal to us
	trap "" USR1
	exec /usr/bin/Xwayland $xwayland_opts
) &

wait
