#!/bin/bash

# Xwayland-wrapper - Pass options and signals between xinit, Xweston and Xwayland

# Check for options file, bail if not found because we were respawned
[ ! -f "$XWAYLAND_OPTS" ] && exit

# Two ugly hacks in one line:
# - Use setsid to prevent being stopped on SIGTT*
# - Restart in interactive shell to allow overriding ignored SIGUSR1
[ "$1" != "--" ] && exec setsid $SHELL -i "$0" -- "$@"
shift

# Read Xwayland options passed down by Xweston
exec 3<$XWAYLAND_OPTS

read xwayland_opts <&3
read xinit_pid <&3

exec 3<&-

rm $XWAYLAND_OPTS
unset XWAYLAND_OPTS

# If running under xinit, we'll be signaled by Xwayland, need to pass it on
[ -n "$xinit_pid" ] && trap "kill -USR1 $xinit_pid" USR1

(
	# Notify Xwayland whether or not we're running under xinit
	[ -n "$xinit_pid" ] && trap "" USR1
	exec /usr/bin/Xwayland $xwayland_opts
) &

wait
