#!/bin/sh

# Xweston - launch Xwayland hosted by weston

# Choose Weston launcher to use depending on whether we're running under X
if [ -z "$DISPLAY" ]; then
	launcher="weston-launch -- $WESTON_OPTS"
else
	launcher="weston $WESTON_OPTS"
fi

# Let Xwayland-wrapper know the X server options to use
export XWAYLAND_OPTS=$(mktemp)
echo "$*" >> $XWAYLAND_OPTS

# If running under xinit, add parent PID to signal when X server is ready
[ -n "$(trap -p USR1)" ] && echo $PPID >> $XWAYLAND_OPTS

# Finally, launch Weston
exec $launcher
