#!/bin/sh

# Xweston - launch Xwayland hosted by weston

if [ -z "$DISPLAY" ]; then
	launcher="weston-launch -- $WESTON_OPTS"
else
	launcher="weston $WESTON_OPTS"
fi

export XWAYLAND_OPTS=$(mktemp)
echo "$*" >> $XWAYLAND_OPTS
exec $launcher
