# Generated by gem2arch
# Maintainer: LeeF

_gemname=fastthread
pkgname=ruby-enterprise-$_gemname
pkgver=1.0.7
pkgrel=0
pkgdesc="Optimized replacement for thread.rb primitives"
arch=('i686' 'x86_64')
url="http://rubygems.org/gems/fastthread"
license=('Ruby')
depends=('ruby-enterprise')
makedepends=('ruby-enterprise')
source=(http://gems.rubyforge.org/gems/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
md5sums=('16eb06dc3661c89301de6c73c71bb16e')

build() {
  cd $srcdir
  local _gemdir=`ruby -rubygems -e'puts Gem.default_dir'`
  gem install --ignore-dependencies --no-rdoc --no-ri  -i "$pkgdir$_gemdir" $_gemname-$pkgver.gem
}
