let blogit_username=''
let blogit_password=''
let blogit_url='http://url.com/blog/xmlrpc.php'
"let blogit_username=''
"let blogit_password=''
"let blogit_url='http://urltootherblog.com/blog/xmlrpc.php'
