post_install() {
echo '--------------------------------------------------------------------------'
echo 'README'
echo 'https://github.com/tritonas00/system-tar-and-restore/blob/master/README.md'
echo '--------------------------------------------------------------------------'
echo 'QUICK INSTRUCTIONS'
echo
echo 'BACKUP'
echo 'Run as root: backup'
echo
echo 'RESTORE'
echo 'Run as root: restore'
echo '--------------------------------------------------------------------------'
}