post_install() {
echo '--------------------------------------------------------------------------'
echo 'README'
echo 'https://github.com/tritonas00/system-tar-and-restore/blob/master/README.md#about'
echo '--------------------------------------------------------------------------'
echo 'QUICK INSTRUCTIONS'
echo
echo 'BACKUP'
echo 'Run as root: backup.sh'
echo
echo 'RESTORE'
echo 'Run as root: restore.sh'
echo '--------------------------------------------------------------------------'
}