
post_install() {
  echo " ==> Adding user qtss..."
  useradd qtss
  echo " ==> Setting directory permissions..."
  chown -R qtss /var/streaming/
  chown -R qtss /etc/streaming/
  echo " ==> Initializing configuration..."
  /usr/sbin/DarwinStreamingServer -x
  chmod 600 /etc/streaming/streamingserver.xml
  echo ""
  echo " ==> Don't forget to create an admin user with 'qtpasswd'"
  echo " ==> and add him to /etc/streaming/qtgroups"
}

post_upgrade() {
  post_install
}

# vim:set ts=2 sw=2 et:
