lines="

% SUNDIALS Toolbox startup M-file, if it exists.
if ( exist('/usr/share/octave/3.8.2/m/sundialsTB/startup_STB.m','file') )
  source ('/usr/share/octave/3.8.2/m/sundialsTB/startup_STB.m')
end"

post_install() {
  echo "Add the following lines to your .octaverc to activate sundials bindings for octave:" "$lines"
}

post_upgrade() {
  post_install $1
}

post_remove() {
  echo "Remember to remove the following lines from your .octaverc:" "$lines"
}
