--- makefile.old	2013-03-04 23:29:19.944992770 +0100
+++ makefile	2013-03-04 23:29:42.294993205 +0100
@@ -1,7 +1,7 @@
 CC = gcc -pthread
 CFLAGS = -O3 -Wall `sdl-config --cflags`
 BMECONV = bmeconv
-LIBS = -lbme `sdl-config --libs`
+LIBS = -lm -lbme `sdl-config --libs`
 
 all: ../missions/original.blk ../missions/test.blk ../data/bofh.pal	\
 ../data/splash.pal ../data/splash.raw ../data/title.spr			\
