# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qweborf/main.ui'
#
# Created: Mon Mar 28 10:59:11 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(532, 536)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.txtPath = QtGui.QLineEdit(self.tab)
        self.txtPath.setObjectName(_fromUtf8("txtPath"))
        self.horizontalLayout.addWidget(self.txtPath)
        self.cmdClearPath = QtGui.QPushButton(self.tab)
        self.cmdClearPath.setObjectName(_fromUtf8("cmdClearPath"))
        self.horizontalLayout.addWidget(self.cmdClearPath)
        self.cmdOpen = QtGui.QDialogButtonBox(self.tab)
        self.cmdOpen.setMaximumSize(QtCore.QSize(80, 16777215))
        self.cmdOpen.setStandardButtons(QtGui.QDialogButtonBox.Open)
        self.cmdOpen.setObjectName(_fromUtf8("cmdOpen"))
        self.horizontalLayout.addWidget(self.cmdOpen)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.spinPort = QtGui.QSpinBox(self.groupBox_2)
        self.spinPort.setMaximum(65536)
        self.spinPort.setProperty(_fromUtf8("value"), 8080)
        self.spinPort.setObjectName(_fromUtf8("spinPort"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinPort)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.cmbAddress = QtGui.QComboBox(self.groupBox_2)
        self.cmbAddress.setObjectName(_fromUtf8("cmbAddress"))
        self.cmbAddress.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.cmbAddress)
        self.horizontalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.chkTar = QtGui.QCheckBox(self.groupBox_3)
        self.chkTar.setToolTip(_fromUtf8(""))
        self.chkTar.setObjectName(_fromUtf8("chkTar"))
        self.verticalLayout_8.addWidget(self.chkTar)
        self.horizontalLayout_5.addWidget(self.groupBox_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.groupBox = QtGui.QGroupBox(self.tab_2)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.chkDav = QtGui.QCheckBox(self.groupBox)
        self.chkDav.setObjectName(_fromUtf8("chkDav"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.chkDav)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label)
        self.chkEnableAuth = QtGui.QCheckBox(self.groupBox)
        self.chkEnableAuth.setObjectName(_fromUtf8("chkEnableAuth"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.chkEnableAuth)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_2)
        self.txtUsername = QtGui.QLineEdit(self.groupBox)
        self.txtUsername.setEnabled(False)
        self.txtUsername.setObjectName(_fromUtf8("txtUsername"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.txtUsername)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_3)
        self.txtPassword = QtGui.QLineEdit(self.groupBox)
        self.txtPassword.setEnabled(False)
        self.txtPassword.setInputMask(_fromUtf8(""))
        self.txtPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.txtPassword.setObjectName(_fromUtf8("txtPassword"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.txtPassword)
        self.chkWrite = QtGui.QCheckBox(self.groupBox)
        self.chkWrite.setEnabled(False)
        self.chkWrite.setObjectName(_fromUtf8("chkWrite"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.chkWrite)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_7 = QtGui.QLabel(self.tab_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_5.addWidget(self.label_7)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.txtLog = QtGui.QTextBrowser(Form)
        self.txtLog.setOpenExternalLinks(True)
        self.txtLog.setOpenLinks(True)
        self.txtLog.setObjectName(_fromUtf8("txtLog"))
        self.horizontalLayout_4.addWidget(self.txtLog)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.cmdClearLog = QtGui.QPushButton(Form)
        self.cmdClearLog.setObjectName(_fromUtf8("cmdClearLog"))
        self.verticalLayout_6.addWidget(self.cmdClearLog)
        self.cmdAbout = QtGui.QPushButton(Form)
        self.cmdAbout.setObjectName(_fromUtf8("cmdAbout"))
        self.verticalLayout_6.addWidget(self.cmdAbout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.cmdStart = QtGui.QPushButton(Form)
        self.cmdStart.setDefault(True)
        self.cmdStart.setObjectName(_fromUtf8("cmdStart"))
        self.horizontalLayout_2.addWidget(self.cmdStart)
        self.cmdStop = QtGui.QPushButton(Form)
        self.cmdStop.setEnabled(False)
        self.cmdStop.setObjectName(_fromUtf8("cmdStop"))
        self.horizontalLayout_2.addWidget(self.cmdStop)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.cmdClose = QtGui.QDialogButtonBox(Form)
        self.cmdClose.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.cmdClose.setObjectName(_fromUtf8("cmdClose"))
        self.verticalLayout_2.addWidget(self.cmdClose)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label_4.setBuddy(self.txtPath)
        self.label_5.setBuddy(self.spinPort)
        self.label_6.setBuddy(self.cmbAddress)
        self.label_8.setBuddy(self.chkDav)
        self.label_9.setBuddy(self.chkWrite)
        self.label.setBuddy(self.chkEnableAuth)
        self.label_2.setBuddy(self.txtUsername)
        self.label_3.setBuddy(self.txtPassword)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.cmdStop, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.stop_sharing)
        QtCore.QObject.connect(self.cmdStart, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.start_sharing)
        QtCore.QObject.connect(self.cmdOpen, QtCore.SIGNAL(_fromUtf8("clicked(QAbstractButton*)")), Form.select_path)
        QtCore.QObject.connect(self.cmdClose, QtCore.SIGNAL(_fromUtf8("clicked(QAbstractButton*)")), Form.terminate)
        QtCore.QObject.connect(self.cmdAbout, QtCore.SIGNAL(_fromUtf8("clicked()")), Form.about)
        QtCore.QObject.connect(self.cmdClearPath, QtCore.SIGNAL(_fromUtf8("clicked()")), self.txtPath.clear)
        QtCore.QObject.connect(self.cmdClearLog, QtCore.SIGNAL(_fromUtf8("clicked()")), self.txtLog.clear)
        QtCore.QObject.connect(self.chkDav, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.chkWrite.setEnabled)
        QtCore.QObject.connect(self.chkEnableAuth, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.txtPassword.setEnabled)
        QtCore.QObject.connect(self.chkEnableAuth, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.txtUsername.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.txtPath, self.cmdClearPath)
        Form.setTabOrder(self.cmdClearPath, self.cmdOpen)
        Form.setTabOrder(self.cmdOpen, self.spinPort)
        Form.setTabOrder(self.spinPort, self.cmbAddress)
        Form.setTabOrder(self.cmbAddress, self.chkTar)
        Form.setTabOrder(self.chkTar, self.chkDav)
        Form.setTabOrder(self.chkDav, self.chkWrite)
        Form.setTabOrder(self.chkWrite, self.chkEnableAuth)
        Form.setTabOrder(self.chkEnableAuth, self.txtUsername)
        Form.setTabOrder(self.txtUsername, self.txtPassword)
        Form.setTabOrder(self.txtPassword, self.tabWidget)
        Form.setTabOrder(self.tabWidget, self.cmdClearLog)
        Form.setTabOrder(self.cmdClearLog, self.cmdAbout)
        Form.setTabOrder(self.cmdAbout, self.cmdStart)
        Form.setTabOrder(self.cmdStart, self.cmdStop)
        Form.setTabOrder(self.cmdStop, self.cmdClose)
        Form.setTabOrder(self.cmdClose, self.txtLog)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "QWeborf", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Directory to share", None, QtGui.QApplication.UnicodeUTF8))
        self.txtPath.setToolTip(QtGui.QApplication.translate("Form", "Insert here the absolute path of the directory to share", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdClearPath.setText(QtGui.QApplication.translate("Form", "⌫", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Form", "Basic", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Port", None, QtGui.QApplication.UnicodeUTF8))
        self.spinPort.setToolTip(QtGui.QApplication.translate("Form", "Select the port. It must be free and not blocked by a firewall.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Address", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbAddress.setToolTip(QtGui.QApplication.translate("Form", "Select the IP address to bind. Leave the default value if you don\'t know what this means.", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbAddress.setItemText(0, QtGui.QApplication.translate("Form", "Bind to all", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Other", None, QtGui.QApplication.UnicodeUTF8))
        self.chkTar.setText(QtGui.QApplication.translate("Form", "Send directories as tar.gz", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Authentication", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "WebDav", None, QtGui.QApplication.UnicodeUTF8))
        self.chkDav.setToolTip(QtGui.QApplication.translate("Form", "If checked, clients will be able to mount the shared directory as a DAV share.", None, QtGui.QApplication.UnicodeUTF8))
        self.chkDav.setText(QtGui.QApplication.translate("Form", "Enable WebDav", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Form", "Writing", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Authentication", None, QtGui.QApplication.UnicodeUTF8))
        self.chkEnableAuth.setText(QtGui.QApplication.translate("Form", "Enable", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.txtUsername.setToolTip(QtGui.QApplication.translate("Form", "Insert here the desired username", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.txtPassword.setToolTip(QtGui.QApplication.translate("Form", "Insert here the password", None, QtGui.QApplication.UnicodeUTF8))
        self.chkWrite.setToolTip(QtGui.QApplication.translate("Form", "If checked, clients will be able to create directories and write file on the server.", None, QtGui.QApplication.UnicodeUTF8))
        self.chkWrite.setText(QtGui.QApplication.translate("Form", "Allow clients to write files on the server", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "Intermediate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Advanced users are supposed to use the terminal", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Form", "Advanced", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdClearLog.setText(QtGui.QApplication.translate("Form", "⌫", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdAbout.setText(QtGui.QApplication.translate("Form", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdStart.setToolTip(QtGui.QApplication.translate("Form", "Start sharing the directory", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdStart.setText(QtGui.QApplication.translate("Form", "Start sharing", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdStop.setToolTip(QtGui.QApplication.translate("Form", "Stop sharing the directory", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdStop.setText(QtGui.QApplication.translate("Form", "Stop sharing", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdClose.setToolTip(QtGui.QApplication.translate("Form", "Stop sharing and exit the program.", None, QtGui.QApplication.UnicodeUTF8))

