post_upgrade() {
  post_install $1
}

post_install() {
  echo "This JRE package contains licensed software."
  echo "You MUST read and agree to the license stored in /opt/bin32-jre/LICENSE before using it"
  echo ""
  echo "To use this JVM you will need to set up JAVA_HOME in /etc/profile.d/jre.sh,"
  echo "your .bash_profile or in your scripts to point to /opt/bin32-jre directory."
  echo "Also, /opt/bin32-jre/bin needs to be included in your PATH."
}

op=$1
shift

$op $*

