post_upgrade() {
	post_install $1
}

post_install() {
	echo "The jre package is licensed software."
	echo "You MUST read and agree to the license stored in /opt/bin32-jre/jre/LICENSE before using it"
	echo ""
	echo "The new mozilla plugin link is /opt/bin32-jre/jre/lib/i386/libnpjp2.so"
	echo "ln -s /opt/bin32-jre/jre/lib/i386/libnpjp2.so /usr/lib/mozilla/plugins/libnpjp2.so"
}

op=$1
shift

$op $*

