post_install() {
    ln -s /usr/lib/perl5/site_perl/bin/ocsinventory-agent /usr/bin/ocsinventory-agent
    echo "Edit /etc/ocsinventory/ocsinventory-agent.cfg with your server details."
}
pre_upgrade() {
    mv /etc/ocsinventory/ocsinventory-agent.cfg /etc/ocsinventory/ocsinventory-agent.cfg.OLD
}
post_upgrade() {
    mv /etc/ocsinventory/ocsinventory-agent.cfg.OLD /etc/ocsinventory/ocsinventory-agent.cfg
}
