post_install() {
    echo "Please restart Pidgin or change your status for the new icons to take effect."

    mkdir /usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/old/
    mkdir /usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/old/
    mkdir /usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/old/
    mkdir /usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/old/

    cp /usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/*.png /usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/old/
    cp /usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/*.png /usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/old/
    cp /usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/*.png /usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/old/
    cp /usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/*.png /usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/old/

    cp /usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/new/* /usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/
    cp /usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/new/* /usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/
    cp /usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/new/* /usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/
    cp /usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/new/* /usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/

    rm -rf /usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/new/
    rm -rf /usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/new/
    rm -rf /usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/new/
    rm -rf /usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/new/
}

post_remove() {

    cp /usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/old/*.png /usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/
    cp /usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/old/*.png /usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/
    cp /usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/old/*.png /usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/
    cp /usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/old/*.png /usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/

    rm -rf /usr/share/pixmaps/pidgin/tray/hicolor/16x16/status/old/
    rm -rf /usr/share/pixmaps/pidgin/tray/hicolor/22x22/status/old/
    rm -rf /usr/share/pixmaps/pidgin/tray/hicolor/32x32/status/old/
    rm -rf /usr/share/pixmaps/pidgin/tray/hicolor/48x48/status/old/

}
