--- s9/Makefile	2012-10-05 13:29:44.000000000 +0200
+++ s9/Makefile.n	2013-05-02 21:40:49.490263236 +0200
@@ -4,7 +4,7 @@
 # Placed in the Public Domain.
 
 # Change at least this line:
-PREFIX= /u
+PREFIX= /usr
 
 # Uncomment these to include the Unix extensions
 EXTRA_SCM+=	-l ext/unix.scm
@@ -30,9 +30,9 @@
 CFLAGS=	-g -Wall -ansi -pedantic -O2
 
 # Where to install the stuff
-BINDIR=	$(PREFIX)/bin
-LIBDIR=	$(PREFIX)/share/s9fes
-MANDIR=	$(PREFIX)/man/man1
+BINDIR=	$(DESTDIR)$(PREFIX)/bin
+LIBDIR=	$(DESTDIR)$(PREFIX)/share/s9fes
+MANDIR=	$(DESTDIR)$(PREFIX)/share/man/man1
 
