--- s9fes-20090906/Makefile	2009-09-06 06:59:05.000000000 +0000
+++ s9fes-20090906.new/Makefile	2009-09-10 20:00:14.000000000 +0000
@@ -2,7 +2,7 @@
 # Nils M Holm, 2007,2008,2009
 
 # Change at least this line:
-PREFIX= /u
+PREFIX= /usr
 
 VERSION= 20090906
 
@@ -19,7 +19,7 @@
 
 BINDIR=	$(PREFIX)/bin
 LIBDIR=	$(PREFIX)/share/s9fes
-MANDIR=	$(PREFIX)/man/man1
+MANDIR=	$(PREFIX)/share/man/man1
 
 # BITS_PER_WORD_64	use 64-bit bignum arithmetics
 # NO_SIGNALS		disable POSIX signal handlers
@@ -111,36 +111,36 @@
 # old version of install(1) may need -c
 #C=-c
 install:	s9 s9.scm s9.image s9.1.gz
-	install -d -m 0755 $(BINDIR)
-	install -d -m 0755 $(LIBDIR)
-	install -d -m 0755 $(LIBDIR)/contrib
-	install -d -m 0755 $(LIBDIR)/help
-	install -d -m 0755 $(MANDIR)
-	install $C -m 0755 s9 $(BINDIR)
-	strip $(BINDIR)/s9
-	install $C -m 0644 s9.scm $(LIBDIR)
-	install $C -m 0644 s9.image $(LIBDIR)
-	install $C -m 0644 lib/* $(LIBDIR)
-	install $C -m 0644 contrib/* $(LIBDIR)/contrib
-	install $C -m 0644 s9.1.gz $(MANDIR)
-	install $C -m 0644 help/* $(LIBDIR)/help
+	install -d -m 0755 $(DESTDIR)$(BINDIR)
+	install -d -m 0755 $(DESTDIR)$(LIBDIR)
+	install -d -m 0755 $(DESTDIR)$(LIBDIR)/contrib
+	install -d -m 0755 $(DESTDIR)$(LIBDIR)/help
+	install -d -m 0755 $(DESTDIR)$(MANDIR)
+	install $C -m 0755 s9 $(DESTDIR)$(BINDIR)
+	strip $(DESTDIR)$(BINDIR)/s9
+	install $C -m 0644 s9.scm $(DESTDIR)$(LIBDIR)
+	install $C -m 0644 s9.image $(DESTDIR)$(LIBDIR)
+	install $C -m 0644 lib/* $(DESTDIR)$(LIBDIR)
+	install $C -m 0644 contrib/* $(DESTDIR)$(LIBDIR)/contrib
+	install $C -m 0644 s9.1.gz $(DESTDIR)$(MANDIR)
+	install $C -m 0644 help/* $(DESTDIR)$(LIBDIR)/help
 
 install-s9e:	install s9e s9e.scm s9e.image s9e.1.gz
-	install $C -m 0755 s9e $(BINDIR)
-	strip $(BINDIR)/s9e
-	install $C -m 0644 s9e.scm $(LIBDIR)
-	install $C -m 0644 s9e.image $(LIBDIR)
-	install $C -m 0644 ext/unix.scm $(LIBDIR)
-	install $C -m 0644 s9e.1.gz $(MANDIR)
+	install $C -m 0755 s9e $(DESTDIR)$(BINDIR)
+	strip $(DESTDIR)$(BINDIR)/s9e
+	install $C -m 0644 s9e.scm $(DESTDIR)$(LIBDIR)
+	install $C -m 0644 s9e.image $(DESTDIR)$(LIBDIR)
+	install $C -m 0644 ext/unix.scm $(DESTDIR)$(LIBDIR)
+	install $C -m 0644 s9e.1.gz $(DESTDIR)$(MANDIR)
 
 install-s9sc:	install s9sc s9sc.scm s9sc.image sys6x12.vf s9sc.1.gz
-	install $C -m 0755 s9sc $(BINDIR)
-	strip $(BINDIR)/s9sc
-	install $C -m 0644 s9sc.scm $(LIBDIR)
-	install $C -m 0644 sys6x12.vf $(LIBDIR)
-	install $C -m 0644 s9sc.image $(LIBDIR)
-	install $C -m 0644 ext/sc.scm $(LIBDIR)
-	install $C -m 0644 s9sc.1.gz $(MANDIR)
+	install $C -m 0755 s9sc $(DESTDIR)$(BINDIR)
+	strip $(DESTDIR)$(BINDIR)/s9sc
+	install $C -m 0644 s9sc.scm $(DESTDIR)$(LIBDIR)
+	install $C -m 0644 sys6x12.vf $(DESTDIR)$(LIBDIR)
+	install $C -m 0644 s9sc.image $(DESTDIR)$(LIBDIR)
+	install $C -m 0644 ext/sc.scm $(DESTDIR)$(LIBDIR)
+	install $C -m 0644 s9sc.1.gz $(DESTDIR)$(MANDIR)
 
 deinstall:
 	rm $(LIBDIR)/contrib/* && rmdir $(LIBDIR)/contrib
