--- a/Makefile	2010-12-08 08:08:09.000000000 +0000
+++ b/Makefile	2011-10-27 07:58:41.000000000 +0000
@@ -4,7 +4,7 @@
 # Placed in the Public Domain.
 
 # Change at least this line:
-PREFIX= /u
+PREFIX= /usr
 
 # Uncomment these to include the Unix extensions
 EXTRA_SCM+=	-l ext/unix.scm
@@ -32,7 +32,7 @@
 # Where to install the stuff
 BINDIR=	$(PREFIX)/bin
 LIBDIR=	$(PREFIX)/share/s9fes
-MANDIR=	$(PREFIX)/man/man1
+MANDIR=	$(PREFIX)/share/man/man1
 
 # Which OS are we using (unix or plan9)?
 OSDEF=	-Dunix
@@ -110,35 +110,35 @@
 # old version of install(1) may need -c
 #C=-c
 install-s9:	s9 s9.scm s9.image s9.1.gz
-	install -d -m 0755 $(BINDIR)
-	install -d -m 0755 $(LIBDIR)
-	install -d -m 0755 $(LIBDIR)/help
-	install -d -m 0755 $(MANDIR)
-	install $C -m 0755 s9 $(BINDIR)
-	strip $(BINDIR)/s9
-	install $C -m 0644 s9.scm $(LIBDIR)
-	install $C -m 0644 s9.image $(LIBDIR)
-	install $C -m 0644 lib/* $(LIBDIR)
-	install $C -m 0644 ext/*.scm $(LIBDIR)
-	install $C -m 0644 contrib/* $(LIBDIR)
-	install $C -m 0644 s9.1.gz $(MANDIR)
-	install $C -m 0644 help/* $(LIBDIR)/help
-	install $C -m 0755 util/make-help-links $(LIBDIR)/help
-	(cd $(LIBDIR)/help && ./make-help-links && rm make-help-links)
+	install -d -m 0755 $(DESTDIR)$(BINDIR)
+	install -d -m 0755 $(DESTDIR)$(LIBDIR)
+	install -d -m 0755 $(DESTDIR)$(LIBDIR)/help
+	install -d -m 0755 $(DESTDIR)$(MANDIR)
+	install $C -m 0755 s9 $(DESTDIR)$(BINDIR)
+	strip $(DESTDIR)$(BINDIR)/s9
+	install $C -m 0644 s9.scm $(DESTDIR)$(LIBDIR)
+	install $C -m 0644 s9.image $(DESTDIR)$(LIBDIR)
+	install $C -m 0644 lib/* $(DESTDIR)$(LIBDIR)
+	install $C -m 0644 ext/*.scm $(DESTDIR)$(LIBDIR)
+	install $C -m 0644 contrib/* $(DESTDIR)$(LIBDIR)
+	install $C -m 0644 s9.1.gz $(DESTDIR)$(MANDIR)
+	install $C -m 0644 help/* $(DESTDIR)$(LIBDIR)/help
+	install $C -m 0755 util/make-help-links $(DESTDIR)$(LIBDIR)/help
+	(cd $(DESTDIR)$(LIBDIR)/help && ./make-help-links && rm make-help-links)
 
 install-util:	install-arse
 	sed -e "s|^#! /usr/local|#! $(PREFIX)|"	\
-		<prog/s9help.scm >$(BINDIR)/s9help
+		<prog/s9help.scm >$(DESTDIR)$(BINDIR)/s9help
 	sed -e "s|^#! /usr/local|#! $(PREFIX)|"	\
-		<prog/s9resolve.scm >$(BINDIR)/s9resolve
+		<prog/s9resolve.scm >$(DESTDIR)$(BINDIR)/s9resolve
 	sed -e "s|^#! /usr/local|#! $(PREFIX)|"	\
-		<prog/scm2html1.scm >$(BINDIR)/scm2html
+		<prog/scm2html1.scm >$(DESTDIR)$(BINDIR)/scm2html
 	sed -e "s|^#! /usr/local|#! $(PREFIX)|"	\
-		<prog/scmpp.scm >$(BINDIR)/scmpp
-	-chmod +x $(BINDIR)/s9help	\
-		  $(BINDIR)/s9resolve	\
-		  $(BINDIR)/scm2html	\
-		  $(BINDIR)/scmpp
+		<prog/scmpp.scm >$(DESTDIR)$(BINDIR)/scmpp
+	-chmod +x $(DESTDIR)$(BINDIR)/s9help	\
+		  $(DESTDIR)$(BINDIR)/s9resolve	\
+		  $(DESTDIR)$(BINDIR)/scm2html	\
+		  $(DESTDIR)$(BINDIR)/scmpp
 
 arse-core.image: contrib/arse.scm ext/unix.scm ext/curses.scm
 	rm -f arse-core.image
@@ -146,60 +146,60 @@
 		-l contrib/arse.scm -d arse-core.image
 
 install-arse: arse-core.image
-	cp arse-core.image $(LIBDIR)
-	cp contrib/arse.help $(LIBDIR)
+	cp arse-core.image $(DESTDIR)$(LIBDIR)
+	cp contrib/arse.help $(DESTDIR)$(LIBDIR)
 	sed -e "s|^#! /usr/local|#! $(PREFIX)|"	\
 	    -e "s|^#! \(.*\)/s9|#! \1/arse-core|"	\
 	    -e '/arse.scm"/d' \
-		<prog/arse1.scm >$(BINDIR)/arse
-	ln -fs $(BINDIR)/s9 $(BINDIR)/arse-core
-	-chmod +x $(BINDIR)/arse
+		<prog/arse1.scm >$(DESTDIR)$(BINDIR)/arse
+	ln -fs s9 $(DESTDIR)$(BINDIR)/arse-core
+	-chmod +x $(DESTDIR)$(BINDIR)/arse
 
 install-programs:
 	sed -e "s|^#! /usr/local|#! $(PREFIX)|"	\
-		<prog/advgen.scm >$(BINDIR)/advgen
+		<prog/advgen.scm >$(DESTDIR)$(BINDIR)/advgen
 	sed -e "s|^#! /usr/local|#! $(PREFIX)|"	\
-		<prog/c2html1.scm >$(BINDIR)/c2html
+		<prog/c2html1.scm >$(DESTDIR)$(BINDIR)/c2html
 	sed -e "s|^#! /usr/local|#! $(PREFIX)|"	\
-		<prog/cols.scm >$(BINDIR)/cols
+		<prog/cols.scm >$(DESTDIR)$(BINDIR)/cols
 	sed -e "s|^#! /usr/local|#! $(PREFIX)|"	\
-		<prog/dupes.scm >$(BINDIR)/dupes
+		<prog/dupes.scm >$(DESTDIR)$(BINDIR)/dupes
 	sed -e "s|^#! /usr/local|#! $(PREFIX)|"	\
-		<prog/edoc.scm >$(BINDIR)/edoc
+		<prog/edoc.scm >$(DESTDIR)$(BINDIR)/edoc
 	sed -e "s|^#! /usr/local|#! $(PREFIX)|"	\
-		<prog/htmlify.scm >$(BINDIR)/htmlify
+		<prog/htmlify.scm >$(DESTDIR)$(BINDIR)/htmlify
 	sed -e "s|^#! /usr/local|#! $(PREFIX)|"	\
-		<prog/s9hts.scm >$(BINDIR)/s9hts
+		<prog/s9hts.scm >$(DESTDIR)$(BINDIR)/s9hts
 	sed -e "s|^#! /usr/local|#! $(PREFIX)|"	\
-		<prog/soccat.scm >$(BINDIR)/soccat
-	-chmod +x $(BINDIR)/advgen	\
-		  $(BINDIR)/c2html	\
-		  $(BINDIR)/cols	\
-		  $(BINDIR)/dupes	\
-		  $(BINDIR)/edoc	\
-		  $(BINDIR)/htmlify	\
-		  $(BINDIR)/s9hts	\
-		  $(BINDIR)/soccat
+		<prog/soccat.scm >$(DESTDIR)$(BINDIR)/soccat
+	-chmod +x $(DESTDIR)$(BINDIR)/advgen	\
+		  $(DESTDIR)$(BINDIR)/c2html	\
+		  $(DESTDIR)$(BINDIR)/cols	\
+		  $(DESTDIR)$(BINDIR)/dupes	\
+		  $(DESTDIR)$(BINDIR)/edoc	\
+		  $(DESTDIR)$(BINDIR)/htmlify	\
+		  $(DESTDIR)$(BINDIR)/s9hts	\
+		  $(DESTDIR)$(BINDIR)/soccat
 
 deinstall:
-	rm -f $(LIBDIR)/help/* && rmdir $(LIBDIR)/help
-	rm -f $(LIBDIR)/* && rmdir $(LIBDIR)
-	rm -f $(BINDIR)/s9
-	-rmdir $(BINDIR)
-	-rmdir $(MANDIR)
+	rm -f $(DESTDIR)$(LIBDIR)/help/* && rmdir $(DESTDIR)$(LIBDIR)/help
+	rm -f $(DESTDIR)$(LIBDIR)/* && rmdir $(DESTDIR)$(LIBDIR)
+	rm -f $(DESTDIR)$(BINDIR)/s9
+	-rmdir $(DESTDIR)$(BINDIR)
+	-rmdir $(DESTDIR)$(MANDIR)
 
 deinstall-util:
-	rm -f $(BINDIR)/arse		\
-	      $(BINDIR)/s9help		\
-	      $(BINDIR)/s9resolve	\
-	      $(BINDIR)/scm2html	\
-	      $(BINDIR)/scmpp
+	rm -f $(DESTDIR)$(BINDIR)/arse		\
+	      $(DESTDIR)$(BINDIR)/s9help		\
+	      $(DESTDIR)$(BINDIR)/s9resolve	\
+	      $(DESTDIR)$(BINDIR)/scm2html	\
+	      $(DESTDIR)$(BINDIR)/scmpp
 
 deinstall-programs:
-	rm -f $(BINDIR)/advgen		\
-	      $(BINDIR)/dupes		\
-	      $(BINDIR)/htmlify		\
-	      $(BINDIR)/soccat
+	rm -f $(DESTDIR)$(BINDIR)/advgen		\
+	      $(DESTDIR)$(BINDIR)/dupes		\
+	      $(DESTDIR)$(BINDIR)/htmlify		\
+	      $(DESTDIR)$(BINDIR)/soccat
 
 tabs:
 	@find . -name \*.scm -exec grep -l "	" {} \;
