post_upgrade() {
	post_install
}

post_install() {
	echo 
	echo "######################################################################"
	echo "              ATTN : flashplugin-prerelease users"
	echo "          This package is going to be deprecated soon,"
	echo "            please shift to flashplugin-beta instead."     
	echo "######################################################################"
	echo 
}
