post_install() {
	sed -i 's/^[^#]/#&/' /etc/acpi/events/anything
	echo "==> See /etc/acpi/eee.conf for configurable options"
 	echo "==> and add DAEMONS=(... eee ...) to your /etc/rc.conf."
}

post_upgrade() {
	echo "==> Check /etc/acpi/eee.conf for new options every time you update"
 	echo "==> and add DAEMONS=(... eee ...) to your /etc/rc.conf."
	echo "==> You should now restart acpid for the changes to take effect."
}
