#!/bin/bash

# Determine action to pass to rc.d scripts
case "$2" in
	up)
		c=start
	;;
	vpn-up)
		c=start
	;;
	down)
		c=stop
	;;
	vpn-down)
		c=stop
	;;
esac


# Source rc.conf, to get the NET_DAEMONS array
. /etc/rc.conf


# loop through NET_DAEMONS Array. Perform appropriate activity.
for i in ${NET_DAEMONS[@]}
do
	if [ -e "/etc/rc.d/$i" ]; then
		rc.d $c $i
	fi
done

