diff --git a/Makefile b/Makefile
index 825263b..f6bf47d 100644
--- a/Makefile
+++ b/Makefile
@@ -44,9 +44,9 @@ clean: distclean
 	rm -f $(TARGET)
 
 install: $(TARGET)
-	install $(TARGET) $(BINDIR)/$(TARGET)
-	install -d /etc/$(TARGET)
-	install -t /etc/$(TARGET) watches.conf $(TARGET).conf
+	install $(TARGET) $(DESTDIR)/$(BINDIR)/$(TARGET)
+	install -d $(DESTDIR)/etc/$(TARGET)
+	install -t $(DESTDIR)/etc/$(TARGET) watches.conf $(TARGET).conf
 #	-install man/$(TARGET).1 $(MANDIR)/$(TARGET).1
 
 uninstall:
