post_install() {
    /bin/cat << EOF
    ===> In order to run Desura, you have to  be in the 'users' group.
    ===>
EOF

  echo "Updating desktop cache..."
  update-desktop-database -q
  echo "done."
}

post_upgrade() {
  # Delete old files
  rm -f /opt/desura/bin/{desura,bittest,crashdlg}

  echo "Updating desktop cache..."
  update-desktop-database -q
  echo "done."
}

pre_remove() {
  echo "Updating desktop cache..."
  update-desktop-database -q
  echo "done."
}
