post_upgrade() {
    return 0
}

post_install() {
    getent group minisatip &>/dev/null || groupadd -r -g 183 minisatip >/dev/null
    getent passwd minisatip &>/dev/null || useradd -r -u 183 -g minisatip -d /dev/null -s /bin/false minisatip >/dev/null
}

post_remove() {
    getent passwd minisatip &>/dev/null && userdel minisatip >/dev/null
    getent group minisatip &>/dev/null && groupdel minisatip >/dev/null
    return 0
}