# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Bruno Souza (varnion at yandex dot com) 

_gemname=RubyInline
pkgname=ruby-rubyinline
pkgver=3.12.3
pkgrel=1
pkgdesc='Allows you to write foreign code within your ruby code'
arch=(any)
url='http://www.zenspider.com/ZSS/Products/RubyInline/'
license=(MIT)
depends=('ruby' 'ruby-zentest')
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('9971a6154bcd2eebdf06604b65e75dae7e27d8c1')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
