#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
[ -f /etc/conf.d/pvpgn ] && . /etc/conf.d/pvpgn

[ -z "$PVPGN_DAEMONS" ] && PVPGN_DAEMONS=(bnetd d2dbs d2cs)

case "$1" in
	start)
		rc=0
		stat_busy "Starting PVPGN Server"
		for d in ${PVPGN_DAEMONS[@]}; do
			PID=`pidof -o %PPID /usr/sbin/$d`
			[ -z "$PID" ] && /usr/sbin/$d 
			rc=$(($rc+$?))
		done
		if [ $rc -gt 0 ]; then
			stat_fail
		else
			add_daemon pvpgn
			stat_done
		fi
	;;
	stop)
		rc=0
		stat_busy "Stopping PVPGN Server"
		for d in ${PVPGN_DAEMONS[@]}; do
			PID=`pidof -o %PPID /usr/sbin/$d`
			[ -z "$PID" ] || kill $PID &> /dev/null
			rc=$(($rc+$?))
		done
		if [ $rc -gt 0 ]; then
			stat_fail
		else
			rm /var/run/pvpgn/bntrackd.pid &>/dev/null
			rm /var/run/pvpgn/d2cs.pid &>/dev/null
			rm /var/run/pvpgn/d2dbs.pid &>/dev/null
			rm /var/run/pvpgn/bnetd.pid &>/dev/null
			rm_daemon pvpgn
			stat_done
		fi
	;;
	restart)
		$0 stop
		sleep 1
		$0 start
	;;
	*)
		echo "usage: $0 {start|stop|restart}"
esac
exit 0
