post_install() {
	sed "s/#MODULE_VERSION#/${1%%-*}/" -i "/usr/src/rt8192cu-${1%%-*}/dkms.conf"
	dkms install -m rt8192cu -v "${1%%-*}"
}
post_upgrade() {
	post_install "${1}"
}
pre_upgrade() {
	local curver="${2%%-*}"
	# $2 is unset due to a bug. See, https://bugs.archlinux.org/task/32278
	# Query current version using pacman as fallback
	[ -n "$curver" ] || curver=$(pacman -Q dkms-rt8192cu | cut -d' ' -f2)
	pre_remove "${curver}"
}
pre_remove() {
	dkms remove -m rt8192cu -v "${1%%-*}" --all
}
