# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>
# Contributor: Alfredo Palhares <masterkorp@masterkorp.net>

_gemname=knife-spec
pkgname=ruby-$_gemname
pkgver=1.0.0
pkgrel=2
pkgdesc='knife-spec is a knife plugin that automatically generates Chef cookbook specs (tests) stubs.'
arch=(any)
url='https://github.com/sethvargo/knife-spec'
license=('Apache 2.0')
depends=(ruby ruby-chef)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('131e1fbc61bdd4924c3c9517f4c659ad21c10a51')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
