## arg 1:  the new package version
post_install() {
  groupadd headphones &> /dev/null
  useradd -g headphones -d /opt/headphones -s /bin/false headphones &> /dev/null
  chown -R headphones:headphones /opt/headphones
}
## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
  chown -R headphones:headphones /opt/headphones
}
## arg 1:  the old package version
pre_remove() {
  userdel headphones &> /dev/null
  groupdel headphones &> /dev/null
}
