pkgname=pupdatenotifier

post_install() {
  cat << EOM
>>> To allow pupdatenotifier synchronize the databases you must
>>> add the following line at the end of the "/etc/sudoers" file:
>>>   user ALL=(ALL) NOPASSWD: /usr/bin/pacman -Sy
>>>
>>> For system upgrade support the following is also needed:
>>>   user ALL=(ALL) NOPASSWD: /usr/bin/pacman -Su
>>>
>>> Using "visudo" to edit the sudoers file is strongly recommendable.
EOM
}
