post_install() {
  chmod 755 /opt/smartgit-ea/bin/smartgit.sh
  ln -s /opt/smartgit-ea/bin/smartgit.sh /usr/bin/smartgit-ea

  echo "update desktop mime database..."
  update-desktop-database
  gtk-update-icon-cache -f /usr/share/icons/hicolor/
}

post_upgrade() {
	gtk-update-icon-cache -f /usr/share/icons/hicolor/
}

post_remove() {
  rm -rf /opt/smartgit-ea
  unlink /usr/bin/smartgit-ea
  update-desktop-database
  gtk-update-icon-cache -f /usr/share/icons/hicolor/
}
