#!/usr/bin/python
import urllib.request, urllib.error, urllib.parse, re, sys, select, socket

if len(sys.argv) != 2:
  print("Usage: {0} url".format(sys.argv[0]))
  exit(1)

baseUrl = sys.argv[1]

m = re.match("^http://(.*?).wrzuta.pl/audio/(.*?)/", baseUrl)
if not m:
  print("Unable to extract user and key from url")
  exit(1)

user = m.group(1)
key = m.group(2)

url = "http://"+user+".wrzuta.pl/u/"+key
src = urllib.request.urlopen(url).read()

src = str(src, encoding = "utf-8")

m = re.search("'flashSrc', encodeURIComponent\(([a-zA-Z]*)\)\);", src)
if m is None:
  print("Unable to parse page")
  exit(1)

key = m.group(1)

l = ""
name = ""
for line in src.split("\n"):
  if "<title>" in line:
    name = line
  if "var " + key in line:
    l = line
    break

ss = ""
grab = False
for c in l:
  if c == '"':
    grab = not grab
  if grab:
    ss = ss + c

ss = ss.replace('"', "")

m = re.search("<title>([^<]*)</title>", name)
name = m.group(1)

name = name.replace("/", "_")
name = name.replace("..", "_")

print("File: " + name + ".mp3")

f = urllib.request.urlopen(ss)
length = int(f.info()["Content-Length"])

f2 = open(name + ".mp3", "wb")

read = 0
while True:
  buf = f.read(1024 * 200)
  if not buf:
    break
  read += len(buf)
  print("{0:7.2f} of {1:7.2f} KB {2:4.0%}".format(read / 1024, length / 1024, read / length))
  f2.write(buf)

f.close()
f2.close()

print("Done.")
