#!/usr/bin/env bash

# Wrapper version
VERSION=0.1.2

# Log operations to $HOME/.log/
DEBUG=${_DEBUG:-1}
LOGDIR=${_LOGDIR:-"$HOME/.log/"}

# Use the packaged steam runtime (0 OFF, 1 ON)
# Read for details:
#     https://wiki.archlinux.org/index.php/steam#Using_native_runtime
USE_RUNTIME=${_USE_RUNTIME:-0}

# Close Steam to the system tray (0 OFF, 1 ON)
CLOSE_TO_TRAY=${_CLOSE_TO_TRAY:-1}

# File to log to, generally do not need to change.
LOG="$LOGDIR/steam-wrapper.log"

#####################################################################
# steam-wrapper
# Packaged by: pyamsoft <pyam.soft@gmail.com>
#####################################################################

# Create the log directory
mkdir -p $LOGDIR

# Log opening
if [[ $DEBUG -eq 1 ]]; then
	echo "steam-wrapper[$VERSION]: Launched on $(date +%Y-%m-%d) at $(date +%R) [$(date +%r)]" >> $LOG
fi

# Remove some files that apperantly conflict with native runtimes on ArchLinux
if [[ $DEBUG -eq 1 ]]; then
	echo "steam-wrapper[$VERSION]: Attempting removal of stale libraries..." >> $LOG
fi

# Read for details:
#     https://wiki.archlinux.org/index.php/steam#Steam_runtime_issues
if [[ $DEBUG -eq 1 ]]; then
	find $HOME/.local/share/Steam/ \( -name "libgcc_s.so*" -o -name "libstdc++.so*" -o -name "libxcb.so*" \) -delete -print >> $LOG
else
	find $HOME/.local/share/Steam/ \( -name "libgcc_s.so*" -o -name "libstdc++.so*" -o -name "libxcb.so*" \) -delete
fi

if [[ $DEBUG -eq 1 ]]; then
	echo "steam-wrapper[$VERSION]: Done." >> $LOG
	echo >> $LOG
fi

# Run steam using the wrapper
exec env \
	STEAM_RUNTIME="${USE_RUNTIME}" \
	STEAM_FRAME_FORCE_CLOSE="${CLOSE_TO_TRAY}" \
	steam "$@"
