post_install() {
	gdk-pixbuf-query-loaders > /opt/google/chrome/loaders.cache
	sed -i '/libpixbufloader-jpeg.so/ c "/opt/google/chrome/libpixbufloader-jpeg.so"' /opt/google/chrome/loaders.cache
	sed -i.bak '/exec/ i export GDK_PIXBUF_MODULE_FILE="$HERE/loaders.cache"\n' /opt/google/chrome/google-chrome
}

post_remove() {
	rm -f /opt/google/chrome/loaders.cache
	mv /opt/google/chrome/google-chrome.bak /opt/google/chrome/google-chrome
}