# coding=utf-8
emoticons = {
  'aa.gif': ['O:-)', 'O:)', 'O+)', 'O=)', '0:-)', '0:)', '0+)', '0=)'],
  'ab.gif': [':-)', ':)', '=)', '+)'],
  'ac.gif': [':-(', ':(', '+(', '=('],
  'ad.gif': [';-)', ';)', '^_~'],
  'ae.gif': [':-P', ':P', ':-p', ':p', '+P', '=P', '+p', '=p', ':-b', ':b', '+b', '=b'],
  'af.gif': ['8-)', '8)', 'B)'],
  'ag.gif': [':-D', ':D', '+D', '=D'],
  'ah.gif': [':-[', ':[', ';-.'],
  'ai.gif': ['=-O', '=O', '=-o', '=0', 'O_O', 'O_o', 'o_O', 'O_0', 'o_0', '0_O', '0_o'],
  'aj.gif': [':-*', ':*', ':-{}', ':{}', '+{}', '={}', '^.^'],
  'ak.gif': [':`(', ':-`('],
  'al.gif': [':-X', ':-x', 'X:', 'x:', ':-#', ':#'],
  'am.gif': ['>:o', '>:O', '>+O', '>:o', '>+o', '>=o', ':-@'],
  'an.gif': [':-|', ':|', '=|'],
  'ao.gif': [':-\\', ':-/', ':\\'],
  'ap.gif': ['*JOKINGLY*', '8P', '8p'],
  'aq.gif': [']:->', '}:->', ']:>', '}:>', '>:-]', '>:]', '*DIABLO*'],
  'ar.gif': ['[:-}', '[:}'],
  'as.gif': ['*KISSED*'],
  'at.gif': [':-!', ';-!', ':!', ';!', ':-~', ';-~'],
  'au.gif': ['*TIRED*', '|-0'],
  'av.gif': ['*STOP*'],
  'aw.gif': ['*KISSING*'],
  'ax.gif': ['@}->--', '@}-:--', '@>}--`---'],
  'ay.gif': ['*THUMBS UP*'],
  'az.gif': ['*DRINK*'],
  'ba.gif': ['*IN LOVE*'],
  'bb.gif': ['@='],
  'bc.gif': ['*HELP*'],
  'bd.gif': ['\m/'],
  'be.gif': ['%)', '%-)', ':$'],
  'bf.gif': ['*OK*'],
  'bg.gif': ['*WASSUP*', '*SUP*'],
  'bh.gif': ['*SORRY*'],
  'bi.gif': ['*BRAVO*'],
  'bj.gif': ['*ROFL*', '*LOL*'],
  'bk.gif': ['*PARDON*', '=]'],
  'bl.gif': ['*NO*'],
  'bm.gif': ['*CRAZY*'],
  'bn.gif': ['*DONT_KNOW*', '*UNKNOWN*'],
  'bo.gif': ['*DANCE*'],
  'bp.gif': ['*YAHOO*', '*YAHOO!*'],
  'bq.gif': ['*HI*', '*PREVED*' , '*PRIVET*', '*HELLO*'],
  'br.gif': ['*BYE*'],
  'bs.gif': ['*YES*'],
  'bt.gif': [';D', '*ACUTE*'],
  'bu.gif': ['*WALL*', '*DASH*'],
  'bv.gif': ['*WRITE*', '*MAIL*'],
  'bw.gif': ['*SCRATCH*'],
 }