--- Makefile	2010-05-24 15:03:18.316406226 +0200
+++ Makefile	2010-05-24 15:03:24.416436817 +0200
@@ -10,7 +10,7 @@
 ###############{
 
 # On HP-UX you will have to change this
-INSTALL = install -o root -g root
+INSTALL = install
 
 DESTDIR = 
 
