post_install() {
  cat <<-EoM

==> Chromium theme was not installed because it will over-write the default
==> chromium theme.
  
==> KDM themes do not work yet.
  
==> If you want the chromium theme, and a slightly modified Firefox, you    
==> should remove this package and download the original package from:
==> http://www.kde-look.org/content/show.php/UniQ?content=112688
==> then follow the install script.

EoM

  update-desktop-database -q

  /bin/true
}

post_upgrade() {
  post_install
}
