post_install(){

	if [ ! -d /mnt/synce ]
	then
		mkdir /mnt/synce
	fi

	ln -s /usr/sbin/mount.cefs /sbin/mount.cefs

	echo "-----------------------------------------------------------"
	echo "In order to allow non-root user to mount SynCE filesystem,"
	echo "add the following line to /etc/fstab"
	echo ""
	echo "none /mnt/synce cefs rw,user,noauto,codadev=/dev/cfs0 0 0"
	echo "-----------------------------------------------------------"
}
