post_install() {
	gtk-update-icon-cache

	# generate a starterfile which starts the daemon and the client 
	echo "#!/bin/bash" > /usr/bin/sflphone
	echo "/usr/lib/sflphone/sflphoned&" >> /usr/bin/sflphone
	echo "/usr/bin/sflphone-client-kde" >> /usr/bin/sflphone
	echo "killall sflphoned" >> /usr/bin/sflphone
	chmod 755 /usr/bin/sflphone
	
	# use our new starterfile in the menu item
	sed -i 's/Exec=sflphone-client-kde/Exec=sflphone/' /usr/share/applications/kde4/sflphone-client-kde.desktop
}