#!/bin/bash

. /etc/rc.d/functions

bin=/usr/bin/xbmc-wiiremote
PID=`pidof -o %PPID $bin`

case "$1" in
	start)
		stat_busy "Starting wiiremote eventclient"
		[ -z "$PID" ] && $bin &>> /var/log/xbmc-wiiremote.log &
		if [[ $? -gt 0 ]]; then
			stat_fail
		else
			add_daemon xbmc-wiiremote
			stat_done
		fi
		;;
	stop)
		stat_busy "Stoppping wiiremote eventclient"
    [ ! -z "$PID" ] && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
			stat_fail
		else
			rm_daemon netfs
			stat_done
		fi
		;;
	restart)
		$0 stop
		while [ ! -z "$PID" -a -d "/proc/$PID" ]; do sleep 1; done
		$0 start
		;;
	*)
		echo "usage: $0 {start|stop|restart}"  
esac

# vim: set ts=2 noet:
