# $Id: audacious-plugins.install,v 1.7 2007/12/16 02:27:33 travis Exp $
# arg 1:  the new package version
post_install() {
    echo "> Optional Dependencies for mplayer"
    echo ">> samba:  Enable Samba (SMB) input."

    # Run ldconfig after installation
    #  the makefile wants to do this after make install
    /sbin/ldconfig
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
    post_install $1 
}

op=$1
shift
$op $*
