available() {
  which "$1" >/dev/null 2>&1
}

post_install() {
  # refresh mime/icon registrations
  update-mime-database /usr/share/mime >/dev/null
  update-desktop-database -q /usr/share/applications

  if available gtk-update-icon-cache; then
    gtk-update-icon-cache -q /usr/share/icons/hicolor
  fi
}

post_upgrade() {
	# refresh mime/icon registrations
  post_install
}

post_remove() {
	# refresh mime/icon registrations
  post_install
}
