_install_notes() {
    echo
    echo 'Edit your /etc/lightdm/lighdm.conf to enable this greeter.'
    echo 'Greeter settings stored in /etc/lightdm/lighdm-another-gtk-greeter.conf'
    echo
    echo 'Version 1.0.4.8: .ui files moved to directory "themes". Add "appearance/greeter-theme" key with proper value to your .conf' 
    echo
}

post_install() {
    _install_notes
}

post_upgrade() {
    _install_notes
}

