#! /bin/bash
# Modifed: 04/30/2010
# 
# This script is heavily borrowed from the netcfg-openvpn scripts
# This will allow you to create a VPNC connection and connect using netcfg.
# Combining this with the net-auto-vpnc script, will allow you to connect
# To a VPN at boot-time.
#

. /usr/lib/network/network

vpnc_up() {
    load_profile $1
    [[ -z "$VPNC_CONFIG" ]] && VPNC_CONFIG="/etc/vpnc/default.conf"
    [[ -z "$VPNC_FLAGS" ]] && VPNC_FLAGS=""

    VPNC_CONF_DIR="`dirname $VPNC_CONFIG`"
    VPNC_CONF_FILE="`basename $VPNC_CONFIG`"

    /usr/sbin/vpnc  $VPNC_FLAGS $VPNC_CONF_FILE
    if [[ $? -ne 0 ]]; then
       report_fail "VPNC connection failed"
       exit 1
    fi
}

vpnc_down() {
    load_profile $1
    /usr/sbin/vpnc-disconnect
    if [[ $? -ne 0 ]]; then
        report_fail "VPNC disconnect failed. Trying again."
        killall -9 `ps aux | pgrep vpnc` >>/dev/null 2>&1
        if [[ $? -ne 0 ]]; then
            report_fail "Unable to terminate or find VPNC process."
        fi
    fi

}

vpnc_$1 $2
exit $?
# vim: set ts=4 et sw=4:
