# PKGBUILD generated by pacpan
pkgname=perl-trycatch
_realname=TryCatch
pkgver=1.002000
pkgrel=1
pkgdesc="'first class try catch semantics for Perl, without source filters.'"
arch=(i686 x86_64)
license=('perl')
url="http://search.cpan.org/~ash/TryCatch"
options=(!emptydirs)

depends=('perl>=5.8.1' 'perl-scope-upper' 'perl-parse-method-signatures' 'perl-b-hooks-endofscope' 'perl-b-hooks-op-check' 'perl-moosex-types' 'perl-b-hooks-op-ppaddr' 'perl-variable-magic' 'perl-devel-declare' 'perl-moose')
makedepends=('perl-b-hooks-op-check' 'perl-extutils-depends' 'perl-b-hooks-op-ppaddr')

#provides=('TryCatch')
provides=('trycatch=1.002000' 'TryCatch::TypeParser=undef' 'perl-trycatch-typeparser=undef' 'TryCatch::Exception=undef' 'perl-trycatch-exception=undef')

source=(http://search.cpan.org/CPAN/authors/id/A/AS/ASH/TryCatch-1.002000.tar.gz)
md5sums=('c0069370f5cbd982872702ed4495daf4')

build() {
  _expected_dir="${srcdir}/${_realname}-${pkgver}"
  if [ -d "$_expected_dir" ]; then
    cd "$_expected_dir"
  else
    _expected_dir="${srcdir}/$(bsdtar -t -f $(basename $source) | head -n1)"
    if [ -d "$_expected_dir" ]; then
      cd "$_expected_dir"
    else
      _makefile=$(find $srcdir -iname Makefile.PL)
      if [ ! -z "$_makefile" ]; then
        _expected_dir=$(dirname $_makefile)
        if [ -d "$_expected_dir" ]; then
          cd "$_expected_dir"
        else
          echo "[1;31mERROR[0m unable to detect source directory"
          echo "[1;34m-->[0m this is often due to CPAN's lack of standard naming conventions"
          echo "[1;34m-->[0m it may be possible to fix this by adjusting the build function in the PKGBUILD"
        fi
      fi
    fi
  fi
  # install module in vendor directories.
  PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor || return 1
  make  || return 1
  make install DESTDIR=${pkgdir} || return 1

  # remove perllocal.pod and .packlist
  find ${pkgdir} -name perllocal.pod -delete
  find ${pkgdir} -name .packlist -delete
}

# vim:set ts=2 sw=2 et:
# END OF PACPAN PKGBUILD

