post_install() {
    update-desktop-database -q

    /usr/bin/cat << EOF
    0.6.9.2 is a transition package. It is recommended to manually specify
    one or two nodes that use 0.6.9.2 in the config file. Connecting only to
    older nodes may fail to propagate transactions.
     
    More information:
    https://forum.litecoin.net/index.php/topic,4615.msg33170.html
EOF
}

post_upgrade() {
    post_install $1
}

post_remove() {
    post_install $1
}
