post_install() {
  glib-compile-schemas usr/share/glib-2.0/schemas
  update-desktop-database -q
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  echo ">>> PLEASE READ!"
  echo ">>>   The package contains a patch to let gnome-boxes run"
  echo ">>>   with version 3.2 of GTK+. However, for a better experience"
  echo ">>>   it is recommended to use at least GTK+ version 3.3.3"
}

post_upgrade() {
  post_install
}

post_remove() {
  post_install
}
