post_install() {
  echo "WARNING: Linux support for Dungeon Defenders is quite poor."
  echo "  There are multiple known crash issues, most noticably with"
  echo "  the Series EV character. See this thread for more information"
  echo "  and possible solutions if you experience issues."
  echo "  http://steamcommunity.com/app/65800/discussions/0/846957366801590893/"
  echo " "
  echo "Also, please note that non-steam multiplayer has been abandoned."
}
