post_install() {
  if [ -L /opt/ivideon/ivideon-client/platforms ]; then
    rm /opt/ivideon/ivideon-client/platforms
  else
  ln -s /opt/ivideon/qtlibs/platforms opt/ivideon/ivideon-client/platforms
  fi
  if [ -L /usr/bin/ivideon-client ]; then
    rm /usr/bin/ivideon-client
  else
  ln -s /opt/ivideon/ivideon-client/ivideon-client /usr/bin/ivideon-client
  fi
  gtk-update-icon-cache -f /usr/share/icons/hicolor &>2
}

post_upgrade() {
  post_install
}

post_remove() {
  post_install
}
