## arg 1:  the new package version
post_install() {
  echo
  echo '==> To make netplug daemon start on boot, add "netplugd" to the DAEMONS'
  echo '==> array in /etc/rc.conf.'
  echo
  echo '==> Change the pattern of monitored network interfaces by netplugd'
  echo '==> in /etc/netplug/netplug.'
  echo
  echo '==> Change actions performed when an interface is plugged or unplugged'
  echo '==> in /etc/netplug/netplugd.conf.'
}

# vim:set ts=2 sw=2 et:
