#!/bin/bash
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

# Reset all variables that might be set
format=""

usage() {
    echo "USAGE:"
    echo "  -h          Show this text"
    echo "  -F FORMAT   Set what format options to pass to mpc (default: \"%artist% - %title%\")"
    echo
    echo "Everything else is passed to dmenu:"
    echo "$(dmenu -h)"
}
 

while true
do
    case $1 in
        -h)
            usage
            exit 0
            ;;
        -F)
            format="$2"
            shift 2
            ;;
        '')  # No more options
            break
            ;;
        *)  # Add option to list of opts that are passed to dmenu
            dmenuopts="$dmenuopts $1"
            shift 1
            ;;

    esac
done

# Default format
if [[ -z "$format" ]]; then
    format="%artist% - %title%"
fi

# Get the current playlist
playlist="$(mpc playlist -f "$format")"

# Pipe the playlist to dmenu, catch name
name="$(echo "$playlist" | dmenu "$dmenuopts")"

# Get the playlist position of the name with sed
songnum="$(echo "$playlist" | sed -n "/${name}/=")"

# Play the song
mpc play $songnum
