post_install() {
  usr/sbin/groupadd -f --system golang
  chgrp -R golang /opt/go
  bin/cat <<EOI

NOTE
----

* check /etc/profile.d/go.sh, then relogin or 'source' the file
* add your user to group 'golang' to be able to 'goinstall' third-party packages
* to avoid permission issues check the 'goinstall' wrapper '/opt/go/bin/goinst'
* the go binaries are installed in '/opt/go/bin'

EOI
}

post_upgrade() {
  post_install $1
}

post_remove() {
  usr/sbin/groupdel golang &>/dev/null
}
