post_install() {
    echo -e '\E[1;34m'
    echo " "
    echo " "
    echo "<==== INFORMATION ====>"
    echo " "
    echo "* FizzBall Demo is now installed."
    echo " "
    echo "* The full version can be purchased for $ 6.95"
    echo "* Homepage: http://grubbygames.com/fizzball/"
    echo " "
    echo "* Accessing the game by typing 'fizzball-demo' in the terminal. "
    echo " "

tput sgr0 
} 
