_comment="# added by hybrid-video-ati-intel install script"

post_install() {
  post_remove

  {
    echo "modprobe radeon $_comment"
    echo "echo OFF > /sys/kernel/debug/vgaswitcheroo/switch $_comment"
  } >> etc/rc.local
  
  grep "/sys/kernel/debug" etc/fstab >/dev/null || echo "none /sys/kernel/debug debugfs defaults 0 0" >> etc/fstab
}

post_upgrade() {
  post_install
}

post_remove() {
  sed -i "/$_comment/D" etc/rc.local
}

