post_install() {
    
    echo ">>> To install your Lexmark printer run as root"
    echo ">>> (don't use \"sudo\", it will not work):"
    echo ">>>"
    echo ">>>  # postinstall.sh"
    echo ">>>"
    echo ">>> In my tests I found that:"
    echo ">>> * Wifi printing is ok"
    echo ">>> * Usb printing doesn't work at all for me :("
    echo ">>> * Wired printing is untested"
    echo ">>>"
    echo ">>> Any comments and suggestions are welcomed!"
}

post_upgrade() {
    post_install $1
}

