

post_install() {
  echo ">>> Adding driver name \"canon_mfp\" to /etc/sane.d/dll.conf"
  echo "canon_mfp" >> /etc/sane.d/dll.conf

  if [ -x /sbin/ldconfig ]; then
     echo ">>> Running ldconfig"
     /sbin/ldconfig
  fi

}

post_remove() {
  echo ">> Removing any occurences of \"canon_mfp\" in /etc/sane.d/dll.conf"
  sed -i -e '/^canon_mfp$/ d' /etc/sane.d/dll.conf

  if [ -x /sbin/ldconfig ]; then
     echo ">>> Running ldconfig"
     /sbin/ldconfig
  fi

}
