post_install() {
  echo -n "Updating vim help tags..."
  /usr/bin/vim --noplugins -u NONE -U NONE \
    --cmd ":helptags /usr/share/vim/doc" --cmd ":q" > /dev/null 2>&1
  echo "done.
See /usr/share/doc/vim-googlereader/README for usage"
}

post_upgrade() {
  post_install
}

post_remove() {
  echo -n "Updating vim help tags..."
  /usr/bin/vim --noplugins -u NONE -U NONE \
    --cmd ":helptags /usr/share/vim/doc" --cmd ":q" > /dev/null 2>&1
  echo "done."
}
