post_install() {
	# lpr
	/opt/brother/Printers/dcpj715w/inf/setupPrintcapij dcpj715w -i
	# cupswrapper
	/opt/brother/Printers/dcpj715w/cupswrapper/cupswrapperdcpj715w
	
	/etc/rc.d/cupsd restart
}

post_upgrade() {
	/bin/true
}

pre_remove() {
  # cupswrapper
	/opt/brother/Printers/dcpj715w/cupswrapper/cupswrapperdcpj715w -e
  
	# lpr
	/opt/brother/Printers/dcpj715w/inf/setupPrintcapij dcpj715w -e
}
