#!/bin/bash

# general config
. /etc/rc.conf
. /etc/rc.d/functions

FSROOT=/usr/freeswitch
PID=`pidof -o %PPID /usr/freeswitch/bin/freeswitch`

case "$1" in
  start)
    stat_busy "Starting FreeSwitch"
    # initialization
    if [ ! -d $FSROOT/conf ]; then
      stat_busy "Adding freeswitch conf directory"
      cp -R $FSROOT/conf.sample $FSROOT/conf
      stat_done
    fi
    if [ ! `egrep '^freeswitch:' /etc/group` ]; then
      stat_busy "Adding freeswitch group"
      groupadd -g 489 freeswitch
      stat_done
    fi
    if [ ! `egrep '^freeswitch:' /etc/passwd` ]; then
      stat_busy "Adding freeswitch user"
      useradd -u 489 -g freeswitch -d $FSROOT -s /bin/bash freeswitch
      [ -d $FSROOT ] && chown -R freeswitch.freeswitch $FSROOT
      stat_done
    fi
    # start the process
    su - freeswitch -c \
     "/usr/freeswitch/bin/freeswitch -nc"
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon freeswitch
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping FreeSwitch"
    su - freeswitch -c \
      "/usr/freeswitch/bin/freeswitch -stop"  
    sleep 3
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon freeswitch
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 3
    $0 start
    ;;
  reload)
    /bin/kill -s SIGHUP $PID
    ;;
  *)
    echo "usage: $0 {start|stop|restart|reload}"  
esac
exit 0
