post_install() {

cat << EOF

To enable the novacom service at boot, run the following command as root:
systemctl enable novacom.service

To manually start the service (without having to reboot), run the following command as root:
systemctl start novacom.service

EOF
post_upgrade

}

post_upgrade() {

cat << EOF

Before removing the novacom service, run the following commands as root:

systemctl stop novacom.service
systemctl disable novacom.service

EOF

}
