# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: kusakata <shohei atmark kusakata period com>

_gemname=feedzirra
pkgname=ruby-$_gemname
pkgver=0.7.0
pkgrel=1
pkgdesc='A feed fetching and parsing library'
arch=(any)
url='http://github.com/pauldix/feedzirra'
license=(MIT)
depends=(ruby ruby-sax-machine ruby-curb ruby-loofah)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('bf3a6bd95e95ff56723336846f7435b1c3131573')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
