post_install() {
  echo "------------------------------------------------------------------------------------"
  echo "This program requires you have Kernel Mode Settings (KMS) enabled."
  echo "For more information, see https://wiki.archlinux.org/index.php/Ati#With_KMS_enabled."
  echo "------------------------------------------------------------------------------------"
}

# vim:set ts=2 sw=2 et:
