post_install() {
	export GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source`
	echo " -> Installing gconf schema"
	gconftool-2 --makefile-install-rule /etc/gconf/schemas/wp_tray.schemas > /dev/null || return 1
}

post_upgrade() {
	export GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source`
	echo " -> Updating gconf schema"
	gconftool-2 --makefile-install-rule /etc/gconf/schemas/wp_tray.schemas > /dev/null || return 1
}

