post_install() {
	# lpr
	/usr/local/Brother/Printer/dcp770cw/inf/setupPrintcapij dcp770cw -i
	
	# cupswrapper
	/usr/local/Brother/Printer/dcp770cw/cupswrapper/cupswrapperdcp770cw
	
	/etc/rc.d/cups restart
}

post_upgrade() {
	/bin/true
}

pre_remove() {
	# lpr
	/usr/local/Brother/Printer/dcp770cw/inf/setupPrintcapij dcp770cw -e
	
	# cupswrapper
	/usr/local/Brother/Printer/dcp770cw/cupswrapper/cupswrapperdcp770cw -e
}

op=$1
shift

$op "$@"


