#!/usr/bin/ash
#
# This file is part of btinput.  btinput is free software: you can
# redistribute it and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation, version 2.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#   
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#   
# Copyright Aline Freitas <aline@alinefreitas.com.br>

#

run_hook() {
    msg "Activating dbus..."
    mkdir -m755 /run/dbus
    dbus-daemon --system
    sleep 1

    msg "Activating bluetoothd..."
    mkdir -m755 /run/sdp
    bluetoothd 
    sleep 1

    msg "Activating hidd..." 
    . /etc/conf.d/bluetooth
    hidd ${HIDD_OPTIONS}
}


