post_install() {
    echo ""
    echo "This package has installed a btinput hook".
    echo "Just add 'btinput' in the HOOKS array before 'encrypt' in /etc/mkinitcpio.conf".
    echo ""
    echo "Example:"
    echo "HOOKS=\"base udev autodetect scsi sata btinput encrypt lvm2 usbinput filesystems fsck\""
    echo ""
    echo "You may need to add the bluetooth specific module for your device in the MODULES array".
}

