post_install() {
  update-desktop-database -q
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

pre_upgrade() {
    if [ -f usr/share/gconf/schemas/transmission-remote-gtk.schemas ]; then
        usr/sbin/gconfpkg --uninstall transmission-remote-gtk
    fi
}

post_upgrade() {
  post_install
}

post_remove() {
  update-desktop-database -q
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor 
}
