post_install() {
  cat <<MSG
NOTE: For this to work properly, you must add

acpi_osi=Linux acpi_backlight=vendor

to your bootloader kernel parameters. (Don't replace the word "vendor" with your actual vendor). Then, add the lines

chmod 666 /sys/class/backlight/intel_backlight/brightness
brightness restore

to your rc.local file, or from anywhere you want to run it at startup.

Additionally, this will only work on kernels 3.1 or later.

MSG
}

post_upgrade() {
  post_install
}
