post_install() {
  echo -e "\033[1m>>>\033[0m Updating icon cache..."
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  echo -e "\033[1m>>>\033[0m Done"
}

post_upgrade() {
  echo -e "\033[1m>>>\033[0m Updating icon cache..."
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  echo -e "\033[1m>>>\033[0m Done"
}

post_remove() {
  echo -e "\033[1m>>>\033[0m Updating icon cache..."
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  echo -e "\033[1m>>>\033[0m Done"
}
