rebuild_module_dependencies() {
	depmod $(uname -r)
}

post_install() {
  	rebuild_module_dependencies
	echo '>>> The module r8168 conflicts with r8169. You can blacklist it with:'
	echo '>>>  `echo "blacklist r8169" > /etc/modprobe.d/r8169.conf`'
	echo '>>>  Run "sudo modprobe r8168 to load" to load module.'
}
post_upgrade() {
	rebuild_module_dependencies
}

post_remove() {
	rebuild_module_dependencies
}
