.TH "Avatar Factory" 1

.SH NAME
\fBAvatar Factory\fP - A bash script that creates eye candy shortcuts for music albums, photo albums, movie files, and more...

.SH SYNOPSIS
.nf
\fBavatar-factory\fP \fI-g grabber-name\fP \fIoptions\fP \fIinput-file/s-or-folder/s\fP \fIoutput-folder\fP
.fi

.SH DESCRIPTION
\fBAvatar Factory\fP is a bash script that creates shortcuts (Desktop Entry files)
with eye candy icons that represent music albums, photo albums, DVD films,
youtube videos, mame roms, comics and more. When clicked the avatars can perform different actions
as launching a video, start playing some music (compatible with many music players), open a folder, etc...
They can be viewed in Nautilus, Thunar or any application that support Desktop Entry files.

.SH ARGUMENTS
.TP
.IP "\fB\-g --grabber\fR \fIgrabber-name\fR"
Select a grabber. Use --help option after the grabber name to print the grabber help.

.IP "\fB\-lg --list-grabbers\fR
List available grabbers.

.IP "\fB\-t --theme\fR \fItheme-name\fR"
Set a different theme.

.IP "\fB\-lt --list-themes\fR
List available themes.

.IP "\fB\--name\fR [\fI1-3\fR]"
Set the name scheme. 0=no name, 1=index, 2=title, 3(1+2)=index.title

.IP "\fB\--type\fR [\fI0-1\fR]"
Set the shortcut type. 0=Link (open the folder or run the default system action), 1=Application (use the avatar launcher)

.IP "\fB\-al --avatar-launcher\fR
This option is used by the avatars but it can also be used to overwrite the launchers.
.IP Example:
.PD 0
.TP
--avatar-launcher --launcher totem avatar1.desktop avatar2.desktop

.IP "\fB\--picture-gui\fR
This option allows to chose the picture (normally the cover) used to make the icon.

.IP "\fB\--folders\fR
Creates folders, replicating folder structure.

.IP "\fB\--folders-2\fR
Same as --folders but from level 2. It skips the first level of folders. Usefull for bookmarks grabbers.

.IP "\fB\--delete\fR
Delete broken avatars in the destination folder recursively.

.IP "\fB\--icon-size\fR \fI[1-99]\fR"
Set icons size for nautilus from 1 to 99. 27 = 128px

.IP "\fB\--widget\fR
Start or restart the script that automatically show/hide the music widget.

.IP "\fB\--widget-quit\fR
Quit the script that automatically show/hide the music widget.

.IP "\fB\-h --help\fR
Print usage and exit. To print the grabber help set first the grabber using "-g grabber-name"

.SH GUI
.TP
.IP "\fB\--gui\fR
Display a Gtk dialog to set a parameter. (zenity)
.IP Examples:
.PD 0
.TP
"-g --gui" to select a grabber.
.TP
"-t --gui" to select a theme.
.TP
"--name --gui" to select the name scheme.
.TP
"--type --gui" to select the shortcut type.

.TP
.IP "\fB\--gui-progress\fR
Display a Gtk progress dialog. (zenity)

.SH CONFIGURATION
.TP
\fBConfiguration files:\fP 
.TP
    \fR \fI~/.avatar-factory/general\fR"
.TP
\fBGrabbers confiturations:\fP 
.TP
    \fR \fI~/.avatar-factory/grabbers/grabber_name\fR"


.SH DEPENDENCIES
.PD 0
.TP
\fBImage Magick\fP 
.TP
\fBZenity\fP (display GTK+ dialogs)

.SH BUGS
Please report any bugs at:
.TP
\fIhttp://ubuntuforums.org/showthread.php?t=486359\fP.
 
.SH CONTACT
Yuzem \fIhttp://ubuntuforums.org/member.php?u=175913\fP

