#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/crond

NAME=zfoned
DAEMON=/usr/local/bin/$NAME
DAEMON_ARGS=""
PID=$(pidof -o %PPID /usr/local/bin/zfoned)

case $1 in
start)
	stat_busy "Starting Zfone Daemon"

	if [[ -z $PID ]] && env -i PATH="/sbin:/usr/sbin:/bin:/usr/bin" $DAEMON $DAEMON_ARGS; then

		PID=$(pidof -o %PPID /usr/local/bin/zfoned)
		echo "$PID" > /var/run/zfoned.pid
		add_daemon zfoned
		stat_done
	else
		stat_fail
		exit 1
	fi
	;;

stop)
	stat_busy "Stopping Zfoned Daemon"
	if [[ ! -z $PID ]]  && kill "$PID" &>/dev/null; then
		rm_daemon zfoned
		stat_done
	else
		stat_fail
		exit 1
	fi
	;;

restart)
	$0 stop
	$0 start
	;;

*)
	echo "Usage: $0 {start|stop|restart}" >&2
	exit 1

esac
