--- ../s48/Makefile.in	2012-01-17 13:40:23.271160532 -0500
+++ ./Makefile.in	2012-01-17 13:45:59.093107430 -0500
@@ -521,25 +521,25 @@
 	done
 # install the scheme48-config script
 	config_script=$(DESTDIR)$(bindir)/$(CONFIG_SCRIPT) &&		\
-	sed -e 's,@incdir\@,$(incdir),g'				\
-	    -e 's,@libdir\@,$(libdir),g'				\
-	    -e 's,@CC\@,$(CC),g'					\
-	    -e 's,@LD\@,$(LD),g'					\
-	    -e 's,@DYNAMIC_EXTERNALS_CFLAGS\@,$(DYNAMIC_EXTERNALS_CFLAGS),g' \
-	    -e 's,@DYNAMIC_EXTERNALS_LDFLAGS\@,$(DYNAMIC_EXTERNALS_LDFLAGS),g' \
+	sed -e 's|@incdir\@|$(incdir)|g'				\
+	    -e 's|@libdir\@|$(libdir)|g'				\
+	    -e 's|@CC\@|$(CC)|g'					\
+	    -e 's|@LD\@|$(LD)|g'					\
+	    -e 's|@DYNAMIC_EXTERNALS_CFLAGS\@|$(DYNAMIC_EXTERNALS_CFLAGS)|g' \
+	    -e 's|@DYNAMIC_EXTERNALS_LDFLAGS\@|$(DYNAMIC_EXTERNALS_LDFLAGS)|g' \
 	< $(srcdir)/build/$(CONFIG_SCRIPT).in > $$config_script &&	\
 	chmod +x $$config_script
 # install the external modules
 	$(INSTALL_PROGRAM) $(EXTERNALS) $(DESTDIR)$(LIB)/
 # install the documentation
 	$(srcdir)/mkinstalldirs $(DESTDIR)$(docdir)
-	$(INSTALL_DATA) $(srcdir)/COPYING $(docdir)
+	$(INSTALL_DATA) $(srcdir)/COPYING $(DESTDIR)$(docdir)
 
 install-doc: dirs doc
 	$(srcdir)/mkinstalldirs $(DESTDIR)$(docdir)
-	$(INSTALL_DATA) $(srcdir)/COPYING $(docdir)
-	$(INSTALL_DATA) $(srcdir)/doc/manual.pdf $(docdir)
-	$(INSTALL_DATA) $(srcdir)/doc/manual.ps $(docdir)
+	$(INSTALL_DATA) $(srcdir)/COPYING $(DESTDIR)$(docdir)
+	$(INSTALL_DATA) $(srcdir)/doc/manual.pdf $(DESTDIR)$(docdir)
+	$(INSTALL_DATA) $(srcdir)/doc/manual.ps $(DESTDIR)$(docdir)
 	for f in $(srcdir)/doc/html/*; do \
 		$(INSTALL_DATA) $$f $(DESTDIR)$(docdir) || exit 1; \
 	done
