# arg 1:  the new package version
# arg 2:  the old package version

KERNEL_VERSION=2.6.31-dmraid45

post_install () {
    echo ">"
    echo "> Updating module dependencies. Please wait ..."

    depmod -v ${KERNEL_VERSION} > /dev/null 2>&1

    echo ">"
    echo "> Generating initramfs, using mkinitcpio.  Please wait..."
    echo ">"

    /sbin/mkinitcpio -p kernel26-dmraid45
}

post_upgrade() {
    post_install
}

op=$1
shift
$op $*
