# Generated by Xyne::Arch::CPAN 0.07

pkgname=perl-gd-barcode
pkgver=1.15
pkgrel=1
pkgdesc="Create barcode image with GD"
arch=('i686' 'x86_64')
url="http://search.cpan.org/dist/GD-Barcode/"
license=('unknown')
source=('http://search.cpan.org/CPAN/authors/id/K/KW/KWITKNR/GD-Barcode-1.15.tar.gz')
md5sums=('53788170efb00b671ffb6ced5b5b897b')
sha256sums=('8c22b449079dce65946ec72acf6d3db78753045e7738c5101bc26932c9704967')
depends=()
provides=('perl-gd-barcode-code39=1.1' 'perl-gd-barcode-coop2of5=0.01' 'perl-gd-barcode-ean13=1.1' 'perl-gd-barcode-ean8=1.1' 'perl-gd-barcode-iata2of5=0.01' 'perl-gd-barcode-industrial2of5=0.01' 'perl-gd-barcode-itf=0.01' 'perl-gd-barcode-matrix2of5=0.01' 'perl-gd-barcode-nw7=1.1' 'perl-gd-barcode-qrcode=0.01' 'perl-gd-barcode-upca=1.1' 'perl-gd-barcode-upce=1.1')
options=(!emptydirs)

build() {
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Makefile.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor || return 1
    make  || return 1
    make install DESTDIR="${pkgdir}" || return 1

  else
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Build.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Build.PL INSTALLDIRS=vendor || return 1
    ./Build  || return 1
    ./Build install destdir=${pkgdir} || return 1

  else
    echo "error: failed to detect build method for $pkgname"
    echo "you may be able to fix this by editing the PKGBUILD"
    return 1
  fi fi

  # remove perllocal.pod and .packlist
  find ${pkgdir} -name perllocal.pod -delete
  find ${pkgdir} -name .packlist -delete
}

# vim:set ts=2 sw=2 et:

