--- Makefile.orig	2004-07-04 00:30:29.000000000 -0400
+++ Makefile	2009-08-05 20:46:44.714174467 -0400
@@ -1,9 +1,9 @@
 # ONLY CHANGE THESE THREE OPTIONS IF YOU KNOW WHAT YOU ARE DOING
-BIN_PREFIX = /usr/local/bin/
+BIN_PREFIX = /usr/bin/
 # if you don't have privileges to install systemwide, comment out both 
 # lines below and the game will then play from the current directory
-DATA_PREFIX = /usr/local/share/games/twind/
-HIGH_SCORE_PREFIX = /var/lib/games/twind/
+DATA_PREFIX = /usr/share/twind/
+HIGH_SCORE_PREFIX = /var/games/twind/
 # uncomment out the EXTENSION if you don't have the png libs on your system
 #EXTENSION = ".bmp"
 AUDIOFLAG = AUDIO
@@ -36,11 +36,11 @@
 	cp -r music/*.ogg $(DATA_PREFIX)music
 	cp -r sound/*.wav $(DATA_PREFIX)sound
 	cp twind $(BIN_PREFIX)
-	chown root:games $(BIN_PREFIX)twind
+#	chown root:games $(BIN_PREFIX)twind
 	chmod g+s $(BIN_PREFIX)twind
 	touch $(HIGH_SCORE_PREFIX)twind.hscr
-	chown root:games $(HIGH_SCORE_PREFIX)twind.hscr
-	chmod 664 $(HIGH_SCORE_PREFIX)twind.hscr
+#	chown root:games $(HIGH_SCORE_PREFIX)twind.hscr
+	chmod 777 $(HIGH_SCORE_PREFIX)twind.hscr
     
 uninstall:
 	rm -rf $(DATA_PREFIX)
