#!/usr/bin/ash

run_hook ()
{
    if [ -n "$ppp_provider" -a -n "$ppp_device" ]; then
	ip link set "$ppp_device" up
	echo "Starting ppp"
	pppd call "$ppp_provider"
    fi
}

run_cleanuphook ()
{
    if [ -n "$ppp_provider" -a -n "$ppp_device" ]; then
	killall pppd
        ip addr flush dev "$ppp_device"
	ip link set down "$ppp_device"
    fi
}
