post_install () {
  if [[ $(locale -a | grep french) == "french" ]];then
    echo -e "\n\033[42mPour utiliser Darling, utilisez la commande : \033[2mdyld\033[0;42m.\N'utilisez pas d'arguments pour voir l'aide.\033[0m"
    echo -e "Attention, il manque des Frameworks. Les Frameworks disponibles sont dans le fichier \033[4m/etc/darling/dylib.conf\033[0m.\n"
  else
    echo -e "\n\033[42mTo use Darling, use command: \033[2mdyld\033[0;42m.\tUse without arguments to see help.\033[0m"
    echo -e "Warning, some Frameworks are missing. Frameworks are available in \033[4m/etc/darling/dylib.conf\033[0m file.\n"
  fi
}