post_install() {
  if [ -x /usr/lib/lightdm/lightdm/lightdm-set-defaults ] ; then
    /usr/lib/lightdm/lightdm/lightdm-set-defaults --keep-old --greeter=lightdm-kde-greeter || true
  fi
}

post_upgrade() {
 post_install
}

post_remove() {
  if [ -x /usr/lib/lightdm/lightdm/lightdm-set-defaults ] ; then
    /usr/lib/lightdm/lightdm/lightdm-set-defaults --remove --greeter=lightdm-kde-greeter || true
  fi
}
