post_install() {
  echo "-------------------------"
  echo "You need to restart cups."
  echo "-------------------------"
  echo
  echo "You need to add your user to the lp group."
}

post_upgrade() {
  echo "-------------------------"
  echo "You need to restart cups."
  echo "-------------------------"
}

post_remove() {
  echo "-------------------------"
  echo "You need to restart cups."
  echo "-------------------------"
}
