--- GNUmakefile.orig.orig	2012-02-07 21:36:41.132516812 +0100
+++ GNUmakefile.orig	2012-02-07 21:37:06.792377801 +0100
@@ -24,26 +24,14 @@
 	$(MAKE) -C src max
 
 install:
-ifdef RPM_BUILD_ROOT
 	install -d ${DESTDIR}${PREFIX}/bin
 	install -m 555 src/spar ${DESTDIR}${PREFIX}/bin/spar
 	install -d ${DESTDIR}$(MANPREFIX)/man1
 	install -m 555 src/spar.1 ${DESTDIR}${MANPREFIX}/man1/spar.1
-else
-	install -d ${PREFIX}/bin
-	install -m 555 src/spar ${PREFIX}/bin/spar
-	install -d $(MANPREFIX)/man/man1
-	install -m 555 src/spar.1 ${MANPREFIX}/man/man1/spar.1
-endif
 
 uninstall:
-ifdef RPM_BUILD_ROOT
 	rm ${DESTDIR}/${PREFIX}/bin/spar
 	rm ${DESTDIR}/${MANPREFIX}/man1/spar.1
-else
-	rm ${PREFIX}/bin/spar
-	rm ${MANPREFIX}/man/man1/spar.1
-endif
 
 help:
 	@echo "Try make, make install or make uninstall"
