#!/usr/bin/perl 
#===============================================================================
#
#         FILE: wgetpkg
#
#        USAGE: ./wgetpkg aurpkglist.txt
#               cat aurpkglist.txt | ./wgetpkg
#               echo "aurpackage" | ./wgetpkg
#
#  DESCRIPTION: Downloads AUR packages by name
#
#      OPTIONS: ---
# REQUIREMENTS: wget
#         BUGS: ---
#        NOTES: ---
#       AUTHOR: Andy Weidenbaum (archbaum@gmail.com)
# ORGANIZATION: ---
#      VERSION: 0.0.1
#      CREATED: 04/14/2013 06:23:04 PM
#     REVISION: 2
#===============================================================================

use strict;
use warnings;
use 5.016;

my %packages;

foreach my $package (<>) {
    chomp($package);
    $package =~ m/^(?<first_two_characters>\w\w)/;
    $packages{$package} = $+{first_two_characters};
}

foreach my $package (sort keys %packages) {
    my $tarball = "https://aur.archlinux.org/packages/$packages{$package}/${package}/${package}.tar.gz";
    system("wget $tarball");
}
