#!/bin/bash
# Logo Lyrarch
#
# Customize: http://www.network-science.de/ascii/
#
# example color:
# BLUE="\033[1;34m"
# RED="\033[1;31m"
# WHITE="\033[1;37m"
# GREEN="\033[1;32m"
# YELLOW="\033[1;33m"
#

# LOGO
echo -e " _                                     _     "
echo -e "( )                                   ( )    "
echo -e "| |     _   _  _ __   _ _  _ __   ___ | |__  "
echo -e "| |  _ ( ) ( )( '__)/'_\` )( '__)/'___)|  _ \`\\"
echo -e "| |_( )| (_) || |  ( (_| || |  ( (___ | | | |"
echo -e "(____/'\`\__, |(_)  \`\__,_)(_)  \`\____)(_) (_)"
echo -e "       ( )_| |                               "
echo -e "       \`\___/'                               "

