#!/bin/bash

kernver=${KERNVER:-$(uname -r)}
arch=${ARCH:-$(uname -m)}
arch=${arch/i686/i386}
catver=whatever



check_ext(){
  # here we are checking kernel's extramodules dir
    for r in /lib/modules/*; do
      s=${r##*/lib/modules/}
      if [[ ${s:0:3} = "ext" ]]; then
	if [[ `cat ${r}/version | grep -c ${kernver}` != 0 ]]; then
	 pakaver="${s#*-}"
	 destidir="${s}"
	 depextrmod="${s}"
	fi
	elif [[ ${s} = ${kernver} ]] && [[ ! -e ${r}/extramodules ]]; then
	 pakaver="${kernver}"
	 destidir="${kernver}/video"
	 depextrmod="null"
      fi
    done
}

install_module(){
    check_ext
    echo ""
    echo -e '\E[37;44m'"\033[1mBuilding catalyst-${pakaver} package for ${kernver} kernel ...\033[0m"
    echo "--------"
    if [ ! -d "/lib/modules/${kernver}/build" ]; then
      echo -e '\E[37;44m'"\033[1mKernel header files are absent: directory /lib/modules/${kernver}/build doesn't exist! Game over\033[0m"
      echo "--------"
      return 1
    fi
    workdir=$(mktemp -du /tmp/catalyst.XXXXXX)
    cp "/usr/share/ati/build_mod" "${workdir}" -R
    cd "$workdir"
    sed -i -e "s/_kernver=.*/_kernver=${kernver}/" PKGBUILD
    sed -i -e "s/_pakaver=.*/_pakaver=${pakaver}/" PKGBUILD
    sed -i -e "s|_destidir=.*|_destidir=${destidir}|" PKGBUILD
    sed -i -e "s/_depextrmod=.*/_depextrmod=${depextrmod}/" PKGBUILD

if [[ ${kernver:0:3} = "3.4" ]]; then
    echo ""
    echo -e '\E[37;44m'"\033[1mLooks like your kernel is 3.4 \033[0m"
    echo "Catalyst does not supporting it, but if you want"
    echo  "i may try to 'hack' it..."
    echo "--------"
    echo "You need to be logged in as root because i need to"
    echo "change kernel's source file (compat.h)."
    echo "After operation originall source file will be recall"
    echo "--------"
    echo -e '\E[37;44m'"\033[1mDo you want to try? [Y/n]\033[0m"
    read check34
	    if [ ${check34} = Y ]; then
		if [ "${LOGNAME}" != "root" ]; then
		      echo "You need to be a root to perform this operation. Quiting..."
		      rm -rf "${workdir}"
		      return 1
		fi

	       echo -e '\E[37;44m'"\033[1mPatching kernel's sources now\033[0m"
	       cp  /lib/modules/${kernver}/build/arch/x86/include/asm/compat.h  /lib/modules/${kernver}/build/arch/x86/include/asm/compat.h.back || return 1
	       cp 34_compat.patch  /lib/modules/${kernver}/build/arch/x86/include/asm/ || return 1
	       cd /lib/modules/${kernver}/build/arch/x86/include/asm || return 1
	       patch -Np0 -i 34_compat.patch || return 1

		cd "$workdir"

		echo "How many cpu cores you have got?"
		read cpu_no
		sed -i -e "s/CPUS_NUMBER/${cpu_no}/" 34_fire.patch

		sed -i -e "s/#patch -Np6 -i 34_fire.patch/patch -Np6 -i 34_fire.patch/" PKGBUILD

		/usr/bin/makepkg -c --asroot

		echo -e '\E[37;44m'"\033[1mOk. catalyst-${pakaver} package built succesfully. Installing ...\033[0m"
		echo -e '\E[37;44m'"\033[1mIf it's asking for password - type root password\033[0m"
		su - root -c "/usr/bin/pacman -Ud ${workdir}/catalyst-${pakaver}-${catver}-$(uname -m).pkg.tar"

		echo -e '\E[37;44m'"\033[1mRecalling kernel's sources patching...\033[0m"
	        mv /lib/modules/${kernver}/build/arch/x86/include/asm/compat.h.back  /lib/modules/${kernver}/build/arch/x86/include/asm/compat.h || return 1
		rm -rf "${workdir}"
		echo -e '\E[37;44m'"\033[1mDone.\033[0m"
	    else 
		      echo "Cleaning and quiting..."
		      rm -rf "${workdir}"
		      return 1
	    fi

  else
	if [ "${LOGNAME}" = "root" ]; then
	  if [ "${user}" = "root" ]; then
	  /usr/bin/makepkg -c --asroot || return 1
	    else	
	      chown ${user}:video ${workdir}
	      chown ${user}:video ${workdir}/* >> /dev/null 2>&1
	      su - ${user} -c "cd ${workdir} && /usr/bin/makepkg -c" || return 1
	  fi
	  else
	    /usr/bin/makepkg -c || return 1
	fi
	echo -e '\E[37;44m'"\033[1mOk. catalyst-${pakaver} package built succesfully. Installing ...\033[0m"
	if [ -e /usr/bin/sudo ]; then
	    echo -e '\E[37;44m'"\033[1mIf it's asking for password - type YOUR password\033[0m"
	    sudo /usr/bin/pacman -Ud ${workdir}/catalyst-${pakaver}-${catver}-$(uname -m).pkg.tar || return 1
	else
	    echo -e '\E[37;44m'"\033[1mIf it's asking for password - type root password\033[0m"
	    su - root -c "/usr/bin/pacman -Ud ${workdir}/catalyst-${pakaver}-${catver}-$(uname -m).pkg.tar" || return 1
	fi
	rm -rf "${workdir}"
	echo -e '\E[37;44m'"\033[1mDone.\033[0m"
  fi
}

build_all_modules(){
    if [ "${LOGNAME}" = "root" ]; then
      echo "Please specify your (unprivileged) user name:"
      echo "(or root if you want to build module for 3.4 kernel)"
      read user
    fi
    for p in /lib/modules/*; do
     if [ ${p:13:3} != "ext" ] && [ -d $p/build ] && [ -d $p/kernel ]; then
      /usr/bin/catalyst_build_module ${p##*/lib/modules/} ${user}
     fi
    done
}

remove_module(){
    echo "Removing unused catalyst-{kernver} packages ..."
    for p in /lib/modules/*; do
      if [[ ${p:13:3} != "ext" ]] && [[ ! -d $p/kernel ]] && [[ -e $p/video/fglrx.ko.gz ]]; then
	      /usr/bin/pacman -Rd --noconfirm catalyst-${p##*/lib/modules/}
      elif [[ ${p:13:3} = "ext" ]] && [[ ! -e $p/version ]] && [[ -e $p/fglrx.ko.gz ]]; then
	      /usr/bin/pacman -Rd --noconfirm catalyst-${p##*/lib/modules/extramodules-}
      fi
    done
}

remove_all_modules(){
    for p in /lib/modules/*; do
      if [[ ${p:13:3} != "ext" ]] && [[ -e $p/video/fglrx.ko.gz ]]; then
	      /usr/bin/pacman -Rd --noconfirm catalyst-${p##*/lib/modules/}
      elif [[ ${p:13:3} = "ext" ]] && [[ -e $p/fglrx.ko.gz ]]; then
	      /usr/bin/pacman -Rd --noconfirm catalyst-${p##*/lib/modules/extramodules-}
      fi
    done
}


case "$1" in
    help|--help)
        echo "usage: $0 {version|all|remove|remove_all|}"
        echo "- with no specified kernel version it will use the current kernel version to build module"
	echo "- all will try to build fglrx modules for all working system's kernels"
        echo "- remove is removing unused catalyst-{kernver} packages"
        echo "- remove_all is removing all catalyst-{kernver} packages"
        ;;
    all)
	build_all_modules
	;;
    remove)
        remove_module
        ;;
    remove_all)
        remove_all_modules
        ;;
    *)
        test "$1" != "" && kernver="$1"
	if [ "$2" != "" ]; then user="$2"
          elif [ "${LOGNAME}" = "root" ]; then
	      echo "Please specify your (unprivileged) user name:"
	      echo "(or root if you want to build module for 3.4 kernel)"
	      read user
	fi
        install_module
        ;;
esac

