
KERNEL_VERSION=whatever
EXTRAMODULES=whatever
WHERE_MODULES=usr

if [ $WHERE_MODULES = "usr" ]; then WHEREM=usr/lib/modules
 elif [ $WHERE_MODULES = "lib" ]; then WHEREM=lib/modules
fi

dep_extr_mod(){
if [ $EXTRAMODULES != null ]; then
    depmod $(cat $WHEREM/$EXTRAMODULES/version)
else
    depmod $KERNEL_VERSION
fi
}

post_install() {
    dep_extr_mod
}

post_upgrade() {
    dep_extr_mod
}

post_remove() {
    dep_extr_mod
}
