fix_permissions()
{
  # the x2goprint command can only be run by users that are in group x2goprint
  # The 0700 permission will start cups-x2go spool with root privileges, otherwise
  # CUPS starts it as user and fails...
  test -f /usr/lib/cups/backend/cups-x2go && \
    chown root root /usr/lib/cups/backend/cups-x2go && \
    chmod 0700 /usr/lib/cups/backend/cups-x2go
}

post_install()
{
  fix_permissions
}

post_upgrade()
{
  fix_permissions
}

