# Generated by Xyne::Arch::CPAN 0.07

pkgname=perl-math-random-oo
pkgver=0.210.0
pkgrel=1
pkgdesc="Consistent object-oriented interface for generating random numbers"
arch=('i686 x86_64')
url="http://search.cpan.org/dist/Math-Random-OO/"
license=('perl')
source=('http://search.cpan.org/CPAN/authors/id/D/DA/DAGOLDEN/Math-Random-OO-0.21.tar.gz')
md5sums=('3867a231685468a4252095612c5722cc')
sha256sums=('bd96976acf9a8361622049423e649f386d3d7d8ce7eda74fb4d3b9c3aca90950')
depends=('perl-class-accessor' 'perl-params-validate>=0.760.0' 'perl-test-mockrandom>=0.950.0' 'perl-test-simple' 'perl-test-number-delta>=0.140.0' 'perl>=5.0.6')
options=(!emptydirs)

build() {
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Makefile.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor || return 1
    make  || return 1
    make install DESTDIR="${pkgdir}" || return 1

  else
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Build.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Build.PL INSTALLDIRS=vendor || return 1
    ./Build  || return 1
    ./Build install destdir=${pkgdir} || return 1

  else
    echo "error: failed to detect build method for $pkgname"
    echo "you may be able to fix this by editing the PKGBUILD"
    return 1
  fi fi

  # remove perllocal.pod and .packlist
  find ${pkgdir} -name perllocal.pod -delete
  find ${pkgdir} -name .packlist -delete
}

# vim:set ts=2 sw=2 et:

