post_install() {
  echo " add the following in your .emacs file:"
  echo "    (add-to-list 'load-path \"/usr/share/emacs/site-lisp/yas\")"
  echo "    (require 'yasnippet) ;; not yasnippet-bundle"
  echo "    (yas/initialize)"
  echo "    (yas/load-directory \"/usr/share/emacs/site-lisp/yas/snippets\")"
}

post_upgrade() {
   post_install  
}
pre_remove() {
   echo "If you like remove the yasnippet stuff from your .emacs"
}