pkgname=contacts
 	
post_install() {
usr/sbin/gconfpkg --install ${pkgname}
gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
update-desktop-database -q
}
	
pre_upgrade() {
pre_remove $1
}
 	
post_upgrade() {
gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
post_install $1
}
	
pre_remove() {
usr/sbin/gconfpkg --uninstall ${pkgname}
post_install $1
}
 	
post_remove() {
update-desktop-database -q
}
