post_install() {
cat << MEOW
 >>> Important: you must mount an optical disk in your LabelFlash drive before launching this program; otherwise, it will claim "Labelflash Drive is not found."
 >>>
 >>> Information: Labelflash Index Maker uses "templates" to structure its UI. To customize them, see the contents of "\$HOME/.labelflash-index-maker/wine/drive_c/Program Files$(case "$(uname -m)" in x86_64) echo " (x86)" ;; esac)/labelflash-index-maker/", which will be created the first time you run /usr/bin/labelflash-index-maker.
MEOW
}
