#!/bin/bash
pl() {
	LANG_whattodo="Co chcesz zrobic?"
	LANG_selectprogram="Wybierz program do uruchomienia:"
	LANG_entercommand="Wpisz komende uruchamiajaca program:"
	LANG_entername="Wpisz nazwe programu:"
	LANG_launch="Uruchomic"
	LANG_add="Dodac program"
	LANG_exit="Wyjsc"
	LANG_whattodoADD="Wykrylismy, ze nie ustawiles/as zadnych programow. Co chcesz zrobic?"
	LANG_yes="Tak"
	LANG_no="Nie"
	LANG_dontask="Nie pytaj wiecej"
	LANG_i3install="Czy ustawic skrot klawiszowy w i3wm? (\$mod+p)"
}

en() {
	LANG_whattodo="What would you like to do?"
	LANG_selectprogram="Select program to launch:"
	LANG_entercommand="Enter command that launches program:"
	LANG_entername="Enter program name:"
	LANG_launch="Launch"
	LANG_add="Add program"
	LANG_exit="Exit"
	LANG_whattodoADD="We've determined that you haven't set any programs. What would you like to do?"
	LANG_yes="Yes"
	LANG_no="No"
	LANG_dontask="Don't ask anymore"
	LANG_i3install="Do you want me to set up shortcut for kailauncher in i3wm? (\$mod+p)"
}

confdir="$HOME/.kailauncher"
run() {
	ans="$(dmenu -p "$LANG_selectprogram"<"$confdir/names")"
	echo "ans=\"$ans\"; case \"$ans\" in
	$(cat "$confdir/commands")
	*) $ans ;;
	esac" > /tmp/land-run.sh
	bash /tmp/land-run.sh
	rm /tmp/land-run.sh
}

add() {
	d="$(echo | dmenu -p "$LANG_entername")"
	e=`cat -n  "$confdir/names" | tail -1 | awk '{print $1}'`
	e=$((e+1))
	[ "x$(echo "$d" | sed 's/ *//g')" == "x" ] && exit;

	b="$(echo | dmenu -p "$LANG_entercommand")"
	c=`cat -n  "$confdir/commands" | tail -1 | awk '{print $1}'`
	c=$((c+1))
	[ "x$(echo "$b" | sed 's/ *//g')" == "x" ] && exit;

	echo "$c*) $b ;;" >>  "$confdir/commands"
	echo "$e - $d" >>  "$confdir/names" 
}

main_menu() {
	ans="$(echo -e "1 - $LANG_launch\n2 - $LANG_add\n3 - $LANG_exit" | dmenu -p "$LANG_whattodo")"
	case "$ans" in
		1*) run ;;
		2*) add ;;
		3*) exit ;;
	esac
}

add_menu() {
	ans="$(echo -e "1 - $LANG_add\n2 - $LANG_exit" | dmenu -p "$LANG_whattodoADD")"
	case "$ans" in
		1*) add ;;
		2*) exit ;;
	esac
}

i3_install() {
	(echo; echo "bindsym \$mod+p exec \"$(readlink -f "$0")\"") >> ~/.i3/config
	echo "i3ask=\"no\"" >> "$confdir/config"
	i3-msg reload;
}

i3_menu() {
	ans="$(echo -e "1 - $LANG_yes\n2 - $LANG_no\n3 - $LANG_dontask" | dmenu -p "$LANG_i3install")"
	case "$ans" in
		1*) i3_install ;;
		2*) return ;;
		3*) echo "i3ask=\"no\"" >> "$confdir/config" ;;
	esac
}



mkconfig() {
	cat >"$confdir/config" << EOF
language=en
EOF
}

load_config() {
	[ -d "$confdir" ] || mkdir "$confdir"
	[ -f "$confdir/names" ] || touch "$confdir/names";
	[ -f "$confdir/commands" ] || touch "$confdir/commands";
	[ -f "$confdir/config" ] || mkconfig
	source "$confdir/config"
}

load_config
case "$language" in
	"pl") pl ;;
	"en") en ;;
	*) en ;;
esac
[ "x$(pgrep i3)" != "x" ] && [ "x$i3ask" != "xno" ] && i3_menu 
[ -s "$confdir/names" ] && main_menu || add_menu
