#!/bin/bash

# general config
. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/bin/monkey`
case "$1" in
  start)
    stat_busy "Starting Monkey HTTP Daemon"
      [ -z "$PID" ] && /usr/bin/monkey -D 2>&1
    if [ $? -gt 0 ]; then
      echo $PID > /var/run/monkey.pid
      add_daemon monkey
      stat_done
    else
      stat_fail
    fi
    ;;
  stop)
    stat_busy "Stopping Monkey HTTP Daemon"
    [ ! -z "$PID" ] && kill $PID &>/dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon monkey
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 3
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
