post_install() {
  cat << EOF
Add the keyword brother2 to your /etc/sane.d/dll.conf for using the scanner.

***
You might also need to add your scanner to /etc/udev/rules.d/53-sane.rules
to be able to scan as user. This entry is for MFC-8860DN:
  
ATTRS{idVendor}=="04f9", ATTRS{idProduct}=="01a6", MODE="0664", GROUP="scanner", ENV{libsane_matched}="yes"

Use lsusb to find your vendor and device id (ID vendor:device )
EOF
}

# vim:set ts=2 sw=2 et:
