post_install() {
    echo
    echo ">>> Run \`grid-updates --patch-tahoe\` to activate this feature"
    echo ">>> Read the man page for detailed usage"
    echo
    chmod -R 777 /usr/lib/python2.7/site-packages/allmydata/web
}

post_upgrade() {
    post_install
}

pre_remove() {
    echo
    echo ">>> Running \`grid-updates --undo-patch-tahoe\` ..."
    /usr/bin/grid-updates --undo-patch-tahoe 2>/dev/null
    echo
    chmod -R 755 /usr/lib/python2.7/site-packages/allmydata/web
}
