post_install() {
  echo ""
  echo "==> Installation notes:"
  echo " This package also installs bfint, a simple brainfuck interpreter, as the following commands:"
  echo " * bfint8"
  echo " * bfint16"
  echo " * bfint32"
  echo " * bfint64"
  echo " depending on the cell size desired"
  echo ""
  echo " awib itself is shipped both as a binary (the awib command) and a script (the awib.b command)."
  echo ""
}

# vim:set ts=2 sw=2 et:
