pkgname=bibleanalyzer

post_install() {
  echo ""
  echo "Please make sure you have the following directory to run the application:"
  echo "/home/[username]/Documents"
  echo "If you have an error after starting the program, please delete the ~/Documents/BibleAnalyzer/Modules folder from previous installations."
  echo "New modules can be downloaded from the website http://www.bibleanalyzer.com/modules"
  echo ""
  }
  
  post_upgrade() {
    post_install $1
    }
