#!/bin/sh

# Modified and improved version of Cisco's Script

# Force PT to use the included QT version
# PT will crash with Arch's version of QT!

LD_LIBRARY_PATH="/opt/pt/lib" /opt/pt/bin/PacketTracer6 "$@"

