# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Jason St. John <jstjohn .. purdue . edu>

_gemname=opennebula
pkgname="ruby-${_gemname}"
pkgver=4.12.1
pkgrel=1
pkgdesc='OpenNebula Client API'
arch=('any')
url='https://rubygems.org/gems/opennebula/'
license=('Apache')
depends=('ruby' 'ruby-nokogiri' 'ruby-json')
options=('!emptydirs')
source=("https://rubygems.org/downloads/${_gemname}-${pkgver}.gem")
noextract=("${_gemname}-${pkgver}.gem")
sha512sums=('5dddc9ff6038b27243d44de88543e854473c4ad47c4e41aa4a6d5d5df666ff3bd0b8fb34fa308248cf0fc60dd13189a74b4363a252e4fbfd6d401740b56ba644')

package() {
	local _gemdir="$(ruby -e'puts Gem.default_dir')"
	gem install --ignore-dependencies --no-user-install -i "${pkgdir}/${_gemdir}" -n "${pkgdir}/usr/bin" "${_gemname}-${pkgver}.gem"
	rm "${pkgdir}/${_gemdir}/cache/${_gemname}-${pkgver}.gem"
}
