#!/bin/bash 

# Set path if path not set (if called from /etc/rc)
case $PATH in
    "") PATH=/bin:/usr/bin:/sbin:/etc
        export PATH ;;
esac

# Save LD_LIBRARY_PATH
SAVE_LLP=$LD_LIBRARY_PATH

RETVAL=0
ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe
ORACLE_OWNER=oracle
ORACLE_SID=XE
LSNR=$ORACLE_HOME/bin/lsnrctl
SQLPLUS=$ORACLE_HOME/bin/sqlplus
SU=/bin/su
export ORACLE_HOME
export ORACLE_SID
export ORACLE_BASE=/u01/app/oracle
export PATH=$ORACLE_HOME/bin:$PATH
LOG="$ORACLE_HOME_LISTNER/listener.log"

export LC_ALL=C

if [ $(id -u) != "0" ]
then
    echo "You must be root to run the configure script.  Login as root and then run the configure script."
    exit 1
fi

CONFIG_NAME=oracle-xe
CONFIGURATION="/etc/sysconfig/$CONFIG_NAME"

if [ -f /etc/arch-release ]
then

    init_status() {
		return 0
    }
    exit_status() {
		exit $?
    }
    success_status() {
		success
		echo
    }
    failure_status() {
		failure $?
		echo
    }
fi
    
success () {
	echo " [OK]"
}

failure () {
 	echo " [FAILED]" 
}

# Source configuration

[ -f "$CONFIGURATION" ] && . "$CONFIGURATION"

init_status

#
# if_fail()
#
# Evaluates return codes.  If 0, prints "OK", if 1, prints "Failed"
# and exits.  If 2, status is "already done" and nothing is printed.
# The rest of the functions in here all honor this convention.
#
if_fail() {
	RC="$1"
	REASON="$2"
	if [ "$RC" = "0" ]
	then
		return
	elif [ "$RC" = "2" ]
	then
		return
	fi
	failure_status "${REASON}"
	exit 1
}


#
# write_sysconfig()
#
# Writes the system configuration
#
write_sysconfig()
{
	cat >"$CONFIGURATION" <<EOF
    
#This is a configuration file for automatic starting of the Oracle
#Database and listener at system startup.It is generated By running
#'/etc/init.d/oracle-xe configure'.Please use that method to modify this 
#file

# ORACLE_DBENABLED:'true' means to load the Database at system boot.
ORACLE_DBENABLED=${ORACLE_DBENABLED:-false}

# LISTENER_PORT: Database listener
LISTENER_PORT=${LISTENER_PORT}

# HTTP_PORT : HTTP port for Oracle Application Express
HTTP_PORT=${HTTP_PORT}

# Configuration : Check whether configure has been done or not
CONFIGURE_RUN=${CONFIGURE_RUN}

EOF
	
    if [ $? != 0 ]
	then
		return 1
	fi
	return 0
}




# configure_perform()
#
# Instantantiate listener.ora,tnsnames.ora,and create the database,
# sets the password,start the listener,and adds database to inittab
# if necessary

configure_perform()
{
	
    sed -i "s/%sga_target%/$SGA_SIZE/g" $ORACLE_HOME/config/scripts/init.ora
    sed -i "s/%pga_aggregate_target%/$PGA_SIZE/g" $ORACLE_HOME/config/scripts/init.ora
    /bin/chown oracle:dba $ORACLE_HOME/config/scripts/init.ora
	
    sed -i "s/%sga_target%/$SGA_SIZE/g" $ORACLE_HOME/config/scripts/initXETemp.ora
    sed -i "s/%pga_aggregate_target%/$PGA_SIZE/g" $ORACLE_HOME/config/scripts/initXETemp.ora
	/bin/chown oracle:dba $ORACLE_HOME/config/scripts/initXETemp.ora

    sed -i "s/%hostname%/`hostname`/g" $ORACLE_HOME/network/admin/listener.ora
    sed -i "s/%port%/$LISTENER_PORT/g" $ORACLE_HOME/network/admin/listener.ora
    /bin/chown oracle:dba $ORACLE_HOME/network/admin/listener.ora

    sed -i "s/%hostname%/`hostname`/g" $ORACLE_HOME/network/admin/tnsnames.ora
    sed -i "s/%port%/$LISTENER_PORT/g" $ORACLE_HOME/network/admin/tnsnames.ora
    /bin/chown oracle:dba $ORACLE_HOME/network/admin/tnsnames.ora

    sed -i "s/%httpport%/$HTTP_PORT/g" $ORACLE_HOME/config/scripts/postDBCreation.sql
    /bin/chown oracle:dba $ORACLE_HOME/config/scripts/postDBCreation.sql

    if test $LISTENER_PORT -ne 1521
    then
	if [ -f /tmp/local_listener ]
	then
	cat >/tmp/local_listener$$ <<EOF
###########################################
# Registration of instance with listsner
###########################################
local_listener="(ADDRESS = (PROTOCOL=TCP) (HOST=%hostname%) (PORT=%port%))"
EOF
	/bin/chmod 664 /tmp/local_listener$$
	cat /tmp/local_listener$$ >> $ORACLE_HOME/config/scripts/init.ora
	else
	cat >/tmp/local_listener <<EOF
###########################################
# Registration of instance with listsner
###########################################
local_listener="(ADDRESS = (PROTOCOL=TCP) (HOST=%hostname%) (PORT=%port%))"
EOF
	/bin/chmod 664 /tmp/local_listener
	cat /tmp/local_listener >> $ORACLE_HOME/config/scripts/init.ora
	fi

	if test -f /tmp/local_listener
	then
		rm -fr /tmp/local_listener
	elif test -f /tmp/local_listener$$
	then
		rm -fr /tmp/local_listener$$
	fi
	
	sed -i "s/%port%/$LISTENER_PORT/g" $ORACLE_HOME/config/scripts/init.ora
	sed -i "s/%hostname%/`hostname`/g" $ORACLE_HOME/config/scripts/init.ora
        /bin/chown oracle:dba $ORACLE_HOME/config/scripts/init.ora

    fi

   sed -i "s/%httpport%/$HTTP_PORT/g" $ORACLE_HOME/config/scripts/gettingstarted.sh
    /bin/chown oracle:dba $ORACLE_HOME/config/scripts/gettingstarted.sh

    homedir=`echo $HOME`
    if [ "$homedir" = "/root" ]
    then
        homedir=`sh -c "echo ~$USER"`
    fi

    if [ -f $ORACLE_HOME/bin/tnslsnr ]  
    then
     	echo -n "Starting Oracle Net Listener..."
       	su -s /bin/bash $ORACLE_OWNER -c "$LSNR  start" > /dev/null 2>&1
	echo "Done"
    fi

    echo -n "Configuring database..."
    su -s /bin/bash $ORACLE_OWNER -c "$ORACLE_HOME/config/scripts/XE.sh" > /dev/null 2>&1
    if [ -d $ORACLE_HOME/config/log ]
    then
            err=`grep "ORA-44410" $ORACLE_HOME/config/log/*.log`
            out=`grep "ORA-01034" $ORACLE_HOME/config/log/*.log`
            if [ "$err" != "" ] || [ "$out" != "" ]
            then
                echo
                echo "Database Configuration failed.  Look into $ORACLE_HOME/config/log for details"
                exit 1
            fi
     fi

    pmon=`ps -ef | egrep pmon_$ORACLE_SID'\>' | grep -v grep`

    if [ "$pmon" = "" ];
    then
        echo
        echo "Database Configuration failed.  Look into $ORACLE_HOME/config/log for details"
        exit 1
    fi

    echo  alter user sys identified by \"$ORACLE_PASSWORD\"\; | su -s /bin/bash $ORACLE_OWNER -c "$SQLPLUS -s / as sysdba" > /dev/null 2>&1
    echo  alter user system identified by \"$ORACLE_PASSWORD\"\; | su -s /bin/bash $ORACLE_OWNER -c "$SQLPLUS -s / as sysdba" > /dev/null 2>&1

    echo @$ORACLE_HOME/apex/apxxepwd.sql \"$ORACLE_PASSWORD\"\; | su -s /bin/bash $ORACLE_OWNER -c "$SQLPLUS -s / as sysdba" > /dev/null 2>&1
    echo "Done"

    /bin/chmod -R 640 /u01/app/oracle/oradata/XE
    /bin/chmod 750 /u01/app/oracle/oradata/XE
    /bin/chmod -R 775 /u01/app/oracle/diag
    rm -fr $ORACLE_HOME/config/seeddb 

    if [ -f /etc/oratab ]
    then
	echo "XE:$ORACLE_HOME:N" >> /etc/oratab
    else
   	echo "XE:$ORACLE_HOME:N" >> /etc/oratab
	/bin/chown oracle:dba /etc/oratab
	/bin/chmod 664 /etc/oratab
    fi
    
   echo -n "Starting Oracle Database 11g Express Edition instance..."
   pmon=`ps -ef | egrep pmon_$ORACLE_SID'\>' | grep -v grep`

   if [ "$pmon" = "" ];
   then
	   su -s /bin/bash  $ORACLE_OWNER -c "$SQLPLUS -s /nolog @$ORACLE_HOME/config/scripts/startdb.sql" > /dev/null 2>&1
   fi
   echo "Done"

   echo "Installation completed successfully."

	
   return 0
}

#
#configure_ask()
#
# Ask configuration questions,setting the variables.
#

configure_ask()
{
	cat <<EOF

Oracle Database 11g Express Edition Configuration
-------------------------------------------------
This will configure on-boot properties of Oracle Database 11g Express 
Edition.  The following questions will determine whether the database should 
be starting upon system boot, the ports it will use, and the passwords that 
will be used for database accounts.  Press <Enter> to accept the defaults. 
Ctrl-C will abort.

EOF
    #get the http port value
	while :
	do
	    while [ 1 ]
	    do
            echo -n Specify the HTTP port that will be used for Oracle Application Express [8080]:
            read LINE
            if [ -z $LINE ]
            then
                LINE=8080
            fi
	    echo
	    port=`netstat -n --tcp --listen | grep :$LINE | awk -F: '{print $4}' | sed 's/ //g'`
            if [ "$port" = "$LINE" ]
            then
		if [ ! -z $1 ]
		then
			echo
			echo "Port $LINE appears to be in use by another application. Specify a different
port and retry the configuration."
			trap "rm -fr $1" exit
			exit
		fi
                echo "Port $port appears to be in use by another application. Specify a different port."
            else
                break;
            fi
        done

	    case "$LINE" in
	    "")
            break
            ;;
        *[^0-9]*)
            echo "Invalid http port: $LINE"
            ;;
        *)
            HTTP_PORT=$LINE
            break
            ;;
	    esac
	done
	
    #get the listener port value
	while : 
	do
        while [ 1 ]
        do
            echo -n Specify a port that will be used for the database listener [1521]:
            read LINE
            if [ -z $LINE ]
            then
                LINE=1521
            fi
            echo
            port=`netstat -n --tcp --listen | grep :$LINE | awk -F: '{print $4}' | sed 's/ //g'`
            if [ "$port" = "$LINE" ]
            then	
		if [ ! -z $1 ]
		then
			echo
			echo "Port $LISTENER_PORT appears to be in use by another application. Specify a different
port and retry the configuration."
			trap "rm -fr $1" exit
			exit
		fi
                echo Port $port appears to be in use by another application.\
                Specify a different port.
            else
                break;
            fi
        done
	          
        case "$LINE" in
        "")
            break
            ;;
        *[^0-9]*)
            echo "Invalid port: $LINE" >&2
            ;;
	    *) 
            	if [ "$HTTP_PORT" != "$LINE" ]
	        then
        	    LISTENER_PORT=$LINE
                    break
	        else
        	    echo Database listener cannot be configured on the same port as Oracle Application Express.
	        fi
            ;;
	    esac
	done
	
	#get the sga size
	while : 
	do
        echo 
        while [ 1 ]
        do
            echo -n Specify your sga size [128M]:
            read LINE
            if [ -z $LINE ]
            then
                LINE="128M"
            fi
            break;
        done
	          
        case "$LINE" in
        "")
            break
            ;;
       
	    *) 
            
        SGA_SIZE=$LINE
        break
            ;;
	    esac
	done
    
    #get the pga_aggregate_target size
	while : 
	do
        echo 
        while [ 1 ]
        do
            echo -n Specify your pga size [96M]:
            read LINE
            if [ -z $LINE ]
            then
                LINE="96M"
            fi
            break;
        done
	          
        case "$LINE" in
        "")
            break
            ;;
       
	    *) 
            
        PGA_SIZE=$LINE
        break
            ;;
	    esac
	done
    
    #get the database password
	    while :
	    do
	    echo -n "Specify a password to be used for database accounts.  Note that the same
password will be used for SYS and SYSTEM.  Oracle recommends the use of 
different passwords for each database account.  This can be done after 
initial configuration:"
	     while [ 1 ]
             do
	     /bin/stty -echo > /dev/null 2>&1
	     temp=`echo $IFS`
             export IFS="\n"	
	     while [ 1 ]
  	     do
	     read LINE
             while [ -z "$LINE" ]
	     do
		 echo
		 echo -n "Password can't be null. Enter password:"  
	         read LINE
	     done

	     result=`expr index "$LINE" [\'\"]`
	     if [ $result != 0 ];
	     then
             	echo 
		        echo -n "The password you entered contains invalid characters. Enter password:"	
	     else
		break
	     fi
	     done
		echo
		echo -n "Confirm the password:"
	        read LINE1
		echo
                if [ "$LINE" != "$LINE1" ];
		then
			if [ ! -z $1 ]
			then
				echo
				echo "Passwords do not match. Specify the same password for both ORACLE_PASSSWORD and 
ORACLE_CONFIRM_PASSWORD, and retry the configuration."
				trap "rm -fr $1" exit
				exit
			fi
			echo    
			echo -n "Passwords do not match.  Enter the password:"
		else
			break
		fi
	done
            /bin/stty echo > /dev/null 2>&1
            ORACLE_PASSWORD=$LINE
	    export IFS=$temp
            break;
	done

	while :
	do
        if [ "$ORACLE_DBENABLED" = "true" ]
        then
            CUR=y
        else
            CUR=n
        fi
	echo
        echo -n "Do you want Oracle Database 11g Express Edition to be started on boot (y/n) [y]:"
        read LINE
	if [ -z $LINE ]
	then
		ORACLE_DBENABLED=true
	fi
        echo
        case "$LINE" in
        "") 
            break
            ;;
        y|Y)
            ORACLE_DBENABLED=true
            break
            ;;
        n|N)
            ORACLE_DBENABLED=false
            break
            ;;
        *)
            echo "Invalid response: $LINE " >&2
            break
        esac
	done
}

configure() {
	if test -f "$CONFIGURATION"
	then
		echo "Oracle Database 11g Express Edition is already configured"
	exit 1
	fi
	configure_ask
	configure_perform
	CONFIGURE_RUN=true
	write_sysconfig
	echo To access the Database Home Page go to \"http://127.0.0.1:$HTTP_PORT/apex\"
}

configure
