--- Makefile	2009-08-27 14:39:48.000000000 +0200
+++ Makefile.corrected	2009-08-27 14:46:37.000000000 +0200
@@ -34,7 +34,10 @@
 	$(RM) core *.o unhtml
 
 install:
-	cp unhtml /usr/local/bin
-	chmod 755 /usr/local/bin/unhtml
-	cp unhtml.1 /usr/local/man/man1
-	chmod 644 /usr/local/man/man1/unhtml.1
+	mkdir -p $(DESTDIR)/usr/bin
+	cp unhtml $(DESTDIR)/usr/bin
+	chmod 755 $(DESTDIR)/usr/bin/unhtml
+	mkdir -p $(DESTDIR)/usr/share/man/man1/
+	cp unhtml.1 $(DESTDIR)/usr/share/man/man1/
+	chmod 644 $(DESTDIR)/usr/share/man/man1/unhtml.1
+
