#!/usr/bin/ash

run_hook ()
{
    if [ -s /etc/chkcryptoboot/chkcryptoboot.conf ]; then
	source /etc/chkcryptoboot/chkcryptoboot.conf
	if [ $BOOTMODE = "mbr" ]; then
	    if [ -n $BOOTDISK -a -s /etc/chkcryptoboot/disk-head.sha256 ]; then
		dd if=$BOOTDISK of=/etc/chkcryptoboot/disk-head bs=512 count=1
		cd /etc/chkcryptoboot
		sha256sum -c disk-head.sha256
		if [ $? -ne 0 ]; then
		    echo -e "\nCHKCRYPTOBOOT ALERT!\n"
		    echo -e "CHANGES HAVE BEEN DETECTED IN YOUR BOOT LOADER INSTALLED IN YOUR MBR!\n"
		    echo -e "YOU ARE STRONGLY ADVISED NOT TO ENTER YOUR ROOT CONTAINER PASSWORD!"
		else
		    echo "Your GRUB mbr code hash was verified successfully."
		fi
	    fi
	elif [ $BOOTMODE = "efi" ]; then
	    if [ -n $ESP -a -s /etc/chkcryptoboot/efistub.sha256 ]; then
		mount $ESP
		sha256sum -c /etc/chkcryptoboot/efistub.sha256
		if [ $? -ne 0 ]; then
		    echo -e "\nCHKCRYPTOBOOT ALERT!\n"
		    echo -e "CHANGES HAVE BEEN DETECTED IN YOUR GRUB EFISTUB!\n"
		    echo -e "YOU ARE STRONGLY ADVISED NOT TO ENTER YOUR ROOT CONTAINER PASSWORD!"
		else
		    echo "Your GRUB efistub hash was verified successfully."
		fi
	    fi
	else
	    echo -e "\nCHKCRYPTOBOOT WARNING!\n"
	    echo -e "YOUR CHKCRYPTOBOOT CONFIGURATION CONTAIN ERRORS!"
	fi
    fi
}

run_cleanuphook ()
{
    if [ -s /etc/chkcryptoboot/chkcryptoboot.conf ]; then
	source /etc/chkcryptoboot/chkcryptoboot.conf
	if [ $BOOTMODE = "efi" ]; then
	    if [ -n $ESP ]; then
		umount $ESP
	    fi
	fi
    fi
}
