post_install() {
	export GCONF_CONFIG_SOURCE=`/usr/bin/gconftool-2 --get-default-source`
	echo -n ":: Installing gtk-window-decorator schema... "
	/usr/bin/gconftool-2 --makefile-install-rule /usr/share/gconf/schemas/gwd.schemas > /dev/null
	if [ $? -gt 0 ]; then
		echo "Failed"
	else
		echo "OK"
	fi
	echo -n ":: Setting gtk-window-decorator as default decorator... "
	sudo gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.defaults --type string --set /apps/compiz-1/plugins/decor/screen0/options/command "gtk-window-decorator --replace" > /dev/null
	if [ $? -gt 0 ]; then
		echo "Failed"
	else
		echo "OK"
	fi
	echo -e "\nPlease modify ~/.config/compiz-1/compizconfig/config to contain the following:\n\n[gnome_session]\nbackend = gconf\n\nAlternatively set it using CompizConfig Settings Manager (install via the ccsm-dev package) by navigating to preferences > backend." | fold -s
	kill -s HUP `pidof /usr/bin/gconfd-2` > /dev/null 2>&1
	update-desktop-database -q     
}
     
pre_remove() {
	export GCONF_CONFIG_SOURCE=`/usr/bin/gconftool-2 --get-default-source`
	/usr/bin/gconftool-2 --makefile-uninstall-rule /usr/share/gconf/schemas/gwd.schemas >/dev/null
}
     
post_remove() {
	kill -s HUP `pidof /usr/bin/gconfd-2` > /dev/null 2>&1
	update-desktop-database -q
}
