post_install() {
	export GCONF_CONFIG_SOURCE=`/usr/bin/gconftool-2 --get-default-source`
	echo -ne "\n:: Setting gtk-window-decorator as default decorator... "
	sudo gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.defaults --type string --set /apps/compiz-1/plugins/decor/screen0/options/command "gtk-window-decorator --replace" > /dev/null
	if [ $? -gt 0 ]; then
		echo "Failed"
	else
		echo "OK"
	fi
	echo -e "\nTo use the GConf backend, select it in the preferences section of CompizConfig Settings Manager.\n" | fold -s
	kill -s HUP `pidof /usr/bin/gconfd-2` > /dev/null 2>&1
	update-desktop-database -q     
}
     
post_remove() {
	kill -s HUP `pidof /usr/bin/gconfd-2` > /dev/null 2>&1
	update-desktop-database -q
}
