*** Makefile	2013-07-19 00:11:08.682666649 -0400
--- Makefile.new	2013-07-19 00:11:11.916030957 -0400
***************
*** 2,10 ****
  MODULES = println.pm puts.pm lncount.pm putfileln.pm putfile.pm pprint.pm pprintln.pm
  PKGNAME = perl-printer
  VERSION = '0.71.0_rc1'
! DOCS = Release_notes license
  PKGFILES = $(MODULES) $(DOCS) Makefile
  all :
  
  install : 
  	for files in $(MODULES) ;\
--- 2,12 ----
  MODULES = println.pm puts.pm lncount.pm putfileln.pm putfile.pm pprint.pm pprintln.pm
  PKGNAME = perl-printer
  VERSION = '0.71.0_rc1'
! DOCS = changelog license
  PKGFILES = $(MODULES) $(DOCS) Makefile
+ 
  all :
+ 	@echo "just run \`make install'"
  
  install : 
  	for files in $(MODULES) ;\
