#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/usr/lib/X11/xinit/.Xresources
sysmodmap=/usr/lib/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
/usr/bin/xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
/usr/bin/xmodmap $sysmodmap
fi

if [ -f $userresources ]; then
/usr/bin/xrdb -merge $userresources
fi

if [ -f $usermodmap ]; then
/usr/bin/xmodmap $usermodmap
fi

# run Xmetisse
geom=`xdpyinfo | awk '$1 == "dimensions:" { print $2 }'`
/usr/bin/Xmetisse -geometry $geom -ac :1 &
PID=$!

metisse-start-fvwm -- -d :0

/bin/kill PID

