post_install() {
  echo "  To play JediOutcastLinux:"
  echo " "
  echo "  Make sure you got the original game installed and patched to version 1.04,"
  echo "  and copy all contents of the Original Gamefolder 'GAMEROOT/GameData/base' to '/usr/share/jedioutcastlinux/base'"
}

post_remove() {
  echo "  To remove Media Files:"
  echo " "
  echo "  Remove the folder '/usr/share/jedioutcastlinux/base', its contents and the parent folder."
}
