post_install()
{

   PATH="$PATH:/sbin"
   ldconfig -n /usr/lib/apache

/bin/cat <<THEEND

Setting it up
-------------

1. add the following to /etc/httpd/conf/httpd.conf
       LoadModule bw_module       lib/apache/mod_bw.so

2. add the module settings to httpd.conf
       <IfModule mod_bw.c>
          #Some bandwidth control parameters.
	  BandwidthModule On
	  ForceBandWidthModule On
	  LargeFileLimit .mp3 1 30000
       </IfModule>

${EXTRATEXT}
THEEND
}

op=$1
shift
$op $*
