post_install() {
  update-desktop-database -q
  echo -e '\033[1mRemember to run nspluginwrapper -v -a -i AS USER (not root) to install the 32-bit plugin.\033[0m'
  echo ">>>--------------"
}

post_upgrade() {
  update-desktop-database -q
  echo -e '\033[1mRemember to run nspluginwrapper -v -a -i AS USER (not root) to install the 32-bit plugin.\033[0m'
  echo ">>>--------------"
}

post_remove() {
  update-desktop-database -q
}
