# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>
# Contributor: Alfredo Palhares <masterkorp@masterkorp.net>

_gemname=kitchen-vagrant
pkgname=ruby-$_gemname
pkgver=0.15.0
pkgrel=1
pkgdesc='Kitchen::Driver::Vagrant - A Vagrant Driver for Test Kitchen.'
arch=(any)
url='https://github.com/test-kitchen/kitchen-vagrant/'
license=('Apache 2.0')
depends=(ruby ruby-test-kitchen)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('8b7498798741cd36585f26529f1e4a79d8fad582')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
