18c18
< 	g++ -shared -Wl,-soname,libnoteye.so -o ../libnoteye.so libnoteye.o -lSDL -lSDL_image -llua5.1 -lutil -lSDL_mixer -lSDL_net -lGL -lGLU -lz -lcurses
---
> 	g++ -shared -Wl,-soname,libnoteye.so -o ../libnoteye.so libnoteye.o -lSDL -lSDL_image -llua5.1 -lutil -lSDL_mixer -lSDL_net -lGL -lGLU
24c24
< 	g++ $(DEF) -Wl,-rpath,. -Wl,-rpath,/usr/share/noteye hydra.o noteye-main.cpp -o ../noteye ../libnoteye.so -lGL -lGLU -lz -lcurses
---
> 	g++ $(DEF) -Wl,-rpath,. -Wl,-rpath,/usr/share/noteye hydra.o noteye-main.cpp -o ../noteye ../libnoteye.so -lGL -lGLU
