--- Makefile	2011-11-08 02:55:41.000000000 +0000
+++ Makefile	2011-11-25 21:27:44.000000000 +0000
@@ -1,6 +1,6 @@
 
 LIBTCODDIR=src/libtcod-1.5.1
-CFLAGS=-Isrc/brogue -Isrc/platform -Wall -Wno-parentheses ${DEFINES}
+CFLAGS=-Isrc/brogue -Isrc/platform -I/usr/include/libtcod -Wall -Wno-parentheses ${DEFINES}
 RELEASENAME=brogue-1.5.2
 
 %.o : %.c
