--- Makefile	2011-05-02 12:40:12.000000000 +0100
+++ Makefile	2011-05-02 12:39:29.000000000 +0100
@@ -1,6 +1,6 @@
 
 LIBTCODDIR=src/libtcod-1.5.1
-CFLAGS=$(FLAGS) -I$(LIBTCODDIR)/include -Isrc/brogue -Isrc/platform -Wall
+CFLAGS=$(FLAGS) -I/usr/include/libtcod -Isrc/brogue -Isrc/platform -Wall
 RELEASENAME=brogue-1.4
 
 %.o : %.cpp
@@ -44,9 +44,7 @@
 	$(wildcard src/platform/*.c*) \
 	$(wildcard src/platform/*.h*) 
 
-${LIBTCODDIR} :
-	src/get-libtcod.sh
 
-bin/brogue : ${LIBTCODDIR} ${OBJS} 
+bin/brogue : ${OBJS} 
 	g++ -O3 -o bin/brogue ${OBJS} -L. -L${LIBTCODDIR} -ltcod -ltcodxx -Wl,-rpath,.
 
