post_install() {
/usr/bin/gtk-update-icon-cache
echo -e "Use these commands, as root, to install your standalone license:\n\n\
echo -e 'MAYA_LICENSE=unlimited\nMAYA_LICENSE_METHOD=standalone' > /usr/autodesk/maya2012-x64/bin/License.env\n\n\
LD_LIBRARY_PATH=/opt/Autodesk/Adlm/R4/lib64 /usr/autodesk/maya2012-x64/bin/adlmreg -i S 657D1 657D1 2012.0.0.F <your serial number> /var/opt/Autodesk/Adlm/Maya2012/MayaConfig.pit"
}

post_uninstall() {
/usr/bin/gtk-update-icon-cache
}