post_install()
{
cat<<EOF

Setting mod_auth_openid up
-------------
1. Add the following to /etc/httpd/conf/httpd.conf
    LoadModule authopenid_module modules/mod_auth_openid.so

2. Create the sqlite file where sessions are stored. By default:
    touch /tmp/mod_auth_openid.db
  Chown as the user apache runs as

3. Minimum directives to use the module (in config or .htaccess):
    AuthType OpenID
    require valid-user

4. Read http://findingscience.com/mod_auth_openid/#usage
EOF
}
