post_install() {
	touch /opt/qsanguosha/config.ini
	chown root:games /opt/qsanguosha/config.ini
	chmod g+rw /opt/qsanguosha/config.ini
	echo "add your username to games group"
	echo "gpasswd -a <yourname> games"
}
post_upgrade() {
	touch /opt/qsanguosha/config.ini      
	chown root:games /opt/qsanguosha/config.ini
	chmod g+rw /opt/qsanguosha/config.ini
	echo "add your username to games group"
	echo "gpasswd -a <yourname> games"
}
