post_install() {
  echo
  echo
  echo "Just add \"xlayout\" to your /etc/rc.conf's daemons section"
  echo "and edit your boot loader (lilo or grub) menu to call the kernel"
  echo "with a new parameter: [...] xlayout=<layout wanted>"
  echo "Please visit http://wiki2.archlinux.org/index.php/XLayout"
  echo "for further information."
  echo 
}

post_upgrade() {
/bin/true
}

pre_remove() {
/bin/true
}

op=$1
shift

$op $*
