@@ -28,17 +28,14 @@ LDFLAGS += -lncurses
 
 all: $(bin)
 
-$(obj): $(wildcard *.h) version.h
+$(obj): $(wildcard *.h)
 
 $(bin): $(obj)
-	gcc -o $(bin) $(CFLAGS) $(LDFLAGS) $(obj)
+	gcc -o $(bin) $(CFLAGS) $(obj) $(LDFLAGS)
 
 clean:
 	rm -f *.o $(bin)
 
-version.h: .git
-	./getver.sh
-
 trans:
 	xgettext -o translations/radeontop.pot -k_ *.c \
 	--package-name radeontop
