post_install() {
  echo "Make sure to setup up sudo so that the needed users can access"
  echo "'sudo /usr/bin/netcfg' with out typing in a password. Example, in"
  echo "visudo, place the following lines:"
  echo "  Cmnd_Alias NETMGR = /usr/bin/netcfg"
  echo "  %network ALL=NOPASSWD: NETMGR"
  echo "Lines such as the above will allow a user to launch sudo for"
  echo "certain commands without requiring a password"

}
# vim:set ts=2 sw=2 et:
