post_install() {
 echo '--------------------------------------------------------------------------'
 echo '                          SETUP INSTRUCTIONS'
 echo
 echo '  1) Edit /etc/sync-browsers.conf and define which users will make use'
 echo '     of the sync to tmpfs for their browser(s) profile(s)'
 echo
 echo '  2) Add an line to the root crontab to have the daemon run in update mode'
 echo '     at some regular interval.'
 echo 
 echo '     Do this using crontab as root: crontab -e'
 echo
 echo '     Example updating once every hour:'
 echo '     * */1 * * * 	/usr/sbin/rc.d update sync-browsers > /dev/null 2>&1'
 echo 
 echo '--------------------------------------------------------------------------'
}

post_remove() {
 echo '--------------------------------------------------------------------------'
 echo 'Be sure to remove the entry in the root crontab!'
 echo '--------------------------------------------------------------------------'
}
