'\" t
.\"     Title: fbcat
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 12/29/2009
.\"    Manual: fbcat manual
.\"    Source: fbcat 0.2
.\"  Language: English
.\"
.TH "FBCAT" "1" "12/29/2009" "fbcat 0\&.2" "fbcat manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
fbcat \- takes a screenshot using the framebuffer device
.SH "SYNOPSIS"
.HP \w'\fBfbcat\fR\ 'u
\fBfbcat\fR [\fIfbdev\fR]
.SH "DESCRIPTION"
.PP

\fBfbcat\fR
takes a screenshot using the framebuffer device\&. The produced image is in PPM format\&. Note that redirection of standard output to a file or another process is needed since fbcat will refuse to write it\*(Aqs output directly to the terminal\&.
.SH "SEE ALSO"
.PP

\fBppm\fR(5),
\fBfbgrab\fR(1)
.SH "COPYRIGHT"
.br
Copyright \(co 2009 Piotr Lewandowski, Jakub Wilk
.br
