'\" t
.\"     Title: fbgrab
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 12/29/2009
.\"    Manual: fbgrab manual
.\"    Source: fbgrab 0.2
.\"  Language: English
.\"
.TH "FBGRAB" "1" "12/29/2009" "fbgrab 0\&.2" "fbgrab manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
fbgrab \- takes a screenshot using the framebuffer device
.SH "SYNOPSIS"
.HP \w'\fBfbgrab\fR\ 'u
\fBfbgrab\fR [\fIoption\fR...] \fIpng\-file\fR
.HP \w'\fBfbgrab\fR\ 'u
\fBfbgrab\fR \fB\-?\fR
.SH "DESCRIPTION"
.PP

\fBfbgrab\fR
is a wrapper around
\fBfbcat\fR
which emulates the behaviour of Gunnar Monell\*(Aqs
\fBfbgrab\fR
utility\&.
.SH "OPTIONS"
.PP

\fBfbgrab\fR
accepts the following options:
.PP
\fB\-c \fR\fB\fIN\fR\fR
.RS 4
Grab the
/dev/ttyN
virtual terminal\&.
.RE
.PP
\fB\-C \fR\fB\fIN\fR\fR
.RS 4
Switch to the
/dev/ttyN
virtual terminal, then wait a few seconds before grabbing it\&.
.RE
.PP
\fB\-d \fR\fB\fIfb\-device\fR\fR
.RS 4
Use the
\fIfb\-device\fR
framebuffer device\&.
.sp
By default, the device name is taken from the
\fIFRAMEBUFFER\fR
environment variable\&. If it is unset or empty, the default is
/dev/fb0\&.
.RE
.PP
\fB\-i\fR
.RS 4
Enable PNG interlacing\&.
.RE
.PP
\fB\-s \fR\fB\fIN\fR\fR
.RS 4
Sleep
\fIN\fR
seconds before making the screenshot or switching virtual terminals\&.
.RE
.PP
\fB\-?\fR
.RS 4
Display help and exit\&.
.RE
.SH "UNSUPPORTED OPTIONS"
.PP
The following options of Gunnar Monell\*(Aqs
\fBfbgrab\fR
are recognized but not supported:
.PP
\fB\-f \fR\fB\fIfb\-dump\-file\fR\fR
.RS 4
.RE
.PP
\fB\-b \fR\fB\fIN\fR\fR
.RS 4
.RE
.PP
\fB\-w \fR\fB\fIN\fR\fR
.RS 4
.RE
.PP
\fB\-h \fR\fB\fIN\fR\fR
.RS 4
.RE
.SH "SEE ALSO"
.PP

\fBpng\fR(5),
\fBfbcat\fR(1)
.SH "COPYRIGHT"
.br
Copyright \(co 2009 Jakub Wilk
.br
