#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

DAEMON_CONF="/etc/amavisd/amavisd.conf"

PID=`pidof -o %PPID amavisd`

case "$1" in

	start)

		stat_busy "Starting amavisd"

		[ -z "$PID" ] && /usr/sbin/amavisd -c ${DAEMON_CONF} &> /dev/null

		if [ $? -gt 0 ]; then

			stat_fail

		else

			add_daemon amavisd

			stat_done

		fi

	;;

	stop)

		stat_busy "Stopping amavisd"

		[ ! -z "$PID" ]  && kill $PID &> /dev/null

		if [ $? -gt 0 ]; then

			stat_fail

		else

			rm_daemon amavisd
			stat_done

		fi

	;;

	restart)

		$0 stop

		sleep 3

		$0 start

	;;

	reload)

		stat_busy "Reloading amavisd"

		/usr/sbin/amavisd -c ${DAEMON_CONF} reload

		stat_done

	;;

	*)
		echo "usage: $0 {start|stop|restart|reload}"
	;;

esac

exit 0
