post_install() {
  getent passwd gitblit &>/dev/null || useradd -r -U -s /bin/false -d /var/lib/gitblit gitblit >/dev/null
  mkdir -p /var/log/gitblit
  chown -R gitblit: /var/lib/gitblit /etc/gitblit /var/log/gitblit
}

pre_upgrade() {
  [ -f /run/daemons/gitblit ] && /etc/rc.d/gitblit stop
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  userdel gitblit &>/dev/null
  groupdel gitblit &>/dev/null || /bin/true
}

# vim:set ts=2 sw=2 et:
