post_install() {
  post_upgrade
}

post_upgrade() {
  getent group "shxd" &>/dev/null || groupadd -r shxd 1>/dev/null
  getent passwd "shxd" &>/dev/null || useradd -r -g shxd -d "/var/empty" -s "/bin/sh" shxd 1>/dev/null
  chown -R shxd:shxd "/srv/shxd" 1>/dev/null
}

post_remove() {
  if getent passwd "shxd" >/dev/null; then
    userdel shxd >/dev/null
  fi
  if getent group "shxd" >/dev/null; then
    groupdel shxd >/dev/null
  fi
}
