post_install() {
    cat << 'EOF'
==> Put this in your $HOME/.emacs file to enable autoloading of paredit:

(require 'geiser)

==> To start a REPL listener from within Emacs:

(run-geiser)

==> ... or connect to a running listener:

(geiser-connect)

==> Note that geiser's keybindings may conflict with `Quack'
==>
==> Note that geiser currently only supports Guile-1.9 and Racket

EOF
}

post_upgrade() {
    post_install
}
