post_install() {
    cat << 'EOF'
==> Put this in your $HOME/.emacs file to enable autoloading of geiser:

(require 'geiser-install)

==> To start a REPL listener from within Emacs:

(run-geiser)

==> ... or connect to a running listener:

(geiser-connect)

==> Note that geiser's keybindings may conflict with `Quack'
==>
==> Note that geiser currently only supports Guile 2.0 or better and
==> Racket 5.0.1 or better.

EOF
}

post_upgrade() {
    post_install
}
