# Generated by gem2arch

_gemname=hub
pkgname=ruby-$_gemname
pkgver=1.10.3
pkgrel=1
pkgdesc="Command-line wrapper for git and GitHub"
arch=('any')
url="http://defunkt.io/hub/"
license=('')
depends=('ruby')
makedepends=('rubygems')
source=(http://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
md5sums=('4a7318404431537b023b8747f8510eb4')
sha1sums=('c7e5d14f884bdb2784b953ec9459fa6dc51e7e7b')

package() {
  cd "$srcdir"
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
}
