post_install() {
	echo "Creating menus and file associations, please wait..."
	/opt/cxgames/bin/cxmenu --crossover --install
	/opt/cxgames/bin/cxassoc --crossover --install
	echo "Done!"
	echo
	echo "This is the demo version, to fully activate it you must have a valid serial and register it."
	echo "More information about this process here:"
	echo "http://www.codeweavers.com/support/docs/crossover-games-linux/demo"
}

post_upgrade() {
	post_install
}