#!/bin/bash
#
# /etc/NetworkManager/dispatcher.d/99-resolv.conf-head_and_tail
# Include /etc/resolv.conf.head and /etc/resolv.conf.tail to /etc/resolv.conf
#
# scripts in the /etc/NetworkManager/dispatcher.d/ directory
# are called alphabetically and are passed two parameters:
# $1 is the interface name, and $2 is “up” or “down” as the
# case may be.
#
# NetworkManager clobbers the resolv.conf every time an interface comes up or
# down.  This is the intended behavior, but if the user has a resolv.conf.head
# or resolv.conf.tail file, it's safe to assume that they *always* want those
# lines in their resolv.conf, regardless of which interface is up.  Therefore,
# unlike most networkmanager-dispatcher scripts, we will be running the same
# code regardless of which interface toggled or what state it went into.
#
# The following is adapted from the script on https://wiki.archlinux.org/index.php/NetworkManager

resolvconf='/etc/resolv.conf'
tmp_resolvconf='/tmp/resolv.conf'

cat "$resolvconf"{.head,,.tail} 2>/dev/null > "$tmp_resolvconf"
mv -f "$tmp_resolvconf" "$resolvconf"

