post_install() {
    cat << EOM

To load included library \$lib, run the following line:

(load #p"/usr/share/common-lisp/source/asdf/\$lib.lisp")

To prevent a conflict with sbcl package, the info file has been renamed to asdf-git.
Use 'info asdf-git' command to view it.
EOM

    cd /usr/share/info
    install-info asdf-git.info dir
}

post_upgrade() {
    post_install
}

pre_remove() {
    cd /usr/share/info
    install-info --remove asdf-git.info dir
}

# End of file
