diff -Naur edbrowse-3.4.6/src/makefile edbrowse-3.4.6-new/src/makefile
--- edbrowse-3.4.6/src/makefile	2011-01-20 10:38:24.000000000 +0000
+++ edbrowse-3.4.6-new/src/makefile	2011-01-26 13:50:10.000000000 +0000
@@ -23,12 +23,15 @@
 STRIP=-s
 endif
 
-CFLAGS = -I/usr/local/js/src -I/usr/local/js/src/Linux_All_DBG.OBJ -DXP_UNIX -DX86_LINUX $(DEBUGFLAGS)
+JSFLAGS = -I/usr/include/js -DXP_UNIX
+
+%.o: %.c
+	$(CC) $(CFLAGS) $(JSFLAGS) -c -o $@ $<
 
 #  If the smjs library is already installed by your linux distribution,
 #  e.g. Debian, use the following flags.
 #
-#CFLAGS = -I/usr/include/js -DXP_UNIX -DX86_LINUX $(DEBUGFLAGS)
+#CFLAGS = -I/usr/include/smjs -DXP_UNIX -DX86_LINUX $(DEBUGFLAGS)
 
 #  Normal load flags
 LFLAGS = $(STRIP)
@@ -59,11 +62,11 @@
 $(EBOBJS) : eb.h eb.p messages.h tcp.h
 
 edbrowse: $(EBOBJS) tcp.o dbstubs.o
-	cc $(LFLAGS) -o edbrowse $(EBOBJS) tcp.o dbstubs.o $(LIBS)
+	$(CC) $(LDFLAGS) -o edbrowse $(EBOBJS) tcp.o dbstubs.o $(LIBS)
 
 #  You probably need to be root to do this.
 install:
-	install -Dm755 edbrowse $(bindir)/edbrowse
+	install -Dm755 edbrowse $(DESTDIR)$(bindir)/edbrowse
 
 #  If you had to build the javascript library yourself,
 #  link it into /usr/lib.
@@ -87,7 +90,7 @@
 
 #  odbc access
 edbrowseodbc: $(EBOBJS) tcp.o dbops.o dbodbc.o
-	cc $(LFLAGS) -o edbrowseodbc $(EBOBJS) tcp.o dbops.o dbodbc.o $(LIBS) -lodbc
+	$(CC) $(LDFLAGS) -o edbrowseodbc $(EBOBJS) tcp.o dbops.o dbodbc.o $(LIBS) -lodbc
 
 #  Build function prototypes.
 #  mkproto is my program, not a general unix utility.
