#!/usr/bin/env bash
set -eu -o pipefail

temp_mirrorlist_file="$(mktemp)"

cleanup()
{
	rm "$temp_mirrorlist_file"
}
trap cleanup EXIT

#/etc/pacman.d/mirrorlist
mirrorlist_file="$1"
#https://www.archlinux.org/mirrorlist/?country=all&use_mirror_status=on
mirrorlist_url="$2"

if [ ! -e "$mirrorlist_file" ]; then
	exit 1;
fi

curl -fL "$mirrorlist_url" > "$temp_mirrorlist_file"
sed '/^#\S/ s|#||' -i "$temp_mirrorlist_file"

if [[ $(diff <(head -n 2 "$temp_mirrorlist_file" ) <(echo -e '#\n# Arch Linux repository mirrorlist')) ]]; then
	exit 1;
fi

cat "$mirrorlist_file" > "$mirrorlist_file.backup"

cat "$temp_mirrorlist_file" > "$mirrorlist_file"
pacman -Syy
