#!/usr/bin/env bash
set -eu -o pipefail

temp_mirrorlist_file="$(mktemp)"

cleanup()
{
	rm "$temp_mirrorlist_file"
}
trap cleanup EXIT

#TODO: Make this configurable outside of the systemd serivce.
mirrorlist_file="$1"
mirrorlist_url="$2"

if [ ! -e "$mirrorlist_file" ]; then
	exit 1;
fi

curl -fL "$mirrorlist_url" -o "$temp_mirrorlist_file"

#TODO: Better sanity checking.
if [[ $(diff <(head -n 3 "$temp_mirrorlist_file" ) <(echo -e '##\n## Arch Linux repository mirrorlist\n## Sorted by mirror score from mirror status page')) ]]; then
	exit 1;
fi

sed '/^#\S/ s|#||' -i "$temp_mirrorlist_file"

cat "$mirrorlist_file" > "$mirrorlist_file.backup"
cat "$temp_mirrorlist_file" > "$mirrorlist_file"

pacman -Syy
