# Contributor: Christian Holme <cholme at gmx dot com>

pkgname=spe-tools
pkgver=0.6
pkgrel=1
pkgdesc="tools for working with .SPE files generated by some CCDs"
arch=('i686' 'x86_64')
url=("http://kmlinux.fjfi.cvut.cz/~jaryvlad/spe-tools.html")
license=('GPL')
depends=('qt' 'root' )
source=("http://kmlinux.fjfi.cvut.cz/~jaryvlad/download/$pkgname-$pkgver.zip")

build() {
  	cd "$srcdir/src"
   	qmake
   	make
}

package() {
	install -Dm 755 $srcdir/src/spe-tools $pkgdir/usr/bin/spe-tools
}

md5sums=('64a0174f18d1af46908530019a048ffd')
