post_install() {
  usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor

  echo "Remember to set the relevant keybinding in dconf-editor. Path to key is: /org/gnome/settings-daemon/plugins/media-keys/video-out"
}

pre_upgrade() {
  if (( $(vercmp $2 2.90.0) < 0 )); then
    usr/sbin/gconfpkg --uninstall gnome-settings-daemon
  fi
}

post_upgrade() {
  post_install
}

post_remove() {
  post_install
}
