KERNEL_VERSION=2.6.28-ARCH

post_install() {
  #Backup kernel hso.ko
  mv /lib/modules/$KERNEL_VERSION/kernel/drivers/net/usb/hso.ko /lib/modules/$KERNEL_VERSION/kernel/drivers/net/usb/hso.ko.bak
  depmod $KERNEL_VERSION
}

post_upgrade() {
  #Backup kernel hso.ko
  if [ -f /lib/modules/$KERNEL_VERSION/kernel/drivers/net/usb/hso.ko ]
  then
    rm /lib/modules/$KERNEL_VERSION/kernel/drivers/net/usb/hso.ko.bak
    mv /lib/modules/$KERNEL_VERSION/kernel/drivers/net/usb/hso.ko /lib/modules/$KERNEL_VERSION/kernel/drivers/net/usb/hso.ko.bak
  fi
  depmod $KERNEL_VERSION
}

post_remove() {
  #Restore kernel hso.ko
  if [ -f /lib/modules/$KERNEL_VERSION/kernel/drivers/net/usb/hso.ko ]
  then
    rm /lib/modules/$KERNEL_VERSION/kernel/drivers/net/usb/hso.ko.bak
  else
    mv /lib/modules/$KERNEL_VERSION/kernel/drivers/net/usb/hso.ko.bak /lib/modules/$KERNEL_VERSION/kernel/drivers/net/usb/hso.ko
  fi
  depmod $KERNEL_VERSION
}
