runme() {
echo	
echo "*****************************"
echo	
echo "1) modify by user:"
echo "mkdir /home/user/.gt"
echo "cp /usr/share/geniustrader/options /home/user/.gt/"
echo	
echo "2) modify .bashrc or similar file"
echo "add to PATH: /usr/share/geniustrader/Scripts"
echo	
echo "3) test data:"
echo "display_indicator.pl I:Prices 13000"
echo	
echo "*****************************"
echo	
}

post_install() {
	runme
}

post_upgrade() {
	runme
}
 
