post_install() {

  echo "Source the colorscheme in your muttrc (choose one):"
  echo "----------"
  echo "source \$MAILCONF/mutt-colors-solarized/mutt-colors-solarized-light-16.muttrc"
  echo "source \$MAILCONF/mutt-colors-solarized/mutt-colors-solarized-dark-16.muttrc"
  echo "source \$MAILCONF/mutt-colors-solarized/mutt-colors-solarized-light-256.muttrc"
  echo "source \$MAILCONF/mutt-colors-solarized/mutt-colors-solarized-dark-256.muttrc"

}

post_upgrade() {

post_install

}  
