post_install() {

  echo ""
  echo ">>> Source the colorscheme in your .muttrc (choose *ONE*):"
  echo ""
  echo "  1. /usr/share/doc/mutt/colors/solarized/mutt-colors-solarized-dark-16.muttrc"
  echo "  2. /usr/share/doc/mutt/colors/solarized/mutt-colors-solarized-dark-256.muttrc"
  echo "  3. /usr/share/doc/mutt/colors/solarized/mutt-colors-solarized-light-16.muttrc"
  echo "  4. /usr/share/doc/mutt/colors/solarized/mutt-colors-solarized-light-256.muttrc"
  echo ""
  echo "Example: "
  echo ""
  echo "    source /usr/share/doc/mutt/colors/solarized/mutt-colors-solarized-dark-256.muttrc"
  echo ""


}

post_upgrade() {

post_install

}  
