post_install() {
  echo "IMPORTANT:"
  echo " ** Check the README for problems, concerns and configuration options."
  echo " ** README: https://github.com/redline6561/paktahn/blob/master/README"
  echo "  * You need to have sudo configured to install packages."
  echo "  * For users with light background terminals:"
  echo "      consult the documentation for setting the appropriate color scheme."
}

post_upgrade() {
  post_install $1
}
