post_install() {
  echo "IMPORTANT:"
  echo "  * You need to have sudo configured to install packages."
  echo "  * Consult the README on github for config options:"
  echo "    http://github.com/redline6561/paktahn/"
  echo "  * In particular, users with light background terminals will want to"
  echo "    add (in-package :pak) and (setf *color-scheme* *color-scheme-lightbg*)"
  echo "    to ~/.paktahn/config.lisp."
}

post_upgrade() {
  post_install $1
}
