post_install() {
  chown -R http:http /usr/share/webapps/piwik
}

pre_remove() {
  cp -r /usr/share/webapps/piwik /usr/share/webapps/piwik_backup
  echo 'Your Piwik folder were backed up to /usr/share/webapps/piwik_backup'
}

post_remove() {
  rm -rf /usr/share/webapps/piwik
}

pre_upgrade() {
  if [ -e /srv/http/piwik ];then
    mv /srv/http/piwik /usr/share/webapps/piwik
    echo 'Piwik is in /usr/share/webapps now'
  fi
}

post_upgrade() {
  chown -R http:http /usr/share/webapps/piwik
}
