## arg 1:  the new package version
post_install() {
  if ! getent passwd rspamd >/dev/null; then
    useradd -c 'rspam daemon' -g mail -d / -s /sbin/nologin rspamd
    passwd -l rspamd >/dev/null
  fi
  chown rspamd:mail /var/lib/rspamd
  systemd-tmpfiles --create rspamd.conf
}

## arg 1:  the old package version
post_remove() {
  if getent passwd rspamd >/dev/null; then
    userdel rspamd
  fi
}

# vim:set ts=2 sw=2 et:
