.TH USBRESET 1 "2012 Oct 12"
.SH NAME
usbreset \- Resets a USB device
.SH SYNOPSIS
.B usbreset
DEVICE
.SH DESCRIPTION
USB devices might need to be reset without being unplugged: this is what usbreset does.
.SH OPTIONS
.TP 12
DEVICE
Path to the USB device, which is /dev/bus/usb/BBB/DDD where BBB is the bus number and DDD the device number.
.SH EXAMPLE
Finding the bus and device numbers of a plugged USB device and resetting it:
.PP
        # lsusb
        ...
        Bus 001 Device 004: ID xxxx:xxxx Device description
        ...
        # usbreset /dev/bus/usb/001/004
        Resetting USB device /dev/bus/usb/001/004
        Reset successful
.SH CAVEATS
Some devices don't reset even when told to.
If the device doesn't react, try resetting the root hub of that bus instead (be aware that it will reset every device connected to the bus).
.SH AUTHOR
usbreset was made by Alan Stern and this man page was written by Joan Rieu.
