=head1 NAME

usbreset - Resets a USB device

=head1 SYNOPSIS

usbreset device-filename

=head1 DESCRIPTION

USB devices might need to be reset without being unplugged: this is what usbreset does.

B<device-filename>      Path to the USB device, which is /proc/bus/usb/BBB/DDD where BBB is the bus number and DDD the device number.

=head1 EXAMPLE

Finding the bus and device numbers of a plugged USB device and resetting it:

        $ lsusb
        ...
        Bus 001 Device 004: ID xxxx:xxxx Device description
        ...
        $ usbreset /proc/bus/usb/001/004
        Resetting USB device /proc/bus/usb/001/004
        Reset successful

=head1 REMARKS

If the /proc/bus/usb directory is empty, you need to mount the usbfs in there:

        $ mount -t usbfs none /proc/bus/usb

=head1 AUTHORS

usbreset was made by Alan Stern and this man page was written by Joan Rieu.
