--- Makefile.in.new	2012-12-05 16:49:06.572071531 +0000
+++ Makefile.in		2012-12-05 16:50:38.983223544 +0000
@@ -26,8 +26,8 @@
 
 check:	bencodetest
 	./bencodetest
-	python bencode.py
-	python typevalidator.py
+	python2 bencode.py
+	python2 typevalidator.py
 	@echo
 	@echo "All tests successful" #
 
@@ -40,7 +40,7 @@
 	install bencat "$(PREFIX)/bin/"
 	@echo
 	@echo "Installing Python packages"
-	python setup.py install $(PYTHON_INSTALL_OPTION)
+	python2 setup.py install $(PYTHON_INSTALL_OPTION)
 
 %.o:	%.c
 	$(CC) $(CFLAGS) -c $<
