.TH FBPDF 1 "NOVEMBER 2011"
.SH NAME
fbpdf \- framebuffer PDF viewer
.SH SYNOPSIS
.B fbpdf
.I filename
.SH DESCRIPTION
.B fbpdf
is a small framebuffer PDF viewer that uses
the mupdf backend (optionally poppler). fbpdf brings
high-quality PDF viewing to the console, and uses
vim keyboard shortcuts.
.SH KEY BINDINGS
.IP h
Scroll to the left
.IP l
Scroll to the right
.IP j
Scroll down
.IP k
Scroll up
.IP ^d
Scroll half a page down
.IP ^u
Scroll half a page up
.IP ^f
Go to next page
.IP ^b
Go to previous page
.IP Backspace
Scroll half a page up
.IP H
Go to the top/current column of page
.IP M
Go to the middle/current column of page
.IP L
Go to the bottom/current column of page
.IP [0-9]+J
Go forward by specified number of pages, default one
.IP [0-9]+K
Go backward by specified number of pages, default one
.IP [0-9]+G
Go to specified page, default to the end
.IP m+[a-z]
Mark page for snap back.
.IP ['|`]+[a-z]
Pop back to marked page.
.IP [0-9]+r
Rotate specified number of degrees
.IP [0-9]+z
Zoom by a multiple of ten
.IP ^[
Clear numerical prefix
.IP i
Display file information
.IP R
Reload file
.IP ^l
Redraw screen
.IP ^z
Suspend program
.IP ^c
Terminate program
.IP q
Quit program
.SH AUTHOR
Ali Gholami Rudi <aligrudi at gmail dot com>
.SH "SEE ALSO"
.BR mupdf (1)
