# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=droplet_kit
pkgname=ruby-$_gemname
pkgver=1.1.2
pkgrel=1
pkgdesc='Droplet Kit is the official Ruby library for Digital Ocean'\''s API'
arch=(any)
url='https://www.digitalocean.com/community/projects/droplet-kit'
license=(MIT)
depends=(ruby ruby-virtus ruby-resource_kit ruby-kartograph ruby-activesupport)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('d9224aba7bff4a0c0904a41144e05b208e44daf7')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE.txt" "$pkgdir/usr/share/licenses/$pkgname/LICENSE.txt"
}
