post_install() {
	cat << _EOF
>>> Be aware that wx-config is in /usr/i486-mingw32/bin
>>> If you have Arch's wxGTK on your system you could symlink to that wx-config!
>>> ln -s /usr/i486-mingw32/lib/wx/config/* /usr/lib/wx/config/

_EOF
}

post_remove() {
	cat << _EOF
>>> If you symlinked to wx-config of wxGTK you shouldn't forget to remove that.
>>> rm /usr/lib/wx/config/i486-mingw32-msw*
_EOF
}

op=$1
shift
[ "$(type -t "$op")" = "function" ] && $op "$@"

