post_install() {
   ldconfig &> /dev/null
   mkpamserv trinity
   echo "Please remember that you can change your kdesu backend from su to sudo"
   echo "by adding following lines to your ~/.trinity/share/kdesurc or to the"
   echo "$TDEDIR/share/config/kdesurc:"
   echo "[super-user-command]"
   echo "super-user-command=sudo"
}

post_upgrade() {
   post_install
}

post_remove() {
   ldconfig &> /dev/null
   rm /etc/pam.d/trinity
}

