post_install() {
	pselect nvidia-libgl enable

	echo By using this package you accept the NVIDIA license,
	echo which has been installed in /usr/share/licenses/nvidia/LICENSE
	echo If you do not accept this license, you must remove the package immediately.
	echo Dont forget to update your /etc/X11/xorg.conf

	echo '*** Nvidia gl libraries are now selected. ***'
	echo '*** Run pselect to change this. ***'
}

post_upgrade() {
	post_install $1
}

pre_remove() {
	pselect nvidia-libgl disable
}
