post_install() {
	       mkdir /var/spool/lpd
	       chown daemon /var/spool/lpd
	       chgrp lp /var/spool/lpd
	       chmod 0700 /var/spool/lpd
	       echo 'See /etc/lprng/README to configure'
}

post_upgrade() {
		/usr/bin/systemctl reenable lpd.service
		/usr/bin/systemctl restart lpd.service
}

pre_remove() {
	     /usr/bin/systemctl stop lpd.service
	     /usr/bin/systemctl disable lpd.service
}
