#!/bin/sh

# set up config
if [ ! -f ~/.excellent-bifurcation ]; then
  cp /usr/share/excellent-bifurcation/init.txt ~/.excellent-bifurcation
fi


# either this or patch every path
cd /usr/share/excellent-bifurcation
./excellent-bifurcation.bin

