# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Babken Vardanyan <483ken@gmail.com>

_gemname=metasploit-credential
pkgname=ruby1.9-$_gemname
pkgver=0.8.6
pkgrel=1
pkgdesc='Credential models for metasploit-framework and Metasploit Pro'
arch=(any)
url='https://github.com/rapid7/metasploit-credential'
license=(BSD-3-clause)
depends=(ruby1.9 ruby1.9-metasploit-concern ruby1.9-metasploit_data_models ruby1.9-metasploit-model ruby1.9-rubyntlm ruby1.9-rubyzip ruby1.9-pg)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('e8df396573dddc9915324f2e65d1406b1f817d49')

package() {
  local _gemdir="$(ruby-1.9 -e'puts Gem.default_dir')"
  gem-1.9 install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
