post_install() {
	# lpr
	/opt/brother/Printers/dcp395cn/inf/setupPrintcapij dcp395cn -i
	
	# cupswrapper
	/opt/brother/Printers/dcp395cn/cupswrapper/cupswrapperdcp395cn
	systemctl stop cups 
	systemctl start cups
}

post_upgrade() {
	/bin/true
}

pre_remove() {
	# lpr
	/opt/brother/Printers/dcp395cn/inf/setupPrintcapij dcp395cn -e
	
	# cupswrapper
	/opt/brother/Printers/dcp395cn/cupswrapper/cupswrapperdcp395cn -e

}

op=$1
shift

$op "$@"


