#!/bin/bash
#

DAEMON_NAME=celeryd
CELERYD_PID_FILE="/var/run/celeryd.pid"
CELERYD_LOG_FILE="/var/log/celeryd.log"
CELERYD_LOG_LEVEL="INFO"
DEFAULT_CELERYD="celeryd"

if [ -f /etc/conf.d/celeryd ]; then
	. /etc/conf.d/celeryd
fi

CELERYD=${CELERYD:-$DEFAULT_CELERYD}
CELERYD_OPTS="$CELERYD_OPTS -f $CELERYD_LOG_FILE -l $CELERYD_LOG_LEVEL"

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
	start)
		stat_busy "Starting $DAEMON_NAME daemon"

		if [ -n "$CELERYD_CHDIR" ]; then
			cd $CELERYD_CHDIR
			export PYTHONPATH="$CELERYD_CHDIR:$PYTHONPATH"
		fi

		[ -n "$CELERY_CONFIG_MODULE" ] && export CELERY_CONFIG_MODULE
		[ -n "$DJANGO_SETTINGS_MODULE" ] && export DJANGO_SETTINGS_MODULE

		$CELERYD $CELERYD_OPTS &> /dev/null &
		if [ $? -gt 0 ]; then
			stat_fail
			exit 1
		else
			echo -n "$!" > $CELERYD_PID_FILE
			add_daemon $DAEMON_NAME
			stat_done
		fi
		;;

	stop)
		stat_busy "Stopping $DAEMON_NAME daemon"
		[ -f "$CELERYD_PID_FILE" ] && kill `cat $CELERYD_PID_FILE` &> /dev/null
		if [ $? -gt 0 ]; then
			stat_fail
			exit 1
		else
			rm -f $CELERYD_PID_FILE
			rm_daemon $DAEMON_NAME
			stat_done
		fi
		;;

	restart)
		$0 stop
		sleep 3
		$0 start
		;;

	status)
		stat_busy "Checking $DAEMON_NAME status";
		ck_status $DAEMON_NAME
		;;

	*)
		echo "usage: $0 {start|stop|restart|status}"
esac

exit 0
