#Automatically generated by pip2arch on 2012-06-20

pkgname=motmot.realtime_image_analysis
pkgver=0.5.7
pkgrel=1
pkgdesc="several image analysis functions that require Intel IPP and FastImage"
url="http://code.astraw.com/projects/motmot"
depends=('python2' )
makedepends=('python2-distribute' )
license=('BSD')
arch=('any')
source=('http://pypi.python.org/packages/source/m/motmot.realtime_image_analysis/motmot.realtime_image_analysis-0.5.7.zip')
md5sums=('cee9f3fc5538c4ed922f420906370370')

build() {
    cd $srcdir/motmot.realtime_image_analysis-0.5.7
    python2 setup.py build
}

package() {
    cd $srcdir/motmot.realtime_image_analysis-0.5.7
    python2 setup.py install --root="$pkgdir" --optimize=1 
}
