# SIP-dev: Installer: Arch
# Contributor: Xavion <Xavion (dot) 0 (at) Gmail (dot) com>

post_install() {
	# Replace older SIP binary
	mv /usr/bin/sip /usr/bin/sip-orig
	mv /usr/bin/sip-dev /usr/bin/sip

	#/bin/true
}

post_upgrade() {
	post_install
	#/bin/true
}

pre_remove() {
	# Replace newer SIP binary
	mv /usr/bin/sip /usr/bin/sip-dev
	mv /usr/bin/sip-orig /usr/bin/sip

	#/bin/true
}

post_remove() {
	/bin/true
}

op=$1
shift

$op "$@"
