#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/sbin/policyd-weight`
case "$1" in
  start)
    stat_busy "Starting policyd-weight Server"
    [ -z "$PID" ] && /usr/sbin/policyd-weight -f /etc/mail/policyd-weight.conf start
    if [ $? -gt 0 ]; then
      stat_fail
    else
      echo $PID > /var/run/policyd-weight.pid
      add_daemon policyd-weight
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping policyd-weight Server"
#	/usr/sbin/policyd-weight stop
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm /var/run/policyd-weight.pid
      rm_daemon policyd-weight
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0

