diff -rpu acpica-unix-20110413/compiler/Makefile acpica-unix-20110413.new//compiler/Makefile
--- acpica-unix-20110413/compiler/Makefile	2011-04-14 00:55:51.000000000 +0800
+++ acpica-unix-20110413.new//compiler/Makefile	2011-05-17 13:02:02.000000000 +0800
@@ -166,11 +166,15 @@ OBJS = \
 
 INTERMEDIATES = \
 	aslcompilerlex.c \
-	aslcompilerparse.c
+	aslcompilerparse.c \
+	dtparserlex.c \
+	dtparserparse.c
 
 MISC = \
 	aslcompiler.y.h \
-	aslcompilerparse.output
+	aslcompilerparse.output \
+	dtparser.y.h \
+	dtparserparse.output

