post_install() {
  echo "==> English and Czech language files are installed by default."
  echo "==> Use 'bflng -h' to list other available language packs."
  echo "==> Launch BC-Commander with either 'bfcmd' or the menu entry."
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  # Language files not under pacman's control
  /usr/share/bfcommander/bflng -r all &> /dev/null
}

post_remove() {
  [ -d "/usr/share/bfcommander" ] && rm -rf /usr/share/bfcommander
}
