post_install() {
cat << 'EOM'
  ==> PLEASE NOTE:
  ==>
  ==> You need to create a database and configure your webserver.
  ==> Check /usr/share/doc/lxr/INSTALL for details.
  ==> 
  ==> If you are using apache, add the following line to your httpd.conf:
  ==> Include conf/extra/lxr.conf
  ==> 
  ==> Also ensure mod_perl is enabled:
  ==> LoadModule perl_module modules/mod_perl.so 
  ==>
  ==> Finally modify /etc/lxr/lxr.conf to fit your needs.
EOM
}
