post_install() {
	echo $'You must run the following command to allow ds4drv access to uinput:\nudevadm control --reload-rules; rmmod uinput; modprobe uinput'
	echo $''
	echo $'Currently Linux kernel, more specifically the hidp module, does not support\nsending correct device reports to DualShock 4 controllers. There is a hacky patch [1]\nthat fixes it on linux-bluetooth mailing list. Proper fixes are probably\navailable in the kernel within few months or so. Until that you can apply that\nhacky patch and use your controllers with pairing and all features.'
	echo $''
	echo $'[1] http://marc.info/?l=linux-bluetooth&m=139026106704092&w=2'
}
