--- Makefile.Linux.orig	2010-12-10 11:27:52.000000000 +0800
+++ Makefile.Linux	2010-12-18 21:06:44.116666940 +0800
@@ -8,11 +8,11 @@
 #LIBS = `sdl-config --libs` `smpeg-config --libs` -lSDL_ttf -lSDL_image -lSDL_mixer -lbz2 -ljpeg -lm
 #DEFS = -DLINUX
 
-INCS = `sdl-config --cflags` `smpeg-config --cflags` `avifile-config --cflags` -I/usr/include/lua5.1
+INCS = `sdl-config --cflags` `smpeg-config --cflags`
 # with OggVorbis and AVI
-LIBS = `sdl-config --libs` `smpeg-config --libs` `avifile-config --libs` -lSDL_ttf -lSDL_image -lSDL_mixer -lbz2 -ljpeg -lm -logg -lvorbis -lvorbisfile -llua5.1
+LIBS = `sdl-config --libs` `smpeg-config --libs` -lSDL_ttf -lSDL_image -lSDL_mixer -lbz2 -ljpeg -lm -logg -lvorbis -lvorbisfile -lfontconfig
 #DEFS = -DLINUX -DUSE_AVIFILE -DUSE_OGG_VORBIS
-DEFS = -DLINUX -DUSE_AVIFILE -DUSE_OGG_VORBIS -DUSE_LUA -DUSE_FONTCONFIG
+DEFS = -DLINUX -DUSE_OGG_VORBIS -DUSE_FONTCONFIG
 
 # with Integer OggVorbis and AVI in PDA size
 #LIBS = `sdl-config --libs` `smpeg-config --libs` `avifile-config --libs` -lSDL_ttf -lSDL_image -lSDL_mixer -lbz2 -ljpeg -lm -lvorbisidec
@@ -33,7 +33,7 @@
 LD = g++ -o 
 
 #CFLAGS = -g -Wall -pipe -c $(INCS) $(DEFS)
-CFLAGS = -O3 -Wall -fomit-frame-pointer -pipe -c $(INCS) $(DEFS)
+CFLAGS += -c $(INCS) $(DEFS)
 
 # for GCC on PowerPC specfied
 #CC = powerpc-unknown-linux-gnu-g++
@@ -50,8 +50,8 @@
 RM = rm -f
 
 #TARGET = onscripter$(EXESUFFIX) sardec$(EXESUFFIX) nsadec$(EXESUFFIX) sarconv$(EXESUFFIX) nsaconv$(EXESUFFIX)
-TARGET = onscripter$(EXESUFFIX) sardec$(EXESUFFIX) nsadec$(EXESUFFIX) sarconv$(EXESUFFIX) nsaconv$(EXESUFFIX) simple_aviplay$(EXESUFFIX)
+TARGET = onscripter$(EXESUFFIX)
 #EXT_OBJS = AVIWrapper$(OBJSUFFIX)
-EXT_OBJS = AVIWrapper$(OBJSUFFIX) LUAHandler$(OBJSUFFIX)
+#EXT_OBJS = AVIWrapper$(OBJSUFFIX) LUAHandler$(OBJSUFFIX)
 
 include Makefile.onscripter
