pre_install() {
	id jetty &>/dev/null || useradd -r -c "Jetty daemon" -g daemon -d /opt/jetty -s /bin/false jetty
}

post_install() {
	sed -i "s/jettyUID/`id -u jetty`/" /opt/jetty/etc/jetty-setuid.xml
	sed -i "s/daemonGID/`id -g daemon`/" /opt/jetty/etc/jetty-setuid.xml
	chown -R jetty.daemon /opt/jetty/logs
}

pre_upgrade() {
	pre_install $1
}

post_upgrade() {
	post_install $1
}

post_remove() {
	if getent passwd jetty >/dev/null 2>&1; then
		userdel jetty &>/dev/null
	fi
}

