infodir=usr/share/info
filelist=(msmtp.info)

post_install() {
  for file in "${filelist[@]}"; do
    install-info "$infodir/$file" "$infodir/dir"
  done

  echo "To set up the queue scripts, read /usr/share/doc/msmtp/README.msmtpq"
  echo "The queue scripts have been installed at /usr/bin/"

}

post_upgrade() {
  post_install
}

pre_remove() {
  for file in "${filelist[@]}"; do
    install-info --delete "$infodir/$file $infodir/dir" 2>/dev/null
  done
}

