# This is a default template for a post-install scriptlet.  You can
# remove any functions you don't need (and this header).

# arg 1:  the new package version
post_install() {
/bin/true
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  echo ">>>"
  echo ">>> You might be interested in 'smile' package available in AUR:"
  echo ">>> http://aur.archlinux.org/packages.php?ID=17912"
  echo ">>>"
}

op=$1
shift
$op $*
