post_install() {
	cat /usr/share/eboard/themeconf.extras1 >> /usr/share/eboard/eboard_themes.conf
	cat /usr/share/eboard/themeconf.extras2 >> /usr/share/eboard/eboard_themes.conf 
}

pre_remove() {
	diff /usr/share/eboard/eboard_themes.conf /usr/share/eboard/themeconf.extras1 |sed '/</!d' |sed 's/< //' > /tmp/eboard_extras_tmp
	diff /tmp/eboard_extras_tmp /usr/share/eboard/themeconf.extras2 |sed '/</!d' |sed 's/< //' > /usr/share/eboard/eboard_themes.conf
	rm -f /tmp/eboard_extras_tmp
}
