# arg 1: The new package version
post_install() {

   _VERSION=`echo $1 | cut -f-1 -d '-'`

   # General info
   echo
   echo "To launch the IDE, simply type 'realstudio'."
   echo
   echo "RealStudio is no longer free for Linux except for open"
   echo "source projects, see www.realsoftware.com/store/opensource"
   echo "for more details."
   echo
   echo "For printing support in REALStudio you must intall cups."
   echo
}

op=$1
shift

$op $*
