post_install() {
	cp /usr/lib/syslinux/memdisk /boot/
	
	echo "------------------------------------------------------------"
	echo "> Place live iso images you want to boot in /boot/images/"
	echo "> Run grub-mkconfig -o /boot/grub/grub.cfg to have them"
	echo "> added automatically to grub.cfg"
	echo "------------------------------------------------------------"
}

post_upgrade() {
	echo "------------------------------------------------------------"
	echo "> Place live iso images you want to boot in /boot/images/"
	echo "> Run grub-mkconfig -o /boot/grub/grub.cfg to have them"
	echo "> added automatically to grub.cfg"
	echo "------------------------------------------------------------"
}

post_remove() {
	rm /boot/memdisk

	echo "------------------------------------------------------------"
	echo "> You may want to remove your iso images in /boot/images/"
	echo "------------------------------------------------------------"
}
# vim:set ts=2 sw=2 et:
