Arch has a different path for xerces-2 (/opt/xerces-c-2)
--- makefile	2008-05-16 16:15:55.000000000 +0530
+++ makefile	2009-08-01 09:22:58.000000000 +0530
@@ -102,7 +102,8 @@
 
 VPATH = source:source/BlahtexCore:source/BlahtexXMLin
 
-INCLUDES=-I. -Isource -Isource/BlahtexCore -Isource/BlahtexXMLin
+INCLUDES=-I. -Isource -Isource/BlahtexCore -Isource/BlahtexXMLin -I/opt/xerces-c-2/include
+LIBRARIES=-L. -L/opt/xerces-c-2/lib
 
 $(BINDIR)/%.o:%.cpp
 	$(CXX) $(INCLUDES) $(CFLAGS) -c $< -o $@
@@ -123,7 +124,7 @@
 	$(CXX) $(CFLAGS) -o blahtex -liconv $(OBJECTS)
 
 blahtexml-linux:  $(BINDIR_XMLIN) $(OBJECTS_XMLIN)  $(HEADERS_XMLIN)
-	$(CXX) $(CFLAGS) -o blahtexml $(OBJECTS_XMLIN) -lxerces-c
+	$(CXX) $(CFLAGS) $(LIBRARIES) -o blahtexml $(OBJECTS_XMLIN) -lxerces-c
 
 blahtexml-mac: $(BINDIR_XMLIN) $(OBJECTS_XMLIN)  $(HEADERS_XMLIN)
 	$(CXX) $(CFLAGS) -o blahtexml -liconv $(OBJECTS_XMLIN) -lxerces-c
