suse_version_info() {
    echo -e "\n\tAbout suse_version:\n"                                                            \
"\tThe variable \"suse_version\" in this package is set to \"openSUSE:Factory\".\n"               \
         "\tCustomize file /usr/lib/rpm/macros.d/macros.suse to suit your own setup.\n"           \
         "\tAnother way is to have RPM macro file that overrides the site-wide version settings."
}

post_install() {
    suse_version_info
}

post_upgrade() {
    suse_version_info
}
