post_install()
{
  if [ ! "`grep /usr/lib/seal /etc/ld.so.conf`" ]; then
    echo -n "updating /etc/ld.so.conf... "
    echo "/usr/lib/seal" >> /etc/ld.so.conf
    /sbin/ldconfig -r .
    echo "done."
  fi
}

post_upgrade()
{
  post_install $1
}

pre_remove()
{
  echo -ne "\nupdating /etc/ld.so.conf... "
  sed -e '/\/usr\/lib\/seal/d' -i /etc/ld.so.conf
  /sbin/ldconfig -r .
  echo "done."
}

op=$1
shift

$op $*
