# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=byebug
pkgname=ruby-$_gemname
pkgver=3.5.1
pkgrel=1
pkgdesc='Ruby 2.0 fast debugger - base + cli'
arch=(i686 x86_64)
url='https://github.com/deivid-rodriguez/byebug'
license=(BSD)
depends=(ruby ruby-columnize ruby-slop ruby-debugger-linecache)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('45d243c90f841e05da3c519f86e702af226ce306')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"

  rm -rf "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/ext"
}
