post_install() {
  cd /opt/openoffice.org3/program
  ./unopkg add --shared /opt/openoffice.org3/share/extension/install/dict-ru.oxt
  ./unopkg add --shared /opt/openoffice.org3/share/extension/install/dict-en.oxt
  ./unopkg add --shared /opt/openoffice.org3/share/extension/install/LanguageTool-0.9.9.oxt
  [ -x /usr/bin/update-desktop-database ] && /usr/bin/update-desktop-database > /dev/null 2>&1
}

pre_upgrade() {
  /bin/true
}

post_upgrade() {
  post_install $1 
}

pre_remove () {
  rm -r /opt/openoffice.org3/share/{uno_packages,registry} 
}

post_remove () {
  [ -x /usr/bin/update-desktop-database ] && /usr/bin/update-desktop-database > /dev/null 2>&1
}

op=$1
shift

$op $*
