#!/bin/bash

# general config
. /etc/rc.conf
. /etc/rc.d/functions

EIBD_BIN=/usr/bin/eibd
EIBD_ARGUMENTS="-i ipt:192.168.123.124"
PID=`pidof -o %PPID $EIBD_BIN`

case "$1" in
    start)
        stat_busy "Starting eibd"
        if [ -z "$PID" ]; then
          stat_busy "Starting eibd"
          $EIBD_BIN $EIBD_ARGUMENTS &
        fi
        if [ ! -z "$PID" -o $? -gt 0 ]; then
          stat_fail
        else
          add_daemon eibd
          stat_done
        fi
        ;;
    stop)
        stat_busy "Stopping eibd"
        [ ! -z "$PID" ] && kill $PID &> /dev/null
        if [ $? -gt 0 ]; then
          stat_fail
        else
          rm_daemon eibd
          stat_done
        fi
        ;;
    *)
        echo "usage: $0 {start|stop|}"
	;;
esac
exit 0
