#!/bin/bash
#
# Python wrapper/launcher

if [ -f ~/.bash_aliases ]; then
. ~/.bash_aliases
fi

CURDIR=`pwd`

if [ -f $CURDIR/src/festige.py ]; then
  exec python $CURDIR/src/festige.py "$@"
elif [ -f /usr/share/festige/festige.py ]; then
  exec python /usr/share/festige/festige.py "$@"
else
  echo "FeSTige doesn't not seem to be installed correctly"
  echo "Please run 'make' and '[sudo] make install' to install it."
fi

