post_install() {
    echo "#####################################################################"
    echo "# For sending fax with CUPS you need cups, ghostscript, gnu-netcat, #"
    echo "# xterm and optional zenity. You have to install a raw-printer in   #"
    echo "# CUPS.                                                             #"
    echo "# For further instructions look at /usr/sbin/capifax-cups!          #"
    echo "#####################################################################"
}
