post_install() {
	# This is easy to automate. Do it!
	sed -i 's/^[^#]/#&/' /etc/acpi/events/anything

#  echo ">>> To use this package, you will have to change your events handler"
#  echo ">>> in /etc/acpi/events/anything to be /etc/acpi/handler_eee.sh."

	echo ">>> See /etc/acpi/eee.conf for configurable options."
}

post_upgrade() {
  post_install
  echo ">>>"
  echo ">>> You should now restart acpid for the changes to take effect."
}

# vim:set ts=2 sw=2 et:
