## arg 1:  the new package version
post_install() {
	echo -e "\\n\\n\\t\\e[01;37m::\\e[00m \\e[01;31mbashbookmarks $1\\e[00m \\e[01;37m::\\e[00m\\n\\nThis package adds \\e[01;37mtag()\\e[00m and \\e[01;37mgat()\\e[00m functions into bash.\\n\\n \$ \\e[01;37mtag\\e[00m \\e[01;31m<arg>\\e[00m marks your current position in filesystem under a given \"alias\".\\n\\n \$ \\e[01;37mgat\\e[00m \\e[01;31m<arg>\\e[00m cd's to given \"alias\". Aliases are stored at ~/.bash-bookmarks.\\n\\n Type:\\n\\n  \\e[01;30m# bookmarks system\\e[00m\\n  \\e[01;37m. /etc/profile.d/bash_bookmarks.sh\\e[00m\\n\\n to use it immediately. Or simply restart your bash shell.\\n"
}
