## arg 1:  the new package version
post_install() {
  echo 
  echo "This package adds tag() and gat() functions into bash."
  echo "tag <arg> marks your current position in filesystem under a given 'alias'."
  echo "gat <arg> cd's to given 'alias'. Aliases are stored at ~/.bash-bookmarks."
  echo "to use it you need to source /etc/profile.d/bash_bookmarks.sh"
  echo "and /etc/bash_completion.d/bash_bookmarks to your bash instance."
}
