post_install() {
    lpadmin -p BRFAX -E -m brfax_cups.ppd &&
      lpadmin -p BRFAX -D 'Brother PC-FAX' &&
        cat <<EOF || echo -e '\n*** Configuration failed!  Is CUPS running?\n'

Configure BRFAX URI using 'lpadmin -v' or http://localhost:631
Follow step 5a or 5b on this page:
  http://support.brother.com/g/s/id/linux/en/instruction_pcf1a.html

EOF
}

post_remove() {
    lpadmin -x BRFAX ||
      echo -e '\n*** Removal incomplete!  Is CUPS running?'
}
