#!/bin/sh
# Altered for Archlinux rc system by andrew@lightningtoads.com
#
# description: pvfs2-server is the server component of PVFS2
#
# chkconfig: 345 35 55

# Source function library.
. /etc/rc.conf
. /etc/rc.d/functions

# Configuration information moved to /etc/conf.d/pvfs2-server.conf
[ -f /etc/conf.d/pvfs2-server.conf ] && . /etc/conf.d/pvfs2-server.conf

# verify presence of server binary
if ! [ -x ${PVFS2SERVER} ]; then
	echo "Error: could not find executable ${PVFS2SERVER}"
	exit 1
fi

# look for fs conf
if test "x$PVFS2_FS_CONF" = x
then
	PVFS2_FS_CONF=${PVFS2_CONF_PATH}/pvfs2-fs.conf
fi
if ! [ -r ${PVFS2_FS_CONF} ]; then
	echo "Error: could not read ${PVFS2_FS_CONF}"
	exit 1
fi

# See how we were called.
PID=`cat $PVFS2_PIDFILE 2>/dev/null`
case "$1" in
  start)
	stat_busy "Starting PVFS2 server: "
	[ -z "$PID" ] && ${PVFS2SERVER} --pidfile ${PVFS2_PIDFILE} ${PVFS2_FS_CONF}
	if [ $? -gt 0 ]; then
		stat_fail
	else
		add_daemon pvfs2-server
		touch /var/lock/pvfs2-server
		stat_done
	fi
	;;
  stop)
	stat_busy "Stopping PVFS2 server: "
	[ ! -z "$PID" ]  && kill $PID &> /dev/null
	if [ $? -gt 0 ]; then
		stat_fail
	else
		rm_daemon pvfs2-server
		rm -f /var/lock/pvfs2-server
		stat_done
	fi
	;;
  status)
        status pvfs2-server
	;;
  restart)
	$0 stop
	# give server time to die cleanly
	sleep 2
	$0 start
	;;
  *)
	echo "Usage: $0 {start|stop|status|restart}"
	exit 1
esac

exit 0

