--- src/Makefile	2009-08-26 15:51:14.415917447 +0300
+++ ../Makefile	2009-08-26 15:51:54.096388161 +0300
@@ -283,7 +283,6 @@
 	$(HEADER_DIR)/types.h \
 	$(HEADER_DIR)/connection.h \
 	$(HEADER_DIR)/property.h \
-	$(HEADER_DIR)/debug.h \
 	$(HEADER_DIR)/error.h \
 	$(HEADER_DIR)/interface.h \
 	$(HEADER_DIR)/message.h \
