# Maintainer: Dennis Fink <the_metalgamer@hackerspace.lu
# Contributor: Rick W. Chen <stuffcorpse@archlinux.us>

pkgname=acoustid-fingerprinter-git
pkgver=71.c43b97d
pkgrel=1
pkgdesc="A cross-platform GUI application for submitting audio fingerprints generated by Chromaprint."
arch=('i686' 'x86_64')
url="http://acoustid.org/fingerprinter"
license=('GPL')
provides=('acoustid-fingerprinter')
conflicts=('acoustid-fingerprinter' 'acoustid-fingerprinter-bzr')
depends=('taglib' 'chromaprint' 'qt4')
makedepends=('git' 'cmake')
source=("git+https://bitbucket.org/acoustid/acoustid-fingerprinter.git")
md5sums=('SKIP')

_gitname="acoustid-fingerprinter"

pkgver() {

  cd "$srcdir"/$_gitname
  echo $(git rev-list --count HEAD).$(git rev-parse --short HEAD)

}

build() {

  cd "$srcdir/$_gitname"

  cmake "$srcdir/$_gitname" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release
}

package() {
  cd "$srcdir/$_gitname"
  make DESTDIR="$pkgdir/" install
} 
