# Maintainer: Dennis Fink <the_metalgamer@hackerspace.lu
# Contributor: Rick W. Chen <stuffcorpse@archlinux.us>

pkgname=acoustid-fingerprinter-git
pkgver=20130303
pkgrel=2
pkgdesc="A cross-platform GUI application for submitting audio fingerprints generated by Chromaprint."
arch=('i686' 'x86_64')
url="http://acoustid.org/fingerprinter"
license=('GPL')
provides=('acoustid-fingerprinter')
conflicts=('acoustid-fingerprinter' 'acoustid-fingerprinter-bzr')
depends=('taglib' 'chromaprint' 'qt4')
makedepends=('git' 'cmake')
_gitroot="https://bitbucket.org/acoustid/acoustid-fingerprinter.git"
_gitname="acoustid-fingerprinter"

build() {
  cd "$srcdir"
  msg "Connecting to GIT server...."

  if [ -d $_gitname ] ; then
    cd $_gitname && git pull origin
    msg "The local files are updated."
  else
    git clone $_gitroot $_gitname
  fi

  msg "GIT checkout done or server timeout"
  msg "Starting make..."

  rm -rf "$srcdir/$_gitname-build"
  mkdir "$srcdir/$_gitname-build"
  cd "$srcdir/$_gitname-build"

  cmake "$srcdir/$_gitname" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release
}

package() {
  cd "$srcdir/$_gitname-build"
  make DESTDIR="$pkgdir/" install
} 
