#!/bin/sh

if [ -n "$DESKTOP_AUTOSTART_ID" ]; then
	dbus-send --session --print-reply=string --dest=org.gnome.SessionManager "/org/gnome/SessionManager" org.gnome.SessionManager.RegisterClient "string:i3-gnome" "string:$DESKTOP_AUTOSTART_ID"
fi

i3
