#!/bin/sh

if [ -n "$DESKTOP_AUTOSTART_ID" ]; then
	dbus-send --session --print-reply=string --dest=org.gnome.SessionManager "/org/gnome/SessionManager" org.gnome.SessionManager.RegisterClient "string:i3-gnome" "string:$DESKTOP_AUTOSTART_ID"
fi

# Fix the cursor missing problem
dconf write /org/gnome/settings-daemon/plugins/cursor/active false

# Disable Gnome Shell's App Menu, so that lost menu items are shown again
gsettings set org.gnome.settings-daemon.plugins.xsettings overrides '@a{sv} {"Gtk/ShellShowsAppMenu": <int32 0>}'

i3
