pkgname=i3-gnome

post_install() {
  update-desktop-database -q
  echo "In '~/.config/i3/config':"
  echo "* use 'exec gnome-session-quit --logout'    : logout dialog"
  echo "* use 'exec gnome-session-quit --power-off' : shutdown menu"
  echo "If you have gnome-screensaver installed and want to use it:"
  echo "* use 'exec gnome-screensaver-command -l'   : locks the screen"
}

post_upgrade() {
  post_install "$1"
}

post_remove() {
  update-desktop-database -q
}

# vim:set ts=2 sw=2 et:
