post_install() {
  echo -n "Updating font cache... "
  fc-cache usr/share/fonts/envypn
  mkfontdir usr/share/fonts/envypn
  echo "You can read changelog with pacman -Qc envypn-font"
  echo "You may take a look at the README"
  echo "done"
}

post_upgrade() {
  echo -n "Updating font cache... "
  echo "You can read changelog with pacman -Qc envypn-font"
  echo "You may take a look at the README"
  echo "done"
}
