post_install(){
    if [[ -e /usr/lib/monodoc/monodoc.xml && -z `grep 'TagLib#' /usr/lib/monodoc/monodoc.xml` ]]; then
	sed -ie '/label=\"Various\"/ a\    <node label=\"TagLib#\" name=\"classlib-taglib-sharp\" \/>' /usr/lib/monodoc/monodoc.xml
    fi || return 1
}
post_remove(){
    if [[ -e /usr/lib/monodoc/monodoc.xml ]]; then
	sed -ie '/TagLib/ d' /usr/lib/monodoc/monodoc.xml
    fi || return 1
}

op=$1
shift
$op "$@"
