#!/bin/bash

#   excute lateralgm jar file.
cd /opt/enigma-dev-git/ # fix for strange bug, where you have to be in the same directory as lgm16b4.jar.
if [[ -a lateralgm.jar ]];then
  java -jar lateralgm.jar 
fi
if [[ -a lgm16b4.jar ]];then
  java -jar lgm16b4.jar
fi