post_install() {
	echo -e "\n#############################################################################\n"
	echo -e "Compiz can be started manually by issuing 'compiz ccp --replace' from the command-line. Add the --indirect-rendering argument if you're using Intel graphics, or --loose-binding if Compiz is sluggish with NVIDIA graphics. " | fold -s
	if [ -f /usr/share/applications/compiz.desktop ]; then
		echo -e "\nWhen using GNOME, additional arguments can be appended to the 'Exec' line in /usr/share/applications/compiz.desktop to make permanent changes." | fold -s
	fi
	echo -e "\nTo get window decorations working, open CompizConfig Settings Manager (install ccsm-dev), navigate to Effects > Window Decoration and set the command as desired, i.e. enter 'gtk-window-decorator' if using GNOME, 'kde-window-decorator' or 'emerald' (a seperate package) and append '--replace'. GNOME users can install gnome-tweak-tool for convenient control of window decoration themes.\n\nPlease refer to the wiki entry on Compiz at https://wiki.archlinux.org/index.php/Compiz for further information." | fold -s
	echo -e "\n#############################################################################\n"
}

pre_remove()
{
	if [ -f /usr/share/gnome-session/sessions/gnome-compiz.session ]; then
		read -N1 -p "Remove GNOME session entries? i.e. /usr/share/{gnome-session/sessions/gnome-compiz.session,xsessions/gnome-compiz.desktop} (y/n) "
		echo -e "\n"
		if [[ "$REPLY" = [yY] ]]; then
			rm -f /usr/share/{gnome-session/sessions/gnome-compiz.session,xsessions/gnome-compiz.desktop,applications/compiz.desktop}
		fi
	fi
	if [ -f /usr/share/applications/compiz.desktop ]; then
		read -N1 -p "Remove XDG menu entry? i.e. /usr/share/applications/compiz.desktop (y/n) "
		echo -e "\n"
		if [[ "$REPLY" = [yY] ]]; then
			rm -f /usr/share/applications/compiz.desktop
		fi
	fi
}
