post_install() {
        if [[ -f /usr/bin/gtk-window-decorator && -f /usr/bin/gconftool-2 ]]; then
	        export GCONF_CONFIG_SOURCE=`/usr/bin/gconftool-2 --get-default-source`
	        echo -ne "\n:: Installing gtk-window-decorator schema file... "
	        /usr/bin/gconftool-2 --makefile-install-rule /usr/share/gconf/schemas/gwd.schemas > /dev/null
	        if [ $? -gt 0 ]; then
		        echo "Failed"
	        else
		        echo "OK"
	        fi
                echo -e "\nNew users may wish to install compizconfig-backend-gconf-dev for ease of setup."
        fi
	echo -e "\n=============================================================================\n"                 
        echo -e "Compiz can be started manually by issuing 'compiz ccp --replace' from the command-line. Add the --indirect-rendering argument if you're using open source drivers and AIGLX (e.g. xf86-video-intel), or --loose-binding if Compiz is sluggish with proprietory NVIDIA drivers.\n\nFor further information, please refer to the following wiki entry:\n\nhttps://wiki.archlinux.org/index.php/Compiz" | fold -s
        
	echo -e "\n=============================================================================\n"
}

pre_remove()
{
        if [ -f /usr/bin/gconftool-2]; then
	        export GCONF_CONFIG_SOURCE=`/usr/bin/gconftool-2 --get-default-source`
	        /usr/bin/gconftool-2 --makefile-uninstall-rule /usr/share/gconf/schemas/gwd.schemas >/dev/null
        fi
	if [ -f /usr/share/gnome-session/sessions/gnome-compiz.session ]; then
		read -N1 -p "Remove GNOME session entries? i.e. /usr/share/{gnome-session/sessions/gnome-compiz.session,xsessions/gnome-compiz.desktop} (y/n) "
		echo -e "\n"
		if [[ "$REPLY" = [yY] ]]; then
			rm -f /usr/share/{gnome-session/sessions/gnome-compiz.session,xsessions/gnome-compiz.desktop,applications/compiz.desktop}
		fi
	fi
	if [ -f /usr/share/applications/compiz.desktop ]; then
		read -N1 -p "Remove XDG menu entry? i.e. /usr/share/applications/compiz.desktop (y/n) "
		echo -e "\n"
		if [[ "$REPLY" = [yY] ]]; then
			rm -f /usr/share/applications/compiz.desktop
		fi
	fi
}
