# This PKGBUILD was generated by cpan4pacman via CPANPLUS::Dist::Pacman
# Contributor: fedor <fedor@yu.wildpark.net>

pkgname=perl-cyrillic
pkgver=2.09
pkgrel=1
pkgdesc="Library for fast and easy cyrillic text manipulation"
arch=('i686' 'x86_64')
url="http://www.perl.com/CPAN"
license=('GPL' 'PerlArtistic')
depends=('perl')
options=('!emptydirs')
source=(cyrillic-$pkgver.tar.gz) 

build() {
  cd  $startdir/src/cyrillic-$pkgver
  PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor || return 1 
  make || return 1
  make install DESTDIR=$startdir/pkg || return 1
  find $startdir/pkg -name '.packlist' -delete
  find $startdir/pkg -name '*.pod' -delete
}
