post_install() {
  echo "When started, Mnemosyne 2 looks for a Mnemosyne 1.x database in"
  echo "~/.mnemosyne/ and tries to automatically import it. It won't overwrite"
  echo "it, though, as it stores its own database in ~/.local/share/mnemosyne/."
  echo "After confirming that it has successfully been imported once, manually"
  echo "delete the old ~/.mnemosyne/ folder (after doing a backup, to be safe)"
  echo "so Mnemosyne won't try to automatically import it again."
}
