post_install() {                                                                
  echo "    After running program copy database to \$HOME directory:"                 
  echo "      cp /usr/lib/food_gui/db_eng.dat ~/.config/food_gui/db.dat"                   
  echo "    or"                                                                      
  echo "      cp /usr/lib/food_gui/db_rus.dat ~/.config/food_gui/db.dat"                   
}
