--- Makefile.old	2013-05-22 13:42:47.124469398 +0200
+++ Makefile	2013-07-06 11:55:47.178171463 +0200
@@ -58,7 +58,9 @@
       K_MAJORSUB := $(K_VERSION).$(K_PATCHLEVEL).$(K_SUBLEVEL)
     endif
   else ifeq ($(K_VERSION), 3)
-    ifeq ($(shell [ $(K_PATCHLEVEL) -ge 9 ] && echo true), true)
+    ifeq ($(shell [ $(K_PATCHLEVEL) -ge 10 ] && echo true), true)
+      SURROGATE := 3.10
+    else ifeq ($(shell [ $(K_PATCHLEVEL) -ge 9 ] && echo true), true)
       SURROGATE := 3.9
     else ifeq ($(shell [ $(K_PATCHLEVEL) -ge 7 ] && echo true), true)
       SURROGATE := 3.7
