post_install()
{
	cat << EOF
Run "/etc/rc.d/phc-intel setup" to build the module for current kernel.
You can enter the desired voltage IDs in /etc/conf.d/phc-intel.
Booting with nophc kernel parameter skips setting of VIDs in case of failure.
EOF
}

post_remove()
{
	echo Removing built modules ...
	rm -f var/log/phc-intel.log
	cd lib/modules/
	rm -f */extra/phc-intel.ko
	rmdir -p --ignore-fail-on-non-empty */extra/
	echo Updating module dependencies ...
	for i in *; do
		depmod $i
	done
}
