use_pepperflash=0
CARCH=0


update_resources() {
        xdg-icon-resource forceupdate --theme hicolor &> /dev/null
        update-desktop-database -q
}

instructions() {
  /bin/cat << EOF

Disable all other flash plugins:
Type chrome://plugins/ in the adress bar and press Enter
Click on Details button on the top right
Click on Disable near all the Flash plugins except the first one

EOF
}

post_install() {
        if [ "${use_pepperflash}" = "1" ]; then
          if [[ $(cat etc/chromium-dev/default) == *ppapi* ]]; then
             : # do nothing
          else
             sed '/CHROMIUM_FLAGS/s|"$|--ppapi-flash-path=0 --ppapi-flash-version=0"|' -i /etc/chromium-dev/default
          fi
          instructions
        fi
        update_resources
}

post_upgrade() {
        if [ "${use_pepperflash}" = "1" ]; then
            [ "${CARCH}" = "i686" ] && sed "s|path=/usr/lib/chromium-dev/libgcflashplayer.so|path=0|g" -i /etc/chromium-dev/default
            sed "s|ppapi-flash-version=.*[0-9]|ppapi-flash-version=0|g" -i /etc/chromium-dev/default
            if [[ $(cat etc/chromium-dev/default) == *ppapi* ]]; then
                : # do nothing
            else
                sed '/CHROMIUM_FLAGS/s|"$|--ppapi-flash-path=0 --ppapi-flash-version=0"|' -i /etc/chromium-dev/default
            fi
        fi
        [ "${use_pepperflash}" = "0" ] && sed "s|--ppapi-flash-path=0 --ppapi-flash-version=1.*[0-999]||g" -i /etc/chromium-dev/default
        update_resources
}

post_remove() {
        [ "${use_pepperflash}" = "1" ] && sed 's|--ppapi-flash-path=0 --ppapi-flash-version=1.*[0-999]||' -i /etc/chromium-dev/default
        update_resources
}
