#contributor Mathieu Clabaut <mathieu.clabaut@gmail.com>
# PKGBUILD generated by pacpan
pkgname=perl-xml-parser-perlsax
_realname=XML-Parser-PerlSAX
pkgver=0.08
pkgrel=1
pkgdesc="no description available"
arch=(i686 x86_64)
license=('unknown: check http://search.cpan.org/src/KMACLEOD/libxml-perl-0.08/README.txt')
url="http://search.cpan.org/~kmacleod/XML-Parser-PerlSAX"
options=(!emptydirs)


#provides=('XML-Parser-PerlSAX')
provides=('xml-parser-perlsax=0.08' 'XML::Handler::CanonXMLWriter=0.08' 'perl-xml-handler-canonxmlwriter=0.08' 'XML::ESISParser=0.08' 'perl-xml-esisparser=0.08' 'XML::PatAct::Amsterdam=0.08' 'perl-xml-patact-amsterdam=0.08' 'XML::Handler::Sample=undef' 'perl-xml-handler-sample=undef' 'XML::Handler::Subs=0.08' 'perl-xml-handler-subs=0.08' 'XML::PatAct::ToObjects=0.08' 'perl-xml-patact-toobjects=0.08' 'MyHandler=undef' 'perl-myhandler=undef' 'XML::Parser::PerlSAX=0.08' 'perl-xml-parser-perlsax=0.08' 'XML::PatAct::MatchName=0.08' 'perl-xml-patact-matchname=0.08' 'XML::SAX2Perl=0.08' 'perl-xml-sax2perl=0.08' 'XML::Handler::XMLWriter=0.08' 'perl-xml-handler-xmlwriter=0.08' 'Data::Grove::Parent=0.08' 'perl-data-grove-parent=0.08' 'Data::Grove::Visitor=0.08' 'perl-data-grove-visitor=0.08' 'Data::Grove=0.08' 'perl-data-grove=0.08' 'XML::Perl2SAX=0.08' 'perl-xml-perl2sax=0.08')

source=(http://search.cpan.org/CPAN/authors/id/K/KM/KMACLEOD/libxml-perl-0.08.tar.gz)
md5sums=('0ed5fbdda53d1301ddaed88db10503bb')

build() {
  _expected_dir="${srcdir}/${_realname}-${pkgver}"
  if [ -d "$_expected_dir" ]; then
    cd "$_expected_dir"
  else
    _expected_dir="${srcdir}/$(bsdtar -t -f $(basename $source) | head -n1)"
    if [ -d "$_expected_dir" ]; then
      cd "$_expected_dir"
    else
      _makefile=$(find $srcdir -iname Makefile.PL)
      if [ ! -z "$_makefile" ]; then
        _expected_dir=$(dirname $_makefile)
        if [ -d "$_expected_dir" ]; then
          cd "$_expected_dir"
        else
          echo "[1;31mERROR[0m unable to detect source directory"
          echo "[1;34m-->[0m this is often due to CPAN's lack of standard naming conventions"
          echo "[1;34m-->[0m it may be possible to fix this by adjusting the build function in the PKGBUILD"
        fi
      fi
    fi
  fi
  # install module in vendor directories.
  PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor || return 1
  make  || return 1
  make install DESTDIR=${pkgdir} || return 1

  # remove perllocal.pod and .packlist
  find ${pkgdir} -name perllocal.pod -delete
  find ${pkgdir} -name .packlist -delete
}
