--- scripts/Makefile	2007-09-12 02:43:45.000000000 +0200
+++ scripts/Makefile.new	2007-12-11 00:16:11.000000000 +0100
@@ -36,7 +36,7 @@
 	pod2man --center=" " --release="Debian Utilities" $< > $@
 %.1: %.dbk
 	xsltproc --nonet -o $@ \
-	  /usr/share/sgml/docbook/stylesheet/xsl/nwalsh/manpages/docbook.xsl $<
+	  /usr/share/xml/docbook/xsl-stylesheets-1.73.2/manpages/docbook.xsl
 
 libvfork.o: libvfork.c
 	$(CC) -fPIC -D_REENTRANT $(CFLAGS) -c $<
