#!/bin/bash
###############################################################################
#
# Jasmin Java Assembler startup script.
#
###############################################################################

JASMIN_JAR="/usr/share/java/jasmin.jar"

java -jar "$JASMIN_JAR" "$@"

