post_install() {
cat << EOF
    load xlicense.el:
    (load-library "/usr/share/emacs/site-lisp/xlicense.el")

Additional abbreviation setup is recommended, e.g.:

    (define-abbrev-table 'global-abbrev-table
      '(
        ("$$license" "" license-skeleton)
        ))

    (add-hook 'c-mode-hook (function (lambda nil (abbrev-mode 1))))
    (add-hook 'c++-mode-hook (function (lambda nil (abbrev-mode 1))))
EOF
}

post_upgrade() {
  post_install
}
