# arg 1:  the new package version

_pkgname=drakma

post_install() {
    cat << EOM

    To load this library with asdf, run the following line
    (or its equivalent for your lisp of choice):

    (asdf:load-system '${_pkgname})
EOM
}

post_upgrade() {
    post_install
}

pre_remove() {
    rm -f /usr/share/common-lisp/$_pkgname/{*.fas,*.fasl,*.lib,*.x86f}
}

pre_upgrade() {
    pre_remove
}

# End of file
