# arg 1:  the new package version
post_install() {
  echo ">>> audiotools will use a PulseAudio server if available." 
  echo ">>> audiotools can burn a CD with cdrecord or cdrdao."
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  echo ">>> audiotools will use a PulseAudio server if available."
  echo ">>> audiotools can burn a CD with cdrecord or cdrdao."
}

op=$1
shift
$op $*

