post_install() {
echo "due to Python3 becoming default for Archlinux, a change is needed in 
/usr/bin/heybuddy:"
echo "if you get an error about python22, change the !# to python2 after installing"
echo "yes, it is an ugly hack"
echo ""
echo "-Spellchecking in heybuddy-"
echo ""
echo "Optional dependences for spellcheck"
echo ""
echo "gtkspell"
echo "python-gtkspell from AUR"
echo "aspell-{locale}" 
}

post_upgrade() {
  post_install 
}

