#!/bin/bash

SCRIPT_DIR=`dirname $0`

classpath=$CLASSPATH
for jarfile in `ls /usr/share/pmd/lib/*.jar`; do
	classpath=$classpath:$jarfile
done

java -cp $classpath net.sourceforge.pmd.util.designer.Designer
