
post_install() {
  cd /usr/share/Aria/
  xdg-mime install auria-ariamaestosa.xml
  xdg-icon-resource install --context mimetypes --size 64 aria_doc.png audio-auria-ariamaestosa
  gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
  update-desktop-database /usr/share/applications
}

post_upgrade() {
  post_install
}

pre_remove() {
  xdg-mime uninstall /usr/share/Aria/auria-ariamaestosa.xml
  xdg-icon-resource uninstall --context mimetypes --size 64 audio-auria-ariamaestosa
}

