#!/bin/bash

USER=
DROPBOX=dropboxd

INTERFACE=$1 # The interface which is brought up or down
STATUS=$2 # The new state of the interface

case "$STATUS" in
    up) # $INTERFACE is up
      sudo -u $USER DISPLAY=:0 $DROPBOX
      ;;
    down) # $INTERFACE is down
      killall $DROPBOX
      ;;
esac
