post_install () {
    echo -e "\n A correct, MIT-specific, Kerberos 5 configuration file has been placed in /usr/share/mit-zephyr/krb5.conf.mit \n To use Zephyr with MIT, merge the existing Kerberos 5 configuration file, \n or just replace the configuration file with  \n mv /usr/share/mit-zephyr/krb5.conf.mit /etc/krb5.conf"
    
    echo -e "Running multiple Zephyr Host Manager (zhm) instances is not encouraged, so instead, the ZHM service can be enabled with 'systemctl enable zhm'"
}
