post_install() {
	fc-cache -fv >> /dev/null
	gtk-update-icon-cache -f -q /usr/share/icons/hicolor
	update-desktop-database -q
	echo "Done"
}

post_upgrade() {
	fc-cache -fv >> /dev/null
	gtk-update-icon-cache -f -q /usr/share/icons/hicolor
	update-desktop-database -q
	echo "Done"
}

post_remove() {
  	update-desktop-database -q
	gtk-update-icon-cache -f -q /usr/share/icons/hicolor
	fc-cache -fv >> /dev/null
	echo "Done"
}



