.TH "pyhaslisps" "1" "1.05" "pyhaslisps 1.05" "General Commands Manual"
.SH "NAME"
.LP 
pyhaslisps \- a program that lists the available implementations of common\-lisp; of course, written in python, as the name
.br
suggests.  
.SH "SYNOPSIS"
.LP
pyhaslisps [nth]
.br

    where nth is a number that corresponds to a position in the list returned by pyhaslisps.  (NOTE: an argument is not required, but can be used to select a particular implementation of common\-lisp.) 
.br
.SH "DESCRIPTION"
.LP
 Pyhaslisps determines if any implementations of common\-lisp are currently installed; returning a list of implementations present.  The author/developer hopes that this program will come in handy for packaging lisp programs and libraries. 
.br
.SH "FILES"
.I /usr/share/licenses/pyhaslisps/license.txt

.I /usr/bin/pyhaslisps

.I /usr/share/man/man1/pyhaslisps.1
.SH "AUTHOR"
.LP 
Alexej Magura <agm2819*gmail*>
.br
.SH "COPYRIGHT"
.LP
.br
 BSD\-3 OSI License                                                                    
.br
.br
 Copyright (c) 2013, Alexej Magura                                                    
.br
                                                                                      
.br
 All rights reserved.                                                                 
.br
