# Generated by Xyne::Arch::CPAN 0.07

pkgname=perl-cgi-session-serialize-yaml
pkgver=4.26
pkgrel=1
pkgdesc="Add YAML and YAML::Syck support to CGI::Session's serializers"
arch=('i686' 'x86_64')
url="http://search.cpan.org/dist/CGI-Session-Serialize-yaml/"
license=('PerlArtistic' 'GPL')
source=('http://search.cpan.org/CPAN/authors/id/R/RS/RSAVAGE/CGI-Session-Serialize-yaml-4.26.tgz')
md5sums=('29f35caaf1de910c0a99bdc9b2f05264')
sha256sums=('1a1f9457e4f7df3d5d176a6af06c3cc3e635b9d2eeaa6bf7fc60350496f7474c')
depends=('perl-cgi-session>=4.3')
makedepends=('perl-module-build>=0.3600' 'perl-test-pod')
options=(!emptydirs)

build() {
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Makefile.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor || return 1
    make  || return 1
    make install DESTDIR="${pkgdir}" || return 1

  else
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Build.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Build.PL INSTALLDIRS=vendor || return 1
    ./Build  || return 1
    ./Build install destdir=${pkgdir} || return 1

  else
    echo "error: failed to detect build method for $pkgname"
    echo "you may be able to fix this by editing the PKGBUILD"
    return 1
  fi fi

  # remove perllocal.pod and .packlist
  find ${pkgdir} -name perllocal.pod -delete
  find ${pkgdir} -name .packlist -delete
}

# vim:set ts=2 sw=2 et:

