post_install() {
	echo
	echo -e "\e[33mThis theme provides an additional background picture for wide screens.\e[0m"
	echo -e "\e[33mIt can be selected in System > Preferences > Appearance > Desktop background.\e[0m"
	echo
    # update icon cache
    gtk-update-icon-cache -fq /usr/share/icons/tropical
}

post_upgrade() {
    # update icon cache
    gtk-update-icon-cache -fq /usr/share/icons/tropical
}

pre_remove() {
    rm -f /usr/share/icons/tropical/icon-theme.cache
}

