post_install() {
    update-desktop-database -q
    gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
    echo ""
    echo "Note: this package installs side-by-side with [extra]'s thunderbird."
    echo "The binary is called 'thunderbird-esr'."
    echo ""
}

post_upgrade() {
    post_install
}

post_remove() {
    update-desktop-database -q
    gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}
