post_install() {
    echo "Updating gtk.immodules..."
    gtk-query-immodules-2.0 > etc/gtk-2.0/gtk.immodules
    echo "Done."

    gtk-update-icon-cache -fq -t usr/share/icons/hicolor

    # update for gkt3
    gtk-query-immodules-3.0 --update-cache 
}


post_upgrade() {
    post_install $1
}

post_remove() {
    gtk-query-immodules-2.0 > etc/gtk-2.0/gtk.immodules
    gtk-update-icon-cache -fq -t usr/share/icons/hicolor

    # update for gkt3
    gtk-query-immodules-3.0 --update-cache 
}
