# PKGBUILD generated by pacpan
pkgname=perl-astro-moonphase
_realname=Astro-MoonPhase
pkgver=0.60
pkgrel=1
pkgdesc="Perl/CPAN module Astro::MoonPhase Information about the phase of the Moon"
arch=(any)
license=('unrestricted')
url="http://search.cpan.org/~brett/Astro-MoonPhase"
options=(!emptydirs)

depends=('perl')

#provides=('Astro-MoonPhase')
provides=('astro-moonphase=0.60' 'Astro::MoonPhase=0.60' 'perl-astro-moonphase=0.60')

source=(http://search.cpan.org/CPAN/authors/id/B/BR/BRETT/Astro-MoonPhase-0.60.tar.gz)
md5sums=('746d03558509d5b596f2c92bc8100372')

build() {
  _expected_dir="${srcdir}/${_realname}-${pkgver}"
  if [ -d "$_expected_dir" ]; then
    cd "$_expected_dir"
  else
    _expected_dir="${srcdir}/$(bsdtar -t -f $(basename $source) | head -n1)"
    if [ -d "$_expected_dir" ]; then
      cd "$_expected_dir"
    else
      _makefile=$(find $srcdir -iname Makefile.PL)
      if [ ! -z "$_makefile" ]; then
        _expected_dir=$(dirname $_makefile)
        if [ -d "$_expected_dir" ]; then
          cd "$_expected_dir"
        else
          echo "[1;31mERROR[0m unable to detect source directory"
          echo "[1;34m-->[0m this is often due to CPAN's lack of standard naming conventions"
          echo "[1;34m-->[0m it may be possible to fix this by adjusting the build function in the PKGBUILD"
        fi
      fi
    fi
  fi
  # install module in vendor directories.
  PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor || return 1
  make  || return 1
  make install DESTDIR=${pkgdir} || return 1

  # remove perllocal.pod and .packlist
  find ${pkgdir} -name perllocal.pod -delete
  find ${pkgdir} -name .packlist -delete
}

# vim:set ts=2 sw=2 et:
