post_install() {
	cat << EOF
	    The systemd service expects a configuration file at /etc/ldm.conf with the
	    following options in it :

	    MOUNT_OWNER=<user who owns the mountpoints>
	    BASE_MOUNTPOINT<the base folder for the mountpoints, /mnt is a safe guess>
EOF
}

post_upgrade() {
	if [ ! -f /etc/ldm.conf ]; then
    echo 'NOTE: The configuration file has been moved to /etc/ldm.conf'
	else
		echo 'NOTE: The options that ldm expects in the /etc/ldm.conf file have changed'
	fi
}
