--- Makefile		2012-08-05 00:44:38.000000000 -0300
+++ Makefile.new	2012-08-14 02:37:11.727162635 -0300
@@ -22,7 +22,7 @@
 	@echo
 
 install:
-	$(INSTALL) -m 755 -d $(INSDIR) $(INSDIR)/pix $(INSDIR)/res $(INSDIR)/src
+	$(INSTALL) -m 755 -d $(INSDIR) $(INSDIR)/pix $(INSDIR)/res $(INSDIR)/src $(ICODIR) $(BINDIR) $(APPDIR)
 	$(INSTALL) -m 755 -d $(INSDIR)/src/gui
 	$(INSTALL) -m 755 -d $(INSDIR)/src/media
 	$(INSTALL) -m 755 -d $(INSDIR)/src/media/format
