# This is a default template for a post-install scriptlet.
# Uncomment only required functions and remove any functions
# you don't need (and this header).

post_install() {
  echo "To use the new plasmoid now, run:"
  echo "  kbuildsycoca4"
}

post_upgrade() {
  echo "To use the new plasmoid now, run:"
  echo "  kbuildsycoca4"
}

post_remove() {
  echo "To use the new plasmoid now, run:"
  echo "  kbuildsycoca4"
}

# vim:set ts=2 sw=2 et:
