#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

# source application-specific settings
[ -f /etc/conf.d/clamsmtp ] && . /etc/conf.d/clamsmtp

PID=`cat /var/run/clamav/clamsmtpd.pid 2> /dev/null`

case "$1" in
  start)
    if [ "$START_CLAMSMTP" == "yes" ]; then
       stat_busy "Starting Clamsmtp"
       CLAMSMTP_OPTIONS="-f /etc/clamav/clamsmtpd.conf -p /var/run/clamav/clamsmtpd.pid $CLAMSMTP_OPTIONS"
       [ -z "$PID" ] && /usr/sbin/clamsmtpd $CLAMSMTP_OPTIONS
       if [ $? -gt 0 ]; then
          stat_fail
       else
          add_daemon clamsmtp
          stat_done
       fi
    fi

    ;;
  stop)
    if [ "$START_CLAMSMTP" == "yes" ]; then
       stat_busy "Stopping Clamsmtp"
   	[ -n "$PID" ] && kill $PID &> /dev/null
        if [ $? -gt 0 ]; then
           stat_fail
        else
           rm_daemon clamsmtp
           stat_done
        fi
    fi

    ;;
  restart)
    $0 stop
    # will not start if not fully stopped, so sleep
    sleep 2
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
