# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Babken Vardanyan <483ken@gmail.com>

_gemname=rspec
pkgname=ruby1.9-$_gemname
pkgver=2.99.0
pkgrel=1
pkgdesc='rspec-2.99.0'
arch=(any)
url='http://github.com/rspec'
license=(MIT)
depends=(ruby1.9 ruby1.9-rspec-core ruby1.9-rspec-expectations ruby1.9-rspec-mocks)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('0a609299795f06ec771fd882f07b76b2260161be')

package() {
  local _gemdir="$(ruby-1.9 -e'puts Gem.default_dir')"
  gem-1.9 install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/License.txt" "$pkgdir/usr/share/licenses/$pkgname/License.txt"
}
