post_install() {
/usr/bin/gtk-update-icon-cache
echo -e "Use these commands, as root, to install your standalone license:\n\n "
echo "echo -e 'MAYA_LICENSE=657F1\nMAYA_LICENSE_METHOD=standalone' > /usr/autodesk/maya2014-x64/bin/License.env"
echo -e "export LD_LIBRARY_PATH=/opt/Autodesk/Adlm/R7/lib64\n
/usr/autodesk/maya2014-x64/bin/adlmreg -i S 657F1 657F1 2014.0.0.F <your serial number> /var/opt/Autodesk/Adlm/Maya2014/MayaConfig.pit"
}

post_uninstall() {
/usr/bin/gtk-update-icon-cache
}
