post_install() {
	echo -n "Updating font cache... "
	mkfontscale /usr/share/fonts/wenquanyi/wqy-unibit
	mkfontdir /usr/share/fonts/wenquanyi/wqy-unibit
	fc-cache -f /usr/share/fonts/wenquanyi/wqy-unibit > /dev/null
	echo "done."
}

post_upgrade() {
	post_install $1
}

post_remove() {
	rm -r /usr/share/fonts/wenquanyi/wqy-unibit
	rmdir --ignore-fail-on-non-empty /usr/share/fonts/wenquanyi/
}

op=$1
shift

$op $*
