
post_install() {
  echo  ">> *** DBXML PACKAGE ***"
  echo  ">> This package provides Berkeley DB XML, a customized version of XQilla" 
  echo  ">> (an XQuery library) as well as Perl and Java bindings to the C++ API. " 
  echo  ">>  For full documentation see "
  echo  ">>    http://www.oracle.com/technology/documentation/berkeley-db/xml/index.html."
  echo  ">> API wrappers for Python, PHP and Tcl are included in the sources but are"
  echo  ">> not provided with this package."
}
