# arg 1: the new package version
post_install() {

  echo "==> Creating nullmail user"
  getent group nullmail > /dev/null || groupadd nullmail
  getent passwd nullmail > /dev/null || useradd -c "Nullmail mail server" -g nullmail -s /bin/false -d /dev/null nullmail
  
  echo "==> Fixing permissions"

  chown nullmail /var/nullmailer/*
  chown nullmail /usr/sbin/nullmailer-queue
  chmod u+s /usr/sbin/nullmailer-queue
  chown nullmail /usr/bin/mailq
  chmod u+s /usr/bin/mailq

  echo "==> Configuring"
  [ -s /etc/nullmailer/me ] || /bin/hostname > /etc/nullmailer/me

  [ -s /etc/nullmailer/remotes  ] || \
  echo -e "\n\n#Type your mail relay hosts at the top, one per line" > \
  /etc/nullmailer/remotes

}

pre_remove() {

  echo "==> Stopping nullmailer"
  sv stop nullmailer >& /dev/null
  rm -f /var/service/nullmailer
  echo "==> Removing nullmailer user and group"
  usr/sbin/userdel nullmail >& /dev/null
  usr/sbin/groupdel nullmail >& /dev/null
  
}

op=$1
shift

$op $*
