--- Makefile.orig	2012-01-16 12:42:33.805304498 +0100
+++ Makefile	2012-01-16 12:42:44.325374189 +0100
@@ -30,7 +30,7 @@
 
 ### Make sure that necessary options are included:
 
-include $(VDRDIR)/Make.global
+# include $(VDRDIR)/Make.global
 
 ### Allow user defined options to overwrite defaults:
 
