#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions
. /etc/conf.d/ipwatchd

PID=$(pidof -o %PPID /usr/sbin/ipwatchd)
case "$1" in
  start)
    stat_busy "Starting ipwatchd"
    [ -z "$PID" ] && /usr/sbin/ipwatchd $IPWATCHD_ARGS
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon ipwatchd
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping ipwatchd"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon ipwatchd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
exit 0
