--- Makefile.orig	2011-10-26 01:59:08.000000000 +0200
+++ Makefile	2011-11-02 22:26:41.034088255 +0100
@@ -137,6 +137,7 @@
 	cp -rf python/r_*.py python/*.$$E ${PYTHON_INSTALL_DIR} ; \
 	fi
 
+ifeq ($(DEVEL_MODE),1)
 install-lua:
 	@if [ "`grep lua supported.langs`" ]; then \
 	for a in 5.1 ; do \
@@ -185,6 +186,7 @@
 	cp -rf perl/*.so $$target/r2 ; \
 	cp -rf perl/*.pm $$target/r2 ; \
 	fi
+endif
 
 install-vapi:
 	@${INSTALL_DIR} ${DESTDIR}${PREFIX}/share/vala/vapi
@@ -201,7 +203,11 @@
 		cp -rf python/test-*.py ${EXAMPLEDIR}/python ; \
 	fi
 
+ifeq ($(DEVEL_MODE),1)
 install: install-python install-ruby install-perl install-lua install-go install-java install-vapi install-examples
+else
+install: install-python  install-vapi install-examples
+endif
 
 deinstall: uninstall
 uninstall:
