# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Thomas Gubler <thomasgubler@gmail.com>

_gemname=timetrap
pkgname=ruby-$_gemname
pkgver=1.8.14
pkgrel=1
pkgdesc='Command line time tracker'
arch=(any)
url='https://github.com/samg/timetrap'
license=(MIT)
depends=(ruby ruby-sequel-4.0 ruby-sqlite3 ruby-chronic)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('5390a246ed6b8681ae2d8e51ab03933e86527572')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE.txt" "$pkgdir/usr/share/licenses/$pkgname/LICENSE.txt"
}
