post_install() {
    echo "[Desktop Entry]
Version=1.0
Name=Radical Comic Designer
Comment=Visual Software Creation
Exec=/opt/RadicalComicDesigner/RadicalComicDesigner
Icon=/opt/RadicalComicDesigner/RCDIcon256.png
Terminal=false
Type=Application
Categories=Graphics;
Name[en_US]=Radical Comic Designer " > /usr/share/applications/RadicalComicDesigner.desktop
    
    echo "Updating desktop MIME database..."
    update-desktop-database -q
    if [ ! -e /opt/RadicalComicDesigner/RadicalComicDesigner ]; then ln -s /opt/RadicalComicDesigner/RadicalComicDesigner /usr/bin/RadicalComicDesigner; fi 
    
}

post_upgrade() {
    post_install $1
}

post_remove() {
    post_install $1
    if [ -e /usr/bin/RadicalComicDesigner ]; then rm  /usr/bin/RadicalComicDesigner; fi
    if [ -e /usr/share/applications/RadicalComicDesigner.desktop ]; then rm /usr/share/applications/RadicalComicDesigner.desktop; fi
}
