pre_install() {
    if [ -e /usr/share/applications/RadicalComicDesigner.desktop ]; then rm /usr/share/applications/RadicalComicDesigner.desktop; fi
}

post_install() {
    update-desktop-database -q
    if [ ! -e /opt/RadicalComicDesigner/RadicalComicDesigner ]; then ln -s /opt/RadicalComicDesigner/RadicalComicDesigner /usr/bin/RadicalComicDesigner; fi
}

pre_upgrade() {
    pre_install
}

post_upgrade() {
    post_install
}

post_remove() {
    post_install
    if [ -e /usr/bin/RadicalComicDesigner ]; then rm /usr/bin/RadicalComicDesigner; fi
    if [ -e /usr/share/applications/RadicalComicDesigner.desktop ]; then rm /usr/share/applications/RadicalComicDesigner.desktop; fi
}
