.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2013 Bruno Nova <brunomb.nova@gmail.com>,
.\"
.TH DRMIPS 1 "29 de Setembro de 2013"
.SH NOME
drmips \- simulador educativo do MIPS
.SH SINOPSE
.B drmips
.RI [ OPÇÕES ]
.RI [ FICHEIRO ]
.br
.SH DESCRIÇÃO
.B DrMIPS 
é um simulador gráfico do processador MIPS para apoiar o ensino e a 
aprendizagem de arquitectura de computadores. É intuitivo, versátil e
configurável.
O simulador está disponível não só para computadores pessoais mas também para
dispositivos Android, especialmente tablets.
.PP
Este comando inicia a versão para PC do simulador. Pode passar um
.IR FICHEIRO
como argumento para o abrir no simulador.
.SH OPÇÕES
.TP
.B \-h, \-\-help
mostrar a ajuda e sair.
.TP
.B \-\-version
mostrar informação da versão e sair.
.TP
.B FICHEIRO
ficheiro opcional a abrir.
.SH VEJA TAMBÉM
A documentação do simulador em:
.IR /usr/share/doc/drmips/doc/
.PP
A página do simulador em:
.IR https://bitbucket.org/brunonova/drmips
