.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2013 Bruno Nova <brunomb.nova@gmail.com>,
.\"
.TH DRMIPS 1 "September 29, 2013"
.SH NAME
drmips \- educational MIPS simulator
.SH SYNOPSIS
.B drmips
.RI [ OPTIONS ]
.RI [ FILE ]
.br
.SH DESCRIPTION
.B DrMIPS 
is graphical simulator of the MIPS processor to support computer architecture
teaching and learning. It is intuitive, versatile and configurable.
The simulator is available not only for personal computers but also for
Android devices, especially tablets.
.PP
This command starts the PC version of the simulator. You can pass a
.IR FILE 
as argument to open it in the simulator.
.SH OPTIONS
.TP
.B \-h, \-\-help
display help and exit.
.TP
.B \-\-version
display version information and exit.
.TP
.B FILE
optional file to open.
.SH SEE ALSO
The documentation of the simulator at:
.IR /usr/share/doc/drmips/doc/
.PP
The page of the simulator at:
.IR https://bitbucket.org/brunonova/drmips
