# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Alireza Savand <alireza.savand@gmail.com>

_gemname=grape
pkgname=ruby-$_gemname
pkgver=0.7.0
pkgrel=1
pkgdesc='A simple Ruby framework for building REST-like APIs.'
arch=(any)
url='https://github.com/intridea/grape'
license=(MIT)
depends=(ruby ruby-rack ruby-rack-mount ruby-rack-accept ruby-activesupport ruby-multi_json ruby-multi_xml ruby-hashie ruby-virtus ruby-builder)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('7e162310eb3a3a695fcfd865bf21d75a64a3ff37')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
