#!/bin/sh

. /etc/cjdnsify.conf

CJDNSADDRESS=$(ifconfig | grep -A 1 $CJDNSTUN | grep inet6 | sed "s/\ *inet6\ //g ; s/\ .*//")

if [ $(echo "$CJDNSADDRESS" | wc -m) -gt 1 ]; then
  FORCE_BIND_ADDRESS_V4="127.0.0.1" FORCE_BIND_ADDRESS_V6="$CJDNSADDRESS" LD_PRELOAD="$BINDLIB" "$@"
else
  echo "cjdns not running"
fi
