post_install() {
/bin/true
/bin/cat << EOF
===>
===> To generate a new configuration file for boost-build
===> do "/etc/rc.d/boost-build-config -s"
===> 
===> do "/etc/rc.d/boost-build-config --help" for more information
===>
===> Documentation can be found in /usr/share/doc/boost
===>
EOF
/etc/rc.d/boost-build-config -s
/bin/true
}

post_upgrade() {
/bin/true
}

post_remove() {
/bin/true
}

op=$1
shift

$op "$@"
