post_install() {

  update-desktop-database -q
  printf "\n"
  printf "==> For installing some sample presets in ~/.miniComputer, use\n"
  printf "==> /usr/share/minicomputer/installpresets.sh .\n"
  printf "==> Use "minicomputer" to start the engine and the GUI.\n"
  printf "==> Documentation can be found under /usr/share/doc/minicomputer/ .\n"
  printf "\n"
}

post_remove() {

  update-desktop-database -q
}

op=$1
shift
$op $*
# vim:set ts=2 sw=2 et:
