post_install () {
	if ! grep -q "^_smtpd:" /etc/passwd; then
		useradd -c "SMTP Daemon" -d /var/empty -s /sbin/nologin _smtpd
	fi
	if ! grep -q "^_smtpq:" /etc/passwd; then
		useradd -c "SMTP queue user" -d /var/empty -s /sbin/nologin _smtpq
	fi
	if ! grep -q "^_smtpf:" /etc/passwd; then
		useradd -c "SMTP filter user" -d /var/empty -s /sbin/nologin _smtpf
	fi
}

post_remove () {
	echo "Consider removing the OpenSMTPD users '_smtpd', '_smtpq', and '_smtpf'"
}

post_upgrade () {
	post_install
}
