--- Makefile.old	2013-01-28 23:46:44.244983307 +0100
+++ Makefile	2013-01-28 23:47:20.641218888 +0100
@@ -1,7 +1,7 @@
 # start of Imakefile
 
 CC		= gcc
-CFLAGS		=  -g -O3 -I../gopher -I../gopher/object -I../libvogl/src -I/usr/OpenMotif/include -force_cpusubtype_ALL -mmacosx-version-min=10.4 -arch i386 -arch ppc -isysroot /Developer/SDKs/MacOSX10.4u.sdk
+CFLAGS		=  -g -O3 -I../gopher -I../gopher/object -I../libvogl/src -I/usr/OpenMotif/include
 LDOPTIONS	=
 LDLIBS		= -L/usr/OpenMotif/lib -L/usr/X11R6/lib
 EXTRA_LOAD_FLAGS=
