# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: kusakata <shohei atmark kusakata period com>

_gemname=webmock
pkgname=ruby-$_gemname
pkgver=1.17.4
pkgrel=1
pkgdesc='Library for stubbing HTTP requests in Ruby.'
arch=(any)
url='http://github.com/bblimke/webmock'
license=(MIT)
depends=(ruby ruby-addressable ruby-crack)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('70ea27897b98a351ce4e2dd6569ae2ce09aa0837')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
