
post_install() {
  update-desktop-database -q
  echo "******"
  echo "*"
  echo "* To add wmal-curses to your applications comment out or remove 'NoDisplay=true' from wmal-curses.desktop"
  echo "*" 
  echo "* wMAL has been renamed, packages are being merged; but until then the new package can be found here: https://aur.archlinux.org/packages/trackma-git/" 
  echo "*" 
  echo "******"
}

post_upgrade() {
  post_install
}

post_remove() {
  update-desktop-database -q 
}
