--- msitools-0.91/Makefile.am	2013-01-25 15:11:51.000000000 +0100
+++ ../src/msitools-0.91/Makefile.am	2013-02-05 19:22:28.263204288 +0100
@@ -112,9 +112,9 @@
 	$(NULL)
 
 wixl_LDADD =					\
-	$(WIXL_LIBS)				\
 	libmsi/libmsi.la			\
-	libcommon.a				\
+	libcommon.a				    \
+	$(WIXL_LIBS)				\
 	$(NULL)
 
 wixl_DEPENDENCIES = libmsi/libmsi.la
