post_install() {
    cp usr/share/FFXIIIManager/weaponsDB.csv usr/share/FFXIIIManager/weaponsDB-ENG.csv
    cp usr/share/FFXIIIManager/accessoriesDB.csv usr/share/FFXIIIManager/accessoriesDB-ENG.csv
    cp -f usr/share/FFXIIIManager/weaponsDB-ITA.csv usr/share/FFXIIIManager/weaponsDB.csv
    cp -f usr/share/FFXIIIManager/accessoriesDB-ITA.csv usr/share/FFXIIIManager/accessoriesDB.csv
}

pre_remove() {
    cp -f usr/share/FFXIIIManager/weaponsDB-ENG.csv usr/share/FFXIIIManager/weaponsDB.csv
    cp -f usr/share/FFXIIIManager/accessoriesDB-ENG.csv usr/share/FFXIIIManager/accessoriesDB.csv
    rm usr/share/FFXIIIManager/weaponsDB-ENG.csv usr/share/FFXIIIManager/accessoriesDB-ENG.csv
}
