post_install() {
    mv "/usr/share/FFXIIIManager/weaponsDB.csv" "/usr/share/FFXIIIManager/weaponsDB-ENG.csv"
    mv "/usr/share/FFXIIIManager/accessoriesDB.csv" "/usr/share/FFXIIIManager/accessoriesDB-ENG.csv"
    mv "/usr/share/FFXIIIManager/weaponsDB-ITA.csv" "/usr/share/FFXIIIManager/weaponsDB.csv"
    mv "/usr/share/FFXIIIManager/accessoriesDB-ITA.csv" "/usr/share/FFXIIIManager/accessoriesDB.csv"
}

pre_remove() {
    mv "/usr/share/FFXIIIManager/weaponsDB-ENG.csv" "/usr/share/FFXIIIManager/weaponsDB.csv"
    mv "/usr/share/FFXIIIManager/accessoriesDB-ENG.csv" "/usr/share/FFXIIIManager/accessoriesDB.csv"
}