post_install() {
    EXTRAMODULES='3.6.0-rc3-mainline/extramodules'
    depmod $(cat /lib/modules/$EXTRAMODULES/version)
    echo 'In order to use nvidia module, reboot the system.'
}

post_upgrade() {
    EXTRAMODULES='3.6.0-rc3-mainline/extramodules'
    depmod $(cat /lib/modules/$EXTRAMODULES/version)
}

post_remove() {
    EXTRAMODULES='3.6.0-rc3-mainline/extramodules'
    depmod $(cat /lib/modules/$EXTRAMODULES/version)
}
