# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Alireza Savand <alireza.savand@gmail.com>

_gemname=rack-accept
pkgname=ruby-$_gemname
pkgver=0.4.5
pkgrel=1
pkgdesc='HTTP Accept* for Ruby/Rack'
arch=(any)
url='http://mjijackson.github.com/rack-accept'
license=()
depends=(ruby ruby-rack)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('810233d94127639d4bf9d628ac6203d1d3d81aca')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
