post_install() {
  echo -e "\n MANUAL INTERVENTION REQUIRED \n You may need to add some scripts to /etc/ppp/chatscripts/ to connect, see the files in that directory and https://wiki.archlinux.org/index.php/3G_and_GPRS_modems_with_pppd for more details. \n Remember to relink the symbolic links to point to the correct scripts."
}

post_upgrade() {
  echo -e "\n MANUAL INTERVENTION REQUIRED \n You may need to add some scripts to /etc/ppp/chatscripts/ to connect, see the files in that directory and https://wiki.archlinux.org/index.php/3G_and_GPRS_modems_with_pppd for more details. \n Remember to relink the symbolic links to point to the correct scripts."
}

# vim:set ts=2 sw=2 et:
