 
post_install() {
  cat << EOF
==> This game uses a server and client set up.
==> If the menu entry does not open your web browser you can
==> either:
==> 1) Start the  server with "bubnbros" from the command line 
==>    and point your browser of choice at the url given.
==> 2) Define the environment variable BROWSER in the file
==>    /etc/profile to point at you browser of choice.
EOF
}

post_upgrade() {
  post_install $1
}

op=$1
shift
$op $*
