#!/bin/bash

declare $dir=~/.terasology
declare download="http://www.movingblocks.net:8080/job/TerasologyStable/lastSuccessfulBuild/artifact/target/TerasologyStable.zip"

if [ ! -e $dir ]; then
	mkdir ~/.terasology
	cd ~/.terasology
	wget $download
	unzip TerasologyStable.zip

else
	cd ~/.terasology
	rm $build
	wget $download
	unzip TerasologyStable.zip
fi
	
