#!/bin/bash

declare dir=~/.terasology
declare download="http://www.movingblocks.net:8080/job/TerasologyStable/lastSuccessfulBuild/artifact/build/distributions/Terasology.zip"

if [ ! -e $dir ]; then
	mkdir ~/.terasology
	cd ~/.terasology
	wget $download
	unzip Terasology.zip

else
	cd ~/.terasology
	rm Terasology.zip
	wget $download
	unzip Terasology.zip
fi
	
