post_install() {
	# Correcting mess caused by previous install
	for i in "annotateBed" "bamToBed" "bed12ToBed6" "bedpeToBam" "bedToBam" "bedToIgv" "bedtools" "closestBed" "clusterBed" "complementBed" "coverageBed" "fastaFromBed" "flankBed" "genomeCoverageBed" "getOverlap" "groupBy" "intersectBed" "linksBed" "maskFastaFromBed" "mergeBed" "multiBamCov" "multiIntersectBed" "nucBed" "pairToBed" "pairToPair" "shuffleBed" "slopBed" "sortBed" "subtractBed" "tagBam" "unionBedGraphs" "windowBed" "windowMaker"
	do
		if [ -h /usr/local/bin/$i ];then
			rm -f /usr/local/bin/$i
		fi
	done
}

post_upgrade() {
	post_install $1
}

