post_install() {

  if [ -d /opt/bedtools/ ];then
	  for i in /opt/bedtools/*
	  do
			  ln -sf $i /usr/local/bin
	  done
  else
	  echo "Seems that you changed the default directory, you should create symbolic links to /usr/local/bin/ manually"
  fi

}

post_upgrade() {
  post_install $1
}

pre_remove() {

  if [ -d /opt/bedtools/ ];then
	  cd /opt/bedtools/
	  for i in *
	  do
			  rm -f /usr/local/bin/$i
	  done
  else

	  echo "Seems that you changed the default directory, you should clean your symbolic links manually"

  fi

}
