post_install() {
    red='\033[1;31m'
    grn='\033[1;32m'
    ylw='\033[1;33m'
    stp='\033[0m'

    echo " ";  
    echo -e "$red==>$bld Now mannually do $grn'lmd -reconf && sudo cp -r -f /usr/share/lmd/langs/ ~/.LMD/lang' $stp";
    echo " ";
    echo -e "$ylw==>In some Websites, when downloading, the program says there was an error with the last page of the chapter, don't worry, coding mistake, that page was downloaded successfully$stp";
}