#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PIDFILE="/var/run/actkbd.pid"
case "$1" in
  start)
    stat_busy "Starting keyboard shortcut daemon"
    [ ! -f $PIDFILE ] && /usr/sbin/actkbd -D -q -p $PIDFILE 
    if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon actkbd
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping keyboard shortcut daemon"
    [ -f $PIDFILE ] && kill `cat $PIDFILE`
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon actkbd
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
