post_install() {
  echo "Please copy the files from your installation of Jazz Jackrabbit 1 to /usr/share/openjazz/data, then run '/usr/share/openjazz/OpenJazz /usr/share/openjazz/data/' to start the game. Watch the output because OpenJazz may expect certain files to be all uppercase. The best solution is to have an upper and lowercase version of all the game data files in the data directory."
}

pre_remove() {
  rm -rf /usr/share/openjazz/data
}

op=$1
shift
$op $*

