# Generated by gem2arch
# Maintainer: LeeF

_gemname=mysql
pkgname=ruby-enterprise-$_gemname
pkgver=2.8.1
pkgrel=1
pkgdesc="This is the MySQL API module for Ruby"
arch=('i686' 'x86_64')
url="http://mysql-win.rubyforge.org"
license=('Unspecified')
depends=('ruby-enterprise' 'libmysqlclient')
makedepends=('ruby-enterprise')
source=(http://gems.rubyforge.org/gems/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
md5sums=('81f2b50b1135e53a526e07bb21e16a4e')

build() {
  cd $srcdir
  local _gemdir=`ruby -rubygems -e'puts Gem.default_dir'`
  gem install --ignore-dependencies --no-rdoc --no-ri -i "$pkgdir$_gemdir" $_gemname-$pkgver.gem
}
