.TH EXTEMP 7
.SH NAME
extemp \- extemp filing/searching program 
.SH SYNOPSIS
.ll +8
.B extemp
.RB [ " option " ]
.RB [ " newspaper " ]
[
.I " searchphrases \&..."
]
.ll -8
.SH DESCRIPTION
.I Extemp 
is a program designed for use in extemporaneous speaking competitions.
It performs a variety of functions, the most important of which is
non-interactively downloading newspaper articles into a searchable database.
It also is able to keep the database up to date by automatically deleting
articles over a certain amount of days old.

.SH OPTIONS
.TP
.B clean
Removes downloaded articles over a certain amount of days old. Right now
the number of days is hardcoded at 21.
.TP
.B delete
Removes all of the articles from the database from the specified paper.
.TP
.B remove
Removes the article matching the specific id given. For instance  
.B extemp remove 21
will remove article number 21 from the database. You can figure out
what an article's id number is by looking at what it is called when
opened in firefox. All articles when written for displaying in firefox
have the papername followed by the number (i.e. foxnews-21).
.TP
.B search
Searches the database for the search phrase(s) specified and then opens
articles matching the search in firefox (see 
.B USAGE EXAMPLES 
below). It searches
the phrases in a case insensitive manner 
one by one and will only display articles that matched all of
the phrases provided. When cycling through the search phrases, it will notify
you at what point the search phrases cease to have articles matching them.
.TP
.B status
A somewhat trivial command, this provides a nicely formatted message
concerning the status of the datbase. It will display how many articles
the newspaper has in the database.
.TP
.B title
Searches only the titles of the articles in the database for matches.
.TP
.B sync
Downloads a database snapshot if one exists. A snapshot is a tarball of
the articles database uploaded to an ftp account. It is useful for new users
to have a database available immediately, or those who cannot update
everyday. There is no guarantee the snapshots will be there.
.TP
.B update
Updates the database by downloading any new articles from the newspaper
specified.
.TP
.B vacuum
Performs an sql vacuum on the database. It is good to use this after removing
things from the database with clean, delete, or remove.

.SH "NEWSPAPERS"
.TP
.B all
Specifying all for the newspaper argument will apply the option to all
of the available newspapers and is the newspaper option that will be
used the most often.
.TP
.B Specific Papers
To get a full list of specific papers, simply execute "extemp" with no
arguments and they should be listed at the bottom.

.SH "USAGE EXAMPLES"
To apply an option to all of the newspapers, just use the syntax below. In
this example, the option is 
.B update 
but you can replace that with any
of the available options:

.B "      extemp update all"

For a specific paper (bbc for instance):

.B "      extemp update bbc"

For searching, you must provide the 
.B search
option followed by the paper like all of the other options. But, you must
also specify what phrases to search for. You can chain the search phrases one
after the other and the program will scan through the database in the order
provided progressively narrowing the article matches in accordance with
the phrases given. The same is true of the 
.B title
command. Here is an example searching through 
.B all
of the database for 
.B barack obama
and
.B articulated policies
.

.B "      extemp search all 'barack obama' 'articulated policies'"

Although this search will obviously turn up nothing, most searches will.

.SH "AUTHOR"
Matthew Bruenig <matthewbruenig@gmail.com>
