#!/bin/bash

filename=$(basename "$1")
path="${1%$filename}"

new_filename_form=`yad --form \
--title="$filename" \
--separator="," \
--field="Original path/filename:" \
--field="New Path:" \
--field="New Filename:" \
"$1" "$path" "$filename"`

new_path="$(awk -F, '{print $2}' <<<"$new_filename_form")"
if [ "$new_path" ] ; then
  i=$((${#new_path}-1))
  if [ "${new_path:$i:1}" != "/" ]; then
    new_path="$new_path""/"
  fi 
  
  new_filename="$(awk -F, '{print $3}' <<<"$new_filename_form")"
  
  mv_to="$new_path$new_filename"
  
  if [ "$mv_to" ] && [ "$mv_to" != "$1" ]; then
    mv_error=`mv "$1" "$mv_to" 2>&1`
    if [ "$mv_error" ]; then 
      yad --error --text="$mv_error"
    fi
  fi
fi
