# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>
# Contributor: Simon Lipp <sloonz+aur@gmail.com
# Contributor: Alexsandr Pavlov <kidoz at mail dot ru>

_gemname=uuidtools
pkgname=ruby-$_gemname
pkgver=2.1.5
pkgrel=1
pkgdesc='A simple universally unique ID generation library'
arch=(any)
url='http://uuidtools.rubyforge.org/'
license=(MIT)
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('c66138adb04e0c082bfe43c45df7f097be7a5b95')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE.txt" "$pkgdir/usr/share/licenses/$pkgname/LICENSE.txt"
}
