#!/bin/bash

# arg 1:  the old package version
pre_remove() {
	:
}

# arg 1:  the old package version
post_remove() {
	[[ -d lib/fbsplash-controld ]] || return 0
	local output error=0
	output=$( mv -v -T lib/fbsplash-controld usr/lib/fbsplash-controld 2>&1 ) || error=1
	cat <<-EOT
		-------------------------------------------------------------------------------
		> Moving cache directory to new location
		> ${output}
		-------------------------------------------------------------------------------
	EOT
	return $error
}

# arg 1:  the new package version
pre_install() {
	:
}

# arg 1:  the new package version
post_install() {
	cat <<-EOT
		-------------------------------------------------------------------------------
		> If starting X from DAEMONS, set SPLASH_XSERVICE in /etc/conf.d/splash !
		> Additional configuration: /etc/conf.d/splash-extras
		> If SPLASH_DAEMON="early" in /etc/conf.d/splash, update your initcpio !
		> *WARNING* - Setting a console font on the kernel command line or in
		> /etc/rc.conf or /etc/vconsole.conf might break the splash screen !
		-------------------------------------------------------------------------------
	EOT
	post_remove
}

# arg 1:  the new package version
# arg 2:  the old package version
pre_upgrade() {
	:
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
	if (( $( vercmp "$2" 3.0 ) < 0 )); then
		post_install "$1"
	else
		post_remove "$2"
	fi
}

# EOF
