#!/bin/bash

# arg 1:  the new package version
pre_install() {
	:
}

# arg 1:  the new package version
post_install() {
	cat <<EOT
-------------------------------------------------------------------------------
> If starting X from DAEMONS, set SPLASH_XSERVICE in /etc/conf.d/splash !
> Additional configuration: /etc/conf.d/splash-extras
> If SPLASH_DAEMON="early" in /etc/conf.d/splash, update your initcpio !
> *WARNING* - Setting a console font on the kernel command line or in
> /etc/rc.conf or /etc/vconsole.conf might break the splash screen !
-------------------------------------------------------------------------------
EOT
}

# arg 1:  the new package version
# arg 2:  the old package version
pre_upgrade() {
	:
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
	(( $( vercmp "$2" 3.0 ) >= 0 )) || post_install "$1"
}

# arg 1:  the old package version
pre_remove() {
	:
}

# arg 1:  the old package version
post_remove() {
	:
}

# EOF
