post_install() {
  echo "Running iscan-registry to register plugins and firmware with iscan"
    iscan-registry --add interpreter usb 0x04b8 0x014a /usr/lib/iscan/libiscan-plugin-perfection-v370 /usr/share/iscan/esfwdd.bin
}

pre_remove() {
  echo "Unregistering perfection-v370 plugins/firmware"
    iscan-registry --remove interpreter usb 0x04b8 0x014a /usr/lib/iscan/libiscan-plugin-perfection-v370 /usr/share/iscan/esfwdd.bin
}

