# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Jean-Noël Rouchon <jnoel@sissiou.net>

_gemname=r18n-desktop
pkgname=ruby-$_gemname
pkgver=1.1.10
pkgrel=1
pkgdesc='A i18n tool to translate your Ruby desktop application.'
arch=(any)
url='https://github.com/ai/r18n/tree/master/r18n-desktop'
license=(LGPL-3)
depends=(ruby ruby-r18n-core)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('2f561021c0a8709f006193598adc9342552c64b5')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
