Index: Makefile
===================================================================
--- Makefile	(revision 1)
+++ Makefile	(revision 2)
@@ -49,6 +49,9 @@
 #
 arch             = UNKNOWN
 #
+topdir		 = $(CURDIR)
+#
+#
 ## Targets #############################################################
 #
 all              : install
@@ -58,33 +61,33 @@
 install          : startup refresh build
 #
 startup          :
-	$(MAKE) -f Make.top startup_dir     arch=$(arch)
-	$(MAKE) -f Make.top startup_src     arch=$(arch)
-	$(MAKE) -f Make.top startup_tst     arch=$(arch)
-	$(MAKE) -f Make.top refresh_src     arch=$(arch)
-	$(MAKE) -f Make.top refresh_tst     arch=$(arch)
+	$(MAKE) -f Make.top startup_dir     arch=$(arch) topdir=$(topdir)
+	$(MAKE) -f Make.top startup_src     arch=$(arch) topdir=$(topdir)
+	$(MAKE) -f Make.top startup_tst     arch=$(arch) topdir=$(topdir)
+	$(MAKE) -f Make.top refresh_src     arch=$(arch) topdir=$(topdir)
+	$(MAKE) -f Make.top refresh_tst     arch=$(arch) topdir=$(topdir)
 #
 refresh          :
-	$(MAKE) -f Make.top refresh_src     arch=$(arch)
-	$(MAKE) -f Make.top refresh_tst     arch=$(arch)
+	$(MAKE) -f Make.top refresh_src     arch=$(arch) topdir=$(topdir)
+	$(MAKE) -f Make.top refresh_tst     arch=$(arch) topdir=$(topdir)
 #
 build            :
-	$(MAKE) -f Make.top build_src       arch=$(arch)
-	$(MAKE) -f Make.top build_tst       arch=$(arch)
+	$(MAKE) -f Make.top build_src       arch=$(arch) topdir=$(topdir)
+	$(MAKE) -f Make.top build_tst       arch=$(arch) topdir=$(topdir)
 #
 clean            :
-	$(MAKE) -f Make.top clean_src       arch=$(arch)
-	$(MAKE) -f Make.top clean_tst       arch=$(arch)
+	$(MAKE) -f Make.top clean_src       arch=$(arch) topdir=$(topdir)
+	$(MAKE) -f Make.top clean_tst       arch=$(arch) topdir=$(topdir)
 #
 clean_arch       :
-	$(MAKE) -f Make.top clean_arch_src  arch=$(arch)
-	$(MAKE) -f Make.top clean_arch_tst  arch=$(arch)
+	$(MAKE) -f Make.top clean_arch_src  arch=$(arch) topdir=$(topdir)
+	$(MAKE) -f Make.top clean_arch_tst  arch=$(arch) topdir=$(topdir)
 #
 clean_arch_all   :
-	$(MAKE) -f Make.top clean_arch_all  arch=$(arch)
+	$(MAKE) -f Make.top clean_arch_all  arch=$(arch) topdir=$(topdir)
 #
 clean_guard      :
-	$(MAKE) -f Make.top clean_guard_src arch=$(arch)
-	$(MAKE) -f Make.top clean_guard_tst arch=$(arch)
+	$(MAKE) -f Make.top clean_guard_src arch=$(arch) topdir=$(topdir)
+	$(MAKE) -f Make.top clean_guard_tst arch=$(arch) topdir=$(topdir)
 #
 # ######################################################################
