post_upgrade() {
	echo '!!! Another change, now you must run an appropriate bind -x command that runs the script.'
	echo '!!! Example with optional "nohelp" argument'
	echo '!!! bind -x '\''"\t":out=$(kingbash.script "$PS1" "$(compgen -A alias -A function)" nohelp); READLINE_LINE=$(echo "$out" | head -n -1); READLINE_POINT=$(echo "$out" | tail -n 1)'\'
	echo '!!! kbdmenu is added to replace the ability of the python script to perform as a console dmenu.'
}
