pre_install() {
   #Install Ruby Nokogiri module (XML parsing)
   a=`gem list nokogiri | grep nokogiri | wc -l`

   if [ $a -eq "0" ]; then
      gem install nokogiri
   fi;
}

pre_upgrade() {
   #Install Ruby Nokogiri module (XML parsing)
   a=`gem list nokogiri | grep nokogiri | wc -l`

   if [ $a -eq "0" ]; then
      gem install nokogiri
   fi;
}

post_remove() {
   echo "Don't forget that downloaded videos still are in ~/.cpvod"
}
