post_install(){
  mv /etc/zsh/zshrc /etc/zsh/zshrc.$(date +"%F%T").pre-oh-my-zsh
  cp /usr/share/oh-my-zsh/templates/zshrc.arch-zsh-template /etc/zsh/zshrc
  chmod +x /etc/zsh/zshrc
  echo "==> NOTE: For any user to get oh-my-zsh to run, they must run load_oh_my_zsh manually or append the command to their .zshrc."
}

post_remove(){
  mv $(ls -c /etc/zsh/zshrc.*.pre-oh-my-zsh|head -1) /etc/zsh/zshrc
}

# vim:set ts=2 sw=2 et:
