PKGVER="$(ls /usr/src/ | grep hid-atari-retrobit | sed 's/^.*-//')"
_dkms="/usr/bin/dkms"


post_install() {
  ${_dkms} add -m "hid-atari-retrobit/${PKGVER}"
  ${_dkms} build -m "hid-atari-retrobit/${PKGVER}"
  ${_dkms} install -m "hid-atari-retrobit/${PKGVER}"
}

post_upgrade() {
  post_install
}

pre_remove() {
  ${_dkms} remove -m "hid-atari-retrobit/${PKGVER}" --all
}

pre_upgrade() {
  pre_remove
}

post_remove() {
  depmod -a
}
