post_install() {
  echo "******"
  echo "*"
  echo "* Documentation can be found at:"
  echo "* https://ripple.com/wiki/Ripple_Client"
  echo "*"
  echo "* Next steps:"
  echo "* 1. Customize /opt/ripple-client/config.js as needed"
  echo "* 2. Change which browser the ripple-client executable opens by"
  echo "*    default by modifying /usr/bin/ripple-client (optional)"
  echo "*"
  echo "******"
}
