.TH BUSTLE-DBUS-MONITOR 1 "January 8, 2009"
.SH NAME
bustle-dbus-monitor \- Generates D-Bus dump for Bustle D-Bus visualiser
.SH SYNOPSIS
.B bustle-dbus-monitor
.RI [\-\-system
.RI |
.RI \-\-session]
.RI [<watch-expressions>]
.RI > logfile
.SH DESCRIPTION
The \fBbustle-dbus-monitor\fP utility generates \fBdbus-monitor\fP-like dumps
of D-Bus traffic for use by the Bustle D-Bus visualiser.
.SH AUTHOR
\fBbustle-dbus-monitor\fP was written by Will Thompson
<will.thompson@collabora.co.uk> based on work by Philip Blundell
<philb@gnu.org>.
.PP
This manual page was written by Chris Lamb <lamby@debian.org> for the Debian
project (but may be used by others).
