.TH BUSTLE-TIME 1 "April 5, 2009"
.SH NAME
bustle-time \- Post-processing tool for Bustle D-Bus logs
.SH SYNOPSIS
.B bustle-time
.RI logfile
.SH DESCRIPTION
\fBbustle-time\fP is a tool to time D-Bus calls for profiling and debugging.
It is intended to complement the rest of the Bustle suite.
.PP
You should generate a dump using \fBbustle-dbus-monitor\fP (N.B. not 
\fBdbus-monitor\fP) and pass its filename as an argument to this command.
.SH AUTHOR
\fBbustle-dot\fP was written by Dafydd Harries <dafydd.harries@collabora.co.uk>
and and Will Thompson <will.thompson@collabora.co.uk>.
.PP
This manual page was written by Chris Lamb <lamby@debian.org> for the Debian
project (but may be used by others).
