.TH BUSTLE-DBUS-MONITOR 1 "January 8, 2009"
.SH NAME
bustle \- D-Bus visualiser
.SH SYNOPSIS
.B bustle
.RI logfile
.SH DESCRIPTION
Bustle is a tool to chart and provide timing information of D-Bus calls for
profiling and debugging. It is intended to replace reading the cryptic output
of \fBdbus-monitor\fP. Calls are displayed using Message Sequence Charts, a
succinct way of representing entities and interactions over time.
.PP
You should generate a dump using \fBbustle-dbus-monitor\fP (N.B. not 
\fBdbus-monitor\fP) and pass its filename as an argument to this command.
.SH AUTHOR
\fBbustle\fP was written by Will Thompson <will.thompson@collabora.co.uk>.
.PP
This manual page was written by Chris Lamb <lamby@debian.org> for the Debian
project (but may be used by others).
