post_install() {
  cat << EOF
> Unfortunately some printer options can't be configured via CUPS.
> These options, like e.g. Papersize, can only be configured via the
> underlying LPR driver.

> The config file for the Brother MFC-260C LPR driver is located at:
> /usr/share/brother/printer/mfc260c/inf/brmfc260crc
> You need to be in the "lp" group to edit this file.

> Please look at the 'brother-mfc260c-lpr' install message for more details.
EOF
}

op=$1
shift
$op $*
