post_install() {
  if ! getent group opensand >/dev/null; then
    groupadd --system opensand
  fi
  if ! getent passwd opensand >/dev/null; then
    useradd --system -c 'OpenSAND user' -g opensand -d / -s /bin/false opensand
  fi
}

post_upgrade() {
  post_install $1
}

post_remove() {
  if getent passwd opensand >/dev/null; then
    userdel opensand
  fi
  if getent group opensand >/dev/null; then
    groupdel opensand
  fi
}

