# Maintainer: RubenKelevra <cyrond@gmail.com>

pkgname=rk-desktop-kde
pkgver=2014.10.19
pkgrel=3
pkgdesc="Metapackage that installs a full kde desktop. Enables all needed services."
url="http://notyetthere.com"
arch=('i686' 'x86_64')
license=('GPLv3')
install=rk-desktop-kde.install
makedepends=("yaourt"
)
depends=("pkgtools"
"preload"
"openssl"
"net-tools"
"sudo"
"iproute2"
"yp-tools"
"dos2unix"
"python2"
"python3"
"wget"
"ntp"
"acpid"
"dbus"
"avahi"
"abs"
"p7zip"
"zip"
"unrar"
"openssh"
"pm-utils"
"traceroute"
"pkgfile"
"hdparm"
"ethtool"
"sdparm"
"dosfstools"
"haveged"
"nmap"
"iperf"
"hping"
"sysstat"
"iotop"
"tcpdump"
"mausezahn"
"htop"
"lsof"
"dnssec-anchors"
"ldns"
"screen"
"curl"
"unrar"
"ntfs-3g"
"dosfstools"
"btrfs-progs"
"git"
"help2man"
"subversion"
"f2fs-tools"
"sshfs"
"imagemagick"
"ghostscript"
"crda"
"bzr"
"cvs"
"iftop"
"cacert-dot-org"
"mtr"
"dnsutils"
"socat"

"kde-meta-kdeadmin"
"kde-meta-kdeartwork"
"kde-meta-kdebase"
"kde-meta-kdeedu"
"kde-meta-kdegraphics"
"kde-meta-kdemultimedia"
"kde-meta-kdenetwork"
"kde-meta-kdepim"
"kde-meta-kdeplasma-addons"
"kde-meta-kdesdk"
"kde-meta-kdetoys"
"kde-meta-kdeutils"
"kde-meta-kdewebdev"
"kde-wallpapers"

"xorg-server"
"xorg-xprop"
"xorg-xinit"
"xorg-utils"
"xorg-server-utils"
#"xorg-drivers"
"xf86-input-evdev"
"xf86-input-joystick"
"xf86-input-keyboard"
"xf86-input-mouse"
"xf86-input-synaptics"
"xf86-input-vmmouse"
"xf86-input-void"
"xf86-video-ark"
"xf86-video-ast"
"xf86-video-ati"
"xf86-video-cirrus"
"xf86-video-dummy"
"xf86-video-fbdev"
"xf86-video-glint"
"xf86-video-i128"
"xf86-video-intel"
"xf86-video-mach64"
"xf86-video-mga"
"xf86-video-modesetting"
"xf86-video-neomagic"
"xf86-video-nouveau"
"xf86-video-nv"
"xf86-video-openchrome"
"xf86-video-r128"
"xf86-video-savage"
"xf86-video-siliconmotion"
"xf86-video-sis"
"xf86-video-tdfx"
"xf86-video-trident"
"xf86-video-v4l"
"xf86-video-vesa"
"xf86-video-vmware"
"xf86-video-voodoo"
"numlockx"
"rfkill"
"ttf-google-fonts-git"
"gstreamer0.10-bad"
"gstreamer0.10-good-plugins"
"gstreamer0.10-ugly"
"gstreamer0.10-ffmpeg"
"gstreamer0.10-good"
"gstreamer0.10-vaapi"
"gstreamer0.10-python"
"gstreamer0.10-ugly-plugins"
"gstreamer0.10-bad-plugins"
"gst-plugins-base"
"gst-plugins-ugly"
"gst-libav"
"gst-plugins-good"
"gstreamer0.10-base-plugins"
"jre7-openjdk-headless"
"ntfs-3g"
"wpa_supplicant"
"ttf-freefont"
"wireless_tools"
"ttf-dejavu"
"libdvdcss"
"libva-intel-driver"
"vorbis-tools"
"mac"
"libaacs"
"libbdplus"
"libbluray"
"libdvdcss"
"mono"
"mkvtoolnix-gtk"
"ttf-cheapskate"
)
conflicts=(
"rk-server-basic"
"rk-desktop-gnome"
"rk-gnome-desktop-native"
)
provides=("rk-desktop")
optdepends=(
"rk-desktop-kde-games: All the nice kde mini-games"
"rk-desktop-kde-removegames: Remove all kde mini-games"
"rk-desktop-apps: The most-used desktop apps"
"rk-desktop-kde-removenative: if you want to remove some useless native-kde apps"
"rk-desktop-kde-accessibility: All the nice kde accessibility apps"
"rk-desktop-kde-removeaccessibility: Remove all accessibility apps"
"rk-print: Everything for printer"
"rk-bluetooth: Everything for bluetooth"
"rk-desktop-favapps: Authors personal app-list"
"firefox: The Firefox browser"
"chromium: The Chromium browser"
"google-chrome: The Chrome browser"
)
