# Generated by gem2arch
# Maintainer: LeeF

_gemname=lockfile
pkgname=ruby-enterprise-$_gemname
pkgver=1.4.3
pkgrel=0
pkgdesc="lockfile"
arch=('i686' 'x86_64')
url="http://codeforpeople.com/lib/ruby/lockfile/"
license=('Unspecified')
depends=('ruby-enterprise')
makedepends=('ruby-enterprise')
source=(http://gems.rubyforge.org/gems/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
md5sums=('53a63206bbaefb7106db5a74a5adf148')

build() {
  cd $srcdir
  local _gemdir=`ruby -rubygems -e'puts Gem.default_dir'`
  gem install --ignore-dependencies --no-rdoc --no-ri  -i "$pkgdir$_gemdir" $_gemname-$pkgver.gem
}
