--- Makefile	2009-01-19 15:11:33.000000000 +0000
+++ Makefile.new	2011-07-16 13:03:52.000000000 +0100
@@ -8,7 +8,7 @@
 # (at your option) any later version.
 
 DESTDIR	=
-prefix	= /usr/local
+prefix	= /usr
 bindir	= $(prefix)/bin
 sbindir	= $(prefix)/sbin
 mandir	= $(prefix)/share/man
