--- make.include.linux.orig	2005-08-03 06:55:45.000000000 +0200
+++ make.include.linux	2009-02-11 13:53:54.970135549 +0100
@@ -13,7 +13,7 @@
 # -DNO_FREETYPE).
 #
 #
-# P_FREETYPE = 1
+P_FREETYPE = 1
 #
 # Alternatively, when compiling, call make with the option P_FREETYPE=1
 
@@ -32,7 +32,7 @@
 
 CXX=g++
 
-CXXFLAGS= -O3 -Wall -Wno-deprecated $(FT_ARG)
+CXXFLAGS+= $(FT_ARG)
 
 INC=  -I../src/ -I$(PREFIX)/include/
 
