#!/bin/sh
if [ -d /usr/lib/jvm/java-7-openjdk/jre ] ; then
	if [ -f /usr/share/icedtea-web/netx.jar ] ; then
		JAVAWS=/usr/share/icedtea-web/netx.jar
	else
		echo "Err: icedtea-web-java7 should install"
		exit 1
	fi
elif [ -d /opt/sun-java6 ] ; then
	. /opt/sun-java6/envsetup.sh
	JAVAWS="$JAVA_HOME"/jre/lib/javaws.jar
	if [ ! -r $JAVAWS ] ; then
		echo "Err: missing JAVAWS ($JAVAWS)"
		exit 1
	fi
elif [ -d /opt/java -o -d /opt/java6 ] ; then
	JAVAWS="$JAVA_HOME"/jre/lib/javaws.jar
	if [ ! -r $JAVAWS ] ; then
		echo "Err: missing JAVAWS ($JAVAWS)"
		exit 1
	fi
else
	echo "Err: Please install openjdk or jre+jdk>=7.7 or sun-java6"
	exit 1
fi

$JAVA_HOME/bin/java -Xmx256m -jar /usr/share/java/sweethome3d.jar
