#!/bin/sh
PROGRAM_DIR=/usr/share/java/sweethome3d
if [ -d /usr/lib/jvm/java-7-openjdk/jre ] ; then
	if [ -f /usr/share/icedtea-web/netx.jar ] ; then
		JAVAWS=/usr/share/icedtea-web/netx.jar
	else
		echo "Err: icedtea-web-java7 should install"
		exit 1
	fi
elif [ -d /opt/sun-java6 ] ; then
	. /opt/sun-java6/envsetup.sh
	JAVAWS="$JAVA_HOME"/jre/lib/javaws.jar
	if [ ! -r $JAVAWS ] ; then
		echo "Err: missing JAVAWS ($JAVAWS)"
		exit 1
	fi
elif [ -d /opt/java ] ; then
	JAVAWS="$JAVA_HOME"/jre/lib/javaws.jar
	if [ ! -r $JAVAWS ] ; then
		echo "Err: missing JAVAWS ($JAVAWS)"
		exit 1
	fi
else
	echo "Err: Please install openjdk or jre+jdk>=7.7 or sun-java6"
	exit 1
fi

$JAVA_HOME/bin/java -Xmx1024m -classpath "$PROGRAM_DIR"/lib/SweetHome3D.jar:\
"$PROGRAM_DIR"/lib/Furniture.jar:"$PROGRAM_DIR"/lib/Textures.jar:\
"$PROGRAM_DIR"/lib/Help.jar:"$PROGRAM_DIR"/lib/Loader3DS1_2u.jar:\
"$PROGRAM_DIR"/lib/iText-2.1.7.jar:\
"$PROGRAM_DIR"/lib/freehep-vectorgraphics-svg-2.1.1.jar:\
"$PROGRAM_DIR"/lib/sunflow-0.07.3g.jar:"$PROGRAM_DIR"/lib/jmf.jar:\
"$PROGRAM_DIR"/lib/batik-svgpathparser-1.7.jar:\
"$PROGRAM_DIR"/lib/j3dcore.jar:"$PROGRAM_DIR"/lib/j3dutils.jar:\
"$PROGRAM_DIR"/lib/vecmath.jar:\
$JAVAWS \
-Djava.library.path="$PROGRAM_DIR"/lib com.eteks.sweethome3d.SweetHome3D \
-open "$1"
