_install_notes() {
    echo
    echo '  (I) IcarusTouch does not have internal sound.'
    echo '      A connected MIDI device is required.'
    echo '      Alternatively, you can use a software MIDI synthesizer.'
    echo '  (I) Ensure the MIDI device or software synthesizer is'
    echo '      connected/running before launching IcarusTouch.'
    echo
}

post_install() {
    _install_notes
}

post_upgrade() {
    _install_notes
}
