post_install() {
cat << EOF
In order to play the game, you HAVE TO install one of the packages listed as optdepends. Packages 'vegastrike-data' and 'vegastrike-data-svn' are the original data sets. Package 'paralleluniverse' intends to be the revival of Privateer, an old spacesim by Origin System from the 90s and is a total conversion of the game.
EOF
}

post_remove() {
cat << EOF
Don't forget to remove the data files for VegaStrike also!
EOF
}
