# arg 1:  the new package version
post_install() {
  echo ""
  echo "The microcode will be updated next time the microcode kernel code"
  echo "will be executed; you can issue the following command to force a"
  echo "reload:"
  echo ""
  echo "    modprobe -r microcode && modprobe microcode"
  echo ""
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $1
}

# vim:set ts=2 sw=2 et:
