post_install() {
  echo "==> By using this software, you accept the FPAV EULA:"
  echo "     /usr/share/licenses/fprot/LICENSE"
  echo "==> Updates are cron'ed, but you should run an initial update:"
  echo "     # fpupdate"
  echo "==> Documentation:"
  echo "     fpscan(1)"
  echo "     f-prot.conf(5)"
  echo "     fpupdate(8)"
  echo "     /usr/share/doc/fprot/README"
}

post_upgrade() {
  post_install $1
}
