post_install() {
cat << EOF
==> You need to copy your windows drivers files to /usr/share/cups/drivers (for 32 bits systems)
==> The files can be found in %WINDIR%\SYSTEM32\SPOOL\DRIVERS\W32X86\3
==> 
==> Copy the following files: (Case is significant)
==> ps5ui.dll
==> pscript.hlp 
==> pscript.ntf 
==> pscript5.dll
==> 
==> Now you can run cupsaddsmb -a as root to export them to the samba server.
EOF
}

post_upgrade() {
	post_install $1
}

