post_install() {
cat << EOF
==> For more information about Icecream have a look at:
==> 'http://en.opensuse.org/Icecream'
==> You can add the daemons icecream on all machines and icecream-scheduler on one machine in /etc/rc.conf
==> You can enable icecream.service and icecream-scheduler.service with systemctl if using systemd
==> Remember to prepend /usr/lib/icecream/bin to your PATH!
EOF
}

op=$1
shift

$op $*
