post_install() {
    echo -e '\E[1;34m'
    echo " "
    echo " "
    echo "<==== INFORMATION ====>"
    echo " "
    echo "* Hacker Evolution Demo is now installed."
    echo "* The full version can be purchased for $ 24.95"
    echo "* Homepage: http://www.exosyphen.com/page_hacker-evolution-untold.html"
    echo " "
    echo "* Accessing the game by typing 'hackerevolution-demo' in the terminal."
    echo "* Changing the game preferences: edit '~/.heuntold-demo/preferences.txt'"
    echo " "

tput sgr0 
}




