post_install() {
echo -e "Run 'archnews' in your terminal:\n$ archnews\nAdd this to your .bashrc or respective configutation file:\ncat $HOME/.archnews_format\nFinally, add 'archnews' to your crontab:\n$ crontab -e\n*/60 * * * *   /usr/bin/archnews\nMore info at: http://matej-lach.me/archnews/"
}

post_upgrade() {
  echo -e "Enjoy this updated version of 'archnews', more info at: http://matej-lach.me/archnews/"
}
