#Automatically generated by pip2arch on 2012-02-07

pkgname=python-rdio
pkgver=0.5
pkgrel=1
pkgdesc="An unofficial wrapper for the Rdio API."
url="http://pypi.python.org/pypi/python-rdio/0.5"
depends=('python2' 'python2-httplib2' 'python2-oauth2' 'python-dateutil')
makedepends=('python2-distribute' 'python2-pip')
license=('MIT')
arch=('any')
source=('http://pypi.python.org/packages/source/p/python-rdio/python-rdio-0.5.tar.gz')
md5sums=('6384b9f089f9f632e7b66f7feb2a1630')

build() {
    cd $srcdir/python-rdio-0.5
    sudo pip2 install --no-deps . 

}

