# Colored makepkg-like functions
msg_blue() {
	printf "${blue}==>${bold} $1${all_off}\n"
}

note() {
	printf "${blue}==>${yellow} NOTE:${bold} $1${all_off}\n"
}

all_off="$(tput sgr0)"
bold="${all_off}$(tput bold)"
blue="${bold}$(tput setaf 4)"
yellow="${bold}$(tput setaf 3)"

post_install() {
	note "The Arm toolchain is under /opt/gcc-linaro-aarch64-linux-gnu/bin/"
	note "In order to use it, use the absolute path or add to your PATH"
}
