--- Makefile.in.orig	2011-10-18 20:58:58.160186938 +0200
+++ Makefile.in	2011-10-18 20:59:21.423394245 +0200
@@ -19,9 +19,9 @@
 endif
 CP=cp -p
 MKDIR=mkdir -p
-BUILD=debug
+BUILD=production
 
-prefix=@prefix@
+prefix=$(DESTDIR)@prefix@
 srcdir=@srcdir@
 root_objdir=@objdir@
 exec_prefix=@exec_prefix@
