#!/bin/bash

export BPDIR=$HOME/.bprolog
PAREA=2000000	# Size of program area
STACK=2000000	# Size of control stack and heap
TRAIL=2000000	# Size of trail stack
TABLE=1000000	# Size of table area

mkdir -p $BPDIR

if [[ ! -f $HOME/.bprolog/bp.out ]]
then
    cp /usr/share/bprolog/bp.out $BPDIR
fi

exec bprolog -p $PAREA -s $STACK -b $TRAIL -t $TABLE $BPDIR/bp.out ${1+"$@"}

