post_install() {
    echo "Run 'zandronum' to initialize: (Click cancel after it fails to open if required)

	zandronum 

Ensure all of your existing .wad files use lowercase only, no UpperCase allowed.
Now copy your existing .wad files to ~/.zandronum/:

    $ cp *.wad ~/.zandronum/

Now copy zandronum.ini to ~/.zandronum/:

    $ cp /usr/share/games/brutaldoom/zandronum.ini ~/.zandronum/zandronum.ini

Good to go!"

}

post_upgrade() {
    post_install
}
