post_install() {
    if [ -z "`grep '^opendnssec:' /etc/group`" ]; then
        groupadd -g 227 opendnssec
    fi
    if [ -z "`grep '^opendnssec:' /etc/passwd`" ]; then
        useradd -u 227 -d /var/lib/opendnssec -g opendnssec -s /bin/false opendnssec
    fi

    echo ">> You need an HSM implementation (try softhsm)"
}


post_upgrade() {
    post_install $1
}

post_remove() {
    userdel opendnssec
}
