# arg 1: the new package version
post_install() {
  echo "Updating font cache... (this may take a while)"
  fc-cache -f > /dev/null
  mkfontscale /usr/share/fonts/misc
  mkfontdir /usr/share/fonts/misc
  [[ -n "$DISPLAY" ]] && xset fp rehash
}

# # arg 1: the new package version
# # arg 2: the old package version
post_upgrade() {
  post_install $1
}
#
# # arg 1: the old package version
post_remove() {
  post_install $1
}

