# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>
# Contributor: Alfredo Palhares <masterkorp@masterkorp.net>

_gemname=celluloid
pkgname=ruby-$_gemname-0.14.1
pkgver=0.14.1
pkgrel=2
pkgdesc='Actor-based concurrent object framework for Ruby'
arch=(any)
url='https://github.com/celluloid/celluloid'
license=(MIT)
depends=(ruby ruby-timers)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('86eeeed26ad7adf9b5868b89d34f8f83a8d4d212')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
