# arg 1: the new package version
# arg 2: the old package version

post_install () {
  echo ">> Place 'frandom' in DAEMONS= in /etc/rc.conf to enable /dev/frandom."
  echo ">> This module needs to be recompiled for every kernel version upgrade."
  depmod -a
}

pre_remove () {
  rmmod frandom 2> /dev/null
  rm /dev/frandom /dev/erandom 2> /dev/null
}

post_remove () {
  depmod -a
}

op=$1
shift
$op $*
