# arg 1: the new package version
# arg 2: the old package version

post_install () {
  echo ">> add frandom to /etc/modules-load.d/ if you want the module to load on boot."
  echo ">> This module needs to be recompiled for every kernel version upgrade."
  depmod -a
}

pre_remove () {
  rmmod frandom 2> /dev/null
  rm /dev/frandom /dev/erandom 2> /dev/null
}

post_remove () {
  depmod -a
}

op=$1
shift
$op $*
