USER="sonarr"
GROUP="sonarr"
DIR="/var/lib/sonarr"

post_install() {
  groupadd ${GROUP} &> /dev/null
  useradd -g ${GROUP} -d ${DIR} -s /bin/false ${USER} &> /dev/null
  chown -R ${USER}:${GROUP} ${DIR}
}

post_upgrade() {
  usermod -g ${GROUP} -d ${DIR} -s /bin/false ${USER} &> /dev/null
  chown -R ${USER}:${GROUP} ${DIR}
}

post_remove() {
  userdel ${USER} &> /dev/null
  groupdel ${GROUP} &> /dev/null || /bin/true
}

