post_install() {
	post_upgrade;
}

post_upgrade() {
	printf "\033[1m\033[32m\x3d\x3d\x3e\033\1330m Configuring to make the driver work...\n"
	/usr/local/Brother/Printer/mfc260c/cupswrapper/cupswrappermfc260c >/dev/null
	if [ "$?" -eq 0 ]; then
		printf "\033[1m\033[32m\x3d\x3d\x3e\033\1330m Done. The printer should be visible now via the CUPS-webinterface (http://localhost:631)\n"
	else
		printf "\033[1m\032[32m\x3d\x3d\x3e\033\1330m Something went wrong...\n"
	fi
}
