notice() {
	echo '======================================'
	echo
	echo -e 'If you are on x64 you may want to install \e[1;31mgcc-multilib\e[1;0m if you have to link 32bits binaries too.'
	echo 'If you want to install it now just type:'
	echo
	echo -e '\e[1;31mpacman -Sy gcc-multilib\e[1;0m'
	echo
	echo '======================================'
}

post_install() {
	notice
}

post_upgrade() {
	notice
}

