post_install() {
 echo " => To enable threading run :"
 echo " -> mplayer -lavdopts threads=N file.mkv"                                 
 echo " -> #where N is the number of threads you want to use."
 echo " => To add it to the config run :"
 echo " -> echo "lavdopts=threads=$(cat /proc/cpuinfo | grep -c cores)" >> $HOME/.mplayer/config "
 echo " -> #Enable multithreading in mplayer, with 1 thread per core."
}

post_upgrade() {
  post_install $1
}