post_install() {    
  groupadd sabnzbd &> /dev/null
  useradd -g sabnzbd -d /opt/sabnzbd -s /bin/false sabnzbd &> /dev/null
  chown -R sabnzbd:sabnzbd /opt/sabnzbd
  echo "  >> Don't forget to edit /etc/conf.d/sabnzbd!"
  echo "  >> Add your Session key and if necessary your username and password to ensure a proper shutdown."
}

post_upgrade() {
  chown -R sabnzbd:sabnzbd /opt/sabnzbd 
}

pre_remove() {
  groupdel sabnzbd &> /dev/null
  userdel sabnzbd &> /dev/null
}