post_install() {
    echo "Moving /etc/gtk-server.cfg to /etc/gtk-server.cfg.default"
    mv /etc/gtk-server.cfg /etc/gtk-server.cfg.default
    echo "Installing ikarus-gtk version of /etc/gtk-server.cfg"
    mv /usr/lib/ikarus/gtk/gtk-server.cfg /etc/gtk-server.cfg
}

post_upgrade() {
  post_remove $1
  post_install $1
}

post_remove() {
  echo "Restoring default /etc/gtk-server.cfg"
  mv /etc/gtk-server.cfg.default /etc/gtk-server.cfg
}

op=$1
shift

$op $*
