# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: kusakata <shohei atmark kusakata period com>

_gemname=activemerchant
pkgname=ruby-$_gemname
pkgver=1.42.4
pkgrel=1
pkgdesc='Framework and tools for dealing with credit card transactions.'
arch=(any)
url='http://activemerchant.org/'
license=(MIT)
depends=(ruby ruby-activesupport ruby-i18n ruby-money ruby-builder ruby-json ruby-active_utils ruby-nokogiri)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('e0d9c69f674a1c1272035df36a2af865e249e226')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/MIT-LICENSE" "$pkgdir/usr/share/licenses/$pkgname/MIT-LICENSE"
}
