post_install() {
echo -e "要建立文件關聯，請運行:\n要建立文件关联，请运行:\nto handle file association, please run:"
echo -e "/usr/local/Yozosoft/Yozo_Office/Jre/bin/java -client -jar /usr/local/Yozosoft/Yozo_Office/Mimelnk/fileAssociate.jar -i\n"
echo -e "要取消文件關聯，請運行:\n要取消文件关联，请运行:\nto cancell file association, please run:"
echo -e "/usr/local/Yozosoft/Yozo_Office/Jre/bin/java -client -jar /usr/local/Yozosoft/Yozo_Office/Mimelnk/fileAssociate.jar -u\n"
}

pre_remove() {
echo "cancelling file association, waiting a while..."
/usr/local/Yozosoft/Yozo_Office/Jre/bin/java -client -jar /usr/local/Yozosoft/Yozo_Office/Mimelnk/fileAssociate.jar -u

rm -f $HOME/.Yozo_Office/UserConfig/BarData $HOME/.Yozo_Office/UserConfig/system.dll $HOME/.Yozo_Office/UserConfig/system0.dll $HOME/.Yozo_Office/UserConfig/system1.dll $HOME/.Yozo_Office/UserConfig/system2.dll $HOME/.Yozo_Office/UserConfig/systempdf.dll
if [ -f /usr/local/Yozosoft/Yozo_Office/patcheio.log ] ; then
	rm -f /usr/local/Yozosoft/Yozo_Office/patcheio.log
fi
rm -rf /usr/local/Yozosoft/Yozo_Office/System
if [ -d $HOME/.Yozo_Office/CustomizedSEImages ]; then
	rm -rf $HOME/.Yozo_Office/CustomizedSEImages
fi

	rm -f /usr/local/Yozosoft/Yozo_Office/ScienceEditorImages/logicalData /usr/local/Yozosoft/Yozo_Office/ScienceEditorImages/logicalData_0 /usr/local/Yozosoft/Yozo_Office/ScienceEditorImages/logicalData_1 /usr/local/Yozosoft/Yozo_Office/ScienceEditorImages/logicalData_2

if [ -d /usr/local/Yozosoft/Yozo_Office/ScienceEditorImages ]; then 
	rmdir /usr/local/Yozosoft/Yozo_Office/ScienceEditorImages &>/dev/null
fi

rm -rf /usr/local/Yozosoft/Yozo_Office/Upgrade/Patch
rm -f /usr/local/Yozosoft/Yozo_Office/Yozo_Office.jar 
libP=/usr/local/Yozosoft/Yozo_Office/Jre/lib
rm -rf $libP
}
