post_install() {
  echo "Updating icon and desktop caches..."
  xdg-icon-resource forceupdate --theme hicolor &> /dev/null
  update-desktop-database -q
  echo "done."
  echo "Fixing KAG permissions..."
  chmod 775 /usr/share/kag/KAG
  chmod +X /usr/share/kag/KAG
  echo "done."
}

post_upgrade() {
  post_install
}

post_remove() {
  echo "Removing leftover files..."
  rm -r /usr/share/kag
  echo "done."
}
