# Generated by Xyne::Arch::CPAN 0.07

pkgname=perl-sys-sendfile
pkgver=0.110.0
pkgrel=1
pkgdesc="Zero-copy data transfer"
arch=('i686' 'x86_64')
url="http://search.cpan.org/dist/Sys-Sendfile/"
license=('perl')
source=('http://search.cpan.org/CPAN/authors/id/L/LE/LEONT/Sys-Sendfile-0.11.tar.gz')
md5sums=('457c534e77f130bfc77ccbe3aa05c908')
sha256sums=('f91e3ebdc3f5b5888922aec5ceca6b43f752dd07c1852a19aa2cd2d76aacf231')
depends=('perl>=5.0.6')
makedepends=('perl-extutils-cbuilder' 'perl-test-more')
options=(!emptydirs)

build() {
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Makefile.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor || return 1
    make  || return 1
    make install DESTDIR="${pkgdir}" || return 1

  else
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Build.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Build.PL INSTALLDIRS=vendor || return 1
    ./Build  || return 1
    ./Build install destdir=${pkgdir} || return 1

  else
    echo "error: failed to detect build method for $pkgname"
    echo "you may be able to fix this by editing the PKGBUILD"
    return 1
  fi fi

  # remove perllocal.pod and .packlist
  find ${pkgdir} -name perllocal.pod -delete
  find ${pkgdir} -name .packlist -delete
}

# vim:set ts=2 sw=2 et:

