post_install() {
    echo -e '\E[1;34m'
    echo " "
    echo " "
    echo "<==== INFORMATION ====>"
    echo " "
    echo "* Rain-Slick Precipice of Darkness - Episode 1 is now installed."
    echo "* To unlock the full game; $ 14.95"
    echo "* Link: http://www.playgreenhouse.com/game/HOTHG-000001-01/"
    echo " "
    echo "* Accessing the game by typing 'rainslickep1' in the terminal. "
    echo " "

tput sgr0 
} 