# Message displayed after a fresh install.
post_install() {
    echo "Add these lines to ~/.emacs:"
    echo "  (require 'yaml-mode)"
    echo "  (add-to-list 'auto-mode-alist '(\"\\\\.yml\\\\'\" . yaml-mode))"
}

# Message displayed afteer package removal.
post_remove() {
    echo "Remove these lines from ~/.emacs:"
    echo "  (require 'yaml-mode)"
    echo "  (add-to-list 'auto-mode-alist '(\"\\\\.yml\\\\'\" . yaml-mode))"
}
