# Message displayed after a fresh install.
post_install() {
	echo "Add these lines to ~/.emacs:"
	echo "  (autoload 'yaml-mode "yaml-mode" "A major mode for YAML" t)"
	echo "  (add-to-list 'auto-mode-alist '(\"\\\\.yml\\\\'\" . yaml-mode))"
}

# Message displayed afteer package removal.
post_remove() {
	echo "Remove these lines from ~/.emacs:"
	echo "  (autoload 'yaml-mode "yaml-mode" "A major mode for YAML" t)"
	echo "  (add-to-list 'auto-mode-alist '(\"\\\\.yml\\\\'\" . yaml-mode))"
}
