post_install() {
    chown granola etc/granola-connect.conf
    cat << __EOF__
===> Requires the granola daemon to be running before starting.
===> Put your https://grano.la/dash/ account information
===> in the config file /etc/granola-connect.conf as root.
===> Also run the following commands as root:
    systemctl enable granola-connect.service
    systemctl start granola-connect.service
__EOF__
}

post_upgrade() {
    post_install
}
