.TH doneyet 1
.SH NAME
doneyet \- an ncurses\-based heirarchical todo list manager
.SH SYNOPSIS
.B doneyet
.SH DESCRIPTION
.PP
\fBdoneyet\fR is a filter\-based todo list manager. Currently there are four filters:
.TP
\fBShow All Tasks\fR
This shows all tasks in the current project.
.TP
\fBShow Unfinished Tasks\fR
This shows any task with a status of \fIunstarted\fR, \fIin progress\fR, or \fIpaused\fR.
.TP
\fBShow Completed Tasks\fR
This shows only tasks that have a completion date within 7 days of now.
.TP
\fBFind\fR
This filter takes a user specified string and shows any that match. This uses case\-sensitive search.
.SH KEY SHORTCUTS
.PP
\fBdoneyet\fR is used primarily through key commands. There is a menu system in place, but not everything can be achieved through it. The key commands are as follows:
.TP
\fBA\fR
Apply the \fIShow All Tasks\fR filter.
.TP
\fBa\fR
If a task is selected, add a new subtask of that task. If no task is selected, add a root level task.
.TP
\fBM\fR
Show the menu bar.
.TP
       \fBj\fR, \fBk\fR        Change menu item.
.TP
       \fBl\fR, \fBh\fR        Change menu.
.TP
       \fBReturn\fR      Select the selected menu item.
.TP
       \fBEscape\fR      Hide the menu bar.
.TP
\fBm\fR
Move the currently selected task.
.br
\fINote\fR: this does not work for root level tasks yet.
.TP
       \fBk\fR, \fBu\fR, \fBUP\fR    Move selected task up
.TP
       \fBj\fR, \fBd\fR, \fBDOWN\fR  Move selected task down
.TP
       \fBReturn\fR      Place task at current position.
.TP
       \fBEscape\fR      Place task to where it was originally.
.TP
\fBn\fR
Add a note to the selected task.
.TP
\fBv\fR
View the notes of the selected task.
.TP
\fBj\fR
Select next task.
.TP
\fBk\fR
Select previous task.
.TP
\fBEscape\fR
Select no task.
.TP
\fBe\fR
Edit selected task.
.TP
\fBd\fR
Delete selected task.
.TP
\fBc\fR
Toggle collapsed state of selected task.
.TP
\fBR\fR
Apply the \fIShow Uncompleted Tasks\fR filter.
.TP
\fBC\fR
Apply the \fIShow Completed Tasks\fR filter.
.TP
\fBf\FR
Apply the \fIFind Tasks\fR filter.
.TP
\fBSpace\fR
Toggle the status of the selected item.
.br
white=\fIunstarted\fR; green=\fIin progress\fR; blue=\fIcompleted\fR; red=\fIpaused\fR.
.TP
\fBq\fR
Quit.
.SH SAVING
.PP
\fBdoneyet\fR will save upon quitting or when choosing 'Save' from the 'Project' menu.
.SH MENU SYSTEM
.PP
The menu system also contains the 'Plain Text' menu item in the 'Generate' menu. This creates a text file of whatever is currently filtered in "/tmp/snippet.txt" and then calls \fBless\fR on that file.
.PP
A potential use of this is reporting weekly progress in email. Copying directly out of the ncurses window is difficult and time consuming. This however generates a plain text version with no borders.
.SH AUTHOR
.TP
.B doneyet
written by gtaubman
.TP
.B doneyet(1)
written by tdy, based on the online readme
.SH COPYRIGHT
.PP
Copyright \(co 2008 gtaubman
.PP
This program may be freely redistributed under the terms of the GNU General Public License.
.PP
http://code.google.com/p/doneyet/
