post_install() {
	echo "Setting files and dirs permissions..."
	chmod -R 777 /usr/share/games/vangers-community-rus/thechain &> /dev/null
	chmod -R 777 /usr/share/games/vangers-community-rus/savegame &> /dev/null
	chmod 777 /usr/share/games/vangers-community-rus/controls.dat &> /dev/null
	chmod 777 /usr/share/games/vangers-community-rus/logfile.txt &> /dev/null
	chmod 777 /usr/share/games/vangers-community-rus/openfile.txt &> /dev/null
	chmod 777 /usr/share/games/vangers-community-rus/options.dat &> /dev/null
	chmod 777 /usr/share/games/vangers-community-rus/tmp_f1.txt &> /dev/null
	chmod 777 /usr/share/games/vangers-community-rus/wrlds.dat &> /dev/null
	echo "Done!"
}

post_upgrade() {
	post_install
}

post_remove() {
	post_install
}
