# Generated by gem2arch
# Maintainer: LeeF

_gemname=net-ssh
pkgname=ruby-enterprise-$_gemname
pkgver=2.0.23
pkgrel=0
pkgdesc="Net::SSH: a pure-Ruby implementation of the SSH2 client protocol."
arch=('i686' 'x86_64')
url="http://github.com/net-ssh/net-ssh"
license=('MIT')
depends=('ruby-enterprise')
makedepends=('ruby-enterprise')
source=(http://gems.rubyforge.org/gems/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
md5sums=('14d51aab0ac31f2af9646236a6af848e')

build() {
  cd $srcdir
  local _gemdir=`ruby -rubygems -e'puts Gem.default_dir'`
  gem install --ignore-dependencies --no-rdoc --no-ri  -i "$pkgdir$_gemdir" $_gemname-$pkgver.gem
}
