pkgname=diff-ext

post_install() {
  usr/sbin/gconfpkg --install $pkgname
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor

  echo "+++ You must set your desired diff tool via the diff-ext-setup tool."
  echo "+++ Run \`diff-ext-setup' or launch it from the menu."
}

pre_upgrade() {
  pre_remove $1
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  usr/sbin/gconfpkg --uninstall $pkgname
}

post_remove() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}
