post_install() {
  update-mime-database /usr/share/mime
  glib-compile-schemas /usr/share/glib-2.0/schemas/

  echo "-----------------------------------------------------"
  echo 'Run "gmate-activate" to load default gmate settings.'
  echo "-----------------------------------------------------"
}

post_upgrade() {
  post_install
}

post_remove() {
  update-mime-database /usr/share/mime
  glib-compile-schemas /usr/share/glib-2.0/schemas/
}
