post_install() {
echo "during the first run you will be asked to choose a location for a library <libSNNS_jkr.so>, 
it can be anywhere, you just need write permissions to this directory." 
}

post_remove() {
echo "library libSNNS_jkr.so was created during install, you need to remove it manually now, pacman cannot locate it, sorry. You were asked for the location during install, so I hope you can find it now ;)"
}
