post_install() {
cat << EOF
 
  =====================================================================================
  ==> It's recommend to download "tcpdump" and "gnuplot"
  ==> See "http://jarok.cs.ohiou.edu/software/tcptrace/useful.html" for useful programs
  =====================================================================================

EOF
}

post_upgrade() {
  post_install
}

op=$1
shift
$op $*
