# arg 1:  the new package version
post_install() {
  echo ">>> Add resmgr to the DAEMONS array in /etc/rc.conf if you want"
  echo ">>> to start at system boot-up."
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
 post_install $1
}

# arg 1:  the old package version
pre_remove() {
  echo ">>> Don't forget to remove resmgr from /etc/rc.conf"
}

op=$1
shift

$op $*