post_install() {
 echo '--------------------------------------------------------------------------'
 echo '                           INSTRUCTIONS FOR USE'
 echo 
 echo 'Simply map the following scripts to keyboard shortcuts in your DE or WM.'
 echo 'Xfce4 allows for this under Settings > Keyboard > Application Shortcuts.'
 echo
 echo '/usr/bin/mute_toggle  ==>  Toggle status of mute'
 echo '/usr/bin/vol_up       ==>  Increase vol by 5 %'
 echo '/usr/bin/vol_down     ==>  Decrease vol by 5 %'
 echo '--------------------------------------------------------------------------'
}

post_remove() {
 echo '-----------------------------------------------------------------------'
 echo 'Be sure you remove any keyboard shortcuts or bindings you created.'
 echo '-----------------------------------------------------------------------'
}
