post_install() {
  echo " ==> Run Texmaster only via the included texmaster shell script."
  echo " ==> After running texmaster for the first time you can change your"
  echo " ==> settings in \$HOME/.texmaster/Texmaster2009.ini"
  echo
  echo " ==> If you are updating from texmaster 2009.1-1, remove ~/.texmaster"
  echo " ==> and run texmaster to re-create it."
}

post_upgrade() {
  post_install
}

# vim:set ts=2 sw=2 et:
