# Message displayed after a fresh install.
post_install() {
    echo "Add the following lines to ~/.emacs:"
    echo "  (add-to-list 'custom-theme-load-path \"~/.emacs.d/themes/\")"
    echo "  (load-theme 'zenmonk t)"
}

# Message displayed afteer package removal.
post_remove() {
    echo "Remove these lines from ~/.emacs:"
    echo "  (add-to-list 'custom-theme-load-path \"~/.emacs.d/themes/\")"
    echo "  (load-theme 'zenmonk t)"
}
