--- Makefile	2012-01-15 01:40:58.000000000 +0100
+++ Makefile	2012-08-13 01:03:22.000000000 +0200
@@ -1,4 +1,4 @@
-WAF=python tools/waf-light
+WAF=python2 tools/waf-light
 
 web_root = node@nodejs.org:~/web/nodejs.org/
 
@@ -32,41 +32,41 @@
 	@$(WAF) uninstall
 
 test: all
-	python tools/test.py --mode=release simple message
+	python2 tools/test.py --mode=release simple message
 
 test-http1: all
-	python tools/test.py --mode=release --use-http1 simple message
+	python2 tools/test.py --mode=release --use-http1 simple message
 
 test-valgrind: all
-	python tools/test.py --mode=release --valgrind simple message
+	python2 tools/test.py --mode=release --valgrind simple message
 
 test-all: all
-	python tools/test.py --mode=debug,release
+	python2 tools/test.py --mode=debug,release
 	make test-npm
 
 test-all-http1: all
-	python tools/test.py --mode=debug,release --use-http1
+	python2 tools/test.py --mode=debug,release --use-http1
 
 test-all-valgrind: all
-	python tools/test.py --mode=debug,release --valgrind
+	python22 tools/test.py --mode=debug,release --valgrind
 
 test-release: all
-	python tools/test.py --mode=release
+	python2 tools/test.py --mode=release
 
 test-debug: all
-	python tools/test.py --mode=debug
+	python2 tools/test.py --mode=debug
 
 test-message: all
-	python tools/test.py message
+	python2 tools/test.py message
 
 test-simple: all
-	python tools/test.py simple
+	python2 tools/test.py simple
 
 test-pummel: all
-	python tools/test.py pummel
+	python2 tools/test.py pummel
 
 test-internet: all
-	python tools/test.py internet
+	python2 tools/test.py internet
 
 test-npm: all
 	./node deps/npm/test/run.js
@@ -146,7 +146,7 @@
 check:
 	@tools/waf-light check
 
-VERSION=v$(shell python tools/getnodeversion.py)
+VERSION=v$(shell python2 tools/getnodeversion.py)
 TARNAME=node-$(VERSION)
 TARBALL=$(TARNAME).tar.gz
 PKG=out/$(TARNAME).pkg
@@ -194,10 +194,10 @@
 	./node benchmark/idle_clients.js &
 
 jslint:
-	PYTHONPATH=tools/closure_linter/ python tools/closure_linter/closure_linter/gjslint.py --unix_mode --strict --nojsdoc -r lib/ -r src/ -r test/
+	python2PATH=tools/closure_linter/ python2 tools/closure_linter/closure_linter/gjslint.py --unix_mode --strict --nojsdoc -r lib/ -r src/ -r test/
 
 cpplint:
-	@python tools/cpplint.py $(wildcard src/*.cc src/*.h src/*.c)
+	@python2 tools/cpplint.py $(wildcard src/*.cc src/*.h src/*.c)
 
 lint: jslint cpplint
 
