#!/bin/sh

_varname='G4REALSURFACEDATA'
_packagename='geant4-realsurfacedata'
_foldername='RealSurface'
_dataversion=1.0

post_install() {

echo "export ${_varname}=/usr/share/${_packagename}/${_foldername}${_dataversion}" >> /etc/profile.d/geant4.sh
echo "setenv ${_varname} /usr/share/${_packagename}/${_foldername}${_dataversion}" >> /etc/profile.d/geant4.csh

}

post_remove() {

sed -i "/${_varname}/d" /etc/profile.d/geant4.sh
sed -i "/${_varname}/d" /etc/profile.d/geant4.csh

}