post_install() {
	if [ ! -e "/usr/share/plymouth/halt.png" ]; then
		ln -s /usr/share/plymouth/splash.png /usr/share/plymouth/halt.png
	fi

	if [ ! -e "/usr/share/plymouth/poweroff.png" ]; then
                ln -s /usr/share/plymouth/splash.png /usr/share/plymouth/poweroff.png
        fi

	if [ ! -e "/usr/share/plymouth/reboot.png" ]; then
                ln -s /usr/share/plymouth/splash.png /usr/share/plymouth/reboot.png
        fi
}

post_upgrade() {
  post_install $1
}

