# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Alireza Savand <alireza.savand@gmail.com>

_gemname=soundcloud2000
pkgname=ruby-$_gemname
pkgver=0.1.0
pkgrel=1
pkgdesc='SoundCloud without the stupid css files'
arch=(any)
url='http://www.github.com/grobie/soundcloud2000'
license=('MIT')
depends=(ruby ruby-json ruby-audite ruby-curses)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('24226f3fcdc6848db292398d6ef756ef1b05bcf7')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
