# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=msgpack
pkgname=ruby-$_gemname-0.4
pkgver=0.4.7
pkgrel=1
pkgdesc='MessagePack, a binary-based efficient data interchange format.'
arch=(i686 x86_64)
url='http://msgpack.org/'
license=(Apache)
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('165ac164ea6b7df9abaa5c24e451e14ddb274a6c')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
