post_install() {
echo 'loadTest("spatial.js");'               >> /usr/share/couchdb/www/script/couch_tests.js
echo 'loadTest("list_spatial.js");'          >> /usr/share/couchdb/www/script/couch_tests.js
echo 'loadTest("etags_spatial.js");'         >> /usr/share/couchdb/www/script/couch_tests.js
echo 'loadTest("multiple_spatial_rows.js");' >> /usr/share/couchdb/www/script/couch_tests.js
echo 'loadTest("spatial_compaction.js");'    >> /usr/share/couchdb/www/script/couch_tests.js
echo 'loadTest("spatial_design_docs.js");'   >> /usr/share/couchdb/www/script/couch_tests.js
echo 'loadTest("spatial_bugfixes.js");'      >> /usr/share/couchdb/www/script/couch_tests.js
echo 'loadTest("spatial_offsets.js");'       >> /usr/share/couchdb/www/script/couch_tests.js
echo "Eight geospatial tests have been added to the end of /usr/share/couchdb/www/script/couch_tests.js."
echo "They should show up at the bottom of the list in 'Test Suite' in Futon."
}