post_install() {
echo "Installing indicator-specific icons..."
xdg-icon-resource install --theme hicolor --novendor --size 22 /usr/share/indicator-china-weather/data/media/icon_china_weather.png weather-indicator
xdg-icon-resource install --theme hicolor --novendor --size 22 /usr/share/indicator-china-weather/data/media/icon_unknown_condition.png weather-indicator-unknown
xdg-icon-resource install --theme hicolor --novendor --size 22 /usr/share/indicator-china-weather/data/media/icon_connection_error.png weather-indicator-error
glib-compile-schemas /usr/share/glib-2.0/schemas
}

post_upgrade() {
  post_install
}


