post_install() {
  echo "Updating module dependencies. Please wait..."
  depmod `uname -r` > /dev/null 2>&1
  echo ""
  echo ">>> Use modprobe or rc.conf to load nv50_thermal module."
  echo ">>> GPU temperature is written to file /sys/kernel/nv50/nv50_temp"
  echo ""
}

post_upgrade() {
  echo "Updating module dependencies. Please wait..."
  depmod `uname -r` > /dev/null 2>&1
}

post_remove() {
  post_upgrade
}
