post_install() {
    useradd -r -s /bin/sh -d /var/lib/btsync btsync
    mkdir -p /var/lib/btsync && chown -R btsync:btsync /var/lib/btsync

    echo -e "Configuration is located at /etc/btsync.conf and contains sample data"
    echo -e "The corresponding systemd-unit is 'btsync.service'"
    echo -e "WebGUI can be accessed at http://localhost:8888"
}

post_upgrade() {
    post_install
}

post_remove() {
  userdel btsync
}
