# This script just give the user some info

post_install() {
   echo ""
   echo "The program qguiconnect has been installed"
   echo "To use it you must provide a job number of a GUI"
   echo "program running over torque"
   echo "For an example xpra qsub script see"
   echo "/usr/share/qguiconnect/rstudio.pbs"
   echo ""
   echo "xpra must be installed on all nodes"
   echo ""
}

post_upgrade() {
  post_install
}
