#!/usr/bin/env sh

export WINEARCH='win32' WINEPREFIX="$HOME/.captvty/wine"

if [ ! -d "$HOME/.captvty" ]; then
  mkdir -p "$HOME/.captvty/wine"
  ln -s /usr/share/captvty/Captvty.exe "$HOME/.captvty/"
  ln -s /usr/share/captvty/Captvty.exe.config "$HOME/.captvty/"
  ln -s /usr/share/captvty/tools "$HOME/.captvty/tools"
  wineboot -u
  winetricks -q dotnet40 comctl32 ie8
  wine /usr/share/captvty/kb975337.exe /x:kb975337 /q
  wine /usr/share/captvty/fplayer.exe -install -au 2
fi

wine "$HOME/.captvty/Captvty.exe"

