post_install() {
   echo "If this is your first time installing snapraid an example"
   echo "config file can be found at /usr/share/snapraid/snapraid.conf.example."
   echo "For a quick start, simply copy the aforementioned file to /etc/snapraid.conf"
   echo "and change to fit your system. See http://snapraid.sourceforge.net/manual.html"
   echo "for more info. Additional docs can be found in /usr/share/docs/snapraid."
}
