# Maintainer: Juho Rutila <juho.rutila@iki.fi>
# Contributor: Jaroslav Lichtblau <dragonlord@aur.archlinux.org>
# Contributor: Travis Willard <travisw@wmpub.ca>
# Contributor: Hugo Ideler <hugoideler@dse.nl>

pkgname=openrpg
pkgver=1.8.0
pkgrel=2
pkgdesc="Online real-time RPG tabletop simulator allowing online play"
arch=('i686' 'x86_64')
url="http://www.openrpg.com/"
license=('GPL')
depends=('wxpython')
source=(http://www.assembla.com/spaces/$pkgname/documents/download/OpenRPG1.8.0.zip \
        $pkgname.desktop $pkgname.sh $pkgname-server.sh $pkgname-server-gui.sh \
        approot.py)
noextract=(OpenRPG1.8.0.zip)
md5sums=('19c28e107a568f71adb34aa2b27aabb8'
         '952a10285710acc840adb99ab8cf735d'
         '60cef4099ef99b6f12417cd931738314'
         '7a1848a8a38d449e58b998ead41774e3'
         'eff65dd2fd98d32b9502239a95877477'
         '7147087a6711cfa8e7d4b1c8ce419946')

build() {
  mkdir -p ${srcdir}/$pkgname || return 1
  cd ${srcdir}/$pkgname || return 1
  bsdtar -xf ${srcdir}/OpenRPG1.8.0.zip || return 1

# Python2
  find ${srcdir} -iname "*.py" | xargs sed -i -e '1s"^#!.* python$"#!/usr/bin/env python2"'

# Something with the wxwidget color != colour
  find ${srcdir}/openrpg/orpg -iname "*.py" | xargs sed -i -e 's"FNB_COLORFUL_TABS"FNB_COLOURFUL_TABS"g'

# Install files into /usr/bin 
  install -D -m755 ${srcdir}/$pkgname.sh ${pkgdir}/usr/bin/$pkgname || return 1
  install -D -m755 ${srcdir}/$pkgname-server.sh ${pkgdir}/usr/bin/$pkgname-server || return 1
  install -D -m755 ${srcdir}/$pkgname-server-gui.sh ${pkgdir}/usr/bin/$pkgname-server-gui || return 1

# Create installation DIR and install files to it
  install -d ${pkgdir}/usr/share/$pkgname || return 1
# Approot.py is attempted to be auto-generated by openRPG. Include it, so pacman knows about it.
  install -D -m644 ${srcdir}/approot.py ${pkgdir}/usr/share/$pkgname/orpg/dirpath/approot.py || return 1

# Install the rest
  cp -a * ${pkgdir}/usr/share/$pkgname || return 1 || return 1

# Pre-compile to .pyc - again, so pacman knows about it
  find ${pkgdir}/usr/share/$pkgname -type d -exec python2 -m compileall {} \; || return 1

# Finally, install .desktop file
  install -D -m644 ${srcdir}/$pkgname.desktop \
    ${pkgdir}/usr/share/applications/$pkgname.desktop || return 1
}
