# Maintainer: Moritz Fischer <moritz.fischer@student.kit.edu>
pkgname=gnuradio-funcube-git
pkgver=20110924
pkgrel=1
pkgdesc="Funcube Dongle source block for GNU Radio"
arch=('i686' 'x86_64')
license=('GPL')
depends=('fftw' 'python-numpy' 'boost' 'cppunit' 'swig' 'gsl' 'blas' 'guile' 'gnuradio' 'libusb')
makedepends=('git' 'libusb')
optdepends=('wxpython: gr-wxgui' 'python-cheetah: grc' 'python-lxml: grc' 'qwtplot3d: gr-qtgui' 'doxygen: docs autogenerated documentation' 'pyxml: grc', 'pygtk: grc' 'python-lxml: grc')
provides=('gnuradio')
url="http://gnuradio.org"
source=(10-funcube.rules)
md5sums=('dab3738ef111d97a09c088cbb72bbbb3')

_gitroot=https://github.com/csete/gr-fcd
_gitname=gr-fcd

build() {
	export PYTHON=python2
	cd ${srcdir}

	if [ -d $_gitname ]; then
		(cd $_gitname && git reset HEAD --hard && git clean -x -d -f && git pull origin)
		msg "Updated the local files."
	else
		git clone $_gitroot
		msg "GIT checkout done or server timeout"
	fi

	cd $_gitname

	msg "Starting build."
	git clean -x -f -d
	msg "Replacing filenames to use python2."
	sed -i -e "s|#![ ]*/usr/bin/env python$|#!/usr/bin/env python2|" $(find $srcdir -name '*.py')
	./bootstrap
	./configure --prefix=/usr --with-boost-libdir=/usr/lib
	make || return 1
}

package()
{
	mkdir -p ${pkgdir}/etc/udev/rules.d/
	cp 10-funcube.rules ${pkgdir}/etc/udev/rules.d/
	cd ${srcdir}/${_gitname}
	make DESTDIR=${pkgdir} install || return 1
}
