hyphen_dir=/usr/lib/python2.7/site-packages/hyphen

post_install() {
  echo ">>> No hyphenation dictionaries were installed."
  echo ">>> To make them available, run (as root):"
  echo ">>> # pyhyphen-setup.py"
  echo ">>>"  
  echo ">>> NOTE: All dictionaries will be removed upon uninstallation."
}

pre_remove() {
  echo "Removing all dictionaries..."
  rm -f ${hyphen_dir}/*.dic

  echo "Removing dictionary info..."
  rm -f ${hyphen_dir}/hyphen_dict_info.pickle
}
