# arg 1: the new package version
post_install() {
	if [ ! "`grep extension=sqlite3.so etc/php.ini`" ]; then
		echo -n "updating /etc/php.ini... "
		echo "extension=sqlite3.so" >>etc/php.ini
		echo "done."
	fi
}

# arg 1: the new package version
# arg 2: the old package version
post_upgrade() {
	post_install $1
}

# arg 1: the old package version
pre_remove() {
	echo -ne "\nupdating etc/php.ini... "
	sed -i -e '/extension=sqlite3.so/d' etc/php.ini
	echo "done."
}

op=$1
shift

$op $*
