# Maintainer: RubenKelevra <cyrond@gmail.com>

pkgname=rk-desktop-gnome-minimal
pkgver=2014.6.6
pkgrel=1
pkgdesc="Metapackage that installs a minimal gnome desktop. Enables all needed services."
url="http://notyetthere.com"
arch=('i686' 'x86_64')
license=('GPLv3')
install=rk-desktop-gnome-minimal.install
makedepends=("yaourt"
)
depends=("pkgtools"
"preload"
"openssl"
"net-tools"
"sudo"
"iproute2"
"yp-tools"
"dos2unix"
"python2"
"python3"
"wget"
"ntp"
"acpid"
"dbus"
"avahi"
"abs"
"p7zip"
"zip"
"unrar"
"openssh"
"pm-utils"
"traceroute"
"pkgfile"
"hdparm"
"ethtool"
"sdparm"
"dosfstools"
"haveged"
"nmap"
"iperf"
"hping"
"sysstat"
"iotop"
"tcpdump"
"mausezahn"
"htop"
"lsof"
"dnssec-anchors"
"ldns"
"screen"
"curl"
"bedup"
"unrar"
"ntfs-3g"
"dosfstools"
"btrfs-progs"
"git"
"help2man"
"subversion"
"f2fs-tools"
"sshfs"
"imagemagick"
"ghostscript"
"crda"
"bzr"
"cvs"
"iftop"
"cacert-dot-org"
"mtr"
"dnsutils"
"socat"

"gdm"
"baobab"
"eog"
"evince"
"gnome-backgrounds"
"gnome-calculator"
"gnome-control-center"
"gnome-desktop"
"gnome-dictionary"
"gnome-disk-utility"
"gnome-font-viewer"
"gnome-icon-theme"
"gnome-icon-theme-extras"
"gnome-icon-theme-symbolic"
"gnome-keyring"
"gnome-screenshot"
"gnome-session"
"gnome-settings-daemon"
"gnome-shell"
"gnome-shell-extensions"
"gnome-system-log"
"gnome-system-monitor"
"gnome-terminal"
"gnome-themes-standard"
#"gnome-user-docs"
#"gnome-user-share"
"gucharmap"
"mousetweaks"
"mutter"
"sushi"
"tracker"
"xdg-user-dirs-gtk"
"yelp"

"file-roller"
"gnome-color-manager"
"gnome-nettool"
"seahorse"
"rygel"
"vinagre"
"gnome-vfs"
"gnome-power-manager"
"gksu"
"gnome-tweak-tool"
"polkit-gnome"
"p7zip"
"usb_modeswitch"

"kdesdk-kate"
"nemo"
"nemo-fileroller"

"xorg-xprop"
"xorg-xinit"
"xorg-utils"
"xorg-server-utils"
#"xorg-drivers"
"xf86-input-evdev"
"xf86-input-joystick"
"xf86-input-keyboard"
"xf86-input-mouse"
"xf86-input-synaptics"
"xf86-input-vmmouse"
"xf86-input-void"
"xf86-video-ark"
"xf86-video-ast"
"xf86-video-ati"
"xf86-video-cirrus"
"xf86-video-dummy"
"xf86-video-fbdev"
"xf86-video-glint"
"xf86-video-i128"
"xf86-video-intel"
"xf86-video-mach64"
"xf86-video-mga"
"xf86-video-modesetting"
"xf86-video-neomagic"
"xf86-video-nouveau"
"xf86-video-nv"
"xf86-video-openchrome"
"xf86-video-r128"
"xf86-video-savage"
"xf86-video-siliconmotion"
"xf86-video-sis"
"xf86-video-tdfx"
"xf86-video-trident"
"xf86-video-v4l"
"xf86-video-vesa"
"xf86-video-vmware"
"xf86-video-voodoo"
"numlockx"
"ntfs-3g"
"wpa_supplicant"
"libva-intel-driver"
)
conflicts=(
"rk-server-basic"
"rk-desktop-kde"
"rk-desktop-gnome"
"rk-gnome-desktop-native"
)
provides=("rk-desktop")
optdepends=(
"rk-desktop-gnome: A full Gnome-Desktop"
"rk-desktop-gnome-games: All the nice gnome mini-games"
"rk-desktop-gnome-removegames: Remove all gnome mini-games"
"rk-desktop-apps: The most-used desktop apps"
"rk-desktop-gnome-removenative: if you want to remove some useless native-gnome apps"
"rk-desktop-gnome-accessibility: All the nice gnome accessibility apps"
"rk-desktop-gnome-removeaccessibility: Remove all accessibility apps"
"rk-print: Everything for printer"
"rk-bluetooth: Everything for bluetooth"
"rk-desktop-favapps: Authors personal app-list"
)
