#!/bin/sh

RYZOM_GAMEDATA_DIR='/var/games/ryzom_data'
RYZOM_UPDATE_URL='www.ryzom.com::ryzom/data'
###############################

cd "$RYZOM_GAMEDATA_DIR"

if groups | grep games > /dev/null 2>&1 ; then 
  rsync -rtzvu --progress --stats --recursive --timeout=30 "$RYZOM_UPDATE_URL" ./ > /dev/null 2>&1 
else 
  echo "you need to be in games group to do this"
  exit 1
fi
