# Maintainer: Evan Teitelman <teitelmanevan at gmail dot com>

pkgname=python-everything
pkgver=1.1
pkgrel=1
pkgdesc="Includes all of the Python packages in the official repos"
arch=(x86_64 i686)
url="https://github.com/EvanTeitelman/pkgbuilds"
license=('custom')
depends=(python-atspi
python-beaker
python-cairo
python-chardet
python-crypto
python-cssselect
python-dbus
python-dbus-common
python-distribute
python-django
python-feedparser
python-gobject
python-gobject2
python-logilab-astng
python-logilab-common
python-lxml
python-lxml-docs
python-mako
python-markupsafe
python-nose
python-nose-doc
python-numpy
python-opengl
python-pip
python-pyasn1
python-pyelftools
python-pylint
python-pyopenssl
python-pyqt4
python-qscintilla
python-qscintilla-common
python-sgmllib
python-sip
python-urwid
python-virtualenv
python-xdg
python-zope-interface
python-basemap
python-basemap-common
python-beautifulsoup4
python-bottle
python-bsddb
python-cchardet
python-cherrypy
python-cssutils
python-cx_freeze
python-dateutil
python-decorator
python-distutils-extra
python-dnspython
python-docs
python-docutils
python-gtkspellcheck
python-httplib2
python-ipaddr
python-irc
python-isodate
python-jinja
python-markdown
python-matplotlib
python-mpi4py
python-numexpr
python-oauthlib
python-openbabel
python-progressbar
python-psutil
python-psycopg2
python-pybox2d
python-pycuda
python-pyenchant
python-pygit2
python-pygments
python-pyinotify
python-pymongo
python-pyopencl
python-pyparsing
python-pyproj
python-pyquery
python-pyro
python-pyserial
python-pytables
python-pytools
python-pytz
python-pyudev
python-pyxattr
python-pyzmq
python-requests
python-rsa
python-scipy
python-sfml
python-sh
python-simplejson
python-six
python-south
python-sphinx
python-sqlalchemy
python-stevedore
python-sympy
python-termcolor
python-tornado
python-virtkey
python-virtualenv-clone
python-virtualenvwrapper
python-xlib
python-yaml)

package() {
  :
}
