post_install() {
  for variant in elementary-xfce{,-dark{,er,est}}; do
    if [[ -d "usr/share/icons/${variant}" ]]; then
      gtk-update-icon-cache -q -t -f "usr/share/icons/${variant}"
    fi
  done
}

post_upgrade() {
  post_install
}

post_remove() {
	post_install
}

pre_remove() {
  for variant in elementary-xfce{,-dark{,er,est}}; do
    rm "usr/share/icons/${variant}/icon-theme.cache"
  done
}
# vim:set ts=2 sw=2 et:
