post_install() {
	if [[ -d usr/share/icons/elementary-xfce ]]; then
		gtk-update-icon-cache -q -t -f usr/share/icons/elementary-xfce
	fi
	if [[ -d usr/share/icons/elementary-xfce-dark ]]; then
		gtk-update-icon-cache -q -t -f usr/share/icons/elementary-xfce-dark
	fi
	if [[ -d usr/share/icons/elementary-xfce-darker ]]; then
		gtk-update-icon-cache -q -t -f usr/share/icons/elementary-xfce-darker
	fi
}

post_upgrade() {
  post_install
}

post_remove() {
	post_install
}

pre_remove() {
	rm usr/share/icons/elementary-xfce/icon-theme.cache
	rm usr/share/icons/elementary-xfce-dark/icon-theme.cache
	rm usr/share/icons/elementary-xfce-darker/icon-theme.cache
}
# vim:set ts=2 sw=2 et:
