## arg 1:  the new package version
post_install() {
	echo
	echo "===[ NOTE ]==="
	echo "This package ships the version $1 of the premake project. This version is completely different from previous (i.e. script syntax, command line options, executable name). This package doesn't conflicts with the premake package (currently, 03 Sep 2009, at version 3.7) so you can keep both installed."
	echo
	echo "To access the help builtin:"
	echo "    premake4 --help"
	echo
}
