JKSH="/usr/sbin/jk_chrootsh"
SHELLS="/etc/shells"

post_install() {
  if ! grep -q "$JKSH" "$SHELLS" >/dev/null; then
    echo "Appending $JKSH to $SHELLS"
    echo "$JKSH" >> "$SHELLS"
  fi
}

pre_remove() {
  if grep -q "$JKSH" "$SHELLS" >/dev/null; then
    echo "Removing $JKSH from $SHELLS"
    TMP="$(mktemp)"
    grep -v "$JKSH" "$SHELLS" > "$TMP"
    install -m 644 -o 0 -g 0 "$TMP" "$SHELLS"
    rm "$TMP"
  fi
}
