# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Matanya Moses <matanya@foss.co.il>

_gemname=aurb
pkgname=ruby-$_gemname
pkgver=1.4.1
pkgrel=1
pkgdesc='An AUR (Arch User Repository) utility'
arch=(any)
url='http://github.com/gigamo/aurb'
license=(custom)
depends=(ruby ruby-yajl-ruby ruby-thor ruby-archive-tar-minitar)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('3608d0be09df43c31aea45efdaa00adca2d04610')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
