#!/usr/bin/env bash

# Provide a basic --help/--version output, since the program itself does not.
_vgmplay_help() {
	printf "Usage: vgmplay file\n"
	printf "Plays VGM, VGZ, CMF, and DRO files either singly or by m3u playlist.\n"
	printf "\n"
	printf "Options:\n"
	printf " -h, -?, --help:            Display this help and exit.\n"
	printf "         --version:         Display version and exit.\n"
	printf "\n"
	printf "Keys (In-Player):\n"
	printf " Cursor Left/Right:         Seek 5 seconds backward/forward\n"
	printf " Ctrl + Cursor Left/Right:  Seek 1 minute backward/forward\n"
	printf " Space:                     Pause\n"
	printf " Esc twice:                 Quit Program\n"
	printf " F:                         Fade Out\n"
	printf " R:                         Restart Current Track\n"
	printf " PageUp/B:                  Previous Track (in playlist)\n"
	printf " PageDown/N:                Next Track (in playlist)\n"
}

# Display help if no options or input files specified.
if (( $# == 0 )); then
	printf "No input file specified.\n\n"
	_vgmplay_help
	exit 64
fi

# VGMPlay requires VGMPlay.ini to be in the current working directory.
#  This keeps track of the actual current working directory for use in
#  command invocation then changes to a 'fake' working directory.
_cwd="$PWD"
cd "$XDG_CONFIG_HOME/vgmplay"

case "$1" in
	-h | -? | --help )
		_vgmplay_help
		exit 0 ;;
	--version )
		printf "VGMPlay Version 2012-11-11, supporting VGM 1.61\n"
		exit 0 ;;
	/* | ~* ) # Absolute path specified: clear _cwd
		_cwd="" ;;
	* )
		;;
esac

# Sets the window title to "VGMPlay" if $TERM has xterm or rxvt - not much,
#  but it helps a bit.
case $TERM in
	xterm* | rxvt* )
		echo -e "\e]2;VGM Player\007" ;;
	* )
		;;
esac

# Checks for the presence of pulseaudio and/or ALSA's aoss wrapper and selects
#  which to use as appropriate.
pulseaudio --check &>/dev/null

if (( $? == 0 )); then
	/usr/bin/padsp /usr/bin/VGMPlay "$_cwd/$@"
elif [[ -e /usr/bin/aoss ]]; then
	/usr/bin/aoss /usr/bin/VGMPlay "$_cwd/$@"
else
	/usr/bin/VGMPlay "$_cwd/$@"
fi

unset _vgmplay_help
unset _cwd
