# Generated by gem2arch
# Maintainer: LeeF

_gemname=file-tail
pkgname=ruby-enterprise-$_gemname
pkgver=1.0.5
pkgrel=0
pkgdesc="File::Tail for Ruby"
arch=('i686' 'x86_64')
url="http://flori.github.com/file-tail"
license=('GPL')
depends=('ruby-enterprise' 'ruby-enterprise-spruz>=0.1.0')
makedepends=('ruby-enterprise')
source=(http://gems.rubyforge.org/gems/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
md5sums=('409f4b5868a747e8f89939eaf9970e81')

build() {
  cd $srcdir
  local _gemdir=`ruby -rubygems -e'puts Gem.default_dir'`
  gem install --ignore-dependencies --no-rdoc --no-ri  -i "$pkgdir$_gemdir" $_gemname-$pkgver.gem
}
