#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

# set Tomcat's variables
[ -f /etc/conf.d/tomcat ] && . /etc/conf.d/tomcat

case "$1" in
    start)
	stat_busy "Starting Tomcat"

	tomcat_prev_umask=`umask`
	umask 006
	$CATALINA_HOME/bin/tomcat \
	    -user $TOMCAT_USER \
	    -home $JAVA_HOME \
	    -Dcatalina.home=$CATALINA_HOME \
	    -Dcatalina.base=$CATALINA_BASE \
	    -Djava.io.tmpdir=$CATALINA_TMP \
	    -wait 10 \
	    -pidfile $CATALINA_PID \
	    -outfile $CATALINA_LOG/catalina.log \
	    -errfile '&1' \
	    $CATALINA_OPTS \
	    -cp $CLASSPATH \
	    org.apache.catalina.startup.Bootstrap
	umask $tomcat_prev_umask
	unset tomcat_prev_umask

	if [ $? -gt 0 ]; then
	    stat_fail
	else
	    add_daemon tomcat
	    stat_done
	fi
	;;
    stop)
	stat_busy "Stopping Tomcat"
	    $CATALINA_HOME/bin/tomcat \
		-stop \
		-pidfile $CATALINA_PID \
		org.apache.catalina.startup.Bootstrap

	    if [ $? -gt 0 ]; then
		stat_fail
	    else
		rm_daemon tomcat
		stat_done
	    fi
	    ;;
    restart)
	$0 stop
	sleep 1
	$0 start
	;;
    *)
	echo "usage: $0 {start|stop|restart}"
esac
exit 0


