post_install() {
	echo ">>> This package only provides a library to interact with the MFD+LEDs and the example program x52output."
	echo ">>> To gain mode/shift functionality, install stickshift-git from the AUR."
}

post_upgrade() {
	echo ">>> This package only provides a library to interact with the MFD+LEDs and the example program x52output."
	echo ">>> To gain mode/shift functionality, install stickshift-git from the AUR."
}
