post_install() {
  echo "NOTICE: This is for apache httpd 2.2.x and this module is
                already enabled in httpd 2.4.x by default."
  echo ">> Add the following lines to /etc/httpd/conf/httpd.conf"
  echo "   LoadModule remoteip_module modules/mod_remoteip.so"
  echo "   RemoteIPHeader X-Forwarded-For"
  echo "   RemoteIPInternalProxy 127.0.0.1"
  echo ""
  echo ">> Don't forget to restart apache: systemctl restart httpd"
}
