# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=actionpack
pkgname=ruby-$_gemname-4.2.0.beta2
pkgver=4.2.0.beta2
pkgrel=1
pkgdesc='Web-flow and rendering framework putting the VC in MVC (part of Rails).'
arch=(any)
url='http://www.rubyonrails.org'
license=(MIT)
depends=(ruby ruby-activesupport-4.2.0.beta2 ruby-rack-1.6.0.beta ruby-rack-test ruby-rails-html-sanitizer ruby-rails-dom-testing ruby-actionview-4.2.0.beta2)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('ca15d12a2c8ba37a8e7d249df864f8a1ae68d8cc')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/MIT-LICENSE" "$pkgdir/usr/share/licenses/$pkgname/MIT-LICENSE"
}
