#!/bin/bash

HOST_DIR="${0%/*}"
if [[ "${LD_LIBRARY_PATH+set}" = "set" ]] ; then                                                                   
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:HOST_DIR"                                                       
else                                                                                                             
    export LD_LIBRARY_PATH="$HOST_DIR"                                                                           
fi

exec -a "$0" "$HOST_DIR/CoherentUI_Host.bin" "$@"
