pkgname=test_server

_service_user=$pkgname
_service_group=$pkgname
_admin_group="${pkgname}_admin"

_data_dir=/var/${pkgname}/data
_log_dir=/var/log/${pkgname}
_cache_dir=/var/cache/${pkgname}
_sass_cache_directory=$_cache_dir
_database_dir=${_data_dir}/db
_files_dir=${_data_dir}/files
_config_dir=/etc/${pkgname}
_database_configuration_file=${_config_dir}/database.yml
_secrets_file=${_config_dir}/secrets.yml

post_install() {
  if ! getent group $_admin_group >/dev/null; then
    groupadd $_admin_group
  fi

  if ! getent passwd $_service_user >/dev/null; then
    useradd -m $_service_user
  fi

  for path in $_log_dir $_sass_cache_directory $_data_dir $_database_dir $_files_dir; do
    chown -R $_service_user:$_service_group $path
  done

  # Admins are allowed to write, service is allowd to read, others can do nothing
  chown :$_admin_group $_files_dir 
  setfacl -m g:$_service_group:rx $_files_dir

  # Allow the web application to read database configuration file
  chown :$_service_group $_database_configuration_file 

  # Allow the web application to read secrets file
  chown :$_service_group $_secrets_file 
  
  # Create run directories
  systemd-tmpfiles --create

  echo ""
  echo "Please place a config file at one of the following places:"
  echo ""
  echo " * $HOME/.config/test_server/config.yaml"
  echo " * $HOME/.test_server/config.yaml"
  echo " * /etc/test_server/config.yaml"
  echo ""
  echo "The package contains a \"config.yaml\" which has been placed at /etc/test_server/config.yaml during package install. Feel free to modify it."
  echo ""
  echo "Make sure you add your admins to the admin group \"$_admin_group\" to enable those to upload files used for testing via scp."
  echo ""
}

post_upgrade() {
  post_install
}

pre_remove() {
  systemctl stop $pkgname
  systemctl disable $pkgname
}

post_remove() {
  echo ""
  echo "Please remove the home directory of the service user ${_service_user} yourself."
  echo ""

  if ! getent group $_admin_group >dev/null; then
    groupdel $_admin_group
  fi

  if ! getent group $_service_group >/dev/null; then
    groupdel $_service_group
  fi

  if ! getent passwd $_service_user >/dev/null; then
    userdel $_service_user
  fi

  # Delete run directories
  systemd-tmpfiles --clean
}
