#!/usr/bin/env bash

post_install() {
cat <<-'!'
  1. Copy /usr/lib/gummiboot/gummiboot.efi to the EFI system partition;
       (e.g. /boot/efi/EFI/arch/gummiboot.efi)
  2. Add Gummiboot to the EFI boot menu:
       efibootmgr -c -l '\EFI\arch\gummiboot.efi' -L "Arch Linux"
!
}

post_upgrade() {
cat <<-'!'
  Remember to copy the new gummiboot.efi to your EFI system partition.
!
}

# vim:set ts=2 sw=2 et:
