# Generated by Xyne::Arch::CPAN 0.07

pkgname=perl-dublincore-record
pkgver=0.03
pkgrel=1
pkgdesc="Container for Dublin Core metadata elements"
arch=('i686' 'x86_64')
url="http://search.cpan.org/dist/DublinCore-Record/"
license=('PerlArtistic' 'GPL')
source=('http://search.cpan.org/CPAN/authors/id/B/BR/BRICAS/DublinCore-Record-0.03.tar.gz')
md5sums=('51354acc8ed6655f7ab901d358b0e15b')
sha256sums=('5924d85b601779bd82cd3beae5b480810b2391a7aec28a692fed5a1cfbadc19c')
depends=('perl-class-accessor')
provides=('perl-dublincore-element=0.03')
options=(!emptydirs)

build() {
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Makefile.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor || return 1
    make  || return 1
    make install DESTDIR="${pkgdir}" || return 1

  else
  _dir=$(find $srcdir -maxdepth 2 -type f -name 'Build.PL')
  if [ ! -z "$_dir" ]; then
    cd $(dirname "$_dir")
    PERL_MM_USE_DEFAULT=1 perl Build.PL INSTALLDIRS=vendor || return 1
    ./Build  || return 1
    ./Build install destdir=${pkgdir} || return 1

  else
    echo "error: failed to detect build method for $pkgname"
    echo "you may be able to fix this by editing the PKGBUILD"
    return 1
  fi fi

  # remove perllocal.pod and .packlist
  find ${pkgdir} -name perllocal.pod -delete
  find ${pkgdir} -name .packlist -delete
}

# vim:set ts=2 sw=2 et:

