pre_install() {
    cat <<EOF
>>> PACKAGE NOTES
>>> --------------
>>> This is a modded launcher for playing Minecraft with the Feed the Beast ModPacks.
>>> You need a valid Minecraft account to play it.
>>> --------------
EOF
}
post_install() {
    update-desktop-database -q
    gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_upgrade() {
    post_install
}

post_remove() {
    post_install
}
