# This is a default template for a post-install scriptlet.
# Uncomment only required functions and remove any functions
# you don't need (and this header).

## arg 1:  the new package version
post_install() {
    echo ">>> PACKAGES NOTES"
    echo ">>> --------------"
    echo ">>> This is a modded launcher for playing Feed the Beast ModPacks, you need a valid account to play it."
    echo ">>> --------------"
}

# vim:set ts=2 sw=2 et:

