signa(){
    #get rid of Testing use only watermark
    echo "9777c589791007f4aeef06c922ad54a2:ae59f5b9572136d99fdd36f0109d358fa643f2bd4a2644d9efbb4fe91a9f6590a145:f612f0b01f2565cd9bd834f8119b309bae11a1ed4a2661c49fdf3fad11986cc4f641f1ba1f2265909a8e34ff1699309bf211a7eb4d7662cd9f8e3faf14986d92f646f1bc" > etc/ati/signature
}


whisperer(){
    echo "----------------------------------------------------------------"
    echo "PLEASE NOTE:"
    echo "For these drivers to work, you must install kernel modules."
    echo "Depending on your kernel, these module packages are named"
    echo "catalyst-\$kernel and stock kernel module is catalyst"
    echo ""
    echo "OR simply use packages that provides auto re-compilation:"
    echo "catalyst-hook or catalyst-daemon"
    echo ""
    echo "OR use catalyst-generator package to generate catalyst-{kernver}"
    echo "packages"
    echo "----------------------------------------------------------------"
    echo "You can use the tool 'aticonfig' to generate an xorg.conf file."
    echo "--------------------- ^^^^^^^^^ --------------------------------"
    echo "Add nomodeset to your kernel line in /boot/grub/menu.lst , ie.:"
    echo "kernel /boot/vmlinuz-linux root=/dev/sda1 ro nomodeset"
    echo "----------------------------------------------------------------"
    echo "IMPORTANT:"
    echo "fglrx was added into /etc/modules-load.d/catalyst.conf"
    echo "----------------------------------------------------------------"
    echo "	atieventsd (needs acpid pkg) on systemd:"
    echo "systemctl enable atieventsd"
    echo "systemctl start atieventsd"
    echo "----------------------------------------------------------------"
    echo "For more info and troubleshooting visit:"
    echo "http://wiki.archlinux.org/index.php/ATI_Catalyst"
    echo "----------------------------------------------------------------"
}

check_libdri_so(){
    if [ ! -e usr/lib/xorg/modules/extensions/libdri.so ]; then
        ln -sf usr/lib/xorg/modules/extensions/libdri.xorg usr/lib/xorg/modules/extensions/libdri.so
    fi
}


post_install(){
    check_libdri_so
    whisperer
    signa
}

post_upgrade(){
    check_libdri_so
    whisperer
    signa
}

post_remove(){
    # If the symlink is dead, remove it
     check_libdri_so
     echo "NOTE: Don't forget to recover your original xorg.conf file."
}
