--- old/Makefile	2010-10-26 22:39:38.232927591 +0200
+++ new/Makefile	2010-10-26 22:48:10.982927591 +0200
@@ -9,8 +9,8 @@
 LIBS=-ltiff -lpng -ljpeg -lm $(SDL) 
 
 setup: clean
-	python setup.py build
-	sudo python setup.py install
+	python2 setup.py build
+	python2 setup.py install --prefix $(PREFIX)
 
 all: _iulib.so _ocropus.so
 
