# Generated by gem2arch
# Maintainer: Reuben Castelino <projectdelphai at gmail dot com>

_gemname=multi_xml
pkgname=ruby-$_gemname
pkgver=0.5.5
pkgrel=1
pkgdesc="A generic swappable back-end for XML parsing"
arch=('any')
url="https://github.com/sferik/multi_xml"
license=('GPL')
depends=('ruby')
makedepends=('rubygems')
source=(http://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
md5sums=('afecb8240f7a14a9183d79f8df5bfa3f')
sha1sums=('391ebaa97148268cb35fa3320bd098585f7e44dc')

package() {
  cd "$srcdir"
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
}
