post_install() {
	cp /usr/lib/syslinux/memdisk /boot/
	
	echo "------------------------------------------------------------"
	echo "> Place your favourite grml iso image(s) in /boot/grml/"
	echo "> To have them added to grub automatically, run"
	echo "> grub-mkconfig -o /boot/grub/grub.cfg"
	echo "------------------------------------------------------------"
}

post_upgrade() {
	post_install
}

post_remove() {
	rm /boot/memdisk
	grub-mkconfig -o /boot/grub/grub.cfg

	echo "------------------------------------------------------------"
	echo "> You may want to remove your grml images in /boot/grml/"
	echo "------------------------------------------------------------"
}

# vim:set ts=2 sw=2 et:
